### ISSUE TITLE
Ignite Developer screen's "Plugin Examples" breaking.

### ISSUE THREAD

**Issue by ckalpit** [infinitered/ignite#1001]
### When clicking on "plugin examples" button in ignite's developer screen here 

<img width="378" alt="screen shot 2017-04-28 at 9 59 23 am" src="https://cloud.githubusercontent.com/assets/6360351/25514558/8001ae10-2bfb-11e7-8ab0-ba24d5bacc8d.png">

then it throws this error 
Objects are not valid as react child ….
-see this screen shot

<img width="375" alt="screen shot 2017-04-28 at 9 58 41 am" src="https://cloud.githubusercontent.com/assets/6360351/25514571/91295bc0-2bfb-11e7-857e-e78272595214.png">

**Comment by ruddell** [comment]
This has something to do with react-navigation in PluginExamplesScreen.  To work around it until a solution is found, you can remove `navigationOptions` from the below section
```

export default StackNavigator({
  PluginExamplesScreen: {screen: PluginExamplesScreen}
}, {
  headerMode: 'screen',
  initialRouteName: 'PluginExamplesScreen',
  navigationOptions: {
    header: {
      visible: false,
      style: {
        backgroundColor: '#3e243f'
      }
    }
  }
})
```

**Comment by GantMan** [comment]
Woah now. Perhaps this is due to a specific version of react-native navigation.  I'll get to the bottom of this today.

**Comment by GantMan** [comment]
Due to updates this needs to be switched to:

```js
export default StackNavigator({
  PluginExamplesScreen: {screen: PluginExamplesScreen}
}, {
  initialRouteName: 'PluginExamplesScreen',
  headerMode: 'none',
})
```

We'll ship a PR and new build today.  Ideally, we should lock react-navigation version so API changes don't kill us.

**Comment by GantMan** [comment]
Fixed via https://github.com/infinitered/ignite/pull/1005
