### ISSUE TITLE
Not able to use jhipster boilerplate.

### ISSUE THREAD

**Issue by ckalpit** [infinitered/ignite#1002]
### While using jhipster as boilerplate it is not getting installed.

I have used this command to install that boilerplate

`ignite new ignite_with_jhipster -b jhipster`

and it seems that the boilerplate is selected 

<img width="648" alt="screen shot 2017-04-28 at 10 18 19 am" src="https://cloud.githubusercontent.com/assets/6360351/25514655/1c267172-2bfc-11e7-85db-89a3aac6af73.png">

but, when it actually trying to install the same dependancy  it skips and uses `ignite-ir-boilerplate-2016`

as shown in screen shot, `ignite_with_jhipster/node_modules/ignite-jhipster/plugin.js does not exist.  skipping.` 

<img width="1199" alt="screen shot 2017-04-28 at 10 20 52 am" src="https://cloud.githubusercontent.com/assets/6360351/25514717/68dd54f4-2bfc-11e7-9aa3-2955f702e2c8.png">

**Comment by ruddell** [comment]
@ckalpit Hey I'm the author of the JHipster boilerplate.  When I generate an app I see everything as expected, the home screen's logo/theme is different so I can tell it worked.

My boilerplate adds ignite-ir-boilerplate-2016 to get access to the screen, redux, saga, and other generators so that is what you are seeing in the logs.  The message about plugin.js is just a warning.

**Comment by ckalpit** [comment]
But there its written that `skipping` thats why I have reported this.

**Comment by ckalpit** [comment]
Yes, it seems that it is different boilerplate.
By the way, since your boilerplate is extending `ignite-ir-boilerplate-2016` your boiler plate also throws same error as I have reported here https://github.com/infinitered/ignite/issues/1001
can you look into it?

**Comment by GantMan** [comment]
The fix will be shipped today.

**Comment by GantMan** [comment]
https://github.com/infinitered/ignite/pull/1005

**Comment by GantMan** [comment]
fix for existing stuff, but this is fixed for all future stuff.
