### ISSUE TITLE
Not able to install Native Base Boilerplate 

### ISSUE THREAD

**Issue by ckalpit** [infinitered/ignite#1003]
###When trying to install ignite with native base boilerplate using following command

`ignite new ignite_with_nbase -b ignite-native-base-boilerplate`
it is not even selecting native base boilerplate 

 
<img width="866" alt="screen shot 2017-04-28 at 10 28 09 am" src="https://cloud.githubusercontent.com/assets/6360351/25514845/6b3fd31a-2bfd-11e7-8bac-9a51f4f8d228.png">

**Comment by ruddell** [comment]
This has been fixed in the boilerplate (https://github.com/GeekyAnts/ignite-native-base-boilerplate/pull/1) but the fix hasn't been released.  

Did you try running the app?  It should work as the only change was which name is displayed

**Comment by ckalpit** [comment]
Okay, I have not tried to run the app, let me try that too.

**Comment by vesper8** [comment]
@ruddell erm I'm confused by this because I just ran into the same problem, but then when I look inside my package.json it does in fact list
```
"ignite-ir-boilerplate-2016": "^0.2.3",
```

So it's not just the name that's wrong.. it's installing the wrong bp.. or am I missing something?

I ran this on 2.0.0-rc.1
```
ignite new NativeBaseBp --boilerplate native-base-boilerplate
```

and got

```
ignite new NativeBaseBp --boilerplate native-base-boilerplate
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app NativeBaseBp
✔ using the Infinite Red 2016 boilerplate
💩  unspecified react native version in ignite cli has been deprecated
   please use version property in project's boilerplate file to set a react native version
   falling back to react native version: 0.42.0
```

**Comment by ruddell** [comment]
@vesper8 That comes from https://github.com/GeekyAnts/ignite-native-base-boilerplate/blob/master/boilerplate.js#L205, that line enables the Native Base boilerplate to use the regular boilerplate's generators (Screen, Container, Redux, Saga, etc)

Like I said above, if you run the app it works.
