### ISSUE TITLE
Encourage Users To Specify Versions When Using `ignite.addModule`

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#1006]
Deprecation warning:
`ignite.addModule` should require version number.  Unless `yolo: true`

### Update Docs
https://github.com/infinitered/ignite/blob/master/docs/advanced-guides/creating-plugins.md#edit-the-pluginjs

**Comment by jamonholmgren** [comment]
@GantMan Can you explain further what you mean here?

**Comment by GantMan** [comment]
ah yes, sorry.

So `addModule` is willy nilly about the version number.   So whatever code you wrote, could be defunct if the module has any major breaking changes!!!!   Not specifying a version number on the module is pretty careless.  SO, we should enforce version numbers!!!   

This ticket is asking for a deprecation warning on any line of code that uses this without a version being passed in.

Now, if a person feels they should NOT put a version number because they like to live life fast and crazy, we require `yolo: true` to supress the warning.   But it's highly recommended that every module added is the specific version that has been tested.

**Comment by skellock** [comment]
We could place a warning if [version is not detected](https://github.com/infinitered/ignite/blob/master/src/extensions/ignite/addModule.js#L16).

Updating [the plugin template] would be another nice touch.

**Comment by jamonholmgren** [comment]
Thanks for the additional context, @GantMan. Good thoughts @skellock .
