### ISSUE TITLE
Ignite requires yarn even if yarn is installed correctly

### ISSUE THREAD

**Issue by BetaConnector** [infinitered/ignite#1007]
Hey There... I have installed yarn - yarn - v shows me:
F:\>yarn -v
yarn install v0.23.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.12s.

I am trying to create a new App with ignite but it shows me the following error:
F:\>ignite new TestApp
Ignite requires yarn >=0.21.0 to be installed.

See https://yarnpkg.com/en/docs/install on how to upgrade for your OS.

What is going wrong? Hope you can help me :)

Thanks in advance - Alex

**Comment by andrei-livadariu** [comment]
This has been giving me some trouble today, and I think I narrowed down the issue to [this line of code.](https://github.com/infinitered/ignite/blob/d69f2ce3b373142a1d32b1101bfd3786cd054ae6/packages/ignite-cli/src/cli/enforceGlobalDependency.js#L83)

I ran `which yarn` on my computer and got `C:\Program Files (x86)\Yarn\bin\yarn.CMD`. Note the space in the path. Ignite is essentially running the command `which C:\Program Files (x86)\Yarn\bin\yarn.CMD` which fails, because it should be `which "C:\Program Files (x86)\Yarn\bin\yarn.CMD"` instead.

I changed the code locally to test this out, and this line seems to work:
`var result = shell.exec('"' + resolvedPath + '" ' + versionCommand, { silent: true })`

**Comment by BetaConnector** [comment]
Works fine - thanks alot :)

**Comment by mwarger** [comment]
@andrei-livadariu - Where did you change that line of code?  I'm bit by this bug as well.

**Comment by Slapbox** [comment]
Does not resolve the issue for me unfortunately.

**Comment by GantMan** [comment]
@andrei-livadariu - do you want to do a PR?

**Comment by andrei-livadariu** [comment]
I wouldn't go that far :) The solution I used is just a quick hack which hasn't been tested on Linux, Mac, or any other Windows configuration. I think I would rather let someone more experienced take care of this.

**Comment by yusufofaibrid** [comment]
works for me ... @andrei-livadariu  thanks a lot

**Comment by jamonholmgren** [comment]
@andrei-livadariu Oops, that's my change. :/ I'll try to get this fixed soon.

**Comment by jamonholmgren** [comment]
Actually, I'm going to ask @kevinvangelder, our resident Windows expert, to tackle this.

**Comment by skellock** [comment]
The react-native packager uses `shell-quote` for this.

**Comment by harry-g** [comment]
An easy workaround is to install yarn (.msi) to a dir w/o spaces, e.g.
`c:\Tools\yarn` works fine for me.
Still this issue might confuse/discourage new users under Windows.
Would be great if you fix it!

**Comment by GantMan** [comment]
We have a PR, would love to help someone test it!  Or @kevinvangelder - can you verify your PR works?   Should only take seconds.

**Comment by harry-g** [comment]
PR verified OK under Windows 10!
Details [see PR 1010](https://github.com/infinitered/ignite/pull/1010)

**Comment by marsonmao** [comment]
Is this fixed in 2.0.0-beta.9?
I installed ignite by 'npm install -g ignite-cli', installed yarn by 'choco install yarn', all done in 30 mins from now and still having this issue.
And my yarn is installed in that x86 folder too.

**Comment by marsonmao** [comment]
Alright, seems not fixed yet, since issue closed 16 days ago and 2.0.0-beta.9 was released 26 days ago.

**Comment by jamonholmgren** [comment]
We're getting closer to releasing beta.10, but since it's the precursor to 2.0.0 we are trying to include more things. Soon!

**Comment by alicelimacd** [comment]
hi, i m also hitting same issue. Have tried the solution above, none of them helps? Anyone can help?
