### ISSUE TITLE
Combined Ignite/create-react-native-app/Expo boilerplate

### ISSUE THREAD

**Issue by ghost** [infinitered/ignite#1008]
It would be great to be able to use Expo with Ignite. 

Is it possible to write a boilerplate that combines the ignite-ir-boilerplate-2016 with what create-react-native-app generates?

**Comment by RyszardRzepa** [comment]
Same question.

**Comment by skellock** [comment]
In that boilerplate, we use some native libraries (`react-native-device-info`, `react-native-vector-icons`, `i18n`) that are incompatible or different from CRNA/expo.

We'd have to separate that stuff in our boilerplate.

Here's what a separated & generated app might look like though:  https://github.com/skellock/expo-with-ignite

**Comment by GantMan** [comment]
Those plugins have an Expo equivalent. It's just a matter of small work to make everything work.

**Comment by jamonholmgren** [comment]
@minibbjd I'll add this to our discussion list for next meeting. cc @GantMan @skellock

**Comment by bubuzzz** [comment]
Please make CRNA work with Ignite. I have tried Ignite recently and totally love it; however, CRNA has become an official part of react native now, thus moving forward with it is essential

**Comment by GantMan** [comment]
@bubuzzz I'll be working on this soon, I expect you all to be awesome beta testers :D

**Comment by l1br3** [comment]
As I cannot use ignite "native" hot reloading (https://github.com/infinitered/ignite/issues/1121) I made this working with Expo. 
I had trouble with DevScreens (DeviceInfo related) but at least I can dev my App with hot reloading now and then copy paste my App and Tests dir into an ignite project.
It would be awesome to have this natively with an ignite boilerplate.

**Comment by jamonholmgren** [comment]
> It would be awesome to have this natively with an ignite boilerplate.

Agree.

**Comment by Amnesthesia** [comment]
+1

**Comment by Inlesco** [comment]
Is this still in-progress and not yet completed? :( I'm all up for seeing Ignite being fully compatible with Expo.

**Comment by l1br3** [comment]
Well its actually very easy to do so, you just need to copy App folder in a
fresh expo + put ignite dependencies in expo package.json
If you are interested, I can share my setup with you

**Comment by Inlesco** [comment]
@l1br3 I'm definitely interested. Please share your setup.

**Comment by l1br3** [comment]
Well, I'll do it mid of next week.

**Comment by Inlesco** [comment]
@l1br3 No rush, mate, but by the mid of next week, I'll probably make one myself :)

**Comment by l1br3** [comment]
What I realize is that my setup isn't a true ignite project as I cannot
compile. Its more the ignite boilerplate into an expo project. 30mn to set
it up

**Comment by kenneho** [comment]
Using Ignite to bootstrap an Expo project would be really excellent. I'm voting for this feature.

**Comment by eliaszica** [comment]
+1

**Comment by GantMan** [comment]
We're talking internally about it!  Will update when we have more info 👍

**Comment by Miheegz** [comment]
Does anyone have a working setup of the ignite boilerplate that works with expo?

**Comment by ruddell** [comment]
@Miheegz The other day, @jbosse posted this in the Ignite Slack
>I have a new repo with Expo.io integrated into a new Ignite 2.0 generated app. 
Repo: https://github.com/jbosse/expo-with-ignite2  
Expo: https://exp.host/@jbosse/expowithignite
https://infiniteredcommunity.slack.com/archives/C41PK1LAY/p1509827728000039

**Comment by jbosse** [comment]
Someone asked me in the Slack about trying to create a boilerplate. I am interested in this but I have to learn how to make a boilerplate first :-). I have a production release next week so I probably won't get to it for a couple of weeks.

**Comment by kenneho** [comment]
Thank you very much, @jbosse! I'll check it out.

**Comment by jbosse** [comment]
@kenneho I just published a version of the boilerplate that integrates Expo. you should be able to get started by using the command `ignite new MyLatestCreation -b ignite-expo`. Please let me know how it works for you. You can file an issues [here](https://github.com/jbosse/ignite-expo-boilerplate/issues)

**Comment by kenneho** [comment]
@jbosse Thanks a lot - it works great! I got the same issue as reported [here](https://github.com/jbosse/ignite-expo-boilerplate/issues/2), but other than that it looks great - I've managed to get the application up and running using Ignite + Expo, so this is a real bonus. Thanks for the excellent work!

**Comment by mikodigital** [comment]
will soon test that sounds great thank you

**Comment by brycereynolds** [comment]
Late to this party and new to react-native in general, but I'm testing out your work as well @jbosse.

**Comment by XeCtvi** [comment]
Waiting for the CRNA support 👍

**Comment by jamonholmgren** [comment]
We're going to call this one solved by @jbosse the Boss. https://github.com/jbosse/ignite-expo-boilerplate
