### ISSUE TITLE
Move React Native version dependency over to boilerplates

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1013]
Related to #957, we should move the version dependency to our boilerplates.

• Issue a warning if `opts.version` is not set [here](https://github.com/infinitered/ignite/blob/master/src/extensions/reactNative.js#L34)
• Update [ir-next](https://github.com/infinitered/ignite-ir-next/blob/091c4ad2616722eaa7e57ae577d014de7185477d/boilerplate.js#L86) and [default](https://github.com/infinitered/ignite-ir-boilerplate-2016/blob/master/boilerplate.js#L96) to properly call out which RN version they want

**Comment by juicycleff** [comment]
This is the best route as it has been one issue I've been struggling with.
