### ISSUE TITLE
Problem with "ignite generate screen PizzaLocationList"

### ISSUE THREAD

**Issue by tokgozmusa** [infinitered/ignite#1015]
Hey,

I think there is an inconsistency when we generate screens by the command that ignite provides.
```
$ ignite generate screen PizzaLocationList
```

After run this command we will have 2 autogenerated files: 
✔︎ App/Containers/PizzaLocationListScreen.js
✔︎ App/Containers/Styles/PizzaLocationListScreenStyle.js

Inside `PizzaLocationListScreen.js` file we see the following autogenerated line.
```
import styles from './Styles/PizzaLocationListStyle'
```

As we can see there is an inconsistency with file names. That autogenerated file should have been as follows:
```
import styles from './Styles/PizzaLocationListScreenStyle'
```

Note: I use ignite version `2.0.0-beta.9`.

Thank you for your considerations.

**Comment by jamonholmgren** [comment]
@tokgozmusa Thanks for reporting this. Did you use the default Ignite boilerplate or `ignite-ir-next`?

**Comment by tokgozmusa** [comment]
@jamonholmgren I installed ignite with `npm install -g ignite-cli` command.

I created my first app using `ignite new PizzaApp` command.

And apparently this command uses `ignite-ir-boilerplate-2016` boilerplate. I can open this bug on that boilerplate.

But I would like to ask how can I use `ignite-ir-next` boilerplate with `ignite-cli`?

Kind regars,
Musa

**Comment by jamonholmgren** [comment]
@tokgozmusa Thanks for the other issue. I have pull requests in both boilerplates now for this:

https://github.com/infinitered/ignite-ir-next/pull/37
https://github.com/infinitered/ignite-ir-boilerplate-2016/pull/38

To use ir-next, pass in `-b ir-next`:

```
ignite new PizzaApp -b ir-next
```

When Ignite CLI 2.0.0 is released, we'll default to our first post-2016 boilerplate release, code named `Andross`.

**Comment by tokgozmusa** [comment]
@jamonholmgren Thank you so much for your interest.
