### ISSUE TITLE
Ignite-cli requests react-native-cli even though it is installed 

### ISSUE THREAD

**Issue by Graren** [infinitered/ignite#1017]
### Hey there! Ignite CLI seems to be having a problem, eh?
---
What's going on?
running ignite in windows always outputs the next text

```
Ignite requires react-native-cli >=2.0.0 to be installed.

To install: npm i -g react-native-cli

Checking for 'react-native' npm package conflict...
```
And then... nothing happens, process closes. Unable to use cli in any way, and yeah I'm sure I have react-native-cli installed
```

npm list -g react-native-cli
C:\Program Files\nodejs
-- react-native-cli@2.0.1

```

---

Steps to reproduce
`ignite`,
or
`ignite new Anything`,
or
`ignite doctor`
Everything ignite related outputs that

---
`ignite doctor` results:
Can't run it

Additional notes: running node 7.8.0 on nvm4w

**Comment by kevinvangelder** [comment]
Many users have reported issues when trying to use NPM with NVM, so that may be the source of the problem.

**Comment by waqas19921** [comment]
@kevinvangelder i think this is your version matching function issue
Poor programming....

**Comment by Graren** [comment]
@kevinvangelder NPM installed yarn and a few other things, they work as expected, nvm is not the problem or so it would seem, yet I found that the solution shown at #1007 did the trick, the sanity checks and related that use shell.exec, without quoting the path (because it includes white spaces) fail.
I'm still waiting to actually test ignite output and make sure there are no problems with nvm though, that would be for another time.

**Comment by jamonholmgren** [comment]
@Graren Thanks for the update. We'll be releasing a new beta version soon.
