### ISSUE TITLE
Unable to initiate a new app using ignite

### ISSUE THREAD

**Issue by waqas19921** [infinitered/ignite#1018]
i have installed ignite using following command
`npm install -g ignite-cli`

when i try to ignite a new app using following command
`ignite new TestMay --npm`

it gives me error yarn not installed.

**Comment by waqas19921** [comment]
![ignite error](https://cloud.githubusercontent.com/assets/17469425/25775080/3aaa6ea8-32b6-11e7-90bd-cfeb0a686a15.png)
![ignite error1](https://cloud.githubusercontent.com/assets/17469425/25775081/42210aac-32b6-11e7-9095-3fe7c8b8fdf3.png)

**Comment by waqas19921** [comment]
And when i installed yarn it gives me following error
![untitled](https://cloud.githubusercontent.com/assets/17469425/25775108/cdf0183e-32b6-11e7-9305-e155a4a3fb1d.png)

**Comment by waqas19921** [comment]
@brad  @daviscabral @kemiller @twerth @jhblacklock any one what's the problem if i run any command it says
`Ignite requires yarn >=0.21.0 to be installed.`

**Comment by ruddell** [comment]
@waqas19921 Where is your yarn installed?  There was a recent fix for directories containing spaces but it hasn't been released yet (Fixed in https://github.com/infinitered/ignite/issues/1010)

**Comment by jamonholmgren** [comment]
For now, I recommend you use Windows Bash prompt rather than regular command terminal. It might be fixed in beta.10 though -- coming out tonight, if I can get through these!

**Comment by bodaz** [comment]
Hi there, I've run into the same issue here, `Ignite requires yarn >=0.21.0 to be installed.` when I have `yarn 0.24.5` installed. I'm using MacOS.

**Comment by jamonholmgren** [comment]
I ran into some things I'm waiting for before I can release 2.0.0-beta.10, but it's coming shortly. Hopefully fixes these issues.
