### ISSUE TITLE
import plugin does not clear yarn cache

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ignite#1020]
When working on an ignite plugin, changes to the plugin are ignored.

This is an issue with ignite/src/lib/ImportPlugin.js. 
Expected behavior is what has to be executed manually:

`~/Documents/Ignite2Experiments/jsonserverapp2 > yarn cache dir
/Users/<user>/Library/Caches/Yarn/v1
~/Documents/Ignite2Experiments/jsonserverapp2 > rm -rf /Users/<user>/Library/Caches/Yarn/v1/npm-ignite-json*`

When the yarn cache is removed, running `ignite add /Users/<user>/git/ignite-json-server` uses the latest changes to `/Users/<user>/git/ignite-json-server`

If the cache is not manually removed, any changes to `/Users/<user>/git/ignite-json-server` are ignored.

If this temporary debugging code is executed in  ignite/src/lib/ImportPlugin.js, from line 32 the problem persists:

if (ignite.useYarn) {
    // if (isDirectory) {
      // where is the yarn cache?
      // log(`checking for yarn cache`)
    const rawCacheDir = await system.exec('yarn cache dir')
    // console.error(`rm -rf ${rawCacheDir}/npm-${moduleName}-*`)
    // process.exit(9999)

    await system.exec(`rm -rf ${rawCacheDir}/npm-${moduleName}-*`)

      // // look for a cached version of this
      // const dirs = filesystem
      //   .cwd(rawCacheDir)
      //   .find({
      //     matching: `npm-${moduleName}-*`,
      //     directories: true,
      //     recursive: false
      //   })

      // // clear existing cache if we have one
      // if (!isEmpty(dirs)) {
      //   forEach(
      //     dir => {
      //       log(`remo/ving yarn cache ${rawCacheDir}/${dir}`)
      //       filesystem.remove(`${rawCacheDir}/${dir}`)
      //     },
      //     dirs
      //   )
      // }
    // }
```
---
Steps to reproduce

- create new plugin `ignite-json-server` in `/Users/<user>/git/ignite-json-server`
- install the plugin: `ignite add /Users<user>/git/ignite-json-server`
- remove the plugin: `ignite remove json-server`
- modify any code in `/Users/<user>/git/ignite-json-server/plugins.js`
- install the plugin: `ignite add /Users/<user>/git/ignite-json-server`
- observe that changes to the plugin are ignored
---

`ignite doctor` results:

```
System
  platform           darwin
  arch               x64
  cpu                8 cores                                                             Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  directory          /Users/derekgreenberg/Documents/Ignite2Experiments/jsonserverapp2

JavaScript
  node               7.7.4        /usr/local/bin/node
  npm                4.1.2        /usr/local/bin/npm
  yarn               0.23.3       /Users/derekgreenberg/.yarn/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.42.0

Ignite
  ignite             2.0.0-beta.9   /Users/derekgreenberg/.node/bin/ignite

Android
  java               1.8.0_73     /usr/bin/java
  android home       -            /usr/local/opt/android-sdk

iOS
  xcode              8.3.2
```

**Comment by jamonholmgren** [comment]
Thanks, @derekgreenberg , I've got this one.

**Comment by jamonholmgren** [comment]
Verifying this now.

**Comment by jamonholmgren** [comment]
Verified with `master` that this no longer is an issue (I think!). @derekgreenberg Can you check?

**Comment by derekgreenberg** [comment]
@jamonholmgren I just tested this change against the latest ignite and confirmed that this issue has been fixed. I created a new ignited app, added my locally sourced plugin, removed it, modified the plugin, invoked the `ignite add` command again, and I saw my changes immediately in the ignited project. You can close this issue.

**Comment by jamonholmgren** [comment]
Thank you @derekgreenberg !!
