### ISSUE TITLE
Ignite requires react-native-cli >=2.0.0 to be installed.

### ISSUE THREAD

**Issue by HelloEdit** [infinitered/ignite#1024]
Hello,

I'm a Windows user (yes I know ...) and i (would) use Ignite with yarn, so I execute this in CMD:
`yarn global add react-native-cli`
`yarn global add ignite-cli`

So, allllll isssss goood ! No errors
`react-native -v` return
```
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
```
And it's time to execute `ignite`,
`ignite new App`

Annnddddd ... nop

```
Ignite requires react-native-cli >=2.0.0 to be installed.
To install: npm i -g react-native-cli
Checking for 'react-native' npm package conflict...
```
I confess that I raged, But I really really really want to use ignite for my project ! So you can help me?

Thanks,

**Comment by HelloEdit** [comment]
`Ignite` work on Bash for Windows ... So i use that way for the moment !

**Comment by GantMan** [comment]
That npm package conflict is interesting.  We're going to set up an appveryor CI to help catch issues.  But we've generally had success on windows.

Perhaps it's the boilerplate?  Can you try another?

**Comment by HelloEdit** [comment]
This is not the fault of the boilerplates, because when I just perform 
`ignite`
I get the same errors...

As I have time to lose today, I will uninstall yarn etc ... and reinstall everything, and all this in joy and good humor !
But if you have a patch for this issuse, let me know !

Thanks,

**Comment by HelloEdit** [comment]
Ok !  So to be honest, I do not know what I did, I reinstall yarn while deleting chocolatey, I regenerate the installation nodejs and npm (and many, many others) and now i have this:
```
C:\ ignite
Ignite requires yarn >=0.21.0 to be installed.
See https://yarnpkg.com/en/docs/install on how to upgrade for your OS.
```
So it makes sense, except that ...
```
C:\ yarn -v
yarn install v0.23.4
[1/4] Resolving packages...
success Already up-to-date.
Done in `0.05s
```
So, I will try to go there gently to make him recognize yarn

Thanks,

**Comment by GantMan** [comment]
I thought we had fixed this issue!   We'll be doing another release soon, but I'm not sure why this is acting up.   What version of ignite?

**Comment by HelloEdit** [comment]
I'm sure it's the latest version, When will the new release take place ?

**Comment by keesee** [comment]
same here => Ignite requires yarn >=0.21.0 to be installed.

PS E:\Projects\> yarn --v
yarn install v0.23.4
info No lockfile found.
...

**Comment by ahsodhi** [comment]
I'm having the exact same problem.
Please try to fix this asap. Thanks.

> C:\Projects>ignite new IgniteTest
> 
> Ignite requires react-native-cli >=2.0.0 to be installed.
> 
> To install: npm i -g react-native-cli
> 
> Checking for 'react-native' npm package conflict...

**Comment by ahsodhi** [comment]
Seems like ignite just isn't able to run the shell commands to get the installed version of dependencies.
I edited the check.js file located in _AppData\Roaming\npm\node_modules\ignite-cli\src\cli_ to bypass all the checks.
Ignite now initializes the project just fine despite printing dependency check failed messages.
I edited the check.js so the process doesn't exit even when the check fails.
Maybe this gives developers a hint to what the actual problem is.

> Starting JS server...
> Building and installing the app on the device (cd android && gradlew.bat installDebug)...
> Incremental java compilation is an incubating feature.
> :app:preBuild UP-TO-DATE
> :app:preDebugBuild UP-TO-DATE
> :app:checkDebugManifest
> :app:preReleaseBuild UP-TO-DATE
> :react-native-config:preBuild UP-TO-DATE
> :react-native-config:preReleaseBuild UP-TO-DATE
> :react-native-config:checkReleaseManifest
> :react-native-config:preDebugAndroidTestBuild UP-TO-DATE
> :react-native-config:preDebugBuild UP-TO-DATE
> :react-native-config:preDebugUnitTestBuild UP-TO-DATE
> :react-native-config:preReleaseUnitTestBuild UP-TO-DATE
> :react-native-config:prepareComAndroidSupportAppcompatV72301Library
> :react-native-config:prepareComAndroidSupportRecyclerviewV72340Library
> :react-native-config:prepareComAndroidSupportSupportV42340Library
> :react-native-config:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
> :react-native-config:prepareComFacebookFrescoDrawee0110Library
> :react-native-config:prepareComFacebookFrescoFbcore0110Library
> :react-native-config:prepareComFacebookFrescoFresco0110Library
> :react-native-config:prepareComFacebookFrescoImagepipeline0110Library
> :react-native-config:prepareComFacebookFrescoImagepipelineBase0110Library
> :react-native-config:prepareComFacebookFrescoImagepipelineOkhttp30110Library
> :react-native-config:prepareComFacebookReactReactNative0420Library
> :react-native-config:prepareComFacebookSoloaderSoloader010Library
> :react-native-config:prepareOrgWebkitAndroidJscR174650Library
> :react-native-config:prepareReleaseDependencies
> :react-native-config:compileReleaseAidl
> :react-native-config:compileReleaseNdk UP-TO-DATE
> :react-native-config:compileLint
> :react-native-config:copyReleaseLint UP-TO-DATE
> :react-native-config:compileReleaseRenderscript
> :react-native-config:generateReleaseBuildConfig
> :react-native-config:generateReleaseResValues
> :react-native-config:generateReleaseResources
> :react-native-config:mergeReleaseResources
> :react-native-config:processReleaseManifest
> :react-native-config:processReleaseResources
> :react-native-config:generateReleaseSources
> :react-native-config:incrementalReleaseJavaCompilationSafeguard
> :react-native-config:compileReleaseJavaWithJavac
> :react-native-config:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
> :react-native-config:extractReleaseAnnotations
> :react-native-config:mergeReleaseShaders
> :react-native-config:compileReleaseShaders
> :react-native-config:generateReleaseAssets
> :react-native-config:mergeReleaseAssets
> :react-native-config:mergeReleaseProguardFiles
> :react-native-config:packageReleaseRenderscript UP-TO-DATE
> :react-native-config:packageReleaseResources
> :react-native-config:processReleaseJavaRes UP-TO-DATE
> :react-native-config:transformResourcesWithMergeJavaResForRelease
> :react-native-config:transformClassesAndResourcesWithSyncLibJarsForRelease
> :react-native-config:mergeReleaseJniLibFolders
> :react-native-config:transformNative_libsWithMergeJniLibsForRelease
> :react-native-config:transformNative_libsWithSyncJniLibsForRelease
> :react-native-config:bundleRelease
> :react-native-device-info:preBuild UP-TO-DATE
> :react-native-device-info:preReleaseBuild UP-TO-DATE
> :react-native-device-info:checkReleaseManifest
> :react-native-device-info:preDebugAndroidTestBuild UP-TO-DATE
> :react-native-device-info:preDebugBuild UP-TO-DATE
> :react-native-device-info:preDebugUnitTestBuild UP-TO-DATE
> :react-native-device-info:preReleaseUnitTestBuild UP-TO-DATE
> :react-native-device-info:prepareComAndroidSupportAppcompatV72301Library
> :react-native-device-info:prepareComAndroidSupportRecyclerviewV72340Library
> :react-native-device-info:prepareComAndroidSupportSupportV42400Library
> :react-native-device-info:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
> :react-native-device-info:prepareComFacebookFrescoDrawee0110Library
> :react-native-device-info:prepareComFacebookFrescoFbcore0110Library
> :react-native-device-info:prepareComFacebookFrescoFresco0110Library
> :react-native-device-info:prepareComFacebookFrescoImagepipeline0110Library
> :react-native-device-info:prepareComFacebookFrescoImagepipelineBase0110Library
> :react-native-device-info:prepareComFacebookFrescoImagepipelineOkhttp30110Library
> :react-native-device-info:prepareComFacebookReactReactNative0420Library
> :react-native-device-info:prepareComFacebookSoloaderSoloader010Library
> :react-native-device-info:prepareComGoogleAndroidGmsPlayServicesBase1020Library
> :react-native-device-info:prepareComGoogleAndroidGmsPlayServicesBasement1020Library
> :react-native-device-info:prepareComGoogleAndroidGmsPlayServicesGcm1020Library
> :react-native-device-info:prepareComGoogleAndroidGmsPlayServicesIid1020Library
> :react-native-device-info:prepareComGoogleAndroidGmsPlayServicesTasks1020Library
> :react-native-device-info:prepareOrgWebkitAndroidJscR174650Library
> :react-native-device-info:prepareReleaseDependencies
> :react-native-device-info:compileReleaseAidl
> :react-native-device-info:compileReleaseNdk UP-TO-DATE
> :react-native-device-info:compileLint
> :react-native-device-info:copyReleaseLint UP-TO-DATE
> :react-native-device-info:compileReleaseRenderscript
> :react-native-device-info:generateReleaseBuildConfig
> :react-native-device-info:generateReleaseResValues
> :react-native-device-info:generateReleaseResources
> :react-native-device-info:mergeReleaseResources
> :react-native-device-info:processReleaseManifest
> :react-native-device-info:processReleaseResources
> :react-native-device-info:generateReleaseSources
> :react-native-device-info:incrementalReleaseJavaCompilationSafeguard
> :react-native-device-info:compileReleaseJavaWithJavac
> :react-native-device-info:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
> :react-native-device-info:extractReleaseAnnotations
> :react-native-device-info:mergeReleaseShaders
> :react-native-device-info:compileReleaseShaders
> :react-native-device-info:generateReleaseAssets
> :react-native-device-info:mergeReleaseAssets
> :react-native-device-info:mergeReleaseProguardFiles
> :react-native-device-info:packageReleaseRenderscript UP-TO-DATE
> :react-native-device-info:packageReleaseResources
> :react-native-device-info:processReleaseJavaRes UP-TO-DATE
> :react-native-device-info:transformResourcesWithMergeJavaResForRelease
> :react-native-device-info:transformClassesAndResourcesWithSyncLibJarsForRelease
> :react-native-device-info:mergeReleaseJniLibFolders
> :react-native-device-info:transformNative_libsWithMergeJniLibsForRelease
> :react-native-device-info:transformNative_libsWithSyncJniLibsForRelease
> :react-native-device-info:bundleRelease
> :react-native-vector-icons:preBuild UP-TO-DATE
> :react-native-vector-icons:preReleaseBuild UP-TO-DATE
> :react-native-vector-icons:checkReleaseManifest
> :react-native-vector-icons:preDebugAndroidTestBuild UP-TO-DATE
> :react-native-vector-icons:preDebugBuild UP-TO-DATE
> :react-native-vector-icons:preDebugUnitTestBuild UP-TO-DATE
> :react-native-vector-icons:preReleaseUnitTestBuild UP-TO-DATE
> :react-native-vector-icons:prepareComAndroidSupportAppcompatV72301Library
> :react-native-vector-icons:prepareComAndroidSupportRecyclerviewV72340Library
> :react-native-vector-icons:prepareComAndroidSupportSupportV42340Library
> :react-native-vector-icons:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
> :react-native-vector-icons:prepareComFacebookFrescoDrawee0110Library
> :react-native-vector-icons:prepareComFacebookFrescoFbcore0110Library
> :react-native-vector-icons:prepareComFacebookFrescoFresco0110Library
> :react-native-vector-icons:prepareComFacebookFrescoImagepipeline0110Library
> :react-native-vector-icons:prepareComFacebookFrescoImagepipelineBase0110Library
> :react-native-vector-icons:prepareComFacebookFrescoImagepipelineOkhttp30110Library
> :react-native-vector-icons:prepareComFacebookReactReactNative0420Library
> :react-native-vector-icons:prepareComFacebookSoloaderSoloader010Library
> :react-native-vector-icons:prepareOrgWebkitAndroidJscR174650Library
> :react-native-vector-icons:prepareReleaseDependencies
> :react-native-vector-icons:compileReleaseAidl
> :react-native-vector-icons:compileReleaseNdk UP-TO-DATE
> :react-native-vector-icons:compileLint
> :react-native-vector-icons:copyReleaseLint UP-TO-DATE
> :react-native-vector-icons:compileReleaseRenderscript
> :react-native-vector-icons:generateReleaseBuildConfig
> :react-native-vector-icons:generateReleaseResValues
> :react-native-vector-icons:generateReleaseResources
> :react-native-vector-icons:mergeReleaseResources
> :react-native-vector-icons:processReleaseManifest
> :react-native-vector-icons:processReleaseResources
> :react-native-vector-icons:generateReleaseSources
> :react-native-vector-icons:incrementalReleaseJavaCompilationSafeguard
> :react-native-vector-icons:compileReleaseJavaWithJavac
> :react-native-vector-icons:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
> :react-native-vector-icons:extractReleaseAnnotations
> :react-native-vector-icons:mergeReleaseShaders
> :react-native-vector-icons:compileReleaseShaders
> :react-native-vector-icons:generateReleaseAssets
> :react-native-vector-icons:mergeReleaseAssets
> :react-native-vector-icons:mergeReleaseProguardFiles
> :react-native-vector-icons:packageReleaseRenderscript UP-TO-DATE
> :react-native-vector-icons:packageReleaseResources
> :react-native-vector-icons:processReleaseJavaRes UP-TO-DATE
> :react-native-vector-icons:transformResourcesWithMergeJavaResForRelease
> :react-native-vector-icons:transformClassesAndResourcesWithSyncLibJarsForRelease
> :react-native-vector-icons:mergeReleaseJniLibFolders
> :react-native-vector-icons:transformNative_libsWithMergeJniLibsForRelease
> :react-native-vector-icons:transformNative_libsWithSyncJniLibsForRelease
> :react-native-vector-icons:bundleRelease
> :app:prepareComAndroidSupportAppcompatV72301Library
> :app:prepareComAndroidSupportRecyclerviewV72340Library
> :app:prepareComAndroidSupportSupportV42400Library
> :app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
> :app:prepareComFacebookFrescoDrawee0110Library
> :app:prepareComFacebookFrescoFbcore0110Library
> :app:prepareComFacebookFrescoFresco0110Library
> :app:prepareComFacebookFrescoImagepipeline0110Library
> :app:prepareComFacebookFrescoImagepipelineBase0110Library
> :app:prepareComFacebookFrescoImagepipelineOkhttp30110Library
> :app:prepareComFacebookReactReactNative0420Library
> :app:prepareComFacebookSoloaderSoloader010Library
> :app:prepareComGoogleAndroidGmsPlayServicesBase1020Library
> :app:prepareComGoogleAndroidGmsPlayServicesBasement1020Library
> :app:prepareComGoogleAndroidGmsPlayServicesGcm1020Library
> :app:prepareComGoogleAndroidGmsPlayServicesIid1020Library
> :app:prepareComGoogleAndroidGmsPlayServicesTasks1020Library
> :app:prepareIgniteTestReactNativeConfigUnspecifiedLibrary
> :app:prepareIgniteTestReactNativeDeviceInfoUnspecifiedLibrary
> :app:prepareIgniteTestReactNativeVectorIconsUnspecifiedLibrary
> :app:prepareOrgWebkitAndroidJscR174650Library
> :app:prepareDebugDependencies
> :app:compileDebugAidl
> :app:compileDebugRenderscript
> :app:generateDebugBuildConfig
> :app:mergeDebugShaders
> :app:compileDebugShaders
> :app:generateDebugAssets
> :app:mergeDebugAssets
> :app:generateDebugResValues
> :app:generateDebugResources
> :app:mergeDebugResources
> :app:bundleDebugJsAndAssets SKIPPED
> :app:processDebugManifest
> :app:processDebugResources
> :app:generateDebugSources
> :app:incrementalDebugJavaCompilationSafeguard
> :app:compileDebugJavaWithJavac
> :app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
> :app:compileDebugNdk UP-TO-DATE
> :app:compileDebugSources
> :app:transformClassesWithDexForDebug
> Running dex in-process requires build tools 23.0.2.
> For faster builds update this project to use the latest build tools.
> :app:mergeDebugJniLibFolders
> :app:transformNative_libsWithMergeJniLibsForDebug
> :app:processDebugJavaRes UP-TO-DATE
> :app:transformResourcesWithMergeJavaResForDebug
> :app:validateSigningDebug
> :app:packageDebug
> :app:assembleDebug
> :app:installDebug
> Installing APK 'app-debug.apk' on 'Nexus_5X_API_25_x86(AVD) - 6.0' for app:debug
> Installed on 1 device.
> 
> BUILD SUCCESSFUL
> 
> Total time: 1 mins 41.397 secs
> Running C:\Android\sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
> Starting the app on emulator-5554 (C:\Android\sdk/platform-tools/adb -s emulator-5554 shell am start -n com.ignitetest/.MainActivity)...
> Starting: Intent { cmp=com.ignitetest/.MainActivity }

**Comment by hustlerism** [comment]
I'm having this problem as well while trying to add maps plugin onto my project.

Tried to npm uninstall -g react-native & npm install -g react-native-cli but still cant add the plugins.

Any workaround for this?

```
D:\Desktop\Makan>ignite add maps
Ignite requires react-native-cli >=2.0.0 to be installed.

To install: npm i -g react-native-cli

Checking for 'react-native' npm package conflict...

It appears you have the global npm package 'react-native' installed. This causes problems
with Ignite. You may have installed this by mistake. Instead, you probably want the
react-native-cli npm package.

npm uninstall -g react-native
npm install -g react-native-cli
```

**Comment by HelloEdit** [comment]
I think @jamonholmgren could add `bug` as label of this issue ^^.

**Comment by HelloEdit** [comment]
For now, while waiting for a fix, the most suitable solution for windows 10 is the Linux subsystem
### Bash for Windows
You can install the Linux environment on windows to avoid system incompatibilities (as the subjet of this issue)

To enable bash, follow the Microsoft tutorial [here](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)

Then you can execute *all* bash command, npm, yarn etc...

### Warning
For use
`react-native run-android | react-native run-ios`, 
You must execute it from *CMD*, because Windows env variables **are not include** in bash (%ANDROID_HOME%).
Remember this, because it is the cause of many misunderstandings

**Comment by GantMan** [comment]
@kevinvangelder - can you help with this please?

**Comment by tehkhop** [comment]
I've got the yarn issue as well.

When the yarn version is being checked, inside src/cli/enforceGlobalDependency.js in getVersion(),`raw` is equal to:
`'C:\Program' is not recognized as an internal or external command,
operable program or batch file.`

The problem appears to be the spaces in the path.

## Quick Fix

I fixed it by changing line 80 to:
`var resolvedPath = '"' + which.sync(whichExec) + '"';`

Don't want to make a pull request, as I'm really not familiar with `which`, and there's probably a better way.

For a temporary solution just do the change I described inside src/cli/enforceGlobalDependency.js

**Comment by csumrell** [comment]
I get this error as well: Ignite requires react-native-cli >=2.0.0 to be installed.

When i downgrade to 2.0.0-beta.4 however I am able to get it working with nvm-windows

**Comment by jamonholmgren** [comment]
This should be fixed in the next release.

**Comment by gauravgupta2** [comment]
I see this issue on mac too...

$ ignite new Pizza
Ignite requires react-native-cli >=2.0.0 to be installed.
To install: npm i -g react-native-cli
Checking for 'react-native' npm package conflict...

$ npm view react-native-cli version
2.0.1

**Comment by bslayerw** [comment]
happening to mac too:

 ignite new MyNewAppName
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app MyNewAppName
Ignite requires react-native-cli >=2.0.0 to be installed.

You currently have 0.43.2 installed.

To install: npm i -g react-native-cli

Checking for 'react-native' npm package conflict...


System
  platform           darwin                                                                          
  arch               x64                                                                             
  cpu                8 cores                    Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz  
  directory          /Users/bywright/Projects                                                        

JavaScript
  node               7.8.0        /usr/local/bin/node  
  npm                4.2.0        /usr/local/bin/npm   
  yarn               0.22.0       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.0.0-beta.9   /usr/local/bin/ignite  

Android
  java               1.8.0_92     /usr/bin/java                        
  android home       -            /Users/bywright/Library/Android/sdk  

iOS
  xcode              8.3.2
