### ISSUE TITLE
Got error after put reducer key to blacklist!!!

### ISSUE THREAD

**Issue by tuandt** [infinitered/ignite#1026]
Hi you all,

I used ignite 1.13.0 for my project.

In REDUX_PERSIST setting, whenever I put a reducer key to blacklist, if I call that reducer I got error message: undefined is not a function (evaluating 'state.merge({ fetching: true, data: data, payload: null })')
request

Does anyone get this error?

Do you have any suggestion?

**Comment by GantMan** [comment]
Never seen that one.  Is the code online?

**Comment by tuandt** [comment]
Hi GantMan,

I am sorry that there is no source code online. If I don't put reducer on blacklist, it works fine.

I am using RN v0.44, redux-persist v3.5.0, redux-saga v0.13.0, react-redux v4.4.6

Does this information help?

**Comment by tuandt** [comment]
Hi,

I found an error on init reducer. Close it for now.

**Comment by kamranyounis12** [comment]
@tuandt what was the issue? I'm suffering from same issue
