### ISSUE TITLE
CLI Needs A list option

### ISSUE THREAD

**Issue by johndanek** [infinitered/ignite#1028]
As far as I can tell, there is no way to see which ignite packages are currently installed. Now that my app is gearing up for release, I would like to remove the ignite packages that I didn't end up using, but I don't know what they are.

Should there be an `ignite list` command added?

**Comment by jamonholmgren** [comment]
I agree @johndanek . Thanks!

**Comment by jamonholmgren** [comment]
In the meantime, a good way to see all installed Ignite packages is `yarn list | grep 'ignite-'`.

**Comment by adrianhartanto0** [comment]
There is already a `ignite list` command though. Any idea what word to use instead? @jamesgeorge007

**Comment by jamonholmgren** [comment]
@adrianhartanto0 We could show which ones are currently installed by highlighting them and adding `[installed]`, or put them in a separate section of the output.

![image](https://user-images.githubusercontent.com/1479215/61179755-2be04c80-a5be-11e9-9c9c-6bc5e76eae99.png)
