### ISSUE TITLE
[Base] Theme Screen

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/ignite#103]
- [X] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [X] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

I think what I came up with for one of our projects would be a reasonable starting point: 
![](https://api.monosnap.com/rpc/file/download?id=I5iXVjOzMAWU7SuHIloAhESGl78Lx7)
![](https://api.monosnap.com/rpc/file/download?id=glp1YwgNWhh15s3Zu1RpzgdF9qCBsQ)

**Comment by GantMan** [comment]
Nice, but how would you find "headings" programmatically?  You can only find font sizes.
