### ISSUE TITLE
Issue creating new project: Missing user in yarn: AVA

### ISSUE THREAD

**Issue by brendanfmartin** [infinitered/ignite#1032]
```➜  react ignite new PizzaApp
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app PizzaApp
✔ using the Infinite Red 2016 boilerplate
✔ added React Native 0.42.0
? Would you like Ignite Development Screens? No
? What vector icon library will you use? none
? What internationalization library will you use? none
? What animation library will you use? none
⠧ ▸ installing ignite dependenciesan error occured while installing ignite-ir-boilerplate-2016 boilerplate.
Error: Command failed: yarn
error An unexpected error occurred: "https://registry.yarnpkg.com/@ava%2fbabel-preset-stage-4: User not found".

⠸ ▸ installing ignite dependencies
```

---
`ignite doctor` results:
```➜  react ignite doctor
System
  platform           darwin                                                                                            
  arch               x64                                                                                               
  cpu                8 cores                                      Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz  
  directory          /Users/XXXXXXX/Sites/personal/react                                                        

JavaScript
  node               7.6.0        /Users/XXXXXXX/.nvm/versions/node/v7.6.0/bin/node  
  npm                4.1.2        /Users/XXXXXXX/.nvm/versions/node/v7.6.0/bin/npm   
  yarn               0.24.4       /Users/XXXXXXX/.nvm/versions/node/v7.6.0/bin/yarn  

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.0.0-beta.9   /Users/XXXXXXX/.nvm/versions/node/v7.6.0/bin/ignite  
vvv -----[ DEBUG ]----- vvv
{ Error: Command failed: java -version 2>&1

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'java -version 2>&1',
  stderr: '' }
^^^ -----[ DEBUG ]----- ^^^
➜  react ```

**Comment by brendanfmartin** [comment]
I'm stuck on the install at this point.

**Comment by jamonholmgren** [comment]
Hey @brendanfmartin , sorry you're having issues. I haven't seen this issue before at all and am kind of scratching my head. Any other context you can give?

**Comment by brendanfmartin** [comment]
Hey @jamonholmgren, thanks for the reply. I have never used ignite before so everything was from a fresh install. 

It appears that this error `error An unexpected error occurred: "https://registry.yarnpkg.com/@ava%2fbabel-preset-stage-4: User not found".` is caused during the installation step of `ignite-ir-boilerplate-2016`. I also attempted to set up `ignite-ir-boilerplate-2016` separately directly from git with a `yarn install` and received the same issue. I checked npm and it does appear that this user is no longer there: https://www.npmjs.com/~ava however the package does exist: https://www.npmjs.com/package/@ava/babel-preset-stage-4

I am going to attempt to clone the boilerplate and point the package.json directly to the github repo for the project: https://github.com/avajs/babel-preset-stage-4

NOTE: I have seen similar issues that only appear when you npm cache clean or npm cache clear (I forget which does what at the moment) so if you want to do those steps to attempt to reproduce I highly recommend backing up your node_module directory.

**Comment by jamonholmgren** [comment]
@brendanfmartin That sounds like a plan. Let me know what you find out.

**Comment by skellock** [comment]
Still an issue? I wonder if npm was cranky that day?

**Comment by brendanfmartin** [comment]
Thanks for the follow up, it appears there is still an issue. I will try on another network to confirm firewall isn't an issue. This is highly unusual

**Comment by brendanfmartin** [comment]
I've confirmed that it's localized to my work laptop due to a custom npm setup.

**Comment by skellock** [comment]
Thx for closing the loop.
