### ISSUE TITLE
Installed ignite using attach - how do I access generators & demos?

### ISSUE THREAD

**Issue by nextriot** [infinitered/ignite#1034]
~**SOLUTION**~

~Should have tested more extensively. Sorry folks.
Did `ignite add ignite-ir-next` then `ignite generate screen LoginScreen` worked as expected.~

Wasn't a solution, `ignite add ignite-ir-next` just adds the theme as an npm package, generating screens etc. does create them but the structure within the file is all messed e.g. trying to access themes at a level which obviously doesn't exist. So back to the original question...

-----

Hi. Framework looks great.

Went ahead and added to an expo project using `ignite attach`. Everything went through as expected. When I attempted `ignite generate screen LoginScreen` - I get 'No generators detected'.

I read another comment that stated that generators were now bundled within the boilerplates.
So my question is - if it's possible - how do I add a boilerplate and use it as my main template / UI in an expo app?

Thanks

**Comment by jamonholmgren** [comment]
@nextriot I believe you ran into a bug I fixed recently and will hopefully be updated in the next boilerplate release.

**Comment by nextriot** [comment]
Cool. Thanks for the response @jamonholmgren. Looking forward to the next release ;)

**Comment by tmaly1980** [comment]
@jamonholmgren What was the underlying issue? I'm using the most recent ignite with bowser and all of the sudden getting this issue, yet "npx ignite-cli doctor" shows the generators!
