### ISSUE TITLE
Upgrading gluegun causes error: "extension.setup" not a function

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1040]
Upgrading from gluegun 0.17.1 to 0.18.0 results in this error when running `yarn run integration`:

![image](https://cloud.githubusercontent.com/assets/1479215/26189229/5611419e-3b58-11e7-8608-ed22e130bd0e.png)

@skellock ... halp... ?

**Comment by skellock** [comment]
We changed the interface in https://github.com/infinitered/gluegun/pull/184 and my breaking change radar didn't go off.  Will fix in the morning.  Sorry.

**Comment by jamonholmgren** [comment]
Okay, thank you @skellock !

**Comment by skellock** [comment]
Slipped my radar.

Good to go now @jamonholmgren once you [pull the merge trigger](https://github.com/infinitered/ignite/pull/1046).
