### ISSUE TITLE
when I use cli, It is a problem

### ISSUE THREAD

**Issue by shuaizhiwen** [infinitered/ignite#1042]
![image](https://cloud.githubusercontent.com/assets/28283255/26190728/8a6d93e0-3bdd-11e7-9279-3dfdaecd5cb7.png)
My English is poor, so an img in here

**Comment by GantMan** [comment]
make sure watchman is properly installed.

**Comment by shuaizhiwen** [comment]
thanks，I think it is my wrong. I use a new compter, but do not install watchman.
