### ISSUE TITLE
Sporked templates not being used

### ISSUE THREAD

**Issue by SRandazzo** [infinitered/ignite#1043]
What's going on?

After running `ignite spork` and selecting the templates I want to spork, they are copied into `ignite/Spork/ignite-ir-boilerplate-2016`

I've modified the template (redux.ejs in this case), saved and then run `ignite generate redux MyState`

The new MyState.js that is created is not based on my modified .ejs template, but instead reflects the default template

---
Steps to reproduce

run `ignite spork`
select the templates you want to spork (in this case redux)
modify the template
run `ignite generate redux MyState`
Observe the newly created MyState.js is using the original format, not your custom sporked template

thanks!

---
`ignite doctor` results:

```
System
  platform           darwin

  arch               x64

  cpu                8 cores                                                 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  directory          /Users/sal/Sites/paperlesspost/pages/packages/PagesRN


JavaScript
  node               7.10.0       /Users/sal/.nvm/versions/node/v7.10.0/bin/node
  npm                4.2.0        /Users/sal/.nvm/versions/node/v7.10.0/bin/npm
  yarn               0.24.4       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.44.0

Ignite
  ignite             2.0.0-beta.9   /Users/sal/.nvm/versions/node/v7.10.0/bin/ignite

Android
  java               1.8.0_131    /usr/bin/java
  android home       -            undefined

iOS
  xcode              8.3.2
```

**Comment by jamonholmgren** [comment]
Thanks @SRandazzo , I'll look into this before we release 2.0.0.

**Comment by jamonholmgren** [comment]
Verified this is happening.

**Comment by jamonholmgren** [comment]
The reason this isn't working is because in most plugins we switched our generators over to `copyBatch`, which doesn't include spork capability.

I'll work on implementing that now.

**Comment by SRandazzo** [comment]
thanks!!! 👏 🎉
