### ISSUE TITLE
Old Ignite folder structure

### ISSUE THREAD

**Issue by mykelaballe** [infinitered/ignite#1045]
how can i generate the old Ignite folder structure using ignite new MyAppName? The new boilerplate seems to not include the folders: Actions, Fonts, Utils, Store. Reducers folder is also changed to Redux

**Comment by GantMan** [comment]
I don't believe we have a boilerplate based on the older structure.   I'd be open to listing a fork of the old structure.  Do you want help creating a boilerplate with that structure?

**Comment by mykelaballe** [comment]
yup that would be great! cause i already have an existing project based on the old folder structure and previous redux logic. i plan to transition everything but not now since im rushing on deploying a new version of my app

**Comment by jamonholmgren** [comment]
Nice! I'll close for now, but reach out if you need help with your new boilerplate.

**Comment by mykelaballe** [comment]
where am i gonna grab the fork?

**Comment by jamonholmgren** [comment]
@mykelaballe I'd start with https://github.com/infinitered/ignite-ir-next, but wait until we release Andross this week (our first major release with Ignite CLI).

**Comment by mykelaballe** [comment]
ohh too bad. i really need the old structure ASAP

**Comment by skellock** [comment]
[This tag](https://github.com/infinitered/ignite/tree/legacy) has the 1.0 structure if you need to resurrect some files.

**Comment by GantMan** [comment]
Yup, look through the releases (https://github.com/infinitered/ignite/releases) and find out when you'd like the old structure, then it's super easy!

**Comment by GantMan** [comment]
Looks to me like anything before 1.7 should be good:   https://github.com/infinitered/ignite/releases/tag/1.7.0

**Comment by mykelaballe** [comment]
@skellock how should i generate the boilerplate? ill download the repo then call ignite new MyApp inside that repo? also when i looked at the App folder, its still the new folder structure.

@GantMan the same question here, how should i generate it? ill download it and then run command ignite new MyApp, and then it will map my app's name to android's manifest file, gradle, ios AppDelegate file, etc...?

**Comment by mykelaballe** [comment]
why is it that ignite new MyApp command gets the 1.13.0 folder structure even though the ignite version installed on my windows pc is 1.5.0?

**Comment by mykelaballe** [comment]
Another thing is that whenever i run the generated boilerplate, i keep getting this error

![image](https://cloud.githubusercontent.com/assets/22584900/26370980/f720fd9a-402b-11e7-9e5f-9103a3198cef.png)

**Comment by GantMan** [comment]
run `npm dedup`

**Comment by mykelaballe** [comment]
it worked for vector-icons but now another naming collision appeared which is the router-flux. is there an npm dedup recursive command?

**Comment by mykelaballe** [comment]
![image](https://cloud.githubusercontent.com/assets/22584900/26431630/bf9fd884-4128-11e7-9817-ab0b146d05f7.png)

**Comment by mykelaballe** [comment]
i tried deleting the collisioned file stated in the image above, but when i build it again another file has collided with other files again. And it seems to happen repeatedly even though i delete the next files and so on and so forth
