### ISSUE TITLE
ignite new MyIgniteProject ends with `Error: not found: git`

### ISSUE THREAD

**Issue by marsonmao** [infinitered/ignite#1051]
Hey I tried to create a new project, but finally got the error message `an error occured while installing ignite-ir-boilerplate-2016 boilerplate.` and `Error: not found: git`.
Anyone knows how to fix this?

Below is the full log:

----

I:\____>ignite new MyIgniteProject
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

� igniting app MyIgniteProject
√ using the Infinite Red 2016 boilerplate
? Would you like Ignite Development Screens? Yes
? What vector icon library will you use? react-native-vector-icons
? What internationalization library will you use? react-native-i18n
? What animation library will you use? react-native-animatable
√ added React Native 0.42.0
√ added ignite-ir-boilerplate-2016
√ added ignite-dev-screens
√ added ignite-vector-icons
√ added ignite-i18n
√ added ignite-animatable
an error occured while installing ignite-ir-boilerplate-2016 boilerplate.
Error: not found: git

**Comment by jamonholmgren** [comment]
Hey @marsonmao , what happens when you do `which git` ?

**Comment by marsonmao** [comment]
Hi @jamonholmgren : it says, 'which' is not recognized as an internal or external command

**Comment by marsonmao** [comment]
Oh sorry didn't state that I'm running on Windows 7. I googled `which` so I tried `where git` and it says cant find the file.

**Comment by jamonholmgren** [comment]
@marsonmao Gotcha! We'll need to check for the presence of `git` in our prerequisites. I'll let @kevinvangelder take over from here.

**Comment by marsonmao** [comment]
@jamonholmgren Oh and thanks for helping!

**Comment by jamonholmgren** [comment]
@marsonmao Don't worry about it -- sounds like you're good to go!

**Comment by ruddell** [comment]
@jeronnex2 You can either install `git`, or pass `--skip-git` when generating your app.

I think this was [fixed in Gluegun](https://github.com/infinitered/gluegun/pull/397), but Ignite still uses an older version

**Comment by ryanlntn** [comment]
Ignite 3 is now using the latest Gluegun. In addition the `ignite-ir-boilerplate-2016` is no longer supported.
