### ISSUE TITLE
ignite attach followed by ignite add ignite-ir-boilerplate = lots of errors

### ISSUE THREAD

**Issue by vesper8** [infinitered/ignite#1063]
Using ignite 2.0.0-rc.1 and latest ir-boilerplate released today

On an existing project

```
ignite attach
ignite add ignite-ir-boilerplate
```

This adds ignite-ir-boilerplate as a npm dependency but does not create any files in the App folder

then

```
ignite generate screen LoginScreen
```

and got this warning during generation

```
✔︎ App/Containers/LoginScreen.js
✔︎ App/Containers/Styles/LoginScreenStyle.js
vvv -----[ DEBUG ]----- vvv
TypeError: print.log is not a function
    at Object.module.exports [as run] (/Volumes/Omitted/com.mydomain.ignited-ir/node_modules/ignite-ir-boilerplate/commands/screen.js:61:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
^^^ -----[ DEBUG ]----- ^^^
```

This command generated two files, including a LoginScreenStyle.js which has this in it
```
import { ApplicationStyles } from '../../Themes/'
```

But there is no Themes folder, my /App/ folder is completely empty save for the two files that were just generated

I also generated a saga 

```
ignite generate saga SagaTest
```

which generated a file that has this

```
import SagaTestActions from '../Redux/SagaTestRedux'
```

But again.. there is no Redux folder, and it did not generate the SagaTestRedux

It also mentions that I need to do things in sagas/index.js but that file also doesn't exist

and so on..

Should I just copy the whole contents of the App folder from the node_modules ? But wouldn't that then include a bunch of demo files? What if I just want to use the generators in a clean project

**Comment by skellock** [comment]
https://github.com/infinitered/ignite-ir-boilerplate/pull/67 fixes the error you're seen.  It'll be included in the next release.

That error was preventing your files from being generated.

Also, you can use the generators separately if you `ignite attach` to an existing project instead of `ignite new NewProject`.  You'd then run `ignite add ir-boilerplate`.  This will bring in the generators, but not do anything to setup the boilerplate directories & files.
