### ISSUE TITLE
no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by latifs** [infinitered/ignite#1065]
What's going on?
when trying to 'ignite new PizzaApp'
<img width="541" alt="screen shot 2017-05-26 at 9 43 31 am" src="https://cloud.githubusercontent.com/assets/3582034/26504065/ebecacb2-41f7-11e7-95df-bca425a72618.png">

---
`ignite doctor` results:
System
  platform         darwin                                                                            
  arch               x64                                                                               
  cpu                4 cores                       Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz  
  directory          

JavaScript
  node               7.10.0      
  npm                4.2.0       
  yarn               0.24.6      

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.0.0-rc.1   

Android
  java               1.6.0_65     
  android home       -          

iOS
  xcode              8.3.2

**Comment by skellock** [comment]
Same thing with he latest ignite? Try updating and giving that a shot.

**Comment by jamonholmgren** [comment]
Closing, feel free to comment if you're still having issues and I'll re-open.

**Comment by martianmartian** [comment]
i still have the issue!!
