### ISSUE TITLE
newly created Project builds but packager produce errors

### ISSUE THREAD

**Issue by mykelaballe** [infinitered/ignite#1069]
Node: 4.8.3
NPM: 4.5.0
RN CLI: 1.0.0
RN: 0.34.0
Ignite: 1.13.0
Platform: Virtualbox running OSX 10.11 El Capitan

![1](https://cloud.githubusercontent.com/assets/22584900/26522040/5385e568-432a-11e7-80e8-2b89d583840c.JPG)
![2](https://cloud.githubusercontent.com/assets/22584900/26522041/587e576c-432a-11e7-822f-14c591e7a9db.JPG)

![image](https://cloud.githubusercontent.com/assets/22584900/26522059/a3490f76-432a-11e7-88f1-22c3548e0a5b.png)

What am i missing? do i need to install a JDK? do i need to update the versions? do i have to run it in an actual machine instead of a virtual one?

**Comment by GantMan** [comment]
Verify you have set up everything prescribed by facebook for your Android environment.  https://facebook.github.io/react-native/docs/getting-started.html

Then you should be good to go!

**Comment by mykelaballe** [comment]
having trouble with ios
