### ISSUE TITLE
Deprication Warnings on `npm install -g react-native-ignite`

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/ignite#107]
- [X] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [X] ignite the cli
  - [ ] ignite generated code

```
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
```

**Comment by GantMan** [comment]
I guess those are dependencies?   *shrug*   Will keep an eye out and research,   Good find!

**Comment by kevinvangelder** [comment]
I looked into this and it appears to be the fault of a dependency. I can dig into it a little more to figure out which dependencies are at fault and then we can close this out.

**Comment by GantMan** [comment]
closing as this has gone stale.
