### ISSUE TITLE
Could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1.

### ISSUE THREAD

**Issue by HelloEdit** [infinitered/ignite#1071]
Hello everyone,

I download the latest version of Ignite, then I execute in my bash for Windows console this:
`ignite new TestApp`
And I answered 'No' to all question, then I execute
`react-native run-android`
for test and, surprise ! BUILD FAILED with this log:

FAILURE: Build failed with an exception.

```log
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1.
     Required by:
         Testapp:app:unspecified > com.facebook.react:react-native:0.42.3-atlassian-1
```
I do not know if I'm the only one right now having problems with react-native (aidl, gradle and many, many others 😢)

PS: You have done a very good job for the last version of the ir-boilerplate, thank you to all your super team 💪 !

**Comment by HelloEdit** [comment]
Oh, and now I have this:
`* What went wrong:
Execution failed for task ':app:compileDebugAidl'.
> java.lang.IllegalStateException: aidl is missing`

**Comment by HelloEdit** [comment]
Ok apparently, it would be a bug related to the linux environment, because windows manages to compile the app without too much trouble. So I will close the issue, for now at least. Thanks to the team anyway 😄

**Comment by HelloEdit** [comment]
Please read [this issue](https://github.com/oblador/react-native-vector-icons/issues/480)

**Comment by elcorders** [comment]
[How i manage to Solve it](https://github.com/facebook/react-native/issues/4968#issuecomment-304533784)

and after the force install you might run in to a problem with the example directory

in `ignite/DevScreens/PluginExampleScreen.js`
replace

```javascript
import '../Examples/Components/animatableExample.js.ejs'
import '../Examples/Components/vectorExample.js.ejs'
```
With
```javascript
import '../Examples/Components/animatableExample'
import '../Examples/Components/vectorExample'
```

and check the `Examples/Components` it might me missing so copy paste the folder form a clean installation

this all happened in windows, and i use powershell FYI

**Comment by HelloEdit** [comment]
Thank you !
