### ISSUE TITLE
DeviceInfo native module is not installed correctly 

### ISSUE THREAD

**Issue by israelws** [infinitered/ignite#1074]
Hey ignite team.

There is an issue I have here.

OS/Env:
MacOS Sierra (10.12.5)
Node v7.7.4
ignite 2.0.0-rc2

I created new ignite project, choose Developer Screens, Vector-Icons, i18n. 
When I'm running react-native run-ios, I'm getting the red-screen on the ios simulator with the following message:
"DeviceInfo native module is not installed correctly"

Cheers,
Israel

**Comment by skellock** [comment]
This was fixing recently. Make sure you have the latest version of `ignite-cli`. There was an issue with `ignite-devscreens` where it wasn't installing `react-native-device-info`.

**Comment by brobey8** [comment]
@skellock Not fixed.. Experiencing the same issue when I ignite new a project with a fresh install:

Node v8.1.2
ignite-cli@2.0.0-rc.2

Any ideas to fix?
