### ISSUE TITLE
Can not run project after ignite new MyNewApp

### ISSUE THREAD

**Issue by maobon** [infinitered/ignite#1075]
xinbob:MyIgniteDemo xinbob$ react-native run-android
Scanning 747 folders for symlinks in /Users/xinbob/workspace-cheerup/react.native.learn/MyIgniteDemo/node_modules (5ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-device-info'.
      > Could not resolve all dependencies for configuration ':react-native-device-info:_debugPublishCopy'.
         > Could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1.
           Required by:
               MyIgniteDemo:react-native-device-info:unspecified > com.facebook.react:react-native:0.42.3-atlassian-1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.728 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by skellock** [comment]
See #1073
