### ISSUE TITLE
Why is `ignite new MyProject` not using latest react-native?

### ISSUE THREAD

**Issue by marsonmao** [infinitered/ignite#1078]
I found that ignite created the project with `"react-native": "0.42.0"`, why is that? Why not creating the project with 0.44?

**Comment by skellock** [comment]
Because ignite is a collection of components and those components all need to play nicely together. And sometimes they don't all cooperate when React Native's version increases.

Luckily, it's your call though.  `ignite new HoldMyBeer --react-native-version 0.45.0-rc.2`

**Comment by marsonmao** [comment]
Great, that option looks promising. 
Just one more question, do I have all corresponding dependencies being installed properly with this option? Will I have RN 0.45 + corresponding React version installed?

P.S. Asides from this answer,  I've just tried manually execute `npm i react-native@latest --save` and `npm i react@16.0.0-alpha.6 --save` and those worked well; just want to make some notes.

**Comment by skellock** [comment]
Yup!  That option you set feeds directly into `react-native init --version xxx`.  So you're setting up `0.45.0-rc.2` and **it's** dependencies (`react@16.0.0-alpha.12`).

I added that pass thru for the same reasons you're asking about.  Sometimes you just wanna forge ahead, dependencies-be-damned.  =)

Glad it's working for ya.

**Comment by marsonmao** [comment]
Greeeeeat! Thanks, and dependencies-be-damned +1!

**Comment by jamonholmgren** [comment]
Latest version (almost ready to be released) will use 0.45.1.
