### ISSUE TITLE
Locating dev screens, icons, internationalisation & animation not being found

### ISSUE THREAD

**Issue by friek108** [infinitered/ignite#1081]
When running the installer, I get the following issues with the development screens, vector icons, internationlisation and animation libraries. They don't get installed when I generate a new app. Results are as below:

> An unfair headstart for your React Native apps.
> https://infinite.red/ignite
> 
> -----------------------------------------------
> 
> 🔥 igniting app IgniteApp2
> √ using the Infinite Red boilerplate v2 (code name 'Andross')
> √ added React Native 0.42.3 in 201.59s
> ? Would you like Ignite Development Screens? Yes
> ? What vector icon library will you use? react-native-vector-icons
> ? What internationalization library will you use? react-native-i18n
> ? What animation library will you use? react-native-animatable
> √ added ignite-ir-boilerplate in 50.06s
> The filename, directory name, or volume label syntax is incorrect.
> The filename, directory name, or volume label syntax is incorrect.
> The filename, directory name, or volume label syntax is incorrect.
> The filename, directory name, or volume label syntax is incorrect.
> The filename, directory name, or volume label syntax is incorrect.
> √ configured git
> √ ignited IgniteApp2 in 326.54s
> 
> Ignite CLI ignited IgniteApp2 in 326.54s
> 
> To get started:
> 
>   cd IgniteApp2
>   react-native run-ios
>   react-native run-android
>   ignite --help
> 
> Read the walkthrough at https://github.com/infinitered/ignite-ir-boilerplate/blob/master/readme.md#boilerplate-walkthrough
> 
> Need additional help? Join our Slack community at http://community.infinite.red.
> 
> Now get cooking!

---
Steps to reproduce

`ignite new IgniteApp2`

---
`ignite doctor` results:

System
  platform           win32                                                      
  arch               x64                                                        
  cpu                4 cores        Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
  directory          C:\ReactApps                                               

JavaScript
  node               8.0.0        C:\Program Files\nodejs\node.EXE
  npm                5.0.0        C:\Program Files\nodejs\npm.CMD
  yarn               0.24.6       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0-rc.2   C:\Users\Fred\AppData\Roaming\npm\ignite.CMD 

Android
  java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
  android home       -            c:\Users\Fred\AppData\Local\Android\sdk

**Comment by skellock** [comment]
Can you try that with a --debug switch? It’ll be more verbose with logging that might provide some clues.  I’m not familiar with windows but I haven’t seen that error yet.

**Comment by brandedcow** [comment]
Same error here, run with a --debug. 
Happens only on the newer ignite-ir-boilerplate. ignite-ir-boilerplate-2016 installs properly.
console:

√ added React Native 0.45.1 in 29.46s
22:58:43 [ignite] changed to directory C:\ReactNativeProjects\LeagueApp\LeagueAp
p
? Would you like Ignite Development Screens? Yes
? What vector icon library will you use? react-native-vector-icons
? What internationalization library will you use? react-native-i18n
? What animation library will you use? react-native-animatable
22:58:53 [ignite] running add command
22:58:53 [ignite] installing C:\ReactNativeProjects\LeagueApp\LeagueApp/node_mod
ules/ignite-ir-boilerplate from source npm
\ adding ignite-ir-boilerplate22:58:54 [ignite] ignite-ir-boilerplate 2.0.0 on n
pm.
22:58:54 [ignite] yarn add ignite-ir-boilerplate --dev
/ adding ignite-ir-boilerplate22:59:17 [ignite] finished yarn command
22:59:17 [ignite] requiring ignite plugin from C:\ReactNativeProjects\LeagueApp\
LeagueApp/node_modules/ignite-ir-boilerplate
22:59:17 [ignite] running add() on ignite plugin
√ added ignite-ir-boilerplate in 23.15s
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
√ configured git
√ ignited LeagueApp in 63.01s

    Ignite CLI ignited LeagueApp in 63.01s

    To get started:

      cd LeagueApp
      react-native run-ios
      react-native run-android
      ignite --help

    Read the walkthrough at https://github.com/infinitered/ignite-ir-boilerplate
/blob/master/readme.md#boilerplate-walkthrough

    Need additional help? Join our Slack community at http://community.infinite.
red.

    Now get cooking! ?

22:59:17 [ignite] finished boilerplate
22:59:17 [ignite] cleaning temporary files
22:59:17 [ignite] moving contents of LeagueApp into place
22:59:17 [ignite] removing unused sub directory LeagueApp
22:59:17 [ignite] finished running new

**Comment by justinlok** [comment]
Same issue here and it is also solved for me by using ignite-ir-boilerplate-2016, however now react-native run-android no longer works. Likely an unrelated issue.

**Comment by endru-ralali** [comment]
I solved the issue by compiling Ignite from source code on GitHub. See #1082.
