### ISSUE TITLE
Listview sections generator naming

### ISSUE THREAD

**Issue by tmaly1980** [infinitered/ignite#1085]
The generator for the ListView sectioned screen doesn't rename the class to what we provide it, it's still ListviewSectionsExample in the file, even though the filename is what it should be (user provided). If I generate a Listview that does NOT use sections, those boilerplate containers are class named properly.

**Comment by skellock** [comment]
Oops.  Would you mind filing this issue over in https://github.com/infinitered/ignite-ir-boilerplate ? Thx!
