### ISSUE TITLE
Generator supporting subfolder structure

### ISSUE THREAD

**Issue by tmaly1980** [infinitered/ignite#1086]
Any plans on supporting subfolders within the generators? Specifically, I am creating many small components all for one screen, while having several screens in my app. In the end I will probably have 30-40 components in my app, mainly to keep logic, styling, JSX, and testing more modularly. Specifically I'm using StorybookUI to refine my component designs/testing.

The App/Components folder is getting pretty cluttered and if I could run something like` ignite g component Product/Review` to generate `App/Components/Product/Review.js` (instead of `App/Components/ProductReview.js`), it would help with organization. The respective stylesheet would have to be put into the same respective subfolder under `App/Components/Product/Styles/Review.js`

**Comment by skellock** [comment]
The boilerplate’s generators [conrol this](https://github.com/infinitered/ignite-ir-boilerplate/blob/master/commands/component.js#L23).

The `target` parameter of `generate` would have to add an extra path. You could feed it one if you detected the some path separators in the `name`.

A PR for this would be warmly received over in https://github.com/infinitered/ignite-ir-boilerplate ! ;)
