### ISSUE TITLE
Compatible Bluetooth library

### ISSUE THREAD

**Issue by inev** [infinitered/ignite#1087]
---
What's going on?

I want to use a bluetooth library with react and I can't seem to get `react-native-ble-plx` to work. `react-native run-android` works before installing the library, but afterward, it doesn't work.
---
Steps to reproduce
1. Create new app with native base boilerplate `ignite new appname --boilerplate native-base-boilerplate`
2. Install `npm install --save react-native-ble-plx`
3. Attempt to run `react-native link` and it won't work. `react-native run-android` doesn't work either. 

While installing `react-native-ble-plx`I get the following warning as well:
```
Error: Cannot find module 'strip-ansi'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Development\Viduthi\mobile\node_modules\chalk\index.js:4:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

---
`ignite doctor` results:
```
System
  platform           win32
  arch               x64
  cpu                4 cores                         Intel(R) Core(TM) i5-63
  directory          C:\Development\Viduthi\mobile

JavaScript
  node               8.1.2        C:\Program Files\nodejs\node.EXE
  npm                5.0.3        C:\Program Files\nodejs\npm.CMD
  yarn               0.24.6       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0-rc.2   C:\Users\aaa\AppData\Roaming\npm\ignite

Android
  java               -            C:\Program Files\Java\jdk1.8.0_131\bin\jav
  android home       -            C:\Users\aaa\AppData\Local\Android\Sdk
```

**Comment by skellock** [comment]
Looks like you are using npm 5. There’s been some issues reported with that and dependencies.  Can you try removing your node_modules directory and typing `yarn`?

**Comment by inev** [comment]
@skellock sorry for the late reply. I did that and got:
```
 ERROR  ENOENT: no such file or directory, scandir 'C:\Development\Viduthi\mobile\node_modules\react-native-ble-plx\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\anim'
{"errno":-4058,"code":"ENOENT","syscall":"scandir","path":"C:\\Development\\Viduthi\\mobile\\node_modules\\react-native-ble-plx\\android\\build\\intermediates\\exploded-aar\\com.android.support\\appcompat-v7\\23.0.1\\res\\anim"}
Error: ENOENT: no such file or directory, scandir 'C:\Development\Viduthi\mobile\node_modules\react-native-ble-plx\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\anim'
```

**Comment by skellock** [comment]
Are you able to install that Bluetooth library on a standard `react-native init` without ignite?

**Comment by inev** [comment]
@skellock running it with just `react-native init` and then installing the bluetooth library works after deleting node_module and typing `yarn`.

**Comment by jamonholmgren** [comment]
Closing as this is quite old -- please open a new issue if it's still a problem.
