### ISSUE TITLE
react-native-cli must be installed globally?

### ISSUE THREAD

**Issue by vinogradov** [infinitered/ignite#1088]
`./node_modules/.bin/ignite new PizzaApp`
`Missing react-native-cli. Install with npm i -g react-native-cli and try again.`

Well, what if I don't want to install `react-native-cli` globally? I have different versions of react native for every project. So having the globally installed react-native/react-native-cli doesn't make any sense for me.

**Comment by skellock** [comment]
`react-native-cli` will dispatch the commands to your project’s `react-native` cli. You should be fine to set it up globally.

We only use it for the `init` command though.

How do you set up new React Native projects on your end without a global install?

**Comment by vinogradov** [comment]
@skellock thanks for the response.
> How do you set up new React Native projects on your end without a global install?

`yarn add react-native-cli`
`./node_modules/.bin/react-native-cli init`

I don't create new projects every day usually. So it's totally fine to add extra `./node_modules/.bin/` 

My point is that if a package depends on another package this dependency should be declared explicitly (in `package.json`)

**Comment by skellock** [comment]
I didn't realize you could create the projects like that.  Interesting.  I'm on mobile atm, but I'll give that a shot.  If it's supported by react-native, then we can problem add support for this too.

**Comment by jamonholmgren** [comment]
Interesting.

**Comment by mdsaddam** [comment]
Install globally using following command 

`yarn global add react-native-cli`

**Comment by kevinvangelder** [comment]
Globally installing `react-native-cli` is the official way to initialize a react-native project. At this point it is unlikely that we will support this abnormal use-case, unless someone wants to submit it as a pull request.

**Comment by mact200590** [comment]
react-native is not recognized as an internal or external command operable program or batch file
i try it all but nothing work

**Comment by jamonholmgren** [comment]
@mact200590 Can you run `react-native` from your command line?

**Comment by mact200590** [comment]
thanks a lot, i just dele all the modules, and install de depencies again
