### ISSUE TITLE
RoundedButton disabled true or false... ?? too bad but the work is Ok

### ISSUE THREAD

**Issue by alexmarton** [infinitered/ignite#1089]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

---
Steps to reproduce

---
`ignite doctor` results:

**Comment by jamonholmgren** [comment]
Hey @alexmarton , can you provide more info about this?
