### ISSUE TITLE
proposal to add tcomb form native or any other best form or integrate it without breaking future release

### ISSUE THREAD

**Issue by steve21124** [infinitered/ignite#109]
What is the right way to propose new component for ignite? or if we want to keep ignite to base class only. how should I integrate ignite with https://github.com/gcanti/tcomb-form-native separately and it will compatible with ignite for future upgrade?
- [x ] ignite base application

the idea is to use

ignite generator screen formschema.json => this will generate screen with form that automatically wired to backedn with realm storage

**Comment by steve21124** [comment]
and also planning to use realm for react native. what will be the best way to integrate it
https://realm.io/news/introducing-realm-react-native/

thanks

**Comment by GantMan** [comment]
Awesome!   I'm reading up on both now!

One of the things we're gearing towards in a composable RN project.  It's our ignite 2.0 roadmap.  So we can make a generated app with features and code depending on what kind of project you need.

These would be great features!   We'll need to focus on making generators for these for now, so they can be optional upgrades.   Let's see about laying out the groundwork for what would be involved for both of these.

**Comment by steve21124** [comment]
rethinkdb open source real  remote backend.
https://github.com/rethinkdb/horizon

if I want to integrate it. where in the code Store.js should I changed?
https://github.com/infinitered/ignite/blob/master/ignite-base/App/Store/Store.js
https://github.com/dferber90/horizon-react-native

**Comment by ahmed1490** [comment]
https://github.com/MichaelCereda/react-native-form-generator

**Comment by skellock** [comment]
I'd love to see a good form generator. With Ignite 2.0, this could be a great plugin someone could make.

**Comment by hhsadiq** [comment]
Any opinion on better choice for working with forms and ignite. I am inclined toward tcomb, but would love to hear you opinions.
