### ISSUE TITLE
ENOENT no such file or directory , uv_chdir

### ISSUE THREAD

**Issue by naza13** [infinitered/ignite#1090]
I tried to create a new project with the ''new'' command but I always have this error

**Comment by jamonholmgren** [comment]
Hey @naza13 , does [this](https://github.com/infinitered/ignite-ir-boilerplate-2016/issues/11#issuecomment-288076176) solve your problem?

**Comment by naza13** [comment]
@jamonholmgren no,I tried but it didn't work

**Comment by naza13** [comment]
I made a debug and it seems it can't install boilerplate

**Comment by jamonholmgren** [comment]
@naza13 Can you provide more information about this?

**Comment by naza13** [comment]
@jamonholmgren when I try to create a new project with the ignite command ''new''  it seems that it can't install ignite boilerplate.
![screenshot from 2017-06-23 20 51 59](https://user-images.githubusercontent.com/9498446/27496459-4b20e8fa-5856-11e7-9b39-ce75f93cacda.png)

**Comment by moomanjohnny** [comment]
@naza13 Just had this problem, I fixed it by deleting the node_modules directory in my home folder.
Check to see if you have a node_modules folder in your home directory and if you do, delete it and try again.

**Comment by johnpanos** [comment]
@naza13 Just had this problem, I fixed it by deleting the node_modules directory in my home folder.
Check to see if you have a node_modules folder in your home directory and if you do, delete it and try again.

**Comment by naza13** [comment]
You mean in the folder where the project is?

Il 25 lug 2017 5:13 AM, "johnpanos" <notifications@github.com> ha scritto:

**Comment by johnpanos** [comment]
@naza13 No I mean your home directory. You can get there by typing "cd ~" into your terminal, then type "ls" and if there is a node_modules folder in there delete it.

**Comment by jamonholmgren** [comment]
Did that work, @naza13 ?

**Comment by naza13** [comment]
Sorry but I didn't try, I am away from my laptop for a while

Il 29 lug 2017 12:32 AM, "Jamon Holmgren" <notifications@github.com> ha
scritto:

**Comment by adrienarnd** [comment]
It's work for me. Thanks all.
