### ISSUE TITLE
Whenver I try to install CLI i get  Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by jpca999** [infinitered/ignite#1092]
![image](https://user-images.githubusercontent.com/1026325/27513341-7a2517fe-5930-11e7-80b3-dd059ade7270.png)

I had been using yarn for a while, is it coz of that ?

### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

---
Steps to reproduce

---
`ignite doctor` results:

**Comment by jamonholmgren** [comment]
Hm, I wouldn't recommend installing `ignite-cli` with `sudo`, can you try without that?

**Comment by jpca999** [comment]
Same result

**Comment by skellock** [comment]
I've seen this issue twice.  Once when people use `npm 2`, and sadly recently, using `npm 5`.  Not sure if they have the sorted yet.

What does your `ignite doctor` look like?
