### ISSUE TITLE
Adding a redux example to DevScreens.

### ISSUE THREAD

**Issue by TitanKing** [infinitered/ignite#1096]
First of all thanks for the awesome framework.

The only thing I found missing was any kind of example of how to implement a proper redux example on any of the screens. Navigation does have redux but that is not really a suitable example. I still have to find a good solution to implement redux.

Thanks for all the hard work.

**Comment by jamonholmgren** [comment]
Sweet, thanks for the kind words, I think you're right. @GantMan any ideas here?

**Comment by GantMan** [comment]
Yup!   We have the screen generator which will give you a redux based screen, but I agree.   We could probably put together a decent set of examples to help people.  Jamon, let's discuss this sometime.  Like an "Intro to RN with Ignite" kinda thing.

**Comment by kevinvangelder** [comment]
Since Bowser does not use Redux we won't be implementing this feature, but we'd be happy to consider any community PRs on it.
