### ISSUE TITLE
Cannot create new app with Ignite 2

### ISSUE THREAD

**Issue by phuongpt** [infinitered/ignite#1098]
<img width="801" alt="screen shot 2017-06-28 at 4 50 23 pm" src="https://user-images.githubusercontent.com/4443583/27631223-0fbcc16a-5c22-11e7-9a0b-503e91188f3a.png">
I don't know what's wrong here, no problem with version 1

**Comment by phuongpt** [comment]
I can create new project by `ignite boilerplate-install ir-boilerplate abc`, but got this error 
<img width="1111" alt="screen shot 2017-07-06 at 10 49 30 am" src="https://user-images.githubusercontent.com/4443583/27894843-d92cc93e-6238-11e7-919e-6c29f23d4369.png">

**Comment by GantMan** [comment]
Hi @phuongpt - I was able to create an app with Ignite just now, with no problem.

From your first message I don't see any errors or any output at all!?  Any feedback that can help?


As for the failed JEST tests, that's due to the enzyme not supporting 0.45.1 yet.  AirBnB claims they will support it when React 16 is out of beta/alpha

**Comment by phuongpt** [comment]
FYI @GantMan 
<img width="566" alt="screen shot 2017-07-06 at 11 02 41 am" src="https://user-images.githubusercontent.com/4443583/27895142-ca77c37e-623a-11e7-8a26-f2c92fa7cc0b.png">

**Comment by jamonholmgren** [comment]
@phuongpt I probably wouldn't name your app `app`. Maybe try:

```
ignite new Foo --min
```

Does this work?

**Comment by nemoNoboru** [comment]
Got exactly the same issue. 
`ignite new Foo` and `ignite new Foo --min` throws the same error:
`undefined is not and object (evaluating 'regeneratorRuntime.mark')`

**Comment by jamonholmgren** [comment]
@nemoNoboru Trying to spin one up now, back at you shortly.

**Comment by jamonholmgren** [comment]
Getting the same error. This has something to do with the generator function. Investigating.

**Comment by jamonholmgren** [comment]
This is related to https://github.com/ben-hunter-hansen/angular-async-await/issues/11.

They're also using regenerator: https://github.com/ben-hunter-hansen/angular-async-await/blob/master/dist/angular-async-await.js#L56

**Comment by jamonholmgren** [comment]
Well...I'm a bit stumped, and headed to bed. @skellock perhaps you have some ideas on this? Some dependency causing the [generator](https://github.com/facebook/regenerator) engine to not be loaded?

**Comment by rochapablo** [comment]
+1

**Comment by JohnKanev** [comment]
I have the same exact error
i updated my node to 8.10 like one hour ago
maybe that's the problem

**Comment by GantMan** [comment]
Yeah, I have node 7.7.4 on this laptop.  I'll upgrade to 8.x and see if the issue comes from that.

**Comment by ernoaapa** [comment]
Had same problem as @phuongpt screenshot. Solved by changing how sagas are exported as described here https://github.com/facebook/react-native/issues/14838#issuecomment-313398604

In `App/Sagas/index.js`:
```
export default function * root () {
```
To:
```
const root = function * root () {
  // ... snip
export default root
```

And similar change to the both sagas.

**Comment by JeffreyJamesMMM** [comment]
I am on Win 7 with nodejs 8.10.0 and I get the same issue when creating a new app with the --max flag.

**Comment by skellock** [comment]
It's because generators are not being compiled when they exist as functions, but they are if they're coerced into an expression and jammed into a variable first.

So as @ernoaapa points out above:

`function * boo () {}` is now 💩  but `const yay = function * () {}` is 👍 .

I believe this to be an upstream issue (upstream from react-native i mean), but haven't found the source just yet.  I suspect it's a babel plugin that got upgraded recently that contains this bug. To target generators, your AST selectors would need to look for both function declarations and expressions.

My recommendation is to stay on 45.x short term.

But if that's not how you roll, convert your generators to be expressions.

Tricksy.

**Comment by skellock** [comment]
Ok, looks like facebook is on this issue, so I'm stepping off for now.

Another workaround is to delete your `.babelrc` file.  Which sucks if you have valuable stuff in there.

I reckon this will be fixed shortly.

**Comment by jamonholmgren** [comment]
Yeah, just saw this tweet by @grabbou which seems to reference it: https://twitter.com/grabbou/status/882927535855722496

He recommends using Haul to fix it.

**Comment by skellock** [comment]
This issue was slightly different than the `transform-runtime` missing dependency though.  Related though.  This issue is an issue with Haul though.  I tested that today.

**Comment by grabbou** [comment]
Thanks for CC-ing me here! I already answered in the react-native repository, this could've been fixed here: https://github.com/facebook/react-native/commit/e7c1cf5b7d2eba9468804635d0c2a0fc6725e42a

Haven't tested it - should be inside 0.47-rc.

**Comment by jamonholmgren** [comment]
Awesome, thanks @grabbou !

**Comment by tmaly1980** [comment]
@ernoaapa , unfortunately, the root trigger of this error for me is NavigationRedux.js, not a saga file. I've disabled all the sagas AND did your suggestion to Sagas/index.js and Sagas/*, with no help. I've removed my .babelrc too. No help.

This is silly that I just installed a fresh ignite boilerplate app and I can't even get the launch screen running. What can I do as a last resort? I need to move my project forward, I can't afford to wait several days (let alone a week) for a solution. I can't afford to be using alpha code that breaks. Why do I have an ignite-based app I started a month ago work fine, and this one not?

I'm noticing this happens only on android, iOS is fine. What gives?

**Comment by hungdev** [comment]
@ernoaapa it still error

**Comment by benjaminhorner** [comment]
@jamonholmgren CC @grabbou : Any updates on this issue? The error is still there if you try with the demo project.

**Comment by grabbou** [comment]
Waiting for metro-bundler to release a new version with the fix and going
to bump it.

**Comment by tastycode** [comment]
This definitely blocked me from being able to use Ignite for a project with a tight deadline. I tried the `const foo = function * foo()` trick and got a more cryptic error.

![image](https://user-images.githubusercontent.com/809953/28002044-0a6a88d6-64f7-11e7-9a48-5bb81e888f28.png)

This is based on following the instructions in README.md (PizzaApp), then trying the fix above. Here's my full diff from what ignite-cli produced. 

```
diff --git a/App/Sagas/GithubSagas.js b/App/Sagas/GithubSagas.js
index 2b562c3..b49547e 100644
--- a/App/Sagas/GithubSagas.js
+++ b/App/Sagas/GithubSagas.js
@@ -2,7 +2,8 @@ import { call, put } from 'redux-saga/effects'
 import { path } from 'ramda'
 import GithubActions from '../Redux/GithubRedux'
 
-export function * getUserAvatar (api, action) {
+
+const getUserAvatar = function * getUserAvatar (api, action) {
   const { username } = action
   // make the call to the api
   const response = yield call(api.getUser, username)
@@ -16,3 +17,5 @@ export function * getUserAvatar (api, action) {
     yield put(GithubActions.userFailure())
   }
 }
+
+export default getUserAvatar
diff --git a/App/Sagas/StartupSagas.js b/App/Sagas/StartupSagas.js
index 8cc37ae..0dd3207 100644
--- a/App/Sagas/StartupSagas.js
+++ b/App/Sagas/StartupSagas.js
@@ -6,7 +6,7 @@ import { is } from 'ramda'
 export const selectAvatar = (state) => state.github.avatar
 
 // process STARTUP actions
-export function * startup (action) {
+const startup = function * startup (action) {
   if (__DEV__ && console.tron) {
     // straight-up string logging
     console.tron.log('Hello, I\'m an example of how to log via Reactotron.')
@@ -38,3 +38,5 @@ export function * startup (action) {
     yield put(GithubActions.userRequest('GantMan'))
   }
 }
+
+export default startup
diff --git a/App/Sagas/index.js b/App/Sagas/index.js
index 18a9fd1..0793cc3 100644
--- a/App/Sagas/index.js
+++ b/App/Sagas/index.js
@@ -21,7 +21,7 @@ const api = DebugConfig.useFixtures ? FixtureAPI : API.create()
 
 /* ------------- Connect Types To Sagas ------------- */
 
-export default function * root () {
+const root = function * root() {
   yield [
     // some sagas only receive an action
     takeLatest(StartupTypes.STARTUP, startup),
@@ -30,3 +30,4 @@ export default function * root () {
     takeLatest(GithubTypes.USER_REQUEST, getUserAvatar, api)
   ]
 }
+export default root
```

I briefly tried bumping to 0.47rc-1 of react-native, but ran into another cryptic error. Most likely because i updated react-native inside package.json after ignite-cli already generated the project. I looked into forking ignite-cli to use the newer version from the beginning, but didn't see a direct dependency for react-native inside ignite's package.json. It wasn't immediately clear how to get ignite-cli to use a newer version of react-native for project generation.

If it helps, here's the output of `ignite doctor`

```
ignite doctor
System
  platform           darwin
  arch               x64
  cpu                4 cores                             Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
  directory          /Users/tastycode/dev/ConcrnClient

JavaScript
  node               8.1.3        /Users/tastycode/.nvm/versions/node/v8.1.3/bin/node
  npm                5.0.3        /Users/tastycode/.nvm/versions/node/v8.1.3/bin/npm
  yarn               0.27.5       /Users/tastycode/.nvm/versions/node/v8.1.3/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.45.1

Ignite
  ignite             2.0.0        /Users/tastycode/.nvm/versions/node/v8.1.3/bin/ignite

Android
  java               1.8.0_131    /usr/bin/java
  android home       -            undefined

iOS
  xcode              8.3.3
```

Best of luck!

**Comment by fredbt** [comment]
Same issue happening here.

**Comment by fredbt** [comment]
For me, deleting .babelrc worked.

This was the content of the file generated by ignite CLI:

{
  "presets": ["react-native"],
  "env": {
    "production": {
      "plugins": ["ignite-ignore-reactotron"]
    }
  }
}

**Comment by jbreuer95** [comment]
I just downgraded babel-preset-react-native to 2.0.0 and got it working

**Comment by fredbt** [comment]
@jbreuer95 I had to do the same in another project.

**Comment by nikitph** [comment]
i cant get a created app to get to work . seems related. deleted babelrc and downgraded babel-preset-react-native to 2.0.0
![simulator screen shot jul 10 2017 8 07 57 pm](https://user-images.githubusercontent.com/5007879/28049343-8f366a1c-65ab-11e7-8a54-ae06d9646ab2.png)

**Comment by hungdev** [comment]
@nikitph just downgraded babel-preset-react-native to 2.0.0, don't need to delete babelrc  file.  Run npm install and react-native run-android. it worked for me.

**Comment by fyodorvi** [comment]
downgraded babel-preset-react-native to 2.0.0, still getting same error

**Comment by endru-ralali** [comment]
Yup, downgraded babel-preset-react-native to 2.0.0 works for me.

`npm install --save babel-preset-react-native@2.0.0`
`npm install --save-dev babel-preset-react-native@2.0.0`

**Comment by hungdev** [comment]
you can clone and compair with your project. this project is clean.
https://github.com/hungdev/Revler

**Comment by devanshsadhotra** [comment]
i faced the similar error using ignite, 
i upgraded react-native version to "0.46.0" and down graded babel-preset-react-native to "2.0.0" and it worked fine

**Comment by kcalmes** [comment]
@fyodorvi Make sure to clear your caches. 
```
watchman watch-del-all
rm -rf ./node_modules
rm -rf $TMPDIR/react-*
npm start -- --reset-cache
```

Make sure all of these commands complete successfully.

**Comment by fyodorvi** [comment]
@kcalmes thanks, cleaning the cache helped

**Comment by chrisbull** [comment]
Just installed ignite for the first time. 
Was getting all the issues above. 
What finally worked for me was essentially everything people mentioned above.

**Step 1**
In the package.json file, I changed 
`react-native` to version `0.46.0` and
`babel-preset-react-native` to `2.0.0`

**Step 2**
iOS Simulator -> Reset Content and Settings 

**Step 3**
```
watchman watch-del-all
git clean -xdf
rm -rf $TMPDIR/react-*
yarn install
react-native run-ios
```

**Comment by nikitph** [comment]
Aren't there smoke tests for this very thing. I mean I love ignite but this
might turn off new comers

**Comment by jqn** [comment]
@nikitph you got that right. I wanted to start using ignite for a new project but I had to turn away because of this error.

**Comment by nikitph** [comment]
@jqn its really great.... i urge you to give another shot... although its ironic having to write this in an issue report

**Comment by zicrox** [comment]
I downgraded babel-preset-react-native to "2.0.0" and it worked fine without changing the react-native version.

**Comment by skellock** [comment]
Ya there was an upstream dependency upgrade that pretty much blew up the React Native universe. It was a bumpy few days.

I’ll take another look today at how we are referencing our dependencies.

**Comment by tmaly1980** [comment]
CAREFUL of @chrisbull 's command list, `git clean -xdf` will WIPE OUT any files not committed into the repo. I just lost a bunch of files. =(

**Comment by tmaly1980** [comment]
@skellock Wouldn't it be as simple as changing the package.json to specifically reference babel-preset-react-native to "2.0.0", rather than leaving people in limbo while we wait for those developers to fix that issue?

**Comment by skellock** [comment]
@tmaly1980 : yes, that sounds like a good plan.  I'll give that a try.

**Comment by jqn** [comment]
Downgrading babel preset also worked for me
npm install --save babel-preset-react-native@2.0.0
npm install --save-dev babel-preset-react-native@2.0.0

**Comment by liambrownweb** [comment]
The babel preset solution seems to be hit and miss; some people are getting results, and some people aren't. I'm firmly in the latter camp with Node 8.1.4 on Linux; I've tried several times with brand-new test projects, and it hasn't worked yet.

**Comment by skellock** [comment]
I had no issues with Linux (elementary & node 8.1.4) here @liambrownweb.  If you're upgrading, don't forget to run `npm run start -- --reset-cache` as there will be some babel cache artifacts ruining the party.

**Comment by juvasquezg** [comment]
Hi,

Not worked for my in Android.

```bash
react-native run-android
```

```
react-native 0.42
node 8.0.0
npm 5.3
```

When i run 

```
react-native run-ios
```

It works perfect but not in Android.

**Comment by juvasquezg** [comment]
Hi,

Again

```bash
yarn add babel-preset-react-native@2.0.0
```
worked for me.

**Comment by liambrownweb** [comment]
@skellock Node 8.1.4 was the solution. Installed and ran with no problems. Definitely worth the trouble; you guys are doing a nice job with this tool.

I'm running OpenSuSE Leap 42.2 in a virtual machine. Same environment where I reported the failure to run earlier, but when I upgraded Node to 8.1.4, it started working. Anybody else, give me a thumbs-up if that version fixes the problem in your setup.

**Comment by jamonholmgren** [comment]
Awesome, thanks for the feedback @liambrownweb ! @phuongpt and others, is it okay to close this issue now?

**Comment by devanshsadhotra** [comment]
@jamonholmgren  you may proceed

**Comment by bamne123** [comment]
Following commands worked for me.

ignite new <appname> --max
rm -rf ./node_modules
npm install
react-native run-ios

**Comment by stempest0925** [comment]
My English is not very good, here is the machine translation.
This is a problem that may occur when the version downgrade 0.56 down 0.55.4, the version of babel-preset-react-native used is 2.1.0.

Resolution process:
Try to reduce the node version to 8, babel-preset-react-native is changed to 2.0.0, use native run-android and start --reset-cache will solve this problem.

Hope it works for you~
