### ISSUE TITLE
Device Details Screen

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/ignite#110]
- [X] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [X] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

**Comment by GantMan** [comment]
I'm thinking @fvonhoven - this would be good for you.   @kevinvangelder  and I could take more pair-driven tasks.

**Comment by kevinvangelder** [comment]
Resolved by #120
