### ISSUE TITLE
npm install removes all modules

### ISSUE THREAD

**Issue by WwoeSsi** [infinitered/ignite#1101]
---
What's going on?
When I hit npm install --save react-native-vector-icons, it removes all modules and the whole app breaks. I don't know how to fix this :(
I get this after npm installing: added 2 packages, removed 717 packages and updated 61 packages in 41.429s

---
Steps to reproduce

I installed ignite with ignite new ignite4 (because I f***ed up so many times)

---
`ignite doctor` results:

System
  platform           win32
  arch               x64
  cpu                4 cores                     Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  directory          C:\Users\karse\js\ignite4

JavaScript
  node               8.1.3        C:\Program Files\nodejs\node.EXE
  npm                5.0.4        C:\Program Files\nodejs\npm.CMD
  yarn               0.27.5       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0        C:\Users\karse\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\karse\AppData\Local\Android\sdk

**Comment by WwoeSsi** [comment]
Hmmmmm I might have found the problem...

Am I supposed to use yarn instead of npm?

If so, why?

I just hit yarn install and now it did install 740 packages or so...

Why doesn't npm work?

**Comment by skellock** [comment]
Good question.  I've heard about as well.  Is it [this issue](https://github.com/npm/npm/issues/16839)?

Not quite sure what's going on. 

Give `yarn` a shot and see if the results are less rage-inducing.

**Comment by WwoeSsi** [comment]
Thanks. Yeah. Yarn seems to work fine! :)

**Comment by skellock** [comment]
Ya, npm 5 is having a few problems.  Sounds like they're fixing it and should be available soon.

**Comment by xwartz** [comment]
@skellock  Did they fix it?

**Comment by skellock** [comment]
I’m not sure what their status is. Not having issues here tho. 🤞

**Comment by akuma06** [comment]
I had this issue today. Everything worked fine after a new ignite app initialization. Then I wanted to add js-base64 module with a `npm install`: it broke everything 😢. Will try with yarn if it solves it.
