### ISSUE TITLE
d

### ISSUE THREAD

**Issue by nathanielkess** [infinitered/ignite#1102]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

---
Steps to reproduce

---
`ignite doctor` results:

**Comment by jamonholmgren** [comment]
Hey @nathanielkess , was this a mistake?

**Comment by nathanielkess** [comment]
Oh, yeah. Sorry about that @jamonholmgren
