### ISSUE TITLE
Plans/Guidance for implementing infinite scroll views?

### ISSUE THREAD

**Issue by tmaly1980** [infinitered/ignite#1104]
I'd be curious if there are any plans on implementing/integrating an infinite scroll view into the listview generator? Seems it was brought up in #164, but not discussed further/elsewhere.

If there aren't any plans to integrate (since it involves modifying the API/redux/saga/etc), are there basic pointers/suggestions/tutorials? I'm currently trying to integrate react-native-infinite-scroll-view.

**Comment by nhducit** [comment]
why don't you use flatlist?

**Comment by skellock** [comment]
We, until recently were on 0.42.x. Now that we are on 45, moving to FlatList is the way to go for infinite lists. Agreed.

@tmaly1980 have a look at our ChainReact repo. There are some FlatList implementations in there you can look at in the short term.

We’ll get this into ignite shortly.
