### ISSUE TITLE
Add warning to README on using Node v8, due to debugging issues

### ISSUE THREAD

**Issue by aschrijver** [infinitered/ignite#1105]
Hi,

Thanks for the Ignite CLI and default boilerplate!

I have (almost) everything working after suffering much more time than a 5 min. no-brainer setup experience, but it appeared that Ignite was not to blame. Spent a full day on getting debugging up and running.

It appears you'll run into serious issues, blockers even when using Node `v8.*` right now. A downgrade to `7.10.1` finally solved this. See stackoverflow for details: [Debugging Jest unit tests with breakpoints in VS Code with React Native](https://stackoverflow.com/questions/45056952/debugging-jest-unit-tests-with-breakpoints-in-vs-code-with-react-native/45073796).

A warning on the README would be nice, so other Ignite users will be spared the trauma :)

One other thing, still not solved, is running the ES6 tests that come with the boilerplate. They fail. See: https://github.com/infinitered/ignite/issues/1083

Thanks.

**Comment by skellock** [comment]
Thanks for taking the time to summarize this. Really appreciate it. Any interest in doing a PR to the readme?

**Comment by aschrijver** [comment]
I think I will PR, but this will have to wait for me to find a proper solution, because my debugging nightmare continues :(

**Comment by aschrijver** [comment]
@skellock It might be an idea to provide a docker image with a complete working Ignite boilerplate environment, one which has all the right combinations of dependencies, debugging facilities, etc.

**Comment by skellock** [comment]
That's an interesting solution. I'd never even thought to consider that.

Things are going to get better though.  Once we start using lock files (yarn & npm5) and fixing our dependency versions, some of this sorrow will subside.

**Comment by aschrijver** [comment]
I am going to setup a [Rancher](https://github.com/rancher/rancher) + Gitlab continuous delivery pipeline and was thinking about such kind of docker solution for web development, allowing for - theoretically, of course - real easy flows from dev > staging > live (and rollback, if needed).
