### ISSUE TITLE
Plans for a wix react-native-navigation boilerplate?

### ISSUE THREAD

**Issue by tmaly1980** [infinitered/ignite#1106]
I'm finding react-navigation to be troublesome and not ideal, specifically dealing with updating header titles based on redux, and the cumbersome interface for altering the navigation tree (especially reset)... I've had to rely upon an unofficial package (satya64's react-navigation-addons) to really make proper use of the navigation system, and I've found that even it has some bugs.

Are there any plans for implementing a react-native-navigation (wix) boilerplate or configuration option to the existing boilerplate?

**Comment by jamonholmgren** [comment]
@tmaly1980 The way that Ignite boilerplate stack decisions are made is that we (at Infinite Red) experiment with other solutions in real world client projects, and if they work out well, we eventually bring them back to Ignite's default boilerplate. So -- we are playing with various navigation solutions, but for now, it seems that react-navigation solves more problems than the others. Wix's is interesting for sure, but no official plans (yet) to make any changes to navigation.
