### ISSUE TITLE
ignite generate container MypageName is not working 

### ISSUE THREAD

**Issue by devanshsadhotra** [infinitered/ignite#1110]
### Hey there! Ignite CLI seems to be having a problem, eh?

---
What's going on?
i am using Ignite 2.0.0 , and today started facing this issue, whenever i am running
`ignite generate container MypageName`
its throwing the following error
Error: 'import[\s\S]*from\s+'react-navigation';?' was not found in file E:\ App/Navigation/AppNavigation.js
---
Steps to reproduce
in your project folder run " ignite generate container MypageName" and you will observe that it is not adding the container I generated to AppNavigation.js file. Two days back it was working perfect.
-- | --

---
```
 System
  platform           win32
  arch               x64
  cpu                4 cores                               Intel(R) Core(TM) i5-4440S CPU @ 2.80GHz
  directory          E:\reactNativeYoungClay\youngclayrn

JavaScript
  node               8.1.3        C:\Program Files\nodejs\node.EXE
  npm                5.0.3        C:\Program Files\nodejs\npm.CMD
  yarn               0.27.5       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1
  app rn version     0.46.0

Ignite
  ignite             2.0.0        C:\Users\oserlabs\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\oserlabs\AppData\Local\Android\sdk 
```

**Comment by jamonholmgren** [comment]
Hey @devanshsadhotra , is it related to this? https://github.com/infinitered/ignite/issues/1084

**Comment by devanshsadhotra** [comment]
@jamonholmgren  yeah it is related to #1084 , and moreover this functionality worked after i restart a whole new Ignite project.

**Comment by devanshsadhotra** [comment]
@kevinvangelder please provide a solution for this
