### ISSUE TITLE
Redux example for navigation and login

### ISSUE THREAD

**Issue by Talkwondo** [infinitered/ignite#1111]
Hello everyone,
I am trying to add onPress value of a button and refer to other page. can anyone give me an example?

Thanks,

Tal

**Comment by fvonhoven** [comment]
Can you elaborate on your use case?... Where is this button? What is it referring to? etc...
If your button is a component of the other page, it sounds as though you could use a callback to trigger an action...

**Comment by DDeme** [comment]
For me starting point with examples will help. In tutorial video it shows lot more things like navigation etc.

**Comment by kevinvangelder** [comment]
For people looking for more example code than we include in Ignite, take a look at the open source app we built for our ChainReact conference: https://github.com/infinitered/chainreactapp
