### ISSUE TITLE
Adding promise handlers/transforms to API calls

### ISSUE THREAD

**Issue by tmaly1980** [infinitered/ignite#1112]
I'd like to be able to add some sort of common handlers/transforms after an API call to know whether there was an authentication (JWT) error, ie if I get a response code of 401 or 402. This wouldn't act like a normal 'failure' saga call, as I would want to do something very specific, such as route to the login screen. 

In my case, if the user's token is invalid, they should be prompted to log in again. It seems a bit cumbersome to check in every API call whether it's JWT related. And I'm not 100% sure what to do to notify the user. 

I think the best bet so far maybe is to wrap the entire app with a LoginWrapper screen/higher-order component, where if I get a JWT error, set the login redux store with the jwt error, so the screen can trigger the login form rather than the actual content.

But that still means I have to handle JWT error responses in each saga action. I'd love a way to generalize this to be an api transformer (ie promise filter), but I don't have access to redux or the navigation unless via a saga action.

**Comment by skellock** [comment]
Related: https://github.com/skellock/apisauce/issues/116

@tmaly1980 one thing you could do is pass a function into your API at creation time... this function could fire everytime your api detects an expired token (via a response transform).  Inside the function you could dispatch a message.

**Comment by nillo** [comment]
The ignite i'am using is using apisauce 

its has this
(see docs adding monitors)

```
const naviMonitor = (response) => console.log('hey!  listen! ', response)
api.addMonitor(naviMonitor)
```

this is the overal response of al actions <-- Within this response, you could check for specific error codes. u could do some general stuff there.

**Comment by kevinvangelder** [comment]
As mentioned above, this is effectively already possible.
