### ISSUE TITLE
`ignite new` fails when project name consists entirely of numbers

### ISSUE THREAD

**Issue by pekkanikolaus** [infinitered/ignite#1116]
When creating an ignite project in a project directory that consists entirely of numbers:

    ignite new 100

creation fails with the message

    ✖ failed to add React Native 0.42.0

**Comment by jamonholmgren** [comment]
### Good opportunity for new OS contributors

This one should be relatively straightforward to detect and fix. Let's not allow all-number project names.

For someone who wants to try this:

[Set up Ignite for development](https://github.com/infinitered/ignite/blob/master/docs/advanced-guides/using-development-build.md).

Create the check in this file, right below (and very similar code to) this block:

https://github.com/infinitered/ignite/blob/master/src/commands/new.js#L43-L48

Also write a test similar to this one:

https://github.com/infinitered/ignite/blob/master/tests/fast/cli/cliEmpty.test.js#L25-L40

Maybe rename that file as `cliMalformed.test.js` and just add the other test in that same file.

Ping me in the Infinite Red Community Slack if you run into problems.

**Comment by pekkanikolaus** [comment]
@jamonholmgren will give this a shot when I can!
