### ISSUE TITLE
Could not find react-native.jar

### ISSUE THREAD

**Issue by khelil** [infinitered/ignite#1117]
---
What's going on?
Can't run the app on android, get an error about a jar file...

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-vector-icons'.
      > Could not find react-native.jar (com.facebook.react:react-native:0.42.0).
        Searched in the following locations:
            file:/Users/khelil/Documents/sandbox/CIVC/node_modules/react-native/android/com/facebook/react/react-native/0.42.0/react-native-0.42.0.jar

Error happens on different component, had the error on react-native-maps before, uninstalled it and now the error is on the react-native-vector-icons

---
`ignite doctor` results:
`System`
  platform           darwin
  arch               x64
  cpu                4 cores                                Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  directory          /Users/khelil/Documents/sandbox/CIVC

`JavaScript`
  node               7.8.0        /usr/local/bin/node
  npm                4.2.0        /usr/local/bin/npm
  yarn               0.21.3       /usr/local/bin/yarn

`React Native`
  react-native-cli   2.0.1
  app rn version     0.42.0

`Ignite`
  ignite             2.0.0        /usr/local/bin/ignite

`Android`
  java               1.8.0_121    /usr/bin/java
  android home       -            /Users/khelil/Library/Android/sdk

`iOS`
  xcode              8.3.3

**Comment by robinheinze** [comment]
Make sure you don't have any stray packagers running, then can you run 'yarn newclear' and see if that helps?

**Comment by khelil** [comment]
Thanks @robinheinze ;)

`yarn newclear` + `npm cache clean --force` + `yarn install` did the job !
