### ISSUE TITLE
App is not hot reloaded on AVD (linux)

### ISSUE THREAD

**Issue by l1br3** [infinitered/ignite#1121]
---
**What's going on?**
I can't get the server to hot reload
---
**Steps to reproduce**
I ran many commands before being in this situation so it might comes from previous things.  
```bash
rm -rf app
ignite new app
cd app
npm run clean
npm run clean:android
npm start
```
* Build is lunched on device
* I get error message because server is not up with npm start
* I `npm start`
* Manual refresh on device
* my AVD load the build, progress bar both in terminal and device.  
* Then the device becomes white.  
* I run again `react-native run-android` in a new shell, the app get reinstalled and I can see DevScreens.  
* I change a file , (eg. <Text/> in App/Components/RoundedButton.js#L36), nothing happen.
* I run again `react-native run-android` in a new shell, the app get reinstalled etc ...
  
###### info: `npm run test:watch` works like a charm, files are watched and tests are run
---
**`ignite doctor` results:**
```bash
System
  platform           linux                                                                        
  arch               x64                                                                          
  cpu                4 cores                  Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz  
  directory          /home/libre/dev/app                                                       

JavaScript
  node               7.7.4        /home/libre/.nvm/versions/node/v7.7.4/bin/node  
  npm                4.1.2        /home/libre/.nvm/versions/node/v7.7.4/bin/npm   
  yarn               0.27.5       /home/libre/.nvm/versions/node/v7.7.4/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.45.1      

Ignite
  ignite             2.0.0        /home/libre/.nvm/versions/node/v7.7.4/bin/ignite  

Android
  java               1.8.0_131    /usr/bin/java            
  android home       -            /home/libre/Android/Sdk  
```
---
**Some another logs:** [just here on pastebin](https://pastebin.com/Gib6ah1x)

From https://github.com/infinitered/ignite/issues/1119, my app is not called "app" but our commercial trademark. 

#### PS: Feel free to change the title or suggest a new one

**Comment by jamonholmgren** [comment]
@l1br3 I just tried it and everything appears to have worked, but I"m on macOS and node 8.1.4 and npm 5.3.0.

**Comment by jamonholmgren** [comment]
Any other info you can provide, @l1br3 ? We don't use Linux to develop apps here at Infinite Red, so I'm not sure we can help much from our end.

**Comment by l1br3** [comment]
I could make a docker image but first can you provide instruction and tips to debug watchman ?

**Comment by l1br3** [comment]
I don't understand how it should be working. From install instructions, I just have to cd into dir and run react-native run-android but if I do only that I've got an error on the device which tell me that server is not online. Nothing is said about npm start, is this the good command to run ?

**Comment by l1br3** [comment]
Do I have to set up `.watchmanconfig` ? It is currently empty.  
I cannot see the filechange triggering anything in watchman logs...

**Comment by l1br3** [comment]
New element: after enabling watchman debug logs, I can't see that it detects fs events.  
Now I must understand how it handle commands, why the app is not getting hot reloaded.

**Comment by l1br3** [comment]
Well, a new information again. There is no trigger set for watchman.  
If I corretly understand, the watcher is set at `npm start`, but no command is associated to it. So it is totaly normal that nothing happen.  
Could you provide help on this ? Why nothing is associated to watchman trigger ?

**Comment by l1br3** [comment]
```
libre@libre:~/dev/ignited3$ watchman watch-list
{
    "version": "4.7.0",
    "roots": [
        "/home/libre/dev/ignited3"
    ]
}
```


```
libre@libre:~/dev/ignited3$ watchman trigger-list /home/libre/dev/ignited3
{
    "version": "4.7.0",
    "triggers": []
}

```

**Comment by skellock** [comment]
Does this work with react native by itself?

**Comment by l1br3** [comment]
Well, this works on my phone with expo and refresh the app for any change:  
[From react native getting started tutorial](https://facebook.github.io/react-native/docs/getting-started.html)
```bash
create-react-native-app AwesomeProject
cd AwesomeProject
npm start
```

BUT, `watchman trigger-list /home/libre/dev/AwesomeProject` returns the same:  
```bash
libre@libre:~/dev/ignited2$ watchman watch-list
{
    "version": "4.7.0",
    "roots": [
        "/home/libre/dev/AwesomeProject",
        "/home/libre/dev/ignited3"
    ]
}


libre@libre:~/dev/ignited2$ watchman trigger-list /home/libre/dev/AwesomeProject
{
    "version": "4.7.0",
    "triggers": []
}
```

So it might not be related to watchman triggers, I don't understand what happens, my knowledge of RNative ecosystem is too low.

**Comment by l1br3** [comment]
@jamonholmgren I had great hopes with trying with node 8 but still no success.

**Comment by kevinvangelder** [comment]
@l1br3 Can you try creating a blank react native app and see if hot reloading works? My guess is that there is something wrong with the combination of watchman, Linux, and AVD, and if that's the case you'll get better support for this particular issue on the react-native repo.

**Comment by l1br3** [comment]
@kevinvangelder Yes it works, actually I'm simply using this pattern to develop the app.
- create a new react native app with expo
- copy/paste ignite App dir into the Expo app
- make some changes 
- run and lunch on AVD

Everything works fine.
You don't imagine I waited 2 weeks without finding a workaround to my issue right ? ;)

**Comment by jamonholmgren** [comment]
Watchman has been problematic for us in the past, too. Not really sure what else to try at this point!

**Comment by l1br3** [comment]
This is seriously annoying as expo does not have some native features. 
Could you help me to debug watchmann ? I did not find the way to access logs.

**Comment by l1br3** [comment]
@jamonholmgren Whouaaaaa it took me 2 month to understand what was happening, thanks to a compilation error which clearly said that HMR was disabled....

Solution -> Open React Native developer menu -> enable Hot reloading ....

..................................................... speechless

**Comment by jamonholmgren** [comment]
Thanks for reporting back with your findings @l1br3 ! And for the PR!
