### ISSUE TITLE
Question: How do I upgrade dependencies' version of a project created months ago?

### ISSUE THREAD

**Issue by marsonmao** [infinitered/ignite#1124]
Hi, I created a project with `ignite new` in May, and haven't touch it since then. 

Now I'd like to continue developing it, but would like to make all dependencies designed by ignite up-to-date. 

I think I'll do `npm update -g ignite` to get the latest ignite first, but how do I then do something like `ignite update MyProject` to refresh the dependencies (package.json) of my project? For example ignite boilerplate may depends on `react 15.0` in May but `react 16.0` now, how do I get all of them up-to-date? Thanks!

**Comment by jamonholmgren** [comment]
Hey @marsonmao! We don't expose an `ignite update MyProject` unfortunately, and are unlikely to. 

There are a few options to move through React Native upgrades. [Facebook tells you](https://facebook.github.io/react-native/docs/upgrading.html#projects-built-with-native-code) to use `react-native-git-upgrade`, but from what I understand that often leads to pain. It's probably best to do [their alternate method](https://facebook.github.io/react-native/docs/upgrading.html#alternative). As a third option, you can generate a brand-new Ignite project and copy over your modified application files.

Hope this helps!

**Comment by marsonmao** [comment]
Thanks for the reply!

I think the 3rd option is the best for me, although I gave the example of react version, actually I want to do a full upgrade of the ir boilerplate. I'll try 3rd option and study the other ones, they are also very important knowledge. Thanks!
