### ISSUE TITLE
Question: Implementing Facebook login

### ISSUE THREAD

**Issue by MythicalFish** [infinitered/ignite#1127]
Hi,

I want to implement Facebook login, using [ignite-example-login](https://github.com/infinitered/ignite-example-login) as a guideline.

However my android build fails with [react-native-fbsdk](https://github.com/facebook/react-native-fbsdk) installed:

`MainApplication.java:29: error: constructor FBSDKPackage in class FBSDKPackage cannot be applied to given types;
            new FBSDKPackage(),
            ^
  required: CallbackManager
  found: no arguments
  reason: actual and formal argument lists differ in length
`

Should I instead use [react-native-facebook-login](https://github.com/magus/react-native-facebook-login)?

Thanks in advance

**Comment by jamonholmgren** [comment]
@derekgreenberg , do you have some advice here? You created `ignite-example-login`.

**Comment by MythicalFish** [comment]
Managed to get FBSDK working (was entirely my mistake, was expecting an easier setup like what's provided by Expo).
