### ISSUE TITLE
Add super cool animation

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#1128]
Does ignite have ACII Fire?  YES... but does that fire animate?  NO!

We need some more sexy in our lives:  
https://github.com/bokub/chalk-animation

^ DO IT!  JUST... DO.. IT!

**Comment by yordis** [comment]
@GantMan PR welcome.

**Comment by GantMan** [comment]
Yup PRs are welcome.  I think were going to be pushing a new version soon, so this is a prime time if someone wants to knock this out.

**Comment by yordis** [comment]
@GantMan I was trying to say that you could do a PR 😄

**Comment by GantMan** [comment]
Hahaha, yeah, I will.  I got flatlist in yesterday, and I have a few other tricks up my sleeve I need to get in place first.   I like this is so low hanging, but I can't keep taking all the fun ones.

**Comment by wisn** [comment]
Are we need this? But that chalk-animation was interesting. I will give a try.

**Comment by GantMan** [comment]
It's a fun PR for sure.   Is it essential?  Not really.

**Comment by yordis** [comment]
@GantMan my personal opinion which means nothing more than just that.

If you will take your valuable time for work for any OSS project I will appreciate if you do something that brings more value than adding some colors to something that you will probably no pay attention after the 3rd time you see, specially if it is every day.

Your time is valuable for everyone, use it wisely. We (community) need you with some other stuff 😂

But if it makes you happy and they will take it ❤️ don't even ask and do it.

But that is my personal opinion, which means nothing and I am already grateful that you give a lot of time to OSS.

**Comment by GantMan** [comment]
truth.  I'm always pretty damn busy.  Though I'm also full of nonsense.  Hahaha.  I doubt I'll get back to this, but happy to review it if someone else does it.

Back to work for me, and thanks for the compliment!

**Comment by wisn** [comment]
@GantMan Have you seen this statement on the `chalk-animation` repository?

> Anything printed to the console will stop the previous animation automatically

So that's mean the animation will be blocking another output. That was bad. Well, I've tested to implement it.
