### ISSUE TITLE
Implementing Firebase subscribe action / listener 

### ISSUE THREAD

**Issue by rcsheng** [infinitered/ignite#1129]
Hi,

Sorry complete newbie here. I'm trying to implement the 'subscribe' action per (http://invertase.io/react-native-firebase/#/redux?id=action-creators), code:

export const subscribe = () => {
  return (dispatch) => {
    firebase.database().ref('todos').on('value', (snapshot) => {
      const todos = [];

      snapshot.forEach((childSnapshot) => {
        todos.push({
          id: childSnapshot.key,
          ...(childSnapshot.val()),
        })
      })

      dispatch({
        type: 'TODO_UPDATE',
        todos,
      })
    })
  }
}

------------------
I really love what you guys have provided but can't figure out how to set up a listener.  Where should the listener sit, in Redux, Sagas or somewhere else?  Any guidance you can provide would be truly appreciated.

Thanks,

R

**Comment by jamonholmgren** [comment]
Hey @rcsheng , did you figure this out?

**Comment by rcsheng** [comment]
Hey @jamonholmgren, I found an ugly way to make it work by putting the listener in my container. I couldn't quite figure out how to do it in the saga though

Thanks,

Richard

**Comment by cosmosof** [comment]
I have this saga login implementation;
import { put, call } from 'redux-saga/effects'
import LoginActions from '../Redux/LoginRedux'
import firebase from 'firebase'
```

// attempts to login
export function * login ({ email, password }) {

  const firebaseAuth = ({ email, password }) =>
  firebase.auth().signInWithEmailAndPassword(email, password)
    .then(response => ({ response }))
    .catch(error => ({ error }))

  if (password === '') {
    yield put(LoginActions.loginFailure('password can not be empty!'))
  } else {
    try {
      const { response, error } = yield call(firebaseAuth, { email, password })
      if (response)
        yield put(LoginActions.loginSuccess(email))
      else
        yield put(LoginActions.loginFailure('user can not be found!'))
    } catch (e) {
      yield put(LoginActions.loginFailure('something went wrong, try again!'))
    }
  }
}
```
