### ISSUE TITLE
my can't run my app on android studio. errors mentioned below.

### ISSUE THREAD

**Issue by umer93379** [infinitered/ignite#1131]
i'm facing issue while rendering an existing project.  
Load setting issue: " Cannot load settings from file 'E:\folder\appFolder\app\app.iml': Error on line 1: Content is not allowed in prolog. Please correct the file content "

Error: Could not find androidtoggleswitch.jar (us.belka:androidtoggleswitch:1.2.0).
Searched in the following locations:
    https://jcenter.bintray.com/us/belka/androidtoggleswitch/1.2.0/androidtoggleswitch-1.2.0.jar

**Comment by lvlrSajjad** [comment]
> i'm facing issue while rendering an existing project.
> Load setting issue: " Cannot load settings from file 'E:\folder\appFolder\app\app.iml': Error on line 1: Content is not allowed in prolog. Please correct the file content "
> 
> Error: Could not find androidtoggleswitch.jar (us.belka:androidtoggleswitch:1.2.0).
> Searched in the following locations:
> https://jcenter.bintray.com/us/belka/androidtoggleswitch/1.2.0/androidtoggleswitch-1.2.0.jar

@umer93379 
what boilerplate do you use ?
this happens on a fresh ignite project?

**Comment by jamonholmgren** [comment]
This issue is pretty stale, so I'm closing it. Please let me know if you still need help with it. 🙂
