### ISSUE TITLE
[survey] public Interest for a full app generator

### ISSUE THREAD

**Issue by l1br3** [infinitered/ignite#1135]
Not an issue, just a quick question to know if some people would be interested in a generator which would transform a config file into an entire app.

---
AutoRnApp is a well opinionated ignite boilerplate + generator which aims to save your precious time.

You need to make an App for a customer? Thanks to this generator, you are going to be the faster dev and your quote will be the lower, just because you didn't wasted time copy/pasting your containers/components/redux/sagas/etc....

Just focus on your business logic ! Writing crud APIs is nor clever nor a source of spiritual lifting !

AutoRnApp will generate for you CRUD and misc actions (signUp, signIn, etc...) in a "stacks in tabs" App (see React Navigation). It will generate hoc, components, styles, redux, sagas and apis 100% automatically.

---

[AutoRnApp generator](https://github.com/l1br3/ignite-AutoRnApp) if you want to have a look or make suggestions. Only file generation is ready for now !

TODO:
patch files
write tests
generate tests

It will generate:
- hocs 
- hoc's styles
- hoc's components
- hoc's component's styles
- redux
- sagas
- apis

Link everything and generate a "stack into tabs" (react-navigation) app.

Exemple of config file:  
```javascript
    user: {
      model: {
          username: 'string',
          password: 'password',
          email: 'email',
          jwt: 'string',
          pictureUrl: 'picture'
      },
      subs: {
        auth: {
          subs: {
            authenticate: {
              navs: ['register', 'recover'], 
              props: ['email', 'password', 'jwt'],
              response: ['jwt'],
              setForm: true, 
            },
            register: {
              navs: ['authenticate', 'recover'],
              props: ['username', 'email', 'password'],
              response: ['jwt'],
              setForm: true, 
            },
            recover: {
              navs: ['authenticate', 'register'],
              props: ['email'],
              response: ['jwt'],
              setForm: true, 
            },
          }
        }
      }
    }
```

**Comment by skellock** [comment]
This is awesome!  Keep going!

**Comment by l1br3** [comment]
Well, doc is done, file generation might be testable (at least on my computer !).
There is at least one big day of work to get this working for real and few other days to write tests and tests generation.
At least we have something to play with now... and to read !

**Comment by l1br3** [comment]
File generation IS testable I mean. I tried it in an entire new project.

**Comment by jamonholmgren** [comment]
I really like this too, fantastic work @l1br3!

**Comment by l1br3** [comment]
@jamonholmgren @skellock The generator is going well, there is some cleaning to do but it works !
So far we can generate stacks in modals in tabs with actions which makes api call through Sagas.
Are you interested / have time to try it ? If so I'll push it on npm so it will be possible to use it as a boilerplate.

**Comment by l1br3** [comment]
If you could give some clues on https://github.com/l1br3/ignite-AutoRnApp/issues/1 and https://github.com/infinitered/ignite/issues/1140 it would be very nice !

**Comment by kevinvangelder** [comment]
Closing this issue because it appears the project didn't generate much interest and hasn't been updated since last year.
