### ISSUE TITLE
[Feature Request] Support ES6 for CLI

### ISSUE THREAD

**Issue by l1br3** [infinitered/ignite#1136]
---
CLI (generate at least) does not support stuff like 'export'

---
Create a new plugin, put some es6 code somewhere, export it with 'export' and import it in the command file with require.

**Comment by skellock** [comment]
That's a `nodejs` restriction.  We don't use `babel` or `typescript` on this project to compile.

Now that the standard is ratified, `nodejs` will have it in place soon.

In the meantime:

These libraries advertise a polyfill style drop in replacement:

https://github.com/benjamn/reify
https://github.com/standard-things/esm

Let us know if you have success with this!

I'm looking forward to `import` and `export` as well.

**Comment by l1br3** [comment]
Perfectly clear, thanks
