### ISSUE TITLE
[BUG] import ReactotronConfig is not in Config/index.js and causes crash

### ISSUE THREAD

**Issue by l1br3** [infinitered/ignite#1137]
---
## What's going on?
Starting a new ignite App, `import ReactotronConfig` misses from `App/config/index.js` while `__DEV__` is `true` and app tries to use Reactotron. This causes a crash because `console.tron` is undefined in `Redux/createStore.js`.

---
## Steps to reproduce
`ignite new appName --min`

---
`ignite doctor` results:
```
System
  platform           linux                                                                                
  arch               x64                                                                                  
  cpu                4 cores                          Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz  
  directory          /home/libre/dev/reactotronTest                                                       

JavaScript
  node               7.7.4        /home/libre/.nvm/versions/node/v7.7.4/bin/node  
  npm                4.1.2        /home/libre/.nvm/versions/node/v7.7.4/bin/npm   
  yarn               0.27.5       /home/libre/.nvm/versions/node/v7.7.4/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.45.1      

Ignite
  ignite             2.0.0        /home/libre/.nvm/versions/node/v7.7.4/bin/ignite  

Android
  java               1.8.0_131    /usr/bin/java            
  android home       -            /home/libre/Android/Sdk  
```

**Comment by skellock** [comment]
The `import` order is important.

So check this out:

1. Do you see in the original boilerplate how the very first thing in `index.ios.js` [imports `ReactotronConfig.js`](https://github.com/infinitered/ignite-ir-boilerplate/blob/master/boilerplate/index.js.ejs#L1)? 
1. And do you see in `ReactotronConfig.js` we import [`DebugConfig.js`](https://github.com/infinitered/ignite-ir-boilerplate/blob/master/boilerplate/App/Config/ReactotronConfig.js#L1)?
1. And you see in `DebugConfig.js` there are [no more dependencies](https://github.com/infinitered/ignite-ir-boilerplate/blob/master/boilerplate/App/Config/DebugConfig.js)?
1. Now [look back](https://github.com/infinitered/ignite-ir-boilerplate/blob/master/boilerplate/App/Config/ReactotronConfig.js#L21) to `ReactotronConfig.js`.  See how there are no more project-based imports?
1. And finally you get to [this line](https://github.com/infinitered/ignite-ir-boilerplate/blob/master/boilerplate/App/Config/ReactotronConfig.js#L21)?

That's how the React Native packager resolves dependencies.

If you put something between startup and that `console.tron = ` line that uses `console.tron.something`, then you're rewarded with a glorious `undefined` error.

My guess is, in your codebase, you're importing redux before that line.  Probably by accident.  Probably in your `App/config/index.js`.

Can you double check please?

**Comment by l1br3** [comment]
1. Well, I was porting the ignite App to Expo as I cannot use hot reloading so now I understand why Reactotron config is not being imported -> index.android.js is not used.

2/3/4/5 This is how I've tracked this "bug" and understood I had to import Reactotron config :) 

No bug, just a different setup !
