### ISSUE TITLE
Ignite boilerplate with ReactNavigation Example?

### ISSUE THREAD

**Issue by plflanagan** [infinitered/ignite#1138]
Hello,

I'm having a hard time figuring out how to implement the navigationBar, which I believe is included in the main boilerplate, yes?

If so, could someone leave an example of how to implement this in an ignite app? The instructions at https://reactnavigation.org/docs/intro/ don't seem to apply.

**Comment by l1br3** [comment]
Stay tunned here -> https://github.com/infinitered/ignite/issues/1135 !
I'm doing [this boilerplate](https://github.com/l1br3/ignite-AutoRnApp), hopefully fully featured during next week (I'm leaving in week end in few hours) !
It's an ignite App "stacks in tabs", everything is in the readme

**Comment by plflanagan** [comment]
Turns out I was editing another app's navigator 😅 

But totally looking forward to that boilerplate!

**Comment by jamonholmgren** [comment]
Ooh 😀 I've done that before. Glad you figured it out!
