### ISSUE TITLE
[Enhancement/proposal] Add babel-plugin-module-resolver to ignite new

### ISSUE THREAD

**Issue by l1br3** [infinitered/ignite#1140]
Building the AutoRnApp boilerplate/generator I'm facing the issue of module depth. 
It would be easy to solve by adding '../' depending of the depth level which is already computed by I find so much elegant to use an 'absolute' path like `import reducer from 'Redux/ScreenName/reducer'` rather than `import reducer from '../../../../......./Redux/.....'`.

I think I cannot edit the `.babelrc` file with the boilerplate so it would be necessary to integrate it directly to the `new` command ?
I'm not sure where to look to make a PR if the idea is validated.

The `.babelrc` would become like this:  

```js
{
  "presets": ["react-native"],
  "plugins": [[
    "module-resolver", {
      "root": ["./App"],
      "alias": {
        "Redux": "./Redux",
        "Sagas": "./Sagas",
        "Screens": "./Screens",
        "Themes": "./Themes",
        "Components": "./Components",
        "Containers": "./Containers",
        "Services": "./Services",
        "Transforms": "./Transforms",
        "Lib": "./Lib",
        "Images": "./Images"
      }
    }
  ]],
  "env": {
    "production": {
      "plugins": ["ignite-ignore-reactotron"]
    }
  }
}
```

The [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver)

**Comment by skellock** [comment]
I answered this on [your issue](https://github.com/l1br3/ignite-AutoRnApp/issues/1#issuecomment-327314763).

Spoiler:  change it in your `boilerplate.js` file.

```js
const babelrc = filesystem.read('.babelrc', 'json')
babelrc.plugins = babelrc.plugins || []
babelrc.plugins.push('module-resolver')
filesystem.write('.babelrc', babelrc, { jsonIndent: 2 })
```

**Comment by l1br3** [comment]
Marvelous ! Thanks

**Comment by kruyvanna** [comment]
Hi, I try to use @l1br3 .babelrc but I got this error 
Something to do with Reactotron?

![simulator screen shot - iphone 6 - 2018-02-10 at 12 56 26](https://user-images.githubusercontent.com/1171793/36059038-ed5ff630-0e61-11e8-8a8e-9599f7a6c06b.png)

**Comment by l1br3** [comment]
Could you please confirm that App/Redux/index.js exists and correctly export a module ?

**Comment by kruyvanna** [comment]
Thanks @l1br3. It does. But after I tried clearing caches now it's working fine.

However, I face another problem with module-resolver
which I created an issue here

https://github.com/tleunen/babel-plugin-module-resolver/issues/271

**Comment by tayfunyasar** [comment]
It should be access all these elements in /App with the only folder name. There are a lot of example. 
https://github.com/react-boilerplate/react-boilerplate/blob/master/app/containers/HomePage/index.js#L15

**Comment by jamonholmgren** [comment]
Thanks for your comment! For now, we don't intend to add this to Ignite. We did [flatten the folder structure](https://shift.infinite.red/announcing-ignite-bowser-3-0-the-flattening-3307d821abf2) in Bowser which should help a lot.
