### ISSUE TITLE
Boilerplate option not picked up

### ISSUE THREAD

**Issue by aledalgrande** [infinitered/ignite#1143]
### What's going on?
When I run this (1):
```
ignite new test -b native-base-boilerplate
```
The selected template is the last one I used. If for example I ran this before (1):
```
ignite new test -b ir-boilerplate-2016
```
then when I run (1) it will use _Infinite Red 2016_ instead of _NativeBase_.

First of all I don't know where Ignite is storing this information.

Second, the NativeBase boilerplate is not working and there is wrong behavior from the client: **instead of erroring out, it just uses another template**.

The interesting thing is that I see `adding native-base-boilerplate` and then it switches to `using the Infinite Red 2016 boilerplate`.

### Steps to reproduce
```
ignite new test -b ir-boilerplate-2016
ignite new test -b native-base-boilerplate
```

### `ignite doctor` results:
```
System
  platform           darwin                                                                                  
  arch               x64                                                                                     
  cpu                4 cores                             Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz  
  directory          /xxx                                                       

JavaScript
  node               8.4.0        /usr/local/bin/node  
  npm                5.3.0        /usr/local/bin/npm   
  yarn               0.27.5       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.0.0        /usr/local/bin/ignite  

Android
  java               1.8.0_112    /usr/bin/java  
  android home       -            undefined      

iOS
  xcode              8.3.3
```

**Comment by ruddell** [comment]
The Native Base boilerplate is being used, it just displays the wrong boilerplate name.  It was fixed https://github.com/GeekyAnts/ignite-native-base-boilerplate/pull/1 but a new version hasn't been released on npm

Related to https://github.com/infinitered/ignite/issues/1003

**Comment by aledalgrande** [comment]
Gotcha, I will close this issue. The question I have left is where does Ignite store answers to the install questions? After I ran a boilerplate for the first time they are not asked any more.

**Comment by ruddell** [comment]
I don't think they are stored anywhere.  The boilerplate is only used for the initial generation, then commands like `ignite generate redux` are available afterwards.
