### ISSUE TITLE
How to run example screens ?

### ISSUE THREAD

**Issue by john1jan** [infinitered/ignite#1144]
I have created a new app using ignite cli.  

`ignite new testApp`

After running the app I can see only one launch screen.  I want to explore other examples.
There is a folder named ignite in the project

![screen shot 2017-08-22 at 11 08 16 am](https://user-images.githubusercontent.com/4264813/29550267-8200a24a-872a-11e7-8735-c3daa3c1bd68.png)

How to run these example screens   ?

**Comment by robinheinze** [comment]
Hey @john1jan!

Great question. Those examples are really more for the code and there isn't a great way to "run" them. The idea is that you could take code from those examples and incorporate it into your app as you build. 

For more examples in action, try checking out the Chain React conference app https://github.com/infinitered/ChainReactApp. Lots of great examples of these things in-use in a live, working app.

**Comment by kevinvangelder** [comment]
Those examples should be rendered in the dev screens. If you didn't opt-in to dev screens when you generated the app, just run `ignite add devscreens`.
