### ISSUE TITLE
Eject signed apk

### ISSUE THREAD

**Issue by ckc52403050** [infinitered/ignite#1145]
How do I eject the signed apk after finishing?

**Comment by skellock** [comment]
It gets built in `./android/app/build/outputs/apk/app-release.apk`.

You can built it manually by: `cd android` and `./gradlew assembleRelease`.

More info on their docs:

http://facebook.github.io/react-native/docs/signed-apk-android.html

**Comment by GantMan** [comment]
Gonna close this one, open if you're still stuck.
