### ISSUE TITLE
Configure spacing and quotes type

### ISSUE THREAD

**Issue by jankalfus** [infinitered/ignite#1146]
Would it please be possible to make the cli configurable? I'd love to have the ability to set indentation to 4 spaces, instead of 2, and also quotes to double quotes, when generating components, screens etc.

ESLint can autofix this, but still, it would be nice to have options for these.

**Comment by GantMan** [comment]
You can modify any of the templates with the `spork` command.

try `ignite spork` to change a template per project.   Let me know if that works for you 👍

**Comment by jankalfus** [comment]
Ah, yes, that works great indeed! Too bad there's no mention about it in the docs. I'll make a PR with some basic info if I find the time at the end of this week ;)

Many thanks! :)

**Comment by GantMan** [comment]
That would be awesome!  yeah, docs def could use some ✨  ❇️ ✨
