### ISSUE TITLE
Components-Generator

### ISSUE THREAD

**Issue by agahEbrahimi** [infinitered/ignite#1150]
Hello,
I'm new Ignite and I don't know all the components that I can generate for my app, I wanted to know if there are any specific places that list Ignite components that can be generated.

Thank you

**Comment by kevinvangelder** [comment]
`ignite g` will list all installed generators. If you don't have any you're probably not in an Ignite project or don't have a boilerplate installed.

**Comment by agahEbrahimi** [comment]
It just brings things like component, container, listview ...
not the things I can generate like, a table or ...

**Comment by GantMan** [comment]
you can generate anything someone writes a template for.  These are the defaults.

You can create your own plugin with your own list of generators:  https://github.com/infinitered/ignite/blob/master/PLUGINS.md

**Comment by agahEbrahimi** [comment]
Thank you, that link you sent is what I wanted.
