### ISSUE TITLE
Official React Native functionality fork

### ISSUE THREAD

**Issue by MyTotoro** [infinitered/ignite#1152]
There's some functionality that's creeping into React Native that is purported to be only available to apps `made with react-native init or to those made with Create React Native App` [https://facebook.github.io/react-native/docs/geolocation.html](url)

A few features include:
```
https://facebook.github.io/react-native/docs/permissionsandroid.html
https://facebook.github.io/react-native/docs/geolocation.html
```

From what I can tell - I can't access those features from my app created with ignite... I've spent a considerable amount of effort building this and I'm considering just abandoning this codebase and salvaging what I can and recreating a new app with `react-native init` while porting as much as I can over

**Comment by GantMan** [comment]
Ignite is built on top of `react-native init`, there should be no reason you cannot access those features.

Ignite has always been very careful to remain "non-lock-in".  Let me know if you find the source of your problem!   But I'm sure ignite isn't holding you back. 

We use geolocation a lot!

**Comment by skellock** [comment]
Please re-open if you're still stuck @MyTotoro
