### ISSUE TITLE
console error: "uncaught at check", "call argument fn is undefined"

### ISSUE THREAD

**Issue by sooxiaotong** [infinitered/ignite#1156]
After i delete whole node_modules folder, i exec `npm install --save` & `react-native run-ios` again, i get this result

![image](https://user-images.githubusercontent.com/13378059/30218887-ec1b0b28-94ec-11e7-9b2b-027dfdc1bd05.png)

```
System
  platform           darwin                                                                                                 
  arch               x64                                                                                                    
  cpu                4 cores                                            Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz  
  directory          /Users/sooxiaotong/Documents/ReactNative/Igniter                                                       

JavaScript
  node               8.4.0        /usr/local/bin/node  
  npm                5.3.0        /usr/local/bin/npm   
  yarn               0.27.5       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.47.2      

Ignite
  ignite             2.0.0        /usr/local/bin/ignite  

Android
  java               1.8.0_121    /usr/bin/java                           
  android home       -            /Users/sooxiaotong/Library/Android/sdk  

iOS
  xcode              8.3.3 
```

**Comment by skellock** [comment]
Check to see what version of `babel-preset-react-native` you have in your `package.json`'s `devDependency`.  If it's not `3.0.2`, try bumping it up there.  

Then restart your packager with a fresh cache `npm start -- --reset-cache`.

Does that work?

**Comment by sooxiaotong** [comment]
Still the same

**Comment by sooxiaotong** [comment]
SOLVED: `yarn install` instead of `npm install`

**Comment by skellock** [comment]
Mon, wed, fri, sun = npm
Tue, thu, sat = yarn

Got it!

**Comment by jamessawyer** [comment]
some issue, is there a solution for this?

**Comment by mukis** [comment]
I have tried deleting node_modules, resetting .rncache, installing with yarn and npm, cleaning build in Xcode, everything, but nothing seems to work. I am stuck on this for quite a while.

**Comment by akaralar** [comment]
I'm having the same issue but the problem disappears if I delete this line from `StartupSagas.js`
```
yield put(GithubActions.userRequest('GantMan'))
```

**Comment by RominHalltari** [comment]
@akaralar thank you! Worked for me 👍

**Comment by parthibanloganathan** [comment]
Experienced this recently and @akaralar's solution worked for me too. Not sure why it works nor does it sound like the proper solution
