### ISSUE TITLE
increase navigation bar height

### ISSUE THREAD

**Issue by mykelaballe** [infinitered/ignite#1161]
RN: 0.34
Ignite: 1.5.0

How can i increase the height of the navigation bar? It looks fine in android and ios mobile phones, but the UI looks small in iPad portrait mode, so i multiplied everything in Metrics.js and Fonts.js by 2, other UI are ok except with the navigation bar, it seems not affected with the height increase

![image](https://user-images.githubusercontent.com/22584900/30527488-b565c6ce-9c5b-11e7-9cd5-f0f3bc04d153.png)

Metrics.js
![image](https://user-images.githubusercontent.com/22584900/30527829-64add9de-9c5f-11e7-9593-9b6b6d9e3aed.png)

multiply all property by 2
![image](https://user-images.githubusercontent.com/22584900/30527820-46ba8eae-9c5f-11e7-9429-c5afd3311784.png)

**Comment by GantMan** [comment]
Can you setup a demo repo, for me to pull down and try?
