### ISSUE TITLE
add another option for linting utility

### ISSUE THREAD

**Issue by jose920405** [infinitered/ignite#1164]
In my case `JavaScript Standard Style` does not seem to me a good tool to verify the state of your code. Not being configurable is one of them, as well as its semicolon rules.

adding ESLint might be a good idea.

**Comment by monotv** [comment]
I use extended JS Standard rules with eslint. Works fine.

`{
  "parser": "babel-eslint",
  "extends": "standard",
  "plugins": ["react", "jsx-a11y", "import"],
  "rules": {
    "jsx-quotes": ["error", "prefer-double"]
  }
}`

**Comment by skellock** [comment]
Ya, keep in mind your this is your app, so you're welcome to change it to fit your standards.  The generators will need to be forked, but it's not too much work.
