### ISSUE TITLE
upgrade to rn 0.49.2 fails 

### ISSUE THREAD

**Issue by valinaga** [infinitered/ignite#1165]
What's going on?
After a classic ignite new myapp I tried to upgrade from RN 0.47 to 0.49.2 using rect-native-git-upgrade. A lot of errors are revealed and the react-native run-ios fails.
---
Steps to reproduce
run rect-native-git-upgrade
---
`ignite doctor` results:

**Comment by GantMan** [comment]
We'll be taking a look at this soon.

**Comment by GantMan** [comment]
@valinaga - merged updates for everything, please take a look and give feedback.

**Comment by valinaga** [comment]
@GantMan do I need to  `npm install -g ignite-cli` ?

**Comment by GantMan** [comment]
we'll update the latest version tomorrow.   Or you can point at master branch tonight.

**Comment by skellock** [comment]
They had some issues with `react-native-git-upgrade`.  Check out the [0.49 release notes](https://github.com/facebook/react-native/releases/tag/v0.49.0) in the section called `updating your code`.  

They say how you can solve it.  🎉
