### ISSUE TITLE
Problems with Expo sdk.

### ISSUE THREAD

**Issue by mobitinker** [infinitered/ignite#1166]
When trying to use Expo it becomes necessary to supply it with fonts on Android, since Avenir is not on that platform. 

I follow the instructions at https://docs.expo.io/versions/latest/guides/using-custom-fonts.html#content and run into a problem. My app red boxes with:

Undefined is not an object (evaluation ExponentConstants.linkingUri) . The stack trace begins in expo.js in node_modules. 

Based on what I've seen on stackoverflow it seems Expo has problems with react-init apps but works fine with those started with CRNA. I'm wondering if there is a conflict with ignite.

**Comment by skellock** [comment]
We don’t use expo here 😿 yet, so I’m afraid we won’t be of much help.

I’d pick up the battle on the expo side. If it turns out to be our fault, please let me know, and i’ll patch it up!
