### ISSUE TITLE
Where to put 'non side-effect' business logic?

### ISSUE THREAD

**Issue by jacogreyling** [infinitered/ignite#1174]
Apology if this question has already been answered. I'm using the ignite-ir-boilierplate 2.2.2 framework which I think does a brilliant job at segregating all the different components in an App. Whilst I understand the use of Sagas I do want to ask the following question. If I have simple business logic that needs to execute (e.g. check the state and update value to X if Y) where must I put this? I know it's bad practice to put it in the reducer or the component. I don't want to put it in a Saga because I think it's overkill (no API calls, etc.). 

Since the ignite-ir-boilerplate is using reduxsauce, it use helper methods to create the Action creator. The downside is there is no way to write custom business logic?? For previous projects I used the Action creators for this kind of logic but using the ignite 'way' I'm not sure where to put it?

Any advice will be greatly appreciated!

**Comment by skellock** [comment]
I’ve seen people (me!) create a selectors directory for this kind of derived/computed data.  I’ve also seen people hang these off the redux file as extra functions. I’ve also seen people pre-calculate these baked into a reducer.

You may also wish to create a standalone file that exports these functions.

I’d say all 4 of these ways are viable.

**Comment by jacogreyling** [comment]
Thank you Steve! I was about to put them in the reducer (seemed like a 'natural' place, since there is no asynchronous code) but then I realised that reducers have to be predicable. Given the same input you should always render the same result / state. Therefor I'm looking for a new home for these functions. Is is possible to update the action creators to have more business logic (whilst using reduxsauce)? Also do you have an example of your method perhaps and how you will reference it, using a selectors directory.

**Comment by jacogreyling** [comment]
Ok so let me give an example, I have three different states for a toggle; on, off and auto. Every time someone clicks a button it should change from auto -> on, then if I click it again from  on -> off and back to auto when it's clicked yet again. This is a simple state change and can possibly be kept in the reducer but I'm thinking maybe a saga daemon function which just cycled through these 3 states all the time (in an infinite while loop), but like I said in my original post it just feels like overkill for such a simple task. Action creators will be more perfect in my opinion but I'm not sure how to do it with reduxsauce in the mix.

**Comment by skellock** [comment]
Hey @jacogreyling.  It does feel overkill for that.

Really what you're describing there is a great candidate for a reducer.  You're talking about how to change the current state (auto) to another state (on). 

But I'm sure you've got other examples of synchronous state.  Here's some examples of where you can put other things.

`mapStateToProps`.  It's not wrong to put some derived data in there.  If it's simple and used in 1 spot, this might be a good candidate.  For example, you maybe want change your `tri-state` example to a string.  `"On."`, `"Off".` or `"-"`.  

If you want to reuse that logic or it just gets too big, maybe you want to have a `selectors.js` file where you put a bunch of these functions inside?  These functions could be exported as named functions that accept the whole state tree and return back a subset of it (or a derivation thereof).

```js
export function getTriStateName(state) {
  if (state.someReducer.currentValue) {
     // ...
  }
}

export function getOrderDetails(state, orderId) {
  // ....
}

export function getGiantReport(state, startDate, endDate = Date.now()) {
  // ...
}
```

That kinda stuff is great for read-only things.

Another pattern we've seen/used is transformations.  Maybe everytime you talk to an API server you have to do conversions like preparing the data for transport, or massaging the data when it comes back before you send it off to a reducer...  You can drop this code in `App/Transforms/ApiTransforms.js` for example.  Just export named functions to call.  Inputs could be the response from the api and outputs could be what you want it to be (another object for example).

There's no real great answer for this.  

In practice, I switch this up all the time from project to project.

Start with something.  Get it working.  Then listen to your spidey sense.  Maybe it's ok where you put it.  Maybe it needs to move.  Maybe it's more important to finish the app than to sweat the perfect home for all your code.   I'll be honest, I get tripped up by that all the time.  =)

If you've got a codebase online I could check out, I wouldn't mind making a few suggestions.

**Comment by jacogreyling** [comment]
Thank you again Steve, for the comprehensive answer. It's really much appreciated. So I like your idea of a 'selectors' folder so this is what I've done:

At the component level I have an `onClick` event that fires an action like so:

```
<TouchableOpacity
    onPress = {() => {this.props.cycleFlashMode(camera.flashMode)}}>
    <Image source={this.flashIcon} />
</TouchableOpacity>
```

My mapDispatchToProps includes the following binding:

```
const mapDispatchToProps = (dispatch) => {
    return {
        cycleFlashMode: (mode) => dispatch(CaptureActions.cycleFlashMode(mode))
    };
};
```

Inside my Redux I've worked out that you can pass a function to the `createActions` call which is where I reference my 'selector'.

```
const { Types, Creators } = createActions({
    cycleFlashMode: Selectors.getNextFlashMode
});

```
I then have a 'Selectors' folder with the name(s) of the individual .js file that of the Reducer(s). This way each reducer has its own selector js file. Inside the .js file, this is what I have:

```
export function getNextFlashMode(currentFlashMode) {

    let flashMode;
    switch (currentFlashMode) {
    case constants.FlashMode.auto:
        flashMode = constants.FlashMode.on;
        break;
    case constants.FlashMode.on:
        flashMode = constants.FlashMode.off;
        break;
    case constants.FlashMode.off:
        flashMode = constants.FlashMode.auto;
        break;
    default:
        // no nothing
    }

    return {
        type: 'CYCLE_FLASH_MODE',
        flashMode
    };
}
```

It all seems to work perfectly and my code is nicely separated. It's probably a lot of overhead for a simple task, but as my code grows I'm sure it's going to pay off in the long run.
