### ISSUE TITLE
Listview generator broken

### ISSUE THREAD

**Issue by JonathanJumper** [infinitered/ignite#1184]
**What's going on?**

Cannot use the generator as intended, the name is set always `View.js` and that leads to the error:
View.js: Duplicate declaration of "View"

**Steps to reproduce**

 $ ignite generate listview EventList

? What coding style do you want for your list? Flatlist (new)
? What kind of List would you like to generate? Row
? How will your data be presented on this list? Single
✔︎ App/Containers/View.js
✔︎ App/Containers/Styles/ViewStyle.js

At first I thought it was because of this new Flatlist, but the classic gives the same results:
 
$ ignite generate listview EventList

? What coding style do you want for your list? Listview (classic)
? What kind of List would you like to generate? Row
? How will your data be presented on this list? Sectioned
✔︎ App/Containers/View.js
✔︎ App/Containers/Styles/ViewStyle.js

I tried with a quoted name too with no luck

**`ignite doctor` results:**

System
  platform           darwin                                                                                            
  arch               x64                                                                                               
  cpu                4 cores                                       Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz  
  directory          /Users/jumper/Developer/ReactNative/Balance                                                       

JavaScript
  node               8.7.0        /usr/local/bin/node  
  npm                5.5.1        /usr/local/bin/npm   
  yarn               1.3.2        /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.49.3      

Ignite
  ignite             2.0.0        /usr/local/bin/ignite  

Android
  java               1.8.0_144    /usr/bin/java                      
  android home       -            /Users/jumper/Library/Android/sdk  

iOS
  xcode              8.3.3

**Comment by joelbarbosa** [comment]
Hi @JonathanJumper  listview  Deprecated - Use `list`

**Comment by mariocorzo** [comment]
This video has the same error
https://www.youtube.com/watch?v=lv00UOXxy0g

**Comment by c0bra** [comment]
@joelbarbosa still deprecated but not clear in the cli? Is that intentional?

**Comment by skellock** [comment]
Unfortunately, this codebase has gotten dusty.  We'll be rolling out a new boilerplate soon, but if you want to kick over a PR to fix this issue, that'd be awesome.

**Comment by skellock** [comment]
Oops... unintentional close.  Damn those 2 buttons are close together.

**Comment by jamonholmgren** [comment]
No longer relevant, so I'm closing this. 😎
