### ISSUE TITLE
After added ignite-ir-boilerplate throw 'The file name, directory name, or volume label syntax is incorrect'

### ISSUE THREAD

**Issue by sppsun** [infinitered/ignite#1189]
After added ignite-ir-boilerplate throw the 'The file name, directory name, or volume label syntax is incorrect' exception， what is wrong? Thank you.

**Comment by sfthurber** [comment]
any solution?

**Comment by skellock** [comment]
Could you post the code & commands you're using?

**Comment by sfthurber** [comment]
i just followed the quickstart example on a windows 10 machine (fully updaed FCU+all subsequent updates):
C:\Users\user\rnapps>ignite new MyLatestCreation
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app MyLatestCreation
√ using the Infinite Red boilerplate v2 (code name 'Andross')
√ added React Native 0.50.4 in 214.94s
? Would you like Ignite Development Screens? No
? What vector icon library will you use? none
? What internationalization library will you use? none
? What animation library will you use? none
? Would you like to include redux-persist? No
√ added ignite-ir-boilerplate in 219.67s
The filename, directory name, or volume label syntax is incorrect.
......

**Comment by sfthurber** [comment]
for my installation i followed the instructions i posted to close both of the issues i initiated concerning installation on windows 10, as follows:

A how-to for a working setup on a windows10 machine in 7 easy steps:

1- Download and install notepad++ [skip if you already have git or are ok with using vim for git editor]
2- Download and install nodejs v8.10 or later [skip if you already have that]
3- Download and install git , NOTE:you will also need to set a git email and username[skip if you already have git]
4- Download and install yarn
5- npm install -g create-react-native-app
6- npm install -g  react-native-cli
7- npm install -g ignite-cli
DONE!

**Comment by sfthurber** [comment]
done

**Comment by skellock** [comment]
Thank you for the step by step instructions @sfthurber!

Awesome!

**Comment by sfthurber** [comment]
why closed? the step by step instructions sis not solve the problem --
i was just telling you what id did. the step by step did solve two
earlier issues (under my name)

**Comment by sfthurber** [comment]
typo
why closed? the step by step instructions did not solve the problem --
i was just telling you what id did. the step by step did solve two
earlier issues (under my name)

**Comment by skellock** [comment]
Ah.  Thought you were telling me how you fixed it.

**Comment by sfthurber** [comment]
i wish! :--))
unfortunately i have not found a fix.

**Comment by jamonholmgren** [comment]
No longer relevant, so I'm closing this. 😎
