### ISSUE TITLE
Best Practices for changing application state via firebase messaging

### ISSUE THREAD

**Issue by dawhitefish** [infinitered/ignite#1191]
Are there any best practices in how to implement firebase within your boilerplate ?

I need to update the application state when the app receives notifications in the background or **foreground.**

**Comment by skellock** [comment]
I'd have a look at how other projects work with Redux and Firebase.  How I'd do it would be to pass the `dispatch` function (and `subscribe` if you need the other way) to the part of the system that can receive firebase events.  Then you can relay them along to redux.
