### ISSUE TITLE
screenTracking in ScreenTrackingMiddleware.js is not being called

### ISSUE THREAD

**Issue by tranvinhtruong** [infinitered/ignite#1192]
---
What's going on?
Should see log from following line when opening dev screens:
> console.tron.log(`NAVIGATING ${currentScreen} to ${nextScreen}`)

Actual: nothing

---
Steps to reproduce
1. create new project:
    `ignite new <project name>`
2. run it:
    `cd <project name>`
    `react-native run-ios`
3. should see app running on simulator, try to play with the app by opening dev screens ...

---
`ignite doctor` results:
System
  platform           darwin                                                                               
  arch               x64                                                                                  
  cpu                8 cores                         Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz  
  directory          <path_to_project>                                                        

JavaScript
  node               8.9.0        /usr/local/bin/node  
  npm                5.5.1        /usr/local/bin/npm   
  yarn               1.3.2        /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.49.3      

Ignite
  ignite             2.0.0        /usr/local/bin/ignite  

Android
  java               1.8.0_131    /usr/bin/java                      
  android home       -            <path_to_android_sdk>  

iOS
  xcode              8.3.3 

---
in package.json:
> react: 16.0.0-beta.5
> react-native: 0.49.3
> redux: ^3.6.0
> redux-saga: ^0.15.6

**Comment by ruddell** [comment]
The dev-screens use a different navigation stack than the regular app ([see here](https://github.com/infinitered/ignite-dev-screens/blob/master/templates/PresentationScreen.js#L84)).  If you generate a screen and add a link to it from the LaunchScreen, you should see the middleware working.

**Comment by tranvinhtruong** [comment]
thanks @ruddell 
You are right, I can see the log now with new generated screen.
Closing...
