### ISSUE TITLE
FYI Future Ignite Release Names

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#1195]
**A** - Andross || Akuma (Street Fighter Alpha 3)
**B** - Bowser
**C** - Clyde (Pac Man) || Cyberdemon (Doom)
**D** - Dysentery (Oregon Trail)
**E** - Enderman (Minecraft)
**F** - Fontaine (Bioshock)
**G** - Ganon
**H** - Heihachi Mishima (Tekken) || Handsom Jack (Borderlands)
**I** - Invaders (space invaders)
**J** - Jecht (Final Fantasy X) 
**K** - King Pig (Angry Birds)
**L** - Lich King (World of Warcraft)
**M** - M. Bison || Mecha-Hitler!! (Wolfenstein)  I know this won't happen :)
**N** - No Heart (Kingdom Hearts)
**O** - Orcs (Warcraft) || O'Chunks (Paper Mario)
**P** - Pyro (Team Fortress 2)
**Q** - Quick Man (Mega Man 2)
**R** - Robotnik (from Sonic)
**S** - Shao Kahn (Mortal Kombat)
**T** - Tom Nook (Animal Crossing) || Tartarus (Halo)
**U** - Umbrella Corporation (Resident Evil)
**V** - Vega (Street fighter 2)
**W** - Wheatley (Portal 2) || Wario?
**X** - Xavius (World of Warcraft)
**Y** - Yeti (Skii-Free)
**Z** - Zombie (Minecraft)

**Comment by GantMan** [comment]
First release was Andross

**Comment by kevinvangelder** [comment]
This should be added to the docs somewhere and closed.

**Comment by jamonholmgren** [comment]
I agree with @kevinvangelder -- let's add to docs somewhere. Easy fix.

**Comment by ryanlntn** [comment]
Moved here: https://github.com/infinitered/ignite/blob/master/docs/quick-start/code-names.md
