### ISSUE TITLE
release 2.3.0 package version not upgraded

### ISSUE THREAD

**Issue by delkant** [infinitered/ignite#1201]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?
the last release doesn't show the right version, ignite -v will display 2.0.0
---
Steps to reproduce
ignite -v

please take a look here: https://github.com/infinitered/ignite/blob/2.3.0/package.json#L3
---
`ignite doctor` results:

**Comment by GantMan** [comment]
The boilerplate version is 2.3, but the CLI is 2.0.0.

I know that sounds silly, but we don't have a method for detecting the current boilerplate.  We could add it.

**Comment by kevinvangelder** [comment]
We've recently added the boilerplate to the Ignite Doctor output.
