### ISSUE TITLE
Generate does not generate files

### ISSUE THREAD

**Issue by naaness** [infinitered/ignite#1204]
I just created a new app with create-react-native-app and attached ignite.

When I try generate a container, not work

`> ignite generate component Head`
`>                                                     `
And then. nothing

ignite doctor
System
  platform           linux
  arch               x64
  cpu                4 cores                                                                              Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  directory          /home/user/project

JavaScript
  node               7.9.0        /usr/bin/node
  npm                5.6.0        /home/user/npm-global/bin/npm
  yarn               0.22.0       /usr/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0        /home/user/npm-global/bin/ignite

Android
  java               1.8.0_131    /usr/bin/java
  android home       -            /home/user/Android/Sdk

**Comment by apatche7** [comment]
I have the same issue.

**Comment by skellock** [comment]
Are you able to run `react-native init Foo` by itself successfully?

**Comment by retrax24** [comment]
I have this exact problem, when you enter ignite g, what does it feed back?
