### ISSUE TITLE
Cut-off Texts

### ISSUE THREAD

**Issue by mykelaballe** [infinitered/ignite#1205]
react-native: 0.34
ignite: 1.5.0

I don't know if this issue is supposed to be posted here or in react native.  But i'm using ignite for my app so it might have something to do with this issue.

![final](https://user-images.githubusercontent.com/22584900/33897441-6a9747c0-dfa0-11e7-8d79-3f9e31760e1c.png)

As you can see on the attached image, some texts are getting cut-off. Those marked with red-colored question mark, there's supposed to be a letter or a word, but someshow its missing. So far this issue happens in some LG in Oppo phone models, haven't seen this issue in Samsung and iPhones.

Thanks in advance and more power

PS: the screenshot is taken from an LG phone, this means that it happens in production also, i can't reproduce this on development using genymotion because i can't find an LG or Oppo emulator.

**Comment by mykelaballe** [comment]
the "Moment" is supposed to be "Moments"

**Comment by GantMan** [comment]
Set `overflow: visible`.  What version of React Native?

There seems to be a lot of debate on if overflow is an issue in Android:  https://github.com/facebook/react-native/issues/6802

If so, can you increase the view size manually?

**Comment by mykelaballe** [comment]
im using 0.34 version. i know its really old version but upgrade is not an option for now. maybe in the future or if its the only way to fix this.

where should i set the overflow? in the Text or View component? actually i didnt change anything settings in the boilerplate but even the Navigation Title gets affected, just like "Moments" becomes "Moment". The letter "s" is missing

is this react or an ignite bug?

**Comment by mykelaballe** [comment]
tnx for the quick response. appreciate it

**Comment by mykelaballe** [comment]
hmm i think the issue u referenced to me is not the same with my issue. it doesnt cut-off the texts vertically, i think its only affecting it horizontally on my case

**Comment by mykelaballe** [comment]
even the word "Sendi" in the Navigation Title is supposed to be "Sendi University"

**Comment by skellock** [comment]
There's nothing actionable on our end here.  This is wrapping.  Like @GantMan suggested, making the label larger will help.  What's happening here is you're word wrapping and android is clipping that in the original rectangle.

Setting `numberOfLines={1}` will make it more obvious where that wrapping is happening.

I've had text measurement issues as well on Android, so I feel your pain.

**Comment by audiae** [comment]
I'm having my header title cut off from this, does anyone have a recommendation on what style changes to make and where?

**Comment by skellock** [comment]
I don't know the solution, but in the more recent versions of React Native, there have been some bug fixes on their text rendering.  Maybe on a new branch of your codebase you could upgrade to see if it fixes?
