### ISSUE TITLE
Bad comparison in isIgniteDirectory.js?

### ISSUE THREAD

**Issue by esbena** [infinitered/ignite#1206]
I encountered this suspicious line in your code base:
 https://github.com/infinitered/ignite/blob/f62021bc8e63a74e55b50fa2dea55f414d2d4932/src/lib/isIgniteDirectory.js#L13

`!jetpack.exists(...)` always evaluates to a boolean, so it never makes sense to compare it to the string `'file'`.

**Comment by skellock** [comment]
You’re right.  That should read `!==` since the ! in front of the the jet pack expression evaluates first.

Sharp eye.

**Comment by GantMan** [comment]
@esbena - care to do a PR?  Hopefully with a test, to assure this mistake never happens again?

**Comment by esbena** [comment]
> Hopefully with a test, to assure this mistake never happens again?

Not easy to do (see PR explanation), but you could enable PR integration for [your project on lgtm.com]( https://lgtm.com/projects/g/infinitered/ignite) to avoid similar issues in the future.

(Full disclosure: I work on lgtm's JavaScript analysis.)
