### ISSUE TITLE
Add a `destroy` command

### ISSUE THREAD

**Issue by wisn** [infinitered/ignite#1208]
Ignite have a `generate` command which is producing an example file from plugin. The missing command is `destroy` which is remove a file that generated by the plugin. Not only add a new command, this will need to change the plugin behavior as well.

```
$ ignite g saga hello
✔︎ App/Sagas/HelloSagas.js
✔︎ Tests/Sagas/HelloSagaTest.js
$ ignite d saga hello
✘ App/Sagas/HelloSagas.js
✘ Tests/Sagas/HelloSagaTest.js
```

**Comment by kevinvangelder** [comment]
We have `remove` for plugins but haven't yet built a way to remove generated files as it's usually easy enough to do it manually, but it's a good suggestion! 👍

**Comment by adrianhartanto0** [comment]
Should this be boilerplate specific command since each boilerplate has its own file structure? @jamonholmgren

**Comment by jamonholmgren** [comment]
@adrianhartanto0 Yeah, you'd just copy and paste the `generate` folder and make a `destroy` folder (and `commands/destroy/destroy.js`).

https://github.com/infinitered/ignite-bowser/tree/d0cae5484a96f4d686ab61c87428ec5749b194d6/commands

I'd wait a bit, though, as we're revamping that folder structure a bit right now.

**Comment by frankcalise** [comment]
Closing since Ignite does not contain plugins anymore

**Comment by frankcalise** [comment]
@jamonholmgren so this would remove a model/screen/component that was once generated?
