### ISSUE TITLE
Debugger does not work for a completely new project

### ISSUE THREAD

**Issue by fredbt** [infinitered/ignite#1209]
---
What's going on?

I cannot get the debugger to work for a completely new ignite app. When I open the debugger and the console, I see the message "Uncaught SyntaxError: Unexpected token ...", and in the app running in the emulator, it gets a timeout to connect to the emulator.

---
Steps to reproduce

ignite new FortuneApp
npm install
react-native start -- --reset-cache
react-native run-android

---
`ignite doctor` results:

System
  platform           linux                                                                                
  arch               x64                                                                                  
  cpu                4 cores                         Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz  
  directory          /home/fred/fortune/FortuneApp                                                        

JavaScript
  node               8.1.3        /usr/local/bin/node  
  npm                4.6.1        /usr/local/bin/npm   
  yarn               0.27.5       /usr/bin/yarn        

React Native
  react-native-cli   2.0.1       
  app rn version     0.50.4      

Ignite
  ignite             2.0.0        /usr/bin/ignite  

Android
  java               1.8.0_111    /usr/bin/java           
  android home       -            /home/fred/Android/Sdk

**Comment by fredbt** [comment]
A bit more context: the app works normally when not debugging. But if I click the "Debug remotely", it opens a new Chrome tab and times out to connect.

**Comment by fredbt** [comment]
![screenshot from 2017-12-15 19-49-44](https://user-images.githubusercontent.com/21107906/34061904-28446730-e1d1-11e7-94a1-733cafcddb7b.png)

the error seems to be around here.

**Comment by skellock** [comment]
When you debug with that debugger, your javascript moves to that environment and is not longer run with React Native.

It causes problems like this.

Unfortunately, there's nothing we seem to be able to do to fix that.  You may want to consider `react-native-debugger` or `reactotron`.  I use the latter.
