### ISSUE TITLE
Getting error after replace redux provider with Apollo Provider

### ISSUE THREAD

**Issue by kukuandroid** [infinitered/ignite#1212]
### Ignite with GraphQL support
- I'm getting Invariant violation error after replacing the provider. Could you suggest to me on how to this ? 

##Dependecies
 "apollo-client": "^2.0.4",
 "apollo-link-context": "^1.0.3",
 "apollo-link-http": "^1.3.2",
 "react-native": "^0.50.4"

**Comment by skellock** [comment]
We aren't currently using `apollo`.  And that's likely to change soon.  =)

So, I'm not sure what's going on here.
