### ISSUE TITLE
[HELP WANTED]  App running fine in development server but components (buttons) disappear when I install it in a device as a signed apk.

### ISSUE THREAD

**Issue by rajat-np** [infinitered/ignite#1214]
@brad 
The develepor version of my app runs fine but in release version only launch image is loaded, nothing more.
I tried to fix by using the following command before gradleRelease 
```
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
```
I deleted node_modules and tried yarn install as well as npm install, nothing helped. 
Also I tried using
```
react-native log-android
```
nothing there also.

**Comment by rajat-np** [comment]
This is release version launch screen. [https://imgur.com/a/eHKFt](url) 
And this is development version of the app (running fine) [https://imgur.com/a/NV9wZ](url)

**Comment by rajat-np** [comment]
Attaching the screenshots-
App in dev mode - 
![whatsapp image 2017-12-31 at 6 18 17 pm](https://user-images.githubusercontent.com/14833138/34461688-576b0496-ee57-11e7-9202-6c9001f73643.jpeg)

App in release mode- 
![whatsapp image 2017-12-30 at 10 05 44 pm](https://user-images.githubusercontent.com/14833138/34461691-606096b0-ee57-11e7-9008-c0a023aece0f.jpeg)

**Comment by brad** [comment]
@rajat-np ¯\\\_(ツ)\_/¯ Did you mean to mention someone else?

**Comment by rajat-np** [comment]
I heard Brad in the video, so I meant to mention you.

**Comment by rajat-np** [comment]
@brad yes.

**Comment by rajat-np** [comment]
@daviscabral 
@kemiller 
@twerth 
@jhblacklock ,
any help will be appreciated, thanks.

**Comment by GantMan** [comment]
Any disappearing component could be a failed component.   Implement `componentDidCatch` and have it render an error, and let me know if that fires.  If so, then you know something is causing an error and state is corrupt in that instance.

**Comment by rajat-np** [comment]
@GantMan When running the app in dev mode , it runs with no problem at all, not even yellowbox warnings and of course no red errors.

**Comment by rajat-np** [comment]
I tested the mainScreen , and there is no error in it.

**Comment by GantMan** [comment]
damn... I'm seriously confused how that's happening then.  Can you reproduce anywhere?  like in a public repo I could pull?

**Comment by rajat-np** [comment]
@GantMan I uploaded the repo , you can check it out. 
this is the repo - https://github.com/rajat-np/AKF
Many thanks for your precious time.

**Comment by GantMan** [comment]
Found it.

https://github.com/rajat-np/AKF/blob/master/App/Config/DebugConfig.js#L2

You have everything tied to if you're in dev mode or not, and a bundle is not in dev mode.

Remove this if block:
https://github.com/rajat-np/AKF/blob/master/App/Components/FeedbackButton.js#L20

**Comment by rajat-np** [comment]
@GantMan Thanks a lot. It solved my problem.

**Comment by rajat-np** [comment]
@GantMan sorry for trouble , but I need a **guiding hand** here, I want to bundle few doc files within my app so that the user can see them and read it using the app installed on the device for the doc file. I searched for it but it didn't served my exact purpose.

**Comment by GantMan** [comment]
Hiya @rajat-np 

Def come join us on the slack chat!  community.infinite.red where lots of people are helping with questions like this all the time :D 

You should be able to include your files in your bundle easily.  Join the chat and specify what you're planning to use to read the docs locally.  Webview?  PDF Viewer?   Let us know!
