### ISSUE TITLE
-bash: ignite: command not found

### ISSUE THREAD

**Issue by lichao0817** [infinitered/ignite#1216]
Hello guys,
I tried
```
~/projects$ npm install -g ignite-cli
/usr/local/Cellar/node/9.3.0_1/bin/ignite -> /usr/local/Cellar/node/9.3.0_1/lib/node_modules/ignite-cli/bin/ignite
```
without any complaints. 

But when I tried `ignite new MyNewAppName`. I got the `-bash: ignite: command not found` message.

I'm using node: 9.3.0, and npm: 5.5.1.

**Comment by tastycode** [comment]
Check your `PATH` environment variable. Make sure `/usr/local/Cellar/node/9.3.0_1/bin` is there. Homebrew's node installation should be adding that entry.

**Comment by skellock** [comment]
Agreed with @tastycode .  It's a `PATH` issue.  Perhaps the `node` you're running is different for your user.  I know `nvm` does clever things where people end up in this situation.

**Comment by hungdev** [comment]
in terminal run: 
```
open ~/.bash_profile
```
to open bash_profile, then add your ATH environment variable, example: 
```
export PATH=${PATH}:/Users/cee/.npm-global/bin/
```
then try again
ignite new MyNewAppName
