### ISSUE TITLE
Shouldn't GithubRedux been excluded when NO dev screens/examples are specified?

### ISSUE THREAD

**Issue by delkant** [infinitered/ignite#1217]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?
GithubRedux should not be part of a clean project (?)
---
Steps to reproduce
 Would you like Ignite Development Screens? No

GithubRedux still in Redux/index.js

---
`ignite doctor` results:

**Comment by GantMan** [comment]
We'll have this fixed in the new version we're working on Bowser.  If you'd like to perform a fix for this existing version, it's quite easy and we'd accept the PR!
