### ISSUE TITLE
QR Code Not Available

### ISSUE THREAD

**Issue by cpalanzo** [infinitered/ignite#1218]
What's going on?
If I create a standard react-native project and yarn start - I get a QR code no problem.
Using Ignite I never see a QR code using Yarn Start or NPM start. I can run the use react-native run-ios just fine on simulator. Not sure what is going on. All items new install. 
---
Steps to reproduce
Always RUNs the METRO Bundler
Ran ignite to create app with no extras... term output as follows:
--------------------
igniting app test2
✔ using the Infinite Red boilerplate v2 (code name 'Andross')
✔ added React Native 0.50.4 in 129.24s
? Would you like Ignite Development Screens? No
? What vector icon library will you use? none
? What internationalization library will you use? none
? What animation library will you use? none
? Would you like to include redux-persist? No
✔ added ignite-ir-boilerplate in 147.4s
✔ added ignite-standard in 101.07s
✔ configured git
✔ ignited test2 in 526.52s

    Ignite CLI ignited test2 in 526.52s

    To get started:

      cd test2
      react-native run-ios
      react-native run-android
      ignite --help

    Read the walkthrough at https://github.com/infinitered/ignite-ir-boilerplate/blob/master/readme.md#boilerplate-walkthrough

    Need additional help? Join our Slack community at http://community.infinite.red.

    Now get cooking! 🍽
--------------------------------

---
`ignite doctor` results:
iMac:test2 Charlie$ ignite doctor
System
  platform           darwin                                                                                       
  arch               x64                                                                                          
  cpu                2 cores                           Intel(R) Core(TM)2 Duo CPU     T7700  @ 2.40GHz  
  directory          /Users/Charlie/ignitetest/test2                                                              

JavaScript
  node               7.10.1       /Users/Charlie/.nvm/versions/node/v7.10.1/bin/node  
  npm                4.2.0        /Users/Charlie/.nvm/versions/node/v7.10.1/bin/npm   
  yarn               1.3.2        /usr/local/bin/yarn                                 

React Native
  react-native-cli   1.0.0       
  app rn version     0.50.4      

Ignite
  ignite             2.0.0        /Users/Charlie/.nvm/versions/node/v7.10.1/bin/ignite  

Android
  java               1.7.0_79     /usr/bin/java                       
  android home       -            /Users/Charlie/Library/Android/sdk  

iOS
  xcode              8.2.1       
iMac:test2 Charlie$ 

----- **NOTE Package JSON has this start script - not react-native start!!:**
"name": "test2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",

**Comment by skellock** [comment]
This boilerplates doesn’t use `create-react-native-app`. That’s where the qr code comes from.
