### ISSUE TITLE
Demo log in fails

### ISSUE THREAD

**Issue by kennethlynne** [infinitered/ignite#122]
![image](https://cloud.githubusercontent.com/assets/390817/15602333/eb2a5792-23f4-11e6-903e-fe10854b963f.png)

-> 

![image](https://cloud.githubusercontent.com/assets/390817/15602318/db0b5bd6-23f4-11e6-8de6-a25ea2f5768f.png)

**Comment by GantMan** [comment]
We've fixed this.  You'll need to generate a new app with our CLI to have the fix.
