### ISSUE TITLE
Ignite not able to generate components any longer?

### ISSUE THREAD

**Issue by chapeljuice** [infinitered/ignite#1220]
When I run `ignite g` it gives me a list of generators such as 'component', 'container', etc., but the descriptions are gone and they say 'missing'. See screenshot below:
<img width="856" alt="screen shot 2018-01-12 at 9 34 10 am" src="https://user-images.githubusercontent.com/862642/34887629-fa64d596-f77b-11e7-8256-a6a085e567c1.png">

Any idea what's going on?

---
`ignite doctor` results:
```
System
  platform           darwin                                                                                     
  arch               x64                                                                                        
  cpu                8 cores                               Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz  
  directory          /Users/chapeljuice/Documents/repos/raapp                                                        

JavaScript
  node               9.3.0        /Users/chapeljuice/.nvm/versions/node/v9.3.0/bin/node  
  npm                5.5.1        /Users/chapeljuice/.nvm/versions/node/v9.3.0/bin/npm   
  yarn               0.23.2       /usr/local/bin/yarn                               

React Native
  react-native-cli   2.0.1       
  app rn version     0.51.0      

Ignite
  ignite             2.0.0-beta.8   /usr/local/bin/ignite  

Android
  java               1.8.0_121    /usr/bin/java                      
  android home       -            /Users/chapeljuice/Library/Android/sdk  

iOS
  xcode              9.2 
```

**Comment by ruddell** [comment]
What you described happens if you don't have the node dependencies installed.  Try running `yarn` or `npm install` and then generating the component.  Also make sure `ignite-ir-boilerplate` is in your package.json under `devDependencies`

**Comment by chapeljuice** [comment]
Thanks for your response!

So I ran `npm install` and double checked my devDependencies. I have:
```
    "ignite-animatable": "^1.0.0",
    "ignite-dev-screens": "^2.2.0",
    "ignite-i18n": "^1.1.1",
    "ignite-ir-boilerplate": "^2.3.1",
    "ignite-vector-icons": "^1.1.0",
```
...but it's still behaving the same way.

Any other thoughts?

**Comment by skellock** [comment]
Try running with `ignite g component OmgWorkPlz --debug`... it'll be more chatty which might reveals some clues (like an out of date `yarn` or `node_modules` living in the `~` directory.

**Comment by chapeljuice** [comment]
@skellock no such luck :(

<img width="319" alt="screen shot 2018-01-12 at 10 31 34 am" src="https://user-images.githubusercontent.com/862642/34889693-d17da13c-f783-11e7-9d9b-e882681a1c52.png">

**Comment by tastycode** [comment]
Does `ignite g component OmgWorkPlz --debug --wtf` return anything (https://github.com/infinitered/ignite/blob/4e8b4a4ef441ceebebc5d85406a9c24c29784cb1/src/cli/cli.js#L51)? What's the exit code `echo $?`

**Comment by LuisUrrutia** [comment]
I have the same problem:
<img width="489" alt="captura de pantalla 2018-02-06 a la s 13 02 13" src="https://user-images.githubusercontent.com/3771248/35869523-06dcdb04-0b3e-11e8-88f8-200926f53b42.png">

**Comment by GantMan** [comment]
eek.  Can you find your global node modules and then identify if you have those generator files in your install?  Are they missing or is ignite not able to find them, is the question.

**Comment by LuisUrrutia** [comment]
First things first, I cloned ir-boilerplate and used this clone as my boilerplate.
`ignite new Bla -b /path/on/my/system`
So I think that there is a problem there. I did this 'cause the latest version of that repo, has the fix for react-navigator >= beta.28, but when i tried to install like:
`ignite new Bla`
It didn't get the latest version of that package.

**Comment by ericklarac** [comment]
@LuisUrrutia 
How did you do it?

Whenever I try to generate a new screen I got the following error.

![image](https://user-images.githubusercontent.com/8422946/35941691-bde9ecda-0c18-11e8-8e5b-ab2250ce65eb.png)

**Comment by LuisUrrutia** [comment]
@ericklarac is `ignite-ir-boilerplate` in your package.json?
Have you created your base with a cloned version  of `ignite-ir-boilerplate`?

**Comment by ericklarac** [comment]
Yes it is, and I changed it as your example but not working :(

**Comment by LuisUrrutia** [comment]
Did you run `yarn` or `npm install` after?

**Comment by ericklarac** [comment]
Yes, and react-native link

**Comment by imcodingideas** [comment]
I'm having the same issue, and added the 
"ignite-ir-boilerplate": "git+https://github.com/infinitered/ignite-ir-boilerplate.git"

and react-native link

ignite generate listview TextablesScreen

? What coding style do you want for your list? Listview (classic)
? What kind of List would you like to generate? Grid
? How will your data be presented on this list? Sectioned
✔︎ App/Containers/View.js
✔︎ App/Containers/Styles/ViewStyle.js

It's creating the name View, not TextablesScreen and it's breaking saying View.


![screen shot 2018-02-13 at 3 18 30 pm](https://user-images.githubusercontent.com/5374985/36176838-2dc19b36-10d1-11e8-97c0-bb54202c18dd.png)

**Comment by ericklarac** [comment]
@imcodingideas A quick solution could be to rename it like:

`import { View as MyView } from '....'`

And then you could use the component as 

`<MyView _props_ />`

**Comment by akhil-geekyants** [comment]
Facing the same issue. How to fix this ?

**Comment by rsumner32** [comment]
I needI need to drop the 5G drivers so I Kanda complete this build on this hypervisor vision or VMware vision and then I need to recode the better version of the universal radio hacker the Joanna Joanna saw Paul has been making working on already got one successful build and it worked and Cesar SS ID numbers but it’s on the windows and I need to be on iOS

**Comment by rsumner32** [comment]
Universal radio hacker

**Comment by ericklarac** [comment]
@akhil-geekyants @LuisUrrutia @chapeljuice 
The solution is adding the generators to the _ignite/ignite.json_

```
{
  "createdWith": "2.0.0",
  "examples": "classic",
  "navigation": "react-navigation",
  "askToOverride": true,
  "generators": {
    "component": "ignite-ir-boilerplate",
    "container": "ignite-ir-boilerplate",
    "listview": "ignite-ir-boilerplate",
    "list": "ignite-ir-boilerplate",
    "redux": "ignite-ir-boilerplate",
    "saga": "ignite-ir-boilerplate",
    "screen": "ignite-ir-boilerplate"
  }
}
```

**Comment by skellock** [comment]
Thanks @ericklarac

**Comment by James-deWitt** [comment]
I'm having this issue with v2.2.4" after downgrading from v3.1.1 due to https://github.com/infinitered/ignite/issues/1394 

Adding the generators like on the previous solution for v2.1.1 did not work (assuming I should substitute `ignite-ir-boilerplate-bowser` for `ignite-ir-boilerplate-andross`)

> {
>   "createdWith": "2.2.4",
>   "boilerplate": "ignite-bowser",
>   "examples": "classic",
>   "navigation": "react-navigation",
>   "askToOverwrite": true,
>   "generators": {
>     "component": "ignite-ir-boilerplate-bowser",
>     "model": "ignite-ir-boilerplate-bowser",
>     "screen": "ignite-ir-boilerplate-bowser",
>     "map": "ignite-maps",
>     "map-utilities": "ignite-maps",
>     "map-callout": "ignite-maps"
>   },
>   "boilerplateVersion": "4.1.1"
> }

**Comment by jamonholmgren** [comment]
We did rename `ignite-ir-boilerplate-bowser` to `ignite-bowser`, so maybe try that, @James-deWitt ?
