### ISSUE TITLE
This navigator has both navigation and container props (question)

### ISSUE THREAD

**Issue by ron04** [infinitered/ignite#1221]
Keep getting the error:

This navigator has both navigation and container props, so it is unclear if it should own its own state. Remove props: "test" if the navigator should get its state from the navigation prop. If the navigator should maintain its own state, do not pass a navigation prop.

I'm using Ignite 2( which uses redux) with react navigation.

`
    import React from 'react'
    import { View, Text, FlatList, ListItem, TouchableOpacity } from 'react-native'
    import { StackNavigator } from 'react-navigation'
    import { connect } from 'react-redux'
    import HotDealDetailsScreen from './HotDealDetailsScreen'

    // More info here: https://facebook.github.io/react-native/docs/flatlist.html

    // Styles
    import styles from './Styles/HotDealsScreenStyle'

    class HotDealsScreen extends React.Component {

      /* ***********************************************************
      * STEP 1
      * This is an array of objects with the properties you desire
      * Usually this should come from Redux mapStateToProps
      *************************************************************/
      
      constructor(props) {
        super(props);
        this.state = {
          dataObjects: [
            {title: 'Baseball', description: 'Rawling MLB', soldBy:'Amazon', price:'$10.00',discount:'50%'},
            {title: 'Stereo', description: 'Sony', soldBy:'Amazon', price:'$10.00',discount:'50%'},
            {title: 'Shoes', description: 'Nike', soldBy:'Nike', price:'$10.00',discount:'50%'},
            {title: 'Tv', description: 'Samsung', soldBy:'BestBuy', price:'$10.00',discount:'50%'},
            {title: 'Electric Saw', description: 'Dehal', soldBy:'Home Depot', price:'$10.00',discount:'50%'}
          ]
        }
        this.renderMyRow = this.renderMyRow.bind(this); //added this but still not sure why do I need to bind it to a specfic function
      };

      /* ***********************************************************
      * STEP 2
      * `renderRow` function. How each cell/row should be rendered
      * It's our best practice to place a single component here:
      *
      * e.g.
        return <MyCustomCell title={item.title} description={item.description} />
      *************************************************************/
      // renderRow ({item}) {
      //   return (
      //     <TouchableOpacity onPress={this._onPress}>
      //     <View style={styles.row}>
      //       <Text style={styles.boldLabel}>{item.title}</Text>
      //       <Text style={styles.label}>{item.description}</Text>
      //       <Text style={styles.label}>{item.soldBy}</Text>
      //       <Text style={styles.label}>{item.price}</Text>
      //       <Text style={styles.label}>{item.discount}</Text>
      //     </View>
      //     </TouchableOpacity>
      //   )
      // }

        /* Me adding it */

      openProduct = ({item}) => {
        this.props.navigation.navigate('HotDealDetailsScreen', item)
      };

      renderMyRow({item}) {
        return (
          <TouchableOpacity style={styles.row} onPress={this.openProduct}>
            <View>
              <Text>
                {item.title}
              </Text>
              <Text>{item.soldBy}</Text>
              <Text></Text>
            </View>
          </TouchableOpacity>
        );
      }

      /* ***********************************************************
      * STEP 3
      * Consider the configurations we've set below.  Customize them
      * to your liking!  Each with some friendly advice.
      *************************************************************/
      // Render a header?
      renderHeader = () =>
        <Text style={[styles.label, styles.sectionHeader]}> - Header - </Text>

      // Render a footer?
      renderFooter = () =>
        <Text style={[styles.label, styles.sectionHeader]}> - Footer - </Text>

      // Show this when data is empty
      renderEmpty = () =>
        <Text style={styles.label}> - Nothing to See Here - </Text>

      renderSeparator = () =>
        <Text style={styles.label}> - ~~~~~ - </Text>

      // The default function if no Key is provided is index
      // an identifiable key is important if you plan on
      // item reordering.  Otherwise index is fine
      keyExtractor = (item, index) => index

      // How many items should be kept im memory as we scroll?
      oneScreensWorth = 20

      // extraData is for anything that is not indicated in data
      // for instance, if you kept "favorites" in `this.state.favs`
      // pass that in, so changes in favorites will cause a re-render
      // and your renderItem will have access to change depending on state
      // e.g. `extraData`={this.state.favs}

      // Optimize your list if the height of each item can be calculated
      // by supplying a constant height, there is no need to measure each
      // item after it renders.  This can save significant time for lists
      // of a size 100+
      // e.g. itemLayout={(data, index) => (
      //   {length: ITEM_HEIGHT, offset: ITEM_HEIGHT * index, index}
      // )}

      render () {
        console.log(this.props.nav);
        console.log(this.state);
        return (
          <View style={styles.container}>
            <FlatList
              contentContainerStyle={styles.listContent}
              data={this.state.dataObjects}
              renderItem={this.renderMyRow}
              keyExtractor={this.keyExtractor}
              initialNumToRender={this.oneScreensWorth}
              ListHeaderComponent={this.renderHeader}
              ListFooterComponent={this.renderFooter}
              ListEmptyComponent={this.renderEmpty}
              // ItemSeparatorComponent={this.renderSeparator}
            />
          </View>
        )
      }
    } // end of Class

    //Navigation to handle touch on List Item into Details for the Item

    const HotDealsNav = StackNavigator({
      HotDealsScreen: {
        screen: HotDealsScreen,
        navigationOptions:{
          title:'Hot Deals'
        }
      },
      HotDealDetailsScreen: {
        screen: HotDealDetailsScreen,
        navigationOptions:{
          title:'Details'
        }
      },
    }, {
        initialRouteName: 'HotDealsScreen'
    })

    const mapStateToProps = (state) => {
      return {
        test:state
      }
    }

    const mapDispatchToProps = (dispatch) => {
      return {
      }
    }

    export default connect(mapStateToProps, mapDispatchToProps)(HotDealsNav)`

I get the error while loading a "list" created with ignite which strange enough has this comments before adding a constructor:

I found some documentation on react navigation into how to work with redux and read some other articles trying to explain it.

My question is, is Ignite 2 setup by default to use the nav state from redux and I broke it by adding my own navigation?

Or should I follow the steps to setup redux with react navigation from the react navigation documentation? (https://reactnavigation.org/docs/guides/redux))

**Comment by ron04** [comment]
Any ideas if this is Ignite Boilerplate specific? or is it React? or Redux? or react-navigation?

**Comment by skellock** [comment]
`react-navigation` wants to either control all your nav state, or control none of it.  You can't do both.  I'd recommend setting it up the way they do in `react-navigation`.  That library is moving pretty quickly, so I'd check with them (weekly).  =)

**Comment by GaneshKonathala007** [comment]
Even i am facing the similar issue with `withNavigation`
can anyone please help me how approach this problem

**Comment by gsushil999** [comment]
Is there any solution yet how to solve this issue

**Comment by jamonholmgren** [comment]
I'd recommend reading this, @gsushil999:

https://reactnavigation.org/docs/en/redux-integration.html
