### ISSUE TITLE
iOS Issues with rn 0.52.0

### ISSUE THREAD

**Issue by valinaga** [infinitered/ignite#1222]
---
I generate a new app with ignite and added maps and push notification plugin.
Then I ran react-native-git-upgrade and the iOS xproj got messed with conflicts. 
After accepting the incoming changes, I noticed in XCode that various modules were missing. Among them was PushNotification and Maps.
Any idea on how to upgrade with no errors?
Thanks,

**Comment by skellock** [comment]
I do this manually. I wish I didn’t. Every time I use a tool like that, I lose hours of my day. 

🤷‍♂️
