### ISSUE TITLE
Ignite new with react-native-vector-icons not installing latest version and throwing error

### ISSUE THREAD

**Issue by RubenPauwels1** [infinitered/ignite#1224]
# Ignite new with react-native-vector-icons not installing latest version and throwing error
---
What's going on?

When using `ignite add elements` after creating new project (`ignite new xxx`) with the option ticked to install vector icons. There is an error saying that react-native-vector-icons/Material or in case of IOS: react-native-vector-icons/Feather is not found.

I found out with the help of Rich Evens that version 4.3.0 is installed instead of the newest version (4.5.0).

---
Steps to reproduce

`ignite new MyApp` (All options to yes)
`ignite add elements`
`react-native run-android`

---
`ignite doctor` results:

System
  platform           win32
  arch               x64
  cpu                4 cores                                             Intel(R) Core(TM) i7-7560U CPU @ 2.40GHz
  directory          C:\Users\Ruben\Documents\Projects\flux\FluxIgnite

JavaScript
  node               8.9.2        C:\Program Files\nodejs\node.EXE
  npm                5.6.0        C:\Program Files\nodejs\npm.CMD
  yarn               1.1.0        C:\Users\Ruben\AppData\Roaming\npm\yarn.CMD

React Native
  react-native-cli   2.0.1
  app rn version     0.50.4

Ignite
  ignite             2.0.0        C:\Users\Ruben\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\Ruben\AppData\Local\Android\Sdk

**Comment by emmavault** [comment]
I'm not sure but maybe this issue is related to this issue: https://github.com/oblador/react-native-vector-icons/issues/626#issuecomment-357493287

**Comment by Pl4gue** [comment]
Somehow, this didn't work for me... @emmavault 

I have the same **"Unable to resolve module `react-native-vector-icons/Feather`"** error, but on Android...

**Comment by emmavault** [comment]
Maybe uninstalling `react-native-vector-icons` package and install it again ??

**Comment by Pl4gue** [comment]
Did resolve it with reinstalling the package and reloading the dependency graph for multiple times... :triumph:

**Comment by Pl4gue** [comment]
Thanks anyway :+1: :) @emmavault

**Comment by skellock** [comment]
Ugh those are the worst fixes eh?

Glad it got solved.
