### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'addListener') 

### ISSUE THREAD

**Issue by kruyvanna** [infinitered/ignite#1225]
---
What's going on?
undefined is not a function
---
Steps to reproduce
`init a new app and run`

This happens both on Android and iOS

---
`ignite doctor` results:
System
  platform           darwin                                                                                            
  arch               x64                                                                                               
  cpu                4 cores                                       Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz  
  directory          /Users/kruyvanna/Projects/Learn/Ignite/Test                                                       

JavaScript
  node               8.9.1        /usr/local/bin/node  
  npm                5.6.0        /usr/local/bin/npm   
  yarn               1.3.2        /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.50.4      

Ignite
  ignite             2.0.0        /usr/local/bin/ignite  

Android
  java               1.8.0_152    /usr/bin/java  
  android home       -            undefined      

iOS
  xcode              9.2         

![simulator screen shot - iphone 6 - 2018-02-03 at 16 33 01](https://user-images.githubusercontent.com/1171793/35765884-1b92f37a-0900-11e8-8927-80019fc0ffbb.png)

**Comment by kruyvanna** [comment]
Found package causing issue is react-navigation

https://github.com/react-navigation/react-navigation/issues/3416

**Comment by 2f-concept** [comment]
I got the same issue !

**Comment by kruyvanna** [comment]
@2f-concept 
use beta26 fixes the issue.

 "react-navigation": "v1.0.0-beta.26"

**Comment by 2f-concept** [comment]
@kruyvanna 
You saved my day! thank you 👍

**Comment by jslok** [comment]
react-navigation 1.0.0-beta.27 should also work fine.

There was a breaking change for beta 28 if you use redux. https://github.com/react-navigation/react-navigation/issues/3416

There are some steps to correct it in the updated react-navigation docs here now. https://reactnavigation.org/docs/redux-integration.html

**Comment by SafaaB4G** [comment]
@kruyvanna you saved my day too ! thank you so much

**Comment by Luckygirlllll** [comment]
How to fix that without upgrading version to "v1.0.0-beta.26"?

**Comment by cheddarwhizzy** [comment]
Using react-navigation 1.0.0-beta.30 I got it to work by modifying my ReduxNavigation.js

```
import React from 'react'
import * as ReactNavigation from 'react-navigation'
import { connect } from 'react-redux'
import AppNavigation from './AppNavigation'

// for react-navigation 1.0.0-beta.30
import {
  createReduxBoundAddListener,
  createReactNavigationReduxMiddleware,
} from 'react-navigation-redux-helpers';

const middleware = createReactNavigationReduxMiddleware(
  "root",
  state => state.nav,
);
const addListener = createReduxBoundAddListener("root");
// end for react-navigation 1.0.0-beta.30


function ReduxNavigation (props) {
  const { dispatch, nav } = props
  const navigation = ReactNavigation.addNavigationHelpers({
    dispatch,
    state: nav,
    addListener // <-- add this as well
  })

  return <AppNavigation navigation={navigation} />
}

const mapStateToProps = state => ({ nav: state.nav })
export default connect(mapStateToProps)(ReduxNavigation)
```

**Comment by bamne123** [comment]
Can anyone explain what is going on with this error??

**Comment by Bonobomagno** [comment]
use that solution for react-native v1 too.

But i pushed the middleware on the redux/index, seem more streamlined

**Comment by skellock** [comment]
@bamne123 : https://github.com/infinitered/ignite/issues/1225#issuecomment-362896714

`react-navigation` introduced a feature where screens can subscribe to the events `willBlur`, `didBlur`, `willFocus` and `didFocus`.

If you don't use `react-navigation`'s built-in state management (like most people do), then not only do you have to bring your own `state` object & `dispatch` function, you now need to bring your own `addListener` function to handle said subscriptions.

This was a breaking change.

It's a nice feature, but a little rough coming out of the gate (as is most software!).

**Comment by Pl4gue** [comment]
Hey @skellock and @kruyvanna,
I am new to React Native and Ignite.

I got the same error and replaced `ReduxNavigation.js` with @cheddarwhizzy 's shared code,
but I know get a "react-navigation-redux-helpers" not found error even after I ran
```
rm -rf node_modules/ && npm install
```
And in package.json:
```
...
"react-native-navigation-redux-helpers": "^0.5.0",
...
```

Could you please help me? :confused:

**Comment by turnamobile** [comment]
Hey guys,
I am trying to set a listener for 'didFocus' event. I followed instructions and already added to middleware.  I am using below snippet in the component,
  onComponentDidFocus = a => {
    console.log("on focus.........");
    };

  componentDidMount() {
    this._onFocusHandler = this.props.navigation.addListener(
      "didFocus",
      this.onComponentDidFocus
    );
  }
  componentWillUnmount() {
    this._onFocusHandler.remove();
  }
Even "Navigation/COMPLETE_TRANSITION" action get dispatched my event handler not getting fired and I couldnt find the reason. Can someone help me ? Thanks

**Comment by skellock** [comment]
Check out their [redux integration](https://reactnavigation.org/docs/redux-integration.html) docs.

In their code example, do you see this:

![image](https://user-images.githubusercontent.com/68273/36032081-d1a147d8-0d7a-11e8-82d9-91176e75b7d7.png)

This is the part that's likely missing in your code.

You've setup the events to listen... but now, it's still up to you to trigger them.  This is what this redux middleware will do for you.

And don't forget to add that to the store:

![image](https://user-images.githubusercontent.com/68273/36032137-07318cfa-0d7b-11e8-8357-6fe378a8ed23.png)

**Comment by turnamobile** [comment]
My store file looks like this:
```javascript
const loggerMiddleware = createLogger({
  predicate: (getState, action) => __DEV__
});

const navMiddleware = createReactNavigationReduxMiddleware(
  "root",
  state => state.nav
);
export const addListener = createReduxBoundAddListener("root");

//create store and add middleware
function configureStore(reducer) {
  const enhancer = composeWithDevTools(
    applyMiddleware(
      navMiddleware,
      thunkMiddleware, // lets us dispatch() functions
      loggerMiddleware
    )
  );
  return createStore(reducer, undefined, enhancer);
} //
//AppStore with reducers
const store = configureStore(reducers);
```
and render of root component looks like:
```javascript
 render() {
    return (
      <AppNavigator
        navigation={addNavigationHelpers({
          dispatch: this.props.dispatch,
          state: this.props.nav,
          addListener
        })}
      />
    );
  }
```

Also, if I did wrong setup on create store, shouldn't I get an error while adding listener to my navigation prop ?  
In my case I am not getting any error or warning, just my handler not getting fired.
Am I missing something ?

**Comment by skellock** [comment]
Everything seems to be correct there.  I'm not sure what the problem is.  I know that some people are reporting issues with the event system on the `react-navigation` repo.  I've personally seem problems with `didBlur`, but the other ones are fine.  

I'm using `mobx-state-tree` and wrote my own `addListener`, so I'm not certain on if there's problems with the `redux` one they ship.

**Comment by turnamobile** [comment]
I think something is wrong with "upstreamSubscribers" method in the source code while working with complicated nested navigators. 
Anyway I will try to find another solution to supply my needs.
Thank you.

**Comment by denisschmidt** [comment]
@skellock I'm using mobx and i have this problem too. How to do it with mobx? Can you show your code pls?

**Comment by skellock** [comment]
It's for `mobx-state-tree` and not `mobx`.

But the deal is the same.  It's 2 steps:

1.  provide an `addListener` function which will be called when people subscribe.
2. when your state changes (you may have this in a `mobx` class -- and likely have a `dispatch` function), you need to tell your subscribers.

That part might look something like this:

```ts
  // who is currently subscribed to react-navigation events
  const subs = new Set()

  /**
   * Fires after we change our state.  You call this from the dispatch
   * to ensure any subscribers are told about state changes.
   *
   * @param action The react-navigation action which triggered this update.
   * @param oldState The previous navigation state.
   * @param newState The next navigation state.
   */
  const fireSubscribers = (action: any, oldState: any, newState: any) => {
    // tell each subscriber out this
    subs.forEach(subscriber => {
      subscriber({
        type: "action",
        action,
        state: newState,
        lastState: oldState,
      })
    })
  }

  /**
   * Provides a way from screens (for example) to subscribe to `react-navigation`
   * events.
   *
   * @param eventName The event.
   * @param handler Some strange handler
   */
  const addListener = (eventName: string, handler: any) => {
    // not entirely react-navigation has this here
    if (eventName !== "action") {
      return { remove: () => {} }
    }

    // subscribe
    subs.add(handler)

    // return the instructions on how to unsubscribe
    return {
      remove: () => subs.delete(handler),
    }
  }

  return { addListener, fireSubscribers }
```

Please ignore the lack of confidence in my code comments.  👀

**Comment by teamoffshootbaymax** [comment]
When I upgraded to 1.0.3 from beta-0.21 I also needed to add `react-navigation-redux-helpers`

`yarn add react-navigation-redux-helpers`

**Comment by denisschmidt** [comment]
@skellock  Thank you.

**Comment by yareyaredesuyo** [comment]
I fixed this problem by @cheddarwhizzy 's answer. 

change package.json's react-navigation version to 1.0.0-beta.30 and Modify ReduxNavigation.js script as above.

It should be fiexed soon.

**Comment by neilhamilton** [comment]
For anyone using ignite-ir-boilerplate, [this commit](https://github.com/infinitered/ignite-ir-boilerplate/commit/8e09ce2c097eb200c77daf0c6a4b625ffbef4fa5) helped me get the event emitting working with React Navigation / Redux

**Comment by leonardo2204** [comment]
@cheddarwhizzy answer worked for me, but I had one more step to make it work:
`npm install --save react-navigation-redux-helpers`
Otherwise it would just not work!

Hope it helps!

**Comment by Takalani** [comment]
Hi. I'm new to both React Native and Ignite. 

I have updated the package.json file to "react-navigation": "v1.0.0-beta.26".

What do I do next? how do I update the dependecies?

**Comment by NULL-SWEAT** [comment]
I ran into this error today after creating a minimal project with ignite but if I create a new project adding only `redux-persist` there is no error.

**Comment by jsina** [comment]
@skellock I wanna call api after tab's focused, I'm integrating the redux with react-navigation. could you give me some hint about it?

**Comment by skellock** [comment]
@jsina probably best to check out `react-navigation` issues on their repo.  i've never tried that.

**Comment by Asalem1** [comment]
Thank you @kruyvanna !!!

**Comment by febuniac** [comment]
> react-navigation": "v1.0.0-beta.26

Thank you very much!
