### ISSUE TITLE
failed to add React Native 0.50.4

### ISSUE THREAD

**Issue by mohammednadeem55** [infinitered/ignite#1226]
Tried creating new Project 
end up with this error
**failed to add React Native 0.50.4**
![screenshot from 2018-02-09 21-41-35](https://user-images.githubusercontent.com/10026098/36037231-1f88dfc6-0de2-11e8-9360-f28d8f296c8e.png)

**Comment by minhphung210** [comment]
![simulator screen shot - iphone 6 - 2018-02-26 at 09 02 11](https://user-images.githubusercontent.com/25664542/36650068-cfafee5a-1ad3-11e8-9c89-ffa2fcc94296.png)

same issues
after add new project and run on ios

**Comment by skellock** [comment]
@minhphung210 Check out #1225 for more info.

**Comment by skellock** [comment]
@mohammednadeem55 are you able to run `react-native init Something` without errors?

**Comment by wemakefocus** [comment]
@skellock I met the same problem and make sure that `react-native init Something` work well finally though with some info "info There appears to be trouble with your network connection. Retrying..."
