### ISSUE TITLE
Hot reload under Windows not working

### ISSUE THREAD

**Issue by xgenvn** [infinitered/ignite#1228]
What's going on?
- Hot reloading seems not working under windows
---
Steps to reproduce
- New project
- Yes to everything
- Build and run:
```react-native run-android```
- Fixed the react-navigation integration error
- Edit some texts from LaunchScreen component
- Waiting for 1 minutes but no updating on UI, bundler not rebuilding and not detecting changes.
- Manually reload the app does reflect the changes.
---
`ignite doctor` results:
```
System
  platform           win32
  arch               x64
  cpu                4 cores                      Intel(R) Core(TM) i7
  directory          C:\dev\reactnative\SampleApp

JavaScript
  node               8.9.1        C:\Program Files\nodejs\node.EXE
  npm                5.6.0        C:\Users\<name>\AppData\Roaming\npm\npm.CMD
  yarn               1.3.2        C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1
  app rn version     0.50.4

Ignite
  ignite             2.0.0        C:\Users\<name>\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
  android home       -            C:\bin\Android\android-sdk
```
Is there anyone can check whether this issue can be reproducible?

Thanks.

**Comment by booleanBoy** [comment]
I also seem to be experiencing this with RN 0.54.2. Having to use Live Reload to see changes on save.

**Comment by skellock** [comment]
The hot-reloading doesn't work great on other platforms either.  I've personally had to stop using it, which really sucks.

**Comment by kevinvangelder** [comment]
AFAIK, hot-reloading has never worked on Windows in any React Native app, Ignite or otherwise. It's unfortunate, but survivable.

**Comment by xgenvn** [comment]
@kevinvangelder Thank you for your input.

I think I can live with this issue, press R seems convenient enough.
