### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by edoofx** [infinitered/ignite#1229]
add ignite-cli, then wanna explore this ignite..

trying to create
ignite app1
ignite app2 --min

same happen, even i cant run with default install (with development screen) , if this ignite is DISCONTINUE, please tell the others..

![incor](https://user-images.githubusercontent.com/34878571/36574975-3533a800-1883-11e8-9922-bfb1cfd70a0b.png)

**Comment by GantMan** [comment]
Gotcha, so `--min` is not working?  or is both `ignite app` and `ignite app --min`?

Just trying to verify the ticket before we dig in.

**Comment by edoofx** [comment]
right, both of them i cant use.. 

using --min or no when create new project..

**Comment by edoofx** [comment]
![doctor](https://user-images.githubusercontent.com/34878571/36614319-343614f8-1917-11e8-9b4f-67b7b0138d66.png)
here ignite doctor

**Comment by sfthurber** [comment]
i was able to eliminate all but one of the error messages by selecting "no" for each prompt -- see below:


C:\Users\user\apps>ignite new pizza2
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app pizza2
√ using the Infinite Red boilerplate v2 (code name 'Andross')
√ added React Native 0.50.4 in 244.35s
? Would you like Ignite Development Screens? No
? What vector icon library will you use? none
? What internationalization library will you use? none
? What animation library will you use? none
? Would you like to include redux-persist? No
√ added ignite-ir-boilerplate in 142.73s
The filename, directory name, or volume label syntax is incorrect.
√ configured git
√ ignited pizza2

**Comment by kevinvangelder** [comment]
@edoofx If it's not too much trouble, could you try running the command with `--debug` and post the output?

**Comment by sfthurber** [comment]
i will if i have occasion to reinstall a react native development
environment. i've switched over to google's flutter -- it just works.
wrote a how-to on medium:
https://medium.com/@sfthurber/flutter-dart-app-development-on-windows-10-without-android-studio-b686f2a82c65

**Comment by sfthurber** [comment]
will do if i have occasion to install react native again. it's not on my machine currently.

**Comment by sfthurber** [comment]
could it be that this error arises from a lack of a package.json file?

**Comment by sfthurber** [comment]
UPDATE: i created an empty package.json in my default user's directory and i no longer get this error. YMMV, of course.

**Comment by andersfloor** [comment]
I'm encountering the exact same problem in a very similar Windows environment. I did an install of ignite-cli today, but I always get the "filename... " error. Even when I try the --min install:

![image](https://user-images.githubusercontent.com/16984414/39205860-30b1e258-47fc-11e8-896a-0f4d2aa19afc.png)

When I try a regular install with selecting yes on all options, I get several mentions of the filename/directory/syntax error:

![image](https://user-images.githubusercontent.com/16984414/39205976-771fbeae-47fc-11e8-88d3-2541db6d1925.png)

Here's the full log when running the command with --debug
[ignite_run_debug_log.txt](https://github.com/infinitered/ignite/files/1944044/ignite_run_debug_log.txt)

![image](https://user-images.githubusercontent.com/16984414/39206070-b81b7498-47fc-11e8-975f-ce44f440af84.png)

When I install the app with max options, I end a basic startup-screen without dev screens (that is, after solving [this](https://github.com/infinitered/ignite/issues/1254#issuecomment-384008919) first), so I assume that the steps that should install the extra options don't get executed:

![image](https://user-images.githubusercontent.com/16984414/39206232-20fe118c-47fd-11e8-9b0f-91b5684d96e3.png)

Adding an empty package.json in my default user directory or in the directory I install from (I tried both) results in an error:
![image](https://user-images.githubusercontent.com/16984414/39206162-ed12e99c-47fc-11e8-84ce-8444b09e7282.png)

Any help greatly appreciated!

**Comment by sfthurber** [comment]
as far as i can tell, the only difference between what you're doing
and what i'm doing is the package.json and the boilerplate. i'm using
the expo fork:
https://github.com/jbosse/ignite-expo-boilerplate
i'm no longer seeing the "filename... " error.

**Comment by lvlrSajjad** [comment]
I ran this command twice : 

```
ignite new milo --min
```

once in the root of C drive (windows installation drive) got the filename error

then in the root of D drive (not a windows installation drive) got no errors at all and the project successfully depolyed

**Comment by jamonholmgren** [comment]
This issue is pretty stale, so I'm closing it. Please let me know if you still need help with it. 🙂
