### ISSUE TITLE
Clicking vector icons fails

### ISSUE THREAD

**Issue by kennethlynne** [infinitered/ignite#123]
![image](https://cloud.githubusercontent.com/assets/390817/15602366/1ca57b30-23f5-11e6-8366-e00801a57ad3.png)

-> 

![image](https://cloud.githubusercontent.com/assets/390817/15602357/1095ea0a-23f5-11e6-9fd0-b5fd1385a48f.png)

**Comment by GantMan** [comment]
@kennethlynne  is this with a generated app or inside of ignite-base?

**Comment by GantMan** [comment]
@kennethlynne - I just generated a fresh app and this doesn't happen for me.   Perhaps bc I'm on latest from Master, but I doubt it.   I'll be pushing out version 0.2.5 soon, so you should try that when you can.

Also, that error message looks indicative of something failing in the install process.   Please verify you have at least version 1.7.0 of `rnpm` with `rnpm --version`

If so, please run:
```shell
rm -rf node_modules
npm i
rpnm link
```

And report back if this works.

**Comment by GantMan** [comment]
Found the issue.  This is likely fixed, we'll push a new version now.

**Comment by GantMan** [comment]
You'll need to update your app:  https://github.com/infinitered/ignite/commit/102bd2943cd7d3a2a52beea8d989ee68b10f2558

or re-generate it.
