### ISSUE TITLE
exception undefind is not function cardstack

### ISSUE THREAD

**Issue by gvlekke** [infinitered/ignite#1230]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

I get the following stacktrace when running the ignite app for the first time

![exception](https://image.ibb.co/cJMv2c/Schermafbeelding_2018_02_27_om_11_03_18.png "Exception")

---
Steps to reproduce

When i execute 
```
ignite new AppName
cd AppName
react-native run-ios
``` 
When asked to add libraries I answer NO to all extra libraries

---
`ignite doctor` results:
System
  platform           darwin                                                                                                    
  arch               x64                                                                                                       
  cpu                8 cores                                              Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz  
  directory          /Users/gvlekke/sping/denjin-Jimu-react-native/Jimu                                                        

JavaScript
  node               8.4.0        /Users/gvlekke/.nvm/versions/node/v8.4.0/bin/node  
  npm                5.6.0        /Users/gvlekke/.nvm/versions/node/v8.4.0/bin/npm   
  yarn               1.3.2        /usr/local/bin/yarn                                

React Native
  react-native-cli   2.0.1       
  app rn version     0.50.4      

Ignite
  ignite             2.0.0        /Users/gvlekke/.nvm/versions/node/v8.4.0/bin/ignite  

Android
  java               1.8.0_112    /usr/bin/java                       
  android home       -            /Users/gvlekke/Library/Android/sdk  

iOS
  xcode              9.2

**Comment by skellock** [comment]
Check out #1225 for more info.

**Comment by gvlekke** [comment]
thx
