### ISSUE TITLE
Generated SectionList Grid, last row shifed

### ISSUE THREAD

**Issue by Derek-X-Wang** [infinitered/ignite#1231]
Hi,

I have a question about sectionlist generated by ignite2.

I'm new to React Native and creating my first app in RN, so pointing me out if I get something wrong.

<img width="50%" alt="simulator screen shot - iphone 8 plus - 2018-03-01 at 23 07 02" src="https://user-images.githubusercontent.com/6364170/36853902-9c6c8b96-1daa-11e8-8c7c-877cf0421d86.png">

The last item in the second section is shifted because section footer, "END SECTION!!!", and list has a style `justifyContent: 'space-around'`.

So I remove the line
`renderSectionFooter={this.renderSectionFooter}`

<img width="50%" alt="simulator screen shot - iphone 8 plus - 2018-03-01 at 23 07 28" src="https://user-images.githubusercontent.com/6364170/36853720-1bb9a088-1daa-11e8-8d37-174e99440c67.png">

So why this happens? And idea?

How to reproduce?

`ignite g list`
change width and height from 100 to
```
width: 150,
height: 120,
```

Thanks

**Comment by GantMan** [comment]
What version did you use to generate?  This yellow box is due to changes in React Native that haven't been settled just yet.

**Comment by Derek-X-Wang** [comment]
Hi @GantMan 

I'm using ignite 2.0.0

**Comment by kevinvangelder** [comment]
@Derek-X-Wang It appears your issue is with flexbox styling, not anything specific to Ignite. If you're still having trouble with this I'd suggest posting to our [community Slack](http://community.infinite.red) or StackOverflow, or do some flexbox tutorials to learn more about some of it's oddities.
