### ISSUE TITLE
The `ignite generate` command must be run in an ignite-compatible directory.

### ISSUE THREAD

**Issue by itanhduy** [infinitered/ignite#1234]
---
What's going on?

I used ignite generate and got error:
"The `ignite generate` command must be run in an ignite-compatible directory."

---
Steps to reproduce
I accidentally removed node_modules when installed again I got error
It seems my project is missing ignite plugins. How can I get it again?

---
`ignite doctor` results:
System
  platform           darwin                                                                                         
  arch               x64                                                                                            
  cpu                4 cores                                    Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz  
  directory          /Users/andynguyen/Code/ServeHut/ServeHut                                                       

JavaScript
  node               8.9.4        /usr/local/bin/node  
  npm                5.6.0        /usr/local/bin/npm   
  yarn               1.5.1        /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.53.0      

Ignite
  ignite             2.0.0        /usr/local/bin/ignite  

Android
  java               1.8.0_152    /usr/bin/java  
  android home       -            undefined      

iOS
  xcode              9.2

**Comment by skellock** [comment]
`yarn install ignite-ir-boilerplate`

**Comment by inturbidus** [comment]
I got a similar error because I deleted the ignite directory.  Just add it back with the ignite.json only and the error goes away.
