### ISSUE TITLE
Misunderstanding app

### ISSUE THREAD

**Issue by daleixo-gocontact** [infinitered/ignite#1238]
Hello

I came accross Ignite tool and it seems pretty cool. I must be using bad practices in my react-native apps since i do not understand some of the logic, mainly related with Redux.  Also, you have one folder named App and another ignite. 

The question is, is there any material that i can read in order to fully understand the practicies you are using in the app? Maybe a doc with what ignit new generated ?  The boilerplate is the one maintained by you. 

Thank you

**Comment by kevinvangelder** [comment]
Hey there! The best place to learn about our best practices is our blog. Here is a good starting place: https://shift.infinite.red/unveiling-ignite-2-d27d772c4959

The next iteration of our boilerplate should be coming out in the next month or so.
