### ISSUE TITLE
Old packages

### ISSUE THREAD

**Issue by AlirezaAkbarix** [infinitered/ignite#1239]
Nice boilerplate but using `ignite new app` makes an app with old libs.
e.g `"react-navigation": "1.0.0-beta.11"` that is a very useful package and it's current version is `1.5.1` with a lot of changes.
Now after updating `react-navigation` I have a lot of errors and because of that I'm not familiar with Redux, I'm not sure whats the problem.

P.S: If ignite init new project with match new packages, it's reliable to continue developing on this skeleton.

**Comment by GantMan** [comment]
We have a new release coming soon.  We know it's far behind, but the plan is to release in the next month.

here's the upcoming version:  https://github.com/infinitered/ignite-ir-boilerplate/tree/ignite_bowser

**Comment by jekirl** [comment]
Is that usable in its current form? Thanks

**Comment by GantMan** [comment]
yup!  You can use it, it will be slightly updated though.  All updated will be trackable in git.

**Comment by GantMan** [comment]
To use it, you use the `-b` flag to point to a different boilerplate during the ignite process.

**Comment by jekirl** [comment]
So I take it you recommend starting a new project with the bowser branch? Thanks

**Comment by GantMan** [comment]
Yes!  Definitely... though there are no docs for you just yet.

**Comment by jekirl** [comment]
Awesome thanks. I would assume that it functions and is used more or less like the current version though, right? Thanks again

**Comment by GantMan** [comment]
Correct, this is the latest and greatest (minus some updates we will be making)

**Comment by omairvaiyani** [comment]
What exactly must be enter into use this branch? ```ignite new AppName -b bowser```?

**Comment by omairvaiyani** [comment]
Nevermind figured it out - in case it helps another newcomer:

clone repo and set branch to ```ignite_bowser``` 
```cd path_one_up_from_repo```  
```ignite new AppName -b ./ignite-ir-boilerplate```

**Comment by xgenvn** [comment]
@omairvaiyani I'm trying to use the ignite_bowser branch, but it throws error while doing
```
ignite add vector-icons
```

Is it possible to add vector-icons and maps this way?

**Comment by skellock** [comment]
Some of the existing plugins are targeting a different filesystem setup, so no.  Not yet at least.

**Comment by xgenvn** [comment]
@skellock thank you.
There's one more thing I noticed about the setup of the branch, is there any good reason to switch to mobx? (I know this should be asked on the target repository)

**Comment by skellock** [comment]
Ya, we've switched to `mobx` and `mobx-state-tree` a while ago. These libs simply do more for you.  `redux` does one thing but does it well.  These things tend to be moving targets. =)

**Comment by AlirezaAkbarix** [comment]
@omairvaiyani Should it work on windows too? I've tested on mac and was OK, but using on windows creates a normal ignite boilerbpate : 'ignite new AppName /b /ignite-ir-boilerplate'

**Comment by kevinvangelder** [comment]
On Windows you should use the `--boilerplate=C:/path/to/boilerplate` option.

**Comment by ccfiel** [comment]
I got this error

```
chris@chris-Inspiron-13-5368:~$ ignite new todoapp -b ./ignite-ir-boilerplate
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app todoapp
✔ using the Infinite Red boilerplate v2 (code name 'Andross')
✔ added React Native 0.52.2 in 24.55s
? Would you like Ignite Development Screens? Yes
? What vector icon library will you use? react-native-vector-icons
? What internationalization library will you use? react-native-i18n
? What animation library will you use? react-native-animatable
? Would you like to include redux-persist? No
✖ /home/chris/todoapp/todoapp/ignite-ir-boilerplate was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add /home/chris/todoapp/todoapp/ignite-ir-boilerplate --dev
warning enzyme > rst-selector-parser > nearley > nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
error An unexpected error occurred: "Package \"/home/chris/todoapp/todoapp/ignite-ir-boilerplate\" refers to a non-existing file '\"/home/chris/todoapp/todoapp/ignite-ir-boilerplate\"'.".

```
any ideas?

**Comment by xgenvn** [comment]
@ccfiel can you try the full path to the branch?

**Comment by ccfiel** [comment]
@xgenvn correct! :D for newbi like me what I did
```ignite new todoapp -b /home/chris/ignite-ir-boilerplate
````

**Comment by ccfiel** [comment]
using this ignite new todoapp -b /home/chris/ignite-ir-boilerplate but I did not see any mobx still redux. Did I miss something?

**Comment by GantMan** [comment]
Is your local branch pointed towards the bowser branch?

https://github.com/infinitered/ignite-ir-boilerplate/tree/ignite_bowser

**Comment by xgenvn** [comment]
@ccfiel 
```
cd /home/chris/ignite-ir-boilerplate
git checkout ignite_bowser
ignite new todoapp -b /home/chris/ignite-ir-boilerplate
```

**Comment by ccfiel** [comment]
@GantMan its now working. Thanks @xgenvn made a little modification in the command

```
cd /home/chris/ignite-ir-boilerplate
git checkout ignite_bowser
cd ..
ignite new todoapp -b /home/chris/ignite-ir-boilerplate
```
