### ISSUE TITLE
ignite a tab-view : Command failed: yarn add react-native-MODULENAME

### ISSUE THREAD

**Issue by ahmadsyamim** [infinitered/ignite#1241]
im trying to add a plugin. However when i'm running,

> ignite a tab-view

DEPRECATION WARNING: Heads up! `index.js` in plugins is deprecated. Please use `plugin.js` instead!
Found in /PizzaApp/node_modules/ignite-tab-view/index.js.
✖ Command failed: yarn add react-native-MODULENAME
error An unexpected error occurred: "Couldn't find package \"react-native-MODULENAME\" on the \"npm\" registry.".

**Comment by skellock** [comment]
Seems like you need to change your plugin's code.  That's the default that the template spits out.

If you don't have any extra `node_modules` to install with your plugin, you can just remove that.
