### ISSUE TITLE
Improve Redux setup by removing boilerplate

### ISSUE THREAD

**Issue by yordis** [infinitered/ignite#1243]
I created a bunch of PR on React Navigation Redux helpers, some of them made it and the others ones I added it to https://github.com/straw-hat-team/react-navigation-redux-helpers (sorry for the lack of documentation folks, the code is small and we are working hard in other code base, sorry)

### Add Nav Reducer

https://github.com/react-navigation/react-navigation-redux-helpers/pull/5

Example:

```js
// ./src/redux/reducers/navigation.js

import { createNavigationReducer } from "react-navigation-redux-helpers";
import { RootNavigator } from "../path/to/your/navigator-component";

export const navReducer = createNavigationReducer(RootNavigator);
```

No need for creating your own 

### Add Screen Tracker

PR: https://github.com/react-navigation/react-navigation-redux-helpers/pull/6 but got rejected 😢 

Implemented on: https://github.com/straw-hat-team/react-navigation-redux-helpers/blob/d265ef15ca1d7203bd46e488b79ff97eb20cebeb/src/middleware/screen-tracking.ts#L14

Example:

```javascript
import { GoogleAnalyticsTracker } from "react-native-google-analytics-bridge";
import { createScreenTrackingMiddleware } from "react-navigation-redux-helpers";

const  navStateSelector = (state) => state.navigation

const ScreenTrackingMiddleware = createScreenTrackingMiddleware(
  navStateSelector,
  (fromScreen, toScreen) => {
    tracker.trackScreenView(toScreen);
    console.tron.log(`NAVIGATING ${fromScreen} to ${toScreen}`)
  }
```

### Add Stateful Nav Component + Android Back button management

PR: https://github.com/react-navigation/react-navigation-redux-helpers/pull/14 but got rejected 😢

Implemented on: https://github.com/straw-hat-team/react-navigation-redux-helpers/blob/d265ef15ca1d7203bd46e488b79ff97eb20cebeb/src/stateful-navigator.tsx#L67

```javascript
import {
  createReactNavigationReduxMiddleware,
  createStatefulNavigator
} from "react-navigation-redux-helpers";

const navigationSubscriberKey = "root";
const navStateSelector = state => state.navigation // make sure that you use your reducer key

// 1. create the middleware first
const ReactNavigationMiddleware = createReactNavigationReduxMiddleware(
    navigationSubscriberKey,
    navStateSelector
  );

// 2. add the middleware to your store

// 3. create the HOC

const Navigator = createStatefulNavigator(
    navigationSubscriberKey,
    navStateSelector,
    RootNavigator
  );

// 4. use <Navigator /> from now on
```

This last one will replace your `ReduxNavigation` file and the good thing is that it will add Android back button support https://github.com/straw-hat-team/react-navigation-redux-helpers/blob/d265ef15ca1d7203bd46e488b79ff97eb20cebeb/src/stateful-navigator.tsx#L34

cc: @jamonholmgren this is related to the stuff I showed you on the streaming, what do you think? Sorry for the delay.

**Comment by jamonholmgren** [comment]
Hey @yordis, sorry about the delay! I've been on vacation.

I'd recommend that you fork our Redux boilerplate and implement these changes on your fork. We can link to it from our boilerplates list. We're moving on from Redux, so you won't find a lot of activity on our Redux boilerplate going forward other than community-driven changes.
