### ISSUE TITLE
How to publish application in production mode

### ISSUE THREAD

**Issue by NaseebullahSafi** [infinitered/ignite#1244]
Currently I've been building the application and debugging by using this command:

```
react-native run-android
```

I would then view it on my Samsung mobile.

I would like to now publish the app in production mode. How do we go about this with ignite?

**Comment by GantMan** [comment]
Hiya @NaseebullahSafi 

I hope these docs help:  https://facebook.github.io/react-native/docs/running-on-device.html

We don't have any special steps, but when you're ready to publish to the app store, I recommend these steps:  https://shift.infinite.red/simple-react-native-android-releases-319dc5e29605

cheers!
