### ISSUE TITLE
Error add firebase plugin

### ISSUE THREAD

**Issue by jeancabral** [infinitered/ignite#1245]
---
What's going on?

I have got below error, when add firebase plugin

DEPRECATION WARNING: addPluginComponentExample called with 'FirebaseExample.js' and no .ejs extension. Add .ejs to your template filename when calling this function.
✖ Cannot read property 'includes' of undefined
➜  MyApp git:(master) ✗ react-native start      

---
Steps to reproduce
ignite add firebase
---
`ignite doctor` results:

System
  platform           linux                                                                                
  arch               x64                                                                                  
  cpu                4 cores                           Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz  
  directory          /home/jean/Projetos/MyApp                                                      

JavaScript
  node               9.6.1        /usr/local/bin/node  
  npm                5.6.0        /usr/local/bin/npm   
  yarn               1.5.1        /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.50.4      

Ignite
  ignite             2.0.0        /usr/local/bin/ignite  

Android
  java               1.8.0_161    /usr/bin/java           
  android home       -            /home/jean/Android/Sdk

**Comment by ruddell** [comment]
You should open this issue in the https://github.com/stoneman1/ignite-firebase repository.
Note that the readme says:
>THIS PLUGIN IS STILL IN VERY EARLY STAGE. USE AT OWN RISK.
