### ISSUE TITLE
There's nothing inside my new app

### ISSUE THREAD

**Issue by mykelaballe** [infinitered/ignite#1249]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?
Nothing has been generated by ignite new MyApp. the folder is created but there's nothing inside. i see the cli starting the ignite process but the stops at "igniting app MyApp"
---
Steps to reproduce
just  run "ignite new MyApp"

OS: Windows 8 64-bit
node: 9.10.1
npm: 5.8
ignite-cli: 2.0.0
react-native-cli: 2.0.1
---
`ignite doctor` results:

**Comment by mykelaballe** [comment]
can anyone help me with this? im still not able to generate anything using "ignite new MyApp". I've tried reinstalling every tools using choco.

Node: 9.10
NPM: 4.5.0
Ignite: 2.0.0
Python: 2.7
Yarn: 1.5.1

![image](https://user-images.githubusercontent.com/22584900/38344843-52e86ede-38be-11e8-97da-e37d46a771b1.png)

as you can see in the image, it just stops at "igniting app MyApp"

And here's my globally installed packages

![image](https://user-images.githubusercontent.com/22584900/38344885-83c5ef68-38be-11e8-8493-48fa09f3b46a.png)

**Comment by mykelaballe** [comment]
I did a re-install and removed some global packages:

![image](https://user-images.githubusercontent.com/22584900/38345553-5df5cc82-38c2-11e8-87a3-d30d592860cb.png)

As you can see, 

i removed:
generator-react-native-ignite@1.13.0
react-native-ignite@1.13.0

updated:
react-native-cli@1.0.0 to react-native-cli@2.0.1

But still the same, i still see empty folder

**Comment by mykelaballe** [comment]
I've re-installed npm and yarn, then run "npm cache clear --force"

but now i'm seeing this error when running "npm ls -g --depth=0"

![image](https://user-images.githubusercontent.com/22584900/38345850-f8b2508c-38c3-11e8-9bcc-356498da62e2.png)

**Comment by mykelaballe** [comment]
still no response from the ignite team? :(

**Comment by kevinvangelder** [comment]
Hey, sorry we couldn't get back to you right away, unfortunately it can take a day or two for us to respond as we spend most of our time working on client projects.

Can you try running the generate command with the `--debug` flag and post the output? It looks like something is going wrong early on in the process (otherwise you'd be seeing a `Installing React Native` line in the output).

**Comment by mykelaballe** [comment]
This is from ignite doctor

![image](https://user-images.githubusercontent.com/22584900/38346202-1ce6d58e-38c6-11e8-9d31-ac7cf03d250b.png)

**Comment by mykelaballe** [comment]
this is from "ignite new App2 --debug"

![image](https://user-images.githubusercontent.com/22584900/38346225-43d2763a-38c6-11e8-9873-091107c2c138.png)

**Comment by mykelaballe** [comment]
btw should it be like this:

![image](https://user-images.githubusercontent.com/22584900/38346289-a412f1be-38c6-11e8-9a2c-dfa0203bb714.png)

![image](https://user-images.githubusercontent.com/22584900/38346299-b241c116-38c6-11e8-854f-29bef8ef5d81.png)


As you can see in the images, the path is supposed to be pointing to a ignite cmd executable right? but inside the bin folder i dont see any ignite.exe file. could it be the issue?

**Comment by kevinvangelder** [comment]
Ignite is running, otherwise you wouldn't see the ASCII art, it would say `command not found`.

It looks from the debug output that it's not running into any errors, did it not create an App2 directory?

**Comment by mykelaballe** [comment]
it creates the directory but there's nothing inside. totally empty

**Comment by mykelaballe** [comment]
any news?

**Comment by mykelaballe** [comment]
I tried restarting my pc but still did not work. Also I can't a project  using "react natve new AppName". Here's my latest global package listing

![image](https://user-images.githubusercontent.com/22584900/38348158-bf1d8206-38d2-11e8-89ca-89a264a9e53e.png)

**Comment by mykelaballe** [comment]
So now the ignite actually starts its "igniting" process when I installed ```react-native-ignite``` globally but there are quite a few problems:

1. the react versions it creates are outdated, inside the `package.json`, react is 15.4.2, while react-native is 0.39.2

2. the ignite gets stuck in this part

![image](https://user-images.githubusercontent.com/22584900/38355741-66497ae0-38f0-11e8-8ec9-6bd1bf00e9f4.png)

3. why ami I not able to run `ignite new App --max`?

4. when you look at the folder generated, unlike before its totally empty, but now there are files inside but its not complete since I terminated the process bcoz its taking a long tie already, running for a few hours already and its still stuck

![image](https://user-images.githubusercontent.com/22584900/38355874-b785bc70-38f0-11e8-950a-6f94fb910e3c.png)

As you can see, there are files, so does this mean you have to install both `ignite-cli` and `react-native-ignite` globally? Why in the installation docs it only specifies to install `ignite-cli`? Over at my side I am not able to generate files if I only install `ignite-cli`, it only generates the App directory but nothing is inside it. But with `react-native-ignite` installed there are files generated, but then its stuck also

Whats going on with this repo? Is the problm isolated over at my side only?

5. when i run `ignite --version`, its showing 1.13.0, not the latest 2.0.0. Does this mean `react-native-ignite` overwrites my previous installation of `ignite-cli`?

![image](https://user-images.githubusercontent.com/22584900/38356122-75365c20-38f1-11e8-8292-d43086d3bbc8.png)


Here's my latest `ignite doctor` and `npm ls -g --depth=0`:


`ignite doctor`

![image](https://user-images.githubusercontent.com/22584900/38356136-8030011c-38f1-11e8-9480-e595b4ec1542.png)

`npm ls -g --depth=0`

![image](https://user-images.githubusercontent.com/22584900/38356208-b022f582-38f1-11e8-89c0-f6e0df274201.png)


Please can someone help me resolve this issue? I cant start any project with this in the way. Thanks and more power to the Ignite team

**Comment by mykelaballe** [comment]
still no fix?

**Comment by mykelaballe** [comment]
:(

**Comment by kevinvangelder** [comment]
Sorry, I gave you the wrong command. Can you see if `react-native init NewApp` works?

**Comment by mykelaballe** [comment]
Hello sorry for the late response. So this is the current states now:

Globally installed packages:

![image](https://user-images.githubusercontent.com/22584900/38476643-755bafaa-3be1-11e8-9876-a03e73e3abcf.png)

Ignite doctor:

![image](https://user-images.githubusercontent.com/22584900/38476902-abd8d566-3be2-11e8-8b40-7d9be39b0e74.png)


Thru `react-native init MyApp (successful)`:

![image](https://user-images.githubusercontent.com/22584900/38476391-1097ac5a-3be0-11e8-8cf9-237f2b7e1d84.png)


Thru 'ignite new IgniteApp` with globally installed `react-native-ignite`:

![image](https://user-images.githubusercontent.com/22584900/38477954-5661d172-3be8-11e8-90ae-c798531c2f1c.png)

It creates the directory with generated files and folders but the "igniting process" gets stuck. It doesnt get finished

Thru `ignite new IgniteApp` without globally installed `react-native-ignite`:

It creates the directory but NO files and directories inside

**Comment by kevinvangelder** [comment]
How long did you let it run? It can take 5-10 minutes sometimes.

**Comment by mykelaballe** [comment]
more or less an hour already. if ifs ok with you, you can teamviewer my PC and see you for yourself. this is very weird. what I'm currently doing now is taking an existing project and changing the values in ios and android folders, like the application name, MainActivity.java, MainApplication.java, etc

**Comment by fajieyefu** [comment]
> more or less an hour already. if ifs ok with you, you can teamviewer my PC and see you for yourself. this is very weird. what I'm currently doing now is taking an existing project and changing the values in ios and android folders, like the application name, MainActivity.java, MainApplication.java, etc

hi  I had the same problem. 'Running React Native setup version 0.39.2 (~ 2 minutes-ish)' all the time 
 ,Have you solved this problem?

**Comment by fajieyefu** [comment]
> more or less an hour already. if ifs ok with you, you can teamviewer my PC and see you for yourself. this is very weird. what I'm currently doing now is taking an existing project and changing the values in ios and android folders, like the application name, MainActivity.java, MainApplication.java, etc
![image](https://user-images.githubusercontent.com/19398548/50260584-96277900-0443-11e9-93b2-f1a786a3046c.png)



> more or less an hour already. if ifs ok with you, you can teamviewer my PC and see you for yourself. this is very weird. what I'm currently doing now is taking an existing project and changing the values in ios and android folders, like the application name, MainActivity.java, MainApplication.java, etc

![image](https://user-images.githubusercontent.com/19398548/50260632-c8d17180-0443-11e9-8ec6-d5c9a5c13ef5.png)

**Comment by jamonholmgren** [comment]
Hi @fajieyefu , we unfortunately no longer support React Native version 0.39. I'm going to close this issue, but if you find a solution please do post it here.

**Comment by leonelOcsa** [comment]
So what version we are supposse to use? Please! I'm stuck at installation the whole day...

**Comment by jazibabdullah1** [comment]
@jamonholmgren is there any solution?

**Comment by jazibabdullah1** [comment]
@leonelOcsa @fajieyefu  have you found any solution?

**Comment by Mightyciti** [comment]
What is the solution please because i am facing the same problem here

**Comment by jamonholmgren** [comment]
@Mightyciti Please file a new issue with everything you've tried so far and any debug info you can provide. Saying "I'm facing the same problem here" on a 5 year old closed issue doesn't really give us enough to figure it out.
