### ISSUE TITLE
Best way to keep my project up to date

### ISSUE THREAD

**Issue by gbaladi** [infinitered/ignite#125]
Hi,

Ignite is a wonderful boilerplate.

how I can keep my ignite base application up to date? Is there a repository I can merge from?

tks

**Comment by GantMan** [comment]
Hi @gbaladi 

We keep updating a live project along-side called `ignite-base`.   Ignite-base is actually, the source of the code for generated apps.  So any application that was generated at time X, and then ignite progresses to time Y, could be also updated by looking at commits to ignite-base between X and Y.

I know that doesn't sound ideal, but as you can see in [our roadmap](https://github.com/infinitered/ignite/wiki/Roadmap) we plan to _eventually_ get there in version 3.

A manual process with step by step commits as instructions is nice for keeping everything up to date when compared to nothing, but I know for a fact we can't wait for version 3.0!

**Comment by GantMan** [comment]
One thing we plan on doing, especially when we need to handle big changes in React, is a upgrade guide, which will be a small assistive document during those critical upgrades.

**Comment by GantMan** [comment]
closing this discussion.
