### ISSUE TITLE
failed to add React Native 0.5x.x

### ISSUE THREAD

**Issue by valinaga** [infinitered/ignite#1251]
[Edited] The issue was from the app name which started with a digit. Apparently an issue!

Hi,

I got a problem when trying to pick a custom RN version. It used to work with this precise version.
However when I tried again for a new app I got this error:

$ ignite new 60plus --react-native-version 0.54.2

🔥 igniting app 60plus
✔ using the Infinite Red boilerplate v2 (code name 'Andross')
✖ failed to add React Native 0.54.2

if I try with the latest I got a different error which I believe it's normal:
💩  react native version 0.55.4 not found on NPM -- 0.42.0 recommended
since you might not add it.

But then I tried with 0.42.0 and I got:
✖ failed to add React Native 0.42.0

and without anything:
✖ failed to add React Native 0.50.4

Nothing special on 
`ignite doctor` results:

System
  platform           darwin
  arch               x64
  cpu                4 cores                     Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  directory          /Users/vali/MyWorks/react

JavaScript
  node               9.4.0        /Users/vali/.nvm/versions/node/v9.4.0/bin/node
  npm                5.6.0        /Users/vali/.nvm/versions/node/v9.4.0/bin/npm
  yarn               1.3.2        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0        /Users/vali/.nvm/versions/node/v9.4.0/bin/ignite

Android
  java               1.8.0_111    /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java
  android home       -            /Users/vali/Library/Android/sdk

iOS
  xcode              9.3

**Comment by kevinvangelder** [comment]
Hey, thanks for the report. I just tried `ignite new example --react-native-version=0.54.2` and it was successful. Maybe you were previously using the shorthand flag (which doesn't require the equals sign)?
