### ISSUE TITLE
Question about persist

### ISSUE THREAD

**Issue by lucaspedroza1** [infinitered/ignite#1253]
Hi guys, 

I'm new with ignite, redux and redux-persist and I got a little lost with the persistence operation.

I looked at some examples and I did not quite understand how to start.

In my app I have a simple introduction page and after the user goes through it once, I can no longer display it.

I tried to put the intro saga on the whitelist, but Its not working and do not know if I'm on the right track.

Could you help me with some example of how I can pass the state and receive the information before loading the first page?

Regards

---

`ignite doctor` results:
System
  platform           darwin                                                                                   
  arch               x64                                                                                      
  cpu                4 cores                              Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz                                                     

JavaScript
  node               9.11.1       /Users/lucas/.nvm/versions/node/v9.11.1/bin/node  
  npm                5.6.0        /Users/lucas/.nvm/versions/node/v9.11.1/bin/npm   
  yarn               1.0.2        /usr/local/bin/yarn                               

React Native
  react-native-cli   2.0.1       
  app rn version     0.50.4      

Ignite
  ignite             2.0.0        /Users/lucas/.nvm/versions/node/v9.11.1/bin/ignite  

Android
  java               1.8.0_161    /usr/bin/java  
  android home       -            undefined      

iOS
  xcode              9.3

**Comment by kevinvangelder** [comment]
@lucaspedroza1 Sorry for the delay. Without seeing a good portion of your code we won't really be able to know what is causing your problem. If you're still looking for help, you can get more real-time discussions on the Infinite Red Slack Community https://community.infinite.red or the Redux channel on the React Discord.
