### ISSUE TITLE
not able to run the newly created ignite project

### ISSUE THREAD

**Issue by mk48** [infinitered/ignite#1254]
I just created a new ignite project and not able to run, getting below error.
I didn't even open the source code.
I just did the below steps:-

have I missed any configuration?

npm install -g ignite-cli
ignite new IgTst
cd IgTst
npm install
react-native run-android

![image](https://user-images.githubusercontent.com/3082469/38789868-c65dcd38-415a-11e8-8b46-02905c9d1449.png)
![image](https://user-images.githubusercontent.com/3082469/38789873-d234515e-415a-11e8-9123-d56d7aa164be.png)

**Ignite doctor** 
C:\k\IgTst>ignite doctor
System
  platform           win32
  arch               x64
  cpu                8 cores      Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz
  directory          C:\k\IgTst

JavaScript
  node               9.8.0        C:\Program Files\nodejs\node.EXE
  npm                5.6.0        C:\Program Files\nodejs\npm.CMD
  yarn               1.5.1        C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1
  app rn version     0.50.4

Ignite
  ignite             2.0.0        C:\Users\*****\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\Program Files\Java\jdk1.8.0_162\bin\java.EXE
  android home       -            C:\Users\*****\AppData\Local\Android\Sdk

**Comment by skellock** [comment]
Have a look at this issue for some answers.  React Navigation's API has changed.

https://github.com/infinitered/ignite/issues/1225

**Comment by NULL-SWEAT** [comment]
What worked for me was not using `ReduxNavigation` on the `RootContainer`, instead I imported and used `AppNavigation` on `RootContainer`.
