### ISSUE TITLE
Cannot find module '@babel/core', while trying to run PizzaApp example app

### ISSUE THREAD

**Issue by therealgilles** [infinitered/ignite#1257]
I followed the instructions to create a new app. Installation seemed to go fine. When I tried to run, I hiy the following error in Metro bundler:

```
Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: Error: Cannot find module '@babel/core' (While processing preset: "/Users/***/PizzaApp/node_modules/babel-preset-react-native/index.js")
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/***/PizzaApp/node_modules/@babel/plugin-transform-block-scoping/lib/tdz.js:6:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

Any advice?

---
Steps to reproduce

> npm install -g ignite-cli
> ignite new PizzaApp
> cd PizzaApp/
> react-native run-ios

---
`ignite doctor` results:

```System
  platform           darwin                                                                                                     
  arch               x64                                                                                                        
  cpu                4 cores                                                Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz  
  directory          /Users/***/PizzaApp                                                       

JavaScript
  node               8.11.1       /Users/***/.nvm/versions/node/v8.11.1/bin/node  
  npm                5.8.0        /Users/***/.nvm/versions/node/v8.11.1/bin/npm   
  yarn               0.16.1       /usr/local/bin/yarn                                

React Native
  react-native-cli   2.0.1       
  app rn version     0.50.4      

Ignite
  ignite             2.0.0        /Users/***/.nvm/versions/node/v8.11.1/bin/ignite
```

**Comment by kevinvangelder** [comment]
Hey, can you try downgrading your Metro version? I saw some chatter about them doing a release within the past few hours upgrading Babel and potentially being breaking changes.

**Comment by therealgilles** [comment]
Unlikely to be the cause. React-native has the metro-bundler version set as follows:

```
node_modules/react-native/package.json:    "metro-bundler": "^0.20.1",
```

**Comment by therealgilles** [comment]
@kevinvangelder, let me know if I am not understanding your comment properly. Where would I change the Metro version?  I do not have it installed globally.

**Comment by therealgilles** [comment]
After making sure I did not have any old metro-bundler processes running, I do not get the above error anymore, but running the app in the simulator shows the red screen below:

![screen shot 2018-04-20 at 4 11 24 pm](https://user-images.githubusercontent.com/18076992/39077323-e7d2f3a4-44b5-11e8-833b-48ba96e4d8b5.png)

**Comment by therealgilles** [comment]
Hmm I guess if babel bundling failed, that makes sense that there would be no .jsbundle file...

**Comment by therealgilles** [comment]
I know there are a lot of variables in building a react-native app, but it would be nice if Ignite would publish known working configurations so that people have something that works to start with.

I was able to get it working back in 12/16, but just trying to get an example app to work right now is unnecessarily frustrating. Of course, I could be doing something wrong on my end. But nowhere do I see specific set versions of OS/Xcode/iOS (equivalent on Android), react-native, and so on. And of course I would not be asking if it was just working out of the box.

**Comment by therealgilles** [comment]
Support for this package is sadly lacking. Here is what I had to do to make it work:

> react-native upgrade
(I said yes to replacing the files it prompted about)

Then I made the following changes to package.json (related to https://github.com/infinitered/ignite-ir-boilerplate/pull/185):

```
-    "react-navigation": "^1.0.0-beta.21",
+    "react-navigation": "^1.5.11",
+    "react-navigation-redux-helpers": "^1.0.4",
...
-    "ignite-ir-boilerplate": "^2.3.1",
+    "ignite-ir-boilerplate": "git+https://github.com/infinitered/ignite-ir-boilerplate.git",
```

Finally, I add to manually modify some files, again because of the above:

```
diff --git a/App/Navigation/ReduxNavigation.js b/App/Navigation/ReduxNavigation.js
index 154f599..652d53c 100644
--- a/App/Navigation/ReduxNavigation.js
+++ b/App/Navigation/ReduxNavigation.js
@@ -1,5 +1,6 @@
 import React from 'react'
 import * as ReactNavigation from 'react-navigation'
+import { createReduxBoundAddListener } from 'react-navigation-redux-helpers'
 import { connect } from 'react-redux'
 import AppNavigation from './AppNavigation'
 
@@ -8,7 +9,8 @@ function ReduxNavigation (props) {
   const { dispatch, nav } = props
   const navigation = ReactNavigation.addNavigationHelpers({
     dispatch,
-    state: nav
+    state: nav,
+    addListener: createReduxBoundAddListener('root'),
   })
 
   return <AppNavigation navigation={navigation} />
diff --git a/App/Redux/CreateStore.js b/App/Redux/CreateStore.js
index 2a9e63e..963275e 100644
--- a/App/Redux/CreateStore.js
+++ b/App/Redux/CreateStore.js
@@ -2,6 +2,7 @@ import { createStore, applyMiddleware, compose } from 'redux'
 import Config from '../Config/DebugConfig'
 import createSagaMiddleware from 'redux-saga'
 import ScreenTracking from './ScreenTrackingMiddleware'
+import { createReactNavigationReduxMiddleware } from 'react-navigation-redux-helpers'
 
 // creates the store
 export default (rootReducer, rootSaga) => {
@@ -10,6 +11,13 @@ export default (rootReducer, rootSaga) => {
   const middleware = []
   const enhancers = []
 
+  /* ------------- Navigation Middleware ------------ */
+  const navigationMiddleware = createReactNavigationReduxMiddleware(
+    'root',
+    state => state.nav
+  )
+  middleware.push(navigationMiddleware)
+
```

@kevinvangelder, do you know why the project hasn't been updated to fix those issues?

**Comment by therealgilles** [comment]
One more step if using (broken) dev screens:

> npm i --save react-native-device-info
> react-native link react-native-device-info
> react-native run-ios

Still getting a FontAwesome error on the Plugin examples dev screen. I saw another thread on this, will update when I have the resolution.

**Comment by therealgilles** [comment]
To update react-native after that, I did:

> npm i -g react-native-git-upgrade
> react-native-git-upgrade
> npm install

That was not sufficient, so I proceeded to do:

> react-native upgrade
(said yes to all prompts, your mileage may vary)
> react-native link

then finally:
> react-native run-ios

and it worked 😄

**Comment by kevinvangelder** [comment]
Hey, sorry you had a bad experience. We're currently focused on getting the next version of our boilerplate ready, but it typically takes us a few days to respond to issues. If you used our default boilerplate without a custom version of RN than you were using a known-working generator. If you added libraries via plugins they should be automatically linked.

What versions of RN did you start with and end up with?

**Comment by kevinvangelder** [comment]
I should have originally said `babel-preset-react-native` rather than `metro`, I didn't have complete information at the time, I just saw something that looked like it could have been related to the issue you were seeing, but probably wasn't.

**Comment by therealgilles** [comment]
I started with the RN version specified in the ignite-red package.json, 0.50.4. I am now using 0.55.3.

**Comment by kevinvangelder** [comment]
We test it every time we issue an update. This is the other issue that I thought might be related: https://github.com/facebook/react-native/issues/18962

**Comment by therealgilles** [comment]
Do you publish what environment you use for such testing?

Here is my babel-preset-react-native version, so not related to 5.0.0 changes:
`    "babel-preset-react-native": "^3.0.2",`

I know I am behind the times on several packages, but I was trying to be conservative when working to resurrect my project from 1+ year back.

**Comment by therealgilles** [comment]
@kevinvangelder: Forgot to say, thank you for trying to help me out 😀
