### ISSUE TITLE
(0 , _validation.verifyTools) is not a function

### ISSUE THREAD

**Issue by yeungyimwang** [infinitered/ignite#126]
Using generator-react-native-ignite@0.3.0

Try to generate container / screen will return below error.

ignite generate container SubMenu1
Generate a new container named SubMenu1
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: (0 , _validation.verifyTools) is not a function
    at ContainerGenerator.initializing (/Users/alfred/.nvm/versions/node/v5.11.0/lib/node_modules/generator-react-native-ignite/container/index.js:38:35)
    at /Users/alfred/.nvm/versions/node/v5.11.0/lib/node_modules/generator-react-native-ignite/node_modules/yeoman-generator/lib/base.js:430:16
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

- [X ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [X ] ignite generated code

**Comment by GantMan** [comment]
![damn](http://i.imgur.com/ktgMeNI.gif)

Looking into it.

**Comment by skellock** [comment]
Dibs on this.  I broke it.  I'll fix it.

**Comment by GantMan** [comment]
![steve](http://i2.kym-cdn.com/photos/images/newsfeed/001/063/207/73b.gif)

**Comment by skellock** [comment]
Haha.

@yeungyimwang : Hang tight, https://github.com/infinitered/ignite/pull/127 is on the way.  Just need thumbs up from @GantMan to make sure we're on the same page.

Sorry about that!

**Comment by GantMan** [comment]
version 0.3.1 released.   Fixed.
