### ISSUE TITLE
Command Failed : yarn add ignite-ir-boilerplate --save

### ISSUE THREAD

**Issue by elmbrent** [infinitered/ignite#1260]
When installing ignite I get the following error.

` igniting app PizzaApp
? Which boilerplate would you like to use? Andross (React Navigation, Redux, & Redux Saga
× ignite-ir-boilerplate-andross was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-ir-boilerplate-andross --dev
error Couldn't find package "ignite-ir-boilerplate-andross" on the "npm" registry.

----------`

![ignite](https://user-images.githubusercontent.com/6248715/39302938-37ad13e2-494c-11e8-98a4-64ea2d19038c.png)

Any ideas what I can do?

```
System
  platform           win32                                                                                              
  arch               x64                                                                                                
  cpu                8 cores                                          Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  directory          C:\Users\BrentF\Documents\Projects\Mercer\Test                                                     

JavaScript
  node               8.11.1       C:\Program Files\nodejs\node.EXE
  npm                5.6.0        C:\Program Files\nodejs\npm.CMD
  yarn               1.6.0        C:\Users\BrentF\AppData\Roaming\npm\yarn.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.1.0        C:\Users\BrentF\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\BrentF\AppData\Local\Android\Sdk


```

**Comment by elmbrent** [comment]
To fix this I went into BASH and went to  : npm config edit
There was some company registery information I had to remove for a private repo. 
See https://docs.npmjs.com/misc/registry

**Comment by minhphung210** [comment]
same issuse

**Comment by kevinvangelder** [comment]
@minhphung210 It's on the registry, as you can see here: http://npmjs.com/ignite-ir-boilerplate-andross

Have you ruled out the possibility of a private repo conflict like @elmbrent mentioned?
