### ISSUE TITLE
[iOS] Tron never logs ComponentWillUnmount when killing app

### ISSUE THREAD

**Issue by Yusiro85** [infinitered/ignite#1266]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

create new project using ignite boilerplate, put console.tron.log in ComponentWillUnmount.
Display the log properly when running on android but never show on iOS.

---
Steps to reproduce

---
`ignite doctor` results:

JavaScript
  node               9.11.0      
  npm                5.8.0       
  yarn               1.6.0      

React Native
  react-native-cli   2.0.1
  app rn version     0.51.0

Ignite
  ignite             2.0.0      

iOS
  xcode              9.3

**Comment by kevinvangelder** [comment]
@Yusiro85 I believe this is an issue with React Native itself. I've never been able to use unmounting functions in the app shutdown case. I think React Native would need to be extended in order to support shutdown callback functions.
