### ISSUE TITLE
Unable to launch Pizza App

### ISSUE THREAD

**Issue by steveharman** [infinitered/ignite#1268]
Hi,

I followed the setup / install instructions (macOS 10.13.4, node 8.9.1) and all went well.  then tried `react-native run-ios --simulator` from the pizza app's project directory and all didn't go well.

*Steps to reproduce*
1) go through the install steps in the readMe
2) `react-native run-ios --simulator` from the pizza app's project directory

*ignite doctor results:*

```ignite doctor
System
  platform           darwin
  arch               x64
  cpu                8 cores              Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  directory          /Users/steveharman

JavaScript
  node               8.9.1        /Users/steveharman/.nvm/versions/node/v8.9.1/bin/node
  npm                5.5.1        /Users/steveharman/.nvm/versions/node/v8.9.1/bin/npm
  yarn               1.3.2        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.1.0        /Users/steveharman/.nvm/versions/node/v8.9.1/bin/ignite

Android
  java               1.8.0_101    /usr/bin/java
  android home       -            /Users/steveharman/Library/Android/sdk

iOS
  xcode              9.2```



*Error displayed in iOS simulator and Metro Bundler*.

```Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /Users/steveharman/PizzaApp

Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `../../../storybook/views` from `/Users/steveharman/PizzaApp/src/views/example/pizza-location/pizza-location.story.tsx`: The module `../../../storybook/views` could not be found from `/Users/steveharman/PizzaApp/src/views/example/pizza-location/pizza-location.story.tsx`. Indeed, none of these files exist:

  * `/Users/steveharman/PizzaApp/src/storybook/views(.native||.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/steveharman/PizzaApp/src/storybook/views/index(.native||.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/steveharman/PizzaApp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (/Users/steveharman/PizzaApp/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/steveharman/PizzaApp/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/steveharman/PizzaApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/steveharman/PizzaApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/steveharman/PizzaApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/steveharman/PizzaApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/steveharman/PizzaApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓░░░░░░░░░░░ 32.0% (377/671), failed.```

**Comment by steveharman** [comment]
Hi Kevin,

No I didn't attempt to enable storybook node, just followed the step by step instructions in the readMe.   

I'll have another try in the morning but if you have any suggestions in the meantime I'll gladly give them a spin.

Cheers,

Steve

**Comment by steveharman** [comment]
Hi Ryan,  

I've updated to the latest (2.1.0 ?) ignite CLI via npm install igmite-cli and now I get something different. 

- I removed the previous PizzaApp project folder entirely
- Followed the installation instructions in the readMe from scratch
- Same environment as when the issue was first raised.
- Issued react-native run-ios
- Error in simulator: [Missing "en.PizzaLocationList.header" translation

The build seems to succeed ok, but...

Thanks,

Steve

![steveharman_ _metro_bundler_ _node_ _launchpackager_command_ _80x24_and_2__steveharman_hackintosh-i7____pizzaapp__zsh__and_iphone_6_-_11_2](https://user-images.githubusercontent.com/12557929/40223608-9214860e-5a7b-11e8-906d-352e09702418.jpg)

**Comment by ryanlntn** [comment]
@steveharman Yeah not the best experience yet for sure.

@kevinvangelder How do you think we should handle that? Should we update the screen template to just use the text prop instead of tx or should we update the screen command to add an entry to en.json?

**Comment by Rambatino** [comment]
Hello, this still appears to be an issue. 
I also fixed an issue here: https://github.com/infinitered/ignite-ir-boilerplate-bowser/pull/66

Have you got a workaround for this particular issue so I can carry on with my day?

**Comment by ryanlntn** [comment]
@Rambatino Are you referring to the storybook issue or the missing translation issue?

**Comment by natguy** [comment]
I know this thread is 5 months old... but I'm seeing the same missing translation error. Was there a solution to this?

**Comment by aditbharadwaj** [comment]
unfortunately the missing translation issue is happening to me same as @steveharman any one got a fix for it ?

**Comment by avh2502** [comment]
Not a fix, but workaround based on @ryanlntn post. 

For now I just changed 
<Text preset="header" tx="pizzaLocationListScreen.header" /> 
to
<Text preset="header" text="pizzaLocationListScreen.header" />

**Comment by Woolei** [comment]
> Not a fix, but workaround based on @ryanlntn post.
> 
> For now I just changed
> Text preset="header" tx="pizzaLocationListScreen.header"
> to
> Text preset="header" text="pizzaLocationListScreen.header"

Hi avh2502, may i know which page you change this? i have the same issue.

**Comment by Boby** [comment]
yes, I am also having the same issue

**Comment by jamonholmgren** [comment]
@Boby Can you try with the latest versions of everything?

**Comment by mayermatheus** [comment]
Hi,
I am also having the same issue for android.

**Comment by jamonholmgren** [comment]
@mayermatheus Can you open a new issue with `ignite doctor` results and a backtrace / screenshot, please?
