### ISSUE TITLE
Please, Add Support for React-Native-Navigation by Wix

### ISSUE THREAD

**Issue by kunaldodiya** [infinitered/ignite#1269]
### Hey there! I am using this, and i love it.

But i have to use default, react-navigation instead of react-native-navigation by wix..

would you please add plugin for react-native-navigation ???

**Comment by GantMan** [comment]
Hi @kunaldodiya -  It's really easy to write a plugin that would swap the two out.  Basically you create a project, swap the two, and take a look at the git diff, and then we code that up!

Would that be something you'd be interested in doing?  Doing a plugin?
https://github.com/infinitered/ignite/blob/master/docs/advanced-guides/creating-plugins.md

**Comment by dzunglht** [comment]
Please help consider this demand/need of this ticket, we do need grow ignite community

**Comment by harrisrobin** [comment]
This would be golden.

**Comment by juddey** [comment]
@harrisrobin, I've done this on my current project, but using v1 of RNN rather than v2 (as I need `handleDeepLinking` which isn't supported on v2 yet).

I just had a quick look at the api between v1 and v2 and while the stack navigators look like they are different, the rest of the insides look fairly similar to whats in v1. 

In order to get v1 going I had to basically pull out the insides of the boilerplate so if you're struggling with that then I might be able to help with some pointers if you like. :+1:

**Comment by harrisrobin** [comment]
@juddey i've actually managed to get most of it working except linking it to my store (mobx-state-tree). Haven't tried yet but that's my next step. I'll give it a try and let you know. If I succeed, i'll try making it into an ignite plugin.

**Comment by skellock** [comment]
@harrisrobin But will you pay yourself $500?

**Comment by harrisrobin** [comment]
@skellock the $500 bounty is still open to anyone that does this because I might not be able to get around making the plugin itself before end of July

**Comment by zakpgrove** [comment]
I also want this—but for Andross.

I was browsing npm and came across this:  [ignite-native-navigation.](https://github.com/Osedea/ignite-native-navigation) However, I'm not sure if this is being actively developed—and it looks like it's only Android at the moment.

If someone could write a plugin for this, I'd also be willing to chip in an additional $150 to the bounty with @harrisrobin.

**Comment by GuillotJessica** [comment]
@zakpgrove it does both but only native code, I'm struggling with redux side of it
thought, it  doesn't take care of 
your-project/node_modules/react-native/React/Views/RCTFont.h

> RCT_EXTERN BOOL RCTHasFontHandlerSet(void); :21
> replacing  RCT_EXTERN BOOL RCTHasFontHandlerSet(); :21 troubkeshooting ios in recent react 

native version on ios build failed : This function declaration is not a prototype
[https://github.com/wix/react-native-navigation/issues/3019](https://github.com/wix/react-native-navigation/issues/3019)

**Comment by juddey** [comment]
@GuillotJessica But that is a `react-native` problem, not a `react-native-navigation` problem. Also, its fixed in RN 0.56.

If you would like help with the redux setup then ping back and we can have a discussion, I have this working in an app.

**Comment by GuillotJessica** [comment]
@juddey my boss figured it out already, unfortunate doc isn't helping much, would be glad to have you're app on a github to share with other your implementation of redux on react-native-navigation v2. we followed https://github.com/eduardomoroni/react-native-boilerplate

**Comment by juddey** [comment]
@GuillotJessica Aah, you're after `v2`, sorry, I was still in `v1` territory.
Seems there are some problems with redux (and HOC's in general) though: https://github.com/wix/react-native-navigation/issues/1642
Sorry can't be more help!

**Comment by juddey** [comment]
Hello, I have written `ignite-react-native-navigation` which will install v2 of `react-native-navigation` by wix into your ignite project. Its made for `bowser`, but should work with other boilerplates too. 

Operation is one way, so if you're just trialling it might be better to spin up a new app with `bowser` to see the full effect.

Alpha software, use at own risk, usual disclaimers etc.

**Comment by juddey** [comment]
I'm going to close this issue off now as there's a plugin available that will make `react-native-navigation` available on your project. @harrisrobin, I don't think there's been a claimer for your bounty, but if you felt inclined could I suggest a small donation to your favorite open source project. :sparkles:
