### ISSUE TITLE
[Request] Support react-native-navigation 

### ISSUE THREAD

**Issue by dzunglht-ibl** [infinitered/ignite#1270]
We love your work, it would be great if your work also supports react-native-navigation coz that navigator is built for high performance, low-latency app and many companies have been utilizing that lib for their own agile projects, various kinds of prototype. We can attract tons of developers from that community also if we are serious about this request !
Ref: https://github.com/wix/react-native-navigation
Best regards

**Comment by kevinvangelder** [comment]
@dzunglht Thanks for the suggestion. Our boilerplates are designed to fit our internal tech stack for client projects and we do not currently use React Native Navigation. If community members would like to fork our boilerplate with React Native Navigation we'd be happy to add it to our list of boilerplates, but unfortunately we don't currently have the bandwidth build and support boilerplates that we aren't/won't be using internally.

Here is an article on how to build a boilerplate for use with Ignite: https://shift.infinite.red/make-your-own-react-native-boilerplate-with-ignite-cli-c45bfa564684
Here is the Andross boilerplate in case you want to fork it: https://github.com/infinitered/ignite-ir-boilerplate-andross
And Bowser boilerplate: https://github.com/infinitered/ignite-ir-boilerplate-bowser

Thanks again!

**Comment by kevinvangelder** [comment]
Also, it could be done via a plugin as suggested by Gant in response to #1269

**Comment by minhphung210** [comment]
I also want this

**Comment by juddey** [comment]
Closing this out. See #1269 for a plugin that will install `react-native-navigation` inro your project.
