### ISSUE TITLE
Regarding android package name and ios bundle id

### ISSUE THREAD

**Issue by SanyasiraoM** [infinitered/ignite#1271]
How to give android package id and ios bundle id while creating the project?

**Comment by kevinvangelder** [comment]
Is it not created automatically? We're using `react-native init` under the hood, so it should just create a bundle id and package name automatically from the name you provide.

**Comment by SanyasiraoM** [comment]
@kevinvangelder Yeah, But we want all bundle id in our control like "com.organization.example" as bundle id and package id

**Comment by SanyasiraoM** [comment]
Dup of https://github.com/infinitered/ignite/issues/365

**Comment by SanyasiraoM** [comment]
Dup of https://github.com/infinitered/ignite/issues/365
