### ISSUE TITLE
[iOS] Unable to archive project if using a custom configuration and using Pods

### ISSUE THREAD

**Issue by gavin-gmlab** [infinitered/ignite#1272]
I've been struggling with this problem for weeks already with my project, and have not been able to resolve this problem. 

I am using Cocoapods due to some of my dependencies requiring it. So I can debug using the default scheme and archive the project using the default 'Release' configuration. I need additional configurations for staging, beta etc, so when I create a new configuration by duplicating the release config, and then try to archive the project using the new Staging config, I get all sorts of errors. Have tried all kinds of suggestions with the header search path, framework search path and others, including adding $(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME) to the framework search paths, but keep getting different kinds of errors, so I'm suspecting I'm digging myself into a deeper and deeper hole.

---
Steps to reproduce

1. Ignite new archiveproject (Note need to modify the ReduxNavigation file to get it to run)
2. Modify the package.json file dependencies to the following:
`
"dependencies": {
    "apisauce": "^0.14.2",
    "format-json": "^1.0.3",
    "identity-obj-proxy": "^3.0.0",
    "lodash": "^4.17.4",
    "prop-types": "^15.6.0",
    "querystringify": "1.0.0",
    "ramda": "^0.25.0",
    "react": "16.2.0",
    "react-native": "0.52.2",
    "react-native-animatable": "^1.2.4",
    "react-native-audio": "4.1.3",
    "react-native-camera": "1.1.2",
    "react-native-code-push": "5.3.2",
    "react-native-config": "^0.11.5",
    "react-native-device-info": "0.21.5",
    "react-native-fabric": "0.5.1",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-i18n": "1.0.0",
    "react-native-image-crop-picker": "0.20.1",
    "react-native-orientation": "3.1.3",
    "react-native-pdf": "3.0.6",
    "react-native-push-notification": "3.0.2",
    "react-native-sensitive-info": "5.1.0",
    "react-native-sound": "0.10.9",
    "react-native-vector-icons": "4.3.0",
    "react-native-video": "2.0.0",
    "react-navigation": "^1.0.0-beta.21",
    "react-navigation-redux-helpers":"1.0.5",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-persist": "^5.4.0",
    "redux-saga": "^0.16.0",
    "reduxsauce": "0.7.0",
    "seamless-immutable": "^7.1.3"
  },
`
3. cd ios && pod init
4. Modify Podfile to the following:
`

platform :ios, '8.0'

target 'archiveproject' do

    rn_path = '../node_modules/react-native'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'BatchedBridge',
      'DevSupport'
    ]
    pod 'CodePush', :path => '../node_modules/react-native-code-push'
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
    pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
    pod 'react-native-camera', path: '../node_modules/react-native-camera'
    pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
    pod 'RNAudio', :path => '../node_modules/react-native-audio'
    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
    pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
    pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'
    pod 'RNSound', :path => '../node_modules/react-native-sound'
    pod 'react-native-video', :path => '../node_modules/react-native-video'
  end  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

`

5. npm install
6. pod install
7. Open project .xcworkspace file in Xcode
8. Create new configuration in project called 'Staging'
9. Change the archive to use the Staging config
10. Run product->archive (note, need to put in your signing key)
Archiving fails with the following errors
`ld: warning: directory not found for option '-L/Users/ldarren/react/archiveproject/archiveproject/ios/Build/Intermediates/ArchiveIntermediates/archiveproject/BuildProductsPath/Staging-iphoneos/CodePush'
ld: warning: directory not found for option '-L/Users/ldarren/react/archiveproject/archiveproject/ios/Build/Intermediates/ArchiveIntermediates/archiveproject/BuildProductsPath/Staging-iphoneos/QBImagePickerController'

...

ld: warning: directory not found for option '-L/Users/ldarren/react/archiveproject/archiveproject/ios/Build/Intermediates/ArchiveIntermediates/archiveproject/BuildProductsPath/Staging-iphoneos/react-native-video'
ld: warning: directory not found for option '-L/Users/ldarren/react/archiveproject/archiveproject/ios/Build/Intermediates/ArchiveIntermediates/archiveproject/BuildProductsPath/Staging-iphoneos/yoga'
`

Same error whether or not I have {$BUILD_DIR}/Release${EFFECTIVE_PLATFORM_NAME} in the various search paths.

Have a sample project available if required.

Tearing what little hair I have out over this....
---
`ignite doctor` results:
System
  platform           darwin                                                                                                   
  arch               x64                                                                                                      
  cpu                4 cores                                              Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz  
  directory          /Users/ldarren/react/archiveproject/archiveproject                                                       

JavaScript
  node               7.9.0        /usr/local/bin/node  
  npm                4.2.0        /usr/local/bin/npm   
  yarn               1.3.2        /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.52.2      

Ignite
  ignite             2.0.0        /usr/local/bin/ignite  

Android
  java               1.8.0_25     /usr/bin/java                        
  android home       -            /Users/ldarren/Library/Android/sdk/  

iOS
  xcode              9.2

**Comment by kevinvangelder** [comment]
Hey Gavin, it looks like your issue is more of a general React Native or even XCode problem than something specific to Ignite. While I wish I were able to help you solve this issue this is not something we do on our projects, so I'm afraid we're not experienced with resolving these types of problems.

I would suggest that you ask for help on the React Discord's React Native channel (that's the official React Native support channel) https://www.reactiflux.com/

If you can't get any help there maybe consider posting it to StackOverflow.com

Thanks for using Ignite, and sorry we can't be of more help.
