### ISSUE TITLE
Not able to install any boilerplate

### ISSUE THREAD

**Issue by shriharip** [infinitered/ignite#1273]
What's going on?

_I run ignite new my-app.
Select Bowser(alpha) or an old boilerplate (typescript) from the list of boilerplates
It adds the Infinite red
Goes to add React Native 0.55, in the typescript boilerplate it is 0.51 and just fails_ 

Steps to reproduce
 _same as above_

`ignite doctor` results:
System
  platform           darwin                                                            
  arch               x64                                                               
  cpu                4 cores       Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz  
  directory          /Users/hari                                                       

JavaScript
  node               8.10.0       /usr/local/bin/node  
  npm                5.8.0        /usr/local/bin/npm   
  yarn               1.6.0        /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.1.0        /usr/local/bin/ignite  

Android
  java               1.8.0_161    /usr/bin/java                    
  android home       -            /Users/hari/Library/Android/sdk  

iOS
  xcode              9.2 

Something related to navigation issue? 1225?

**Comment by kevinvangelder** [comment]
@shriharip What's the error you're seeing?

**Comment by shriharip** [comment]
On add react native (30 secondsish). It just fails and gives message saying 'could not add react native'.

**Comment by kevinvangelder** [comment]
Are you able to `react-native init MyProject`?

**Comment by shriharip** [comment]
hi,

I wanted to take a video of what was happening to better explain but it was working this time :).

I ran the react-native run ios and android commands, and on android it loaded perfectly but on iOS I had the below problem.
![screen shot 2018-05-17 at 23 43 58](https://user-images.githubusercontent.com/3909110/40205501-8df52050-5a2c-11e8-910a-132c95a6c745.png)
