### ISSUE TITLE
Where is the drawer navigation?

### ISSUE THREAD

**Issue by ortix** [infinitered/ignite#1274]
Maybe I'm missing something obvious but on all the renders for this boilerplate framework there is a burger menu visible. However, I can't seem to find it anywhere. Pretty much everything is in place for navigation, but there is literally nothing on the front-end for navigation. Am I missing something here?

**Comment by kevinvangelder** [comment]
The hamburger menu you see is a part of the dev screens, which is currently only an option on the Andross boilerplate.

**Comment by kevinvangelder** [comment]
Side note, if you're looking for how to do a drawer navigation in a Bowser project, check out the documentation here: https://reactnavigation.org/docs/en/drawer-based-navigation.html
