### ISSUE TITLE
api call doesnt reach Redux in release mode

### ISSUE THREAD

**Issue by Chatharaju** [infinitered/ignite#1275]
App run fine on Debug mode, on Release mode, when the first dispatch call is hit, app kinda stays there. I was debugging and found out that on dispatch call, it doesnt even reach the Redux Request. Does anyone has this issue? Please help.

**Comment by kevinvangelder** [comment]
That's a strange one. Can you provide the code and the debugging output?

**Comment by Chatharaju** [comment]
@kevinvangelder , I have modified the api calls with normal fetch calls. It totally works fine now. Still not sure what was the issue. I cannot provide the code because I have modified too much. Thanks for your response tho.
