### ISSUE TITLE
Remove compiled files from source control

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#128]
I'd like to remove the compiled files from this repo (and add them to .gitignore).  There's just too much noise and we've already had someone make edits to them directly.

Who's with me!?!!!!

CHAARGGGEEEEEEE

**Comment by GantMan** [comment]
I like it.   DO IT!

**Comment by skellock** [comment]
And then 30 minutes later he does it anyway.  On a Saturday.   There's no winning with you.

😈

**Comment by GantMan** [comment]
hah, I was pushing version 0.3.1 and the release notes looked so sad.
