### ISSUE TITLE
window10 isnot wroking

### ISSUE THREAD

**Issue by xiaozhanghui** [infinitered/ignite#1281]
window10 isnot wroking. lack some  you choose Modules。for example：react-native-vector-icons

**Comment by kevinvangelder** [comment]
Are you building for Android or React Native Windows? Many modules do not support React Native Windows and some modules do not support Android on Windows. Unfortunately we don't have the bandwidth to fix all of those modules as we work almost exclusively in OSX.

**Comment by jamonholmgren** [comment]
This issue is pretty stale, so I'm closing it. Please let me know if you still need help with it. 🙂
