### ISSUE TITLE
Would a `boilerplatize` command be a good idea?

### ISSUE THREAD

**Issue by adrienthiery** [infinitered/ignite#1282]
Hi there,

This is a feature proposition that I would be ready to implement.

Problem right now is that maintaining the dependencies set in our boilerplate is too hard (I need to create a new project with my boilerplate, upgrade packages, change files if needed and report all changes manually in my `boilerplate/` folder).

I was wondering if it would not be easier to create a command that allows you to transform a working react-native project into the `boilerplate/` folder of an ignite "boilerplate plugin".

That way, I could create a new app with my boilerplate, upgrade dependencies, run my tests to verify that everything works as expected and "re-boilerplatize" it to update my boilerplate.

What do you guys think?
Or am I missing something and there's already a simple way to do that?

**Comment by adrienthiery** [comment]
@GantMan @kevinvangelder Any opinion on this? 🙂

**Comment by GantMan** [comment]
HOLY HELL!  I love it!

**Comment by jqn** [comment]
That would be an awesome feature.

**Comment by bryanstearns** [comment]
Closing this: it's pretty stale, and as of Ignite 6, we don't support custom boilerplates any more; also, the `boilerplate` folder within the ignite project is a working standalone (non-expo) project, so you can work on it in place.
