### ISSUE TITLE
running react-native run-ios does not launch app

### ISSUE THREAD

**Issue by pdad04** [infinitered/ignite#1285]
I'm trying to run the PizzaLocation app but When running `react-native run-ios` it outputs `Build Succeeded` but nothing launches. I've looked around online but haven't had any luck finding anything.

 I get the following output in terminal

```
** BUILD SUCCEEDED **



The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm
	Analyze Modules/RCTUIManager.m
(2 commands with analyzer issues)

Installing build/Build/Products/Debug-iphonesimulator/PizzaApp.app
Launching org.reactjs.native.example.PizzaApp
org.reactjs.native.example.PizzaApp: 42784
```

And then in my other terminal window I see this, but nothing else happens from here.
```
Metro Bundler ready.

Loading dependency graph, done.
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1974/1974), done.
```
---
Steps to reproduce
1. ignite new PizzaApp 
    - Andross selected
    - No i18n
    - No Animation
2. run `react-native run-ios`.

---
`ignite doctor` results:
```
System
  platform           darwin                                                                                                                 
  arch               x64                                                                                                                    
  cpu                4 cores                                                            Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz  
  directory          /Users/xxx/Documents/xxx/React/react-native/PizzaApp                                                       
vvv -----[ DEBUG ]----- vvv
{ Error: not found: yarn
    at getNotFoundError (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/node_modules/which/which.js:13:12)
    at Function.whichSync [as sync] (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/node_modules/which/which.js:131:9)
    at which (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/src/core-extensions/system-extension.js:113:22)
    at Command.module.exports [as run] (/usr/local/lib/node_modules/ignite-cli/src/commands/doctor.js:45:20)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'ENOENT' }
^^^ -----[ DEBUG ]----- ^^^
```
---
`react-native info`
```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 10.2.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.1 => 0.55.1
```

**Comment by pdad04** [comment]
I was able to get this working. It still does not work if I just use `react-native run-ios` but if I run with `react-native run-ios --simulator="iPhone 6s"` or specifying another iPhone type it works.

**Comment by williamdarkocode** [comment]
I did that, but still, nothing opens.

**Comment by pdad04** [comment]
Are you on a Mac? I found also that after I run the command in terminal, If it doesn’t open it was just that the simulator didn’t open automatically, so I had to manually launch the simulator

**Comment by lalithnarayan** [comment]
@pdad04 can you please let me know how to manually launch simulator

**Comment by pdad04** [comment]
> @pdad04 can you please let me know how to manually launch simulator

@lalithnarayan on Mac if you open spotlight search (command-Space Bar) and type 'simulator' then enter, it should open. That is what I had to do initially when my sim was not launching on its own.

**Comment by lalithnarayan** [comment]
@pdad04  thank you

**Comment by EriksonMurrugarra** [comment]
I opened the project in XCODE and it worked.

**Comment by asvenus9999** [comment]
@EriksonMurrugarra Er Me too. I run by terminal, It didn't open in simulator but it worked when i build by xcode. Could you help me?

**Comment by kevinvangelder** [comment]
After you run it from Xcode try running it from the terminal again. Usually the terminal command starts working for me again.

**Comment by jakesyl** [comment]
Having the same issue in xcode 10

**Comment by alainib** [comment]
> Having the same issue in xcode 10

me too. try this maybe, it worked for me before but now the problem appear again

Xode -> file -> project setting 
for « pre user build system » choose « legacy »

**Comment by kaushal9678** [comment]
As @gdowens  mentioned, I followed those steps and it worked for me
**rm -rf ios/build then running react-native run-ios --simulator**

**Comment by jamonholmgren** [comment]
I just ran through the steps outlined above and, other than running into [this issue](https://github.com/facebook/react-native/issues/22863), it worked fine.

<img src="https://user-images.githubusercontent.com/1479215/50676182-dc361e00-0fa7-11e9-8323-ccc8165dd7a2.png" width="200" />

**Comment by Rashmi215** [comment]
> I opened the project in XCODE and it worked.

Can you please elaborate the steps.

**Comment by michlee1337** [comment]
I've tried 
- setting all workspace/ project build and pre-build systems to "legacy"
- deleting the build folder
- running the run-ios with different specified devices

But every time my simulator opens, the app opens to the loading page, then crashes. It never gets pass the loading page.

But if I build the project from XCode everything works fine.

Any advice?

**Comment by jamonholmgren** [comment]
@michlee1337  Related to #1401, maybe? Try the latest Ignite CLI and Ignite Bowser, it might help.

**Comment by prathusingh** [comment]
I was able to resolve it by building it from Xcode itself.
Once build is succeeded, you may need to run (if you get an error)
"sudo launchctl limit maxproc [limit for one user] [total limit]"
Inside Simulator Help, Apple's example values are 2000 for one user and 2500 total.

**Comment by dkniffin** [comment]
Just going to put this here, because it comes up in search results and I've been trying to figure this out for several hours: If you are using [react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen), make sure you do `SplashScreen.hide()` 🤦‍♂

**Comment by stelselim** [comment]
> I've tried
> 
> * setting all workspace/ project build and pre-build systems to "legacy"
> * deleting the build folder
> * running the run-ios with different specified devices
> 
> But every time my simulator opens, the app opens to the loading page, then crashes. It never gets pass the loading page.
> 
> But if I build the project from XCode everything works fine.
> 
> Any advice?

Did you figure out? I am having the same issue. 
it works with Xcode, but not in terminal (react-native run-ios)

**Comment by sam-ong** [comment]
@stelselim Hi did you get your problem fixed? Running into the same issue

**Comment by tonystaark** [comment]
same issue

**Comment by ODINA101** [comment]
same issue

**Comment by stelselim** [comment]
Just quit searching, i jumped into Flutter. Its much more stable and hasslefree. I would recommend

**Comment by ODINA101** [comment]
@stelselim react native is more flexible to design app

**Comment by jamonholmgren** [comment]
This issue seems to be more of a catch-all for many different types of issues. I'm going to lock it for now. If you have a particular issue and especially if you can provide a repro, feel free to file it in the appropriate place:

https://github.com/infinitered/ignite/issues for CLI issues
https://github.com/infinitered/ignite-bowser/issues for issues with Ignite Bowser boilerplate
https://github.com/infinitered/ignite-andross/issues for issues with Ignite Andross boilerplate
