### ISSUE TITLE
Cannot create ignite boilerplate

### ISSUE THREAD

**Issue by mykelaballe** [infinitered/ignite#1286]
What's going on?

running `ignite new MyApp -b ir-next` does not generate the projects files, it only generates an empty folder named `MyApp`

---
Steps to reproduce

simply run the command `ignite new MyApp -b ir-next`, or any `ignite new` commands

---
`ignite doctor` results:

![image](https://user-images.githubusercontent.com/22584900/41324910-f5f7e616-6ee9-11e8-8b61-33f88740331e.png)

Helpful Screenshots:

![image](https://user-images.githubusercontent.com/22584900/41324830-8525e5b4-6ee9-11e8-9c9e-6b492a813af3.png)

![image](https://user-images.githubusercontent.com/22584900/41324882-c9922848-6ee9-11e8-856c-6ce4cc77734f.png)

**Comment by kevinvangelder** [comment]
@mykelaballe We don't have an `ir-next` boilerplate. Were you trying to use `ignite-ir-boilerplate-bowser`? Did you see that in the documentation somewhere? If so, we should update it.

**Comment by mykelaballe** [comment]
`ignite new AppTwo ignite-ir-boilerplate-bowser` still doesnt create projects files, only empty folder

![image](https://user-images.githubusercontent.com/22584900/41325760-9d1aecaa-6eee-11e8-9f3b-fcf29fafa6db.png)

**Comment by mykelaballe** [comment]
@kevinvangelder if you can help me with this that would be greatly appreciated. thanks in advance

**Comment by kevinvangelder** [comment]
Looks like you missed the `-b` flag and selected Andross. Looks like the generator isn't even being run. Can you try adding the `--debug` flag and see what that outputs?

**Comment by mykelaballe** [comment]
@kevinvangelder  thanks for the response. this is the output using your input

![image](https://user-images.githubusercontent.com/22584900/41369086-731b507e-6f76-11e8-9a6a-20a23fd31d3d.png)

**Comment by kevinvangelder** [comment]
You're still using the wrong flag. It's `-b ignite-ir-boilerplate-bowser` or `--boilerplate=ignite-ir-boilerplate-bowser`

**Comment by mykelaballe** [comment]
I actually typed `-b` correctly, but the --debug displays `--b` which is not what I typed. you can try over at your side

**Comment by atulmith** [comment]
I tried 
ignite new MyExpoTry -b ignite-expo
It took me more than one and a half hour and still it is stuck at "Would you like to include redux-persist? Yes"

Please is this a big issue .
Please look into this. 
Don't know how to proceed since the basic ignite boilerplate cannot be generated.

**Comment by mykelaballe** [comment]
yep i got that before. but now it proceeds after the question, but it finishes right away without showing the whole process and it only generates an empty folder. i think the guys from infinite dont even know how to fix this thats why they cant get back to us

**Comment by atulmith** [comment]
Which means that we can no longer use ignite the way it was supposed to.
Making ignite as good as deprecated or is there a way to run ignite under these conditions.
I just need to run a ignite boilerplate for expo .
I have to start working on a project .
Please help.

**Comment by mykelaballe** [comment]
i suggest you create the project without using ignite cli, install the needed dependencies based from ignite's boilerplate package.json files, copy and paste the folders in their boilerplate, then fix the errors 1 by 1. If you're going to wait for their response, you'll be stuck

**Comment by atulmith** [comment]
Thank you for your advice.
Is there a github from where I can get a expo boilerplate project >> ignite.
So I can download the project just as if I made the project using ignite.

**Comment by kevinvangelder** [comment]
Hey guys, sorry you're having a bad experience. We just wrapped up a big effort to put on our annual conference this past week, so none of us were available to assist.

At this point I'm not really sure what's going wrong. I'll try to remember to play with this on my Windows machine sometime this week and see if I'm getting a similar issue or not (last time I tried just a couple months ago everything was working just fine) and post an update.

**Comment by kevinvangelder** [comment]
So I tried tonight on my Windows machine and I'm getting this error: https://github.com/infinitered/ignite-ir-boilerplate-bowser/issues/40

Unfortunately that looks to be different from what you're getting.

**Comment by mykelaballe** [comment]
in my side the `ignite new` command doesnt generate the files, it only creates the folder

**Comment by lvlrSajjad** [comment]
> `ignite new AppTwo ignite-ir-boilerplate-bowser` still doesnt create projects files, only empty folder
> 
> ![image](https://user-images.githubusercontent.com/22584900/41325760-9d1aecaa-6eee-11e8-9f3b-fcf29fafa6db.png)

I used exact settings for creating a project and it created successfully see below screenshot .
![untitled2](https://user-images.githubusercontent.com/42815758/47983205-cb704580-e0e7-11e8-89d7-e27cf5f92b0f.jpg)

maybe it have issue with your npm || node version .
my specs:
```
Windows 10 Pro 64-bit 1803
npm -v : 4.2.0
node -v : 8.12.0
```

**Comment by jamonholmgren** [comment]
This issue is pretty stale, so I'm closing it. Please let me know if you still need help with it. 🙂
