### ISSUE TITLE
App hangs up on splash screen

### ISSUE THREAD

**Issue by punktzrzutu** [infinitered/ignite#1287]
Hi,
What's going on?
Newly created app hangs up on splash screen, also doesn't react to shake gesture.
It happens both in iOS simulator and Android device.
<img width="395" alt="screen shot 2018-06-16 at 13 54 11" src="https://user-images.githubusercontent.com/6332985/41498394-c6102eba-716c-11e8-9b48-9675cc1edc10.png">

---
Steps to reproduce

$ ignite new PizzaApp
  ( Choose `Bowser (alpha)` when prompted )
$ cd PizzaApp
$ ignite generate screen pizza-location-list
  ( Choose `example` domain when prompted. This determines where your new screen will go in the directory structure. )
$ ignite generate component pizza-location
  ( Choose `example` domain when prompted. This determines where your new screen will go in the directory structure. )
$ react-native run-ios

---
`ignite doctor` results:

```
System
  platform           darwin                                                                                              
  arch               x64                                                                                                 
  cpu                8 cores                                        Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz  
  directory          /Users/bartek/code/reactnative/ignite/Pizza3                                                        

JavaScript
  node               8.11.1       /Users/bartek/.nvm/versions/node/v8.11.1/bin/node  
  npm                6.0.0        /Users/bartek/.nvm/versions/node/v8.11.1/bin/npm   
  yarn               1.7.0        /usr/local/bin/yarn                                

React Native
  react-native-cli   2.0.1       
  app rn version     0.55.4      

Ignite
  ignite             2.1.0        /Users/bartek/.nvm/versions/node/v8.11.1/bin/ignite  

Android
  java               1.8.0_92     /usr/bin/java                      
  android home       -            /Users/bartek/Library/Android/sdk  

iOS
  xcode              9.2         
```

**Comment by lustigdev** [comment]
👍

**Comment by lustigdev** [comment]
@punktzrzutu,

Try using this instead: `ignite new PizzaApp -b ir-boilerplate`

Worked for me. Still familiarizing myself with ignite though, but I don't think this is the bowser boilerplate.

**Comment by mrgoodrich** [comment]
+1

**Comment by kevinvangelder** [comment]
Usually if you get stuck on the splash screen there is a redbox error behind it. You can either try resetting the cache on your packager with `npm start --reset-cache` or temporarily comment out the splash screen call in the native code so you can see the redbox error and address it. Since Leon's PR should have improved things here I'm closing this issue, but feel free to reopen if it's still a problem.

**Comment by engineerStuardo** [comment]
Hi @kevinvangelder ... I just have a related issue about this. I created a brand new project with ignite and everything is working fine on local. But when I did expo publish then the iOS app it's stuck in the SplashScreen (Android is working fine). This is my published project: https://expo.dev/@stuardocortez/NewPizzaApp
