### ISSUE TITLE
Ensure generators are in the correct directory.

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#129]
It'd be nice if the generators were to validate the directory before running.

Similarly to how `react-native run-ios` will die with a great error message if your `node_modules` aren't installed.

**Comment by juddey** [comment]
Going to give this a go. 
I've got the "great dying error message": 
`Command `run-ios` unrecognized. Did you mean to run this inside a react-native project?`

When you say "validate the directory", what were you thinking? I can see that there's checks for file overwriting when running the generators. but not sure what else was needed.

**Comment by juddey** [comment]
Just had a thought about this over lunch. Was it that you want the generator to check that the `generate` command was being run in a react-native directory?

**Comment by GantMan** [comment]
basically, people shouldn't generate an app inside of an app, and you shouldn't generate a listview outside of an app.  There should be the minimal check that you're in the right folder 👍
