### ISSUE TITLE
How to use /src instead of /App for ignite generate

### ISSUE THREAD

**Issue by devautor** [infinitered/ignite#1294]
I have to rename `/App` to `/src` to be compatible with AWS Mobile Hub requirements. Now doing `ignite generate component LaunchScreen`  rightfully adds the component to a freshly created `/App` directory. Is there a way to tell ignite to use my `/src` for its job instead?

P.S. ignite i love you

**Comment by kevinvangelder** [comment]
You would probably have to fork the boilerplate to make that change. We support sporking the templates, but I don't think that would allow you to change the location.

**Comment by kevinvangelder** [comment]
I misread your issue the first time. Good news for you, our new Bowser boilerplate (still in alpha, but hopefully only for a couple more weeks) uses a `/src` directory in place of `/App`. There are some other changes (MobX replacing Redux, introduction of TypeScript, etc).

**Comment by kevinvangelder** [comment]
https://github.com/infinitered/ignite-ir-boilerplate-bowser
