### ISSUE TITLE
Can not install redux-persist and other ignite plugins on windows

### ISSUE THREAD

**Issue by 2534290808** [infinitered/ignite#1296]
Can not install redux-persist and other ignite plugins on windows

 "dependencies": {
    "apisauce": "^0.14.2",
    "format-json": "^1.0.3",
    "identity-obj-proxy": "^3.0.0",
    "lodash": "^4.17.4",
    "prop-types": "^15.6.1",
    "querystringify": "1.0.0",
    "ramda": "^0.25.0",
    "react": "16.3.1",
    "react-native": "0.55.1",
    "react-native-config": "^0.10.0",
    "react-navigation": "^1.5.11",
    "react-navigation-redux-helpers": "^1.0.4",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-saga": "^0.16.0",
    "reduxsauce": "0.7.0",
    "seamless-immutable": "^7.1.2"
  }

**Comment by kevinvangelder** [comment]
@2534290808 I see you've pasted some of your terminal output, but not the errors. Could you provide additional information on what's going wrong?

**Comment by lvlrSajjad** [comment]
@2534290808
i've tested this command with the same options you have selected . as below pic.
`ignite new hhhh -b ignite-ir-boilerplate-andross`
![untitled](https://user-images.githubusercontent.com/42815758/47982106-bbeefd80-e0e3-11e8-9fb4-fc262ef2f526.jpg)
my specs:
`Windows 10`
`npm -v : 4.2.0`
`node -v : 8.12.0`

and everything successfully installed as below pic :
![untitled1](https://user-images.githubusercontent.com/42815758/47982107-bc879400-e0e3-11e8-8f0a-51996f3bff8b.jpg)

So what are you dependencies ?
Are you sure that's not a network related problem ? (internet connection interruptions)

**Comment by jamonholmgren** [comment]
This issue is pretty stale, so I'm closing it. Please let me know if you still need help with it. 🙂
