### ISSUE TITLE
Does ignite 2.0 work with EXPO or it's much better working independently?

### ISSUE THREAD

**Issue by inglesuniversal** [infinitered/ignite#1300]
Can you access features and API's that are not typically included on EXPO?

For example: Recording Audio, Access to Microphone, Background Audio Playback on iOS, Speech to Text, WebRTC, etc?

**Comment by skellock** [comment]
For react-native projects (whether it's expo, react-native, or ignite on react-native), to use those features you'll need to find 3rd party libraries (or build them).

**Comment by kevinvangelder** [comment]
To answer the question in your title, Ignite is intended to be used without Expo. It probably could be done but would require some tweaks.

**Comment by kevinvangelder** [comment]
You can take a look at this app which we built with Bowser, it's not the best code I've ever written, but it should give you some basic reference points: https://github.com/infinitered/ChainReactApp2018

For releases, we don't do anything different from the standard React Native release process, so the documentation and any generic RN release tutorials should do the trick.
