### ISSUE TITLE
[Request] How to implement react-navigation v2 in this version of ignite?

### ISSUE THREAD

**Issue by Royovo** [infinitered/ignite#1302]
### Implement react-navigation v2 in ignite

I have been gone through this article
[https://reactnavigation.org/docs/en/redux-integration.html](url)

but I am not sure how to upgrade to v2.

Can anyone help me? Thanks!!!

**Comment by valinaga** [comment]
I completely give up on redux integration. After the latest release of react-navigation I couldn't find any reason to do this. ScreenTracking can be done without redux and so the navigation from non-screen components (i.e. sagas).
Just clean the generated code about ReduxNavigation and all will be well.
Best.

**Comment by morenoh149** [comment]
@valinaga I'm interested in your opinion, have you been able to write apps with react navigation and no redux?

**Comment by valinaga** [comment]
All my complex apps are using Redux as it’s one of the best ways to handle data across components. I’m not advocating against redux. On the contrary. However, lately I couldn’t find any serious reason to store navigation routes in redux. The ignite boilerplate is providing redux react navigation integration off the shelf, which is an issue if you want to use the latest react navigation version. Dropping ReduxNavigation and cleaning up a bit is not a big effort.

**Comment by adrienthiery** [comment]
Hi guys,

If I'm not mistaken, it's not really a bug with ignite or one of the boilerplate, but more of an implementation problem.

@Royovo , you are welcome to come on the community.infinite.red slack and ask for help, but I'll close that issue.

Feel free to re-open if you disagree 🙂
