### ISSUE TITLE
React depreciation warning  ComponentWillMount

### ISSUE THREAD

**Issue by ranvirgorai** [infinitered/ignite#1304]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?
ComponentWillMount and ComponentWillReciveProps depreciation warning  
---
Steps to reproduce
create a new app using ignite 
and run react-native run-ins
---
`ignite doctor` results:

**Comment by kevinvangelder** [comment]
Hey @ranvirgorai, thanks for the report. I believe this warning is coming from one (or more) of our dependencies, including but maybe not limited to `react-navigation`, if memory serves.

**Comment by jamonholmgren** [comment]
This issue is pretty stale, so I'm closing it. Please let me know if you still need help with it. 🙂
