### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by xiaozhanghui** [infinitered/ignite#1307]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?
× ignite-ir-boilerplate-andross was not able to be installed. Is it a valid NPM module?
----------
Command failed: yarn add ignite-ir-boilerplate-andross --dev
error An unexpected error occurred: "https://github.com/react-navigation/react-native-tab-view: connect ETIMEDOUT 13.250.177.223:443".

----------
× ignite-dev-screens was not able to be installed. Is it a valid NPM module?
× ignite-vector-icons was not able to be installed. Is it a valid NPM module?
× ignite-animatable was not able to be installed. Is it a valid NPM module?
---
Steps to reproduce

---
`ignite doctor` results:

**Comment by diego-lipinski-de-castro** [comment]
Same here

**Comment by kevinvangelder** [comment]
This was likely a short-term NPM glitch or a configuration issue. Are you still having this problem?
