### ISSUE TITLE
Need full view image splash screen in android for react-native

### ISSUE THREAD

**Issue by sanjeetnonia** [infinitered/ignite#1311]
I did not get any reference how to create full image view splash screen on android but we did in iOS. Please suggest me.

**Comment by kevinvangelder** [comment]
I would recommend checking out the React Native Splash Screen module documentation: https://github.com/crazycodeboy/react-native-splash-screen

**Comment by chancesmith** [comment]
For those using expo, there are settings to help with android and splash image resizing: https://docs.expo.dev/guides/splash-screens/
