### ISSUE TITLE
Ignite projects failing on Xcode 10

### ISSUE THREAD

**Issue by talal7860** [infinitered/ignite#1317]
What's going on?
After upgrading to Xcode 10 my ignite project failed to build and showing me the error: `Print: Entry, ":CFBundleIdentifier", Does Not Exist`. After looking here and there many issues suggested that I update my react-native version which is 0.55.1. I ran the `react-native-git-upgrade` tool and it created some conflicts and I resolved them which I thought were best.
I then ran the project and it failed with a different error this time on the simulator which said that `_this._registerEvents is undefined`. 

After many attempts to fix it I decided to start a new project with the default settings and with no changes in anything and I was able to reproduce exactly as mentioned above.

Ignite Doctor Results:
```
System
  platform           darwin
  arch               x64
  cpu                4 cores                     Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
  directory          /Users/talal/Dev/KudosApp

JavaScript
  node               8.11.4       /Users/talal/.nvm/versions/node/v8.11.4/bin/node
  npm                5.6.0        /Users/talal/.nvm/versions/node/v8.11.4/bin/npm
  yarn               1.9.4        /Users/talal/.nvm/versions/node/v8.11.4/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.57.1

Ignite
  ignite             2.1.1        /Users/talal/.nvm/versions/node/v8.11.4/bin/ignite

Android
  java               10.0.2       /usr/bin/java
  android home       -            undefined

iOS
  xcode              10.0
```

**Comment by kevinvangelder** [comment]
Only RN 0.57+ is compatible with Xcode 10. This is being discussed over on the Bowser repo. https://github.com/infinitered/ignite-ir-boilerplate-bowser/issues/102

**Comment by talal7860** [comment]
I'm already on 0.57.1.  I've even commented on that thread. Let me know if you want me to close this one

**Comment by talal7860** [comment]
I was able to reproduce this exact issue on react-native by creating a brand new project using `react-native init`. So, I don't think so it has anything to do with ignite. Closing this issue

**Comment by kevinvangelder** [comment]
@talal7860 Did you try the Product > Clean in Xcode? That often will help, even when it's a RN issue.
