### ISSUE TITLE
i18n is now depricated 

### ISSUE THREAD

**Issue by tonmanayo** [infinitered/ignite#1319]
---
What's going on?
i18n: This library is deprecated in favor of react-native-languages
---
Steps to reproduce
ignite init uses the react-native-i18n and should be changed to react-native-languages
---
`ignite doctor` results:

**Comment by kevinvangelder** [comment]
Yep, this has been resolved in Bowser: https://github.com/infinitered/ignite-ir-boilerplate-bowser/pull/105

Andross will probably not be updated as it is no longer supported.

**Comment by tonmanayo** [comment]
ah no that sucks. I really liked the Andross package. Any reason for not supporting it anymore? @kevinvangelder
