### ISSUE TITLE
Are there missing steps to get up and running on a clean mac?

### ISSUE THREAD

**Issue by derekdon** [infinitered/ignite#1320]
I thought this would be straight forward, but I keep hitting setup issues... I'm wondering if steps are missing from the readme. I wanted to try the bowser boilerplate.

For example so far I've had to manually install react-native-typescript-transformer, typescript, babel-plugin-transform-inline-environment-variables, also run react-native link react-native-splash-screen as was getting splash screen package errors... had to open up the build.gradle file in Android Studio so it could download the older sdk and accept the licence... After finally getting the app to launch on my phone I get 500 errors like Unable to resolve module `AccessibilityInfo` etc.

I feel like I must me missing something...

`ignite doctor` results:

```
System
  platform           darwin                                                                                                 
  arch               x64                                                                                                    
  cpu                4 cores                                            Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz  
  directory          /Users/derekdon/projects/colton/TodoMoreFrontend                                                       

JavaScript
  node               8.12.0       /usr/local/bin/node  
  npm                6.4.1        /usr/local/bin/npm   
  yarn               1.10.1       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.55.4      

Ignite
  ignite             2.1.2        /usr/local/bin/ignite  

Android
  java               1.8.0_102    /usr/bin/java               
  android home       -            /usr/local/opt/android-sdk  

iOS
  xcode              7.3.1       
```

**Comment by kevinvangelder** [comment]
Some of those (like Typescript) need to be globally installed, so they should probably be documented (we haven't done a very good job updating the documentation for Bowser). Others (like manually running react-native link) are probably legitimate issues.

**Comment by derekdon** [comment]
@kevinvangelder that's fair enough... to be honest I just picked it up and tried it on a clean mac, just assumed all the dependencies would be auto installed via the project's package.json or highlighted as prerequisites in the readme. No worries.

**Comment by derekdon** [comment]
Forgot to add you may want to expand on Reactotron intergration, as I couldn't get it to work / connect for the Bowser boilerplate... Cheers
