### ISSUE TITLE
exclamation mark with ignite start up or stop

### ISSUE THREAD

**Issue by AizenSousek** [infinitered/ignite#1328]
Hello team:
 there is a bug with ignite node about output content when I start up ignite node or stop it,the console will output so many exclamation mark, more than 20.then I debug application, when I get it:
`ignite = Ignition.start(ServerConfigurationFactory.createConfiguration());`
it will output exclamation mark by console
![85670051-2a3c-44cd-b874-975e57d0dffa](https://user-images.githubusercontent.com/42226823/47203005-88a53280-d3b1-11e8-803b-7f9e51a09e7f.png)
![0f2bdb2e-1580-4b63-b6e2-b2aacd3db3b5](https://user-images.githubusercontent.com/42226823/47203006-893dc900-d3b1-11e8-98ae-8a4e53292c9a.png)

**Comment by bryanstearns** [comment]
Hi @AizenSousek -- I think you might have the wrong project; this Ignite is a CLI for React Native project. Maybe you were thinking of https://ignite.apache.org ?
