### ISSUE TITLE
[Base] - Cleanup Script

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#133]
- [x] Issue does not already exist

Create a script that checks if there are any styles that exist, that are never used.   As a design evolves, there forms a cruft in the codebase, and it would behoove us all if there was a script that helped us identify this cruft for cleaning.   

Unused styles, and perhaps even later identify other unused images/colors etc.

**Comment by skellock** [comment]
As soon as someone uses a interpolated string, this becomes an impossible task unfortunately.
