### ISSUE TITLE
ignite-ir-boilerplate-bowser was not able to be installed. Is it a valid NPM module?

### ISSUE THREAD

**Issue by sayhei** [infinitered/ignite#1342]
## when i init a new project by choose bowser ,the error shows beloew

    igniting app igniteDemo
    ? Which boilerplate would you like to use? Bowser (React Navigation, MobX State Tree, & TypeScript)
    ✔ using the Infinite Red boilerplate v3 (code name 'Bowser')
    ✔ added React Native 0.55.4 in 39.27s
    ✖ ignite-ir-boilerplate-bowser was not able to be installed. Is it a valid NPM module?
    ----------
    Command failed: yarn add ignite-ir-boilerplate-bowser --dev
    error An unexpected error occurred: "https://github.com/infinitered/addon-storyshots: ESOCKETTIMEDOUT".
  
    ----------
    ✔ configured git
    ✔ ignited igniteDemo in 127.01s
    
        Ignite CLI ignited igniteDemo in 127.01s
    
        To get started:
    
          cd igniteDemo
          react-native run-ios
          react-native run-android
          ignite --help
    
        Need additional help? Join our Slack community at http://community.infinite.red.
    
        Now get cooking! 🍽

##  then i  run  'cd igniteDemo & yarn install & react-native run-ios'

    ** BUILD FAILED **
    
    
    The following build commands failed:
    	CompileC /Users/garry/Code/Apps/igniteDemo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/strtod.o /Users/garry/Code/Apps/igniteDemo/node_modules/react-native/third-party/double-conversion-1.1.5/src/strtod.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    
    	CompileC /Users/garry/Code/Apps/igniteDemo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/double-conversion.o /Users/garry/Code/Apps/igniteDemo/node_modules/react-native/third-party/double-conversion-1.1.5/src/double-conversion.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    	CompileC /Users/garry/Code/Apps/igniteDemo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fixed-dtoa.o /Users/garry/Code/Apps/igniteDemo/node_modules/react-native/third-party/double-conversion-1.1.5/src/fixed-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    	CompileC /Users/garry/Code/Apps/igniteDemo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fast-dtoa.o /Users/garry/Code/Apps/igniteDemo/node_modules/react-native/third-party/double-conversion-1.1.5/src/fast-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    	CompileC /Users/garry/Code/Apps/igniteDemo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/cached-powers.o /Users/garry/Code/Apps/igniteDemo/node_modules/react-native/third-party/double-conversion-1.1.5/src/cached-powers.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    	CompileC /Users/garry/Code/Apps/igniteDemo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/bignum.o /Users/garry/Code/Apps/igniteDemo/node_modules/react-native/third-party/double-conversion-1.1.5/src/bignum.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    	CompileC /Users/garry/Code/Apps/igniteDemo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/diy-fp.o /Users/garry/Code/Apps/igniteDemo/node_modules/react-native/third-party/double-conversion-1.1.5/src/diy-fp.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    (7 failures)
    
    Installing build/Build/Products/Debug-iphonesimulator/igniteDemo.app
    An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
    Failed to install the requested application
    The bundle identifier of the application could not be determined.
    Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
    Print: Entry, ":CFBundleIdentifier", Does Not Exist
    
    Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/igniteDemo.app/Info.plist
    Print: Entry, ":CFBundleIdentifier", Does Not Exist
   
## `ignite doctor` results:

    System
      platform           darwin
      arch               x64
      cpu                8 cores                             Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      directory          /Users/garry/Code/Apps/igniteDemo
    
    JavaScript
      node               11.1.0       /Users/garry/.nvm/versions/node/v11.1.0/bin/node
      npm                6.4.1        /Users/garry/.nvm/versions/node/v11.1.0/bin/npm
      yarn               1.12.3       /Users/garry/.nvm/versions/node/v11.1.0/bin/yarn
    
    React Native
      react-native-cli   2.0.1
      app rn version     0.55.4
    
    Ignite
      ignite             2.1.2        /Users/garry/.nvm/versions/node/v11.1.0/bin/ignite
    
    Android
      java               1.8.0_111    /usr/bin/java
      android home       -            /Users/garry/Library/Android/sdk
    
    iOS
      xcode              10.1

**Comment by kevinvangelder** [comment]
The CFBundleIdentifier issue is either a build cache issue or an XCode 10 issue. If you have XCode 10 you'll need to either upgrade RN to 0.57.5+ or downgrade XCode. Otherwise, try opening the project in Xcode and go to Build > Clean and try running the app again.

**Comment by sayhei** [comment]
@kevinvangelder  i follow your sugguestion but the project still can not run

**Comment by sayhei** [comment]
For now ,i can run it after execute 'yarn install & react-native link'

**Comment by kevinvangelder** [comment]
@sayhei This is probably resolved in the latest release of the Bowser boilerplate (though you would have to generate a new project to test). We were trying to use a smaller fork of the Storybook module (because they unnecessarily include a large dependency by default), but it seems that was causing a lot of issues so we've gone back to the original dependency for now.
