### ISSUE TITLE
Error logging on loading boilerplate

### ISSUE THREAD

**Issue by karner** [infinitered/ignite#1344]
Hi guys!

First - Thanks for this awesome project!
This is a request for enhancement: **Please add logging for the exact exception including callstack caused by the line: require(`${modulePath}/boilerplate.js`)  in  boilerplate-install.js (Currently line 62)**

I started working on a custom boilerplate based on ignite-typescript-boilerplate which didn't get an update since RN 0.51.0 and faced some troubles: **"error loading the boilerplate"**.

In the end I found the problem in my boilerplate, but I had to clone the ignite repo and add some logging so I could get to the source of the problem. 

This is the block of code concerned:
```
let pluginModule
  try {
    pluginModule = require(`${modulePath}/boilerplate.js`)
  } catch (e) {
    spinner.fail(`error loading the boilerplate`)
    process.exit(exitCodes.PLUGIN_INVALID)
}
```

I think this could be a major point of failure when having problems in the boilerplate and adding logs here would help big time.

Many thanks & Keep up the good work!
Mathias

**Comment by mlaco** [comment]
Thank you for opening this issue, @karner. We'll address it as time permits.

**Comment by ruddell** [comment]
The same thing would be useful when loading boilerplate `commands`.  If something goes wrong, it silently exits with no error message.

**Comment by mlaco** [comment]
@ruddell I'd be happy to help. Could you be more specific about what boilerplate commands please?

**Comment by ruddell** [comment]
@mlaco Any command that has an error in the javascript.  Here's an example to reproduce what I'm saying:

```
# generate an app using bowser
ignite new BowserExample -b bowser

# try to generate a component without a name, you will see output saying a name is required
ignite g component
   > ignite generate component <name>
   > A name is required.

# add a bad import to the "component" command file in ignite-bowser
echo "const badImport = require('badimport')" >> node_modules/ignite-bowser/commands/component.js

# now generating a component fails silently
ignite g component
   >
```

When I log [`registryItem`](https://github.com/infinitered/ignite/blob/1096c26df9f8dd690da4e5f0479850e7e8279030/src/commands/generate.js#L166) in `generate.js`, this is the output:
```
{ type: 'component',
  pluginName: 'ignite-bowser',
  error: 'command badfile',
  description: null,
  plugin: 
   Plugin {
     name: 'ignite-bowser',
     loadState: 'ok',
     errorState: 'none',
     description: undefined,
     defaults: {},
     directory: '/private/tmp/jh/ignite/BowserExample/node_modules/ignite-bowser',
     errorMessage: null,
     hidden: true,
     commands: [ [Object], [Object], [Object] ],
     extensions: [],
     exception: null,
     ignite: undefined },
  command: 
   { name: 'component',
     description: 'Generates a component, supporting files, and a storybook test.',
     file: '/private/tmp/jh/ignite/BowserExample/node_modules/ignite-bowser/commands/component.js',
     run: null,
     loadState: 'error',
     errorState: 'badfile',
     exception: { Error: Cannot find module 'badimport'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/tmp/jh/ignite/BowserExample/node_modules/ignite-bowser/commands/component.js:43:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' },
     hidden: true,
     alias: undefined } }
```
