### ISSUE TITLE
ignite android initial build failed on Windows 8.1

### ISSUE THREAD

**Issue by absjabed** [infinitered/ignite#1349]
---
What's going on?

My OS; win8.1
Node: v10.14.0
NPM: 6.4.1

I just used command: `ignite new ignitehuh`
then: ` react-native run-android`

![screenshot_1543747935](https://user-images.githubusercontent.com/13753347/49338957-fe104e00-f653-11e8-8b8b-0388508d02b8.png)
---
Steps to reproduce
---
`ignite doctor` results:

C:\Users\absjabed\Desktop\igniteapp\ignitehuh>ignite doctor
System
  platform           win32

  arch               x64

  cpu                8 cores                                         Intel(R) Co
re(TM) i7-7700 CPU @ 3.60GHz
  directory          C:\Users\absjabed\Desktop\igniteapp\ignitehuh

vvv -----[ DEBUG ]----- vvv
{ Error: not found: yarn
    at getNotFoundError (C:\Users\absjabed\AppData\Roaming\npm\node_modules\igni
te-cli\node_modules\gluegun\node_modules\which\which.js:13:12)
    at Function.whichSync [as sync] (C:\Users\absjabed\AppData\Roaming\npm\node_
modules\ignite-cli\node_modules\gluegun\node_modules\which\which.js:131:9)
    at which (C:\Users\absjabed\AppData\Roaming\npm\node_modules\ignite-cli\node
_modules\gluegun\src\core-extensions\system-extension.js:113:22)
    at Command.module.exports [as run] (C:\Users\absjabed\AppData\Roaming\npm\no
de_modules\ignite-cli\src\commands\doctor.js:45:20)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'ENOENT'
 }
^^^ -----[ DEBUG ]----- ^^^

**Comment by mlaco** [comment]
@absjabed do you have [yarn](https://yarnpkg.com/) installed?

**Comment by absjabed** [comment]
no i'm i was using npm

**Comment by jamonholmgren** [comment]
@absjabed Can you try with Yarn instead?

**Comment by ryanlntn** [comment]
This issue is pretty stale, so I'm closing it. Please let me know if you still need help with it. :slightly_smiling_face:
