### ISSUE TITLE
[Opinion] The project feasibility

### ISSUE THREAD

**Issue by kelvin-dev** [infinitered/ignite#1351]
We support your idea of a universal boilerplate for React-native, appreciate your effort but it seems current status quo requires MUCH effort for maintenance and SW dependencies are outdated against latest community releases. Plz help consider another attractive project road map, for example, support react-native navigation so that we can gain more STARs and community interest !
https://github.com/wix/react-native-navigation.git
Tons of thanks

**Comment by kevinvangelder** [comment]
Kelvin, you're right, keeping things up to date is difficult, and thanks for the suggestion. We're currently in the process of evaluating React Native Navigation to decide if we are going to use it in our next boilerplate version. I'm not sure I understand what you mean by "project road map", as far as I'm aware there is no alternative comprehensive boilerplate tool on the same scale as Ignite.

**Comment by jamonholmgren** [comment]
Ignite did fall a little behind early in 2018 but we are putting a lot of energy into it now and you should see a lot of progress. Stay tuned. :)
