### ISSUE TITLE
[Bowser] Creating new application fails to apply patch.

### ISSUE THREAD

**Issue by JoshLWScott** [infinitered/ignite#1352]
---
What's going on?

> Joshs-iMac:Documents josh$ ignite new Application
> 🔥 igniting app Application
> ? Which boilerplate would you like to use? Bowser (React Navigation, MobX State Tree, & Ty
> peScript)
> ✔ using the Infinite Red boilerplate v3 (code name 'Bowser')
> ✔ added React Native 0.57.7 in 79.75s
> ✔ added ignite-ir-boilerplate-bowser in 91.97s
> ⠹ ▸ setting up splash screen: configuringan error occured while installing ignite-ir-boilerplate-bowser boilerplate.
> Error: Command failed: git apply /Users/josh/Documents/Application/Application/patches/splash-screen/splash-screen.patch
> error: patch failed: android/app/src/main/java/com/application/MainActivity.java:2
> error: android/app/src/main/java/com/application/MainActivity.java: patch does not apply
> 
> ⠸ ▸ setting up splash screen: configuring

---
Steps to reproduce

`ignite new application`

---
`ignite doctor` results:

> Joshs-iMac:~ josh$ ignite doctor
> System
>   platform           darwin                                                            
>   arch               x64                                                               
>   cpu                4 cores       Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz  
>   directory          /Users/josh                                                       
> 
> JavaScript
>   node               11.3.0       /usr/local/bin/node  
>   npm                6.4.1        /usr/local/bin/npm   
>   yarn               1.12.3       /usr/local/bin/yarn  
> 
> React Native
>   react-native-cli   2.0.1       
> 
> Ignite
>   ignite             2.1.2        /usr/local/bin/ignite  
> 
> Android
>   java               1.8.0_181    /usr/bin/java  
>   android home       -            undefined      
> 
> iOS
>   xcode              10.1        
> Joshs-iMac:~ josh$

**Comment by jamonholmgren** [comment]
Should be fixed with https://github.com/infinitered/ignite-ir-boilerplate-bowser/pull/130 when that is merged.
