### ISSUE TITLE
failed to add React Native 0.57.7

### ISSUE THREAD

**Issue by jasan-s** [infinitered/ignite#1358]
ignite version `2.1.6` on MacOSX mojave
ran `ignite new testignitereactnative` 
selected `Andross`
got the following error:  `failed to add React Native 0.57.7`
<img width="652" alt="screen shot 2018-12-09 at 3 19 39 am" src="https://user-images.githubusercontent.com/13863953/49696620-4bfbe900-fb61-11e8-8456-263396f01902.png">

**UPDATE:** 
**These all fail** with same error of unable to install the react-native version:
 `ignite new testignitereactnative --react-native-version 0.57.6`
 `ignite new testignitereactnative --react-native-version 0.57.5`
 `ignite new testignitereactnative --react-native-version 0.57.4`
 `ignite new testignitereactnative --react-native-version 0.57.3`

**This worked** , I was able to get it to work if I create a new project using react-native version 0.57.2 
`ignite new testignitereactnative --react-native-version 0.57.2` 

**UPDATE 2**
with the 0.57.2 version  I now get the error: `CFBundleIdentifier error` prob same reason as https://github.com/infinitered/ignite/issues/1329

**Comment by jamonholmgren** [comment]
@jasan-s Can you do `--debug` to get more verbose output? It's working for me. Also, can you update with the results of `ignite doctor`?

**Comment by jasan-s** [comment]
seems to be now working.

**Comment by jamonholmgren** [comment]
Thanks @jasan-s !

**Comment by shouse** [comment]
I switched from 9.X to 8.12.0 and this rectified my issue.  Thanks @vincentferniot

**Comment by noumanDev** [comment]
When i use --debug i found that npx was not installed
`npm install -g npx`
fixed the problem

**Comment by jamonholmgren** [comment]
Cool, thanks @noumanDev !

**Comment by jamonholmgren** [comment]
@noumanDev Would you want to submit a PR where we check if `npx` is installed and provide a nice friendly error message? Something like this one:

https://github.com/infinitered/ignite/blob/b3b7538204aa856ede404afa344146b74a669bca/src/cli/check.js#L16-L22

... but not optional (so remove the line with `optional: true`).
