### ISSUE TITLE
`ignite add` should show where it is adding the plugin from

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1360]
When I run `ignite add`, it searches in several locations, including `~/.ignite/overrides`, NPM, etc.

Once it resolves where it is adding a plugin from, it should display to the user what the source is. 

This will help prevent confusing situations where you forget that you have an override in place and add from the wrong source.

**Comment by bryanstearns** [comment]
Closing - stale, and we no longer support plugins as of Ignite 6
