### ISSUE TITLE
Redux Persist not able to get value on startup

### ISSUE THREAD

**Issue by nyl9488** [infinitered/ignite#1361]
Hi.... the redux persist seem to rehydrate after the screen render... how to delay the screen render wait until rehydrate finished?

**Comment by nyl9488** [comment]
componentDidMount() not able to get redux persist on the first page initial render... it is working on 2nd page afterward...

**Comment by jamonholmgren** [comment]
Hey there @nyl9488, this would be a good question for our community! http://community.infinite.red. Let me know if you find a bug with Ignite, though.

**Comment by DeVoresyah** [comment]
2020 and still get the same issue
