### ISSUE TITLE
ignite new app fails with  ✖ ignite-redux-persist is not available on npm

### ISSUE THREAD

**Issue by nikitph** [infinitered/ignite#1366]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
ignite new apptest fails on 
✖ ignite-redux-persist is not available on npm

---
What's going on?
ignite new app fails on 
✖ ignite-redux-persist is not available on npm
---
Steps to reproduce
ignite new app
---
`ignite doctor` results:
System
  platform           darwin                                                                             
  arch               x64                                                                                
  cpu                4 cores                        Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz  
  directory          /Users/omkareshwar/Downloads                                                       

JavaScript
  node               11.6.0       /usr/local/bin/node  
  npm                6.4.1        /usr/local/bin/npm   
  yarn               1.13.0       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.2.0        /usr/local/bin/ignite  

Android
  java               10.0.2       /usr/bin/java  
  android home       -            undefined      

iOS
  xcode              10.1

**Comment by ruddell** [comment]
I believe this is fixed in https://github.com/infinitered/ignite-andross/pull/239

**Comment by jamonholmgren** [comment]
@nikitph Can you test and report back?

**Comment by FelixButzbach** [comment]
Same problem here. How can I update the andross version?

**Comment by ruddell** [comment]
You can test with:
```
git clone -b fix-ignite-plugin-versions https://github.com/ruddell/ignite-ir-boilerplate.git
ignite NewApp --boilerplate /full/path/to/cloned/repository
```

**Comment by jamonholmgren** [comment]
@FelixButzbach I've merged @ruddell 's fix into Andross and the new version should be available shortly. Thanks so much to @ruddell and everyone for their help!

**Comment by devanshAppiness** [comment]
i reinstalled nodeJs and it worked!!
