### ISSUE TITLE
Error when using Node 8.9.4

### ISSUE THREAD

**Issue by alisarac** [infinitered/ignite#1371]
### Hey there! Ignite CLI seems to be having a problem, eh?

---
What's going on?

I installed ignite-cli and then tried to create a new project. The error below occurred after selecting boilerplate. 

SyntaxError: Invalid regular expression: /(?<|^|\/)@/: Invalid group at detectInstall 
It looks this is a "RegExp Lookbehind Assertion" and it is not supported in node.js version 8.9.4 and previous versions, maybe requires a flag.

[es2018 feature support lists](https://node.green/#ES2018-features--RegExp-Lookbehind-Assertions)

After I updated my node.js version to v10.15.0 everything works as expected.

---
Steps to reproduce

`# ignite new MyApp`

then select any boilerplate

```vvv -----[ DEBUG ]----- vvv
SyntaxError: Invalid regular expression: /(?<!^|\/)@/: Invalid group
    at detectInstall (/Users/alisarac/.config/yarn/global/node_modules/ignite-cli/src/lib/detectInstall.js:39:24)
    at Command.installBoilerplate [as run] (/Users/alisarac/.config/yarn/global/node_modules/ignite-cli/src/commands/boilerplate-install.js:39:25)
    at Runtime.run (/Users/alisarac/.config/yarn/global/node_modules/gluegun/src/domain/runtime.js:159:46)
    at run (/Users/alisarac/.config/yarn/global/node_modules/ignite-cli/src/cli/cli.js:65:29)
    at Object.<anonymous> (/Users/alisarac/.config/yarn/global/node_modules/ignite-cli/bin/ignite:9:31)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
^^^ -----[ DEBUG ]----- ^^^
```
---
`ignite doctor` results:
System
  platform           darwin                                                                                    
  arch               x64                                                                                       
  cpu                4 cores                               Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz  
  directory          /Users/alisarac/projects/mobile/CRM                                                       

JavaScript
  node               8.9.4        /Users/alisarac/.nvm/versions/node/v8.9.4/bin/node  
  npm                5.6.0        /Users/alisarac/.nvm/versions/node/v8.9.4/bin/npm   
  yarn               1.10.1       /Users/alisarac/.nvm/versions/node/v8.9.4/bin/yarn  

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.2.2        /usr/local/bin/ignite  

Android
  java               9.0.4        /usr/bin/java                        
  android home       -            /Users/alisarac/Library/Android/sdk  

iOS
  xcode              10.1

**Comment by jamonholmgren** [comment]
@asharamseervi Can you file a new issue?

**Comment by submetu** [comment]
I am getting the same error on Node 8.9.4

**Comment by hubciorz** [comment]
Same here.

**Comment by Jnlbr** [comment]
Same error on 8.9.0

**Comment by jamonholmgren** [comment]
Thanks for reporting everyone. We are aware of the issue and working on a fix. No need for more "same issue" comments. :-)

**Comment by germanllop** [comment]
> Hello community,
> 
> Me too facing issues with `ignite new HelloWorld`, while I'm having windows10. Please help.
> 
> ```
> PS D:\Playground\ignite\helloworld>yarn -v
> 1.13.0
> PS D:\Playground\ignite\helloworld> node -v
> v10.14.2
> PS D:\Playground\ignite\helloworld> ignite new HelloWorld
> At C:\Users\asharamseervi\AppData\Local\Yarn\bin\ignite.ps1:5 char:13
> +     *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
> +             ~
> Unexpected token ')' in expression or statement.
> At C:\Users\asharamseervi\AppData\Local\Yarn\bin\ignite.ps1:8 char:3
> + if [ -x "$basedir/pwsh" ]; then
> +   ~
> Missing '(' after 'if' in if statement.
> At C:\Users\asharamseervi\AppData\Local\Yarn\bin\ignite.ps1:8 char:5
> + if [ -x "$basedir/pwsh" ]; then
> +     ~
> Missing type name after '['.
> At C:\Users\asharamseervi\AppData\Local\Yarn\bin\ignite.ps1:9 char:20
> + ... edir/pwsh"  "$basedir/../Data/global/node_modules/.bin/ignite.ps1" "$ ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Unexpected token '"$basedir/../Data/global/node_modules/.bin/ignite.ps1"' in expression or statement.
> At C:\Users\asharamseervi\AppData\Local\Yarn\bin\ignite.ps1:9 char:75
> + ... ir/pwsh"  "$basedir/../Data/global/node_modules/.bin/ignite.ps1" "$@"
> +                                                                      ~~~~
> Unexpected token '"$@"' in expression or statement.
>     + CategoryInfo          : ParserError: (:) [], ParseException
>     + FullyQualifiedErrorId : UnexpectedToken
> 
> PS D:\Playground\ignite\helloworld>
> ```

Hi, did you get any fix?

**Comment by stevematdavies** [comment]
> igniting app MyTestApp
> ✔ Which boilerplate would you like to use? · Bowser (React Navigation, MobX State Tree, & TypeScript) - RECOMMENDED
> 🐉 You're using a prerelease version of bowser@beta4.
> ⠋ installing boilerplateError call stack:
> /Users/stdavies/Projects/ReactNative/MyTestApp/node_modules/ignite-bowser/boilerplate.js:233
>     print.error('
>                 ^
> 
> SyntaxError: Invalid or unexpected token


Node 11.7.0
npm 6.7.0
yarn 1.13.0

Mac High sierra
