### ISSUE TITLE
Not going furthe

### ISSUE THREAD

**Issue by charanrajh** [infinitered/ignite#1376]
### Hey there! Ignite CLI seems to be having a problem, eh?

After I installed ignite 2.x, I tried to create an application using ignite new. It asked me about andross or bowser and some other questions too. Then the screen looked like the following. The activity indicator is scrolling on and on. The process went to infinite time. It's not getting completed.
---
What's going on?
Process was going on for hours.
---
Steps to reproduce
N/A
---
`ignite doctor` results:
N/A

![screenshot from 2019-02-07 11-07-50](https://user-images.githubusercontent.com/37415880/52392617-b3360b00-2ac8-11e9-9631-ac9fbcd072ee.png)

**Comment by jamonholmgren** [comment]
Hi @charanrajh, can you try Bowser and see if it works?

**Comment by ryanlntn** [comment]
This issue is pretty stale, so I'm closing it. Please let me know if you still need help with it. :slightly_smiling_face:
