### ISSUE TITLE
launchPackager.command in new window doesn't use same node version

### ISSUE THREAD

**Issue by raedwa01** [infinitered/ignite#1377]
---
What's going on?
When I run on a machine where my default node version is fairly old (4.9.1), I switch to 10.15.0 using nvm.  Problem is, the new terminal that launches the launchPackage.command function, uses my default version of node and fails.  There should be a simple way (maybe using .nvmrc) you check to see if the version of node in the "popup" is the same as the original version and change it.
---
Steps to reproduce

1. set nvm default to older version of node (like 4.9.1)
2. call nvm use to use a newer version of node (like 10.15.0)
3. launch your app using react-native run-ios 
4. observe error in popup that the version of node is not correct.

`ignite doctor` results:

```
ystem
  platform           darwin
  arch               x64
  cpu                12 cores                                       Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  directory          /Users/redwards/Projects/Playground/PizzaApp

JavaScript
  node               10.15.0      /Users/redwards/.nvm/versions/node/v10.15.0/bin/node
  npm                6.4.1        /Users/redwards/.nvm/versions/node/v10.15.0/bin/npm
  yarn               1.13.0       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.57.8

Ignite
  ignite             2.2.2           /usr/local/bin/ignite
  boilerplate        ignite-bowser

Android
  java               11.0.2       /usr/bin/java
  android home       -            undefined

iOS
  xcode              10.1
```

**Comment by jamonholmgren** [comment]
Hey @raedwa01 , thanks for reporting! My recommendation is to run the packager yourself using `react-native start` in a command window that already has nvm set properly.

I'm going to close this issue as it is not Ignite-specific. You may want to open an issue over at https://github.com/react-native-community/react-native-cli.
