### ISSUE TITLE
Ignite new broken 

### ISSUE THREAD

**Issue by raooll** [infinitered/ignite#1378]
---
What's going on?
- Create new app with ignite new fails.
```
Command failed: yarn add ignite-bowser --dev 
 ~ ❯❯❯ node -v
v10.14.1
~ ❯❯❯ react-native -v
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
~ ❯❯❯ ignite -v
2.2.2
```

<img width="1267" alt="screen shot 2019-02-13 at 1 57 25 am" src="https://user-images.githubusercontent.com/3482371/52666072-3de89100-2f33-11e9-8a3e-145d25dba1d5.png">

---

Steps to reproduce 
- yarn global add ignite-cli
- ignite new test_app

---

`ignite doctor` results:

<img width="1119" alt="screen shot 2019-02-13 at 1 59 58 am" src="https://user-images.githubusercontent.com/3482371/52666101-4fca3400-2f33-11e9-9d61-97bb58ddfa65.png">

**Comment by jamonholmgren** [comment]
Hi @raooll , it looks like you have the command line tools installed but not Xcode. Can you confirm this?

**Comment by raooll** [comment]
@jamonholmgren yes I have only installed command line tool. Is the missing xcode causing the problem ?

**Comment by raooll** [comment]
Hey @jamonholmgren, I installed the latest xcode and I still get the same error.

**Comment by diegotejadav** [comment]
I also had a problem like this, a solution was to open Xcode and set the Command Line Tools:
![screen shot 2019-02-13 at 8 18 52 am](https://user-images.githubusercontent.com/3412546/52714575-3394ba00-2f68-11e9-9bf5-d6af9345d4a2.png)
Restart the machine and try it again.

**Comment by raooll** [comment]
Hello @diegotejadav, the command line tools is set in my Xcode, still the same error.
<img width="781" alt="screen shot 2019-02-14 at 8 22 10 am" src="https://user-images.githubusercontent.com/3482371/52759716-f0ebe400-3032-11e9-8204-40fdbe99209c.png">

Restarting the machine did not help either.

**Comment by jamonholmgren** [comment]
Weird. I'm not entirely sure what's going on there. My machine is completing the steps properly. Are you getting a new error or the same one?

**Comment by jamonholmgren** [comment]
@raooll Can you try creating a new react native bare app, like this:

```
react-native init Test
```

and then add ignite-bowser, like this:

```
yarn add ignite-bowser --dev
```


Does that complete?

**Comment by raooll** [comment]
@jamonholmgren tried the above, it worked without any problem.

<img width="1278" alt="screen shot 2019-02-15 at 7 57 31 am" src="https://user-images.githubusercontent.com/3482371/52830617-8355bb80-30f7-11e9-9e61-3ebf3c712b9a.png">

**Comment by ethicalvats** [comment]
Same issue

ignite new is failing!

**Comment by ethicalvats** [comment]
After the app was generated running it via iOS sim 12.1 it shows this screen

![simulator screen shot - iphone x - 2019-03-08 at 13 58 31](https://user-images.githubusercontent.com/1000068/54016883-5c485200-41aa-11e9-9e66-ce827c45854b.png)

I am trying the fixes as per https://stackoverflow.com/questions/52262084/syntax-error-support-for-the-experimental-syntax-decorators-legacy-isnt-cur

will let you know

**Comment by jamonholmgren** [comment]
I think the comments under this issue are mostly unrelated, so I'm going to close and lock this, and if you can create new issues we'll take a look!
