### ISSUE TITLE
Ignite new app does not work

### ISSUE THREAD

**Issue by Zetsukaze** [infinitered/ignite#1380]
What's going on?

Attempting to ignite a new app gives the following error:
![image](https://user-images.githubusercontent.com/1698993/52765128-d54a0300-305d-11e9-946d-52776171127d.png)

I have tried using npm to install the boilerplate for bowser using the command below, and it throws a template not found error.
`ignite boilerplate-install ignite-bowser MyAwesomeApp --debug --npm`

---
Steps to reproduce

ignite new MyApp

---
`ignite doctor` results:
```
System
  platform           win32
  arch               x64
  cpu                8 cores      Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  directory          D:\

JavaScript
  node               11.9.0       C:\Program Files\nodejs\node.EXE
  npm                6.5.0        C:\Program Files\nodejs\npm.CMD
  yarn               1.13.0       C:\Users\user\AppData\Roaming\npm\yarn.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.2.2        C:\Users\user\AppData\Roaming\npm\ignite.CMD

Android
  java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
  android home       -            undefined
```

**Comment by diegotejadav** [comment]
This seems to be same problem as https://github.com/infinitered/ignite/issues/1378, unfortunately stills open

**Comment by Zetsukaze** [comment]
Is there a previous CLI version that we could use to bypass this issue?

**Comment by jamonholmgren** [comment]
Hey @Zetsukaze, I'm having trouble recreating this issue.

![image](https://user-images.githubusercontent.com/1479215/52800668-1f68bf80-3031-11e9-8061-6a12d222e7cf.png)

Can you try this?

```
npm uninstall -g ignite-cli
yarn global add ignite-cli
```

and try again?

**Comment by jamonholmgren** [comment]
@diegotejadav I think the other issue is unrelated, but I could be wrong.

**Comment by raooll** [comment]
Hello @jamonholmgren,

Tried the above, did not work.

<img width="573" alt="screen shot 2019-02-14 at 9 58 25 pm" src="https://user-images.githubusercontent.com/3482371/52801405-c8e89900-30a3-11e9-86cb-04223e3ded38.png">

<img width="573" alt="screen shot 2019-02-14 at 9 58 39 pm" src="https://user-images.githubusercontent.com/3482371/52801417-cdad4d00-30a3-11e9-93b0-2dc8881d05d9.png">

**Comment by Zetsukaze** [comment]
@jamonholmgren Yeah, I tried that as well, did not work. I did a yarn install of ignite first, then npm. Both had issues.

**Comment by raooll** [comment]
@jamonholmgren can we use an older version of ignite ?

**Comment by jamonholmgren** [comment]
@raooll Can you use the newest alphas and see if those work?

```
yarn global add ignite-cli@3.0.0-alpha.5
ignite new MyApp -b ignite-bowser@4.0.0-alpha.3
```

**Comment by pawitk** [comment]
I have been facing the same issues.  Tried using an older version of ignite-cli to no success.  

Using the exact solution suggested by @jamonholmgren works.  Thanks!

**Comment by LINXUEZHAO** [comment]
ignite: command not found

**Comment by Christop406** [comment]
@jamonholmgren is this still the recommended way to fix this issue? I was able to get it to work using your commands but not using the recommended installation instructions on the README

**Comment by jamonholmgren** [comment]
@Christop406 Sorry about the delay, I didn't see your comment until now. How is it with the latest Bowser?

**Comment by joeyfigaro** [comment]
@jamonholmgren 

OS: OS X 10.15 Beta (catalina)
package manager: yarn

FWIW

```
~/Repositories via ⬢ v12.10.0
❯ ignite new groupic -b ignite-bowser@4.0.0-alpha.3
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app groupic
✔ using the Infinite Red boilerplate v3 (code name 'Bowser')
✔ added React Native 0.58.6 in 0.98s
an error occured while installing ignite-bowser boilerplate.
Error: ENOENT: no such file or directory, chdir '/Users/joeyfigaro/Repositories/groupic' -> 'groupic'
    at process.chdir (internal/process/main_thread_only.js:29:13)
    at Object.<anonymous> (/Users/joeyfigaro/.config/yarn/global/node_modules/ignite-cli/build/extensions/reactNative.js:126:33)
    at step (/Users/joeyfigaro/.config/yarn/global/node_modules/ignite-cli/build/extensions/reactNative.js:32:23)
    at Object.next (/Users/joeyfigaro/.config/yarn/global/node_modules/ignite-cli/build/extensions/reactNative.js:13:53)
    at fulfilled (/Users/joeyfigaro/.config/yarn/global/node_modules/ignite-cli/build/extensions/reactNative.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chdir',
  path: '/Users/joeyfigaro/Repositories/groupic',
  dest: 'groupic'
}
error installing boilerplate
```

**Comment by joeyfigaro** [comment]
@jamonholmgren changing node version from `12.10.0` to `11.10.0` got me past the previous failure involving `process.chdir`

**Comment by joeyfigaro** [comment]
@jamonholmgren @Christop406 

Was able to generate my first ignite bowser project using node `11.10.0` and refusing detox tests. Including detox causes another failure.

**Comment by tudorpintea** [comment]
> @jamonholmgren @Christop406
> 
> Was able to generate my first ignite bowser project using node `11.10.0` and refusing detox tests. Including detox causes another failure.

i downgraded to node 11.10.0 but i have the same failure :(
Does anyone have another solution?
Thanks !

**Comment by jamonholmgren** [comment]
If you run ignite with `--debug` you'll see more verbose logs which might give you more info to debug this.

**Comment by giorgosart** [comment]
Hey I am facing the same issue here, it seems like the issue is with the `react-native` version that is being installed with `ignite-andross`

![image](https://user-images.githubusercontent.com/1062121/72172370-e2d24f00-33cc-11ea-89a9-8fde46f1bb8c.png)

`error Cannot use React Native CLI to initialize project with version lower than 0.60.0.`
