### ISSUE TITLE
Cannot read property '0' of undefined error installing boilerplate

### ISSUE THREAD

**Issue by imtechnofreak** [infinitered/ignite#1393]
I am having a wired issue when generating a new project using ignite-cli. I followed the same steps in the docs.

yarn global add ignite-cli
ignite new MyNewAppName
<img width="1033" alt="Screenshot 1940-12-22 at 6 32 14 PM" src="https://user-images.githubusercontent.com/10373433/54280848-74f7a400-45be-11e9-80f8-daf821a8b65c.png">

node  v11.11.0
react-native-cli: 2.0.1

**Comment by danielmain** [comment]
Same here, my versions are:

- yarn: 1.13.0
- node: v11.10.0
- zsh/tmux environment on mac os 10.14

**Comment by danielmain** [comment]
With Node version 10.15.3 I get the same problem

**Comment by imtechnofreak** [comment]
@danielmain i think the cli is broken

**Comment by k2s** [comment]
downgrade to 2.2.2 works

**Comment by DusanDimitric** [comment]
Same issue here.

```
ignite -v    -> 3.0.0-alpha.5
node -v      -> v11.11.0
npm -v       -> 6.9.0
ignite       -v -> 3.0.0-alpha.5
react-native -v -> react-native-cli: 2.0.1
```

**Comment by pspelman** [comment]
I'm also having this issue
node -v   ->   v.11.6.0
npm -v   ->   6.9.0
ignite -v   ->   3.0.0-alpha.5
react-native -v   ->   react-native-cli: 2.0.1

**Comment by ruddell** [comment]
It looks like the `alpha.5` was released as the latest version on NPM:

`npm info ignite-cli` shows:

```
dist-tags:
latest: 3.0.0-alpha.5  next: 3.0.0-alpha.3
```
I didn't test but I'm guessing that's the reason for the recent issues.

**Comment by return-main** [comment]
So after trying every alpha versions of ignite-cli 3.0.0 on Windows 10 and Manjaro, i generated my project using:
`ignite new MyApp -b bowser`

**Comment by pspelman** [comment]
> So after trying every alpha versions of ignite-cli 3.0.0 on Windows 10 and Manjaro, i generated my project using:
> `ignite new MyApp -b bowser`
@return-main Your solution worked on Mac with 3.0.0-alpha.5 !!

I used:
`ignite new myIgniteApp -b andross`

**Comment by jamonholmgren** [comment]
Apologies for the problems, folks! We're looking into it.

**Comment by jamonholmgren** [comment]
I think fixing the dist-tags problem fixed the issue. Please report if it's still a problem.

**Comment by DusanDimitric** [comment]
I still get **3.0.0-alpha.5** when I `npm i -g ignite-cli`

```
$ ignite -v
3.0.0-alpha.5
```

You didn't make a release or?

**Comment by jamonholmgren** [comment]
@DusanDimitric You might have run into another erroneous deployment. Because of our non-standard alpha publishing process right now, it's sometimes easy to screw up the order of commands. I'm trying to be better about it though! 😅

**Comment by DusanDimitric** [comment]
Thanks for the effort. When can we expect 3.0.0 ?

**Comment by jamonholmgren** [comment]
@DusanDimitric I feel like we're ready to publish now, to be honest. Just need a few more people to test it and make sure it works.

**Comment by ruddell** [comment]
I already prepared the Ignite JHipster boilerplate for v3 ([commit](https://github.com/ruddell/ignite-jhipster/commit/20d1ca0c1689dc4ad71f45e86fd9decc984a50da)) and it works as expected.  Thanks for keeping it simple 👍

**Comment by jamonholmgren** [comment]
I had intended to reach out about ignite-jhipster and forgot. 🤦‍♂️ Glad it's good to go!

**Comment by jamonholmgren** [comment]
I'm going to go ahead and release this morning.

**Comment by jamonholmgren** [comment]
I didn't get a chance to do it. Maybe tomorrow?
