### ISSUE TITLE
Ignite command fails and i can't even run the command ignite doctor.

### ISSUE THREAD

**Issue by san4u** [infinitered/ignite#1394]
This is the error which is showing when i try to run the ignite command.
Error: Error: Couldn't load command component -- needs a "run" property with a function.
  
```
  - command-loader.js:53 Object.loadCommandFromFile
    [global]/[gluegun]/build/loaders/command-loader.js:53:15
  
  - plugin-loader.js:40 
    [global]/[gluegun]/build/loaders/plugin-loader.js:40:105
  
  - Array.map
  
  - plugin-loader.js:40 Object.loadPluginFromDirectory
    [global]/[gluegun]/build/loaders/plugin-loader.js:40:59
  
  - runtime.js:172 Runtime.addPlugin
    [global]/[gluegun]/build/runtime/runtime.js:172:38
  
  - runtime.js:201 
    [global]/[gluegun]/build/runtime/runtime.js:201:58
  
  - Array.map
  
  - runtime.js:201 Runtime.addPlugins
    [global]/[gluegun]/build/runtime/runtime.js:201:24
  
  - builder.js:139 
    [global]/[gluegun]/build/domain/builder.js:139:61
  
  - Array.forEach
  

/Users/macbookpro/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Error: Couldn't load command component -- needs a "run" property with a function.
    at Object.loadCommandFromFile (/Users/macbookpro/.config/yarn/global/node_modules/gluegun/build/loaders/command-loader.js:53:15)
    at /Users/macbookpro/.config/yarn/global/node_modules/gluegun/build/loaders/plugin-loader.js:40:105
    at Array.map (<anonymous>)
    at Object.loadPluginFromDirectory (/Users/macbookpro/.config/yarn/global/node_modules/gluegun/build/loaders/plugin-loader.js:40:59)
    at Runtime.addPlugin (/Users/macbookpro/.config/yarn/global/node_modules/gluegun/build/runtime/runtime.js:172:38)
    at /Users/macbookpro/.config/yarn/global/node_modules/gluegun/build/runtime/runtime.js:201:58
    at Array.map (<anonymous>)
    at Runtime.addPlugins (/Users/macbookpro/.config/yarn/global/node_modules/gluegun/build/runtime/runtime.js:201:24)
    at /Users/macbookpro/.config/yarn/global/node_modules/gluegun/build/domain/builder.js:139:61
    at Array.forEach (<anonymous>)
```

**Comment by jamonholmgren** [comment]
Hey @san4u , thanks for your patience -- I'm a bit behind on Ignite issues. Can you try this?

```
yarn global add ignite-cli@3.0.0-alpha.5
ignite --version
ignite doctor
```

**Comment by timkuilman** [comment]
Same issue here running `3.0.0-beta.3`

`ignite --help` and `ignite doctor` commands fail.

**Comment by brenohq** [comment]
same error here on ```3.0.0-beta.4```

**Comment by superp** [comment]
I have the same problem with 3.0.0-alpha.5.
Both _ignite --help_ and _ignite doctor_ fail.
What can I do to fix this?

**Comment by kevinvangelder** [comment]
If you're having trouble with the betas, try installing 2.2.4

**Comment by ryanlntn** [comment]
This error indicates that you're using an ignite plugin which has commands that have not yet been updated to support ignite 3. What ignite plugins are you using?

**Comment by superp** [comment]
> If you're having trouble with the betas, try installing 2.2.4

I have tried to upgrade version to 3.1.1 but it had no success.
So, I've downgraded to  2.2.4 and it works now.

**Comment by jamonholmgren** [comment]
@superp Can you file a new issue with the problems you're having with 3.1.1? We'd like to fix them.

**Comment by superp** [comment]
> @superp Can you file a new issue with the problems you're having with 3.1.1? We'd like to fix them.

@jamonholmgren At 3.1.1 version the problem was the same. No one ignite's generators and ignite doctor commands didn't work. The error was the same as at the top of this issue.

**Comment by magpielover** [comment]
same for me for version 3.1.1

**Comment by ryanlntn** [comment]
@superp @magpielover Can you post the ignite plugins you're using? One or more of them has commands that need to be updated to support Ignite 3 which changed made breaking changes to the command interface.

**Comment by James-deWitt** [comment]
This seemed to occur for me on ignite-cli@3.1.1 after adding `ignite-maps` and running `npm install`

Downgrading to 2.2.4 has broken the bowser generators however...

**Comment by ryanlntn** [comment]
Thanks @James-deWitt! We'll get an update out for `ignite-maps` to support Ignite 3.

**Comment by ryanlntn** [comment]
@James-deWitt https://github.com/infinitered/ignite-maps/releases/tag/v1.0.0 is now compatible with Ignite 3.

**Comment by James-deWitt** [comment]
Awesome! I can confirm that my ignite-cli@3.1.1 doesn't throw up anymore!

**Comment by john1jan** [comment]
i also have same with ignite 3.1.3

**Comment by jamonholmgren** [comment]
Can you file a new issue with more information? Thanks!
