### ISSUE TITLE
Error ignite generate

### ISSUE THREAD

**Issue by drakonkat** [infinitered/ignite#1395]
I created a new Bowser boilerplate project, then tried to list all possible "generate" component calling the service "ignite generate". But this command always throw and error.

---
Launching the command ignite generate i will get this error: 

      ` Error: Error with "ignite generate" in ignite-bowser
        please report issue at https://github.com/infinitered/ignite

  - generate.js:11 Command.run
    [BeerWall]/[ignite-bowser]/commands/generate/generate.js:11:11

  - run.js:108 Runtime.<anonymous>
    [global]/[gluegun]/build/runtime/run.js:108:58

  - run.js:43 step
    [global]/[gluegun]/build/runtime/run.js:43:23

  - run.js:24 Object.next
    [global]/[gluegun]/build/runtime/run.js:24:53

  - run.js:15 fulfilled
    [global]/[gluegun]/build/runtime/run.js:15:58

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7

  - loader.js:744 Function.Module.runMain
    internal/modules/cjs/loader.js:744:11

  - node.js:285 startup
    internal/bootstrap/node.js:285:19

  - node.js:739 bootstrapNodeJSCore
    internal/bootstrap/node.js:739:3

C:\Users\<user>\AppData\Local\Yarn\Data\global\node_modules\gluegun\build\index.js:13
    throw up;
    `
---
Steps to reproduce:
create a new project on windows "new" and then tried this

---
`ignite doctor` results:

System
  platform           win32                                                           

  arch               x64                                                             
  cpu                8 cores                                                          AMD FX(tm)-8320 Eight-Core Processor           
  directory          C:\Users\<user>\Documents\VisualStudioCode\ReactNative\BeerWall  

JavaScript
  node               10.13.0      C:\Program Files\nodejs\node.EXE
  npm                6.4.1        C:\Program Files\nodejs\npm.CMD
  yarn               1.12.3       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1     
  app rn version     0.58.6    

Ignite
  ignite             3.0.0-alpha.5   C:\Users\<user>\AppData\Local\Yarn\bin\ignite.CMD
  boilerplate        ignite-bowser  

Android
  java               -            C:\Program Files\Java\jdk1.8.0_191\bin\java.EXE
  android home       -            C:\Android\android-sdk

**Comment by juanmiret** [comment]
I'm having the same issue 😟

**Comment by jamonholmgren** [comment]
Thanks for reporting! I'll look into this.

**Comment by jamonholmgren** [comment]
Can you try with `ignite-bowser@4.0.0-alpha.4`?

```
yarn global add ignite-cli@3.0.0-alpha.3
ignite new MyApp -b ignite-bowser@4.0.0-alpha.4
```

And see if that helps?

I was able to do the above and `ignite g` lists out the generators and they all work.

**Comment by drakonkat** [comment]
I have tried with @4.0.0-alpha.4 and it works, i suppose is a bowser version problem.
Thanks for the help
