### ISSUE TITLE
Ignite new App Andross & Bowser not working properly

### ISSUE THREAD

**Issue by yesIamFaded** [infinitered/ignite#1397]
---
**What's going on?**

When I build an App with Ignite and Boilerplate Andross it gets build and it also works but I dont have a Developer Screen even when manually running: ignite add dev-screens 

When I build an App with Ignite and Bowser it throws the error many people seem to have : 
x ignite-bowser was not able to be installed. Is it a valid NPM module? 

so both of them are not working correctly for me.
even tried the alpha to run Bowser but didnt get any further.

---

**Steps to reproduce**

I am on Windows 7. Just run ignite new Appname and then choose Andross click yes on dev-screen, or run it with Bowser.

---

**`ignite doctor` results:**

```
System
  platform           win32                 

  arch               x64                   
  cpu                6 cores                Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  directory         **************  

JavaScript
  node               10.13.0      C:\Program Files\nodejs\node.EXE
  npm                6.4.1        C:\Program Files\nodejs\npm.CMD
  yarn               1.15.2       C:\Program Files (x86)\Yarn\bin\yarn.CMD

React Native
  react-native-cli   2.0.1     

Ignite
  ignite             3.0.0-alpha.5   C:\Users\*******\AppData\Local\Yarn\bin\ignite.CMD

Android
  java               -            C:\ProgramData\Oracle\Java\javapath\java.EXE
  android home       -            c:\Users\*********\AppData\Local\Android\Sdk
```

**Comment by levi-beers** [comment]
I have this same problem on MacOS 10.14.3. Dev screens will not add even though they are in packages.json.

**Comment by TiangeHu2806** [comment]
I have same issue, got error like "Support for the experimental syntax 'decorators-legacy' isn't currently enabled".

**Comment by jamonholmgren** [comment]
@TiangeHu2806 Try the answer listed here for your problem: https://github.com/infinitered/ignite/issues/1385#issuecomment-467967378

**Comment by jamonholmgren** [comment]
@yesIamFaded @levi-beers I haven't updated [ignite-dev-screens](https://github.com/infinitered/ignite-dev-screens) yet to be compatible with the latest alphas. I would recommend not installing ignite-dev-screens until I do. I'm not sure on an ETA.

**Comment by yesIamFaded** [comment]
@jamonholmgren  Same error with this Alpha aswell: 
x ignite-bowser was not able to be installed. Is it a valid NPM module?

**Comment by jamonholmgren** [comment]
@yesIamFaded Can you try with the latest versions of each?

**Comment by ryanlntn** [comment]
https://github.com/infinitered/ignite-dev-screens has been updated to be compatible with Ignite 3. This should now be fixed with Ignite 3 and the latest Andross boilerplate.
