### ISSUE TITLE
New screen isn't reflected in navigationStore

### ISSUE THREAD

**Issue by AnonymousSB** [infinitered/ignite#1399]
What's going on?

Using the Bowser template with Mobx, anytime I add any new screens and update the navigators, I have to tear down the entire app and restart. How can I clear the Mobx navigationStore?

---
Steps to reproduce

use ignite generate screen to add a screen, observe with Reactotron that navigationStore doesn't reflect new screen.

---
`ignite doctor` results:

System
  platform           darwin                                                                                                                
  arch               x64                                                                                                                   
  cpu                4 cores                                                           Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz                                                     

JavaScript
  node               10.12.0      /usr/local/bin/node  
  npm                6.4.1        /usr/local/bin/npm   
  yarn               1.10.1       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.57.7      

Ignite
  ignite             2.1.2        /usr/local/bin/ignite  

Android
  java               11.0.2       /usr/bin/java                             

iOS
  xcode              10.2

**Comment by kevinvangelder** [comment]
If you're using Reactotron, you should be able to just press Cmd+. and enter `resetStore`, then reload your app. If you're not using Reactotron, the easiest way to reset your store is to comment out the loading from async storage in `setupRootStore.ts`.
