### ISSUE TITLE
Doctor, doctor what version of the boilerplate was used for the new project?

### ISSUE THREAD

**Issue by budda** [infinitered/ignite#1406]
Can ```ignite doctor``` show the version of the boilerplate that was used at app creation time?

**Comment by jamonholmgren** [comment]
Good question. That information might be in `ignite/ignite.json` -- we could incorporate that into `ignite doctor` at some point?

**Comment by ryanlntn** [comment]
This is now included in Ignite 3

**Comment by ruddell** [comment]
The boilerplate name is available from `ignite doctor`, but the version is not.
