### ISSUE TITLE
ignite fresh install, reactotorn cannot resolve ../../../App/redux ; case sensitive

### ISSUE THREAD

**Issue by us-22** [infinitered/ignite#1410]
Hey 

---
What's going on?
ignite fresh install with Androos boilerplate template not working. after running `react-native run-ios` i got `Unable to resolve module '../../../App/redux' from 'path/to/my/work/directory/node_modules/reactotorn-redux/dist/index.js'`

However, App/redux do exists but with capital R in redux. So it's App/Redux not App/redux.

---
Steps to reproduce
Create a fresh install 

---
`ignite doctor` results:
System
  platform           darwin

  arch               x64
  cpu                8 cores                      Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz

JavaScript
  node               8.11.3       /usr/local/bin/node
  npm                6.1.0        /usr/local/bin/npm
  yarn               1.7.0        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.59.3

Ignite
  ignite             3.0.0-beta.4     /usr/local/bin/ignite
  boilerplate        ignite-andross

Android
  java               10.0.1       /usr/bin/java
  android home       -            undefined

iOS
  xcode              10.1

**Comment by ryanlntn** [comment]
Hey @us-22 I'm unable to recreate with a freshly ignited app. Given that the error seems to be coming from reactotron-redux it's possible that it was already fixed there. I'm going to close this for now but feel free to reopen if you're continuing to have this issue.

**Comment by us-22** [comment]
@ryanlntn After investigation. This issue happens only if you choose not to install ignite development screens with Androos template. Otherwise, it's working just fine.
