### ISSUE TITLE
newly generated Andross project has broken saga

### ISSUE THREAD

**Issue by atingsonpetcircle** [infinitered/ignite#1413]
What's going on?

the example saga StartupSagas.startup is not being invoked

version: 3.0.0-beta.4

Steps to reproduce
1. installed the latest ignite v2 version
2. ignite new SampleProjectWhatever
3. react-native run-ios

the following code was not invoked, even the `Hello, Test.`

```
import { put, select } from 'redux-saga/effects'
import GithubActions, { GithubSelectors } from '../Redux/GithubRedux'
import { is } from 'ramda'

// exported to make available for tests
export const selectAvatar = GithubSelectors.selectAvatar

// process STARTUP actions
export function * startup (action) {
  console.tron.log('Hello, Test.')
  if (__DEV__ && console.tron) {
    // straight-up string logging
    console.tron.log('Hello, I\'m an example of how to log via Reactotron.')

    // logging an object for better clarity
    console.tron.log({
      message: 'pass objects for better logging',
      someGeneratorFunction: selectAvatar
    })

    // fully customized!
    const subObject = { a: 1, b: [1, 2, 3], c: true }
    subObject.circularDependency = subObject // osnap!
    console.tron.display({
      name: '🔥 IGNITE 🔥',
      preview: 'You should totally expand this',
      value: {
        '💃': 'Welcome to the future!',
        subObject,
        someInlineFunction: () => true,
        someGeneratorFunction: startup,
        someNormalFunction: selectAvatar
      }
    })
  }
  const avatar = yield select(selectAvatar)
  // only get if we don't have it yet
  if (!is(String, avatar)) {
    yield put(GithubActions.userRequest('GantMan'))
  }
}
```

screenshot of reactotron

![Screen Shot 2019-05-03 at 9 27 13 AM](https://user-images.githubusercontent.com/41312737/57116123-b10ce100-6d85-11e9-9ac7-1d8548efbfc9.png)

**Comment by jamonholmgren** [comment]
Hi @atingsonpetcircle, thanks for the issue. We don't use Andross regularly at IR anymore, so we're relying on the community for pull requests. I'll mark this as a bug and if you get a chance to submit a PR (or someone else) I'd be happy to review and publish a new version. 🙏

**Comment by atingsonpetcircle** [comment]
@jamonholmgren 

Thanks for response. as much as i wanted to fix this, I am fairly new to react-native, so gotta wait for response from others....

does that mean we should migrate to mobx instead?

**Comment by jamonholmgren** [comment]
@atingsonpetcircle I do recommend moving to mobx-state-tree, but only if you're early in your app development. Bowser is our current stack and we really like it. If you've already invested a lot of time into an Andross app, I'd recommend sticking with that, as it's a fine way to build an app.

**Comment by atingsonpetcircle** [comment]
@jamonholmgren tbh we have a code built on Andross template already. I think for short term fix on the bug is desirable

**Comment by atingsonpetcircle** [comment]
fix according to https://github.com/infinitered/ignite-andross/issues/267

change the code to this of `CreateStore.js`
```
// kick off root saga
  let sagasManager = sagaMiddleware.run(rootSaga)
```

update reactotron-redux-saga to at least `3.0.0`

**Comment by ryanlntn** [comment]
Closing this here as this is Andross specific and already being tracked with https://github.com/infinitered/ignite-andross/issues/267
