### ISSUE TITLE
Not able to create a new plugin

### ISSUE THREAD

**Issue by GuillaumeHemmen** [infinitered/ignite#1418]
Hello, I recently updated my ignite-cli and tried to create a new plugin with no success. See details below:

---
What's going on?

I tried to create a new plugin following the official documentation: https://github.com/infinitered/ignite/blob/master/docs/advanced-guides/creating-plugins.md

The command `ignite plugin new radio-buttons` throw the following error:

```
➜  ignite plugin new radio-buttons
ignite plugin new ignite-foo

Plugin name is required
```

---
Steps to reproduce

- Try to create a new plugin using the command `ignite plugin new <plugin name>`.

---
`ignite doctor` results:

```
➜  test ignite doctor
System
  platform           darwin

  arch               x64
  cpu                12 cores                        Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  directory          /Users/ghemmen/Downloads/test

JavaScript
  node               10.15.3      /Users/ghemmen/.nvm/versions/node/v10.15.3/bin/node
  npm                6.9.0        /Users/ghemmen/.nvm/versions/node/v10.15.3/bin/npm
  yarn               1.16.0       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite-cli         3.1.1        /Users/ghemmen/.nvm/versions/node/v10.15.3/bin/ignite

Android
  java               1.8.0_172    /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java
  android home       -            /Users/ghemmen/Library/Android/sdk

iOS
  xcode              10.2.1
```

**Comment by GuillaumeHemmen** [comment]
I would also add that I get the same issue on a freshly install mac VM.

**Comment by ruddell** [comment]
https://github.com/infinitered/ignite/blob/3da165cd48950f0e46d6d7e9a02c7218be945b8e/src/commands/plugin.ts#L51

It looks like `parameters.second` contains the plugin name instead of `parameters.third`
```
{ plugin: 'ignite',
  command: 'plugin',
  array: [ 'new', 'TestPlugin' ],
  options: {},
  raw: 
   [ '/Users/ruddell/.nvm/versions/node/v8.14.0/bin/node',
     '/Users/ruddell/.nvm/versions/node/v8.14.0/bin/ignite',
     'plugin',
     'new',
     'TestPlugin' ],
  argv: 
   [ '/Users/ruddell/.nvm/versions/node/v8.14.0/bin/node',
     '/Users/ruddell/.nvm/versions/node/v8.14.0/bin/ignite',
     'plugin',
     'new',
     'TestPlugin' ],
  first: 'new',
  second: 'TestPlugin',
  third: undefined,
  string: 'new TestPlugin' }
```

**Comment by GuillaumeHemmen** [comment]
@ruddell is there anything I could do on my end to solve the problem or is it related to ignite-cli itself?

**Comment by jamonholmgren** [comment]
Yeah, our plugin generator is currently borked, I believe. We need to fix this.

**Comment by GuillaumeHemmen** [comment]
I raised a PR. I don’t know if it’s the correct approach though
