### ISSUE TITLE
Routing Improved?

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#142]
I've heard great things, and after looking it seems kinda cool.  Even if it has the word `flux` in the name :)

https://github.com/aksonov/react-native-router-flux

If we want to swap to this it wouldn't be hard, but it would change our generator process.

opinions plz @skellock @kevinvangelder

**Comment by skellock** [comment]
We switched to this last week in our current project.  I highly recommend it.

**Comment by GantMan** [comment]
O wow.  k

**Comment by skellock** [comment]
We have really strange navigation requirements (non standard) and this lib is holding up great so far. I'll give you the tour tomorrow.

**Comment by kevinvangelder** [comment]
Unfortunately we have to put this task on hold for now because RNRF has decided to skip RN 0.27. https://github.com/aksonov/react-native-router-flux/issues/786

**Comment by aksonov** [comment]
@kevinvangelder I've removed dependency from RN0.26.

**Comment by GantMan** [comment]
released in 1.3.1!
