### ISSUE TITLE
issue: ignite new app created with 'src' as package name.  Package name should be Project name.

### ISSUE THREAD

**Issue by nileshprajapati007444** [infinitered/ignite#1422]
If I create new app with 'ignite new 'SampleApp'. It is created, but Main Folder 'SampleApp' contain  sub folder as 'src', and package name is also created with 'src'. It is the issue.

Before around 1 month, It was working fine with ignite.

Can anyone give me solution of it ? 

Thanks in advance.

**Comment by ruddell** [comment]
What version of `ignite` are you using?  If you aren't using v3, I recommend upgrading

**Comment by nileshprajapati007444** [comment]
@ruddell yes. it is working fine with upgraded version. Thank you.
