### ISSUE TITLE
Ignite command not found

### ISSUE THREAD

**Issue by AtharvaAbsolute** [infinitered/ignite#1424]
![ignite](https://user-images.githubusercontent.com/19706447/58323555-f337b880-7e41-11e9-8d75-1fde3a1eb2c4.png)

Can you tell me exactly what path to update in .bashrc for this to work?

**Comment by jamonholmgren** [comment]
Hey @AtharvaAbsolute , try:

```
export PATH="$PATH:$(yarn global bin)"
```
