### ISSUE TITLE
List Boilerplate in Ignite CLI

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1426]
Hi, I was wondering what it takes to get my boilerplate code get listed in ignite.

I have written React Native boiler plate code that is based on [Atomic design](http://bradfrost.com/blog/post/atomic-web-design/) and uses redux, react-navigation, storybook, redux saga.
[Boiler plate code](http://github.com/alexakasanjeev/arcn)

_Originally posted by @alexakasanjeev in https://github.com/infinitered/ignite/issues/11#issuecomment-496511531_

**Comment by jamonholmgren** [comment]
@alexakasanjeev If you want to convert it to an Ignite boilerplate, I'd be happy to evaluate it for possible inclusion in Ignite CLI.

**Comment by alexakasanjeev** [comment]
@jamonholmgren **Can you give me more context about what it means to convert into Ignite boilerplate**, 

I would really like to get my boilerplate get enlisted.
About my boilerplate code: [arcn](http://github.com/alexakasanjeev/arcn)

1. It uses [Atomic design](http://bradfrost.com/blog/post/atomic-web-design/)
2. It uses redux 
3. It uses [redux-saga](https://redux-saga.js.org/) for async operation handle
4. It uses [react-navigation](https://reactnavigation.org/)
5. It has [storybook](https://storybook.js.org) implementation

**Comment by jamonholmgren** [comment]
Hey @alexakasanjeev! Check out this guide, and if you run into problems, please let me know here!

https://github.com/infinitered/ignite/blob/master/docs/advanced-guides/creating-boilerplates.md

**Comment by bryanstearns** [comment]
Closing this - Ignite 6 no longer supports custom boilerplates.
