### ISSUE TITLE
Can't create generator

### ISSUE THREAD

**Issue by nirre7** [infinitered/ignite#1427]
What's going on?
Can't create generator

`ignite plugin new test`

crashes and gives me this:

```
 Error: template not found /Users/niso/.config/yarn/global/node_modules/ignite-cli/build/templates/plugin/gitignore
  
  - template-tools.js:71 Object.<anonymous>
    [global]/[gluegun]/build/toolbox/template-tools.js:71:27
  
  - template-tools.js:32 step
    [global]/[gluegun]/build/toolbox/template-tools.js:32:23
  
  - template-tools.js:13 Object.next
    [global]/[gluegun]/build/toolbox/template-tools.js:13:53
  
  - template-tools.js:7 
    [global]/[gluegun]/build/toolbox/template-tools.js:7:71
  
  - new Promise
  
  - template-tools.js:3 __awaiter
    [global]/[gluegun]/build/toolbox/template-tools.js:3:12
  
  - template-tools.js:51 Object.generate
    [global]/[gluegun]/build/toolbox/template-tools.js:51:16
  
  - copy-batch.js:84 Object.<anonymous>
    [global]/[ignite-cli]/build/extensions/ignite/copy-batch.js:84:55
  
  - copy-batch.js:32 step
    [global]/[ignite-cli]/build/extensions/ignite/copy-batch.js:32:23
  
  - copy-batch.js:13 Object.next
    [global]/[ignite-cli]/build/extensions/ignite/copy-batch.js:13:53
  

/Users/niso/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^

```
Checked /Users/niso/.config/yarn/global/node_modules/ignite-cli/build/ and there is no template folder there.

I'm I misunderstanding how to create a generator?? :(

---
Steps to reproduce

1. Create new ignite project 
2. cd newProject
3. ignite plugin new testgenerator
4. no, yes,yes
5. *crash*

---
`ignite doctor` results:
```
System
  platform           darwin                                                         
                                          
  arch               x64                                                            
  cpu                12 cores              Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz 
  directory          /Users/niso/dev/lab                                            

JavaScript
  node               10.15.1      /Users/niso/.nvm/versions/node/v10.15.1/bin/node 
  npm                6.4.1        /Users/niso/.nvm/versions/node/v10.15.1/bin/npm  
  yarn               1.16.0       /Users/niso/.yarn/bin/yarn                       

React Native
  react-native-cli   2.0.1      

Ignite
  ignite-cli         3.1.3        /Users/niso/.config/yarn/global/node_modules/.bin/ignite 

Android
  java               1.8.0_201    /usr/bin/java                   
  android home       -            /Users/niso/Library/Android/sdk 

iOS
  xcode              10.2.1     

```

**Comment by ruddell** [comment]
This is a bug in the packaging.  Using a local clone of the ignite repo works, like you said the `templates` folder is not released to npm.  It looks related to https://github.com/infinitered/gluegun/pull/537

**Comment by nirre7** [comment]
Yepp that seems to be the issue 👍

**Comment by myfoostrong** [comment]
To save others time, the implied fix above is...
`git clone https://github.com/infinitered/ignite
mv ignite/src/templates ~/.config/yarn/global/node_modules/ignite-cli/build/
rm -rf ignite`

Went from the above error, to...
`✔ Is this an app boilerplate plugin? · No
✔ Will your plugin have a generator command? (e.g. ignite generate <mygenerator> <name>) · Yes

Creating new plugin: ignite-test
✔︎ ignite-test/.gitignore
✔︎ ignite-test/plugin.js
✔︎ ignite-test/ignite.json
✔︎ ignite-test/package.json
✔︎ ignite-test/README.md
✔︎ ignite-test/test/add.js
✔︎ ignite-test/test/remove.js
✔︎ ignite-test/test/interface.js
✔︎ ignite-test/commands/generate/ignite-test.js
✔︎ ignite-test/templates/ignite-test.js.ejs`

**Comment by jamonholmgren** [comment]
I'll try to get this fixed soon!

**Comment by jamonholmgren** [comment]
I have a PR in the works ... once we release that, it'll fix this issue.
