### ISSUE TITLE
React Native Web with Ignite

### ISSUE THREAD

**Issue by tomacotuna** [infinitered/ignite#1428]
Hey, so this is just a thought I had this couple of days while working on bootstrapping a side project using Ignite boilerplate, and saw the new development in react-native-web and the fact that Microsoft and expo are pushing it.

Was wondering if the amazing team behind Ignite have any plans on creating a Ignite starter with react-native-web as an option.

**Comment by kevinvangelder** [comment]
We are not, however Ignite boilerplates are fairly straightforward to create, so if it's something you would use feel free to give it a go. We'll even link to it in our documentation so other people can find it.

**Comment by jamonholmgren** [comment]
I'd love to eventually do this, but it's a nontrivial amount of work and we'd have to have a client need it to justify the time. Want to hire us to do it? :-)

**Comment by mwarger** [comment]
I have used the most recent ignite CLI to create an expo project and attempted to run it on the web.  I had to play a bit of whack-a-mole with the config (and Platform checks) just to get it to run.  I have not yet put in the time to see if this is correct, but I thought I'd share my progress so far (running `yarn web` and letting expo webpack do its thing shows the landing page, but the logo doesn't work...).  I imagine something like these changes could be moved into the boilerplate generator once they're confirmed correct and working.

https://github.com/mwarger/ignite-expo-web-repro/commit/3caf1c6cb1dfa985a55fe9b51077befc54d2c3ad

cc @jamonholmgren 

Is it still the case that this hasn't been a focus for the CLI?  Is the newest ignite CLI rewrite tested with web support?

**Comment by jamonholmgren** [comment]
@mwarger You're correct that we haven't focused on web support. We don't run into needing web very often, and when we do, it's often something pretty custom. So if we do run into a situation where we need React Native Web, we'll definitely take a look at adapting Ignite for that.

In the meantime, if someone wanted to take a stab at it, I'd entertain PRs!

**Comment by waltermvp** [comment]
this is BY FAR my favorite react-native boilerplate to work with. Amazing work.  Supporting react-native-web would be a huge addition. I would love to help if anyone leads the way (I'm not really experienced with tooling)

**Comment by waltermvp** [comment]
@jamonholmgren I would like to start a bounty, id be happy to pitch in.

**Comment by jamonholmgren** [comment]
@waltermvp Thanks so much for the kind words! Have you tried out @markrickert's new version that works with Expo's web support yet?
