### ISSUE TITLE
[CLI] Host key verification failed. Could not read from remote repository.

### ISSUE THREAD

**Issue by ghsamm** [infinitered/ignite#144]
I got an error when installing ignite for the first time. I then tried to fix it by running 'npm i'. I get the following message:
E:\REPORT\app2>npm i                                                               
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --ge
t remote.origin.url                                                                
npm WARN addRemoteGit                                                              
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:207:12)    
npm WARN addRemoteGit     at emitTwo (events.js:106:13)                            
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)                   
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)         
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_pr
ocess.js:215:5)                                                                    
npm WARN addRemoteGit  git+ssh://git@github.com/GantMan/react-native-push-notificat
ion.git resetting remote C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes\git-
ssh-git-github-com-GantMan-react-native-push-notification-git-93738d0d because of e
rror: { Error: Command failed: git -c core.longpaths=true config --get remote.origi
n.url                                                                              
npm WARN addRemoteGit                                                              
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:207:12)    
npm WARN addRemoteGit     at emitTwo (events.js:106:13)                            
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)                   
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)         
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_pr
ocess.js:215:5)                                                                    
npm WARN addRemoteGit   killed: false,                                             
npm WARN addRemoteGit   code: 1,                                                   
npm WARN addRemoteGit   signal: null,                                              
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin
.url' }                                                                            
npm ERR! git clone --template=C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes
\_templates --mirror ssh://git@github.com/GantMan/react-native-push-notification.gi
t C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-Gant
Man-react-native-push-notification-git-93738d0d: Cloning into bare repository 'C:\U
sers\sameh\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-GantMan-re
act-native-push-notification-git-93738d0d'...                                      
npm ERR! git clone --template=C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes
\_templates --mirror ssh://git@github.com/GantMan/react-native-push-notification.gi
t C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-Gant
Man-react-native-push-notification-git-93738d0d: Host key verification failed.     
npm ERR! git clone --template=C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes
\_templates --mirror ssh://git@github.com/GantMan/react-native-push-notification.gi
t C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-Gant
Man-react-native-push-notification-git-93738d0d: fatal: Could not read from remote 
repository.                                                                        
npm ERR! git clone --template=C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes
\_templates --mirror ssh://git@github.com/GantMan/react-native-push-notification.gi
t C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-Gant
Man-react-native-push-notification-git-93738d0d:                                   
npm ERR! git clone --template=C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes
\_templates --mirror ssh://git@github.com/GantMan/react-native-push-notification.gi
t C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-Gant
Man-react-native-push-notification-git-93738d0d: Please make sure you have the corr
ect access rights                                                                  
npm ERR! git clone --template=C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes
\_templates --mirror ssh://git@github.com/GantMan/react-native-push-notification.gi
t C:\Users\sameh\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-github-com-Gant
Man-react-native-push-notification-git-93738d0d: and the repository exists.        
npm ERR! Windows_NT 6.3.9600                                                       
npm ERR! argv "E:\\node\\bin\\node.exe" "E:\\node\\bin\\node_modules\\npm\\bin\\npm
-cli.js" "i"                                                                       
npm ERR! node v6.2.1                                                               
npm ERR! npm  v3.9.3                                                               
npm ERR! code 128                                                                  
                                                                                   
npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\sameh
\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@github.com/Ga
ntMan/react-native-push-notification.git C:\Users\sameh\AppData\Roaming\npm-cache\_
git-remotes\git-ssh-git-github-com-GantMan-react-native-push-notification-git-93738
d0d                                                                                
npm ERR! Cloning into bare repository 'C:\Users\sameh\AppData\Roaming\npm-cache\_gi
t-remotes\git-ssh-git-github-com-GantMan-react-native-push-notification-git-93738d0
d'...                                                                              
npm ERR! Host key verification failed.                                             
npm ERR! fatal: Could not read from remote repository.                             
npm ERR!                                                                           
npm ERR! Please make sure you have the correct access rights                       
npm ERR! and the repository exists.                                                
npm ERR!                                                                           
npm ERR!                                                                           
npm ERR! If you need help, you may report this error at:                           
npm ERR!     <https://github.com/npm/npm/issues>                                   
                                                                                   
npm ERR! Please include the following file with any support request:               
npm ERR!     E:\REPORT\app2\npm-debug.log                                          
                                                                                   

Before posting the issue, I made sure everything is up to date: git, node, npm, react-native

**Comment by GantMan** [comment]
thanks @ghsamm - It looks like it might be something with your config, but I think the lib that's giving you trouble has been updated, so I no-longer need to point at my branch.

So probably this line is your problem: https://github.com/infinitered/ignite/blob/master/ignite-base/package.json#L30

I'll fix this today.   Could you try switching your package.json to point at npm and let me know if that fixes your problem?

**Comment by ghsamm** [comment]
@GantMan Problem solved. I changed the version to 1.0.7 which the latest version and it worked. Thank you.

**Comment by ghsamm** [comment]
@GantMan Now that I think about it, I probably shouldn't have closed it until you fix it for others to find it. I'm still a noob when it comes to open source. Anyway, it's your choice now.

**Comment by GantMan** [comment]
all good :)   handled via https://github.com/infinitered/ignite/pull/147
