### ISSUE TITLE
There is option to install Javascript and MobX ? (without typescript)

### ISSUE THREAD

**Issue by idanlevi1** [infinitered/ignite#1440]
I don't use typescript, i saw one option for mobx with typescript and another for javascript with redux
how i combine mobx and javascript?

**Comment by kevinvangelder** [comment]
Hey, sorry no one responded to you. Unfortunately there is no mix-and-match as we use boilerplates to generate your app and that would require maintaining boilerplates with every possible combination of the various options. There may be a community boilerplate that more closely resembles the options that you are looking for.
