### ISSUE TITLE
Sample splash screen for the example app

### ISSUE THREAD

**Issue by ahmed1490** [infinitered/ignite#145]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.  Then feel free to delete this comment and above.
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

**Comment by GantMan** [comment]
Hi @ahmed1490 - We are considering writing a lib that allows splash screens to be easy.  Whenever we do add that, we'll integrate it here :)

**Comment by ahmed1490** [comment]
Great work @GantMan !! :)

**Comment by ahmed1490** [comment]
relevant: https://github.com/mehcode/rn-splash-screen

**Comment by mykelaballe** [comment]
is the Splash Screen up already?

more power to Ignite :+1:

**Comment by skellock** [comment]
Perhaps someone can wrap the library @ahmed1490 mentioned into a plugin.
