### ISSUE TITLE
Clear Redux Store 

### ISSUE THREAD

**Issue by rahultatvasoft** [infinitered/ignite#1451]
@ruddell how to clear store or flush all data stored in Props?

**Comment by ruddell** [comment]
To clear the store, you can increase the `reducerVersion` in [`redux-persist.js`](https://github.com/ruddell/ignite-jhipster/blob/fcd53047a10d4ce86dc2fb8d71e0fd9c377c0e51/boilerplate/app/config/redux-persist.js#L7) of an Ignite JHipster app (or `ReduxPersist.js` for an Andross app).  Or if you only want to reset only a single key, you can add a reset method [like this example](https://github.com/ruddell/IgniteJhipsterSampleApp/blob/2d8cea5f3ebdbef358de4f3a9ab873997787e8be/App/Redux/ChatRedux.js#L27-L29)

**Comment by ruddell** [comment]
Closing since this looks solved, feel free to add more comments
