### ISSUE TITLE
React native I18 is deprecated

### ISSUE THREAD

**Issue by Lucas-Geitner** [infinitered/ignite#1452]
**What's going on?**

https://github.com/AlexanderZaytsev/react-native-i18n
This library is deprecated in favor of react-native-localize. You can use react-native-localize with I18n-js (but also with react-intl, react-i18next, etc. The choice is yours!)

I was trying to update react-native i18n for react-native 60, and I find out the package was depreciated !

It's would be good to choose a new one !

Thanks !

**Comment by jamonholmgren** [comment]
@Lucas-Geitner Can you post the results of `ignite doctor` please?

**Comment by Lucas-Geitner** [comment]
I eject and remove all the ignite related stuff sorry @jamonholmgren ! 

Still thanks for the great job !

**Comment by jamonholmgren** [comment]
Good luck with the project! <3
