### ISSUE TITLE
Why use plugins? (Question)

### ISSUE THREAD

**Issue by gazedash** [infinitered/ignite#1463]
### it is unclear from the docs or plugins README why would I use a plugin and do I need to?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

---
Steps to reproduce

---
`ignite doctor` results:

**Comment by kevinvangelder** [comment]
Plugins were part of our answer to complaints we got about Ignite Andross, which included everything by default. In the end they didn't get maintained and most of them are now defunct, but we've found a better balance and only include the things that a majority of users want.

**Comment by gazedash** [comment]
@kevinvangelder Thanks for clarification. But currently what is the use case to use a plugin? 
The only use case I can see if I want to make a boilerplate on top of ignite, but even then I don't see why I would use plugins

**Comment by kevinvangelder** [comment]
We used them for adding and configuring optional packages like `react-native-maps`, which had substantial setup steps that had to be exactly followed in order to get it working and it worked way better to have it automated so you couldn't screw it up (as long as we maintained the package to keep up with the constantly changing setup steps).
