### ISSUE TITLE
Missing Android while trying to start new project

### ISSUE THREAD

**Issue by 0gebey** [infinitered/ignite#1464]
Hello guys , I'm just trying to start Ignite , I downloaded it via yarn on windows.I'm writting ignite new MyNewIgnite to the cmd console but I got an issue like;

🔥 Setting MyNewIgnite on FIRE! 🔥
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------
Igniting MyNewIgnite

✔︎ Finding react-native
/ Running React Native setup version 0.39.2 (~ 2 minutes-ish)
✔︎ Finding git
✔︎ Getting ready for guests

It can not find android , the error is Missing Android. I have checked the path and it seems okey.
My ignite doctor results are;

Computer
  Platform: win32

Ignite
  Version: 1.13.0
  Path: C:\USERS\OGEDA\APPDATA\ROAMING\NPM\IGNITE.CMD

Node
  Version: v12.8.1
  Path: C:\PROGRAM FILES\NODEJS\NODE.EXE

NPM
  Version: 6.10.2
  Path: C:\PROGRAM FILES\NODEJS\NPM.CMD

Yeoman
  Version: 3.1.0

React Native CLI
  Version: 2.0.1

App
  React Native Version: ¯\_(ツ)_/¯

Please answer me because I'm on my internship now , I have to start working with Ignite immediately.Thank you all.

**Comment by ruddell** [comment]
Please update Ignite to the latest version.  You are on `v1.13.0` where the latest version is [`v3.1.6`](https://github.com/infinitered/ignite/releases/tag/v3.1.6).  That should solve several problems.

**Comment by mlaco** [comment]
Closing as resolved

**Comment by jazibabdullah1** [comment]
@ruddell can you please guide how to update ignite or how to install a specific version on it?
