### ISSUE TITLE
README: Create graphic for Jon Ruddell quote

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1467]
In the README, we have this great quote:

> Ignite saved me a few weeks (if not months) getting started with React Native.
>
> Jon Ruddell

I'd like to create a graphic for Ignite and embed it in the README.

**Comment by GantMan** [comment]
Yes!  I love quote cards!   They really make stuff beautiful!   Here's how much they livened up a separate post.

![image](https://user-images.githubusercontent.com/997157/65645670-f8f30580-dfbd-11e9-95e6-56ec1e3a4b40.png)
