### ISSUE TITLE
'ignite' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ahuseyn** [infinitered/ignite#1472]
I have an issue seems to insolvable. I installed ignite cli as described. But after install any `ignite `command returns same answer:
**'ignite' is not recognized as an internal or external command,
operable program or batch file.**

Then I tried to install cli via npm but I got same results. My system is windows 10. There are no problem with dependencies because I installed all of them.

Thank you in advance!

**Comment by jamonholmgren** [comment]
Hey @ahuseyn, can you try running it with `npx` instead?

```
npx ignite doctor
```

**Comment by arielrodrigues** [comment]
Hi @ahuseyn, I am not a windows user but I guess that it can be solved putting ignite-cli in your Environment Variables. Maybe you missed that step? Can you try to add it to your Environment Variables and tell us if it solves your problem?
