### ISSUE TITLE
Add `ignite-cli` binary command to allow running with NPX

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1487]
We need to add a new binary in `./bin` called `./bin/ignite-cli` to allow Ignite to be run with NPX.

It can just require the other `./ignite`, which should work to trigger the CLI.

```js
#!/usr/bin/env node

require('./ignite')
```

Make sure to `chmod +x ./bin/ignite-cli`, and test it with `./bin/ignite-cli doctor` to ensure parameters are passed.

The `files` property in package.json shouldn't need to change, as it already includes `./bin` in full.

**Comment by anusha5695** [comment]
@jamonholmgren : I would like to give it a try

**Comment by anusha5695** [comment]
@jamonholmgren : PR: https://github.com/infinitered/ignite/pull/1492. Is this what is required?
