### ISSUE TITLE
Clean up ignite doctor generators output

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1490]
#1478 fixed the generators not showing up, but the output leaves a little to be desired:

![image](https://user-images.githubusercontent.com/1479215/67791958-91edc400-fa35-11e9-87bf-3ac0646af09f.png)

Let's clean this up and make it look good.

@mikaoelitiana or @arielrodrigues, are you interested in doing this?

**Comment by mikaoelitiana** [comment]
Sure, I will check that

**Comment by mikaoelitiana** [comment]
@jamonholmgren, it would look like this : 

![Capture d’écran 2019-10-31 à 17 10 11](https://user-images.githubusercontent.com/674667/67964899-599ae100-fc01-11e9-8ad6-77a1ab0c4224.png)
