### ISSUE TITLE
[Generator] - Remove Examples - BLANK PROJECT feel

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#150]
Create a command which helps users rip out the kitchen sink and place it comfortably out of the way.

Consider asking this upfront with the generator.

**Comment by ahsanazim** [comment]
@GantMan what workflow do you currently imagine a dev to have with ignite? 

For example, currently if you generate a new component/container/etc through the ignite cli then it's created in an App directory within the existing application. Do you feel that we should develop our own app within said App directory, and then when ready, remove your existing application contents? (and then fix the wiring accordingly)

**Comment by GantMan** [comment]
Thanks @ahsanazim !!!!  We love working on this :)   Let's chat about it.

### Quick Review
**Ignite 1.0 workflow** - Create an app, app has everything and more.  Delete more things than you use, o wow why so much!? AHHHHH!!!!

**Ignite 2.0 workflow** - `ignite new MyApp` creates a very bland app.   You can then use our friendly set of generators `ignite walkthrough` (or something witty) will give you a "Will your app have X/Y/Z, walkthrough process, and fire the correct generators "

To get to v2, from v1, we'll need to take all our kitchen sink items and start writing friendly generators for them.  Once all existing items are wrapped in a generator instead of just copied files, we'll be good.

For this reason, I kinda have trouble spending too much time on a project CLEANING task to remove examples, but perhaps it would be best if we came up with a "v2.0 empty project except for the essentials, and folder structure that we expect" to be generated.  Sort of a beginnings of the bare bones metal all generators should use.   We can then break ignite into `ignite new Project` - Would you like the kitchen sink with that? question on the generation process.   OR just have a kitchen sink command.  Thoughts?

cc:  @skellock @ryanlntn @fvonhoven

**Comment by GantMan** [comment]
O and don't forget @kevinvangelder 
![image](https://cloud.githubusercontent.com/assets/997157/17828158/7a242e2c-664f-11e6-996c-4fbcf0b71fca.png)
# KEVIN!

**Comment by ahsanazim** [comment]
@GantMan hhhmm the transition from v1 to v2.0 sounds fascinating, as do the possibilities for various kinds of v2's . 

The current base v2.0 goal (i.e. *'`ignite new MyApp` creates a very bland app. You can then use ...'* ) seems really cool - just the functionality of easily being able to take your app from a blank and basic state to one that has several views along with assorted wiring (store, sagas, etc) would increase dev speed to a ridiculous degree :) I'd say that - i.e. the current v2.0 goal - strikes just the right balance between having Ignite at once help you sprint through time-consuming boilerplate, while also still giving you the feel of constructing something that feels like it's your own and could've been written by you. (A shoutout here to some of the underlying tech decisions you guys made - the navigation scheme in particular has proved especially useful 👍 )

So yes, although that answer got a bit meandering, I'd definitely say your current v2.0 goal sounds best. For example: 

User gets initial project (with varying amounts of boilerplate already there, depending on answers to a startup walkthrough along the lines of what you mentioned)  ---> user begins normal app development ---> if user at a later stage wants to quickly generate, say, a listview, types in the appropriate ignite command ---> user gets a listview all wired up and ready to fill in

^^^ something along those lines sounds pretty decent if you ask me ;)

**Comment by skellock** [comment]
`ignite new MyApp --min` or `ignite new MyApp --empty` or you can even create your own app templates in 2.0.
