### ISSUE TITLE
ignite-bowser does not have a boilerplate.js

### ISSUE THREAD

**Issue by jainthedestroyer** [infinitered/ignite#1500]
---
What's going on?

🔥 igniting app Temp3
✖ ignite-bowser does not have a boilerplate.js
error installing boilerplate
---
Steps to reproduce
`ignite new Temp3 --boilerplate bowser --no-detox`
---
`ignite doctor` results:

System
  platform           linux                                                 
  arch               x64                                                   
  cpu                4 cores      Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz 
  directory          destroyer    /home/destroyer                          

JavaScript
  node               12.13.0      /usr/bin/node 
  npm                6.12.0       /usr/bin/npm  
  yarn               1.19.1       /usr/bin/yarn 

Ignite
  ignite-cli         3.3.1        /usr/bin/ignite                        
  ignite src         build        /usr/lib/node_modules/ignite-cli/build 
  generators         {}                                                  

Android
  java               1.8.0_232-ea   /usr/bin/java 
  android home       -              undefined

**Comment by TnasuH** [comment]
Me too.

**Comment by Gorhom** [comment]
should be fixed now https://github.com/infinitered/ignite-bowser/issues/290 👍🏿
