### ISSUE TITLE
Disable persisting data

### ISSUE THREAD

**Issue by radouanedev** [infinitered/ignite#1524]
Hi guys, do you have any idea on how to disable persisting data definitively ?

**Comment by 3mpe** [comment]
You must turn off the active parameter in REDUX_PERSIST

**Comment by kevinvangelder** [comment]
Disable lines 35 and 52 in [setup-root-store.ts](https://github.com/infinitered/ignite-bowser/blob/master/boilerplate/app/models/root-store/setup-root-store.ts#L35).

**Comment by bryanstearns** [comment]
Closing this - not an issue
