### ISSUE TITLE
Is Redux a must?

### ISSUE THREAD

**Issue by mehdi-cit** [infinitered/ignite#153]
Hello and thank you for ignite.
Is it mandatory to use Redux? 
Ignite seems great but at the same time I dislike Redux with passion.
I'm sure one can find ways to use Ignite without Redux but how practical would that be?
Thanks for your feedback in davance.

**Comment by hknd** [comment]
(I am just an ignite user)

I can't believe that someone can dislike redux, but thats one of the benefits of using react: you can use any state-container you want, or none if you want to manage your state by yourself.

Practically you would need to remove all redux relevant code from your Root (App/Root.js) component and add your own store (any flux store, or rxjs store, or none).

Nevertheless, if your app or products grows you'll face some challanges which are solved by using redux and the architecture of ignite (which occasional is completely equal to our companies react arcitecture).

**Comment by mehdi-cit** [comment]
Thanks @hknd 
>> if your app or products grows you'll face some challanges which are solved by using redux and the architecture of ignite 
Is there something inherently biased towards Redux that mandates it use if the app "grows in complexity". One can simply use their own state management "thing" or would that alternative turn to be tedious due to ignite inner nature? 
PS: We do exist (developers disliking Redux) but we are just hiding for now :)

**Comment by skellock** [comment]
Nothing is a must.  Ignite is indeed opinionated when it comes to state container choice.   We've seen Redux make a big difference in the apps we're building.

There is still value though in Ignite if you remove Redux, although considerably less.

Before you jump in, have a look around.  See how we do our theming.  Checkout our API access and our developer screens.

Redux is awesome.   But so is mobx, rxjs, and cerebral.   Use what's right for you.  And don't hide.  By exposing problems with Redux, it'll get better, or it's successor will.

**Comment by mehdi-cit** [comment]
Thank you for your reply.
Hiding was just a joke at ( I can't believe that someone can dislike redux )!

**Comment by skellock** [comment]
Ha!  Totally flew over my head!  :)

**Comment by GantMan** [comment]
@mehdi-cit  - As our version 2 evolves, we hope to become more amicable towards differing opinions.   For example, right now you get push notifications... you may not want that.   Only a subset of our apps need it.  **BUT** for version 1.0 we decided to go kitchen sink.   Version 2.0 will be generator based, a la `ignite add push` etc.   There's no rule that says that there won't be a `ignite add mobx` one day... just depends on the demands and ecosystem.   

Personally, I'm a fan of Redux :)  so I'll be making that generator first, but comparability will be our ultimate goal.   Please take this with a grain of salt, though, as we just released version 1.0, so 2.0 is far far away.

**Comment by mehdi-cit** [comment]
Thanks @GantMan !.
I will keep an eye on ignite

**Comment by ahmed1490** [comment]
I must say I started using sagas because of ignite and I Love how simple my control flows become with sagas! :)

so.. my vote against redu(e)xit  for the sake of redux-sagas :D

**Comment by skellock** [comment]
With the new app-templates and plugins in 2.0, redux is now optional.
