### ISSUE TITLE
Is there any play to support React navigation v5

### ISSUE THREAD

**Issue by bhaveshdaswani93** [infinitered/ignite#1534]
The newly released react navigation v5 is a component based approach versus react navigation v4 which is like registry based approach and there are kindly new features in react navigation v5. 
Are you planning for providing support for react navigation v5

**Comment by kevinvangelder** [comment]
There is already an open PR, you can help us out by reviewing the code and/or taking it out for a test drive.

**Comment by bhaveshdaswani93** [comment]
ok, will look into that.
