### ISSUE TITLE
Question: generate screen w

### ISSUE THREAD

**Issue by lasharela** [infinitered/ignite#1536]
I've just discovered Ignite and created `Bowser` template.

In a template, I see that screens are in directories (which is nice), but by default `ignite generate screen login` creates screen in the root of the `screen` directory.

Is there any way to specify directory?

**Comment by mazenchami** [comment]
@lasharela using the latest version, you can only generate a screen into the `screens` folder (i.e. `/app/screens/test/test-screen.tsx`). Generating into a different folder isn't currently possible. I will be closing this issue.
