### ISSUE TITLE
change navbar height

### ISSUE THREAD

**Issue by texas697** [infinitered/ignite#154]
I am trying to change the navbar height and margins with no luck. I can change the icon sizes, but when I adjust the navBarHeight in Metrics.js nothing changes? This is on android

**Comment by GantMan** [comment]
It might be changing, but the nav bar height spacing of the main controller might still be set, and the background color is the same as the navbar, giving the illusion that it's not changing.

Could you try using inspector to verify?  Or change background color etc?  If you're still having problems, I can dig in further.

**Comment by texas697** [comment]
I changed the height to 54 and changed the color. no difference. here is inspector
![screenshot_2016-06-08-12-35-20](https://cloud.githubusercontent.com/assets/6617881/15904236/cce32572-2d75-11e6-9fbc-53f6f3e51b69.png)

**Comment by GantMan** [comment]
I believe I just fixed this, could you make the same change locally?

https://github.com/infinitered/ignite/commit/810794c4a7d3f21e07ce47e285e921ae8878f9c7

**Comment by texas697** [comment]
that was it. thank you! also on another note, could you add a how to implement the Android BackButton to pop the navigation stack. Thanks!

**Comment by GantMan** [comment]
I love that idea!  Please file a ticket and we'll get that in there soon :)  We're looking at doing a navigation update for version 1.1

**Comment by sudharsan1988** [comment]
When I change the height in metrics.js, it hides the navigation bar title and buttons. I tried changing the margins but no luck. Am I missing something here? I wanted to have the navbar height as 34 and it hides both the title and button.
