### ISSUE TITLE
Prepare for React Native 0.62.0

### ISSUE THREAD

**Issue by DeVoresyah** [infinitered/ignite#1540]
So I just see that react native will release new version `0.62.0`. And I see that the core team of Ignite not really focus on **Andross Boilerplate**. For me, Andross Boilerplate is really good, especially for new beginners to React Native.

So I hope to ignite the core team to develop Andross Boilerplate, if it's because of the fund or something. Maybe we can open funding to develop more this boilerplate.

Regards,

**Comment by tuandt** [comment]
This is a good idea. I want to give a hand.

**Comment by vantuan88291** [comment]
dont, please wait for 0.63 release

**Comment by DeVoresyah** [comment]
I would like to donate for new Ignite Boilerplate roadmap, since I can't help to contribute

**Comment by jamonholmgren** [comment]
@DeVoresyah I really appreciate your offer! If someone outside of IR wants to take you up on your offer, that's great -- and tag me so I can review the PR.

**Comment by waqas19921** [comment]
@DeVoresyah @jamonholmgren i can send PR for upgrade.

**Comment by DeVoresyah** [comment]
> @DeVoresyah I really appreciate your offer! If someone outside of IR wants to take you up on your offer, that's great -- and tag me so I can review the PR.

I've some requirement list to do in next ignite update:
- [ ] React Native version minimum 0.62
- [ ] React Navigation v5
- [ ] Redux Saga

Please still using the current Ignite project structure, we just need to upgrade RN version and Navigation. For Reactotron, I think we don't need it anymore since RN 0.62 already give default debugger??

**Comment by waqas19921** [comment]
@DeVoresyah I have created a pull request here https://github.com/infinitered/ignite-andross/pull/307

It is currently creating a new project with above mentioned requirements.

**Comment by waqas19921** [comment]
@jamonholmgren I need your guideline for linting the project files. As i have not updated linting libraries.
Also plugins like dev-screens, vector-icons and redux-persist also needs to update.

**Comment by jamonholmgren** [comment]
@waqas19921 

On linting, you probably don't need to update the linting library. Just keep it at the current version.

The plugins -- do you know what needs to be updated?

**Comment by waqas19921** [comment]
i think we have to remove dev-screens and move some screen examples in the boilerplate. Rest just needs version updates.

**Comment by jamonholmgren** [comment]
@waqas19921 If you can submit PRs and then post here with a list of all the PRs to review, I'll get that done.
