### ISSUE TITLE
remove component or screen with teminal not working

### ISSUE THREAD

**Issue by tunm1228** [infinitered/ignite#1541]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

---
Steps to reproduce

---
`ignite doctor` results:

**Comment by bryanstearns** [comment]
Ignite doesn't support removing components or screens from the command line - it's not something we do all the time (like generating components & screens), and it's just a matter of removing a couple of files, so I don't think it'd be much of a timesaver - but if you disagree, please explain and we'll see what we can do.
