### ISSUE TITLE
How do I use mobx-state-tree in my class components?

### ISSUE THREAD

**Issue by tunm1228** [infinitered/ignite#1542]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

---
Steps to reproduce

---
`ignite doctor` results:

**Comment by jamonholmgren** [comment]
@tunm1228 The best way is to use `mobx-react` rather than `mobx-react-lite` which only supports function components. Otherwise it should work pretty similarly.
