### ISSUE TITLE
cant start my firts app

### ISSUE THREAD

**Issue by saso1212** [infinitered/ignite#1543]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

---
Steps to reproduce

---
`ignite doctor` results:

**Comment by saso1212** [comment]
I cant start my first app.
I have error on my android Simulator TypeError:undify is not an object(evaluating '._reactNavigator.ThemeColor.light')


 platform           win32       
  arch               x64         
  cpu                4 cores      Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  directory          burgerApp    D:\REACT-NATIVE\ignite\burgerApp

JavaScript
  node               13.11.0      C:\Program Files\nodejs\node.EXE
  npm                6.13.7       C:\Program Files\nodejs\npm.CMD
  yarn               1.22.4       C:\Program Files (x86)\Yarn\bin\yarn.CMD

Ignite
  ignite-cli           3.5.1     
                                                                                C:\Users\sdavidovic\AppData\Local\Yarn\bin\ignite.CMD
  ignite src           build     
                                                                                C:\Users\sdavidovic\AppData\Local\Yarn\Data\global\node_modules\ignite-cli\build
  createdWith          3.5.1     
                                                                               

  boilerplate          ignite-andross
                                                                               

  examples             classic   
                                                                               

  navigation           react-navigation
                                                                               

  askToOverwrite       true      
                                                                               

  generators           {"component":"ignite-andross","container":"ignite-andross","list":"ignite-andross","redux":"ignite-andross","saga":"ignite-andross","screen":"ignite-andross","listview":"ignite-andross"}  

  boilerplateVersion   4.2.0     
                                                                               


Android
  java               -            C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\sdavidovic\AppData\Local\Android\Sdk

**Comment by irosadie** [comment]
same issue

**Comment by akash89bis** [comment]
More or less same issue 
"TypeError: Cannot read property 'light' of undefined" any idea/guidance what could be the issue?

**Comment by akash89bis** [comment]
@saso1212  - were you able to fix it, please let me know?

**Comment by exlnt** [comment]
I'm running into this same issue.

**Comment by santoshzp** [comment]
I'm running into this same issue.

**Comment by markrickert** [comment]
@kevinvangelder Any way you could take a look at this one on windows? You might also want to see if my PR fixes the issue on windows here: #1686

**Comment by joshuayoes** [comment]
There has been a lot of changes since this issue last had activity. This is going to be closed for now, but please re-open if this still needs attention.
