### ISSUE TITLE
ignite new IgniteApp    This command requires yo to be installed. Error.

### ISSUE THREAD

**Issue by ottotsuma** [infinitered/ignite#1544]
C:\Users\"User"\Desktop\Textables>ignite new IgniteApp
This command requires yo to be installed.
Installing yo...
'CI' �́A�����R�}���h�܂��͊O���R�}���h�A
����\�ȃv���O�����܂��̓o�b�` �t�@�C���Ƃ��ĔF������Ă��܂���B
🔥 Setting IgniteApp on FIRE! 🔥
'yo' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
events.js:288
      throw er; // Unhandled 'error' event
      ^

This is the error message I got when trying to run "ignite new IgniteApp" in the cmd. I have no idea what the funky ?? are but the Japanese below is expected. Oh I should add I installed Ignite. 

C:\Users\"User"\Desktop\Textables\TextArt>ignite -V
1.13.0

Windows 10

Hope this helps also,

Snow

**Comment by ruddell** [comment]
You should use the latest version of the `ignite-cli` package which is currently v3.5.1, you are using v1.13.0.  Yeoman is no longer used in ignite since v2

**Comment by ottotsuma** [comment]
im doing "npm install -g ignite-cli" is this not how you install the latest package of ignite? as I did it again just now and again i have been given 1.13.0

**Comment by ruddell** [comment]
That's definitely confusing since I don't see a 1.13.0 release of `ignite-cli` available on npm (verified with `npm view ignite-cli versions`).

You can try to install the latest by specifying the version: `npm install -g ignite-cli@v3.5.1`

**Comment by akash89b** [comment]
@ottotsuma  - please dont use "npm install -g ignite-cli". First install yarn via choco.
Run "choco install yarn" and then simply run "yarn global add ignite-cli", this will work fine.

**Comment by ottotsuma** [comment]
I`m not sure if still doing someting wrong but i followed @akash89b  and i got the following:

C:\Users\locks>yarn global add ignite-cli
yarn global v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "ignite-cli@3.5.1" with binaries:
      - ignite
Done in 3.33s.

C:\Users\locks>ignite -V
1.13.0

I am trying to do @ruddell suggestion but I am getting some strange errors so i feel this must be the root of the problem, thank you for helping !

**Comment by ottotsuma** [comment]
After uninstalling chocolate and just running npm install -g ignite-cli@v3.5.1 in the cmd with node.js the issue was resolved. For some reason with chocolate installed i kept getting the error: npm ERR! code EEXIST.
