### ISSUE TITLE
Ignite Select Query Performance

### ISSUE THREAD

**Issue by SivaSamrajS** [infinitered/ignite#1546]
Hi Ignite Team,

I have a table A which has composite primary key and there is no index on this table. The table will usually have 10 columns and it can go upto 10M records. Whenever i am selecting records from this table, i am giving 3 keys in the where condition. My application is taking taking almost 10 mins to do the job with the select query, without the select query it is taking only 10 seconds. 

Please let us know, anything we need to improve? We re using Ignite 2.7.5 version and 4 node cluster. One of the primary key is the affinity key.

**Comment by ruddell** [comment]
Are you sure this is the right project to report this issue on?  I'm guessing you are looking for the Apache Ignite repository.  

This repository is for the Ignite CLI for React Native, which doesn't have code dealing with databases.
