### ISSUE TITLE
Cocoapods Installed but Error Installing Boilerplate

### ISSUE THREAD

**Issue by destinybonavita** [infinitered/ignite#1549]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

---
What's going on?

I'm trying to run `ignite new project` but it's throwing the below error:
I have cocoapods installed so it should be working fine. Not sure why this issue is happening.

```
an error occured while installing ignite-bowser boilerplate.
Error: Command failed: yarn
error Command failed with exit code 1.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn',
  stderr: 'error Command failed with exit code 1.\n'
}
error installing boilerplate
```

---
Steps to reproduce

Run `ignite new project`

---
`ignite doctor` results:

System
  platform           darwin                                                                              
  arch               x64                                                                                 
  cpu                16 cores       Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz                             
  directory          React Native   /Users/user/Documents/project/React Native 

JavaScript
  node               13.7.0       /Users/user/.nvm/versions/node/v13.7.0/bin/node 
  npm                6.14.2       /Users/user/.nvm/versions/node/v13.7.0/bin/npm  
  yarn               1.22.0       /Users/user/.nvm/versions/node/v13.7.0/bin/yarn 

Ignite
  ignite-cli         3.5.1        /usr/local/bin/ignite                                                    
  ignite src         build        /Users/user/.config/yarn/global/node_modules/ignite-cli/build 
  generators         {}                                                                                    

Android
  java               1.8.0_241    /usr/bin/java                              
  android home       -            /Users/user/Library/Android/sdk 

iOS
  xcode              11.4.1     
  cocoapods          1.9.1        /usr/local/bin/pod

**Comment by kevinvangelder** [comment]
Do you use a ruby switcher like `chruby` or `ruby-env`? I often forget to switch to the ruby that has cocoapods installed when running `ignite`.

**Comment by destinybonavita** [comment]
I don't think I do; how would I check?

**Comment by destinybonavita** [comment]
Fixed it! There was a problem with my cocoapods setup

**Comment by bryanstearns** [comment]
Hey @destinybonavita -- can you share what was wrong with your cocoapods setup? Maybe it's something Ignite could check for, and give a clearer error message.

**Comment by destinybonavita** [comment]
I think it came down to a problem with the `./configure` file having the wrong file encoding. I tried a bunch of things at once and it eventually worked. 

The last thing I tried was changing my global git config to ignore file encodings for macOS vs Windows

**Comment by bryanstearns** [comment]
Alrighty, thank you!
