### ISSUE TITLE
Basic getting started questions

### ISSUE THREAD

**Issue by RaphaelFreedactics** [infinitered/ignite#1554]
Hey there, 

thanks a lot for this awesome project. 
I'm just starting to play around with ignite and really like it. 

However I've got a few questions, which in fact are probably pretty dumb. Sorry in advance :)

1) If I like to use some third party npm package, which is not installed and for which no ignite plugin exists. Can I just go ahead and `npm i -s package` or am I supposed to create a plugin first?

2) If I use Bowser but would rather like to use Redux as state solution. (We use Redux in the corresponding Web Project and state logic ist almost same) Can I just delete the MST store with an Redux store and use Redux as I  would normally? Or are there any deep dependencies in the project structure, that would cause issues? 

Thanks a lot for your help
Raphale

**Comment by kevinvangelder** [comment]
Hey @RaphaelFreedactics, thanks for trying Ignite!

1. Plugins are not required. We added the ability to use plugins to help automate the large number of steps required to install and configure some packages, but these days a lot of the packages have simplified their own setup process.
1. I've lost track of it, but I think someone out there was working on an Ignite Boswer Redux boilerplate, so I'd suggest you try to see if you can find it. Even if it isn't completed and usable there is probably a lot of information you could learn from it regarding how much work would be necessary. You would need to swap out the provider, my guess is that migrating the navigation portion to Redux would probably be the most difficult part.

Let us know how it goes!

**Comment by RaphaelFreedactics** [comment]
Thanks a lot for your help!
