### ISSUE TITLE
Boilerplate with graphql support

### ISSUE THREAD

**Issue by vamshi9666** [infinitered/ignite#1557]
There are no boilerplates supporting graphql currently. It would be great to have one with ```mst-gql``` integrated. 

related: 
#1181

**Comment by kevinvangelder** [comment]
We were going to use GQL in our next boilerplate, but most of our client projects have been sticking with REST API's, so for now an Infinite Red GQL boilerplate is on hold. As always, community boilerplates are welcome.

**Comment by vamshi9666** [comment]
cool. I am planning to build one boilerplate with mst-gql support with [this](https://shift.infinite.red/make-your-own-react-native-boilerplate-with-ignite-cli-c45bfa564684) guide

**Comment by sharife3** [comment]
Is there any plan to show how GraphQL can be used here?
