### ISSUE TITLE
making custom generators doesnt work

### ISSUE THREAD

**Issue by dakkafex** [infinitered/ignite#1558]
what the title says.

the documentation on creating generators seems to be outdated and doesnt work as described. (or work at all for that matter)

**Comment by tmaly1980** [comment]
I haven't figured this out either. Any luck? I've created the plugin with a generator example, but I don't know how to access it.

**Comment by jamonholmgren** [comment]
We've reworked custom generators in the latest Ignite (6.x). Check out the [blog post about it](https://shift.infinite.red/introducing-ignite-4-0-flame-1dfc891f9966) and try it out!
