### ISSUE TITLE
Ignite install throws error "an error occured while installing ignite-bowser boilerplate"

### ISSUE THREAD

**Issue by jeysinghanbu** [infinitered/ignite#1559]
**Issue:** 
command used for installing ignite
`sudo ignite new reactgenMob --debug`

---
**Error:**
an error occured while installing ignite-bowser boilerplate

![image](https://user-images.githubusercontent.com/4211519/86512792-c3b7f580-be22-11ea-9f4b-395c3f9d0d96.png)

---

**Ignite Doctor:**

System
  platform           darwin
  arch               x64
  cpu                4 cores       Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  directory          reactgenMob   /Users/mariajeysinghanbu/reactgenMob/reactgenMob

JavaScript
  node               13.14.0      /usr/local/bin/node
  npm                6.14.4       /usr/local/bin/npm
  yarn               1.22.4       /usr/local/bin/yarn

Ignite
  ignite-cli         3.5.2              /usr/local/bin/ignite
  ignite src         build              /usr/local/share/.config/yarn/global/node_modules/ignite-cli/build
  navigation         react-navigation
  generators
                     component          ignite-bowser
                     model              ignite-bowser
                     navigator          ignite-bowser
                     screen             ignite-bowser

Android
  java               1.8.0_252    /usr/bin/java
  android home       -            undefined

iOS
  xcode              11.3.1
  cocoapods          1.9.3        /usr/local/bin/pod

---
_Thanks in advance!_

**Comment by jeysinghanbu** [comment]
I changed the version in command like this and getting below error

`ignite new reactgenMob --react-native-version=0.54.2
`

---

Error

````
an error occured while installing ignite-bowser boilerplate.
Error: Command failed: yarn
error Command failed with exit code 1.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn',
  stderr: 'error Command failed with exit code 1.\n'
}
error installing boilerplate
````

**Comment by jeysinghanbu** [comment]
```
react-native init Test
cd Test
```

and then add ignite-bowser, like this:

`yarn add ignite-bowser --dev`

I tried this way it successfully completed. do you have any idea why it is not working on ignite?

**Comment by hbxz** [comment]
Same case, same error message. 
My case was fixed by installing the missing `react-native-cli`.
You can run `npm install -g react-native-cli` and try again.
