### ISSUE TITLE
[CLI | Generator] Add support for Relay

### ISSUE THREAD

**Issue by DanielMSchmidt** [infinitered/ignite#156]
Hi there,

First of all thanks for this super awesome project! 
![awesome](http://tclhost.com/wdbODwX.gif)

I would love to see one feature added: **Support for [relay](https://github.com/facebook/relay)**
This would include
- [ ] a boolean option for the initial generation
- [ ] a generator for a relay container

This would be super awesome as the initial setup time for relay is quite high and complex.
Have a nice day!

**Comment by skellock** [comment]
I can't stop laughing at the gif.

**Comment by DanielMSchmidt** [comment]
On this matter, I haven't had the time to work with relay currently, but I plan to do so in the near future. Would you like to see a Pull Request for this, as soon as I get started with it?

**Comment by skellock** [comment]
I know very little about Relay.

This boilerplate project is very much invested in Redux, right down to the UI split of containers & components.

My vote for now is to stick with Redux.  And it's not because another state container isn't awesome, it's just a big switch.

I do see a future where `ignite new FurryCosplayApp --stateContainer mobx` is a thing.

If you get your Relay app up & open-sourced, I'd love to walk through it.  I know absolutely nothing about Relay.

**Comment by DanielMSchmidt** [comment]
As you can see with the [F8 App](https://github.com/fbsamples/f8app) ([see the blog post here](http://makeitopen.com/tutorials/building-the-f8-app/relay/))  redux and relay are not mutual exclusive. You can use both in the same project with no harm as the solve different problems, redux solves state change and relay data fetching.

I see that it may be too early to adopt it in this project, so I am going to get back to you as soon as I have an application with both up and running.

**Comment by skellock** [comment]
No, actually I didn't know that.  Thanks for the insights!  Will study up some more.

**Comment by DanielMSchmidt** [comment]
I will build an application generated with ignite which includes relay, so you may see how they play together

**Comment by matart15** [comment]
@DanielMSchmidt Did you able to use ignite with relay?
I looked at your https://github.com/DanielMSchmidt/ignite-relay-demo

but it seems not working.

**Comment by DanielMSchmidt** [comment]
@matart15 Sorry, but I didn't manage to get this working and kind of stopped working on it for a while. But I think I will give it another shot in the next couple days and keep you up to date.

**Comment by skellock** [comment]
This is possible to do now in 2.0 with plugins.  I'd love to see a relay or an apollo plugin!

**Comment by DanielMSchmidt** [comment]
Great idea, I wish I had more time for things Like this :/

**Comment by skellock** [comment]
There's so much awesome going on in the React Native world right now.  I can't keep up anymore.
