### ISSUE TITLE
Document the Using Your Own Boilerplate

### ISSUE THREAD

**Issue by johntimothybailey** [infinitered/ignite#1561]
## Documentation Request

_Note: Perhaps I missed it, and if so I recommend moving the usage message to the Boilerplate available documentation page too._

---
### What's going on?
Had to go to the [source code](https://github.com/infinitered/ignite/blob/f6f2cbfda602b92905d4bade40c312b6d214fb90/src/lib/detect-install.ts#L68) to figure out how to use my own Boilerplate

---
### Steps to reproduce
1. Go to the documentation.
2. Notice there isn't a clear way of using your own Boilerplate (again apologies if I missed it)

---
### Request
Make a section in the documentation for creating your own Boilerplate and how to use it.
- Local
- Remote via Github

Both seem to be features but not clear how or even that one could use their own.

---
### Final thought
It would be wonderful if there was ignite Bare Boilerplate starter instead of using `ignite spork` Perhaps there is a way to view Spork that I'm currently not.

**Comment by jamonholmgren** [comment]
I haven't reviewed this recently and it is a few years old, but here's an article I wrote about creating your own boilerplate. If it is still relevant, maybe we should link to it more prominently.

https://shift.infinite.red/make-your-own-react-native-boilerplate-with-ignite-cli-c45bfa564684

**Comment by johntimothybailey** [comment]
@jamonholmgren  Thank you! I'll definitely go through it and make some comments. I do agree that should be more prominent. I can submit a PR to the documentation as an idea after going through the article you wrote.

I will respond back here after doing so.

**Comment by tmaly1980** [comment]
I'm curious about this too. The documentation looks a bit outdated, especially regarding publishing the package to npmjs. Any suggestions?

**Comment by tmaly1980** [comment]
Looks like I needed to run "npm install" and "yarn build" for my custom boilerplate, and then publish to npmjs via "npm login" and "npm publish". It seems the generators expect to be found under build/commands, rather than src/commands . Thus any cloning of the boilerplate will fail unless the build folder is compiled/included.
