### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by iamrutvik** [infinitered/ignite#1562]
### Hey there! Ignite CLI seems to be having a problem, eh?

Welllllll, it just might be. First, search the issues to make sure it's not already
here, and if not head over to http://community.infinite.red to
get some help. If you've identified that it's really an Ignite CLI issue, then:

- Explain what's going on and preferably how to replicate the issue (bonus points for a repro app)
- Run `ignite doctor` and paste the result below, including the lines with 3 backticks
- Delete these instructions! We don't want to look at them. ;)

Cant install with ignite new command. Throws error

---
What's going on?

A lot of package errors

---
Steps to reproduce
Just install on a new system

---
`ignite doctor` results:

<img width="1440" alt="Screen Shot 2563-08-13 at 00 56 51" src="https://user-images.githubusercontent.com/19551848/90051723-55f4c880-dd02-11ea-9236-6d5d04dbe0a1.png">

**Comment by BrandonSM** [comment]
What version of ignite are you running @iamrutvik @DilipCoder ?

<img width="568" alt="ignite-andross-output" src="https://user-images.githubusercontent.com/1038726/91245913-9f8add80-e71c-11ea-9969-057883561774.png">

**Comment by amberRrucker** [comment]
Also having the same issues

**Comment by waqarmorghulis** [comment]
I was able to install it successfully having:

1. ignite: 3.5.3
2. node: 14.11.0
3. npm: 6.14.8

@iamrutvik @DilipCoder Which versions you guys have been using?

<img width="1280" alt="Ignite CLI Androse" src="https://user-images.githubusercontent.com/58202900/93901241-c0405600-fd0f-11ea-8f5c-1b98b2b3d28b.png">

**Comment by WaqarShahid147** [comment]
I was able to install it successfully having:

ignite: 3.5.3
node: 14.11.0
npm: 6.14.8
@iamrutvik @DilipCoder Which versions you guys have been using?

<img width="1280" alt="Ignite CLI Androse" src="https://user-images.githubusercontent.com/16704649/93902014-8a4fa180-fd10-11ea-8fe8-96698da2962a.png">

**Comment by flexbox** [comment]
@iamrutvik @DilipCoder 
I got some issues as well because I installed globally ignite
Yes this `ignite`
https://www.npmjs.com/package/ignite

Not that same as `ignite-cli` 😱
