### ISSUE TITLE
I use ignite on my react native app. How do I test on ignite. Really need your help. Test function mainly, login, snapshot,...

### ISSUE THREAD

**Issue by thpthang10** [infinitered/ignite#1564]

**Comment by flexbox** [comment]
Hey @thpthang10 

Thanks for your message but can you please be more explicit because your issue is a huge work.

I suggest you have a look at:
https://github.com/callstack/react-native-testing-library

If it solves your problem can your close your issue?

**Comment by thpthang10** [comment]
> Hey @thpthang10
> 
> Thanks for your message but can you please be more explicit because your issue is a huge work.
> 
> I suggest you have a look at:
> https://github.com/callstack/react-native-testing-library
> or ask your question on https://stackoverflow.com/questions/tagged/react-native
> 
> If it solves your problem can your close your issue?

Thank you! I will close it.
