### ISSUE TITLE
[Generator] - Create an ignite config file

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#157]
When the generator is used to make an app, a version file should be copied in, so we can make an appropriate upgrade path, as well as stub for a place to store information.

Json I assume, contains current version number for starters

**Comment by skellock** [comment]
Great idea. Like an `.igniterc` or something?

```json
{
  "version": "1.0.4",
  "options": {
    "componentFolders": true,
    "styles": {
      "pluralName": false,
      "useStevesHeresyVersionWithoutStyleSheetClass": false,
    }
  },
  "plugins": {
    "reactotron": false,
    "redux": true,
    "tests": "ava"
  }
}
```

**Comment by GantMan** [comment]
yes.  For now, we can have it just be the version.   That way it's there for the moment when we need a more intelligent structure.  Writing a file for version is simple and gets us started.  Future tickets/prs can get us advanced organically.

how about something simple like `.ignite` ?
