### ISSUE TITLE
Reduce npm package size

### ISSUE THREAD

**Issue by retyui** [infinitered/ignite#1571]
Toy suddenly publish a package with test __tests__, .babelrc.js,

- See: https://unpkg.com/browse/ignite@1.11.2/src/

**Comment by bryanstearns** [comment]
Hi @retyui -- Uh, I'm not sure what the issue is, or what you're suggesting. Can you please add more info?

**Comment by retyui** [comment]
@brad https://unpkg.com/browse/ignite@1.11.2/src/__tests__/

`src/__tests__` could you please add ignore rule for this 
![image](https://user-images.githubusercontent.com/4661784/98858773-39d40500-2472-11eb-9491-162212185440.png)

**Comment by bryanstearns** [comment]
I'm pretty sure the [Ignite Flame rewrite](https://github.com/infinitered/ignite/pull/1568) fixed this; please reopen if not.
