### ISSUE TITLE
NOT ABLE TO RUN IT

### ISSUE THREAD

**Issue by moedeveloper** [infinitered/ignite#1572]
There were errors while generating the project. Run with --debug to see verbose output.
    
an error occured while installing ignite-bowser boilerplate.
Error: Command failed with exit code 2: ignite add ignite-bowser 
    at makeError (/Users/mo3/.config/yarn/global/node_modules/gluegun/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/Users/mo3/.config/yarn/global/node_modules/gluegun/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  command: 'ignite add ignite-bowser ',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\x1B[31m----------\x1B[39m\n' +
    '\x1B[31mCommand failed: yarn add ignite-bowser --dev\x1B[39m\n' +
    '\x1B[31mwarning @storybook/addon-storyshots > @storybook/core > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.\x1B[39m\n' +
    '\x1B[31mwarning @storybook/addon-storyshots > @storybook/core > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.\x1B[39m\n' +
    '\x1B[31mwarning @storybook/addon-storyshots > @storybook/core > @storybook/ui > @storybook/components > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1\x1B[39m\n' +
    '\x1B[31mwarning @storybook/addon-storyshots > @storybook/core > @storybook/ui > @storybook/components > react-syntax-highlighter > highlight.js@9.13.1: Version no longer supported. Upgrade to @latest\x1B[39m\n' +
    '\x1B[31mwarning @storybook/addon-storyshots > @storybook/core > @storybook/ui > @storybook/components > react-syntax-highlighter > lowlight > highlight.js@9.13.1: Version no longer supported. Upgrade to @latest\x1B[39m\n' +
    '\x1B[31mwarning @storybook/addon-storyshots > @storybook/core > @storybook/ui > @storybook/components > react-popper-tooltip > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1\x1B[39m\n' +
    '\x1B[31mwarning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\x1B[39m\n' +
    '\x1B[31mwarning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142\x1B[39m\n' +
    '\x1B[31mwarning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request > har-validator@5.1.5: this library is no longer supported\x1B[39m\n' +
    '\x1B[31mwarning " > reactotron-mst@3.1.3" has unmet peer dependency "reactotron-core-client@^2.5.0".\x1B[39m\n' +
    '\x1B[31mwarning "reactotron-react-native > react-native-flipper@0.34.0" has incorrect peer dependency "react-native@^0.62.0".\x1B[39m\n' +
    '\x1B[31mwarning " > @react-navigation/stack@5.12.8" has unmet peer dependency "@react-native-community/masked-view@>= 0.1.0".\x1B[39m\n' +
    '\x1B[31mwarning " > @react-navigation/stack@5.12.8" has unmet peer dependency "react-native-gesture-handler@>= 1.0.0".\x1B[39m\n' +
    '\x1B[31mwarning "@storybook/addon-storyshots > @storybook/core@5.3.19" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".\x1B[39m\n' +
    '\x1B[31mwarning "@storybook/react-native-server > @storybook/api@5.3.19" has unmet peer dependency "regenerator-runtime@*".\x1B[39m\n' +
    '\x1B[31mwarning " > @storybook/react-native-server@5.3.19" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".\x1B[39m\n' +
    '\x1B[31mwarning " > jest-expo@38.0.2" has incorrect peer dependency "react@~16.11.0".\x1B[39m\n' +
    '\x1B[31merror Command failed with exit code 2.\x1B[39m\n' +
    '\x1B[31m\x1B[39m\n' +
    '\x1B[31m----------\x1B[39m',
  stderr: '- adding \x1B[36mignite-bowser\x1B[39m\n' +
    '✖ \x1B[31mignite-bowser\x1B[39m was not able to be installed. Is it a valid NPM module?',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error installing boilerplate

**Comment by flexbox** [comment]
Hey @moedeveloper 

can you please give the output of

```
ignite doctor
```
