### ISSUE TITLE
Got stuck

### ISSUE THREAD

**Issue by cosic-dalibor** [infinitered/ignite#1577]
What's going on?

Just tried following from the landing page and got stuck multiple times:
![image](https://user-images.githubusercontent.com/7594292/103046387-53e02780-4588-11eb-8111-5d61346889b5.png)

Steps to reproduce

1. npx ignite-cli new PizzaApp

---

`ignite doctor` results:

![image](https://user-images.githubusercontent.com/7594292/103046604-1e880980-4589-11eb-9b74-eba568b00a68.png)

**Comment by cosic-dalibor** [comment]
Fixed. Thanks!

**Comment by tusharvikky** [comment]
How? @cosic-dalibor

**Comment by yorickshan** [comment]
> How? @cosic-dalibor

upgrade your node version
