### ISSUE TITLE
Trouble generating app with Ignite 6.0

### ISSUE THREAD

**Issue by banerjed** [infinitered/ignite#1588]
Running into some trouble generating app with ignite 6.0  -- am able to generate a expo app, but that errors out at a different place. Creating a bowser app (with ignite-cli-3.0) works nicely...

banerjed@Dhritimans-iMac work % ignite new TrailBlazers

· · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

█ Creating TrailBlazers using Ignite 6.0.0
█ Powered by Infinite Red - https://infinite.red
█ Using react-native-cli
────────────────────────────────────────────────
🔥 Igniting app
🧊 Cooling print nozzles
☕️ Baking CocoaPods

/Users/banerjed/.config/yarn/global/node_modules/gluegun/build/index.js:13
throw up;
^
yarn run v1.22.5
,error Command "format" not found.
,info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

(Use node --trace-uncaught ... to show where the exception was thrown)

banerjed@Dhritimans-iMac work % ignite doctor
System
platform darwin
arch x64
cpu 4 cores Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
directory work /Users/banerjed/work

JavaScript
node 15.4.0 /usr/local/bin/node
npm 7.0.15 /usr/local/bin/npm
yarn 1.22.5 /Users/banerjed/.yarn/bin/yarn

Ignite
ignite-cli 6.0.0 /Users/banerjed/.config/yarn/global/node_modules/.bin/ignite
ignite src build /Users/banerjed/.config/yarn/global/node_modules/ignite-cli/build

Android
java 1.8.0_275 /usr/bin/java
android home - /Users/banerjed/Library/Android/sdk

iOS
xcode 12.3
cocoapods 1.10.0 /usr/local/bin/pod

>>>>>>>>>>> EXPO RUN CREATED FINE, BUT RAN INTO ERRORS LATER ON >>>>>>>>>>>>>
When generated as an Expo app, here is what I get while trying to run:

Failed to compile.
/Users/banerjed/work/TrailBlazers/node_modules/react-native/Libraries/Network/XMLHttpRequest.js
Module not found: Can't resolve './RCTNetworking' in '/Users/banerjed/work/TrailBlazers/node_modules/react-native/Libraries/Network'

>>>>>>>>>>>>> BOWSER RUN WORKED PERFECTLY >>>>>>>>>>>
banerjed@Dhritimans-iMac work % npx ignite-cli@3 new IgniteTrivia --boilerplate bowser
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app IgniteTrivia
✔ using the Infinite Red Bowser boilerplate
✔ Would you like to use Expo on this project?

        Why Expo? Expo (https://expo.io) is the fastest way to get started.
        However, Expo support is experimental at this time. If unsure, select No and we'll install the traditional route.
        Additionally, using Expo means you won't be able to add any custom native modules.

       (y/N) · false
✔ Would you like to include Detox end-to-end tests? (y/N) · false
✔ added React Native 0.63.2 in 318.51s
✔ Installed dependencies
✔ Linked assets
✔ Linted and formatted
✔ ignited IgniteTrivia in 586.237s

    Ignite CLI ignited IgniteTrivia in 586.237s

    To get started:

      cd IgniteTrivia
      react-native run-ios
react-native run-android
      npx ignite-cli --help
      npx ignite-cli doctor

    Need additional help? Join our Slack community at http://community.infinite.red.

    Now get cooking! 🍽

    (Running yarn install one last time to make sure everything is installed -- please be patient!)
  
✔ yarn complete
✔ configured git
banerjed@Dhritimans-iMac work % cd IgniteTrivia 
banerjed@Dhritimans-iMac IgniteTrivia % git status
On branch master
nothing to commit, working tree clean
banerjed@Dhritimans-iMac IgniteTrivia % react-native run-ios
info Found Xcode workspace "IgniteTrivia.xcworkspace"
info Launching iPhone 11 (iOS 14.2)
 

info Building (using "xcodebuild -workspace IgniteTrivia.xcworkspace -configuration Debug -scheme IgniteTrivia -destination id=DD133A6C-6070-4DCA-92A6-BCF050EC13E1")
(node:90350) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

success Successfully built the app
info Installing "/Users/banerjed/Library/Developer/Xcode/DerivedData/IgniteTrivia-gwymskfwxegfmcdgpndrpjkgotag/Build/Products/Debug-iphonesimulator/IgniteTrivia.app"

info Launching "org.reactjs.native.example.IgniteTrivia"
success Successfully launched the app on the simulator

**Comment by nirre7** [comment]
This is a duplicate of https://github.com/infinitered/ignite/issues/1580

**Comment by banerjed** [comment]
Note the "RCTNetworking" error I am seeing is different:

EXPO RUN CREATED FINE, BUT RAN INTO ERRORS LATER ON >>>>>>>>>>>>>
When generated as an Expo app, here is what I get while trying to run:

Failed to compile.
/Users/banerjed/work/TrailBlazers/node_modules/react-native/Libraries/Network/XMLHttpRequest.js
Module not found: Can't resolve './RCTNetworking' in '/Users/banerjed/work/TrailBlazers/node_modules/react-native/Libraries/Network'

**Comment by nirre7** [comment]
Can you create a "vanilla" expo project? 
https://docs.expo.io/#quick-start

**Comment by banerjed** [comment]
I updated to ignite 6.1.0 and it now seems to work pretty cleanly -- was able to test bring up the dummy app on both IOS and Android


banerjed@Dhritimans-iMac work % ignite doctor
System
  platform           darwin                                               
  arch               x64                                                  
  cpu                4 cores      Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz 
  directory          work         /Users/banerjed/work                    

JavaScript (and globally-installed packages)
  node               15.4.0       /usr/local/bin/node            
  npm                7.0.15       /usr/local/bin/npm             
    brew             0.0.8                                       
    cordova          5.0.0                                       
    expo-cli         4.0.17                                      
    firebase-tools   9.0.0                                       
    gulp             3.8.11                                      
    ignite-cli       3.5.2                                       
    ionic            1.4.5                                       
    ios-sim          3.1.1                                       
    node-gyp         3.4.0                                       
    node             0.0.0                                       
    npm              7.0.15                                      
    satellizer       0.10.1                                      
    yarn             0.16.1                                      
  yarn               1.22.5       /Users/banerjed/.yarn/bin/yarn 
    expo-cli         4.0.17                                      
    ignite-cli       6.1.0                                       

Ignite
  ignite-cli         6.1.0        /Users/banerjed/.config/yarn/global/node_modules/.bin/ignite      
  ignite src         build        /Users/banerjed/.config/yarn/global/node_modules/ignite-cli/build 

Android
  java               1.8.0_275    /usr/bin/java                       
  android home       -            /Users/banerjed/Library/Android/sdk 

iOS
  xcode              12.3       
  cocoapods          1.10.0       /usr/local/bin/pod 
banerjed@Dhritimans-iMac work % ignite new PizzaApp 
   

   · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

    █ Creating PizzaApp using Ignite 6.1.0
    █ Powered by Infinite Red - https://infinite.red
    █ Using react-native-cli
    ────────────────────────────────────────────────

   🔥 Igniting app
   🖨  3D-printing a new React Native app
   ☕️ Baking CocoaPods
   🗄  Backing everything up in source control
   
   
   Ignite CLI ignited PizzaApp in 89.09s
   
   To get started:
     cd PizzaApp  
     npx react-native run-ios  
     npx react-native run-android  
   
   To run in Android, make sure you've followed the latest react-native setup
   instructions at https://facebook.github.io/react-native/docs/getting-started.html
   before using ignite. You won't be able to run Android successfully until you have.
   
   Need additional help?
   
   Join our Slack community at http://community.infinite.red.
   
   Now get cooking! 🍽
   · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

**Comment by banerjed** [comment]
I will close this out. The only issue remaining is the one that was pointed out below, while using "Expo" in web-mode.

https://github.com/infinitered/ignite-bowser/issues/323
