### ISSUE TITLE
Learning ignite by integrating "page swiper component"

### ISSUE THREAD

**Issue by steve21124** [infinitered/ignite#159]
- [x] ignite base application
  - [x] ignite the cli
  - [x] ignite generated code

<pre>
Here is my first test case in integrating ignite with swiper component. feel free to give feedback and any feedback is welcome or feel free to tell if it is not the right direction. 

Currently react native swiper has 1469 stars.
https://github.com/leecade/react-native-swiper
Here are the steps
1. Importing react native swiper library to ignite-base/package.json{dependencies}
2. Need to decide if it is component or container or screen?
- since the swiper library can contain other components or screen but at the same time it will not occupy the whole screen, then it can be categories as "container"
3. To create a new container generator, it can follow LoginScreen.js container
- ignite generate container IntroPage
-- above line create two files
create App/Containers/IntroPage.js
create App/Containers/Styles/IntroPageStyle.js
4. Import "react-native-swiper" library into IntroPage.js
import Swiper from 'react-native-swiper'
5. add swiper to IntroPage.js
		<Swiper style={styles.container}		      
		      showsButtons={true}>
		        <View style={styles.slide1}>
		          <Text style={styles.text}>Hello Swiper</Text>
		        </View>
		        <View style={styles.slide2}>
		          <Text style={styles.text}>Beautiful</Text>
		        </View>
		        <View style={styles.slide3}>
		          <Text style={styles.text}>And simple</Text>
		        </View>
		 </Swiper>
6. add style to /IntroPageStyle.js
  slide1: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#9DD6EB',
    },
    slide2: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#97CAE5',
    },
    slide3: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#92BBD9',
    }  

7. integrate drawer on the left side to call Intro Page and here is the gist
https://gist.github.com/steve21124/f8e2ad1e34d06e8e3db68a4b5380f2ff

IntroPage and IntroPageStyle gist
https://gist.github.com/steve21124/f8e2ad1e34d06e8e3db68a4b5380f2ff

8. the screenshot of functional intro page tour
https://giphy.com/gifs/xT0GquNnoIMhzSUkG4

9.===> Next step is ==> Ideas in how to make this as part of generator component
10. There are 2 files  to make swiper component to work
App/Containers/IntroPage.js
App/Containers/Styles/IntroPageStyle.js

11. Swiper type/parameters as component
- Number of slide
- Type of slide (horizontal slide, vertical slide, header slide, whole page slide)

12. Finally, is all these above necessary to create it as a component? may be it just too much customization for generator and less priority 

</pre>

**Comment by GantMan** [comment]
@steve21124  - I think RN just merged a swiper though.   

Look at swipable list view:  https://github.com/facebook/react-native/releases/tag/v0.27.0

**Comment by GantMan** [comment]
btw, awesome doc and action steps.

**Comment by steve21124** [comment]
Good catch. I did not know there will be Swiper soon in RN. so I can close this then... let RN do the job :)
