### ISSUE TITLE
Application width is fixed, does not expand when rotated

### ISSUE THREAD

**Issue by darron-haworth** [infinitered/ignite#160]
- [ x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

Hey, has anyone else noticed that with the out-of-the-box application, the width is fixed to the device width on launch.  On Android virtual and physical, or IOS simulator, the application screens do not expand to fill the entire screen when rotated left or right.  

![igniterotated](https://cloud.githubusercontent.com/assets/9342747/15988178/32492380-2ffb-11e6-80c7-baff318fa95a.png)

**Comment by GantMan** [comment]
Hey @darron-haworth 

I noticed that if I refresh while in landscape, it will fit the whole screen.  It appears to be some issue with width/height being set and not re-evaluated on rotation.

@fvonhoven  and @kevinvangelder  and @skellock 
Do you think we should use https://github.com/yamill/react-native-orientation ?

**Comment by skellock** [comment]
@ryanlntn mentioned this as well:  https://github.com/walmartreact/react-native-orientation-listener

I haven't any of them yet.

**Comment by darron-haworth** [comment]
@GantMan 

Thanks for looking at this, I am new to RN.  Hooking into the rotate event and changing the width on rotate is not something I am going to be able to do right now.   This library looks really awesome but I can't use it as it currently sits.  I don't understand how this library can be described as "battle tested" when rotating leaves it with a fixed width.  This seems pretty important and basic, I wish I were familiar enough with RN to work around this issue so that I could start our next project with Ignite...

I will keep an eye out as the project matures...

**Comment by GantMan** [comment]
Hey Darron, we've shipped apps, but none that needed this particular feature... yet.

We'll make this feature higher priority, because as you've stated, it's quite fundamental.  Look for updates in this ticket.

**Comment by darron-haworth** [comment]
Thanks @GantMan for the response.  I've been trying to find some "how to use" documents for the ignite project. Pulling it down and running it is one thing, but being new to all things RN is making things difficult.  Changing the theme is where I am trying to start.  I will keep an eye out for updates to this issue, hopefully I start getting some traction and can get comfortable with the library soon.

**Comment by GantMan** [comment]
additionally @darron-haworth  if you're a blogger, I'm prepared to spend some 1 on 1 time with you to give you the intro to changing the theme etc.    You could then blog the info, and we'll link to that in our docs.   We just got this idea when someone wrote a blog article about ignite, giving a nice intro.  We embrace community driven dev.  So there's opportunity if you're interested in a screen share.

**Comment by fvonhoven** [comment]
@darron-haworth Hey Darron,
I got the fix for you! About to PR it now!

**Comment by darron-haworth** [comment]
@fvonhoven, thank you much!  I've incorporated the changes in my local project.  I appreciate the quick fix and the heads up.  

@GantMan,  I am not a blogger but I still appreciate the offer. I am working my way through this and I think I will get there myself.  I just need to get familiar with things.
