### ISSUE TITLE
Add newly generated screen to screens/index.ts exports

### ISSUE THREAD

**Issue by fvonhoven** [infinitered/ignite#1609]
What's going on?

When generating a new screen with Ignite, the screen is not added to the exports in `screens/index.ts`

Steps to reproduce

1. Ignite a new project
2. `npx ignite-cli g screen NewlyGenerated`
3. Notice that the screen is not added to the exports in `screens/index.ts`

---

`ignite doctor` results:
N/A

**Comment by jamonholmgren** [comment]
Fixed with #1617
