### ISSUE TITLE
Add newly generated component to components/index.ts exports

### ISSUE THREAD

**Issue by fvonhoven** [infinitered/ignite#1610]
What's going on?

When generating a new component with Ignite, the component is not added to the exports in `components/index.ts`

Steps to reproduce

1. Ignite a new project
2. `npx ignite-cli g component NewlyGenerated`
3. Notice that the screen is not added to the exports in `components/index.ts`

---

`ignite doctor` results:
N/A

**Comment by jamonholmgren** [comment]
Fixed with #1617.

**Comment by fabtrompet** [comment]
I have the same problem, when creating model

![image](https://user-images.githubusercontent.com/6043140/111240723-85dab600-85da-11eb-8061-f9601bb2e3f4.png)

In 6.5.0 Version
