### ISSUE TITLE
Generating a new navigator creates a sibling folder to `navigation/`

### ISSUE THREAD

**Issue by fvonhoven** [infinitered/ignite#1611]
What's going on?

*  On first time generating a navigator creates a `navigators/newly-generated/navigator` folder and sub folder as a sibling to `/navigation` , is this desired?  
* Additionally, there is no index.ts in the newly created `navigators/` folder. 
* Perhaps make `navigators/` a child of `navigation/`? 

Seems a little confusing to have similarly named sibling folders.

Steps to reproduce

1. `npx ignite-cli g navigator MyNewNavigator`
2. Observe sibling folders `navigation/` & `navigators/`

Screenshot of folders:
![image](https://user-images.githubusercontent.com/10098988/108294041-b30e8280-715a-11eb-854a-f908d6317069.png)

---

`ignite doctor` results:
N/A

**Comment by jamonholmgren** [comment]
I think @kateinkim is working on something that might address this.
