### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by cjinghong** [infinitered/ignite#1616]
What's going on?

Receiving "error Command "format" not found." when creating new project using `npx ignite-cli new Donut`
<img width="1018" alt="Screenshot 2021-02-23 at 5 58 22 PM" src="https://user-images.githubusercontent.com/11567740/108827557-b98c7680-7600-11eb-90cc-0730bf2dab59.png">

---

Steps to reproduce

1. `npx ignite-cli new Donut`

---

`ignite doctor` results:
```
System
  platform           darwin
  arch               x64
  cpu                8 cores      Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  directory          donut        /Users/chanjinghong/Development/donut

JavaScript (and globally-installed packages)
  node                        15.8.0       /Users/chanjinghong/.nvm/versions/node/v15.8.0/bin/node
  npm                         7.5.1        /Users/chanjinghong/.nvm/versions/node/v15.8.0/bin/npm
    chromedriver              88.0.0
    create-react-app          4.0.2
    create-react-native-app   3.5.3
    firebase-tools            9.5.0
    npm                       7.5.1
    sequelize-cli             6.2.0
    yarn                      1.22.10
  yarn                        1.22.10      /Users/chanjinghong/.nvm/versions/node/v15.8.0/bin/yarn
    create-eth-app            1.6.2
    create-next-app           9.5.0
    create-react-app          3.4.1
    eslint                    5.16.0
    react-devtools            3.6.1
    serve                     11.3.0

Ignite
  ignite-cli         6.2.0        /Users/chanjinghong/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/chanjinghong/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               1.8.0_144    /usr/bin/java
  android home       -            /Users/chanjinghong/Library/Android/sdk

iOS
  xcode              12.4
  cocoapods          1.10.1       /usr/local/bin/pod
```

**Comment by cjinghong** [comment]
I've resolved the issue, please make sure you have the correct `react-native-cli` installed. 

Remove incorrect react-native-cli
`yarn global remove react-native-cli` or `npm uninstall -g react-native-cli`

Install the correct one
`yarn global add @react-native-community/cli` or `npm install -g @react-native-community/cli`

I think this should be mentioned in the docs somewhere.

**Comment by jamonholmgren** [comment]
@cjinghong Would you mind adding it to the docs via PR?

**Comment by jamesjara** [comment]
had the issue, it works, thanks

> I've resolved the issue, please make sure you have the correct `react-native-cli` installed.
> 
> Remove incorrect react-native-cli
> `yarn global remove react-native-cli` or `npm uninstall -g react-native-cli`
> 
> Install the correct one
> `yarn global add @react-native-community/cli` or `npm install -g @react-native-community/cli`
> 
> I think this should be mentioned in the docs somewhere.
