### ISSUE TITLE
Feature Request: Loading indicator for ignite cli

### ISSUE THREAD

**Issue by MichaelDimmitt** [infinitered/ignite#1619]
What's going on?

When the cli is running in a terminal it is working on the problem but there is no loading indicator to tell the developer to wait. This could lead the developer to assume that the process is in an infinate loop of some sort and will never finish causing them to kill the process and start again.

---

Steps to reproduce

1. npx ignite-cli new MyApp --expo

---

I made an initial attempt cloning the project locally and which was to run the cli with a dot printing for every second of inactivity. The final result looked like the following:

![run-with-dots-part1](https://user-images.githubusercontent.com/11463275/109172652-02ebdb80-7751-11eb-8d3c-30fddd0cdfc9.png)

**Comment by MichaelDimmitt** [comment]
Feel free to close, I just wanted to see if there was interest to have some form of loading spinner added to the project.

**Comment by jamonholmgren** [comment]
@MichaelDimmitt I'd love to have one, just haven't put the time in to add it! I like your idea!

There is the `print.spinner()` command available in Gluegun. I haven't looked at whether it makes sense to incorporate it

**Comment by MichaelDimmitt** [comment]
Thanks for the advice @jamonholmgren , 
I will take a look at print.spin and give draft pr's of both implementations.
If that sounds good.

**Comment by kateinkim** [comment]
Hey @MichaelDimmitt! Are you working on this or would it be okay if I picked it up? Thanks!

**Comment by MichaelDimmitt** [comment]
Sure @kateinkim 

eager to see what you come up with 🙂

**Comment by mazenchami** [comment]
@MichaelDimmitt just tested with the latest version (v6.12.2), Igniting a new app will show a loading spinner thanks to PR #1660 (thanks @kateinkim).

**Comment by MichaelDimmitt** [comment]
yes, looks good ! 

thanks @kateinkim
