### ISSUE TITLE
possible idea: ignite generate model ModelName

### ISSUE THREAD

**Issue by steve21124** [infinitered/ignite#162]
- [x ] ignite base application
- [x] ignite the cli
- [x] ignite generated code

so far in the documentation, it did not have Model generation. I kind of thinking similar to Rails where base on the fields name, it will automatically generate model, screen controller and api to local database or backend for save/update. 

do you think it is a good idea?

I think this one already been in roadmap version  1.1 (Gifted form, Realm etc.)

**Comment by GantMan** [comment]
I like this.   Let's flesh out the idea.

**Comment by steve21124** [comment]
so far here is the needs. 
1. Social Mobile App with backend integration
- need to retrieve json from backend and map to model and maybe child of the model
2. Survey Mobile App
- create a model, that map to local database and later can be sync to backend server
3. Dynamic Model Generation
- Given json and child relationship, automatically create model based on keys of the json.

In Rails=> rails generate model NAME [field[:type][:index] field[:type][:index]] 
I think we can follow the same thing too
ignite generate model NAME [field[:type][:index] field[:type][:index]] 

in Rails => rails generate scaffold HighScore game:string score:integer (this will create view, controller, assets, model, unit test, etc)

ignite  generate scaffold HighScore game:string score:integer
=> This will generate
- PageView (component/container/screen)
- Model
- Automatic integration with local db/ RealmDB

or anything that will make a job easier for standard mobile application

**Comment by steve21124** [comment]
What if, follow realm model api and extended it to other datastore or backend data. This might give advantages of having the model relationship done for free and extend the same api to async data store or backend

So far, from https://realm.io/news/introducing-realm-react-native/
ignite generator model Dog name:string age:int
<pre>
class Dog {}
Dog.schema = {
    name: 'Dog',
    properties: {
        name: 'string',
        age: 'int',
    }
};
</pre>
ignite generator model Person name:string dogs:list[Dog]
<pre>
class Person {}
Person.schema = {
    name: 'string',
    dogs: {type: 'list', objectType: 'Dog'},
};

</pre>

**Comment by skellock** [comment]
This becomes very possible with plugins in 2.0.  You can make a generator plugin now.
