### ISSUE TITLE
Storybook not working as stated in home screen

### ISSUE THREAD

**Issue by tyler-jewell** [infinitered/ignite#1620]
After following instructions verbatim on install and starting app with npm start, I see the following instructions on the home screen:

![image](https://user-images.githubusercontent.com/72859335/109402239-c7e8d400-7919-11eb-8d99-018ffe3ab2bb.png)

After opening settings, I do not see "Toggle Storybook"

![image](https://user-images.githubusercontent.com/72859335/109402251-f23a9180-7919-11eb-885a-f2eec64687b5.png)

Steps to reproduce:

```
npx ignite-cli new PizzaApp --expo
npm start
```

1. install react-native expo w/ 
2. Start expo app with 
3. Choosing 'i' for iPhone simulator
4. CMD-D for settings

---

`ignite doctor` results:

```
System
  platform           darwin                                            
  arch               x64                                               
  cpu                8 cores      Apple M1                             
  directory          OneTappApp   /Users/tylerjewell/github/OneTappApp 

JavaScript
  node               14.15.1      /usr/local/bin/node 
  npm                7.5.6        /usr/local/bin/npm  
  yarn               1.22.10      /usr/local/bin/yarn 

Ignite
  ignite-cli         3.5.3        /usr/local/bin/ignite                                                
  ignite src         build        /Users/tylerjewell/.config/yarn/global/node_modules/ignite-cli/build 
  generators                                                                                           

Android
  java               1.8.0_281    /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              12.4       
  cocoapods          1.10.0       /usr/local/bin/pod 
```

Update 1:

After some minor debugging - I have found the main issue to be with the DevSettings.addMenuItem function. This doesn't seem to run the function. The useEffect is running but not entering DevSettings.addMenuItem

```
// Add our toggle command to the menu
DevSettings.addMenuItem("Toggle Storybook", () => {
  setShowStorybook((show) => {
    // On toggle, flip the current value
    show = !show

    // Write it back to storage
    saveString("devStorybook", show ? "on" : "off")

    // Return it to change the local state
    return show
  })
})
```

**Comment by jamonholmgren** [comment]
I think Expo doesn't use that function and might use its own dev menu function. I haven't dug into it to see if it does. Help on this would be appreciated!

**Comment by JimmyLv** [comment]
Oh, how to fix this issue? @tyler-jewell :(

**Comment by tmpg** [comment]
I am using Expo and I am also having his issue.

**Comment by velociwabbit** [comment]
I have just tested it with the web display and it comes up with "To run storybook press undefined ...." . The storybook instance runs stand alone, but i was hoping to look at the components on the web. 

Is there another way to access them or a location that shows all of them online?

If you give me a pointer or two I can humbly try to glue everything together.

Also there is a cors issue with example.com (which is very funny imho) I assume that you all know about that?

**Comment by tyler-jewell** [comment]
Not really a fix, but what I am doing now is creating a "screen" of the storybook and putting it in my side navigation drawer. That way it's hidden from the main UI, and I can toggle back and forth.

**Comment by JimmyLv** [comment]
> Not really a fix, but what I am doing now is creating a "screen" of the storybook and putting it in my side navigation drawer. That way it's hidden from the main UI, and I can toggle back and forth.

It sounds like a workaround way, but could you please help to provide the code example? Thanks a lot! @tyler-jewell

**Comment by suerta-git** [comment]
is there some guys can tell me for now how to enter the storybook?

**Comment by tran2** [comment]
My temporary work around and somewhat manual is in toggle-storybook.tsx I added this line in the useEffect hook right above the  `DevSettings.addMenuItem("Toggle Storybook",` line 
```
saveString("devStorybook", "on")
```
Then reload the app. Storybook should show up instead of the original app.

**Comment by sergioisidoro** [comment]
> I think Expo doesn't use that function and might use its own dev menu function.

It doesn't seem like the easiest thing to implement:
https://docs.expo.dev/development/extending-the-dev-menu/

**Comment by sergioisidoro** [comment]
I tried to make Reactotron work with storybook toggle, since making custom menus is difficult. 

Enabling Storybook with a reactotron custom command is easy, but because Storybook renders instead of the RootStore (i think), reactotron doesn't work inside storybook (?) At least I'm getting:
```
Unhandled promise rejection, [RangeError: Maximum call stack size exceeded.]
at node_modules/core-js/internals/host-report-errors.js:5:32 in module.exports
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:255352:138 in dispatchEvent
at node_modules/core-js/modules/es.promise.js:170:23 in perform$argument_0
at node_modules/core-js/internals/perform.js:3:20 in module.exports
at node_modules/core-js/modules/es.promise.js:167:22 in call$argument_2
```

Any help appreciated

**Comment by dannyhw** [comment]
Well I guess in this case detecting expo and changing the text might be the solution. Since the issue itself is because of how the dev-menu can't be changed easily on expo (only possible with eas dev clients).

The solution is to use reactotron to toggle storybook or other similar solutions stated in this issue. I find the easiest way is to have a json config file with a showStorybook value which makes it easy to change with a script etc.

If reactotron doesn't work with storybook that could be because of the [promise issue](https://github.com/infinitered/ignite/pull/1863#issuecomment-1047133771) or maybe could be related to storybook websockets. You can disable the websockets for react native storybook via the config and see if it changes anything.

**Comment by yulolimum** [comment]
Our team has decided to move away from Storybook altogether. We will be removing it in [Ignite v8: Maverick](https://github.com/infinitered/ignite/milestone/19). Meanwhile, if reliability is still an issue, the simplest "cross-platform"/"cross-framework" solution is to mount `<StorybookUIRoot/>` directly as part of a navigation screen (this should work in vanilla/expo, mobile/web) as @tyler-jewell suggested. Take a look at the documentation found towards the end of this page (note, most of the "getting-started" instructions are already configured in ignite): https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/

![yulolimum-capture-2022-08-15--17-50-38@2x](https://user-images.githubusercontent.com/1775841/184763015-efa7caaa-5608-40ac-a01e-7c9d5444889a.jpg)
