### ISSUE TITLE
Storybook UI not working on fresh install

### ISSUE THREAD

**Issue by jascination** [infinitered/ignite#1622]
On a fresh install, I'm trying to load storybook

In the app (opening developer menu => toggle storybook) it works fine. However, when I run `yarn storybook` and go to `http://localhost:9001/` , I just see the following (the left menu has a spinning loader when I hover over it)

![image](https://user-images.githubusercontent.com/2121331/109593568-4dac8f80-7b65-11eb-8d52-3910a297c8e8.png)

Ignite doctor shows:

```
System
  platform           darwin
  arch               x64
  cpu                8 cores      Apple M1
  directory          test    /Users/user/Sites/test

JavaScript (and globally-installed packages)
  node                              14.15.5      /Users/user/.nvm/versions/node/v14.15.5/bin/node
  npm                               7.5.0        /opt/homebrew/bin/npm
    eslint                          7.17.0
    expo-cli                        4.2.1
    firebase-tools                  9.1.2
    generator-react-native-ignite   1.13.0
    ignite-cli                      6.2.0
    netlify-cli                     2.71.0
    npm                             7.5.0
    react-native-cli                2.0.1
    react-native-ignite             1.13.0
    serverless                      2.25.2
    yarn                            1.22.10
    yo                              3.1.1
  yarn                              1.22.10      /opt/homebrew/bin/yarn

Ignite
  ignite-cli         6.2.0        /opt/homebrew/bin/ignite
  ignite src         build        /opt/homebrew/lib/node_modules/ignite-cli/build

Android
  java               1.8.0_282    /usr/bin/java
  android home       -            undefined

iOS
  xcode              12.4
  cocoapods          1.10.1       /usr/local/bin/pod
  ```

**Comment by jamonholmgren** [comment]
Confirmed on my Mac too.
![image](https://user-images.githubusercontent.com/1479215/111045057-e7dfc380-8400-11eb-903c-05d908f7d3bc.png)

```
❯ npx ignite-cli doctor
System
  platform           darwin                                                
  arch               x64                                                   
  cpu                16 cores     Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz 
  directory          Issue1622    /Users/jh/Code/Temp/Issue1622            

JavaScript (and globally-installed packages)
  node                14.15.3      /usr/local/bin/node 
  npm                 6.14.9       /usr/local/bin/npm  
    appium            1.17.1                           
    appium-doctor     1.15.3                           
    expo-cli          4.0.12                           
    ignite-cli        6.1.1                            
    npm               6.14.9                           
    pure-prompt       1.11.0                           
  yarn                1.22.10      /usr/local/bin/yarn 
    create-next-app   9.4.4                            
    detox-cli         17.11.0                          
    expo-cli          4.3.0                            
    firebase-tools    9.3.0                            
    ios-deploy        1.11.4                           
    pod-install       0.1.14                           
    ts-node           8.8.2                            
    typescript        3.8.2                            
    vercel            19.1.1                           

Ignite
  ignite-cli         6.4.0        /Users/jh/.npm/_npx/53403/bin/ignite                        
  ignite src         build        /Users/jh/.npm/_npx/53403/lib/node_modules/ignite-cli/build 

Android
  java               1.8.0_232    /usr/bin/java                 
  android home       -            /Users/jh/Library/Android/sdk 

iOS
  xcode              12.4       
  cocoapods          1.10.1       /usr/local/bin/pod 
```

**Comment by bmeverett** [comment]
Is this actually an issue? There is a blurb on that screen that says stories won't load unless you're running the device too.

```
Note that due to an implementation detail, your stories will only show up in the left-pane after your device has connected to this storybook server
```

**Comment by jamonholmgren** [comment]
@bmeverett Good call, I missed that too. 🤦 

Doesn't look like it's our issue after all. They should add that note to the left pane though.

**Comment by ilovepku** [comment]
My stories won't load with `yarn storybook` even if I'm also running storybook simultaneously on my Android devices (both emulator and physical).

System
  platform           linux                                                   
  arch               x64                                                     
  cpu                12 cores        Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 
  directory          IgniteDemoApp   /home/xli/repos/IgniteDemoApp           

JavaScript (and globally-installed packages)
  node                    14.16.1      /usr/bin/node 
  npm                     7.11.1       /usr/bin/npm  
    detox-cli             18.0.0                     
    expo-cli              4.4.3                      
    ignite-cli            6.9.0                      
    npm                   7.11.1                     
    source-map-explorer   2.5.2                      
    yarn                  1.22.10                    
  yarn                    1.22.10      /usr/bin/yarn 
    expo-cli              4.4.3                      
    ignite-cli            6.9.0                      

Ignite
  ignite-cli         6.9.0        /usr/bin/ignite                        
  ignite src         build        /usr/lib/node_modules/ignite-cli/build 

Android
  java               1.8.0_242-release   /usr/local/android-studio/jre/bin/java 
  android home       -                   /home/xli/Android/Sdk
