### ISSUE TITLE
again unable to make ignite app :(

### ISSUE THREAD

**Issue by CodeBunny786** [infinitered/ignite#1623]
un able to create app using ignite :(

---

Steps to reproduce

1. npx ignite-cli new PizzaApp

---

`ignite doctor` results:
apple@Apples-MacBook-Pro desktop % ignite doctor          
System
  platform           darwin                                                 
  arch               x64                                                    
  cpu                8 cores      Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz 
  directory          Desktop      /Users/apple/Desktop                      

JavaScript
  node               10.16.3      /usr/local/bin/node 
  npm                6.9.0        /usr/local/bin/npm  
  yarn               1.9.4        /usr/local/bin/yarn 

Ignite
  ignite-cli         3.5.1        /usr/local/bin/ignite                                          
  ignite src         build        /Users/apple/.config/yarn/global/node_modules/ignite-cli/build 
  generators         {}                                                                          

Android
  java               1.8.0_201    /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              12.2       
  cocoapods          1.10.1       /usr/local/bin/pod 
apple@Apples-MacBook-Pro desktop %

**Comment by CodeBunny786** [comment]
please help

**Comment by CodeBunny786** [comment]
![Uploading Screenshot 2021-03-03 at 2.36.46 PM.png…]()

**Comment by bwnstck** [comment]
I solved this issue by 
- installing yarn `$ npm -g yarn`
- and setting up my git user.name and user.email `$ git config --global user.name ¨First Last¨`
