### ISSUE TITLE
Strange screen-flash animation when navigating on Android Expo

### ISSUE THREAD

**Issue by jascination** [infinitered/ignite#1627]
Fresh install of the latest client + expo, I'm using Android and Expo Go.

When I navigate from screen to screen just using your demo setup (complete fresh install), I get very strange flashes. Attached a video to show it.

I don't get this when I use the IOS simulator for the same project.

https://user-images.githubusercontent.com/2121331/110413142-78589400-80e1-11eb-9f9e-70b32dbfe036.mp4

```

System
  platform           darwin
  arch               arm64
  cpu                8 cores      Apple M1
  directory          name        ~/Sites/name

JavaScript (and globally-installed packages)
  node               15.9.0       ~/.nvm/versions/node/v15.9.0/bin/node
  npm                7.6.1        ~/.nvm/versions/node/v15.9.0/bin/npm
    npm              7.6.1
    yarn             1.22.10
  yarn               1.22.10      ~/.nvm/versions/node/v15.9.0/bin/yarn

Ignite
  ignite-cli         6.2.0        ~/.npm-packages/bin/ignite
  ignite src         build        ~/.npm-packages/lib/node_modules/ignite-cli/build

Android
  java               1.8.0_282    /usr/bin/java
  android home       -            undefined

iOS
  xcode              12.4
  cocoapods          1.10.1       /usr/local/bin/pod  
```

**Comment by jamonholmgren** [comment]
That is odd. Do you think this is a React Navigation issue?

**Comment by cihanbas** [comment]
i think it is background image problem, can you remove the background image and try it again?

**Comment by Tj3n** [comment]
Not just Android, iOS is also having this whenever I try to use `Wallpaper`

**Comment by khilnani** [comment]
+1 I see this on iOS as well.

Seems to be related to debug mode perhaps - When in install to my device I see the flicker when metro is running. If i do not use metro / kill metro, i see no flickering

**Comment by calendee** [comment]
It happens on the iOS simulator too. This is generally not seen on higher end devices (along with many other transition artifacts) because the device is so fast compared to the simulator and running a production build.

I have a fix for it that I'll PR in a bit. I'm just waiting to reinstall all of Android SDK so I can test the fix on the Android emulator.

https://user-images.githubusercontent.com/57374/116868427-645a7b80-abd4-11eb-9b87-ddc05b30d80a.mp4

**Comment by JayPerfetto** [comment]
This issue still persists, I've opened a new issue for it

**Comment by jamonholmgren** [comment]
#1755
