### ISSUE TITLE
Moving to Mobx Keystone

### ISSUE THREAD

**Issue by maccman** [infinitered/ignite#1628]
I highly recommend you guys consider moving to Mobx Keystone, the successor in many ways to mobx-state-tree.

https://mobx-keystone.js.org/

Keystone is built by one of the maintainers of MST and is much more Typescript 'native' - it solves many of the problems with mst around types.

**Comment by jamonholmgren** [comment]
Hey @maccman!

I'm the primary maintainer of Ignite as well as MobX-State-Tree, so admittedly I'm a bit biased.

I've been keeping an eye on MobX-Keystone and I appreciate the efforts being made over there.

I think overall we're still pretty happy with our experience around MST. The TypeScript types are not nearly as much of an issue as back when MobX-Keystone was first made, and I think the API makes more sense to us than Keystone's class-based approach.

But of course, decisions are always up for revisiting later. I appreciate you bringing it up!

**Comment by jamonholmgren** [comment]
FYI @maccman we are evaluating MobX-Keystone and may try it in a new project soon.

**Comment by dzcpy** [comment]
mobx-keystone is pretty awesome. IMO it's a bit simpler to use than MST. But anyway both of the two are great libraries. Maybe we can add two options and make it work like Nuxt.js

**Comment by maccman** [comment]
I think the typescript support is what convinced me.
