### ISSUE TITLE
Possible addition: Adding gradient background color

### ISSUE THREAD

**Issue by steve21124** [infinitered/ignite#163]
- [x ] ignite base application

not sure if it is good or not, the current theme a little bit plain. I have testing out adding gradient to the current ignite
https://github.com/brentvatne/react-native-linear-gradient

This gradient color might give attractive background. 
![alt text](http://i.imgur.com/THUS32B.png)

**Comment by GantMan** [comment]
Hey Steve!   
So couple things.   Yes, we love that gradient tool too! :)

Now that we've got version 1.0, we're going to start moving non-essential tools to add ons.   The philosophy will be this:

User wants gradients.
`ignite add gradient`

The generator would then add the library, link it up, and then add an example to usage example screen IF it exists.

Thoughts?

**Comment by steve21124** [comment]
as far as right now, I am not sure yet what will be the best approach in adding the gradient. since gradient  can be in button, it can be in view, it can be toolbar. ..... or it is just simple adding gradient or gradient with its own custom parameters. may be with 

ignite add gradient .. param1, param2, param3  => let the custom library  of gradient dicide what to do with the parameters
ignite add customLibrary param1, param2, param3, param4==>  let the custom library  dicide what to do with the parameters

**Comment by GantMan** [comment]
I might make this, and record it so we can make a quick video explaining.  That way future contributors could follow.

**Comment by fvonhoven** [comment]
Sounds good to me

**Comment by steve21124** [comment]
after looking at the trend. seems like diffuse background is the trend of 2016
https://github.com/react-native-fellowship/react-native-blur

![alt text](http://us.123rf.com/450wm/avgust01/avgust011405/avgust01140500004/28905303-abstract-background-blur-diffuse-image-template-with-label-separate-from-background-landscape-with-t.jpg "Logo Title Text 1")

**Comment by steve21124** [comment]
just finished integrating the blur background. though somehow the text is not displaying...
![alt text](http://s33.postimg.org/mcs854t1b/Screen_Shot_2016_06_12_at_7_08_52_PM.png "Logo Title Text 1")

**Comment by fvonhoven** [comment]
@Skellock get with me on this tomorrow. I have the fix for you

**Comment by fvonhoven** [comment]
@steve21124 You'll need to wrap your `BlurView` in a `View`, then lay the `Image` element as a background Image like this...
```
<View style={{height: Metrics.screenHeight, width: Metrics.screenWidth}}>
  <Image
    source={{uri: 'https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg'}}
    style={{top: 0, left: 0, right: 0, bottom: 0, position: 'absolute'}}
  />
  <BlurView blurType="light" style={styles.blur}>
    <Text>Hi, I am a tiny menu item</Text>
  </BlurView>
</View>

**Comment by GantMan** [comment]
hahaha, I was gonna use a diffused background for my original ignite design!  YOU HEAR THAT @justinhuskey , I can design things!

Looking good @steve21124

**Comment by steve21124** [comment]
```html
				<View style={{height: Metrics.screenHeight, width: Metrics.screenWidth}}>
				  <Image
				    source={{uri: 'https://s-media-cache-ak0.pinimg.com/236x/d5/51/19/d5511900b5fc0c0a5d3b97719b5863a7.jpg'}}
				    style={{top: 0, left: 0, right: 0, bottom: 0, position: 'absolute'}}
				  />
				  <BlurView blurType="light" style={styles.blur}>
				    <Text style={{color: 'white'}}>Hi, I am a tiny menu item</Text>
				  </BlurView>
				</View>
```
above code also only give images


```html
				<View style={{flex: 1,justifyContent: 'center', alignItems: 'center'}}>
				  <Image
				    source={{uri: 'https://s-media-cache-ak0.pinimg.com/236x/d5/51/19/d5511900b5fc0c0a5d3b97719b5863a7.jpg'}}
				    style={{top: 0, left: 0, right: 0, bottom: 0, position: 'absolute'}}
				  />
				  <BlurView blurType="light" style={styles.blur}>
				    <Text style={{color: 'white'}}>Hi, I am a tiny menu item</Text>
				  </BlurView>
				</View>
```
above code give below images
![alt text](http://s33.postimg.org/yzy0rz8u7/Screen_Shot_2016_06_12_at_9_03_18_PM.png "Logo Title Text 1")


https://gist.github.com/steve21124/cf1238ad7fb675db3cc5f66d646e1d55

**Comment by steve21124** [comment]
Here is the final solution
```html
				<View style={{flex: 1,justifyContent: 'center', alignItems: 'center'}}>
				  <Image
				    source={{uri: 'https://s-media-cache-ak0.pinimg.com/236x/d5/51/19/d5511900b5fc0c0a5d3b97719b5863a7.jpg'}}
				    style={{top: 0, left: 0, right: 0, bottom: 0, position: 'absolute'}}
				  />
				  <BlurView blurType="light" style={{height: Metrics.screenHeight, width: Metrics.screenWidth,flex: 1,justifyContent: 'center', alignItems: 'center'}}>
				    <Text style={{color: 'white'}}>Hi, I am a tiny menu item</Text>
				  </BlurView>
				</View>
```
![alt text](http://s33.postimg.org/je23b4jun/Screen_Shot_2016_06_12_at_9_14_42_PM.png "Logo Title Text 1")

**Comment by skellock** [comment]
This looks great.  Plugins are a new feature in 2.0 and these types of components fit right in there.
