### ISSUE TITLE
Detect when `ignite new` would overwrite a folder and fail unless `--overwrite` is provided

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1632]
When running `ignite new Foo`, if there's already a `Foo` folder, Ignite will either fail (in the case of `--expo`) or just skip past the `react-native init` process (when not using Expo).

We should error with something like:

```
Error: There's already a folder with the name "Foo". To force overwriting that folder, run with `--overwrite`.
```

If they run it with `--overwrite`, we should delete any existing folder with that name.

**Comment by mazenchami** [comment]
Closing this issue as since v6.11.0 (currently on v6.12.2), this feature is available. Example: `npx ignite-cli new PizzaApp --overwrite)
