### ISSUE TITLE
App.tsx ESLint/Prettier problem

### ISSUE THREAD

**Issue by Tj3n** [infinitered/ignite#1633]
What's going on?

New generated project have file `app.tsx` error line 53.
I have to add `"no-extra-semi": "off", "@typescript-eslint/no-extra-semi": 0` to `package.json` to mute it, looking for another solution.

---

Steps to reproduce

1. Generate new project with `--expo`
2. In `app.tsx` file line 53: `;(async () => {` have error by `@typescript-eslint/no-extra-semi`

---

`ignite doctor` results:
```
System
  platform           darwin                                                             
  arch               x64                                                                
  cpu                4 cores          Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz          
  directory          MyApp

JavaScript (and globally-installed packages)
  node               14.2.0       /usr/local/bin/node 
  npm                6.14.4       /usr/local/bin/npm  
    expo-cli         4.3.0                            
    ignite-cli       6.5.0                            
    ios-deploy       1.10.0                           
    npm              6.14.4                           
  yarn               1.22.4       /usr/local/bin/yarn 
    eslint           7.0.0                            
    react-devtools   3.6.3                            

Ignite
  ignite-cli         6.5.0        /usr/local/bin/ignite                        
  ignite src         build        /usr/local/lib/node_modules/ignite-cli/build 

Android
  java               12.0.2       /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              12.4       
  cocoapods          1.9.3        /usr/local/bin/pod

**Comment by nonameolsson** [comment]
I can confirm this.

**Comment by mazenchami** [comment]
@nonameolsson thank you for providing the solution. I can confirm that both solutions fixed the issue–I personally prefer Solution 2. To answer your question, I don't see any reason why some functionality would be lost by this refactor.

@Tj3n can you confirm that either of these solutions fixed the issue for you without having to mute the error?

**Comment by Tj3n** [comment]
It's fixed, I'm closing this. Thanks!
