### ISSUE TITLE
support react native 0.64.0, please 

### ISSUE THREAD

**Issue by stfenjobs** [infinitered/ignite#1634]
react-native has been released 0.64.0 https://github.com/facebook/react-native/releases

please support react native 0.64.0

thank you very much

**Comment by stfenjobs** [comment]
https://github.com/infinitered/ignite/pull/1641

**Comment by nirre7** [comment]
The ignite boilerplate has been updated to React Native 0.64.0.
However there is regression issues with the above mentioned version so I would hold of upgrading production app atm.
We will updated Ignite as soon as RN 0.64.1 releases.
