### ISSUE TITLE
[Gen] - Listview Generator

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#164]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

#### officially requesting a listview generator
`ignite g listview HotDates`
creates new screen with listview best practices and steps to configure.

### :star2: BONUS POINTS 🌟 
1. Generator makes a custom component for your cell
2. Generator asks you if you'd like to make a grid
3. Generator asks you if you'd like sticky headers or not
4. Pull to Refresh included as well
5. Searchable lists would be awesome, too
6. Infinite scroll?

**Comment by GantMan** [comment]
Gridview should be easy:  https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ListViewGridLayoutExample.js

**Comment by steve21124** [comment]
what do you think the advantages of using react native easy grid here?
https://github.com/GeekyAnts/react-native-easy-grid

on another note, is it make sense to integrate native base with ignite?
https://github.com/GeekyAnts/NativeBase

I try to implement,  given all json parameters, it will dynamically create the layout that I wanted.
do you know what library do I need to look for?

**Comment by GantMan** [comment]
I would like to look into NativeBase at some point.   We'll have to see.   I'm especially open when we get more optional setups involved.

**Comment by GantMan** [comment]
I think we should move infinite scroll / searchable lists to a separate ticket.

I do think pull to refresh should still be on here, though.

**Comment by tleduc-km** [comment]
I tried it and got this issue at the launch :
```sh
TypeError: this.env.adapter.prompt(...).then is not a function
```

**Comment by GantMan** [comment]
ah yes, thanks for the heads up.   This definitely requires a certain version of `yo` to be global.   I might have to check that on run.   It's always strange enforcing globals.
