### ISSUE TITLE
 TypeError: o is not a function

### ISSUE THREAD

**Issue by xforcarlos** [infinitered/ignite#1646]
What's going on?
error when create  app with ignite and i don't know how to follow this error  in debug mode only 
app working fine in release
---
![Screen Shot 2021-03-30 at 12 58 45 PM](https://user-images.githubusercontent.com/76874617/112978988-4a062b80-9158-11eb-9de5-36890a75a5cb.png)
```
ExceptionsManager.js:179 TypeError: o is not a function
    at r (index.js:1)
    at EventTarget.a (index.js:1)
    at EventTarget.dispatchEvent (event-target-shim.js:818)
    at EventTarget._setReadyState (FileReader.js:80)
    at FileReader.js:130
    at es.promise.js:114
    at flush (microtask.js:26)
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:274
```

Steps to reproduce

1. init new app with npx ignite-cli new PizzaApp

---

`ignite doctor` results:
```
System
  platform           darwin                                                           
  arch               x64                                                              
  cpu                12 cores       Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz          
  directory          OurEducation   /Users/mahmoudhamdy/Desktop/work/our/OurEducation 

JavaScript (and globally-installed packages)
  node               15.5.1       /usr/local/bin/node 
  npm                7.3.0        /usr/local/bin/npm  
    axios            0.21.1                           
    detox-cli        18.0.0                           
    ignite-cli       6.6.0                            
    ios-deploy       1.11.3                           
    npm              7.3.0                            
    osmi-cli         1.2.0                            
    pod-install      0.1.18                           
  yarn               -            not installed       

Ignite
  ignite-cli         6.6.0        /usr/local/bin/ignite                        
  ignite src         build        /usr/local/lib/node_modules/ignite-cli/build 

Android
  java               1.8.0_282    /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              12.3       
  cocoapods          1.10.1       /usr/local/bin/pod ```

**Comment by Tj3n** [comment]
Also getting this issue.

**Comment by pascal-mormin** [comment]
Apparently, it is a bug from Reactotron-react-native, but issue is still not resolved.

[https://github.com/infinitered/reactotron-react-native/issues/768](url)

**Comment by mazenchami** [comment]
@xforcarlos I was able to run an app (expo also) with the latest version of Ignite (v6.12.2) without running into any issues. Can you please use the latest version for Ignite (v6.12.2) and confirm if this is still happening for you?

**Comment by JeroenGoddijn** [comment]
Just restart the metro-server and the app will reload and error will be gone.... but I agree it is very annoying.

**Comment by MonsterAnan** [comment]
Also getting this issue.

**Comment by jamonholmgren** [comment]
Still looking into this -- it does look like it's an issue with Reactotron.

https://github.com/infinitered/reactotron-react-native/issues/768

**Comment by xforcarlos** [comment]
@mazenchami  it still exist

**Comment by xforcarlos** [comment]
@jamonholmgren  thanks man & good luck

**Comment by joshuayoes** [comment]
There has been a lot of changes since this issue last had activity. This is going to be closed for now, but please re-open if this still needs attention.
