### ISSUE TITLE
Unrecognized font family 

### ISSUE THREAD

**Issue by mustafauyysl** [infinitered/ignite#1651]
I use custom font (Montserrat) on my project with expo. I put all tff files in theme/fonts and index.ts in this folder is
```
  import * as Font from "expo-font"
  
  export const initFonts = async () => {
    await Font.loadAsync({
      Montserrat: require("./Montserrat-Regular.ttf"),
    })
  }
```

But ı alwasy see "Unrecognized font family" error. I upgrade expo-cli and expo font but it did not work.

**Comment by adamjw3** [comment]
@mustafauyysl how did you fix this?
