### ISSUE TITLE
[IOS].Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by tunm1228** [infinitered/ignite#1653]
What's going on?

---/***/ios/Pods/OpenSSL-Universal/Frameworks/OpenSSL.xcframework/." failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code

Steps to reproduce

1.Run the CLI: npx ignite-cli new PizzaApp

---

`ignite doctor` results:

**Comment by ugglr** [comment]
this is a problem which is inherited by react native 0.64, there are several issues in that repo, I think the one with the most comments is this one: https://github.com/facebook/react-native/issues/31275

**Comment by nirre7** [comment]
Yepp, there are multiple regression issues in RN 0.64.0.
We'll update to RN 0.64.1 as soon as it gets released.

**Comment by ugglr** [comment]
I could actually solve my problem in a bare RN project by re-installing nvm and then reinstalling all dependancies in the project.

**Rough steps:**

**installing nvm in their official repo:**
https://github.com/nvm-sh/nvm

**Then I reinstalled node:**
nvm install node && nvm alias default node

**Then I deleted the following things from my project:**
- node_modules
- lock file (yarn.lock in my case)
- ios/Pods
- ios/Podfile.lock

Then I reinstalled node_modules

Then `cd ios` -> `pod install --repo-update`

Finally I could go and start the simulator as normal `npx react-native run-ios`

**Comment by jamonholmgren** [comment]
#2214 may fix this as well.
