### ISSUE TITLE
npx ignite-cli new PizzaApp --> gluegun/build/index.js:13 throw up;

### ISSUE THREAD

**Issue by tdautreme** [infinitered/ignite#1655]
What's going on?

Can't create ignite project on windows, same as https://github.com/infinitered/gluegun/issues/735
C:\Users\timda\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\gluegun\build\index.js:13
    throw up;
    ^

TypeError: Cannot read property 'replace' of undefined
    at C:\Users\timda\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build\commands\new.js:137:26    at step (C:\Users\timda\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build\commands\new.js:44:23)
    at Object.next (C:\Users\timda\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build\commands\new.js:25:53)
    at fulfilled (C:\Users\timda\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build\commands\new.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Steps to reproduce

1.

npx ignite-cli new PizzaApp

`ignite doctor` results:
C:\Users\timda\Desktop\Projets\React native\shopping lists>npx ignite-cli doctor
System
  platform           win32
  arch               x64
  cpu                12 cores         Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  directory          shopping lists   C:\Users\timda\Desktop\Projets\React native\shopping lists

JavaScript (and globally-installed packages)
  node               12.18.3      C:\Program Files\nodejs\node.EXE
  npm                7.0.10       C:\Program Files\nodejs\npm.CMD
    npm              7.0.10
  yarn               1.22.10      C:\Users\timda\AppData\Roaming\npm\yarn.CMD

Ignite
  ignite-cli         6.7.0        C:\Users\timda\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\timda\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               1.8.0_281    C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\timda\AppData\Local\Android\Sdk

**Comment by elam76** [comment]
Same issue on Ubuntu 20.04

>ignite-cli new PizzaApp
   

   · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

    █ Creating PizzaApp using Ignite 6.8.0
    █ Powered by Infinite Red - https://infinite.red
    █ Using react-native-cli
    ────────────────────────────────────────────────

   🔥 Igniting app
   🧊 Cooling print nozzles
   ☕️ Baking CocoaPods

/home/abc/.config/yarn/global/node_modules/gluegun/build/index.js:13
    throw up;
    ^
yarn run v1.22.4
warning ../../../package.json: No license field
error Command "format" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


> ignite doctor
System
  platform           linux                                                  
  arch               x64                                                    
  cpu                8 cores      Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz 
  directory          moblie       /home/abc/projects/moblie        

JavaScript (and globally-installed packages)
  node                                 15.14.0        /usr/local/bin/node       
  npm                                  7.9.0          /usr/local/bin/npm        
    @google-cloud/functions-emulator   1.0.0-beta.6                             
    express-generator                  4.16.0                                   
    jslint                             0.12.1                                   
    n                                  6.5.1                                    
    npm                                7.9.0                                    
    react-native-cli                   2.0.1                                    
    yarn                               1.22.10                                  
  yarn                                 1.22.4         /home/abc/.yarn/bin/yarn 
    create-react-app                   3.4.1                                    
    express-generator                  4.16.0                                   
    forever                            1.0.0                                    
    ignite-cli                         6.8.0                                    
    serve                              11.3.2                                   
    storybook                          1.0.0                                    
    typescript                         3.5.3                                    

Ignite
  ignite-cli         6.8.0        /home/abc/.yarn/bin/ignite                                  
  ignite src         build        /home/abc/.config/yarn/global/node_modules/ignite-cli/build 

Android
  java               11.0.10      /usr/bin/java          
  android home       -            /home/abc/Android/Sdk

**Comment by nirre7** [comment]
Hi.

Try to remove **react-native-cli** from your global installs, the version you have installed is very old. 
Hope it helps.

**Comment by elam76** [comment]
> Hi.
> 
> @elam76 Try to remove **react-native-cli** from your global installs, the version you have installed is very old.
> @tdautreme You could also try using [nvm](https://github.com/nvm-sh/nvm) for getting a NodeJS LTS version with no global installs and try again.
> 
> Hope it helps.

Thanks, removing **react-native-cli** from your global installs fixed this issue!

**Comment by humarkx** [comment]
> Hi.
> 
> @elam76 Try to remove **react-native-cli** from your global installs, the version you have installed is very old.
> @tdautreme You could also try using [nvm](https://github.com/nvm-sh/nvm) for getting a NodeJS LTS version with no global installs and try again.
> 
> Hope it helps.

This solution didn't work for me on Apple M1.

**Comment by nirre7** [comment]
@humarkx try this https://amanhimself.dev/blog/setup-macbook-m1/

**Comment by maqeelqureshi** [comment]
Facing dependency issue while creating new PizzaApp

```
C:\Users\Dev Aadi\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\gluegun\build\index.js:13
    throw up;
    ^
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: pizza-app-6@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0" from @react-native-community/masked-view@0.1.10
npm ERR! node_modules/@react-native-community/masked-view
npm ERR!   @react-native-community/masked-view@"0.1.10" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Dev Aadi\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev Aadi\AppData\Local\npm-cache\_logs\2021-06-04T19_36_21_710Z-debug.log

(Use node --trace-uncaught ... to show where the exception was thrown)

```

**Comment by varora1406** [comment]
Facing same issue with 7.0.3
Even without global installs of react-native-cli

**Comment by chaudhryjunaid** [comment]
facing same issue with 7.0.8 on macbook m1
