### ISSUE TITLE
Missing documentation , how to use SVG files ?

### ISSUE THREAD

**Issue by nutrimax1987** [infinitered/ignite#1662]
What's going on?
I have a lot of assets with svg format , Need to config it , no access to metro.config.js , how to do that ?
I'm using next libraries :  react-native-svg ,  react-native-svg-transformer .

**Comment by nirre7** [comment]
Hi.

Add a `metro.config.js`.
We are using svg's and a chart lib that used svg's and the libraries you mentioned, with no issues.

Hope it helps.

**Comment by PtrLarsson** [comment]
> What's going on?
> I have a lot of assets with svg format , Need to config it , no access to metro.config.js , how to do that ?
> I'm using next libraries : react-native-svg , react-native-svg-transformer .

Hello here is a more detailed guide on the topic:
https://blog.usejournal.com/how-to-use-svg-in-react-native-e581eca59534

**Comment by jamonholmgren** [comment]
A good place to ask these questions is [our Slack community](https://community.infinite.red). Check out the #react-native and #ignite channels there. Thanks for using Ignite!
