### ISSUE TITLE
Adding a test above that just maybe waits for the UI of the app being inserted into the Expo app come into view helps:

### ISSUE THREAD

**Issue by rashd640** [infinitered/ignite#1664]
Adding a test above that just maybe waits for the UI of the app being inserted into the Expo app come into view helps:
```
 it('handles expo -> app transition', async () => {
       await waitFor(element(by.id("next-screen-button"))).toBeVisible().withTimeout(8000)
  })
```

_Originally posted by @henrymoulton in https://github.com/infinitered/ignite/issues/1594#issuecomment-759421113_

**Comment by joshuayoes** [comment]
There has been a lot of changes since this issue last had activity. This is going to be closed for now, but please re-open if this still needs attention.
