### ISSUE TITLE
change the first screen, but the app not fresh

### ISSUE THREAD

**Issue by stfenjobs** [infinitered/ignite#1666]
# What's going on?
the default first screen is `welcome`,  I change it to my custom screen `aaa`, but my app first screen aways stay in `welcome`, not my new screen `aaa`

 

---

# Steps to reproduce

1. I create a new screen， named `aaa`
2. then i edit   the file: `app/navigators/main-navigator.tsx`  , after edit like this :
![image](https://user-images.githubusercontent.com/6580897/116345510-dde01b80-a81a-11eb-877e-26f884770c5a.png)
3. press `R` in   terminal window  to make it rebuild my app
4. in my simulator, the app first screen aways stay in `welcome` , not my new screen `aaa`

---

# `ignite doctor` results:
![image](https://user-images.githubusercontent.com/6580897/116345905-a58d0d00-a81b-11eb-8c73-26bffdb00ce0.png)

**Comment by stfenjobs** [comment]
i must delete the app in my simulator and restart the project, then the first screen will be fresh

but ,the steps is very complex， not easy

can you make it auto fresh  when i change  first screen  `welcome` to another ?

**Comment by stfenjobs** [comment]
thank you very mych

**Comment by nirre7** [comment]
Hi.

I just tried it with a new IgniteJs app. Everything works fine. 

You should not need to press any buttons, the simulator should just reload when you have done your changes (even if you add files), with the help of [fast refresh](https://reactnative.dev/docs/fast-refresh)

I think you have issues with your environment setup, please check that you have watchman etc set up, for more info click [here](https://reactnative.dev/docs/environment-setup)

Hope this helps.
