### ISSUE TITLE
which is  react-native-cli inside ignite?

### ISSUE THREAD

**Issue by stfenjobs** [infinitered/ignite#1671]
https://www.npmjs.com/package/react-native-cli

https://www.npmjs.com/package/@react-native-community/cli

in ignite,  what is react-native-cli we used?

**Comment by nirre7** [comment]
The react-native-cli is deprecated, if you have it installed globally you should remove it.

If you create a new ignite app without expo ignite runs the `npx react-native init your-awesome-app` command.

**Comment by stfenjobs** [comment]
thank you
