### ISSUE TITLE
Adding Tab Navigator doesn't render component

### ISSUE THREAD

**Issue by cmcglynn-nestegg** [infinitered/ignite#1673]
What's going on?
When I use the simple PizzaApp example, I try to add in a tab navigator but when I select the tab I want, nothing renders, just a white screen.
---

Steps to reproduce
Simple way to reproduce off of the starter template
app/navigators/root-navigator
The `DemoScreen` has not been changed, this is the only change I have done to test out the bottom tab navigators.
```
/**
 * The root navigator is used to switch between major navigation flows of your app.
 * Generally speaking, it will contain an auth flow (registration, login, forgot password)
 * and a "main" flow (which is contained in your MainNavigator) which the user
 * will use once logged in.
 */
import React from "react"
import { NavigationContainer, NavigationContainerRef } from "@react-navigation/native"
import { createStackNavigator } from "@react-navigation/stack"
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs"
import { MainNavigator } from "./main-navigator"
import { DemoScreen } from "../screens"

/**
 * This type allows TypeScript to know what routes are defined in this navigator
 * as well as what properties (if any) they might take when navigating to them.
 *
 * We recommend using MobX-State-Tree store(s) to handle state rather than navigation params.
 *
 * For more information, see this documentation:
 *   https://reactnavigation.org/docs/params/
 *   https://reactnavigation.org/docs/typescript#type-checking-the-navigator
 */
export type RootParamList = {
  mainStack: undefined
}

// const Stack = createStackNavigator<RootParamList>()
//
// const RootStack = () => {
//   return (
//     <Stack.Navigator
//       screenOptions={{
//         headerShown: false,
//       }}
//     >
//       <Stack.Screen
//         name="mainStack"
//         component={MainNavigator}
//         options={{
//           headerShown: false,
//         }}
//       />
//     </Stack.Navigator>
//   )
// }

const Tab = createBottomTabNavigator()

const RootStack = () => {
  return (
    <Tab.Navigator>
      <Tab.Screen
        name="mainStack"
        component={DemoScreen}
      />
    </Tab.Navigator>
  )
}

export const RootNavigator = React.forwardRef<
  NavigationContainerRef,
  Partial<React.ComponentProps<typeof NavigationContainer>>
>((props, ref) => {
  return (
    <NavigationContainer {...props} ref={ref}>
      <RootStack />
    </NavigationContainer>
  )
})

RootNavigator.displayName = "RootNavigator"
```

---

`ignite doctor` results:
![Simulator Screen Shot - iPhone 11 - 2021-05-04 at 12 52 04](https://user-images.githubusercontent.com/80188263/117040137-90aaf080-acd7-11eb-8a99-8c05baf87812.png)

**Comment by br1anchen** [comment]
I had similar issue when using `TabNavigator` with `Ignite`.
Here is the `ignite-cli doctor`:
```
System
  platform           linux
  arch               x64
  cpu                12 cores     Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  directory          BlimeApp     /home/br1anchen/Documents/BlimeApp

JavaScript (and globally-installed packages)
  node                15.14.0      /tmp/fnm_multishell_104304_1621886415348/bin/node
  npm                 6.14.12      /tmp/fnm_multishell_104304_1621886415348/bin/npm
    @expo/ngrok       2.4.3
    eslint            7.23.0
    eslint_d          10.0.4
    expo-cli          4.3.4
    ignite-cli        6.6.0
    npm               6.14.12
    prettier          2.2.1
    prettier_d_slim   1.0.0
    yarn              1.22.10
  yarn                1.22.10      /tmp/fnm_multishell_104304_1621886415348/bin/yarn
    neovim            4.9.0

Ignite
  ignite-cli         6.6.0        /tmp/fnm_multishell_104304_1621886415348/bin/ignite
  ignite src         build        /home/br1anchen/.fnm/node-versions/v15.14.0/installation/lib/node_modules/ignite-cli/build

Android
  java               -            null
  android home       -            undefined
```
In my case, I did not test on iOS simulator, I used `expo` tunnel link and test iOS build on actual iPhone, and get empty tab content result. From the debugger, tab `Screen` is mounted/rendered, but it is empty in view. Very strange.
I tested bare-bone `expo` project with tab navigator through `expo` tunnel link on actual iPhone, it works fine. Not sure what configuration `Ignite` made causes this.

**Comment by mazenchami** [comment]
@br1anchen please try uninstalling your globally installed ignite-cli package and use npx ignite you app. According to `ignite-cli doctor` you're using v6.6.0 and ignite is currently on v7.0.0
`yarn global remove ignite-cli`
`npx ignite-cli new PizzaApp`

**Comment by br1anchen** [comment]
@mazenchami Thanks for the updates. After upgrade to `v7.0.0`, it works with nested tab navigator.
Do you know what is the difference between v7 and v6 to cause this?

**Comment by yulolimum** [comment]
@mazenchami we will be adding TabNavigator examples for milestone "Maverick". Does this issue need to be addressed still?

**Comment by mazenchami** [comment]
> @mazenchami Thanks for the updates. After upgrade to `v7.0.0`, it works with nested tab navigator. Do you know what is the difference between v7 and v6 to cause this?

@br1anchen sorry for the delay in getting back to you! I'm not quite sure what the difference was but if you go to this [link](https://github.com/infinitered/ignite/compare/v6.6.0...v7.0.0), you can see the difference between your version `v6.6.0` and `v7.0.0` (and any combo you want)

**Comment by mazenchami** [comment]
> @mazenchami Thanks for the updates. After upgrade to `v7.0.0`, it works with nested tab navigator. Do you know what is the difference between v7 and v6 to cause this?

@yulolimum nope, this issue can be closed since it's resolved and you're handling it in the newer version.
