### ISSUE TITLE
React Native 0.64.x  - unable to resolve class com.android.build.OutputFile

### ISSUE THREAD

**Issue by tatva-denish** [infinitered/ignite#1675]
What's going on?

Could not compile build file 'XXXXXXXXXXX\android\app\build.gradle'.
> startup failed:
  build file 'XXXXXXXXXXX\android\app\build.gradle': 3: unable to resolve class com.android.build.OutputFile
   @ line 3, column 1.
     import com.android.build.OutputFile

Steps to reproduce

1. yarn android

---

`ignite doctor` results:

**Comment by nirre7** [comment]
HI.

I tried:
`npx ignite-cli AwesomeApp`
 `npx react-native run-android`
Which worked 👍 

Hope this helps.

**Comment by selindoga** [comment]
> 

where did you change it ? I cannot find `com.android.tools.build:gradle:4.1.0`

**Comment by kevingo710** [comment]
> > 
> 
> where did you change it ? I cannot find `com.android.tools.build:gradle:4.1.0`

/android/build.gradle

```
 dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
 }
```

**Comment by jacob0123456** [comment]
dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
 }

I changed like this. but not working.

**Comment by ysumiit005** [comment]
same problem 

changed to 3.5.3 it dont work 
i checked other projects which were not showing that error on vscode 
but when i opened that file in other projects , that file also started showing error. its like when you deal with that build,gradle then only it shows error on import line of code.

i was using react native documentation to create apk  
https://reactnative.dev/docs/signed-apk-android

before this recently installed vscode gradle plugin which was automatically notified by vscode to me

**Comment by ysumiit005** [comment]
made a new project using 
 npx react-native init testApp

checked for android/app/build.gradle

got same problem 
unable to resolve class com.android.build.OutputFile
 @ line 4, column 8.Gradle

line 4 has 
import com.android.build.OutputFile

**Comment by nrooban** [comment]
removing gradle plugin from vscode simply do the job, thanks @ysumiit005

**Comment by Sebas1307** [comment]
@nrooban How did you remove it?

**Comment by ysumiit005** [comment]
I mean remove the vscode extension for gradle @nrooban

**Comment by Sebas1307** [comment]
Oh ok thanks I already did that but the error is still there.
Also change the version of tool.build:gradle to 3.5.3 and it doesn't work

**Comment by pruteanualex** [comment]
> pruteanualex

this solve my problem ))

**Comment by kaheihong** [comment]
not complaining after removing the vscode extension for me... thanks

**Comment by konstantindt** [comment]
I used the new vscode extension for gradle settings from https://github.com/microsoft/vscode-gradle/issues/339 to fix the issue without removing the extension.

**Comment by archanarackenchath** [comment]
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1100 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
Starting a Gradle Daemon, 5 incompatible Daemons could not be reused, use --status for details

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.1.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\HP\Downloads\bsafe - Copy\bsafe - Copy\bSafe-main\android\app\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> org/gradle/initialization/BuildCompletionListener

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

PS C:\Users\HP\Downloads\bsafe - Copy\bsafe - Copy\bSafe-main> 
 Can anyone help me with this error
