### ISSUE TITLE
Question: initialise  StoreModel with parameters

### ISSUE THREAD

**Issue by scinfu** [infinitered/ignite#1689]
How can initialise  a StoreModel with parameters?
your example is like this:

CharacterStoreModel
```
export const CharacterStoreModel = types
  .model("CharacterStore")
  .props...
```

```
export const RootStoreModel = types.model("RootStore").props({
  characterStore: types.optional(CharacterStoreModel, {} as any),
})
```

and in my screen
`const { characterStore } = useStores()`

but what about if my StoreModel is with parameters like this?
```
export const CharacterStoreModel = types
  .model("CharacterStore",{userId: types.string})
  .props...
```
I Added **{userId: types.string}**

Thank you

**Comment by markrickert** [comment]
Hey @scinfu! Thanks for using ignite! 

You can provide defaults to your rootstore model when setting everything up. Note that it's persisted so this will only be a default for the first launch:

```
export const RootStoreModel = types.model("RootStore").props({
  characterStore: types.optional(CharacterStoreModel, {userID: "1234"} as any),
})
```

That will start your app with this default model already in the store. Then you can manipulate it in the screen...

```
const { characterStore } = useStores()
console.log(characterStore.userId) // "1234"
```

Here's a link to the mobx state tree documentation so you can read up more on how MST works: https://mobx-state-tree.js.org/intro/philosophy

**Comment by scinfu** [comment]
@markrickert  thank you for the quick answer.
ok, so useStores() most to be used likely for shared StoreModel or remember to reset/re-Set some property.

I'm trying to create a new one with CharacterStoreModel.create({userID: "56789"}) and work but getCharacters seems do not have self.environment.api, so the REST API request go in exception and then in error.
With CharacterStoreModel.create I want to pass the ID and **ignore MST** but  self.environment.api in null, how can I initialise it?

**Comment by markrickert** [comment]
Check out this section in the mobx state tree docs: https://mobx-state-tree.js.org/intro/getting-started#creating-model-instances-tree-nodes

A "store" is just a fancy model that likely stores instances of other models. So here we have a character store and a character model. I'd get the store with `const { characterStore } = useStores()` and then create a new character with `const myNewCharacter = Character.create({whatever: "attributes"})` but it's just a model instance and not connected with your persistent store. To add it to the `characterStore` by doing `characterStore.characters.push(myNewCharacter)`.

Generally, i like letting the stores handle the API calls and then when the results come back, it updates it's own data structure. So the view calls the store to fetch the api, that then ideally uses `applySnapshot` to update its data structure.

**Comment by scinfu** [comment]
all clear thank you.
What about `self.environment` is null in `CharacterStoreModel` using `CharacterStoreModel.create()`?
Thank you

**Comment by jamonholmgren** [comment]
@scinfu If you're still having problems with MST, feel free to open a discussion here: https://github.com/mobxjs/mobx-state-tree/discussions

Thanks for using Ignite!
