### ISSUE TITLE
Question: Whitelist specific models in mbx st on async storage

### ISSUE THREAD

**Issue by fredyonge** [infinitered/ignite#1690]
Hello!

Is there any way of whitelisting only specific stores, like in redux persist? 

Thanks a lot!

**Comment by jamonholmgren** [comment]
One idea would be to manually address which ones get inserted.

From here:

https://github.com/infinitered/ignite/blob/32989d290532e29a473e80049abca80920ffdb9d/boilerplate/app/models/root-store/setup-root-store.ts#L52

```typescript
  onSnapshot(rootStore, (snapshot) => {
    const { userStore, myOtherStore } = snapshot
    const storageSnapshot = { userStore, myOtherStore }
    storage.save(ROOT_STATE_STORAGE_KEY, storageSnapshot)
  })
```

**Comment by fredyonge** [comment]
Thank you! Looking forward to port to the ignite stack, especially mobx state tree.
