### ISSUE TITLE
withRootStore Dependency cycle

### ISSUE THREAD

**Issue by josehernandezv** [infinitered/ignite#1692]
What's going on?

`Dependency cycle via ../root-store/root-store`

I was trying to use the withRootStore extension but it creates a Dependency cycle, how can I avoid this issue?

**Comment by casamia918** [comment]
I have similar issue. When I define mst models, it works fine. But when I insert `.extend(withRootStore)` into model definition chain, every model type inference is broken. After withRootStore injected, the store model and rootStore model are inferenced as type any. 

Does anybody knows this answer?

**Comment by jamonholmgren** [comment]
This is fixed in 7.1.0 (#1741 by @anhtuank7c). Thanks!
