### ISSUE TITLE
An issue loading the app on IOS simulator. This happens on a fresh install of both ignite 6 and 7

### ISSUE THREAD

**Issue by aimensasi** [infinitered/ignite#1693]
What's going on?

An issue loading the app on IOS simulator. This happens on a fresh install of both ignite 6 and 7
---

Steps to reproduce

1. npx ignite-cli new PizzaApp --expo 
2. expo start
3. Then open in IOS simulator

---

`ignite doctor` results:

```
System
  platform           darwin                                                           
  arch               x64                                                              
  cpu                8 cores       Apple M1                                           
  directory          MasterClass   /Users/username/Sites/Code/React/MasterClass 

JavaScript (and globally-installed packages)
  node                 14.15.4      /usr/local/bin/node 
  npm                  6.14.10      /usr/local/bin/npm  
    @adonisjs/cli      4.0.13                           
    @expo/ngrok        2.4.3                            
    expo-cli           4.2.1                            
    ngrok              2.2.3                            
    react-native-cli   2.0.1                            
    react-viro-cli     2.17.1                           
    truffle            5.3.0                            
  yarn                 -            not installed       

Ignite
  ignite-cli         7.0.0        /Users/username/.npm/_npx/2500/bin/ignite                        
  ignite src         build        /Users/username/.npm/_npx/2500/lib/node_modules/ignite-cli/build 

Android
  java               1.8.0_282    /usr/bin/java                             
  android home       -            /Users/username/Library/Android/sdk 

iOS
  xcode              12.5       
  cocoapods          1.10.1       /usr/local/bin/pod 
```

<img width="366" alt="Screenshot 2021-06-01 at 6 16 38 PM" src="https://user-images.githubusercontent.com/13252355/120307393-82b3b400-c305-11eb-96eb-9d55fbeaef69.png">

<img width="332" alt="Screenshot 2021-06-01 at 6 16 51 PM" src="https://user-images.githubusercontent.com/13252355/120307413-8ba48580-c305-11eb-8a05-21509d9310e8.png">

**Comment by MadhavNasit** [comment]
> What's going on?
> 
> ## An issue loading the app on IOS simulator. This happens on a fresh install of both ignite 6 and 7
> Steps to reproduce
> 
> 1. npx ignite-cli new PizzaApp --expo
> 2. expo start
> 3. Then open in IOS simulator
> 
> `ignite doctor` results:
> 
> ```
> System
>   platform           darwin                                                           
>   arch               x64                                                              
>   cpu                8 cores       Apple M1                                           
>   directory          MasterClass   /Users/username/Sites/Code/React/MasterClass 
> 
> JavaScript (and globally-installed packages)
>   node                 14.15.4      /usr/local/bin/node 
>   npm                  6.14.10      /usr/local/bin/npm  
>     @adonisjs/cli      4.0.13                           
>     @expo/ngrok        2.4.3                            
>     expo-cli           4.2.1                            
>     ngrok              2.2.3                            
>     react-native-cli   2.0.1                            
>     react-viro-cli     2.17.1                           
>     truffle            5.3.0                            
>   yarn                 -            not installed       
> 
> Ignite
>   ignite-cli         7.0.0        /Users/username/.npm/_npx/2500/bin/ignite                        
>   ignite src         build        /Users/username/.npm/_npx/2500/lib/node_modules/ignite-cli/build 
> 
> Android
>   java               1.8.0_282    /usr/bin/java                             
>   android home       -            /Users/username/Library/Android/sdk 
> 
> iOS
>   xcode              12.5       
>   cocoapods          1.10.1       /usr/local/bin/pod 
> ```
> 
> <img alt="Screenshot 2021-06-01 at 6 16 38 PM" width="366" src="https://user-images.githubusercontent.com/13252355/120307393-82b3b400-c305-11eb-96eb-9d55fbeaef69.png">
> 
> <img alt="Screenshot 2021-06-01 at 6 16 51 PM" width="332" src="https://user-images.githubusercontent.com/13252355/120307413-8ba48580-c305-11eb-8a05-21509d9310e8.png">

+1

**Comment by MadhavNasit** [comment]
+1
Issue on Macbook M1

**Comment by aimensasi** [comment]
You can try to run `npm dedupe `, It helped me with the issue

**Comment by MadhavNasit** [comment]
> You can try to run `npm dedupe `, It helped me with the issue

Still app stuck on splash screen on ios simulator, while working fine on android.

**Comment by aimensasi** [comment]
try cloning this [repo](https://github.com/aimensasi/ignite), and see if it works on your device. make sure to `npm install` before running.

**Comment by joeyfigaro** [comment]
@aimensasi looks like that link is no longer working
