### ISSUE TITLE
Is drawer a must? 

### ISSUE THREAD

**Issue by coolzilj** [infinitered/ignite#170]
- [x] ignite generated code

I think TabBar is used much more often than drawer, right?
Why not replace drawer with TabBar? Or add a TabBar example?

**Comment by GantMan** [comment]
We'll be making drawer an optional add on as we progress towards 2.0

**Comment by kevinvangelder** [comment]
Once #235 is merged, it should be significantly easier to completely change the method of navigation from the default drawer to a tab bar.

**Comment by matanwerbner** [comment]
I've had a problem trying to add a Youtube player to an ignite project, it wont play until i removed drawer...
took me a good couple of hours to understand this, somehow it sees it as an overlay , so it wont play.

keep up the awesome work otherwise!

**Comment by skellock** [comment]
We're overhauling 2.0 of ignite including the navigation.  Once `react-navigation` is ready to go, it'll be optional to use their drawer.  🎉
