### ISSUE TITLE
Handle api errors

### ISSUE THREAD

**Issue by cuongnv-dev** [infinitered/ignite#1704]
In a store, if response kind is “ok” we will update store data, but not, I want to show message toash in screen and how can I do it? Hope get your help

**Comment by jamonholmgren** [comment]
Hi @cuongnv-dev, good question.

One way to approach this is to use [react-native-toast-message](https://github.com/calintamas/react-native-toast-message), which is a solid library for this sort of thing.

![toast-gif](https://raw.githubusercontent.com/calintamas/react-native-toast-message/main/docs/toast.gif)

In your code, you can detect if the response isn't correct and kick off a toast message. There are a number of ways to accomplish this; you can do some sort of pubsub, or an MST `errorMessage` prop in your RootStore, or something like that.

(note: I haven't tested this code, just doing it as an example)

```tsx
useEffect(() => {
  if (rootStore.errorMessage.length > 0) {
    // kick off error toast
  }
}, [ rootStore.errorMessage ])
```

You might have to set a ref to track the old one and ensure you're not setting the same one twice, although this code _should_ work in most cases.

By the way, a good way to ask these questions and get more timely answers is to ask [in our Slack community](https://community.infinite.red).
