### ISSUE TITLE
How to ignore files (blacklist or exclusionlist)?

### ISSUE THREAD

**Issue by waltermvp** [infinitered/ignite#1707]
I need to ignore some directories in my project and I am unsure of how to change the configuration. I know that typically we can change the `metro.config.js` but this boilerplate uses `react-native.config.js`. I have attempted to modify the `react-native-config.js` like so https://github.com/aws-amplify/amplify-cli/issues/3295#issuecomment-833640678 with unsuccessful results. Am I missing something?

**Comment by walterobvio** [comment]
Friendly bump

**Comment by joshuayoes** [comment]
There has been a lot of changes since this issue last had activity. This is going to be closed for now, but please re-open if this still needs attention.
