### ISSUE TITLE
7.0.3 new app failing

### ISSUE THREAD

**Issue by SubhajeetS** [infinitered/ignite#1709]
What's going on?

Unable to create a new app on Mac.

---

Steps to reproduce

1. npx ignite-cli new NewApp

---

`ignite doctor` results:

System
  platform           darwin
  arch               x64
  cpu                12 cores              Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  directory          improv-productivity   /Users/subhajeetsarkar/Projects/improv-productivity

JavaScript (and globally-installed packages)
  node               15.5.1       /Users/subhajeetsarkar/.nvm/versions/node/v15.5.1/bin/node
  npm                7.3.0        /Users/subhajeetsarkar/.nvm/versions/node/v15.5.1/bin/npm
    npm              7.3.0
    yarn             1.22.10
  yarn               1.22.10      /Users/subhajeetsarkar/.nvm/versions/node/v15.5.1/bin/yarn
    ios-deploy       1.11.4

Ignite
  ignite-cli         7.0.3        /Users/subhajeetsarkar/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/subhajeetsarkar/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               1.8.0_252    /Users/subhajeetsarkar/.jenv/shims/java
  android home       -            /Users/subhajeetsarkar/Library/Android/sdk

iOS
  xcode              12.4
  cocoapods          1.10.1       /usr/local/bin/pod

**Comment by sjgrytfit** [comment]
It worked with this -

System
  platform           darwin
  arch               x64
  cpu                12 cores              Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  directory          improv-productivity   /Users/subhajeetsarkar/Projects/improv-productivity

JavaScript (and globally-installed packages)
  node               16.1.0       /Users/subhajeetsarkar/.nvm/versions/node/v16.1.0/bin/node
  npm                7.11.2       /Users/subhajeetsarkar/.nvm/versions/node/v16.1.0/bin/npm
    npm              7.11.2
  yarn               1.22.4       /usr/local/bin/yarn
    ios-deploy       1.11.4

Ignite
  ignite-cli         7.0.3        /Users/subhajeetsarkar/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/subhajeetsarkar/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               1.8.0_252    /Users/subhajeetsarkar/.jenv/shims/java
  android home       -            /Users/subhajeetsarkar/Library/Android/sdk

iOS
  xcode              12.4
  cocoapods          1.10.1       /usr/local/bin/pod

**Comment by SubhajeetS** [comment]
It worked with this - 

System
  platform           darwin
  arch               x64
  cpu                12 cores              Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  directory          improv-productivity   /Users/subhajeetsarkar/Projects/improv-productivity

JavaScript (and globally-installed packages)
  node               16.1.0       /Users/subhajeetsarkar/.nvm/versions/node/v16.1.0/bin/node
  npm                7.11.2       /Users/subhajeetsarkar/.nvm/versions/node/v16.1.0/bin/npm
    npm              7.11.2
  yarn               1.22.4       /usr/local/bin/yarn
    ios-deploy       1.11.4

Ignite
  ignite-cli         7.0.3        /Users/subhajeetsarkar/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/subhajeetsarkar/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               1.8.0_252    /Users/subhajeetsarkar/.jenv/shims/java
  android home       -            /Users/subhajeetsarkar/Library/Android/sdk

iOS
  xcode              12.4
  cocoapods          1.10.1       /usr/local/bin/pod
