### ISSUE TITLE
There is a delay in navigating to another screen - Android

### ISSUE THREAD

**Issue by sudharsan1988** [infinitered/ignite#171]
Hi,

I must admit, this is the best starter kit for React Native projects. I am playing around with Android build but there is a delay in navigating to another screen on Android device(5.0). I have tested some more samples but I am not seeing the same issue. Is this because of the animation or is there any configuration to set the time interval?

- [* ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ *] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

**Comment by GantMan** [comment]
It could be a few things. 

One, if you're using Redux to push/nav between screens, it could be the logger middleware, which does cause a `delay` kind of feel.   You can turn the logger off in config.

Two, it could be remote debugging, which has been known to cause packager delays.

If you're sure it's not either of these two, we'll have to figure out if this is ignite specific under certain conditions or not.

**Comment by sudharsan1988** [comment]
Thank you for your answer. I tried with a signed apk and it's better now. I am having this delay only when I am trying with debug apk on a physical device through USB. 

Also, I have noticed another one thing, whenever I open the app, it starts with a white blank screen and after few seconds, it loads the presentation screen. I guess, it's because of missing splash screen. This is happening on both signed apk and debug.

Do we have option to include splash screen in ignite?

**Comment by GantMan** [comment]
We're working on figuring out the best way to supply an ignite splash screen.  If you have any suggestions, we're open to it.  I guess, we should probably consider putting one in sooner rather than later.

I plan on making splash and other options more optional soon :)   Been a bit busy this week, heh.

**Comment by steve21124** [comment]
https://github.com/remobile/react-native-splashscreen

**Comment by GantMan** [comment]
closing this ticket as the core issue seems resolved.
