### ISSUE TITLE
Auth Example

### ISSUE THREAD

**Issue by maidinhkhoa92** [infinitered/ignite#1713]
Hi,

I'm using your boilerplate for my project. However, I'm getting some stuck with Authorization.

1. How can I set Authorization in every request ?
2. After 3 hours, I have to call refreshing token API. How can I do it ?

If you have some examples, it is awesome.

**Comment by MadhavNasit** [comment]
You can use below code in api.ts file's setup(){} methods as below,
`this.apisauce.addAsyncRequestTransform(request => async () => {
      let authKey = await AsyncStorage.getItem("userToken");
      if (authKey) {
        request.headers["Authorization"] = "Bearer " + authKey
      }
    })`
    
 This will authorise for every api call, Also update you async token after every 3 hour, Above call fetch latest token and will work on that.

**Comment by jamonholmgren** [comment]
@MadhavNasit That's a good way to do it.

This would be a good thing for us to document better or provide some sample code.

**Comment by MadhavNasit** [comment]
@jamonholmgren Thank you for answer improvement.

**Comment by maidinhkhoa92** [comment]
@MadhavNasit thank you for example.
How about refreshing token ?

**Comment by MadhavNasit** [comment]
> @MadhavNasit thank you for example.
> How about refreshing token ?

You can setinterval which call every 3 hours and fetch new api tocken.

But best way to do it is using socket.io, when token i changed, emit from server and client side listen that and update tocken in listen function.

**Comment by maidinhkhoa92** [comment]
@MadhavNasit Thank you.
For now, I used setInterval and it worked well. However, it looks like work around because I see a warning in log terminal.

**Comment by MadhavTatva** [comment]
> @MadhavNasit Thank you.
> For now, I used setInterval and it worked well. However, it looks like work around because I see a warning in log terminal.

Socket.io is what you need.

**Comment by maidinhkhoa92** [comment]
@MadhavNasit 
I found an issue with reactotron.

if you add these code in api.ts, reactotron won't work when you reloading app. Same action with close app and open again.

```
this.apisauce.addAsyncRequestTransform(request => async () => {
  let authKey = await AsyncStorage.getItem("userToken");
  if (authKey) {
    request.headers["Authorization"] = "Bearer " + authKey
  }
})
```

Please check my video in here.
https://streamable.com/3o3e7y

In my video, status is done (without your code). After I added your code, status is pending. It never change into done.

I tried to use Flow of mobx-state-tree but nothing changed.

https://mobx-state-tree.js.org/concepts/async-actions

**Comment by maidinhkhoa92** [comment]
> @MadhavNasit That's a good way to do it.
> 
> This would be a good thing for us to document better or provide some sample code.



> > @MadhavNasit Thank you.
> > For now, I used setInterval and it worked well. However, it looks like work around because I see a warning in log terminal.
> 
> Socket.io is what you need.

Thanks I will note.

**Comment by carlinisaacson** [comment]
@maidinhkhoa92 I'm working on documenting some solutions for these situations. In the meantime, another way we've added the Authorization header in the past is to add a method to the api.

```
// api.ts

setAuthorizationHeader = (newToken?: string) => {
  if (newToken) {
    this.apisauce.setHeader("Authorization", `Bearer ${newToken}`)
  } else {
    this.apisauce.deleteHeader("Authorization")
  }
}
```

On sign in success, or token refresh, pass the new token to this method to set it. On sign out success, call it without arguments to delete the existing header.

**Comment by maidinhkhoa92** [comment]
> @maidinhkhoa92 I'm working on documenting some solutions for these situations. In the meantime, another way we've added the Authorization header in the past is to add a method to the api.
> 
> ```
> // api.ts
> 
> setAuthorizationHeader = (newToken?: string) => {
>   if (newToken) {
>     this.apisauce.setHeader("Authorization", `Bearer ${newToken}`)
>   } else {
>     this.apisauce.deleteHeader("Authorization")
>   }
> }
> ```
> 
> On sign in success, or token refresh, pass the new token to this method to set it. On sign out success, call it without arguments to delete the existing header.

@carlinisaacson I followed your guide.

Here is my signin action in auth model:

```
signin: async (payload: LoginPayload) => {
      try {
        self.setStatus("pending")
        const authApi = new AuthApi(self.environment.api)
        const result = await authApi.signIn(payload)

        if (result.kind === "ok") {
          self.environment.api.setAuthorizationHeader(result.response.accessToken) <= I added this line
          self.saveAuth(result.response)
          self.setStatus("done")
        } else {
          self.setStatus("error", result)
        }
      } catch (error) {
        self.setStatus("error")
      }
    },
```

It worked. However, when I closed app and opened again. Token is not saved. 

Maybe I'm wrong with your solution. Could you send me codes in auth.signin action ?

**Comment by maidinhkhoa92** [comment]
I Found how to add token and use Reactotron.

1. Adding these code in setup in api.ts

```
this.apisauce.addAsyncRequestTransform(request => async () => {
  let authKey = await AsyncStorage.getItem("userToken");
  if (authKey) {
    request.headers["Authorization"] = "Bearer " + authKey
  }
})
```

2. In api file, use return with Promise.resolve and Promise.reject
For example: https://github.com/infinitered/ignite/blob/master/boilerplate/app/services/api/character-api.ts

```
async getCharacters(): Promise<GetCharactersResult> {
    try {
      // make the api call
      const response: ApiResponse<any> = await this.api.apisauce.get(
        "https://raw.githubusercontent.com/infinitered/ignite/master/data/rick-and-morty.json",
        { amount: API_PAGE_SIZE },
      )

      // the typical ways to die when calling an api
      if (!response.ok) {
        const problem = getGeneralApiProblem(response)
        if (problem) return Promise.reject(problem)
      }

      const characters = response.data.results

      return Promise.resolve({ kind: "ok", characters })
    } catch (e) {
      __DEV__ && console.tron.log(e.message)
      return Promise.reject({ kind: "bad-data" })
    }
  }
```

**Comment by carlinisaacson** [comment]
I'm glad you found a solution that works for you. I haven't had much time to put together the documentation so I've been piecing it together as I get time.

Closing the app and restarting requires rehydration. We do this with MST state by loading the snapshot from async storage in setup-root-store.ts. The api is outside of MST, and the auth token is set as a header on it's apisauce instance. In order to rehydrate that, we need to take `setupRootStore` a step further. Once the auth token is rehydrated into the MST state we need to call the `setAuthorizationHeader` method and give it the auth token. This can be done toward the end of `setupRootStore`. 

It could look something like this:

```ts
export async function setupRootStore() {
  ...

  // reactotron logging
  if (__DEV__) {
    env.reactotron.setRootStore(rootStore, data)
  }

  const { authToken } = rootStore.authStore
  if (authToken) {
    env.api.setAuthorizationHeader(authToken)
  }

  return rootStore
}
```

**Comment by maidinhkhoa92** [comment]
> ```ts
> const { authToken } = rootStore.authStore
>   if (authToken) {
>     env.api.setAuthorizationHeader(authToken)
>   }
> ```

Thanks so much @carlinisaacson . Your solution is nice. Let me take a look if I can implement in my source.

Honestly, I want to follow code in your boilerplate because I want to upgrade latest version.

**Comment by cspeer** [comment]
Hi,

since 2021 a lot has changed and there is no `env` in `setupRootStore.js` any longer.
Would anyone know what the current solution would be to access the `api` instance from within `setupRootStore.js` to equip  api requests with a user specific auth token

Another way could be to somehow access the `authenticationStore` from within `api.ts` to set the auth token.

Since I'm fairly knew to all of this, any help would be appreciated!

Thanks!

**Comment by betocolon23** [comment]
@cspeer did you manage to do this? I have the same question!

**Comment by cspeer** [comment]
> @maidinhkhoa92 I'm working on documenting some solutions for these situations. In the meantime, another way we've added the Authorization header in the past is to add a method to the api.
> 
> ```
> // api.ts
> 
> setAuthorizationHeader = (newToken?: string) => {
>   if (newToken) {
>     this.apisauce.setHeader("Authorization", `Bearer ${newToken}`)
>   } else {
>     this.apisauce.deleteHeader("Authorization")
>   }
> }
> ```
> 
> On sign in success, or token refresh, pass the new token to this method to set it. On sign out success, call it without arguments to delete the existing header.

@betocolon23 once you retrieve the token (from your api or whatever), you can store it somewhere safely like an encrypted local storage. Then you can use @maidinhkhoa92' solution to hand token to the api instance once on app launch and preferebly right after you initially obtain the token. Hope that helps :)
