### ISSUE TITLE
Ios app stuck on splash screen on mac with m1(works fine on intel mac)

### ISSUE THREAD

**Issue by MadhavNasit** [infinitered/ignite#1714]
What's going on?
Latest ignite app stuck on splash screen on ios, for android it working fine.
It builds successfully for ios but stuck on splash screen for infinite time.
This is only on macbook with M1 chip.
---

Steps to reproduce

1. Create new project using `npx ignite-cli new projectName` after generating project `cd projectName && npx react-native run-ios`

---

`ignite doctor` results:

```
System
  platform           darwin                                                               
  arch               x64                                                                  
  cpu                8 cores            Apple M1                                          
  directory          DemoLatestIgnite   /Users/madhav/Documents/Projects/DemoLatestIgnite 

JavaScript (and globally-installed packages)
  node               14.17.0      /Users/madhav/.nvm/versions/node/v14.17.0/bin/node 
  npm                6.14.13      /Users/madhav/.nvm/versions/node/v14.17.0/bin/npm  
    npm              6.14.13                                                         
  yarn               1.22.10      /opt/homebrew/bin/yarn                             
    ios-deploy       1.11.4                                                          

Ignite
  ignite-cli         7.0.4        /Users/madhav/.npm/_npx/20329/bin/ignite                        
  ignite src         build        /Users/madhav/.npm/_npx/20329/lib/node_modules/ignite-cli/build 

Android
  java               1.8.0_275    /usr/bin/java                     
  android home       -            /Users/madhav/Library/Android/sdk 

iOS
  xcode              12.5       
  cocoapods          1.10.1       /usr/local/bin/pod 
```

**Comment by jamonholmgren** [comment]
Could we get others with an M1 chip to confirm this is happening?

**Comment by MadhavNasit** [comment]
Yes my other 3 friends are also facing same issue, i can provide my mac m1's remote access if you need for some time.

**Comment by jamonholmgren** [comment]
@MadhavNasit Appreciate it! Do you have any ideas on what might be happening?

**Comment by MadhavNasit** [comment]
> @MadhavNasit Appreciate it! Do you have any ideas on what might be happening?

Not getting any error, so unable to trace anything.

**Comment by ViraliVasa** [comment]
> Could we get others with an M1 chip to confirm this is happening?

Yes I am having mac M1 and also facing this error.

**Comment by Neel2497** [comment]
> Could we get others with an M1 chip to confirm this is happening?

Yes I am facing this error too.

**Comment by jamonholmgren** [comment]
I'd appreciate help debugging this, as I don't have an M1 at this point.

**Comment by Caleb-Mantey** [comment]
Am also facing the same issue. works on a mac with intel chip but not on my m1

**Comment by mrmurphy** [comment]
I've got an M1 and have been trying to get going with ignite. I've run into other problems but at least for me, I wasn't stuck on the splash screen in the iOS simulator.

**Comment by khatbahusain** [comment]
Yes I am facing this error too.

**Comment by MuhtasimTanmoy** [comment]
Same error.

**Comment by joshuayoes** [comment]
There has been a lot of changes since this issue last had activity. This is going to be closed for now, but please re-open if this still needs attention.
