### ISSUE TITLE
Incomplete Android native setup for react-native-gesture-handler

### ISSUE THREAD

**Issue by jehartzog** [infinitered/ignite#1718]
## What's going on?
This boilerplate includes `react-native-gesture-handler` but doesn't include the code needed to use it correctly on Android. The lack of this introduces all sorts of Android only bugs, that come without warnings/errors, down the line.

---

## Details

1. `react-native-gesture-handler` is [included in the boilerplate](https://github.com/infinitered/ignite/blob/master/boilerplate/package.json#L42)
2. There are [specific](https://docs.swmansion.com/react-native-gesture-handler/docs/#updating-mainactivityjava) (and important) instructions on completing the Android setup. 
3. The above setup instructions [are not included](https://github.com/infinitered/ignite/blob/master/boilerplate/android/app/src/main/java/com/helloworld/MainActivity.java) in the boilerplate.

---
## Effects

We kept hitting unexpected issues on Android when expanding functionality, mainly around touches on overlays of various sorts. The issue which finally led me here was [this](https://github.com/jeremybarbet/react-native-modalize/issues/112#issuecomment-621466229).

I'd be happy to throw together a PR to correct this, as long as somebody is interested in reviewing it.

**Comment by jamonholmgren** [comment]
@jehartzog I'll review it for sure, and thanks for offering to do the PR!
