### ISSUE TITLE
ignite new MyTestApp hangs on "Running React Native setup (~ 1 minute)"

### ISSUE THREAD

**Issue by romanchukenator** [infinitered/ignite#172]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [x] ignite the cli
  - [ ] ignite generated code

I will also cancel the process and then run ```ignite new MyTestApp``` again and I'll sometimes push through to the next step "Installing Ignite dependencies (~30 seconds-ish)" and then it'll hang again. Rinse, repeat, I'll run ```ignite new MyTestApp``` and I'll push through to the next step and then end up at issue [138](https://github.com/infinitered/ignite/issues/138)

Help? What's going on? I can't generate a new project!

I've deleted and reinstalled everything. I've updated react-native to the latest.

I've removed the ```stdio: 'ignore'``` from ```this.spawnCommand(command, commandOpts, {stdio: 'ignore'})``` to have a look at the output but all I'm getting is nothing. The project init just hangs at "Running React Native setup (~ 1 minute)" without any messaging.

**Comment by GantMan** [comment]
Hiya @romanchukenator !

Ok, so let's get digging because we both want this fixed!    First, can you create a new project using react native?
ergo: `react-native init MyTestApp`   

This step "Running React Native Setup" is actually doing this.   So I'm interested if you get stuck somewhere in the gears, or right at the starting line.

Please report back what you find!

**Comment by romanchukenator** [comment]
I turn on the ```--verbose``` flag and everything goes fine. Make my project, no errors. I'll run it without the ```--verbose``` flag and it's fine, too.

Now I went ahead and modified some code to this:

```
{
    key: 'reactNativeInit',
    value: function reactNativeInit() {
      var _this3 = this;

      var status = 'Running React Native setup (~ 1 minute)';
      this.spinner.start();
      this.spinner.text = status;
      var done = this.async();
      var command = 'react-native';
      var commandOpts = ['init', this.name, '--verbose'];
      this.spawnCommand(command, commandOpts).on('close', function () {
        _this3.spinner.stop();
        _this3.log(check + ' ' + status);
        done();
      });
    }
  }
```

So now I'm providing the ```---verbose``` flag and ignite fires off perfectly every time! Hah! And now I'm making a full ignite project without a hitch. Hrm. 

I ran the regular ```react-native init MyTestApp``` multiple times without the ```--verbose``` flag and on occasion it did hang, though. Not sure why the ```--verbose``` flag avoids any hanging.

**Comment by GantMan** [comment]
that's wild!  So maybe we'll add --verbose but hide the output?

would you think that solves the issue?

**Comment by romanchukenator** [comment]
Maybe? I'm trying to look into this bit of weirdness. Not sure why a verbose output avoids oddities but I'm game for outputting verbose feedback and hiding it.

**Comment by GantMan** [comment]
gonna close this one and consider revitalizing it should `--verbose` prove significant on a second machine.

**Comment by ur23** [comment]
Hi I am having the same issue of hanging during the Installing Ignite dependencies 1min-ish step. I tried twice and same issue, only thing I could think was Missing Android! notification (though this was because I just installed android studio on the same day). I do now know how to use --verbose and have not tried react-native init MyTestApp.   I did have react native tutorial running yesterday in Xcode  though. Thanks for any Time or help you may have to offer. Excited to try it out!

**Comment by mac-elumen** [comment]
I have the same issue as ur23 😢

**Comment by GantMan** [comment]
hrmmmmm not sure.  Either of you available to screen share?

**Comment by GantMan** [comment]
try to catch us on the gitter chat gitter.im/infinitered/ignite

**Comment by GantMan** [comment]
This was resolved for @ur23 - it was permissions during `yarn` install.    If you find this issue, verify your npm AND your yarn, if you have it installed, are working correctly.

**Comment by prijindal** [comment]
I am having the same issue as @ur23, can you elaborate what did you do to fix this problem?

**Comment by iatsu** [comment]
Currently I am having the same issue. Firstly it says "Missing android SDK 23" even though I have specifically installed this SDK and then it just hangs with "Running React Native setup version 0.39.2 (~ 2 minutes-ish)".

**Comment by jamonholmgren** [comment]
@iatsu Please open a new issue with as much detail as you can provide. Thank you!
