### ISSUE TITLE
After inject withRootStore, ts type inference is broken to any type.

### ISSUE THREAD

**Issue by casamia918** [infinitered/ignite#1720]
What's going on?

When I define mst models, everything works fine at first. But when I insert `.extend(withRootStore)` into model definition chain, every model type inference is broken. After withRootStore injected, the store model and rootStore model are inferenced as type any.

Does anybody knows this answer?
---

Steps to reproduce

1. Create ignite project
2. Choose any model you want
3. import withRootStore and inject with extend method

example
```typescript

import { withEnvironment, withRootStore } from "../extensions"

export const QuestionStoreModel = types
  .model("QuestionStore")
  .props({
    questions: types.optional(types.array(QuestionModel), []),
  })
  .extend(withEnvironment)
  .extend(withRootStore)
```
4. After then, type inference of store models are broken. Infered as Any type. Also type of RootStore is infered as any too.

---

**Comment by casamia918** [comment]
Ok. I found answer.

In withRootStore, return type should be explicitly assigned.

```typescript
export const withRootStore = (self: IStateTreeNode) => ({
  views: {
    /**
     * The root store.
     */
   // before: get rootStore(): {
    get rootStore(): RootStore {
      return getRoot<typeof RootStoreModel>(self)
    },
  },
})

```

**Comment by jamonholmgren** [comment]
Ah, yes. Good point.

Want to do a PR, @casamia918?

https://github.com/infinitered/ignite/blob/7b885d8546f296d7847973ed2a9810bb923081fd/boilerplate/app/models/extensions/with-root-store.ts#L13

**Comment by casamia918** [comment]
> Ah, yes. Good point.
> 
> Want to do a PR, @casamia918?
> 
> https://github.com/infinitered/ignite/blob/7b885d8546f296d7847973ed2a9810bb923081fd/boilerplate/app/models/extensions/with-root-store.ts#L13

 I think it is too cumbersome to make PR by myself to add only 11 characters in code (": RootStore"). If any of this repo maintainer found this issue, PR please :) .
