### ISSUE TITLE
Generating a component should add the generated story to the storybook-registry.

### ISSUE THREAD

**Issue by hubConnect** [infinitered/ignite#1721]
When generating a component, a story item is generated for that component. However, that story must be added to the storybook-registry manually. It would be a nice feature to instead have this step done automatically.

**Comment by jamonholmgren** [comment]
Yeah, that's true.

**Comment by ryanlntn** [comment]
https://github.com/infinitered/ignite/pull/1630 would enable this functionality.

**Comment by yulolimum** [comment]
Storybook is removed for  [Ignite v8: Maverick](https://github.com/infinitered/ignite/milestone/19).
