### ISSUE TITLE
ignite is dead

### ISSUE THREAD

**Issue by relaxfinger** [infinitered/ignite#1724]
What's going on?

---

Steps to reproduce

1.

---

`ignite doctor` results:

**Comment by jamonholmgren** [comment]
![ignite is dead](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.brumleyprinting.com%2Fprint-is-dead-or-is-it%2F&psig=AOvVaw2H7mymHjlB8Opr1x_PXNCA&ust=1626215091554000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCLCckLvJ3vECFQAAAAAdAAAAABAD)
