### ISSUE TITLE
Why "react-native-gesture-handler" library setup is missing?

### ISSUE THREAD

**Issue by casamia918** [infinitered/ignite#1727]
What's going on? : question

Steps to reproduce :  Just create new ignite app.

---

Hi. I'm learning ReactNative with ignite boilerplate. I'm reading ignite app code step by step.

Ignite uses react-native to give navigation feature. 

In the react-navigation doc,  it guides me to install some other libraries too. See [getting started page](https://reactnavigation.org/docs/getting-started/).

Especially, react-navigation doc says to import "react-native-gesture-handler" library for the first time of app code. 

But in the ignite project, the "react-native-gesture-handler" package is installed but libary import is missing. 

Why?

**Comment by jamonholmgren** [comment]
Hey @casamia918, welcome to Ignite! Thanks for trying it out.

Make sure you're using `ignite-cli@7.0.6`, as we recently fixed this:

https://github.com/infinitered/ignite/pull/1719

**Comment by casamia918** [comment]
![스크린샷 2021-07-14 오전 8 55 05](https://user-images.githubusercontent.com/8295005/125539869-6cd65f0a-da89-4cb4-863a-4e694b91821b.png)

[RNGH doc](https://docs.swmansion.com/react-native-gesture-handler/docs/)

@jamonholmgren  Sorry to bother you. I should have stated that "question for ios". 

In the RNGH doc, document clearly says that it needs to insert `import 'react-native-gesture-handler';` at the first of index.js file. 

But when I created ignite project, this import code is missing.

I'm new to RN and ignite. So I just want to know that ignite team deliberately omit this line, or it was just mistake.
