### ISSUE TITLE
npx ignite-cli new fooapp hangs on "Cleaning up Expo install"

### ISSUE THREAD

**Issue by growlycode** [infinitered/ignite#1735]
What's going on?

Attempting to initialize a new expo project, it just hangs on "Cleaning up Expo install". Left it for hours, and it never completed.
When I look at the package.json, none of it is expo-related, it's all react native stuff.

I can can successfully create and run an app using the vanilla expo-cli

```
· · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

    █ Creating fooapp using Ignite 7.0.7
    █ Powered by Infinite Red - https://infinite.red
    █ Using expo-cli
    ────────────────────────────────────────────────

 [object Object]
    - Igniting app npx expo-cli@4 init fooapp --template C:\Users\blahblah\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\boilerplate --non-interactive        
    🔥 Igniting app
 - Downloading and extracting project files.

 √ Downloaded and extracted project files.

 [10:25:13] 🧶 Using Yarn to install packages. Pass --npm to use npm instead.

    - Summoning Expo CLI - Installing JavaScript dependencies.

    | Summoning Expo CLI > yarn install

    - Summoning Expo CLI yarn install v1.13.0

 info No lockfile found.

 [1/4] Resolving packages...

    - Summoning Expo CLI [2/4] Fetching packages...

    \ Summoning Expo CLI info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.

 info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.

 [3/4] Linking dependencies...

    - Summoning Expo CLI [4/4] Building fresh packages...

    - Summoning Expo CLI success Saved lockfile.

 $ node ./bin/postInstall

    / Summoning Expo CLI patch-package 6.2.2

 Applying patches...

    / Summoning Expo CLI 
✔︎ Solidarity checks valid

    / Summoning Expo CLI Jetifier found 1263 file(s) to forward-jetify. Using 12 workers...

    \ Summoning Expo CLI Done in 114.09s.

 √ Installed JavaScript dependencies.

 - Installing CocoaPods...

 √ Skipped installing CocoaPods because operating system is not on macOS.



 ✅ Your project is ready!


    🪔  Summoning Expo CLI
    - Cleaning up Expo install To run your project, navigate to the directory and run one of the following yarn commands.

- cd fooapp
- yarn start # you can open iOS, Android, or web from here, or run them directly with the commands below.
- yarn android
- yarn ios # requires an iOS device or macOS for access to an iOS simulator
- yarn web

    \ Cleaning up Expo install
```
---

Steps to reproduce

1. ```npx ignite-cli new fooapp --expo --debug```
2. Wait for hours - never completes

---

`npx ignite-cli doctor` results:

```
System
  platform           win32         
  arch               x64           
  cpu                12 cores       Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  directory          foo   D:\blahblah\git\foo

JavaScript (and globally-installed packages)
  node               16.4.2       C:\Program Files\nodejs\node.EXE
  npm                7.18.1       C:\Program Files\nodejs\npm.CMD
    expo-cli         4.7.3       
    npm              7.18.1      
  yarn               1.13.0       C:\Users\blahblah\AppData\Roaming\npm\yarn.CMD
    serve            10.1.2      

Ignite
  ignite-cli         7.0.7        C:\Users\blahblah\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\blahblah\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               -            null
  android home       -            undefined
```

**Comment by jamonholmgren** [comment]
@growlycode Hm, I was able to spin one up, albeit a lot slower than it should have been.

![image](https://user-images.githubusercontent.com/1479215/126024200-6d9f40c6-d30a-4c98-872c-52fd567a84fe.png)

doctor

```
System
  platform           darwin                                                
  arch               x64                                                   
  cpu                16 cores     Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz 
  directory          Temp         /Users/jh/Code/Temp                      

JavaScript (and globally-installed packages)
  node                 16.4.2       /usr/local/bin/node 
  npm                  7.18.1       /usr/local/bin/npm  
    appium-doctor      1.15.3                           
    appium             1.17.1                           
    npm                7.18.1                           
    pure-prompt        1.11.0                           
  yarn                 1.22.10      /usr/local/bin/yarn 
    create-next-app    9.4.4                            
    detox-cli          17.11.0                          
    firebase-tools     9.3.0                            
    ios-deploy         1.11.4                           
    react-native-cli   2.0.1                            
    ts-node            8.8.2                            
    typescript         3.8.2                            
    vercel             21.3.3                           

Ignite
  ignite-cli         7.0.6        /usr/local/bin/ignite         
  ignite src         src          /Users/jh/Code/ignite-cli/src 

Android
  java               1.8.0_232    /usr/bin/java                 
  android home       -            /Users/jh/Library/Android/sdk 

iOS
  xcode              12.5.1     
  cocoapods          1.10.1       /usr/local/bin/pod 
```

**Comment by growlycode** [comment]
> @growlycode Hm, I was able to spin one up, albeit a lot slower than it should have been.
> 

Not sure, I just retried it with the exact same result - 12 hours later and it hadn't completed or spat out any errors.
Not the quick "get up and running" thing I had planned.
I'm using Windows, if that makes a difference.

**Comment by fais3000** [comment]
Mine is hanging at **Unboxing NPM dependencies**. It never completes. 

Ignite 7.0.8

On MacOS 2.3 GHz Macbookpro( 8-Core Intel Core i9, 64 GB 2667 MHz DDR4)

**Comment by AaronLayton** [comment]
I just tried on Windows 10 and got the same hang on `Cleaning up Expo install`

Also side note, there are no docs of quick start guides or how to run up and view in a (browser, android, ios) command, even some of the links in the main readme link to paywall'd content.

**Comment by scottma** [comment]
same here, hanging at Unboxing NPM dependencies. It never completes.

**Comment by Minifish57** [comment]
same here, stuck at "Cleaning up Expo Install"
![image](https://user-images.githubusercontent.com/16252118/131822604-6123bbc0-ffc7-4fef-82b5-9d1c4c542a88.png)

The project seams ready but it never ends :(

Npx Ignite-cli doctor
![image](https://user-images.githubusercontent.com/16252118/131822801-344d5bd8-a117-4e55-a7ac-24934f3b2781.png)

**Comment by Germanicus1982** [comment]
Same here. I really hope this bug gets fixed soon. Ignite seems like it's the perfect boilerplate.

**Comment by Minifish57** [comment]
The tricky thing is that if you run the same command in Ubuntu in Windows (WSL), it works like a charm, is it related to windows only?

**Comment by cptnwinky** [comment]
> The tricky thing is that if you run the same command in Ubuntu in Windows (WSL), it works like a charm, is it related to windows only?

Great discovery, it works fine within the wsl container but not if you try to run it on an attached ntfs volume.

**Comment by jsh088** [comment]
just ran into this on windows.
non-expo went through fine, --expo hangs on cleaning up expo install.

**Comment by mlynchdev** [comment]
Reading through this and having had my own issues I'm going to venture a guess.  I think it may have something to do with the workaround in #1776  & #1781. (since .gitignore was changed)
I'm basing this on your report that Git disk usage is off the charts, and when I open VSCode I'm seeing 4K+ changes.  Possibly the git init for HEAD needs to be reordered if --expo flag is in place?  Otherwise it seems that git is running during the CLI cleanup to swap to an Expo app.

**Comment by BattleOfPlassey** [comment]
Having the same problem with --expo flag on Windows 10. Please fix this.

**Comment by joshuayoes** [comment]
There has been a lot of changes since this issue last had activity. This is going to be closed for now, but please re-open if this still needs attention.
