### ISSUE TITLE
Doesn't run on web out of the box

### ISSUE THREAD

**Issue by kbrandwijk** [infinitered/ignite#1736]
What's going on?

Out of the box, the template uses `LogBox` in `utils/ignore-warnings.ts`. This is not compatible with web, as it's a native only component. I would propose including a `ignore-warnings.native.ts` with it, and do not include it in the regular file for web. 

If you're open to a PR for this, I'd be happy to submit one.
---

Steps to reproduce

1. Initialize a new app, with expo support
2. Open it on web

---

`npx ignite-cli doctor` results:
```
System
  platform           darwin                                                  
  arch               x64                                                     
  cpu                8 cores       Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz 
  directory          TestAppExpo   ***

JavaScript (and globally-installed packages)
  node                           12.22.1      /Users/***/.nvm/versions/node/v12.22.1/bin/node 
  npm                            6.14.12      /Users/***/.nvm/versions/node/v12.22.1/bin/npm  
    eas-cli                      0.21.0                                                       
    eas-cli-local-build-plugin   0.0.28                                                       
    expo-cli                     4.7.3                                                        
    npm                          6.14.12                                                      
  yarn                           1.22.5       /usr/local/bin/yarn                             
    appium                       1.14.0                                                       
    exp                          51.4.0                                                       
    react-native-cli             2.0.1                                                        

Ignite
  ignite-cli         7.0.7        /Users/***/.npm/_npx/36167/bin/ignite                        
  ignite src         build        /Users/***/.npm/_npx/36167/lib/node_modules/ignite-cli/build 

Android
  java               9.0.4        /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              12.5.1     
  cocoapods          1.10.1       /Users/***/.rvm/rubies/ruby-2.5.1/bin/pod 
```

**Comment by markrickert** [comment]
Hmm... `react-native-web` supports `YellowBox` and `LogBox`. What kind of behavior are you seeing? I just tested a brand new ignited app and the web opened and runs properly.

**Comment by kbrandwijk** [comment]
![image](https://user-images.githubusercontent.com/852069/126574754-36552e9b-42e4-408d-8d3c-ff807d1bf481.png)

**Comment by kbrandwijk** [comment]
Update: it turned out to be a version incompatibility. I ran `expo upgrade` to upgrade from SDK 40 to 42, but apparently, `react-native-web ~0.13.12` wasn't upgraded along with it, and should have. I've manually re-added it, and expo adds 0.17.1 (the latest version), and now everything works fine.
