### ISSUE TITLE
Unboxing NPM dependencies fails --expo

### ISSUE THREAD

**Issue by dennisbouwpas** [infinitered/ignite#1742]
What's going on?
After running npx ignite-cli new PizzaApp --expo
Unboxing NPM dependencies fails
---

Steps to reproduce

1. npx ignite-cli new PizzaApp --expo

---

`npx ignite-cli doctor` results:
ignite-cli         7.0.8 
platform           darwin 

<img width="1246" alt="Screenshot 2021-07-23 at 12 15 44" src="https://user-images.githubusercontent.com/71178868/126768791-eb2369e0-63aa-45cc-a332-259c2bae89b6.png">

**Comment by JaydonChion** [comment]
@dennisbouwpas  hi, any solution to this problem? thank you
