### ISSUE TITLE
Flashing background when navigating (Mobile only)

### ISSUE THREAD

**Issue by JayPerfetto** [infinitered/ignite#1755]
When navigating to any new screen on ios, both simulator and a physical iphone Xs, there is a white flash before the background renders on every new screen (does not happen on back navigation)

I brought this up on a PR and was told it could be because the background gradient is actually an image, which is not loading fast enough in the Dev Build, but wouldn't be a problem in a production build.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/34031697/128552575-d25a6f83-8547-4ae6-ac67-f929879be128.gif)

**Comment by jamonholmgren** [comment]
This could be related to the changes in #1712.

**Comment by jamonholmgren** [comment]
@JayPerfetto Do you notice it in 7.0.x? You can test this by doing `npx ignite-cli@7.0 new MyApp`. If so, it's a regression in 7.1.0.

**Comment by JayPerfetto** [comment]
This is happening on 7.0.0 - I have also seen the pink flashing instead of white flashing on ^7

**Comment by JayPerfetto** [comment]
I also just tried upgrading to 7.1.1, and a fresh create of PizzaApp does not compile on iOS - could I have a typescript version issue or something? I am on typescript 4.3.5
<img width="967" alt="Screen Shot 2021-08-06 at 4 34 42 PM" src="https://user-images.githubusercontent.com/34031697/128580086-a407c0a3-03eb-4878-a965-fa97ba645bc0.png">

**Comment by harrisrobin** [comment]
> I just tried upgrading to 7.1.1, and a fresh create of PizzaApp does not compile on iOS which would seem to be a regression from 7.0.0, and looks like it could be related to the PR you referenced - could I have a typescript version issue or something? I am on typescript 4.3.5
> <img alt="Screen Shot 2021-08-06 at 4 34 42 PM" width="967" src="https://user-images.githubusercontent.com/34031697/128580086-a407c0a3-03eb-4878-a965-fa97ba645bc0.png">

main-navigator.tsx does not exist anymore, which makes me think you may be running an old bundle or having a cache issue. If you generated this project with 7.1.1 (make sure to verify this with ignite-cli -v), then make sure to try restarting your bundle with a `--reset-cache` flag. (react-native start --reset-cache)

**Comment by Kiura** [comment]
I also have the same problem, updated my code from `6.*` to the latest version `7.*`.
Everything works perfectly fine, except when I add a dark theme: the flickering appears as described above.
`--reset-cache` didn't help, manually adding `cardStyle: { backgroundColor: "transparent" }` or `cardStyle: { backgroundColor: color.palette.deepPurple }` didn't help either.

**Comment by jamonholmgren** [comment]
Should be fixed in latest; please file a new issue and reference this one if you’re still running into it. Thanks!
