### ISSUE TITLE
Changes not reflecting until reloading app again in (saga/redux)

### ISSUE THREAD

**Issue by mrshahzeb7** [infinitered/ignite#1760]
changes not reflecting in sage/redux until reloading whole app
for example in sage if I write console.log('') it won't show until I reload whole app
is there any way to solve it because it is slowing down development?

Steps to reproduce:

1.change some thing in sage and dispatch again it won't reflect current change that you did until full reload

---

`npx ignite-cli doctor` results:

```
System
  platform           darwin                                                               
  arch               x64                                                                  
  cpu                4 cores      Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz                


JavaScript (and globally-installed packages)
  node               16.2.0        
  npm                7.13.0        
    expo-cli         4.9.1                            
    ios-deploy       1.11.4                           
    jetifier         2.0.0                            
    nodemon          2.0.9                            
    npm              7.13.0                           
    yarn             1.22.10                          
  yarn               1.22.10      

Ignite
  ignite-cli         7.2.0         
  ignite src         build       

Android
  java               1.8.0_292                          
  android home       -            

iOS
  xcode              12.5.1     
  cocoapods          1.10.1       
```

**Comment by jamonholmgren** [comment]
Hey @mrshahzeb7 , we don't use sagas in the current boilerplate. Are you using an old Andross version?

**Comment by mrshahzeb7** [comment]
yes I am using older version I am thinking of using current boiler plate . I did not change because I don't know how mobs works. kindly can you tell me how to solve the issue and will it solve if I use current boiler plate 
Thank-you

**Comment by jamonholmgren** [comment]
Migrating might be quite a chore. I would say stay with the old version at this point. The new one is a pretty big change.
