### ISSUE TITLE
Path to copy doesn't exist /node_modules/ignite-cli/boilerplate/.gitignore

### ISSUE THREAD

**Issue by adampax** [infinitered/ignite#1776]
What's going on?

Hi, this is my first time trying Ignite. I'm trying the [Quick Start](https://github.com/infinitered/ignite#quick-start) for React Native, and am hitting an error. 

Steps to reproduce

1. `npx ignite-cli new PizzaApp` yields the following:
```
   · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·

    █ Creating PizzaApp using Ignite 7.4.0
    █ Powered by Infinite Red - https://infinite.red
    █ Using ignite-cli
    █ Bundle identifier: com.PizzaApp
    ────────────────────────────────────────────────

    🔥 Igniting app
    🖨  3D-printing a new React Native app
/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Path to copy doesn't exist /Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/boilerplate/.gitignore
    at generateNoSourceError (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/fs-jetpack/lib/copy.js:52:15)
    at checksBeforeCopyingSync (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/fs-jetpack/lib/copy.js:83:11)
    at Object.copySync [as sync] (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/fs-jetpack/lib/copy.js:150:3)
    at Object.copy (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/fs-jetpack/lib/jetpack.js:76:12)
    at /Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/commands/new.js:173:36
    at step (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/commands/new.js:44:23)
    at Object.next (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/commands/new.js:25:53)
    at fulfilled (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/commands/new.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ENOENT'
}
```

`npx ignite-cli doctor` results:

```
System
  platform           darwin                                                  
  arch               x64                                                     
  cpu                12 cores      Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz 
  directory          reactnative   /Users/adam/Dev/scratch/reactnative       

JavaScript (and globally-installed packages)
  node                                    14.17.5       /usr/local/bin/node 
  npm                                     7.21.0        /usr/local/bin/npm  
    @angular/cli                          7.0.3                             
    @aws-amplify/cli                      5.3.0                             
    @loopback/cli                         1.24.0                            
    @openapitools/openapi-generator-cli   1.0.1-4.1.3                       
    @vue/cli                              4.4.4                             
    alloy                                 1.14.6                            
    appcelerator                          5.0.0                             
    dotenv                                8.0.0                             
    eslint                                5.2.0                             
    firebase-tools                        8.6.0                             
    ionic                                 4.0.5                             
    jasmine                               3.1.0                             
    liveview                              1.4.5                             
    n                                     2.1.12                            
    nodemon                               1.18.3                            
    npm                                   7.21.0                            
    swagger                               0.7.5                             
    tisdk                                 2.0.1                             
    tishadow                              2.10.1                            
    titanium                              5.3.2                             
    tiunit                                1.0.0                             
    yarn                                  1.22.10                           
  yarn                                    1.22.10       /usr/local/bin/yarn 

Ignite
  ignite-cli         7.4.0        /Users/adam/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               1.8.0_242-release   /usr/bin/java 
  android home       -                   undefined     

iOS
  xcode              12.5.1     
  cocoapods          1.10.1       /usr/local/bin/pod 

```

**Comment by djdnl13** [comment]
Hello, 

please read this other issue: https://github.com/infinitered/ignite/issues/1578#issuecomment-903811120

By the way, the **new** command in ignite-cli is not working very well so far, wish you luck.

Greetings.

**Comment by shirshak55** [comment]
are they going to fix it? I thought it was fnm or npm issue. Thankfully its not a big deal

**Comment by alastudio** [comment]
> What's going on?
> 
> Hi, this is my first time trying Ignite. I'm trying the [Quick Start](https://github.com/infinitered/ignite#quick-start) for React Native, and am hitting an error.
> 
> Steps to reproduce
> 
> 1. `npx ignite-cli new PizzaApp` yields the following:
> 
> ```
>    · · · · · · · · · · · · · · · · · · 🔥 Ignite 🔥 · · · · · · · · · · · · · · · · · ·
> 
>     █ Creating PizzaApp using Ignite 7.4.0
>     █ Powered by Infinite Red - https://infinite.red
>     █ Using ignite-cli
>     █ Bundle identifier: com.PizzaApp
>     ────────────────────────────────────────────────
> 
>     🔥 Igniting app
>     🖨  3D-printing a new React Native app
> /Users/adam/.npm/_npx/e31027f3785124a8/node_modules/gluegun/build/index.js:13
>     throw up;
>     ^
> 
> Error: Path to copy doesn't exist /Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/boilerplate/.gitignore
>     at generateNoSourceError (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/fs-jetpack/lib/copy.js:52:15)
>     at checksBeforeCopyingSync (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/fs-jetpack/lib/copy.js:83:11)
>     at Object.copySync [as sync] (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/fs-jetpack/lib/copy.js:150:3)
>     at Object.copy (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/fs-jetpack/lib/jetpack.js:76:12)
>     at /Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/commands/new.js:173:36
>     at step (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/commands/new.js:44:23)
>     at Object.next (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/commands/new.js:25:53)
>     at fulfilled (/Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build/commands/new.js:16:58)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
>   code: 'ENOENT'
> }
> ```
> 
> `npx ignite-cli doctor` results:
> 
> ```
> System
>   platform           darwin                                                  
>   arch               x64                                                     
>   cpu                12 cores      Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz 
>   directory          reactnative   /Users/adam/Dev/scratch/reactnative       
> 
> JavaScript (and globally-installed packages)
>   node                                    14.17.5       /usr/local/bin/node 
>   npm                                     7.21.0        /usr/local/bin/npm  
>     @angular/cli                          7.0.3                             
>     @aws-amplify/cli                      5.3.0                             
>     @loopback/cli                         1.24.0                            
>     @openapitools/openapi-generator-cli   1.0.1-4.1.3                       
>     @vue/cli                              4.4.4                             
>     alloy                                 1.14.6                            
>     appcelerator                          5.0.0                             
>     dotenv                                8.0.0                             
>     eslint                                5.2.0                             
>     firebase-tools                        8.6.0                             
>     ionic                                 4.0.5                             
>     jasmine                               3.1.0                             
>     liveview                              1.4.5                             
>     n                                     2.1.12                            
>     nodemon                               1.18.3                            
>     npm                                   7.21.0                            
>     swagger                               0.7.5                             
>     tisdk                                 2.0.1                             
>     tishadow                              2.10.1                            
>     titanium                              5.3.2                             
>     tiunit                                1.0.0                             
>     yarn                                  1.22.10                           
>   yarn                                    1.22.10       /usr/local/bin/yarn 
> 
> Ignite
>   ignite-cli         7.4.0        /Users/adam/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
>   ignite src         build        /Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 
> 
> Android
>   java               1.8.0_242-release   /usr/bin/java 
>   android home       -                   undefined     
> 
> iOS
>   xcode              12.5.1     
>   cocoapods          1.10.1       /usr/local/bin/pod 
> ```

Copy .gitignore file from older version to your directory /Users/adam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/boilerplate/

**Comment by jamonholmgren** [comment]
Hey folks, apologies for how long this has taken. I will be taking a look at this tonight.
