### ISSUE TITLE
support react native 0.65.1, please

### ISSUE THREAD

**Issue by oktorakevinarigi** [infinitered/ignite#1778]
when release version react-native 0.65.1 ?
react-native has been released 0.65.1 

please support react native 0.65.1

thank you

**Comment by markrickert** [comment]
We'll be working on it soon, but unfortunately, an ignited expo version won't support it until the expo sdk supports it.

For now, you can still ignite a new app and then follow the react-native upgrade instructions to upgrade your project. The upgrade path from 0.64.2 to 0.65.1 is _very_ straightforward: https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.65.1

**Comment by nervouscat** [comment]
Hello all, 

I attempted to upgrade from 0.64.2 to 0.65.1
and i got the following error: 
**RCT-Folly/Time.h:52:17: Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')**

Please help!

**Comment by vietanhdtd** [comment]
> Hello all,
> 
> I attempted to upgrade from 0.64.2 to 0.65.1 and i got the following error on ios: **RCT-Folly/Time.h:52:17: Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')**
> 
> Please help!

Delete `Podfile.lock` in ios dir. Then run `pod install` again.

**Comment by crazycoder-io** [comment]
> Working on this now to resolve this error I keep getting: [microsoft/react-native-windows#7451](https://github.com/microsoft/react-native-windows/issues/7451)
> 
> When I try to `yarn add react-native@0.65.1` I get the error:
> 
> ```
> error @jest/create-cache-key-function@27.0.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.3.0"
> ```
> 
> When I run `npx --call "node -v"` I do, in fact, get `v14.3.0`. I upgraded node to `14.15.0` as mentioned in the error but then get a new error:
> 
> ```
> An unexpected error occurred: "expected hoisted manifest for \"metro-react-native-babel-transformer#@babel/core#@babel/helper-compilation-targets#browserslist\"".
> ```

Hello, could you find the solution for second scenario on your comment? I have the same issue and I still could not find out what's wrong!
