### ISSUE TITLE
How can I change navigationbar title?

### ISSUE THREAD

**Issue by manel-jove** [infinitered/ignite#178]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.  Then feel free to delete this comment and above.

- [ ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

**Comment by GantMan** [comment]
each route has the title.  Look at your routes for a title property.

https://github.com/infinitered/ignite/blob/master/ignite-base/App/Navigation/Routes.js

**Comment by manel-jove** [comment]
Oh, I mean update the title of the screen
Thanks!

**Comment by GantMan** [comment]
Ah, from code!

Any screen has access to the title through navigator.

So you could `this.props.navigator.setState({title: 'New Title'})`

**Comment by manel-jove** [comment]
OK! Thank you very much! ;)

**Comment by GantMan** [comment]
cheers!

**Comment by justingosan** [comment]
`this.props.navigator.setState({title: 'New Title'})` doing this overwrites any defined titles in `NavigationBarRouteMapper.js`

I got over it by adding:
```
componentWillUnmount() {
        const { navigator } = this.props
        navigator.setState({
            title: null
        });
}
```
...but it still displays the title up until the scene change animation finishes.

Is there a better way to do this?
