### ISSUE TITLE
Create new app throws Error: Path to copy doesn't exist 

### ISSUE THREAD

**Issue by SteveSultan** [infinitered/ignite#1780]
What's going on?

**Create new app throws error **

**Error: Path to copy doesn't exist : /Users/user/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/boilerplate/.gitignore**

See below image as detailes: 

<img width="919" alt="error" src="https://user-images.githubusercontent.com/59545545/131234938-a6626a43-169b-48dd-ad11-0e6a33560a61.png">

`npx ignite-cli doctor` results:

![image](https://user-images.githubusercontent.com/59545545/131234951-ec511916-b801-4da3-934a-6aa16702a59c.png)

**Comment by pfuersattel** [comment]
Same issue here. Could be related to the latest version 7.4.0.

Creating a new app works when specifying the previous release works for me:
`npx ignite-cli@v7.3.0 new ....`

**Comment by SteveSultan** [comment]
npx ignite-cli@7.3.0 new ....

Worked for me.
