### ISSUE TITLE
Fix boilerplate/ios/HelloWorld.xcodeproj/project.pbxproj to work on Apple M1

### ISSUE THREAD

**Issue by barbieri** [infinitered/ignite#1795]
Please take a look at https://github.com/react-native-community/react-native-template-typescript/issues/223:

In order to build on macOS with M1 (arm64), the `LIBRARY_SEARCH_PATHS` must be changed, see https://github.com/facebook/react-native/commit/a1c445a39c580037ada4a5d194a0d2daef15a25a

- do not exclude `"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "arm64"`
- change `LIBRARY_SEARCH_PATHS` to be:
   - `"\"$(SDKROOT)/usr/lib/swift\""`
   - `"$(inherited)"`
   - `"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"`
   - **Remove:** `"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"`

Worth recommending CocoaPods 1.11 instead of 1.10 as that version includes fixes to newer Xcode.

**Comment by jamonholmgren** [comment]
Closed in #1832
