### ISSUE TITLE
How to get useful stack traces for promises?

### ISSUE THREAD

**Issue by 1mike12** [infinitered/ignite#1796]
What's going on?

Out of the box any errors in promises gives absolutely no information as to what is happening and doesn't really contain a useful stack trace. I've seen this issue posted a lot including in reactotron https://github.com/infinitered/reactotron/issues/646 but what is the recommended way to do this in ignite? Is there something I need to enable?

---

Steps to reproduce

1. throw any error in a promise

---

`npx ignite-cli doctor` results:

**Comment by joshuayoes** [comment]
There has been a lot of changes since this issue last had activity. This is going to be closed for now, but please re-open if this still needs attention.
