### ISSUE TITLE
Conflict with aws-amplify Auth and API modules (Unhandled promise rejection)

### ISSUE THREAD

**Issue by jasiek-net** [infinitered/ignite#1799]
What's going on?

After add AWS amplify (like here https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native/#install-amplify-libraries) and create simple example of `signIn` and `API.get` I've got `Unhandled promise rejection, [RangeError: Maximum call stack size exceeded.]`

Steps to reproduce

1. Install `npx ignite-cli new TobaIgnite --expo`
2. Add aws deps `yarn add aws-amplify aws-amplify-react-native @react-native-community/netinfo @react-native-async-storage/async-storage`
3. Create simple `Auth.signIn` logic
4. There is an anhandled error

I thought that this is `aws-amplify` problem, but I created fresh project with `react-native-cli` and `expo-cli` and everything was OK, only `ignite` boilerplate throw errors. Related issue in `aws-amplify` project: https://github.com/aws-amplify/amplify-js/issues/8957

---

`npx ignite-cli doctor` results:

```
System
  platform           darwin                                                
  arch               x64                                                   
  cpu                4 cores      Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz 
  directory          TobaIgnite   /Users/user/TobaIgnite                   

JavaScript (and globally-installed packages)
  node                         14.15.4      /Users/user/.nvm/versions/node/v14.15.4/bin/node 
  npm                          6.14.10      /Users/user/.nvm/versions/node/v14.15.4/bin/npm  
    @angular/cli               12.0.4                                                        
    @aws-amplify/cli           6.0.1                                                         
    eslint                     7.31.0                                                        
    expo-cli                   4.12.1                                                        
    ignite-cli                 7.5.0                                                         
    json-server                0.16.3                                                        
    ng-up                      3.0.0                                                         
    npm                        6.14.10                                                       
    react-native-cli           2.0.1                                                         
    serverless                 2.60.3                                                        
  yarn                         1.22.5       /usr/local/bin/yarn                              
    bower-away                 1.1.2                                                         
    requirejs-to-webpack-cli   1.0.0                                                         

Ignite
  ignite-cli         7.5.0        /Users/user/.nvm/versions/node/v14.15.4/bin/ignite                        
  ignite src         build        /Users/user/.nvm/versions/node/v14.15.4/lib/node_modules/ignite-cli/build 

Android
  java               13.0.2       /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              13.0       
  cocoapods          1.11.2       /usr/local/bin/pod 
```

**Comment by janhorubala** [comment]
This issue is somehow connected with https://github.com/infinitered/ignite/issues/1745, I removed `ToggleStorybook` and aws services works like a charm (`Auth` & `API`),

**Comment by vankhoa01** [comment]
Hi @jasiek-net @jamonholmgren,
I had other issue with aws-amplify here https://github.com/infinitered/ignite/issues/1939
Do you have any ideas to resolve this? 
Thank you so much

**Comment by joshuayoes** [comment]
There has been a lot of changes since this issue last had activity. Most notably, we have remove Storybook in our latest Ignite Maverick release, which seemed to be the source of this issue. 

This is going to be closed for now, but please re-open if this still needs attention.
