### ISSUE TITLE
Need to fix android title bar element positioning

### ISSUE THREAD

**Issue by markrickert** [infinitered/ignite#18]
### Make sure verify the following before submitting an issue.

- [x] Issue does not already exist
- [x] You have example code or some other reproduce experiment that we can verify

![screenshot 2016-03-28 14 21 53](https://cloud.githubusercontent.com/assets/139261/14085928/90a730de-f4f0-11e5-99ab-253b2d16ca93.jpg)

**Comment by GantMan** [comment]
I just saw that, too
![image](https://cloud.githubusercontent.com/assets/997157/14085999/8e79720c-f4e8-11e5-9f2a-5947bd080d33.png)


Seems padding isn't something Android gives two :hankey: about.  Try margin.

**Comment by skellock** [comment]
![image](https://cloud.githubusercontent.com/assets/68273/14096046/b989b4fc-f533-11e5-9c61-e582711d711e.png)

Seems off on iOS too.

**Comment by GantMan** [comment]
@fvonhoven  this might be good one.
