### ISSUE TITLE
not seeing the "Toggle Storybook" option in the developer menu

### ISSUE THREAD

**Issue by chancesmith** [infinitered/ignite#1807]
What's going on?
I'm not seeing the "Toggle Storybook" option in the developer menu.

![image](https://user-images.githubusercontent.com/4466585/137400023-a385349d-923a-450a-8dd2-dfc4edfc7870.png)

---

Steps to reproduce

1. `npx ignite-cli new PizzaApp --expo --bundle=com.infinitered.pizzaapp`
2. `yarn storybook`
3. `yarn start`
4. open developer menu (CMD + D)
5. expect to see the option "Toggle Storybook"

---

`npx ignite-cli doctor` results:
```
*[master][~/wip/pizzaapp]$ npx ignite-cli doctor
System
  platform           darwin                                                  
  arch               x64                                                     
  cpu                16 cores      Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz 
  directory          pizzaapp   /Users/chance/wip/pizzaapp             

JavaScript (and globally-installed packages)
  node                  14.18.1      /Users/chance/.nvm/versions/node/v14.18.1/bin/node 
  npm                   6.14.15      /Users/chance/.nvm/versions/node/v14.18.1/bin/npm  
    npm                 6.14.15                                                         
  yarn                  1.22.10      /usr/local/bin/yarn                                
    create-react-app    4.0.1                                                           
    ios-deploy          1.11.1                                                          
    npm-check-updates   7.0.2                                                           
    serve               11.3.2                                                          

Ignite
  ignite-cli         7.5.0        /Users/chance/.npm/_npx/822/bin/ignite                        
  ignite src         build        /Users/chance/.npm/_npx/822/lib/node_modules/ignite-cli/build 

Android
  java               13.0.2       /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              12.4       
  cocoapods          1.10.1       /usr/local/bin/pod 
```

**Comment by chancesmith** [comment]
@jamonholmgren any tip or direction to get storybook showing? I'm happy to dig in.

**Comment by bayswaterpc** [comment]
To add to this I'm getting a slightly different issue where storybook is showing a constant "loading story" on the storybook page.

![StorybookEternalLoading](https://user-images.githubusercontent.com/78702667/140648667-d3df5698-4237-4d30-9d9b-f9a25a397bf6.png)

-  `yarn android`
-  `yarn storybook`

I'm using windows 10 and node 16.

**Comment by leonskim** [comment]
@chancesmith Hi there! 
There's a way how to customize the dev menu for the Expo, but it's only for ejected apps(https://docs.expo.dev/development/extending-the-dev-menu/), and there's nothing we could do on managed Expo apps. So I agree with @jamonholmgren about utilizing Reactotron. And yes, it's broken for now but the fix is coming up very soon!
