### ISSUE TITLE
Update/Improve Expo app.json boilerplate settings

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ignite#1809]
What's going on?

We should update the app.json boilerplate to set the root backgroundColor value to match the app background color (just to remove white flash appearing just before the app renders) and other Expo improvements for splash screen rendering and app icons. See https://docs.expo.dev/guides/app-icons/ for guidance.

In addition, `app.json` supports inline comments if you set the language for the file to 'JSON with Comments' in VSCode (using Json5). We should annotate the Expo settings for the benefit of Ignite users.

However, let's consider moving the expo settings to `app.config.ts` (no special effort required to add code comments). Another option to consider: we can use `app.config.ts` in conjunction with `app.json`. See https://docs.expo.dev/workflow/configuration/

**Comment by yulolimum** [comment]
This should be resolved with PR #1965 and later #1987
