### ISSUE TITLE
Migrate unimodules to the expo package

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ignite#1811]
Unimodules for Expo apps is being replaced with a new `expo` package in order to simplify development and package naming conventions, as well as speeding up iOS builds thanks to pre-built libraries for some modules - along with a host of other improvements.

Read about the history of unimodules and the story behind the new `expo` package [here](https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc)

Use this [migration guide ](expo.fyi/expo-modules-migration)for updating the Ignite dependencies.

**Comment by 1mike12** [comment]
the lilnk seems to be dead? Is this the doc it used to point to? https://github.com/expo/fyi/blob/master/expo-modules-migration.md

**Comment by leonskim** [comment]
I'm closing this issue since we migrated unimodules to expo modules. (https://github.com/infinitered/ignite/pull/1830)
