### ISSUE TITLE
[Feature Request]: Migrate AsyncStorage -> MMKV

### ISSUE THREAD

**Issue by kieran-osgood** [infinitered/ignite#1818]
## Feature Request
I get it may not be wanted due to the fact most people know AsyncStorage, but do we think it would be a worthwhile upgrade to migrate from AsyncStorage to [MMKV](https://github.com/mrousavy/react-native-mmkv).

## Pros
- Significantly faster 
- MMKV has encryption support for secure local storage
- Synchronous storage, so simpler application code

## Cons
- Slightly higher learning curve for people adopting ignite (but still easier to use due to synchronous storage)
- Due to the fact it's built on JSI the the Chrome Debugger will no longer work and flipper is the alternative 

## Support
There appears to be an integration for persisting mobx store already too, though I haven't tested this yet  https://github.com/mrousavy/react-native-mmkv/blob/master/docs/WRAPPER_MOBX.md 

Realised a major caveat to it would be that expo is not able to autolink JSI yet, but there appears to be a plugin that can be configured for expo managed projects https://github.com/mrousavy/react-native-mmkv/issues/157 - so again something that would require some investigation if this sounds good.

I wanted to confirm if this is something that is agreed would be desirable, and I'm happy to work on a PR if so!

**Comment by oguzturker8** [comment]
Hi,
In react-native-mmkv [installation](https://github.com/mrousavy/react-native-mmkv/blob/master/INSTALL.md), it says for Android:
> Since react-native-reanimated also uses JSI, there will be conflicts if you install both libraries at the same time. That's why the installation steps are different:

Would be any problem with using ignite x react-native-mmkv x reanimated?
And also i see reactotron also uses AsyncStorage. We need to migrate it too.

**Comment by frankcalise** [comment]
Recipe over at the Ignite Cookbook! https://infinitered.github.io/ignite-cookbook/docs/MigratingToMMKV

**Comment by caiorrs** [comment]
> Recipe over at the Ignite Cookbook! https://infinitered.github.io/ignite-cookbook/docs/MigratingToMMKV

Hey, the link is broken, can you update it please?

**Comment by frankcalise** [comment]
@caiorrs updated! https://ignitecookbook.com/docs/recipes/MigratingToMMKV

**Comment by bi3ri** [comment]
Thanks, @frankcalise, for the tutorial! I've applied your tips. Now, I'm looking to integrate MMKV with Reactotron instead of AsyncStorage [here](https://github.com/infinitered/ignite/blob/db71c8aa102ad191b2108fb82c37d1305bdde627/boilerplate/app/devtools/ReactotronConfig.ts#L31). Any advice on making this switch?

**Comment by frankcalise** [comment]
@bi3ri hey yeah we should update that recipe (would welcome a PR if you want to help confirm and verify the steps!) to include the Reactotron plugin setup documented here: https://docs.infinite.red/reactotron/plugins/react-native-mmkv/
