### ISSUE TITLE
Errors during IOS app startup

### ISSUE THREAD

**Issue by vnovick** [infinitered/ignite#182]
Hey. When I install ignite as described in the readme and then cd to my application folder and run
 `react-native run-ios` I get the following error:

<img width="565" alt="screen shot 2016-06-22 at 5 27 25 pm" src="https://cloud.githubusercontent.com/assets/3762909/16270487/2231ee12-389f-11e6-9bba-a40f0b32aa3e.png">

This is fixed by running
`npm i` inside the directory.
After running 
 `react-native run-ios` again emulator is opened and I get RNI18n.locale error:
<img width="370" alt="screen shot 2016-06-22 at 5 29 48 pm" src="https://cloud.githubusercontent.com/assets/3762909/16270535/546f71c4-389f-11e6-8870-8261f3959ea9.png">

During the install no errors were outputted to console and all checks passed.

Please advise.

**Comment by skellock** [comment]
Bummer.

Can you give us a few versions here to help you debug?

```
node -v
npm -v
ignite -V
rnpm -V
react-native -v
```

**Comment by vnovick** [comment]
node - v5.0.0
npm - 3.3.6
ignite - 1.0.2
rnpm - 1.9.0
react-native - 0.27.2

**Comment by skellock** [comment]
I wonder if something is wrong with that particular version of node?  I switched to 5.0.0 and a simple `react-native init RNHack` doesn't even work.

But it does work on `5.11.1` and the latest 6.x branch of Node.

I don't see anything in the docs in React Native that says problems with 5.0.0.

The easy way out is to upgrade your node.   I like to use `n` for this.  `npm i -g n` then `n 6.2.2`.  Makes it easy to switch node versions.

**Comment by GantMan** [comment]
also, don't forget to kill packager each time.  I've seen that error when I leave packager open between runs for i18n.

**Comment by vnovick** [comment]
Thanks. All works now. I suggest when running ignite generator to check that node version is above 5.11.1
