### ISSUE TITLE
ToggleStorybook vs react-native-camera

### ISSUE THREAD

**Issue by maqeelqureshi** [infinitered/ignite#1826]
react-native-camera library doesn't work inside ToggleStorybook tag.

I am trying to use camera library. Camera component works fine in simple RN project but when I try to use the same in ignite project, it shows black screen. 

Only if I remove the ToggleStorybook parent element in app.tsx than it works fine.

Any suggestion?

**Comment by jamonholmgren** [comment]
We probably need to move the `getStorybookUI` function call into a function and only call it when storybook is activated.

https://github.com/infinitered/ignite/blob/ef5810aac792794ee9102e4e563862145d098ea0/boilerplate/storybook/storybook.tsx#L11-L16

According to @dannyhw from React Native Storybook, it polyfills some things which can be problematic and possibly causing this issue. (Potentially resolved in Storybook 6.x)

**Comment by dannyhw** [comment]
somewhat related issue: https://github.com/storybookjs/react-native/issues/20

**Comment by dannyhw** [comment]
@maqeelqureshi it would be worth checking this on the latest version of ignite since the change in #1906 would probably fix this issue.
