### ISSUE TITLE
How does canExit works?

### ISSUE THREAD

**Issue by callmemonky** [infinitered/ignite#1841]
What's going on?
In app-navigator.tsx, we have canExit functionality, how does it work?
---

Steps to reproduce

1. I tried adding other screen in that, for e.g added "demoList"
2. Now when I am on the "demoList" screen, try to press back, it doesn't work. App doesn't closes. But according to that function it should.
---

`npx ignite-cli doctor` results:

**Comment by leonskim** [comment]
I can confirm that `canExit` isn't functioning as it's supposed to do. I found what's causing it, fix is coming soon.

**Comment by leonskim** [comment]
Fixed by https://github.com/infinitered/ignite/pull/1844, let us know if it still occurs. Thanks!

**Comment by jamonholmgren** [comment]
:tada: This issue is fixed in version 7.8.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ignite-cli/v/7.8.2)
- [GitHub release](https://github.com/infinitered/ignite/releases/tag/v7.8.2)
