### ISSUE TITLE
Why do we have while true in STARTUP action

### ISSUE THREAD

**Issue by ahmed1490** [infinitered/ignite#185]
```
// process STARTUP actions
export function * watchStartup () {
  while (true) {
    yield take(Types.STARTUP)
    const temp = yield select((state) => state.weather.temperature)
    // only fetch new temps when we don't have one yet
    if (!R.is(Number, temp)) {
      yield put(Actions.requestTemperature('San Francisco'))
    }
  }
}
```
Does it have to be inside while(true) block? given that the action is dispatched only once?

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

**Comment by skellock** [comment]
You're right.  The while loop could come out.

**Comment by GantMan** [comment]
@eladnava - I see a commit to something, but no clue what it is?   Was this going to be a PR from you?

**Comment by eladnava** [comment]
@GantMan yeah, but I couldn't find the time to fill out the PR form.

**Comment by GantMan** [comment]
k, I might just take care of it then.  Cheers!
