### ISSUE TITLE
Navigator Naming Convention

### ISSUE THREAD

**Issue by simon-lund** [infinitered/ignite#1854]
What's going on?

When generating a navigator (e.g. "test") the generated file will be named test-navigator.tsx.
However, the generated component's name is Test and not TestNavigator, which would be consistent with the AppNavigator component. 

 I wonder why this is the default case and if there is a reason why generated, custom navigators should not be called navigators.

---

Steps to reproduce

npx ignite-cli generate navigator test

**Comment by jamonholmgren** [comment]
@simon-lund Good question!

I think you're right. It should be `TestNavigator`. Want to submit a PR?
