### ISSUE TITLE
TS Issue on generating new screens

### ISSUE THREAD

**Issue by lvlrSajjad** [infinitered/ignite#1857]
What's going on?

When I generate a new screen using command below, it generates screen without NavigatorParamList more info in following paragraphs.

This is the demo screen:
![image](https://user-images.githubusercontent.com/42815758/147771254-440a3acf-76b5-468c-9f9c-4b00361708cb.png)

This is my generated screen:
![image](https://user-images.githubusercontent.com/42815758/147771306-a10f2038-aee9-4fea-aea2-532798e49d7c.png)

This is the TS issue:
![image](https://user-images.githubusercontent.com/42815758/147771331-f9f89e6b-9a90-426d-88ed-9898c5fad413.png)

Although it is pretty easy to fix but it'd be less confusing if we generated screens with NavigatorParamList ...

Also I had to add this to fix all TS issues:
![image](https://user-images.githubusercontent.com/42815758/147771692-1d9872ab-ea5d-4a3b-82e1-72c8b74bfb3e.png)

---

Steps to reproduce

1. 
```  npx ignite-cli g navigator Splash ```

---

`npx ignite-cli doctor` results:
``` Not needed for this one :-D ```

**Comment by robinheinze** [comment]
Hey @lvlrSajjad, taking a look at this!
