### ISSUE TITLE
Generate screen doesn't work and infinite prints gibberish

### ISSUE THREAD

**Issue by SirDavenport** [infinitered/ignite#1859]
What's going on?
I do the command npx ignite-cli g screen question and this is what I get
![image](https://user-images.githubusercontent.com/35716952/148709113-ebbaa93a-54cc-4405-b0d0-ded9866421f7.png)

---

Steps to reproduce

1. create ignite project using the --expo option
2. npx ignite-cli g screen question
3. watch

---

`npx ignite-cli doctor` results:

**Comment by lovelycbm** [comment]
Same with Mac :(

<img width="3120" alt="스크린샷 2022-01-10 오후 2 46 06" src="https://user-images.githubusercontent.com/46586390/148723025-3cf4f1cd-ae5a-4fc9-a64e-00c5763f18f6.png">

**Comment by JohnLamHK** [comment]
Same here!

**Comment by jensiepoo** [comment]
Same here. Been looking into it all day 😔 

![Screen Shot 2022-01-09 at 10 50 03 PM](https://user-images.githubusercontent.com/4207571/148727582-aa247cfa-93bc-4526-824d-84c9d5730ba3.png)

**Comment by tqyellow** [comment]
I believe this issue is related to the Marak Zalgo Liberty 2 bug.
https://snyk.io/blog/open-source-maintainer-pulls-the-plug-on-npm-packages-colors-and-faker-now-what/
Marak/colors.js#285

**Comment by dragonmaster784** [comment]
Can confirm this is part of the color.js LIBERTY bug.

**Comment by SirDavenport** [comment]
Looks like npm reverted the bad updates, so I reinstalled ignite-cli, and now its working 👍

**Comment by inoxxe** [comment]
> Looks like npm reverted the bad updates, so I reinstalled ignite-cli, and now its working 👍

how to reinstall the ignite-cli completely? i try using npm uninstall but it doesnt work

**Comment by dragonmaster784** [comment]
It seems this has been patched since, so you can close it. 👍
