### ISSUE TITLE
App stops executing next lines of code after network requests

### ISSUE THREAD

**Issue by ibrahimelaradi** [infinitered/ignite#1860]
## What's going on?

I'm waiting for network requests to finish before change the state of the app using mobx actions, I'm using generator functions as described in [here](https://mobx-state-tree.js.org/concepts/async-actions)

Here's a screenshot of logs from Reactotron, there should be a log after the API response that shows the state change
![reactotron](https://user-images.githubusercontent.com/44804830/149186800-aea25f86-f7b6-4948-ab86-984fd607d519.png)

### Action:
```typescript
.actions((self) => ({
  // ...
  signIn: flow(function* (form: CustomerSigninForm) {
    const api = self.environment.apis.guest
    const signinResult = yield api.signinAsCustomer(form) // <= code stops executing here

    // state change (saving token, fetching user details, etc

  }),
  // ...
}))
```

### API method:
```typescript
export class GuestApi extends Api {
  // client config, other methods
  async signinAsCustomer(form: CustomerSigninForm): Promise<SigninCustomerResult> {
    const url = this.base + "/integration/customer/token"
    const params = mapToCustomerSigninRequest(form)
    const response = await this.apisauce.post<string>(url, params) // <-- Code lines after this line don't execute
    if (!response.ok) {
      return getGeneralApiProblem(response) || { kind: "bad-data" }
    }
    return { kind: "ok", token: response.data }
  }
}
```

I'm experiencing this issue with both Android and iOS, however on Android, if I turn off __DEV__ from `cmd + M > Settings` and reload the app it works perfectly fine

I tried running it with minification enabled and the issue still persists, am I doing something wrong?

---

## Steps to reproduce

Will create a reproduction repo if no one has faced this issue before

---

## `npx ignite-cli doctor` results:

![doctor](https://user-images.githubusercontent.com/44804830/149189004-4ba98f65-a5fc-4652-a88f-097e6f6e1c56.png)

**Comment by markrickert** [comment]
Hey @ibrahimelaradi, sorry youre experiencing this. Is your component that is observing the mobx properties wrapped in the `observer()` function from `mobx-react-lite`? 

For example, this won't update:

```jsx
const MyComponent = () => {
  const stores = useStores();
  return (
    <Text>{stores.someStore.observedValue}</Text>
  )
}
```

...but this WILL:

```jsx
const MyComponent = observer(() => {
  const stores = useStores();
  return (
    <Text>{stores.someStore.observedValue}</Text>
  )
})
```

**Comment by ibrahimelaradi** [comment]
Hey @markrickert, all the files I'm using are generated using the CLI and they are by default wrapped inside of `observer()`, also it is worth mentioning that I've tried looking at the state tab of Reactotron and no state change has been recorded after receiving the network response

**Comment by carlosa54** [comment]
Hi @ibrahimelaradi out of curiosity can you remove/comment out the `<ToggleStorybook>` component in app.tsx and see if it works?

https://github.com/infinitered/ignite/blob/10efc3878567926e9466c028c648ddb9e65f6b8d/boilerplate/app/app.tsx#L58-L69

Just in case I had a similar issue and I ended up fixing it by refactoring the file below to use ES6 import instead

https://github.com/infinitered/ignite/blob/10efc3878567926e9466c028c648ddb9e65f6b8d/boilerplate/storybook/toggle-storybook.tsx#L48

**Comment by ibrahimelaradi** [comment]
Hello @carlosa54, I commented out the wrapper and it worked fine, I'll refactor `toggle-storybook.tsx` to use ES6 import
Thank you!
