### ISSUE TITLE
React native getting started link redirects to a Not Found page

### ISSUE THREAD

**Issue by terceser** [infinitered/ignite#1872]
using ignite cli new command

```sh
npx ignite-cli new dummy
```

print out
<pre>
   To get started:
     cd dummy  
     pnpm run android   
   
   To run in Android, make sure you've followed the latest react-native setup
   instructions at <b>https://facebook.github.io/react-native/docs/getting-started.html</b>
   before using ignite. You won't be able to run Android successfully until you have.
   
   Need additional help?
   
   Join our Slack community at http://community.infinite.red.
   
   Now get cooking! 🍽

</pre>

`https://facebook.github.io/react-native/docs/getting-started.html` redirects to a Not Found page

https://github.com/infinitered/ignite/blob/d3a8e96336778899a415dc056150126bda6460fa/src/commands/new.ts#L326

The link should be

```
https://facebook.github.io/react-native/docs/getting-started
```

**Comment by terceser** [comment]
#1873

**Comment by robinheinze** [comment]
PR merged. Closing!
