### ISSUE TITLE
Colors.js infinite loop when trying to initialize new app.

### ISSUE THREAD

**Issue by zamplyy** [infinitered/ignite#1875]
What's going on?
---
I can't see any other issues regarding this, but i think ignite-cli has been affected by Malaks recent changes to Colors.js (https://github.com/Marak/colors.js). When i use npx ignite-cli new PizzaApp all i see is the loop from Colors.js and therefore can't use the cli.
Steps to reproduce

1. Either use npx ignite-cli new PizzaApp or npx ignite-cli doctor

---

`npx ignite-cli doctor` results:
undefined
undefined
undefined
                                   !             H|H|H|H|H           H__________________________________             H|§|§|§|H           H|* * * * * *|---------------------|             H|§|∞|§|H           H| * * * * * |---------------------|             H|§|§|§|H           H|* * * * * *|---------------------|             H|H|H|H|H           H| * * * * * |---------------------|             H|H|H|H|H           H|---------------------------------|          ===============        H|---------------------------------|            /| _   _ |          H|---------------------------------|            (| O   O |)          H|---------------------------------|            /|   U   |          H-----------------------------------             |  =/  |           H              _..._/            H              _|I/|_            H      _______/| H |/_______    H     /           / /          H    |          | | /         |  H    |          ||o||          |  H    |    |     ||o||     |    |  H    |    |     ||o||     |    |  H   Carl Pilcher

**Comment by jamonholmgren** [comment]
Duplicate #1859 -- make sure you are using the latest (`npx ignite-cli@latest new PizzaApp`). <3
