### ISSUE TITLE
Upgrade to React Native 0.67

### ISSUE THREAD

**Issue by vanenshi** [infinitered/ignite#1877]
React native announced their new version `0.67`
can we upgrade the boilerplate react native version?

https://reactnative.dev/blog/2022/01/19/version-067

**Comment by jamonholmgren** [comment]
Working on it now @vanenshi -- thanks!

**Comment by jamonholmgren** [comment]
@vanenshi I'm working on it on stream if you're interested!

YouTube: [https://youtube.infinite.red](https://youtube.infinite.red)
Twitch: [https://twitch.tv/jamonholmgren](https://twitch.tv/jamonholmgren)
