### ISSUE TITLE
[Request] Isolate theme and colours to a react hook, allowing for light/dark theming

### ISSUE THREAD

**Issue by sergioisidoro** [infinitered/ignite#1879]
I'm working on an app with a dark and light theme. It's, I believe, a fairly common pattern nowadays.
I've found that having a react Hook to be a good approach.

```
import { useTheme } from '../hooks/';

const makeRootStyles(colors: any): ViewStyle => {
  return {
    backgroundColor: colors.black,
    flex: 1,
  }
}

const Component ....
   const { colors } = useTheme();
   const componentStyles = makeRootStyles(colors)

  return (
    <Screen style={componentStyles} preset="scroll">
      <Text preset="header" text="home" />
    </Screen>
```

However, if we do that, we lose many of the advantages of the generators, which import directly from the constants.

I'm wondering if there would be a way to implement variable theming with the ignite templates, without losing the advantages of the super helpful generators. Or if it is in the roadmap to isolate the colours / themes into a hook.

**Comment by lindboe** [comment]
Addressed by #2636.
