### ISSUE TITLE
Component auto-image story book dependency on Screen asset (bowser image)

### ISSUE THREAD

**Issue by sergioisidoro** [infinitered/ignite#1880]
If we delete the `welcome` screen, while keeping the component `auto-image` we get an error from the strorybook, as it is importing an asset from the screen.

I feel that a component being dependent on a screen is a bit of a problematic pattern.
Of course the easy solution would be to also delete the auto-image component story book for the component.

Steps to reproduce

1. Start a clean project
2. Delete the screen `welcome` (including all of its dependencies)
3. get an error

**Comment by robinheinze** [comment]
Yep, you're right. The image should be stored in /assets/images, rather than inside the welcome screen since it's used by something other than the screen component. I'll get a PR up shortly.

**Comment by sergioisidoro** [comment]
Thanks a lot for taking the time to address this ☺️ This project is fantastic, and you all made an awesome work :)
