### ISSUE TITLE
Unable to resolve module ./rick.png

### ISSUE THREAD

**Issue by martincpt** [infinitered/ignite#1884]
Repo contains _rick.jpg_ instead of **rick.png**

```
npx ignite-cli new RickConfused
cd RickConfused
yarn
yarn react-native run-ios
```

Error: Unable to resolve module ./rick.png

The problem is that _./app/components/auto-image/_ contains _rick.jpg_ instead of **rick.png**

![rick](https://user-images.githubusercontent.com/4718103/153452574-4edc526c-2bd0-4d26-aba7-3dee831b07d6.jpg)

His face tells everything.

**Comment by jamonholmgren** [comment]
> His face tells everything.

Indeed. 😆 

PR pretty pls? 😇

**Comment by martincpt** [comment]
Ok, sure. This is my first PR. I've submitted it. 😅
