### ISSUE TITLE
Editorconfig file

### ISSUE THREAD

**Issue by ahmed1490** [infinitered/ignite#189]
Since the project follows 2 space tabs, and most other projects I worked on followed 4 space. Its good to have an .editorconfig file for editor to adjust tabs accordingly

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

**Comment by GantMan** [comment]
great suggestion!   It's going out in next release
https://github.com/infinitered/ignite/pull/198
