### ISSUE TITLE
Error installing `ignite-cli` version `7.10.3`

### ISSUE THREAD

**Issue by patevs** [infinitered/ignite#1893]
Attempting to install `ignite-cli` version `7.10.3` throws the following error:

```bash
> npm i -g ignite-cli
npm ERR! code 1
npm ERR! path C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c solidarity
npm ERR! 'solidarity' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
```

---

Steps to reproduce

1. Run: `npm i -g ignite-cli`

---

The error indicates that `solidarity` is not installed but note that even if `solidarity` is installed, `ignite-cli` is still unable to be installed as the following error is thrown:

```bash
> npm i -g ignite-cli
npm ERR! code 3
npm ERR! path C:\Users\User\scoop\persist\nodejs-lts\bin\node_modules\ignite-cli
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c solidarity
npm ERR! No Solidarity Settings Found
npm ERR! Make sure you are in the correct folder or run solidarity onboard to create a .solidarity file for this project.
```

**Comment by takameyer** [comment]
I'm getting this same issue on MacOS.  First I tried with `npx`, which failed silently.  
Then I installed globally and got the following error:
```bash
> npm install -g ignite-cli
npm ERR! code 127
npm ERR! path ***/.nvm/versions/node/v17.4.0/lib/node_modules/ignite-cli
npm ERR! command failed
npm ERR! command sh -c solidarity
npm ERR! sh: solidarity: command not found
```

I have also tried installing `solidarity` globally.  With that I get the following:
```bash
> npm install -g ignite-cli
npm ERR! code 3
npm ERR! path ***/.nvm/versions/node/v17.4.0/lib/node_modules/ignite-cli
npm ERR! command failed
npm ERR! command sh -c solidarity
npm ERR! No Solidarity Settings Found
npm ERR! Make sure you are in the correct folder or run solidarity onboard to create a .solidarity file for this project.
```

I've tried with npm 6/7 and node 14/15/16/17.

**Comment by Lektrion** [comment]
It seems to be a postinstall problem witch means ignite-cli still install itself correctly. 

I ran `npm i -g solidarity`
then `npm i -g ignite-cli --force` (to overwrite existing content) 

then when running `npx ignite-cli new igniteRealm --expo` 

```
 Creating igniteRealm using Ignite 7.10.3
    █ Powered by Infinite Red - https://infinite.red
    █ Using expo-cli with yarn
    █ Bundle identifier: com.igniteRealm
```

ignite-cli version = 7.10.3 ... i dont know if the solidarity error will be a problem further in the process.

**Comment by Ppang0405** [comment]
I have same issues.

**Comment by chadwpry** [comment]
I've run into this same issue on both a macOS and Windows 10 WSL environment while using npx. It seems to be an issue solely related to 7.10.3, although I've not been able to identify the culprit. Running npx ignite-cli@7.10.2 is working alternative at the moment.

**Comment by allaniftrue** [comment]
> npx ignite-cli@7.10.2

`npx ignite-cli@7.10.2 new PizzaApp`

works!

**Comment by jamonholmgren** [comment]
I'm getting this same error -- will look into it tonight!

**Comment by jamonholmgren** [comment]
Looks like it was introduced in #1882.

**Comment by jamonholmgren** [comment]
It appears to be working with 7.10.4. Please give it a go and let me know!

<img width="922" alt="image" src="https://user-images.githubusercontent.com/1479215/154196163-58f602da-4da8-4fb0-aa60-e2d3917fe8ae.png">

**Comment by patevs** [comment]
> It appears to be working with 7.10.4. Please give it a go and let me know!
> 

Version `7.10.4` installs and works as expected, thank you!

**Comment by chadwpry** [comment]
I've been able to successfully execute in a Windows WSL and macOS environment using version 7.10.4 using npx ignite-cli 👍
