### ISSUE TITLE
Anyone was able to make flipper work?

### ISSUE THREAD

**Issue by silencer07** [infinitered/ignite#1896]
Basically I followed this steps on freshly-generated PizzaApp with `--expo` flag.

https://blog.expo.dev/developing-react-native-with-expo-and-flipper-8c426bdf995a

Having "No Application Detected" error in Flipper.

Tried upgrading latest expo via `expo upgrade`. tried matching the flipper version to flipper desktop app.

No Bueno. 

Anyone?

**Comment by finnmerlett** [comment]
> @jamon and Joel configured and used flipper with ignite in this video, https://www.youtube.com/watch?v=XvzMGhy3Sos

Whilst I appreciate the link, with no timestamp, no video comments and basically no description it's kinda useless - I can't search through over an hour of video just to find the right 30 seconds I need :worried:

**Comment by finnmerlett** [comment]
Okay I found it, it's around the 40 minute mark. However it's clear they're using a non-expo project, so the setup is different and not directly transferable to an expo project. Still haven't got Flipper working with my ignite expo setup...

**Comment by frankcalise** [comment]
@finnmerlett have you managed to get Flipper working on your Expo project? Keep in mind you'll probably have to build your own expo-dev-client to get this working. Here are some walk throughts:

https://blog.expo.dev/developing-react-native-with-expo-and-flipper-8c426bdf995a
https://github.com/jakobo/expo-community-flipper

**Comment by frankcalise** [comment]
I'm going to close this issue due to inactivity. However, if you have any issue in the future with the latest version of Ignite, please open a new issue stating the problem and the output of `npx ignite-cli doctor`.

Also, you can check out https://community.infinite.red to get help with us (and a bunch of other RN devs!) directly in Slack.
