### ISSUE TITLE
Cannot start sample project

### ISSUE THREAD

**Issue by WilsonChiang** [infinitered/ignite#190]
Running a fresh install of NPM and Node. Can start a normal RN project, but using ignite i get the following:

<img width="394" alt="screen shot 2016-06-23 at 6 32 38 pm" src="https://cloud.githubusercontent.com/assets/620386/16322883/67c789ca-3974-11e6-8f56-91b7f60f3794.png">

```
[6:57:20 PM] <START> find dependencies
transformed 989/990 (100%)[6:57:20 PM] <END>   find dependencies (500ms)
NotFoundError: Cannot find entry file global code@http://localhost:8081/index.ios.js in any of the roots: ["/Users/wilson/Documents/test"]
    at DependencyGraph._getAbsolutePath (/Users/wilson/Documents/test/node_modules/node-haste/lib/index.js:288:13)
    at /Users/wilson/Documents/test/node_modules/node-haste/lib/index.js:226:30
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by GantMan** [comment]
Hey!  this is a temporary bug due to a mistake, we'll have this fixed in a jiffy.  Will update ticket here.  Sorry about this!   Some code got pushed that shouldn't have.

**Comment by WilsonChiang** [comment]
Ah thanks so much for your fast response! Real excited to try out ignite and was trying to figure out why it wouldn't work :)

**Comment by GantMan** [comment]
if you want to fix it locally, just open package.json and switch it down to `0.27.2` - looks like `0.28` has a small issue.

**Comment by GantMan** [comment]
O, and you'll need to `npm install` again.

**Comment by GantMan** [comment]
ok, Master is fixed :)
