### ISSUE TITLE
Expo publish fails on fresh install

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [infinitered/ignite#1904]
On a brand new ignite expo project, running `expo publish` results in the following error
```
Processing asset bundle patterns:
- /Users/user/Documents/projects/PizzaApp/**/*

Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')
    at _configureExpForAssets (/Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/lib/node_modules/expo-cli/node_modules/xdl/src/ProjectAssets.ts:168:26)
    at exportAssetsAsync (/Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/lib/node_modules/expo-cli/node_modules/xdl/src/ProjectAssets.ts:229:3)
    at Object.publishAsync (/Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/lib/node_modules/expo-cli/node_modules/xdl/src/project/publishAsync.ts:93:3)
    at actionAsync (/Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/lib/node_modules/expo-cli/src/commands/publish/publishAsync.ts:103:18)
```

This is an old [expo-cli issue](https://github.com/expo/expo-cli/issues/179) but one that should not happen in newer sdk's.
Non of the solutions from the original issue works.

in app.json you can change `assetBundlePatterns` from `**/*` to `assets/*` to make it run without error, but none of the assets will be uploaded or available in the build. Furthermore the ignite boilerplate places assets in lots op places, not only in the assets folder.

Im thinking it has something to do with dependencies or babel setup 🤔
Installing a clean expo TS project (non-ignite)  with the same sdk from ignite, does not produce the error.

---

Steps to reproduce

You need to have a logged in expo account to publish.
```
npx ignite-cli new PizzaApp --expo
cd PizzaApp
expo publish
```
---

`npx ignite-cli doctor` results:

```
System
  platform           darwin
  arch               arm64
  cpu                8 cores      Apple M1
  directory          PizzaApp     /Users/alexanderlindkjaer/Documents/LindkjaerProjects/PizzaApp

JavaScript (and globally-installed packages)
  node               16.14.0      /Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/bin/node
  npm                8.3.1        /Users/alexanderlindkjaer/.nvm/versions/node/v16.14.0/bin/npm
    corepack         0.10.0
    expo-cli         5.2.0
    npm              8.3.1
  yarn               1.22.17      /opt/homebrew/bin/yarn
  pnpm               -            not installed

Ignite
  ignite-cli         7.10.5       /Users/alexanderlindkjaer/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/alexanderlindkjaer/.npm/_npx/e31027f378
```

**Comment by AlexanderLindkjaer** [comment]
Found the culprit after hours of poking at files. It's the `metro.config.js` file.  I took the advice from the comments in that file and deleted the file and the dependencies it used. Now Expo published assets fine.  

So thats a workaround to get i working 🙂 Will leave the issue open, as the default boilerplate should work with `expo publish` out-of-the-box.

**Comment by robinheinze** [comment]
Hey @AlexanderLindkjaer, thanks for solving that! Do you have any idea which part of that config was the issue?

**Comment by AlexanderLindkjaer** [comment]
@robinheinze 

The whole makeMetroConfig() call makes it not publish
```js
module.exports = (async () => {
  const defaultConfig = await getDefaultConfig()
  //   return makeMetroConfig({ <--- commenting this out will make it publish
  //     projectRoot: __dirname,
  //     resolver: {
  //       resolveRequest: MetroSymlinksResolver(),
  //       assetExts: [...defaultConfig.resolver.assetExts, "bin"],
  //     },
  //   })
})()
```


If you do it a more traditional way of just exporting an object, instead of a async function returning  makeMetroConfig(...)
it publishes fine. the `const defaultAssetExts` is i bit dirty, but skips the async await.

```js
// get defaults assetExts array
const defaultAssetExts = require("metro-config/src/defaults/defaults").assetExts

module.exports = {
  projectRoot: __dirname,
  resolver: {
    resolveRequest: MetroSymlinksResolver(),
    assetExts: [...defaultAssetExts, "bin"],
  },
}
```

Disclaimer: I dont use pnpm or any monorepo stuff, so i dont know if the provided solution still gives the desired results 🙂
