### ISSUE TITLE
How to use Generator based on Custom Template by path

### ISSUE THREAD

**Issue by steve21124** [infinitered/ignite#191]
- [x ] ignite base application
  - [x ] ignite the cli
  - [x ] ignite generated code

Current generator
ignite generate component SmoothButton  .... then it use
ignite/ignite-generator/component/templates/component-style.js.template
ignite/ignite-generator/component/templates/component.js.template

How to use generator to pick component template from custom path
ignite generate component SmoothButton  --path "/path_to_my_custom_component"  

Reason to use above, if my component style is not similar to default component, I would like to customize according to my need.

**Comment by GantMan** [comment]
I like what you're saying @steve21124 - let's chat about it!

The component generator is for making a clean and simple component for placeholding.   Is it that your component often has different imports?  Or is it a fundamental differing opinion?

If fundamental differing opinion, I'd love to see a the differences, so we can improve our component.

If it's something project specific, I would love to hear about it, so we can make the perfect example!

Sounds good?

**Comment by steve21124** [comment]
Good point. I think the "variation of component" might be different from project to project. some project might not used standard component button and want to enhance it. 
Yes, to enhance a component can be done in several ways.

A. For example. let's assume we want to integrate
https://github.com/mastermoo/react-native-action-button
https://gist.github.com/steve21124/545eafd895d68b4a97ccd7e2e2460b06 => component content
https://github.com/infinitered/ignite/blob/master/ignite-generator/component/templates/component.js.template => component from ignite
1. It will have different import, 
2. it will have different view.

B. Now let's say, I need to create radio button
https://github.com/moschan/react-native-simple-radio-button
1. it will have different import
2.  it will have different view.

I am think in the route of "instead of keep modifying component after generating it, would it be nice given a path to my component template and it will use it instead". This will make it very flexible to any requirement changes in the future. just update component template without needing to change anything in the core.

**Comment by steve21124** [comment]
another example
C. create a button as drop down
https://github.com/alinz/react-native-dropdown
1. different import
2. different content.

**Comment by GantMan** [comment]
I like it.  We're going to have to think for a bit on the best way to solve this, but it's a great request!

**Comment by steve21124** [comment]
Thanks this is not urgent. just when have time. I look at the generator code
https://github.com/infinitered/ignite/blob/master/ignite-generator/Generator.js#L68
In line 68, I think by calling this directly Generator.js, I will be able to customize it to take from my custom template?

**Comment by steve21124** [comment]
I start checking out ignite generator package and how to compile 
compile ignite package
https://github.com/infinitered/ignite/blob/master/ignite-generator/package.json

npm run compile
<pre>
> generator-react-native-ignite@1.0.0 compile /Users/steve/junk4/ignite/ignite-generator
> babel -d ./ src/

You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall babel
    npm install babel-cli

See http://babeljs.io/docs/usage/cli/ for setup instructions.

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/steve/.nvm/versions/node/v6.0.0/bin/node" "/Users/steve/.nvm/versions/node/v6.0.0/bin/npm" "run" "compile"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! generator-react-native-ignite@1.0.0 compile: `babel -d ./ src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the generator-react-native-ignite@1.0.0 compile script 'babel -d ./ src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the generator-react-native-ignite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel -d ./ src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs generator-react-native-ignite
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls generator-react-native-ignite
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/steve/junk4/ignite/ignite-generator/npm-debug.log
</pre>

babel Generator.js --out-file test.js  => this create just create a test.js like Generator.js

**Comment by GantMan** [comment]
hey bud!

So you're looking at how to edit the generators yes?

All code is in the `/src` folder.   Then you can (while inside the generator folder) run `npm run compile` which will compile the code down (if you have everything ready to go)  and then you'll need to `npm link`

To be honest, I need to write a doc on contributing.   Perhaps we can screen share and I can get you started, which would help me get the doc going.

**Comment by steve21124** [comment]
Thanks, able to compile it now and if have time, will start experimenting in modifying it. right now, since try to understand the internal working of it.

**Comment by GantMan** [comment]
yup, a lot of moving parts, but fundamentally easy once you have them all figured out.

**Comment by jsheets** [comment]
Any progress on this? I was interested in customizing the ignite templates a bit for my personal use. Mainly to cut down on the minor tweaks I do to every new component, like adding semicolons, adding PropTypes and View to the React imports, etc.

Also interested in creating some commonly used component wrappers, like for Buttons or Images. Would it maybe be easier for me to create standalone yo generators for that, rather than going through ignite-cli?

**Comment by GantMan** [comment]
@steve21124 and @jsheets - lots of progress on this as we grow closer to 2.0

See PR: #498

**Comment by skellock** [comment]
We now have `ignite spork` if you want to tweak the templates just a bit.  We also have plugins where you can make your own generators!  All in 2.0.  Coming soon!
