### ISSUE TITLE
app-navigator should be observer component to detect MST 

### ISSUE THREAD

**Issue by MusabBasheer** [infinitered/ignite#1918]
What's going on?
app-navigator does not listen to MST changes  
---

Steps to reproduce
1. use any store inside app-navigator
2. inside app-navigator UI use store prop to show UI based on conditions like 
 {authenticationStore.isAuthenticated ?
                `<AppStack/>`
                :
               ` <AuthStack />`
            }
3- observe no change happened when store prop value changed.

**Comment by conoremclaughlin** [comment]
We bumped into this issue as well with swapping stacks. AppNavigator currently does not re-render. Likely related:
https://stackoverflow.com/questions/71257766/rerender-appnavigator-on-state-change

**Comment by yulolimum** [comment]
Fixed! will be released in [Ignite v8: Maverick](https://github.com/infinitered/ignite/milestone/19)
