### ISSUE TITLE
Use npm git hooks as package instead of standalone

### ISSUE THREAD

**Issue by enapupe** [infinitered/ignite#192]
in `ignite base application`, it is better to use a npm package like https://www.npmjs.com/package/ghooks or https://www.npmjs.com/package/pre-commit to handle git hooks instead of an isolated solution (like `brew install git-hooks`), this way, cloning and installing the project guarantees the hooks are in place.

**Comment by GantMan** [comment]
Good suggestion.  I'll give this a look tomorrow.

**Comment by GantMan** [comment]
completed in #247
