### ISSUE TITLE
No Generators Detected

### ISSUE THREAD

**Issue by amorain2** [infinitered/ignite#1921]
I am unable to use the ignite generate commands, whenever I attempt to, I get the error dialog shown in the attached image.
![image](https://user-images.githubusercontent.com/38302038/161681096-56d750e7-9bf6-4860-b2d2-d4ed44ac4927.png)

---

Steps to reproduce

1. Install a new ignite app using npx ignite-cli new PizzaApp --expo
2. Run ignite generate

---

`npx ignite-cli doctor` results:
![image](https://user-images.githubusercontent.com/38302038/161681370-121df996-650c-4981-a897-9b4bd151bc7e.png)

**Comment by robinheinze** [comment]
@amorain2 Based on your ignite doctor, it looks like you have an old global version (3.5.3) of ignite-cli installed. Can you remove that and try again?

**Comment by amorain2** [comment]
Updating solved the problem! Thanks for the suggestion! Not sure how that happened
