### ISSUE TITLE
Improve troubleshooting experience

### ISSUE THREAD

**Issue by robinheinze** [infinitered/ignite#1924]
Some troubleshooting improvements:
 
- In https://github.com/infinitered/ignite#troubleshooting, mention the need to uninstall global versions of ignite CLI
- Link to https://github.com/infinitered/ignite#troubleshooting from the GH issue template
- In troubleshooting docs, suggest running with `--debug`, and running `yarn solidarity`

**Comment by frankcalise** [comment]
Added in #2006
