### ISSUE TITLE
Solidarity failures cause confusing error on Ignite new

### ISSUE THREAD

**Issue by robinheinze** [infinitered/ignite#1927]
While debugging #1912, I noticed that any solidarity failures (like incorrect cocoapods version for example) cause Ignite new to fail very vaguely. 

Steps to reproduce

1. Set cocoapods version to 1.10
2. Run `npx ignite-cli new Pizza App`

**Comment by GantMan** [comment]
You can loosen the solidarity rules, or even remove solidarity completely imo.

**Comment by robinheinze** [comment]
It's still nice to have to ensure folks have the right environment, I just need to figure out why the actual error isn't bubbling up through Gluegun.

**Comment by yulolimum** [comment]
@jamonholmgren since Solidarity is removed, this issue could be closed?
