### ISSUE TITLE
Ignite Doctor new feature: show Expo version

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1928]
It would be useful to add the current Expo version to the `ignite-cli doctor` output.

Relatively straightforward update, if anyone wants to take this on.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/1479215/164046242-609c2d1a-44cf-49db-9e53-e3b4b456255e.png">

**Comment by robinheinze** [comment]
@jamonholmgren `expo-cli` version is in there already. Are you talking about a different Expo version?

**Comment by frankcalise** [comment]
I think he's referring to the Expo SDK version here. Similar to what you would get in the output of `npx expo-env-info` from a project directory, ie: `expo: 42.0.0`
