### ISSUE TITLE
Explore merging Expo and vanilla templates

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1933]
With [Expo Prebuild](https://docs.expo.dev/workflow/expo-cli/#expo-prebuild), you can now run your app as Expo *and* from the RN CLI.

Right now, we use different CLI depending on whether you pass in `--expo` or not. It makes several changes based on that decision, and some packages (like react-native-mmkv) can't be included in the Expo version because of Expo managed app limitations.

@yulolimum's reply on #1920 is relevant: https://github.com/infinitered/ignite/pull/1920#pullrequestreview-949350813

This approach creates bugs in Ignite because we have to test changes in Expo and vanilla every time. As of Ignite 6, you can run the boilerplate from the Ignite source, which is nice, but it is vanilla-only, not Expo.

With all this said, there's an opportunity here to create a boilerplate that works with both. This issue will be the central place to discuss if this could be done, and what needs to be done, to make this happen.

**Comment by jeremyspritelyco** [comment]
Does anyone work on this issue?

**Comment by frankcalise** [comment]
@jeremyspritelyco it is being tracked here https://github.com/infinitered/ignite/issues/1983

@jamonholmgren should we close this?

**Comment by frankcalise** [comment]
Closed by https://github.com/infinitered/ignite/pull/1985
