### ISSUE TITLE
Performance stack navigation when use enableScreens()

### ISSUE THREAD

**Issue by vfa-khuongdv** [infinitered/ignite#1934]
Performance stack navigation when use enableScreens()

By default enableScreens() turn on, the animation when I navigate to other screen it will make app slow than I turn off enableScreens(false).

**Comment by joshuayoes** [comment]
There has been a lot of changes since this issue last had activity. We have release a new major version of Ignite, codenamed Maverick. This is going to be closed for now, but please re-open if this still needs attention.
