### ISSUE TITLE
yarn iOS fail on ignite-cli v7.10.9, node lts v16.15.0

### ISSUE THREAD

**Issue by HidePoSy** [infinitered/ignite#1936]
What's going on?

Could not run sample project created with "npx ignite-cli new PizzaApp" command.
I just clean install back my mac to Big Sur, due to there is a need to use Xcode version 12.4, but after I reinstall everything (homebrew, cocoapod, node, etc.), issue occurs.
I can no longer even run a simple sample project with "yarn iOS" now.

From what I can see from the terminal description, seems to have something to do with "Flipper-Folly".
I spend an entire day trying different node version, and downgrade to ignite-cli v7.9.*, but issues still occur. 

---

Steps to reproduce

1) Make sure using node version v16.15.0 (LTS) & ignite-cli v7.10.92. 
2) Create the sample project with "npx ignite-cli new PizzaApp"
3) cd into the project, then run "yarn ios"
---

error screenshots:

<img width="1440" alt="Screenshot 2022-05-05 at 4 09 09 PM" src="https://user-images.githubusercontent.com/67035526/166887353-6db3e9fd-1d9d-46cf-a587-6aa5b9aa014c.png">
<img width="1440" alt="Screenshot 2022-05-05 at 4 10 00 PM" src="https://user-images.githubusercontent.com/67035526/166887362-5f4b1a33-b7c1-4a7a-bc07-7b6f9b72bdd1.png">

`npx ignite-cli doctor` results:
<img width="1440" alt="Screenshot 2022-05-05 at 4 15 14 PM" src="https://user-images.githubusercontent.com/67035526/166887367-ac4da2c3-fcfa-4f1e-9680-63b37ca1bb20.png">

**Comment by HidePoSy** [comment]
I manage to overcome this issue by avoiding ignite-cli 7, and directly creating a new project with a stable version of ignite-cli 6 instead like this:

`npx ignite-cli@6.12.2 new PizzaApp`

I also have to make sure to remove any other version of ignite-cli from my mac, so that my mac will automatically only use ignite-cli 6.12.2.

`npm uninstall ignite-cli -g`
`npm install ignite-cli@6.12.2 -g`

I am not sure that ignite-cli 7 is unstable, or has terrible compatibility with Xcode 12.4.
But clearing my system of ignite-cli 7 seems to have solved this issue.

**Comment by myfoostrong** [comment]
I'm experiencing what I believe is the same issue. I just reformatted my Macbook, so fresh setup via: https://reactnative.dev/docs/environment-setup
Using NVM for Node

Repro
`
npx ignite-cli new test
cd ./test
npm run ios
`

Last lines of build output:
`
The following build commands failed:
	CompileSwift normal x86_64 (in target 'ExpoLinearGradient' from project 'Pods')
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'ExpoLinearGradient' from project 'Pods')
(2 failures)
`

npx ignite-cli doctor
`
System
  platform           darwin                                                
  arch               x64                                                   
  cpu                12 cores     Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 
  directory          test         /Users/conor/work/dev/testing/test       

JavaScript (and globally-installed packages)
  node               16.15.0      /Users/conor/.nvm/versions/node/v16.15.0/bin/node 
  npm                8.5.5        /Users/conor/.nvm/versions/node/v16.15.0/bin/npm  
    corepack         0.10.0                                                         
    npm              8.5.5                                                          
  yarn               -            not installed                                     
  pnpm               -            not installed                                     

Ignite
  ignite-cli         7.10.9       /Users/conor/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/conor/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               11.0.15      /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              13.3.1     
  cocoapods          1.11.3       /usr/local/bin/pod 
`

**Comment by myfoostrong** [comment]
So, I was able to get a fresh build running on `ignite-cli@7.10.2`

`npx ignite-cli@7.10.2 new test10.2`

7.10.3 npm reported a breaking issue, and bails
7.10.4-9 all result in the same error above when building

**Comment by nesjett** [comment]
Can confirm It's not workig for me to run on windows (Android) and M1 (IOS) in version 7.10.9, but It works on ignite-cli 7.10.2.

Different error but also related with Expo modules (linearGradient)
Opening a new issue because its not the exact same error https://github.com/infinitered/ignite/issues/1948

**Comment by myfoostrong** [comment]
I will give this a try later.

My tests were done on an Intel Macbook. And similar errors for Android on Mac and Windows with ExpoLinearGradient.

**Comment by frankcalise** [comment]
@myfoostrong @HidePoSy @nesjett Have you been able to check out the latest version of Ignite 7.14.2 and see if this is still an issue for you?

**Comment by frankcalise** [comment]
Closing this issue due to stale activity.

Also, v8 has been released! So please try the new version and feel free to open another issue should you still be experiencing trouble.
