### ISSUE TITLE
Problem with aws-amplify 

### ISSUE THREAD

**Issue by vankhoa01** [infinitered/ignite#1939]
**What's going on?**

After add AWS amplify (like here https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native/#create-a-new-react-native-app) and call function Amplify.configure(config), I got error below:
<img width="946" alt="Screen Shot 2022-05-09 at 17 18 29" src="https://user-images.githubusercontent.com/8953129/167391146-59cddfd6-d327-4c8a-8ef4-bbb2d70c4bfc.png">

**Steps to reproduce**

1. Install npx ignite-cli new DamageAssessment
2. Add aws libraries: npm install aws-amplify aws-amplify-react-native amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage @react-native-picker/picker
3. Call function Amplify.configure(config)
4. There is an error

I created fresh project with react-native-cli and expo-cli and everything was OK, only ignite boilerplate throw errors
I tried some solution here https://github.com/infinitered/ignite/issues/1799#issuecomment-934267102, but can not resolve my issue
`npx ignite-cli doctor` results:

<img width="832" alt="Screen Shot 2022-05-09 at 17 25 50" src="https://user-images.githubusercontent.com/8953129/167391720-e5adc2cf-0c10-44c9-b4be-275f9f05b089.png">

**Comment by awgrass** [comment]
I got the same problem. I solved it by extending the resolver object inside my metro.config.js to recognize the .mjs filetype among others like so:

module.exports = (async () => {
  const defaultConfig = await getDefaultConfig()
  return makeMetroConfig({
    projectRoot: __dirname,
    resolver: {
      resolveRequest: MetroSymlinksResolver(),
      assetExts: [...defaultConfig.resolver.assetExts, "bin"],
      sourceExts: ["jsx", "js", "ts", "tsx", "mjs"],    <----- This is what I added
    },
  })
})()

**Comment by awgrass** [comment]
As soon as the problem is solved with the fix I described above, the next problem pops up in the metro console:

```
ERROR  Error: secure crypto unusable, insecure Math.random not allowed
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```
It works with a fresh create-react-native-app setup, but not with Ignite. Is there maybe some tempering with global variables that overwrites behavior in amplify configure?

**Comment by vankhoa01** [comment]
Hi @awgrass : Thank you very much for your supporting

I tried with your solution and it's working well know

**Comment by vankhoa01** [comment]
Hi @awgrass : Did you get this issue https://github.com/aws-amplify/amplify-js/issues/5539 when you are working with aws-amplify ?

**Comment by vankhoa01** [comment]
Hi, my aws amplify issues came from *custom metro config* with *@rnx-kit*
Currently, I removed *@rnx-kit* to resolve my issue

Thank all for supporting :)
