### ISSUE TITLE
Bulk load image asserts into Images file

### ISSUE THREAD

**Issue by fvonhoven** [infinitered/ignite#194]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

`ignite g imagesfile`

Iterate over all images in `/Images`
**Remove `@1x`, `@2x`, `@3x`
Unique to remove duplicates
Generate camelCase names
Create new images object with key: camelCaseName, value: filepath/old_name (R.assoc(k: v))
Merge existing images object with new images object where value is unique**
Write new images file - merged object

**Comment by GantMan** [comment]
YAYYYY RAMDA FUN

This will get you the object, just not the merge.
http://goo.gl/KfEVPj

**Comment by GantMan** [comment]
@skellock - I know I cheaped out by using chained .replace, don't kick me.

**Comment by GantMan** [comment]
This was released in 1.2.0 and in version 1.2.1 automatic image mocking was accompanied.
