### ISSUE TITLE
Brand new app - Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1942]
### Discussed in https://github.com/infinitered/ignite/discussions/1941

<div type='discussions-op-text'>

<sup>Originally posted by **papadi** May 12, 2022</sup>
When I'm creating a new app (npx ignite-cli new MyTestApp --expo) and run it on the browser without any modification of my own (yarn web) then I get this error in my browser console.

"Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function."

Any idea why? I cannot detect where it's coming from.</div>

**Comment by jamonholmgren** [comment]
@papadi FYI ^^

**Comment by emanual4real** [comment]
Did you still need help?
