### ISSUE TITLE
Boilerplate Enhancement: Crash Reporting

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1945]
Crash reporting is one of the first things we add to new Ignite projects. It would be great to have a defined place to add this.

My current idea is to add a `crash-reporting.ts` file to the boilerplate with some comments:

```ts
/**
 * This is where you put your crash reporting service initialization code.
 * If you're using Crashlytics: <link to Crashlytics docs>
 * If you're using Sentry: <link to Sentry docs>
 * If you're using Bugsnag: <link to Bugsnag docs>
 */
```

We could potentially add a generic interface that works with all three of those systems, so it's easier to swap them in and out:

```ts
export function reportCrash(error) {
  // Sentry.captureException(error)
  // crashlytics().recordError(error)
  // Bugsnag.notify(error)
}
```

Open to additional feedback on this. I would recommend putting this file in [`app/config/crash-reporting.ts`](https://github.com/infinitered/ignite/tree/master/boilerplate/app/config)

**Comment by frankcalise** [comment]
Implemented in #1996

Will be included in Ignite v8: Maverick #1987
