### ISSUE TITLE
Expo EAS build fails on fresh project

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [infinitered/ignite#1946]
Both Android and IOS EAS builds fails with default expo ignite boilerplate. 
---
The reason is these two command in [postInstall](https://github.com/infinitered/ignite/blob/master/boilerplate/bin/postInstall) 

```js
// Make sure we're set up correctly
{ command: "solidarity" },

// on iOS, make sure our native modules are installed
{ command: "pod install", cwd: "ios", onlyPlatforms: ["darwin"] },
```

EAS build environment fails the solidarity check, and on IOS it tries to run pod install even though there is no Podfile. Not sure how their builds works under the hood.
Quick fix for anybody looking is to just comment out those two commands.

EAS is heavily pushed by expo as the new build standard over `expo build`, so it should properly work out of the box for ignite expo projects. It has some [built-in environment variables](https://docs.expo.dev/build-reference/variables/#built-in-environment-variables) that maybe could be used to check if its running on EAS servers.

As said, it works if i comment out the two commands, so feel free to close. Thanks for the great boilerplate ! 😃

**Comment by frankcalise** [comment]
@AlexanderLindkjaer Thank you for the write up! Could you provide us with a little more information so we can tackle this correctly? Please run `npx ignite-cli doctor` and provide the output.

Also if you have any screenshots as to what step the EAS build failed from Expo's dashboard that would be helpful also, for example:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/374022/185228841-6a5ee84b-4361-42a6-bf19-962de355da47.png">

**Comment by frankcalise** [comment]
I've tested an `eas build -p android --profile preview` for example in our `maverick` branch and it worked successfully (solidarity is removed). However one thing to note is that the prebuild step did not run (and this is due to our merge of vanilla RN and Expo in the boilerplate). 

```
Skipped running "expo prebuild" because the "android" directory already exists. Learn more about the build process: https://docs.expo.dev/build-reference/android-builds/
```

**Comment by AlexanderLindkjaer** [comment]
@frankcalise I've just created a brand new project to test out. Both Android and IOS eas build fails, but due to other reasons than the original issues. The postinstall script does not seem to cause trouble anymore.

The only thing i've done is
```
npx ignite-cli new PizzaApp --expo
cd PizzaApp
eas build
```
In the eas build command, I build for both platforms and did the first-time default options.
----------
`npx ignite-cli doctor` 
![screenshot 26](https://user-images.githubusercontent.com/33224052/186650644-b4a54447-a4a7-47b4-ae2c-042e3fba9ce4.png)
These are only those that are relevant, since EAS servers have their own system/javascript/android/ios versions. I dont know what those are.
----------
The IOS build fails with the following in the "Run Fastlane" step
![screenshot 28](https://user-images.githubusercontent.com/33224052/186651657-104f815b-0673-430f-a4b5-ee174c99c9fa.png)


The Android build fails with the following in the "Run gradelw" step
![screenshot 29](https://user-images.githubusercontent.com/33224052/186651924-4449c5f0-eb70-44c1-82cb-7566d45346a0.png)

----------

I, unfortunately, don't know much about the underlying details of building the apps, and even less about how EAS does it specifically. 
Both platforms seem to fail with the expo modules. 

You are welcome to close this issue since the original error is fixed in new versions of ignite-cli.

**Comment by AlexanderLindkjaer** [comment]
@frankcalise I've just created a brand new project to test out. Both Android and IOS eas build fails, but due to other reasons than the original issues. The postinstall script does not seem to cause trouble anymore.

The only thing i've done is
```
npx ignite-cli new PizzaApp --expo
cd PizzaApp
eas build
```
In the eas build command, I build for both platforms and did the first-time default options.
----------
`npx ignite-cli doctor` 
![screenshot 26](https://user-images.githubusercontent.com/33224052/186650644-b4a54447-a4a7-47b4-ae2c-042e3fba9ce4.png)
These are only those that are relevant, since EAS servers have their own system/javascript/android/ios versions. I dont know what those are.
----------
The IOS build fails with the following in the "Run Fastlane" step
![screenshot 28](https://user-images.githubusercontent.com/33224052/186651657-104f815b-0673-430f-a4b5-ee174c99c9fa.png)


The Android build fails with the following in the "Run gradelw" step
![screenshot 29](https://user-images.githubusercontent.com/33224052/186651924-4449c5f0-eb70-44c1-82cb-7566d45346a0.png)

----------

I, unfortunately, don't know much about the underlying details of building the apps, and even less about how EAS does it specifically. 
Both platforms seem to fail with the expo modules. 

You are welcome to close this issue since the original error is fixed in new versions of ignite-cli.

**Comment by frankcalise** [comment]
@AlexanderLindkjaer I will close this due to the original issue being solved.

FYI, the latest Ignite has been released and you can try running EAS builds with that. 

I just ran the EAS builds locally for a simulator build without issue, but first deleting the android/ios directories.
