### ISSUE TITLE
Basic ignite apk size is exceeding 45mb without expo

### ISSUE THREAD

**Issue by Prabhat-git-99** [infinitered/ignite#1947]
Am generating apk for ignite app with just one screen to test, not using expo just working with native cli. The apk size after build came out to 48mb. Is there any way to reduce this big size?

Also getting  `Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.`

Steps to reproduce

1. `npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/`

**Comment by frankcalise** [comment]
Hey @Prabhat-git-99, thanks for your interest in ignite!

While we understand the need for smaller bundle sizes, please keep in mind you are choosing to start with a boilerplate that may include more libraries/features than you need. If you're not intending to use each of them, feel free to remove them to trim the size of your application.

You may be also interested in the following:
- The APK although convenient, isn't always a good indicator of final app size. Bundling via Android App Bundle (AAB) will let the Play Store create optimized APKs for specific device configurations, ~15% smaller than the APK. [(read more here)](https://developer.android.com/guide/app-bundle)
- [Enabling ProGuard to further reduce unused code](https://reactnative.dev/docs/signed-apk-android#enabling-proguard-to-reduce-the-size-of-the-apk-optional)

Hope this helps, happy coding!

**Comment by frankcalise** [comment]
Closing this issue, let's continue this via [Discussions](https://github.com/infinitered/ignite/discussions) if you want to further continue exploring app size reduction.
