### ISSUE TITLE
Project installs but does not run

### ISSUE THREAD

**Issue by danilodorgam** [infinitered/ignite#1954]
What's going on?
Error when trying to start a newly created project.
I've tried it on both Linux Mint and Windows 10 following the suggested course
---

Steps to reproduce

1. npx ignite-cli new PizzaApp
2. cd PizzaApp/
3. yarn android

---

`npx ignite-cli doctor` results:
System
  platform           linux                                                                 
  arch               x64                                                                   
  cpu                16 cores     Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz                
  directory          PizzaApp     /home/danilodorgam/Documentos/projetos/PizzaApp 

JavaScript (and globally-installed packages)
  node               16.15.0      /home/danilodorgam/.nvm/versions/node/v16.15.0/bin/node 
  npm                8.5.5        /home/danilodorgam/.nvm/versions/node/v16.15.0/bin/npm  
    corepack         0.10.0                                                               
    npm              8.5.5                                                                
  yarn               1.22.19      /usr/bin/yarn                                           
  pnpm               -            not installed                                           

Ignite
  ignite-cli         7.10.10      /home/danilodorgam/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /home/danilodorgam/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               11.0.15      /usr/bin/java                  
  android home       -            /home/danilodorgam/Android/Sdk

BUILD FAILED in 6s

    at makeError (/home/danilodorgam/Documentos/projetos/PizzaApp/node_modules/execa/index.js:174:9)
    at /home/danilodorgam/Documentos/projetos/PizzaApp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/home/danilodorgam/Documentos/projetos/PizzaApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/danilodorgam/Documentos/projetos/PizzaApp/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by HAFDIAHMED** [comment]
@jamonholmgren 

please help us many projects are generated by ignite these days but they cannot be runned using ignite ???

**Comment by ahdidou-mohamed** [comment]
Same problem,
Running the project doesn't work out of the box.
To make it work I had to set node version globally to v16.14.2
I also had to remove expo-linear-gradient package to make it compile for Android

I think requirements section should be updated

❯ npx ignite-cli doctor
System
  platform           darwin
  arch               x64
  cpu                16 cores     Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  directory          mohamed      /Users/mohamed

JavaScript (and globally-installed packages)
  node                    16.14.2                                   /Users/mohamed/.nvm/versions/node/v16.14.2/bin/node
  npm                     8.5.0                                     /Users/mohamed/.nvm/versions/node/v16.14.2/bin/npm
    corepack              0.10.0
    ionic                 5.0.0
    nodemon               2.0.15
    npm                   8.5.0
    pm2                   5.2.0
    serve                 13.0.2
  yarn                    1.22.17                                   /usr/local/bin/yarn
    appcenter-cli         2.10.9
    create-electron-app   1.0.0
    vite                  2.9.6
  pnpm                    6.32.11                                   /usr/local/bin/pnpm
                          <no pnpm global package info available>

Ignite
  ignite-cli         7.10.10      /Users/mohamed/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/mohamed/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               11.0.9       /usr/bin/java
  android home       -            /Users/mohamed/Library/Android/sdk

iOS
  xcode              13.3.1
  cocoapods          1.11.3       /usr/local/bin/pod

**Comment by ahdidou-mohamed** [comment]
@mazenchami Thanks for pointing us to the solution
FYI by the time I've done the tests, the version was :  7.10.10
Cheers

**Comment by mazenchami** [comment]
@ahdidou-mohamed thanks for pointing that out. I'll go ahead and close this issue since its resolved in the latest build. Please re-open a new issue if you notice anything going on.

Also, my preferred `node` version is `v16.15.1`
