### ISSUE TITLE
Remove withRootStore, switch to getRootStore

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#1974]
@mazenchami and I ran into a problem with strict TypeScript where using withRootStore on substores will result in the error:

```
Type 'RootStore' recursively references itself as a base type. ts(2310)
```

I am not really a fan of hanging the `rootStore` reference as a view off of every store anyway, so I'm proposing we replace the `withRootStore` extension with a very similar `getRootStore` helper function.

```diff
- import { withRootStore } from "./extensions/with-root-store"
+ import { getRootStore } from "./helpers/get-root-store"

const MyStore = types.model("MyStore")
- .extend(withRootStore)
.views((store) => ({
  get someProp() {
-    return store.rootStore.someProp
+    return getRootStore(store).someProp
  }
})
```

The implementation should be very similar (actually, simpler) to the existing extension.

**Comment by FlanaganSe** [comment]
In some situations I still get the error for `Type 'RootStore' recursively references itself as a base type. ts(2310)` when using a getRootStore() helper function. 

It occurs when trying to return a value that was dependent on a value pulled from another store. I think mobx-state-tree only wants actions to update values in the store and to not return them. 

So an example where this occurs is if you have an action that takes in a userId, stored in another store, and uses it to fetch data from an API and then return something with the data. 

`
getDatabasedOnuser: flow(function* (): Type {
  const { userId } = getRootStore(self).UserModel;

  try {
      const SomeFeetchedObject = self.environment.api.fetchSomething(userId);
      self.storeProperty = SomeFeetchedObject;
      return SomeFeetchedObject.id; 
   } catch (e) { ....... }
}   
`

Remove the return and the error goes away. I'm sure it can occur in other situations but this has been the one that I've been running into.

**Comment by frankcalise** [comment]
@FlanaganSe Have you tried explicitly adding a return type to the view?

You can also try reordering `views` above `actions` to see if that will auto type it.
