### ISSUE TITLE
TabNavigator and component demo

### ISSUE THREAD

**Issue by lindboe** [infinitered/ignite#1988]
Add a [TabNavigator](https://reactnavigation.org/docs/tab-based-navigation/). The first screen should be a "Components" demo.

Experiment with:
* Making the "Components" screen contain the cases shown in storybook (and compare with using storybook)
* Making the "Components" screen a long single screen (see if we can/want to showcase any performance optimizations) and using a drawer menu (https://docs.swmansion.com/react-native-gesture-handler/docs/api/components/drawer-layout) to jump between examples (similar to storybook UI)

Out of scope:
* Final UI designs. We'll follow up later with that.
* Final flow into and out of this navigator. Add buttons wherever is convenient for now.

**Comment by kateinkim** [comment]
Done here https://github.com/infinitered/ignite/pull/2018 and merged to maverick
