### ISSUE TITLE
Upgrade to 0.28

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#199]
As of right now, everything looks great, except switching out `0.27.2` to `0.28.0` causes a strange error:
![image](https://cloud.githubusercontent.com/assets/997157/16358086/89dcef5e-3ace-11e6-82c4-af7269ca0aed.png)

The stack trace is blow away.  Here's our starting point.   https://github.com/facebook/react-native/blob/516bf7bd94d14600920a3d78fdcf51ea7fe48495/Libraries/EventEmitter/NativeEventEmitter.js#L32

@skellock @kevinvangelder @fvonhoven  - Would send mayonnaise to first person who solves this.

**Comment by GantMan** [comment]
take a look at this:  http://stackoverflow.com/questions/37999468/entry-file-error-in-react-native-from-packager

seems to be the same error that packager is saying.

**Comment by GantMan** [comment]
I've narrowed this down to push notifications.  Commenting out pushconfig fixes:
![image](https://cloud.githubusercontent.com/assets/997157/16367665/6f188976-3beb-11e6-8354-4ca90c3f9282.png)

**Comment by GantMan** [comment]
simply adding
`import PushNotification from 'react-native-push-notification'` causes this error.   Will file with the npm module source.   For now I'm likely to disable push in ignite.   Keeping this lib working is a bit of a burden.

**Comment by GantMan** [comment]
Solved by removing push #210

**Comment by pampang** [comment]
Can you post your package.json file? This situation seems to happen when we are having a lower version of rn plugins?
