### ISSUE TITLE
.babelrc not generated by ignite new on Win 10, causing tests to fail

### ISSUE THREAD

**Issue by will-hart** [infinitered/ignite#203]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

----

I've found this issue on Win 10 using cmder `ignite -V == 1.0.2`. 

Steps followed:

1. `ignite new TestApp`
2. Run `npm run test` - all tests fail with `unexpected token import`
3. Verify `.babelrc` doesn't exist in generated app
4. Copy / paste `.babelrc` from https://github.com/infinitered/ignite/tree/master/ignite-base 
5. Rerun tests - they run 

As an aside -  after this new tests I added had the same `unexpected token import` error. I had to delete `node_modules/.cache/ava` to get them to run. I assume this is an ava issue.

**Comment by ahmed1490** [comment]
+1 on mac as well

**Comment by GantMan** [comment]
Ah, I think this is due to our complicated release system.   We're going to try to lock down our releases to tags.   But as of right now, the generator is `npm`, but the copied files are `git`.   I'll need to release version 1.0.3 - I'll do that now.

**Comment by GantMan** [comment]
released 1.0.3 - We'll make sure stuff like this doesn't happen in the future.   We're working on the generator making sure it checks out a tag rather than master.   So releases can't have these little sneaky breaking issues.
