### ISSUE TITLE
New app gets created but does not start (windows + android)

### ISSUE THREAD

**Issue by ishdeep-sidhu-kidsloop** [infinitered/ignite#2034]
What's going on?
When I start a new app using the template, it creates the app successfully but when I run `pnpm run android` it gives the error in the screenshot. I even tried deleting the node modules and doing a normal `npm install` but that too gives a similar error. My android env is fine as other react-native apps work fine. 
![err2](https://user-images.githubusercontent.com/102518164/185841611-2befd8e1-ff37-4f43-9b07-7b3dc6c69af7.png)

---

Steps to reproduce

1. npx ignite-cli new PizzaApp
2. cd PizzaApp
3. pnpm run android

---

`npx ignite-cli doctor` results:
![doc](https://user-images.githubusercontent.com/102518164/185841806-ed76ca49-75cf-45b5-a325-f1191efee158.png)

**Comment by joshuayoes** [comment]
There has been a lot of changes since this issue last had activity. We have release a new major version of Ignite, codenamed Maverick. This is going to be closed for now, but please re-open if this still needs attention.
