### ISSUE TITLE
react-native start - Error: Couldn't find preset "es2015-node" relative to directory ..

### ISSUE THREAD

**Issue by ahmed1490** [infinitered/ignite#204]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

```
> ignite new TestApp
> cd TestApp
> react-native start
> ignite -V // 1.0.2.
```

While installing I got a warning that babel should be global. I dont think this error related though.

<img width="1092" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/16360781/eb084c60-3b73-11e6-90e8-c4aaa8aae117.png">

**Comment by GantMan** [comment]
Excellent!  Do you mind helping us track this down?

First, run this:
`npm install babel-preset-es2015 --save`
if you're on windows you'll need to do this
`npm install babel-preset-es2015 --save --no-bin-links`

Let me know if this fixes it for that project.  If so, I can modify master to make sure this is fixed for everyone.   If it complains about `react` you'll have to do the same thing with
`npm install babel-preset-react --save` add `--no-bin-links` on windows.

Depending on how this works for you is how we'll fix the project.  Cheers!

**Comment by ahmed1490** [comment]
@GantMan `npm install babel-preset-es2015 --save`  worked for me! Cheers :D

except one warning: `react-native-push-notification@1.1.1 requires a peer of react-native@>=0.28 but none was installed.`

**Comment by GantMan** [comment]
AHHH, good to know.   We'll have to add that to our package.json, we must have somehow installed it globally.

As for push 1.1.1 requires 0.28, that will go away as soon as we finish #199

**Comment by ahmed1490** [comment]
@GantMan are you going to use the new navigator with the upgrade?

**Comment by GantMan** [comment]
We plan on moving to it as soon as we can do so confidently.  We've been mixing it into various projects, but every release of RN they seem to break or deprecate something.  We'll have it soon, though.  It's way better than classic.
