### ISSUE TITLE
Update remaining "legacy" components to new patterns / design: Checkbox, Switch, Card

### ISSUE THREAD

**Issue by yulolimum** [infinitered/ignite#2044]
Most components have been migrated (and new ones built) to feature the new Ignite design.  There are a few left. Creating this issue to track progress. I'll self-assign. Will need to revamp those:

- [x] Checkbox
- [x] Switch
- [ ] Card

**Comment by robinheinze** [comment]
@yulolimum FYI I'm using Switch in the DemoPodcast screen, so that may need to be updated after the component is updated. I won't worry to much about it looking great since I know you're updating it.

**Comment by jamonholmgren** [comment]
@JosephDunivan Really appreciate the offer! @yulolimum already has some WIP on this so he’ll take it to the finish line. But I really appreciate any help and feedback you have on the changes we are making. Manually testing especially

**Comment by jamonholmgren** [comment]
Awesome @JosephDunivan ! We're pretty excited about these changes as well!

**Comment by yulolimum** [comment]
Hi @JosephDunivan!

Just wanted to add some details here to address your use-case before closing this issue.

>It needs a complete overhaul to be useful
>Although the switch does not have the feature to do this

I agree with you there! The switch (and other components) could have used some love some time ago, but I don't think it was completely unusable. The purpose of the components shipped with Ignite is for them to be good starters, rather than ones with advanced functionality that would rarely get used. Since we use Ignite internally for projects, most components are customized (enhanced) to fit the project they are used in and we just can't have components that are overly engineered that we would have to refactor (simplify) every time. 

The new components (those that will ship with Maverick) are no different. They do _look_ better and do ship with more customization options and more patterns that we see every day in our projects, but they are also simple in their nature in that they can be expanded upon (which is what you did 😄) rather than serve as a catch-all for every use case out there. 

---

Now, regarding the Switch...

The new Switch is called [Toggle](https://github.com/infinitered/ignite/pull/2107) and will contain a few different variations as far as looks go. 

How is the component state handled? Well, it's actually the same as the old Switch which is based on RN's own [Switch](https://reactnative.dev/docs/switch). Reading their docs:

>This is a controlled component that requires an onValueChange callback that updates the value prop in order for the component to reflect user actions. If the value prop is not updated, the component will continue to render the supplied value prop instead of the expected result of any user actions.

Note "**_controlled component_**". In Toggle, the `value` will reflect its on/off state and we provide two [callback method props](https://github.com/infinitered/ignite/blob/maverick/boilerplate/app/components/Toggle.tsx#L138-L142) to determine if you need to update that state. These callback methods will not change the `value`, that's up to you.

---

Here's an example for your use-case. 

```tsx
const List = observer(function List() {
  const { items } = useStores()

  const allChecked = items.every((i) => i.isChecked)

  return (
    <>
      <Toggle
        value={allChecked}
        onValueChange={() => items.forEach((i) => i.setIsChecked(!allChecked))}
      />

      {items.map((i) => (
        <ListItem
          LeftComponent={
            <Toggle value={i.isChecked} onValueChange={() => i.setIsChecked(!i.isChecked)} />
          }
        >
          {i.name}
        </ListItem>
      ))}
    </>
  )
})
```
