### ISSUE TITLE
Boilerplate Android build fails on Appcenter with "Could not read script '/' as it is a directory."

### ISSUE THREAD

**Issue by jvgeee** [infinitered/ignite#2049]
**What's going on?**

When using the default boilerplate, building locally works fine but an Appcenter (and potentially other cloud build tools, not sure), you get this error:

```
Starting a Gradle Daemon (subsequent builds will be faster)
Gradle 7.3.3

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/runner/work/1/s/ThriveBusiness/android/settings.gradle' line: 4

* What went wrong:
A problem occurred evaluating settings 'Thriday'.
> Could not read script '/' as it is a directory.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Error: /Users/runner/work/1/s/ThriveBusiness/android/gradlew failed with return code: 1
    at ChildProcess.<anonymous> (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/1.128.0/node_modules/vsts-task-lib/toolrunner.js:569:30)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
##[error]Error: /Users/runner/work/1/s/ThriveBusiness/android/gradlew failed with return code: 1
```

This is caused by lines like this:

```
apply from: new File(["node", "--print", "require.resolve('expo/package.json')"].execute().text.trim(), "../scripts/autolinking.gradle");
```

The suggested method from Expo is to do use `.execute(null, rootDir).text.trim()` instead,  like this:

```
apply from: new File(["node", "--print", "require.resolve('expo/package.json')"].execute(null, rootDir).text.trim(), "../scripts/autolinking.gradle")
```

A similar change has to be made on /app/build.gradle at this line:

```
apply from: new File(["node", "--print", "require.resolve('react-native/package.json')"].execute().text.trim(), "../react.gradle");
```

It fails, but if you change it to `.execute(null, rootDir).text.trim()` then it works.

**Comment by Piemontez** [comment]
Same for me.

But in my case, the solution "null, rootDir" not working.

**Comment by joshuayoes** [comment]
@jvgeee could you submit a PR with the gradle change that fixed it for you?

**Comment by frankcalise** [comment]
@Piemontez @jvgeee Does this seem related to the issues you're seeing? https://github.com/expo/expo/issues/18412

**Comment by mohamed-ahdidou-nw** [comment]
The solution for me was to create a new ignite project using `yarn` instead of `npm` & `pnpm`
I'm trying to fix that since I'm a big `pnpm` fan

**Comment by bohdan-sharkz** [comment]
As @mohamed-ahdidou-nw suggested, migrating to yarn solved the issue. I've removed node_modules and reinstalled them with yarn and the error was gone. It's a shame that pnpm produces the issue...

**Comment by alakdam07** [comment]
I think if you guys run `npm install` should solve the issue.

**Comment by alakdam07** [comment]
I think if you guys run `npm install` should solve the issue

**Comment by kdenz** [comment]
For me I'm using pnpm, and it's missing `@react-native-community/cli-platform-android`, which after I do `pnpm i -D @react-native-community/cli-platform-android` it works

**Comment by frankcalise** [comment]
@jvgeee could you try @kdenz solution and let us know if it works for you?

**Comment by jvgeee** [comment]
@frankcalise I'm not working on the project that uses appcenter anymore, but as noted in the original post changing all instances of:

`.execute().text.trim(), "../scripts/autolinking.gradle");`

to

`.execute(null, rootDir).text.trim(), "../scripts/autolinking.gradle");`

Then it works fine in AppCenter. You have to find all of them in the Ignite boilerplate and fix, there are a few.

@kdenz 's solution isn't a solution for this issue, maybe something related (but seems more related to pnpm so not general-purpose). 

The OP issue is specifically that AppCentre can't find the rootDir to apply `text.trim()` on because of the way its build system works.

I'll make a PR which fixes this.
