### ISSUE TITLE
[Feature request] Cross platform FCM notifications

### ISSUE THREAD

**Issue by ahmed1490** [infinitered/ignite#205]
- https://github.com/zo0r/react-native-push-notification/issues/77
- https://github.com/evollu/react-native-fcm
- https://console.firebase.google.com/?pli=1
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

**Comment by drastick** [comment]
+1

**Comment by lukabers** [comment]
+1

**Comment by geekvijay** [comment]
+1

**Comment by besarthoxhaj** [comment]
+1

**Comment by skellock** [comment]
In Ignite 2, we support plugins.  It'd be awesome for someone to create a plugin for Firebase!

**Comment by pankajit3** [comment]
+1
