### ISSUE TITLE
New project walkthrough fails when project names differs from project dir

### ISSUE THREAD

**Issue by frankcalise** [infinitered/ignite#2056]
### Describe the bug

During the `new` command walkthrough, I tried to name my project different from the directory it would be located in and saw the following error:

`node ignite/bin/ignite new KristieLengel`

```
Error: ENOENT: no such file or directory, chdir '/Users/fcalise/code' -> 'KristieLengel'
    at wrappedChdir (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at process.chdir (node:internal/worker:98:5)
    at /Users/fcalise/code/ignite/src/commands/new.ts:341:13
    at step (/Users/fcalise/code/ignite/src/commands/new.ts:44:23)
    at Object.next (/Users/fcalise/code/ignite/src/commands/new.ts:25:53)
    at fulfilled (/Users/fcalise/code/ignite/src/commands/new.ts:16:58) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chdir',
  path: '/Users/fcalise/code',
  dest: 'KristieLengel'
```

### Ignite version

Maverick 7a20616be0d5c33e79cec4894d3100d2d7111e49

### Additional info

<img width="712" alt="image" src="https://user-images.githubusercontent.com/374022/186558556-a7bc2e36-3337-400d-aa80-e1c5b6a72be9.png">

**Comment by joshuayoes** [comment]
I'll take a look at this today

**Comment by joshuayoes** [comment]
I've put together a PR to resolve this. If you could take a look at it @frankcalise and make sure that it works on your end, I would appreciate it
