### ISSUE TITLE
Double export defaults in container screens

### ISSUE THREAD

**Issue by ahmed1490** [infinitered/ignite#207]
`export default class UsageExamplesScreen`
`export default connect(mapStateToProps)(UsageExamplesScreen)`

Same for presentation and few other screens

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

**Comment by GantMan** [comment]
good catch!
