### ISSUE TITLE
Empty State component for podcast list

### ISSUE THREAD

**Issue by robinheinze** [infinitered/ignite#2079]
Would be nice to have a little empty state component so it's not a blank list.

**Comment by robinheinze** [comment]
Hey @kateinkim how's the progress on this? Do you need anything design-wise?

**Comment by kateinkim** [comment]
I have a temporary design and Jenna will have something for me after this Friday. The empty state component is all added but I haven’t pushed yet. I have one question for you though. I will ping you tomorrow if that’s ok @robinheinze
