### ISSUE TITLE
Replace DeviceEventEmitter with Keyboard in screen.js.template

### ISSUE THREAD

**Issue by ahmed1490** [infinitered/ignite#208]
Keyboard.addListener('keyboardDidShow', this.keyboardDidShow.bind(this))
instead of 
DeviceEventEmitter.addListener('keyboardDidShow', this.keyboardDidShow.bind(this))

https://github.com/infinitered/ignite/blob/a42cf19c930d71c289a02988518b86c8e65ed7c2/ignite-generator/screen/templates/screen.js.template#L33

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

I am sorry if I am annoying with too many issues!

**Comment by GantMan** [comment]
hah, on the contrary!  You're helping a ton!

great finds!
