### ISSUE TITLE
New command hangs after process complete

### ISSUE THREAD

**Issue by cdanwards** [infinitered/ignite#2084]
### Describe the bug

When spinning up a new app through cli, after all of the processes run the node instance will continue to run, hanging the terminal.

<img width="672" alt="Screen Shot 2022-08-30 at 4 11 35 PM" src="https://user-images.githubusercontent.com/8878532/187534209-6025f46c-1625-41ab-8e63-a2971ee4d5c6.png">

### Ignite version

maverick `713919b6`

### Additional info

<img width="677" alt="Screen Shot 2022-08-30 at 4 15 25 PM" src="https://user-images.githubusercontent.com/8878532/187534476-2f435687-4095-420f-bb90-34345c81dd3e.png">

**Comment by joshuayoes** [comment]
It seems related to the usage of `prompt.ask`, if it ever gets called, it sometimes doesn't resolve.

**Comment by joshuayoes** [comment]
This wasn't the case in earlier commits, so I may try to do a git-bisect to see when it go introduced

**Comment by joshuayoes** [comment]
Apparently this has been around since the initial commit in maverick

**Comment by joshuayoes** [comment]
Dan found this using [`npx why-is-node-running`](https://github.com/mafintosh/why-is-node-running#cli)

<img width="1197" alt="Screen Shot 2022-08-31 at 12 07 54 PM" src="https://user-images.githubusercontent.com/37849890/187796330-21a1786c-257c-4296-8dc0-a9f246dfbca2.png">

It seems that either the `prompt` tool or `crossSpawn` tool is never resolving out of the event loop

**Comment by cdanwards** [comment]
I think we can close this issue with #2092 being merged.
