### ISSUE TITLE
[Maverick] Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#2103]
### Describe the bug

Running the boilerplate with Xcode Version 13.4.1 (13F100) produces these two errors:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/1479215/187816660-b7e063b5-7fbf-4ee0-88ce-998a609d6bc5.png">

```
ExpoModulesCore Group
Command CompileSwiftSources failed with a nonzero exit code

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoModulesCore' from project 'Pods')

( a bunch of output )

remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
Command CompileSwiftSources failed with a nonzero exit code
```

```
FBReactNativeSpec Group
Command PhaseScriptExecution failed with a nonzero exit code
Node found at: /var/folders/8j/349q4sb50qv8zwvxk751kdsw0000gn/T/yarn--1660789716516-0.8769200455720108/node
/Users/jh/Code/ignite-cli/boilerplate/ios/Pods/../../node_modules/react-native/React/FBReactNativeSpec/../../scripts/react_native_pods_utils/script_phases.sh: line 83: /var/folders/8j/349q4sb50qv8zwvxk751kdsw0000gn/T/yarn--1660789716516-0.8769200455720108/node: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

### Ignite version

Maverick

### Additional info

No

**Comment by jamonholmgren** [comment]
Tried:

```
pod deintegrate
pod install
```

Xcode -> Product menu -> Clean Build Folder

Re-run in Xcode

No dice, same issue

**Comment by jamonholmgren** [comment]
Tried:

```
yarn upgrade expo-modules-autolinking react-native --latest
```

Didn't help

**Comment by jamonholmgren** [comment]
Tried this, didn't help:

https://stackoverflow.com/a/69384358/204044

(Adding to POdfile)

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    # some older pods don't support some architectures, anything over iOS 11 resolves that
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
```

**Comment by jamonholmgren** [comment]
I'll try `pod update` and see if that helps.

...

... it didn't

**Comment by jamonholmgren** [comment]
There's some node error here too. Not sure what's going on with that.

Online, people are saying do this, but...

```
ln -s $(which node) /usr/local/bin/node
```

... it doesn't help. Same error.

**Comment by jamonholmgren** [comment]
It's weird that it's picking up some Yarn version of node that doesn't exist.

Someone online said to reinstall yarn, so I did that, but no dice.

**Comment by jamonholmgren** [comment]
Okay, the weird `yarn` node output was because there's a `.xcode.env.local` file in my `ios` folder. Deleting that now.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/1479215/187818724-7e3b0f60-95be-49b6-b41e-6cd7c6e8ad52.png">

**Comment by jamonholmgren** [comment]
And ... now it's working. I guess!

<img width="564" alt="image" src="https://user-images.githubusercontent.com/1479215/187819296-e4499522-78f4-4b66-9d74-c1d854c6b0cf.png">

**Comment by jamonholmgren** [comment]
Yeah, that seems to have been the issue.

I believe that file is used for customizing your local node path. If you delete it, it'll use `.xcode.env` instead, which has these contents:

```
# This `.xcode.env` file is versioned and is used to source the environment
# used when running script phases inside Xcode.
# To customize your local environment, you can create an `.xcode.env.local`
# file that is not versioned.
# NODE_BINARY variable contains the PATH to the node executable.
#
# Customize the NODE_BINARY variable here.
# For example, to use nvm with brew, add the following line
# . "$(brew --prefix nvm)/nvm.sh" --no-use
export NODE_BINARY=$(command -v node)
```

I'll close this, as it seems to have been the issue.

**Comment by jamonholmgren** [comment]
By the way, running `yarn` will output this:

```
Auto-generating `.xcode.env.local` with
$NODE_BINARY=/var/folders/8j/349q4sb50qv8zwvxk751kdsw0000gn/T/yarn--1661999583968-0.618588229915737/node
```

But then it runs fine.

So, I guess this means that sometimes you'll just need to remove that file and re-yarn.

```
rm ./ios/.xcode.env.local
yarn
```

**Comment by jamonholmgren** [comment]
Somewhat related: https://github.com/expo/eas-cli/issues/1264

**Comment by sync** [comment]
Fixed in expo 46 (latest) see https://github.com/expo/expo/pull/18727

**Comment by jamonholmgren** [comment]
Again bitten by this -- definitely check for the `.xcode.env.local` if you run into this. Not sure why Yarn is adding it.

**Comment by sync** [comment]
because expo will read add it every time you run their scripts
