### ISSUE TITLE
Images are missing in apk

### ISSUE THREAD

**Issue by sudharsan1988** [infinitered/ignite#211]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

Images are missing in the generated apk. I placed all my images in App/Images/ and included in images.js. It works fine when debugging with packager but not on the generated apk. Thank you for your help.

**Comment by sudharsan1988** [comment]
I followed this solution to fix this. Thank you.

http://stackoverflow.com/questions/35567502/how-to-bundle-images-resources-of-react-native-in-android

**Comment by GantMan** [comment]
Thanks for the info!  Gonna close this ticket for now.   Will reopen if we need further action.

**Comment by illing2005** [comment]
I had the same issue.
Maybe we should add the `bundle` command to `npm run android:build`?
