### ISSUE TITLE
Beautify `ignite new` command

### ISSUE THREAD

**Issue by joshuayoes** [infinitered/ignite#2114]

**Comment by jamonholmgren** [comment]
Currently:

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/1479215/188217052-9ab6a641-0dea-46a9-b75c-a2b1718d1215.png">

It's not bad, but I'd love to continue to make it shine

**Comment by joshuayoes** [comment]
This article has some nice notes, although we mostly already have most of these principles: https://blog.developer.atlassian.com/10-design-principles-for-delightful-clis/

**Comment by joshuayoes** [comment]
Enquirer, which is what gluegun uses for prompts, has a lot of nice customization options: https://github.com/enquirer/enquirer

**Comment by jamonholmgren** [comment]
I like the output in this command:

https://twitter.com/samselikoff/status/1566842918941360128

**Comment by joshuayoes** [comment]
I also really liked the gatsby-cli, it had a lot of style: https://www.gatsbyjs.com/docs/reference/gatsby-cli/
![0_jAK-XXvfqorbpKcv](https://user-images.githubusercontent.com/37849890/188759858-d1d18a0f-98b4-43a4-9ae9-f0674e821fb8.png)

**Comment by joshuayoes** [comment]
Gant Ideas:
- **Create an emoji loading bar, where a fuse lights towards a stick of dynamite, that explodes when it is done** 
- Add `--party` as a flag to add rainbows
- Add `--america` as a flag to add america
- Add `--nyan` to use nyan cat as a loading bar
- Add `--rocket` to use a rocket ship as a loading bar
- Show loading messages based on holidays or day of the week

**Comment by joshuayoes** [comment]
Closed by https://github.com/infinitered/ignite/pull/2119
