### ISSUE TITLE
Latest ignite builds for Expo 43 and Expo Go only supports 44+

### ISSUE THREAD

**Issue by tbehunin** [infinitered/ignite#2122]
### Describe the bug

Followed the readme steps:

1. npx ignite-cli new PizzaApp --expo
2. cd PizzaApp
3. npm run start

Everything built and started fine. Scanned the QR code on my iPhone 13 and got the following:

![IMG_8DB369D5DFBA-1](https://user-images.githubusercontent.com/796147/188349868-07aab0cf-91fe-4a77-9c24-19f3e588ce2c.jpeg)

The ignite starter project seems to be DOA.

### Ignite version

7.15.0

### Additional info

System
  platform           darwin
  arch               x64
  cpu                16 cores     Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  directory          PizzaApp     /Users/tbehunin/code/personal/rn-sandbox/PizzaApp

JavaScript (and globally-installed packages)
  node               14.16.0                                   /Users/tbehunin/.asdf/installs/nodejs/14.16.0/bin/node
  npm                6.14.11                                   /Users/tbehunin/.asdf/plugins/nodejs/shims/npm
    expo-cli         6.0.5
    serverless       3.21.0
  yarn               -                                         not installed
  pnpm               5.18.9                                    /Users/tbehunin/.asdf/shims/pnpm
                     <no pnpm global package info available>
  expo               43.0.0                                    managed

Ignite
  ignite-cli         7.15.0       /Users/tbehunin/.npm/_npx/87019/bin/ignite
  ignite src         build        /Users/tbehunin/.npm/_npx/87019/lib/node_modules/ignite-cli/build

Android
  java               11.0.11      /Users/tbehunin/.asdf/shims/java
  android home       -            undefined
/Users/tbehunin/.npm/_npx/87019/lib/node_modules/ignite-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Command failed: xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'xcodebuild -version',
  stdout: '',
  stderr: "xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance\n"
}

**Comment by tbehunin** [comment]
Changing `"expo": "43.0.0",` to `"expo": "44.0.0",` in `package.json` fixes it, although someone should probably raise a PR for the real fix.

**Comment by jamonholmgren** [comment]
We're currently working on a big upgrade to Ignite (in the`maverick` branch) that has RN and Expo at latest versions. Hopefully should have a beta this Friday!

**Comment by jamonholmgren** [comment]
Beta out, so I'm going to close this. Thanks!
