### ISSUE TITLE
[Maverick] Better setup script

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#2135]
### Describe the bug

The setup script (in `./bin/setup`) is out of date. Let's take another look at it, and probably tell people it's there after spinning up a new app if they're on Mac? That way they can look at it and then run it.

### Ignite version

Maverick

### Additional info

NO

**Comment by joshuayoes** [comment]
Related to https://github.com/infinitered/ignite/issues/2208

**Comment by joshuayoes** [comment]
It appears we could remove `jetifier` from postInstall.js, as `react-native run-android` calls it automatically as of React Native 0.60

<img width="751" alt="Screen Shot 2022-09-23 at 11 55 14 AM" src="https://user-images.githubusercontent.com/37849890/192037754-4ba58f65-c601-4a93-b463-e6ab61caef86.png">

> Note that jetifier is included and ran automatically with [react-native-community/cli](https://github.com/react-native-community/cli) for React Native versions 0.60 and above, so you do not need to install and run jetifier manually.
https://github.com/mikehardy/jetifier#do-you-need-this

---

I've run through both
```
npx ignite-cli@next PizzaApp
cd PizzaApp
yarn android
```

and

```
npx ignite-cli@next PizzaApp
cd PizzaApp
yarn expo:android
```

And Ignite appears to be working fine on Android
