### ISSUE TITLE
Requiring unknown module "reactotron"/Windows10

### ISSUE THREAD

**Issue by PanRada** [infinitered/ignite#214]
Hi Coders

Just wondering if u can help me manage my error with u cool tool
On correct run ignite intallation (try manage this during week - but now all no error) my virtual phone on Genymotion is stopped my App. This now happend with all new apps.
Error : `Requiring unknown miduke "reactotron"` on red screen
My system : Windows 10
Lates version Ignite
Lates version node
Lates verion Genymotion

No try run on phisical machine 
UPDATE: on phiscical phone this same error

any sugestion

RESOLVE : 
Need manualy install `npm install reactotron --save-dev`
Windows 10 is not good machine :(

**Comment by GantMan** [comment]
nice!   We'll definitely need to check into Windows 10 a bit more.

We appreciate the info!

**Comment by GantMan** [comment]
closing in favor of #196
