### ISSUE TITLE
[Maverick] Favorites toggle is out of sync

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#2143]
### Describe the bug

Both of these are favorites, but only one has the right color for the heart.

![CleanShot 2022-09-09 at 18 34 07@2x](https://user-images.githubusercontent.com/1479215/189463844-d3f1ab59-a96a-43d0-9321-3c1635654d8f.png)

### Ignite version

Maverick beta 2

### Additional info

NO

**Comment by jamonholmgren** [comment]
I think it has something to do with the animation, but I could be wrong.

**Comment by jamonholmgren** [comment]
Also only seems to happen when you favorite an episode other than the first two, like it's reusing the animated values from those two cards.

**Comment by joshuayoes** [comment]
Resolved by https://github.com/infinitered/ignite/pull/2156
