### ISSUE TITLE
Catch non-camelCase project name, reformat to camelCase as default project name

### ISSUE THREAD

**Issue by edjw** [infinitered/ignite#2145]
I started with a kebab case project name. I got the error that it needed to be camel case and it showed what my title would be in camel case. I think it'd be nicer if the cli would not quit completely at that point. And instead it would go again to the project title question with the camel case version of the user's first attempt at a project name as the default answer

Here's a screenshot of what I did without concentrating very hard

<img width="571" alt="grafik" src="https://user-images.githubusercontent.com/6547979/189474998-cec798ae-452c-406c-a3bf-b553810a5c22.png">

**Comment by joshuayoes** [comment]
I've created a PR to update the prompt to show the error message, but give the opportunity to fix it before exiting the process

https://user-images.githubusercontent.com/37849890/190263094-aa8a6a8e-3bfa-41e1-9662-0f902bcd3940.mov

**Comment by joshuayoes** [comment]
Resolved now by https://github.com/infinitered/ignite/pull/2161
