### ISSUE TITLE
[Maverick] DrawerIconButton doesn't work when drawer is open

### ISSUE THREAD

**Issue by rblakesley** [infinitered/ignite#2148]
### Describe the bug

The DrawerIconButton works nicely to open the drawer, but nothing happens when you tap it again to close the drawer.

(On iOS you can swipe left to close the drawer, but on Android it can't be closed without tapping on one of the menu options.)

### Ignite version

Mavericks beta 2

### Additional info

```
npx ignite-cli doctor
System
  platform           darwin                                            
  arch               arm64                                             
  cpu                10 cores          Apple M1 Max                    
  directory          DickensMaverick   /Users/rb/Xcode/DickensMaverick 

JavaScript (and globally-installed packages)
  node               18.4.0       /Users/rb/.nvm/versions/node/v18.4.0/bin/node 
  npm                8.12.1       /opt/homebrew/bin/npm                         
    expo-cli         5.4.12                                                     
    npm              8.12.1                                                     
  yarn               1.22.19      /opt/homebrew/bin/yarn                        
    ignite-cli       7.13.1                                                     
    react-devtools   4.24.7                                                     
  pnpm               -            not installed                                 
  expo               46.0.10      managed                                       

Ignite
  ignite-cli         7.13.1       /opt/homebrew/bin/ignite                                    
  ignite src         build        /Users/rb/.config/yarn/global/node_modules/ignite-cli/build 

Android
  java               11.0.16      /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java 
  android home       -            /Users/rb/Library/Android/sdk                                        

iOS
  xcode              13.4.1     
  cocoapods          1.11.3       /opt/homebrew/bin/pod 
```

**Comment by joshuayoes** [comment]
Would you mind adding a screen recording of the issue?

**Comment by joshuayoes** [comment]
I might be misunderstanding the issue, but I don't see DrawerIconButton when the drawer is already open. We have a back button, and you can press the gray area as well

https://user-images.githubusercontent.com/37849890/190470119-cb651520-dd91-4cf3-9423-0215f003bd70.mov

**Comment by joshuayoes** [comment]
I'm also able to do it on Android

https://user-images.githubusercontent.com/37849890/190472434-88a8e440-7079-45f9-b3f0-1d0e640b8e14.mov

**Comment by rblakesley** [comment]
Ah, I hadn't tried it on a simulator – only on real devices.  I just checked and it works OK for me on the simulators too.

> I might be misunderstanding the issue, but I don't see DrawerIconButton when the drawer is already open. We have a back button, and you can press the gray area as well

The DrawerIconButton component animates its shape from the three-line "hamburger button" to the back arrow when the drawer is open, but I think it's still the same component.  The grey area works for dismissing the drawer on iOS devices, but not on the Android devices that I tried.

On these Android devices, the DrawerIconButton (back arrow) isn't working for me, but I just noticed that I can sometimes get it to work if I tap slightly to the right of the arrow – see the screen recording below:
- Pixel 6 running Android 12
- Huawei Mate 20 Pro running Android 10

I also just found that the DrawerIconButton:
- works fine on an iPhone 12 running iOS 15.5 
- doesn't work on an iPhone 6s running iOS 14.6 (which was the device I first tested with)

...and I noticed that for all devices and simulators, you can open the drawer by tapping anywhere to the right of the hamburger button, though it looks like that's easily avoided by fixing the width of the DrawerButtonIcon component (to prevent it filling the whole screen width)

https://user-images.githubusercontent.com/17591275/190517941-f5427ff9-8ca3-467f-80ce-39307700ce30.mp4

**Comment by rblakesley** [comment]
I think the issue is that the `<Pressable>` component in DrawerIconButton.tsx isn't being translated left along with the visible bars that make up the icon – adding a backgroundColor to the `<Pressable>` makes the problem easy to see.  Removing the outer `<Animated.View>` container and instead translating the `<Pressable>` fixes the problems for me:

```
  return (
    <Pressable {...PressableProps} style={[{transform:[{translateX: open ? (isRTL?60:-60) : 0}]}, $container]}>
      <Animated.View style={[$topBar, animatedTopBarStyles]} />

      <Animated.View style={[$middleBar, animatedMiddleBarStyles]} />

      <Animated.View style={[$bottomBar, animatedBottomBarStyles]} />
    </Pressable>
  )

```

**Comment by rblakesley** [comment]
We could do that with an `<Animated.View>` container wrapping _outside_ the `<Pressible>` (instead of being inside it, like it was before) – like this (with the backgroundColor added just to make it clearer):

```
  return (
    <Animated.View style={[$container, animatedContainerStyles, {backgroundColor:"#DD0"}]}>
      <Pressable {...PressableProps} style={$container}>
        <Animated.View style={[$topBar, animatedTopBarStyles]} />

        <Animated.View style={[$middleBar, animatedMiddleBarStyles]} />

        <Animated.View style={[$bottomBar, animatedBottomBarStyles]} />
      </Pressable>
    </Animated.View>
  )

```

**Comment by joshuayoes** [comment]
I've open a PR where I made the `Pressible` component animatable! https://github.com/infinitered/ignite/pull/2167

**Comment by joshuayoes** [comment]
I will have someone else review this, and get merged into Maverick tomorrow

**Comment by rblakesley** [comment]
Thanks!  Yes, I just tried your PR code and it works very nicely (and is much neater than my suggestion above!)

**Comment by joshuayoes** [comment]
Thank you for your help on this! I'm glad it's working on your end

**Comment by joshuayoes** [comment]
@rblakesley something I figured out while working on this: apparently you can enable a "touchables" toggle in the element inspector to highlight all touchables

https://user-images.githubusercontent.com/37849890/190529142-a43a9c00-a40b-4eb1-b261-55725ee035ad.mp4

**Comment by rblakesley** [comment]
Ah, I didn't know about that – looks very useful – thank you!

**Comment by joshuayoes** [comment]
Resolved by https://github.com/infinitered/ignite/pull/2167
