### ISSUE TITLE
Problem with the Drawer on latest update

### ISSUE THREAD

**Issue by sudharsan1988** [infinitered/ignite#215]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

I have added "Hamburger" icon to a screen which is already available on the Drawer. Here is the Problem, when I press the menu item, it takes me to the corresponding screen. If I press the same menu item again, it loads a empty screen along with the below warning,

Warning: flattenchildren(...): Encountered two children with the same key, 'scene_1'. Child keys must be unique; when two children share a key, only the first child will be used.

Steps to reproduce:

1. Add a "Hamburger" icon on "Device Info Screen" as right-button
2. Open the drawer and press the "Device Info Screen"
3. Once you are on the "Device Info Screen", again press the "Device Info Screen"

**Comment by GantMan** [comment]
@fvonhoven  - ping me when you can about this issue.   We'll probably need to figure out an elegant solution.

**Comment by sudharsan1988** [comment]
Hi, any luck with this? Just looking for a solution to sort this out :) By the way, I am trying to add a background image to the drawer. Is it possible with the current version of Ignite?

**Comment by skellock** [comment]
The screen navigation problem will go away once we merge in `react-native-router-flux`.  They have a solution for this.

For the background image, you can add an `<Image>` to your `DrawerContents.js` file.

**Comment by GantMan** [comment]
@sudharsan1988 - we're going to be upgrading to RNRF this week likely.   This will cause a bit of change, but also a bit of advancement in the capabilities of navigation.

**Comment by GantMan** [comment]
@sudharsan1988 - please check on this with 1.3.1 👍
