### ISSUE TITLE
Error when opening Maverick in simulators / Expo Go

### ISSUE THREAD

**Issue by cdanwards** [infinitered/ignite#2152]
### Describe the bug

When transitioning from the `Login` screen to the `Welcome` screen, the app throws an error:

`Error: A navigator can only contain 'Screen', 'Group' or 'React.Fragment' as its direct children (found ' '). To render this component in the navigator, pass it in the 'component' prop to 'Screen'.`

<img width="1467" alt="Screen Shot 2022-09-13 at 12 25 58 PM" src="https://user-images.githubusercontent.com/8878532/189955791-be810c10-fb20-4cd8-8ad2-591466395db7.png">

<img width="400" alt="Screen Shot 2022-09-13 at 12 25 58 PM" src="https://user-images.githubusercontent.com/8878532/189955807-5078706f-26b9-46d8-92df-e380795225b5.png">

<img width="400" alt="Screen Shot 2022-09-13 at 12 25 58 PM" src="https://user-images.githubusercontent.com/8878532/189955855-2061fd97-8b0d-4c82-8fef-5ff6fb604c3f.png">

### Ignite version

maverick - 502640de

### Additional info

```
System
  platform           darwin
  arch               arm64
  cpu                10 cores     Apple M1 Max
  directory          ignite       /Users/danedwards/Code/ignite

JavaScript (and globally-installed packages)
  node                    18.7.0       /opt/homebrew/bin/node
  npm                     8.15.0       /opt/homebrew/bin/npm
    expo-cli              6.0.5
    npm                   8.15.0
    why-is-node-running   2.2.2
  yarn                    1.22.19      /opt/homebrew/bin/yarn
    ios-deploy            1.11.4
  pnpm                    -            not installed
  expo                    -            not installed

Ignite
  ignite-cli         7.15.0       /opt/homebrew/bin/ignite
  ignite src         src          /Users/danedwards/Code/ignite/src

Android
  java               -            not installed
  android home       -            /Users/danedwards/Library/Android/sdk

iOS
  xcode              14.0
  cocoapods          1.11.3       /opt/homebrew/bin/pod
```

**Comment by joshuayoes** [comment]
Resolved by https://github.com/infinitered/ignite/pull/2156
