### ISSUE TITLE
[Maverick] Red Screen of Death: Reactotron unable to resolve react

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite#2168]
### Describe the bug

Run `npx ignite-cli@next new PizzaApp`

Boot the app as per the instructions

Get the following screen:
![ignite-reactotron-error](https://user-images.githubusercontent.com/7445602/190538183-c52f7c39-9cf8-4c3e-889a-81b3165337ea.png)

npm cache clean and all the usuals done - do you get the same?

### Ignite version

8.0.0-beta-5

### Additional info

Same as https://github.com/infinitered/ignite/issues/2163#issue-1373822536

**Comment by juddey** [comment]
I'm going to try to rip out reactotron to move forward, logging this fyi.

**Comment by juddey** [comment]
removed reactron and app boots successfully.

**Comment by jamonholmgren** [comment]
@juddey I'm not able to reproduce, but I'm on macOS. Are you on Linux? 
![CleanShot 2022-09-16 at 10 58 44@2x](https://user-images.githubusercontent.com/1479215/190702946-a5b137e0-4f59-4b33-83f4-d1abd8df1cc1.png)

**Comment by juddey** [comment]
@jamonholmgren Thanks for checking it out. On MacOS.(under duress haha!) What node version are you running? And how are you running it? (nvm, n, direct install) 

I'm running node 18, for reference.

**Comment by jamonholmgren** [comment]
@juddey Doctor here ... running node via `brew` direct install:

```
npx ignite-cli@next doctor
System
  platform           darwin
  arch               arm64
  cpu                10 cores     Apple M1 Max
  directory          PizzaApp     /Users/jh/Code/Temp/PizzaApp

JavaScript (and globally-installed packages)
  node                            14.20.0      /opt/homebrew/opt/node@14/bin/node
  npm                             6.14.17      /opt/homebrew/opt/node@14/bin/npm
    eas-cli                       0.52.0
    expo-cli                      6.0.5
    firebase-tools                11.1.0
    ios-deploy                    1.11.4
    npm                           8.17.0
  yarn                            1.22.19      /opt/homebrew/bin/yarn
    create-react-native-library   0.20.1
  pnpm                            -            not installed
  expo                            46.0.10      managed

Ignite
  ignite-cli         8.0.0-beta.5   /Users/jh/.npm/_npx/14032/bin/ignite
  ignite src         build          /Users/jh/.npm/_npx/14032/lib/node_modules/ignite-cli/build

Android
  java               11.0.14      /Users/jh/.sdkman/candidates/java/current/bin/java
  android home       -            /Users/jh/Library/Android/sdk

iOS
  xcode              14.0
  cocoapods          1.11.3       /opt/homebrew/bin/pod
  ```

**Comment by juddey** [comment]
Dropped from  node@18 to node@14 @jamonholmgren, and thats resolved the issue.
