### ISSUE TITLE
[Maverick] No simulator found with name "iPhone 13"

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#2170]
### Describe the bug

When trying to run a new Maverick project with Xcode 14, I get this:

<img width="879" alt="CleanShot 2022-09-16 at 10 47 00@2x" src="https://user-images.githubusercontent.com/1479215/190701200-9f4e831e-713f-408a-a24c-6d2adde8a6db.png">

```
npx ignite-cli new PizzaApp
cd PizzaApp
yarn ios
```

### Ignite version

Maverick

### Additional info

no

**Comment by jamonholmgren** [comment]
Workaround is to run:

```
yarn ios --simulator="iPhone 14"
```

**Comment by joshuayoes** [comment]
Is it possible this has to do with Xcode using an old workspace from a previous PizzaApp?

**Comment by frankcalise** [comment]
This is baked into RN it seems?

https://reactnative.dev/docs/running-on-simulator-ios#specifying-a-device

https://stackoverflow.com/questions/68933467/npx-react-native-run-ios-is-picking-non-existing-simulator

**Comment by frankcalise** [comment]
1. Open Xcode workspace for existing project and select the device at the top
<img width="379" alt="image" src="https://user-images.githubusercontent.com/374022/190865095-22810475-179b-4f47-9bde-28b946ff44fd.png">

2. Select `Add Additional Simulators...` from the menu
<img width="353" alt="image" src="https://user-images.githubusercontent.com/374022/190865133-6074e336-8f51-48e3-b6c1-998c63d3ad19.png">

3. Create an `iPhone 13` simulator
<img width="557" alt="image" src="https://user-images.githubusercontent.com/374022/190865167-155a69f4-d51d-435b-b0fe-b845d42f5a9b.png">

4. Run `yarn ios` or `yarn expo:start` and you're good to go

**Comment by joshuayoes** [comment]
@jamonholmgren do we want to leave this issue open? This seems like an upstream issue to me

**Comment by joshuayoes** [comment]
I did just run into this trying to do Detox tests. Perhaps there is a way we could detect in Ignite whether the default simulator is available and print a warning?

**Comment by frankcalise** [comment]
@joshuayoes perhaps we can pipe the output from `applesimutils --list` and see if it matches the detox config?

**Comment by Gurminder-Kaler** [comment]
add this 
    `"iphone13": "npx react-native run-ios --simulator=\"iPhone 13 Pro\"",` in your script and then run "npm run iphone13"

**Comment by joshuayoes** [comment]
@frankcalise I like that solution, it appears we may be able to install simulators for Xcode.

So perhaps the following logic may be good to add somewhere in the `new` command:
1. Check if `iPhone 13` is in `applesimutils --list` or `xcrun simctl list devices` output
2. Warn user that default iOS simulator is not installed
3. Give sample output of workaround (`yarn ios --simulator="iPhone 14"`)
4. Offer to run command to install default iPhone 13 simulator to Xcode (`xcrun simctl create "iPhone 13" "iPhone 13" iOS 15.5`

**Comment by joshuayoes** [comment]
> add this
"iphone13": "npx react-native run-ios --simulator=\"iPhone 13 Pro\"", in your script in package.json file and then run "npm run iphone13"

@Gurminder-Kaler I'm not sure that will solve what we want. I'm trying to use your command with iPhone 7, which is not a simulator on my machine, and my xcode just resolves to the first one that isn't that version

**Comment by jamonholmgren** [comment]
Closing as "not our bug"
