### ISSUE TITLE
Button component weird behavior with LeftAccessory and RightAccessory

### ISSUE THREAD

**Issue by cdanwards** [infinitered/ignite#2172]
### Describe the bug

This was a specific use case but in the new design for the DemoPodcastListScreen, I was originally passing the animated icon views to the `LeftAccessory`. When I did this and clicked on a button, _all_ of the buttons icons would flicker.

I ended up moving the animated view to be a child and no longer had the issue.

https://user-images.githubusercontent.com/8878532/190799491-84d5d10a-5632-47af-bf0c-7b7d7d745eea.mov

### Ignite version

maverick

### Additional info

N/A

**Comment by yulolimum** [comment]
@cdanwards It's happening because the Left/Right Accessories are a React Component and probably should be memoized where they're defined (similar to the TextField accessories on the LoginScreen). The children are React Element.

**Comment by frankcalise** [comment]
Utilizing @yulolimum's memo method he mentioned, things work properly. See this commit for details: https://github.com/infinitered/ignite/pull/2138/commits/0055d813c3f42cc2f902d250e06daa4c7ffb0073

**Comment by yulolimum** [comment]
I'm going to see if memoizing the left/right accessories inside the actual component makes more sense (so you don't have to do that every time).
