### ISSUE TITLE
Convert boilerplate into yarn workspace

### ISSUE THREAD

**Issue by joshuayoes** [infinitered/ignite#2173]
# Problem
Currently, in order to work on the boilerplate, you either need to:

```
cd boilerplate
yarn install
yarn start
```

Or you need to:
```
npm link
npx ignite-cli new PizzaApp \
        --bundle=com.pizzaapp \
        --git \
        --install-deps \
        --packager=yarn \
        --target-path=~/Code/PizzaApp \
        --overwrite
cd ~/Code/PizzaApp
yarn start
```

This is a pretty clunky workflow.

# Potential Solution
Convert ignite into a monorepo, where we have two workspaces: `cli` and `boilerplate`

That way, we can treat `boilerplate` as a real app, and get tooling with typescript intelisense, prettier, etc. out of the box.

**Comment by jamonholmgren** [comment]
![monorepo](https://c.tenor.com/uBhzzXtirz4AAAAd/angry-chewing.gif)

Me when @joshuayoes suggests going back to a monorepo on Ignite

**Comment by jamonholmgren** [comment]
I'm not really understanding why a yarn workspace would make it better. The first option seems pretty straightforward, no?

**Comment by joshuayoes** [comment]
> Me when @joshuayoes suggests going back to a monorepo on Ignite

Why did we move away from monorepos?

---

Here is the main pros I see is for CI/CD stuff:
- we could run `prettier`, `lint`, `typecheck`, `format`, etc in the CI if it were a yarn workspace, and better parallelize those tests. This would mean less manual testing and review from external contributors. 
- Making `boilerplate` a workspace means that things like [this `.gitignore` issue](https://github.com/infinitered/ignite/issues/2174) would happen less since it is more of a "real" workspace 
- a lot of the E2E tests are bottlenecked by creating node_modules, we could potentially run way more of them in parallel by having them get installed into a real workspace and make our `npx ignite-cli new` tests leaner

**Comment by jamonholmgren** [comment]
![monorepo](https://c.tenor.com/uBhzzXtirz4AAAAd/angry-chewing.gif)

**Comment by jamonholmgren** [comment]
(Lest people think I'm a jerk, I did this on Zoom with Josh there...lol)
