### ISSUE TITLE
[Maverick] ignite-cli is not initializing git repository

### ISSUE THREAD

**Issue by vijjusri14** [infinitered/ignite#2188]
### Describe the bug

CLI is not initializing git repository even after answering the below prompt as Yes

> Do you want to initialize a git repository? (Y/n) » Yes 

Tried with inline command, yet git was not initialized.

`npx ignite-cli@next new PizzaApp --bundle=com.pizzaapp --git --install-deps --packager=yarn`

### Ignite version

8.0.0-beta.6

### Additional info

```
System
  platform           win32
  arch               x64
  cpu                8 cores      11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  directory          PizzaApp    C:\Users\Vijay\Desktop\PizzaApp

JavaScript (and globally-installed packages)
  node               16.17.0      C:\Program Files\nodejs\node.EXE
  npm                8.15.0       C:\Program Files\nodejs\npm.CMD
    corepack         0.12.1
    jshint           2.13.5
    npm              8.15.0
    yarn             1.22.19
  yarn               1.22.19      C:\Program Files\nodejs\yarn.CMD
    http-server      14.1.1
    localtunnel      2.0.2
  pnpm               -            not installed
  expo               46.0.10      managed

Ignite
  ignite-cli         8.0.0-beta.6   C:\Users\Vijay\AppData\Local\npm-cache\_npx\2351a7c35afcf833\node_modules\.bin\ignite.CMD
  ignite src         build          C:\Users\Vijay\AppData\Local\npm-cache\_npx\2351a7c35afcf833\node_modules\ignite-cli\build

Android
  java               17.0.4.1     C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin\java.EXE
  android home       -            C:\Users\Vijay\AppData\Local\Android\Sdk
```

**Comment by joshuayoes** [comment]
@vijjusri14  8.0.0-beta.7 is out now with a PR that should resolve this. Can you try again with `npx ignite-cli@next new`?

**Comment by vijjusri14** [comment]
@joshuayoes This is working, git is initialized properly now. 

As Maverick now initializes git and depends on locally installed git, can we have the installed git version displayed when we run `npx ignite-cli@next doctor` just for sanity. 

Should I create a new issue for this?

**Comment by frankcalise** [comment]
Hey @vijjusri14 that's a great idea. Yes, please create a new issue.

**Comment by vijjusri14** [comment]
@frankcalise created #2198 to track it
