### ISSUE TITLE
[Maverick] Automated builds for CI/CD fails in App Center due to deprecated Jetifier warnings

### ISSUE THREAD

**Issue by vijjusri14** [infinitered/ignite#2208]
### Describe the bug

Automated CI builds are failing in App Center due to jetifier logging the warnings to console. 

![image](https://user-images.githubusercontent.com/6272770/192000530-23f740c0-014d-4f5b-aaae-6cfef26d1028.png)

[Here](https://github.com/microsoft/appcenter/issues/887) is the issue in appcenter repo

The [workaround](https://github.com/microsoft/appcenter/issues/887#issuecomment-1103251628) suggested was to use v1.6.8 version of jetifier which is purpose built for this issue and is same as v2.0.0 without the warnings [v1.6.8...v2.0.0](https://github.com/mikehardy/jetifier/compare/v1.6.8...v2.0.0)

Should ignite-cli drop jetifier (or use v1.6.8 to suppress the warnings) step in postinstall scripts as React Native has [added](https://reactnative.dev/blog/2019/07/03/version-60#androidx-support) supports for AndroidX in 2019 and most of the native android libraries have [migrated](https://developer.android.com/jetpack/androidx/migrate) to Androidx.

Skipping jetifier should also reduce the build time.

### Ignite version

8.0.0-beta.7

### Additional info

```
System
  platform           win32
  arch               x64
  cpu                8 cores      11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  directory          PizzaApp     C:\Users\Vijay\Desktop\PizzaApp

JavaScript (and globally-installed packages)
  node               16.17.0      C:\Program Files\nodejs\node.EXE
  npm                8.15.0       C:\Program Files\nodejs\npm.CMD
    corepack         0.12.1
    jshint           2.13.5
    npm              8.15.0
    yarn             1.22.19
  yarn               1.22.19      C:\Program Files\nodejs\yarn.CMD
    http-server      14.1.1
    localtunnel      2.0.2
  pnpm               -            not installed
  expo               46.0.10      managed

Ignite
  ignite-cli         8.0.0-beta.7   C:\Users\Vijay\AppData\Local\npm-cache\_npx\2351a7c35afcf833\node_modules\.bin\ignite.CMD
  ignite src         build          C:\Users\Vijay\AppData\Local\npm-cache\_npx\2351a7c35afcf833\node_modules\ignite-cli\build

Android
  java               17.0.4.1     C:\Program Files\Eclipse Adoptium\jdk-17.0.4.101-hotspot\bin\java.EXE
  android home       -            C:\Users\sbhimalingam\AppData\Local\Android\Sdk

**Comment by vijjusri14** [comment]
This will also fail for projects created with ignite-cli v7.11.0 as per the [git blame](https://github.com/infinitered/ignite/commit/9297f1c5fed5a5428ed9b699db2033ee5a384519#diff-594f75b3ec0c76210a39b8c7ce238eea438454a93d830bd968a282f89e30a8b0R92)

**Comment by jamonholmgren** [comment]
I like the idea of skipping jetifier. @vijjusri14 would you want to PR that? cc @frankcalise @joshuayoes

**Comment by vijjusri14** [comment]
Sure I'll take it up

**Comment by joshuayoes** [comment]
Ignite `8.0.0-beta.8` has been release with this PR https://github.com/infinitered/ignite/pull/2209

I'm going to close this issue for now, but if you are still having issues with it, feel free to re-open it
