### ISSUE TITLE
Fix various issues launching new template

### ISSUE THREAD

**Issue by ahmedbodi** [infinitered/ignite#2233]
### Describe the bug

Platform: web
Ignite-cli: next

Bugs experienced:
process is not defined.

Fix:
```
+  "overrides": {
+    "react-error-overlay": "6.0.9"
+  },

```

No such asset assets/images/rnr-image-1.png

Fix:
atm i just copied rmr-image@2.png to the path

### Ignite version

8.0.0-beta.8

### Additional info

```
npx ignite-cli@next doctor
System
  platform           linux                                                 
  arch               x64                                                   
  cpu                12 cores     Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 
  directory          roktools     /home/ahmedbodi/work/multicoin/roktools  

JavaScript (and globally-installed packages)
  node               16.17.1      /home/ahmedbodi/.nvm/versions/node/v16.17.1/bin/node 
  npm                8.15.0       /home/ahmedbodi/.nvm/versions/node/v16.17.1/bin/npm  
    corepack         0.12.1                                                            
    npm              8.15.0                                                            
  yarn               -            not installed                                        
  pnpm               -            not installed                                        
  expo               46.0.13      managed                                              

Ignite
  ignite-cli         8.0.0-beta.8   /home/ahmedbodi/.npm/_npx/2351a7c35afcf833/node_modules/.bin/ignite      
  ignite src         build          /home/ahmedbodi/.npm/_npx/2351a7c35afcf833/node_modules/ignite-cli/build 

Android
  java               11.0.16      /usr/bin/java 
  android home       -            undefined     

Tools
/home/ahmedbodi/.npm/_npx/2351a7c35afcf833/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: Command failed: git -v
unknown option: -v
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]```

**Comment by jamonholmgren** [comment]
@ahmedbodi Could you submit a PR for this?

**Comment by ahmedbodi** [comment]
Will do when I've got a spare moment

**Comment by carlinisaacson** [comment]
I believe the missing image is because it's named wrong. There are images named rnr-image-2 and rnr-image-3, and rnr-image. I believe just renaming rnr-image to rnr-image-1 will fix this.

**Comment by kateinkim** [comment]
https://github.com/infinitered/ignite/pull/2237

**Comment by joshuayoes** [comment]
> I believe the missing image is because it's named wrong. There are images named rnr-image-2, rnr-image-3, and rnr-image. I believe just renaming rnr-image to rnr-image-1 will fix this.

@ahmedbodi could you verify that renaming the image would fix instead of overriding a dependency? We are a little hesitant to override a lower dependency like this without a lot more testing on our part.

**Comment by frankcalise** [comment]
Hi @ahmedbodi can you please describe the steps you needed to take to run Expo web more clearly? I'm having trouble getting to the spot where you're stuck.

Please form them like so for example:
1. npx ignite-cli new PizzaApp --yes
2. cd PizzaApp
3. (anything else here? dependencies, config changes)
4. yarn expo:web

**Comment by ahmedbodi** [comment]
just the above exactly as that. no changes. then when going to the homepage if u look in the browser console there is an error about process is not defined

**Comment by frankcalise** [comment]
Related to the issues documented here within Expo - https://github.com/expo/expo/issues/17547

When throwing an error as is, the screen goes blank or just remains at our rendered screen (LoginScreen for example). After making this override change (or perhaps we'll opt for resolutions like mentioned in the above issue), web errors would then react like this:

![image](https://user-images.githubusercontent.com/374022/193825644-67fb99a1-d45d-4c1a-b026-9741342519ae.png)

**Comment by joshuayoes** [comment]
Thank you for adding all this context @frankcalise!

These issues are pretty old. A fix has not been implemented, which is disappointing because Webpack 5 has been around for a while. But that also suggests to me that a upstream fix is likely not going to be happening in the next year or so, so it would be worth adding this.
