### ISSUE TITLE
[Maverick] Demo screens glitch on first render

### ISSUE THREAD

**Issue by rblakesley** [infinitered/ignite#2234]
### Describe the bug

When switching between demo screens using the bottom tab navigator, the first render of each screen glitches briefly – the content is rendered too high then jumps down to the correct position after a frame or two.  Subsequent renders of the screens are fine.

It's not noticeable on the simulator but is on both Android and iOS devices – below is a screen recording from a Pixel 6.
- On Android devices, the issue goes away if I remove the `<StatusBar>` item from the `Screen` component (but then the status bar doesn't pick up the app theme).
- On iOS devices, the `<StatusBar>` item isn't causing the problem – it looks like it's the `<SafeAreaView>` instead.
- I thought that adding `lazy: false` to the `<Tab.Navigator screenOptions` might be a reasonable workaround, but it doesn't seem to make a difference.

https://user-images.githubusercontent.com/17591275/193025794-c5c9090d-16fd-43f2-b4e9-188f0690e1c3.mp4

[Edit]: Here's a slowed-down video to show the glitches more clearly

https://user-images.githubusercontent.com/17591275/193048629-18140301-93d8-472a-9769-b4528a93fb97.mp4

### Ignite version

8.1.0

### Additional info

```
npx ignite-cli doctor

System
  platform           darwin                                           
  arch               arm64                                            
  cpu                10 cores         Apple M1 Max                    
  directory          IgniteMaverick   /Users/rb/GitHub/IgniteMaverick 

JavaScript (and globally-installed packages)
  node               18.4.0       /Users/rb/.nvm/versions/node/v18.4.0/bin/node 
  npm                8.12.1       /opt/homebrew/bin/npm                         
    expo-cli         5.4.12                                                     
    npm              8.12.1                                                     
  yarn               1.22.19      /opt/homebrew/bin/yarn                        
    react-devtools   4.24.7                                                     
  pnpm               -            not installed                                 
  expo               46.0.10      managed                                       

Ignite
  ignite-cli         8.1.0        /Users/rb/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/rb/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               11.0.16      /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java 
  android home       -            /Users/rb/Library/Android/sdk                                        

iOS
  xcode              14.0.1     
  cocoapods          1.11.3       /opt/homebrew/bin/pod 

Tools
  git                git version 2.37.2   /opt/homebrew/bin/git 
```

**Comment by carlinisaacson** [comment]
This is an issue with the react-native-safe-area-context library. There are several issues in that repo regarding this.

The fix is to not use SafeAreaView and instead use their provided `useSafeAreaInsets` hook to get the insets. Then wrap your content in a regular View and set the insets using padding in the styles.

```
const insets = useSafeAreaInsets()

<View style={{paddingTop: insets.top, paddingBottom: insets.bottom }}>
  ...children
</View>
```

Ignite has been updated to use this pattern. So, newly created apps using 8.2.2 should not have this issue.
