### ISSUE TITLE
Add environmental variable support

### ISSUE THREAD

**Issue by joshuayoes** [infinitered/ignite#2239]
We provide a `config` utility in Ignite: https://github.com/infinitered/ignite/blob/master/boilerplate/app/config/config.prod.ts

This is useful. However, most project at some point need to support passing in environmental variables, such as through an `.env` file.

There are a lot of libraries that support this: 
- https://github.com/luggit/react-native-config
- https://www.npmjs.com/package/react-native-dotenv
- https://reactnative.dev/docs/security#storing-sensitive-info

--- 

It would be nice to have Ignite support this out of the box. It's a step that I feel needs to happen in most projects, but it's annoying to set up in my opinion.

**Comment by frankcalise** [comment]
@mazenchami just did this for Chain React App, perhaps we can have a team discussion on which method we use most often and implement that?

**Comment by frankcalise** [comment]
Cookbook recipe has been created!
