### ISSUE TITLE
Generator create new file without wrapper folder

### ISSUE THREAD

**Issue by xforcarlos** [infinitered/ignite#2242]
### Describe the bug

hello all
when try to generate new [ screen, model , component  ] or 
the generator create new file with out the wrapper folder 
& import index.ts file not work anymore

!Hint  create date Fri Sep 16 01:30:31 2022 +0200
 npx ignite-cli new 

``` npx ignite-cli g component cart-item ```
out put 
```
 Generated new files:
   pwd/someappName/app/components/CartItem.story.tsx
   pwd/someappName/app/components/CartItem.tsx
``` 
<img width="344" alt="Screen Shot 2022-10-01 at 10 34 52 PM" src="https://user-images.githubusercontent.com/76874617/193427333-8c06b620-1ee8-45ba-a8ef-ca817b3b0bf2.png">

model too

<img width="336" alt="Screen Shot 2022-10-01 at 10 35 20 PM" src="https://user-images.githubusercontent.com/76874617/193427350-1a4cc5a2-1848-4fd1-ae9d-1ee9295799a4.png">

```
   Generated new files:
   /app/models/Test.test.ts
   /app/models/Test.ts
   ```

### Ignite version

8.2.0

### Additional info

``` 
System
  platform           darwin                                                                
  arch               x64                                                                   
  cpu                12 cores      Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz                
  directory          openFashion   /Users/mahmoudhamdy/Desktop/me/p-work/react/openFashion 

JavaScript (and globally-installed packages)
  node                  14.19.0      /usr/local/opt/node@14/bin/node 
  npm                   6.14.16      /usr/local/opt/node@14/bin/npm  
    @sanity/cli         2.23.2                                       
    appcenter           4.2.0                                        
    appcenter-cli       2.9.0                                        
    axios               0.21.1                                       
    detox-cli           18.0.0                                       
    expo-cli            5.3.2                                        
    firebase-tools      11.8.0                                       
    ios-deploy          1.11.3                                       
    npm                 8.4.1                                        
    npm-check-updates   12.5.4                                       
    osmi-cli            1.2.0                                        
    pod-install         0.1.18                                       
    react-devtools      4.10.4                                       
    rtlcss              3.5.0                                        
    typescript          4.5.5                                        
    yarn                1.22.10                                      
  yarn                  1.22.10      /usr/local/bin/yarn             
    create-next-app     11.0.0                                       
  pnpm                  -            not installed                   
  expo                  45.0.8       managed                         

Ignite
  ignite-cli         8.2.0        /Users/mahmoudhamdy/.npm/_npx/10289/bin/ignite                        
  ignite src         build        /Users/mahmoudhamdy/.npm/_npx/10289/lib/node_modules/ignite-cli/build 

Android
  java               11.0.16.1    /usr/bin/java                           
  android home       -            /Users/mahmoudhamdy/Library/Android/sdk 

iOS
  xcode              14.0.1     
  cocoapods          1.11.3       /usr/local/bin/pod 

Tools
  git                git version 2.37.0 (Apple Git-136)   /usr/bin/git  
```

**Comment by kateinkim** [comment]
Hi @xforcarlos! Since our new v8 update on Ignite, we restructured the generated files to be added without the folder. Also, I noticed that your generator still adds a story file which shouldn't be the case with the new update either.

Will you please confirm that you have updated the generator templates? If you haven't, please replace your component template file with [this](https://github.com/infinitered/ignite/blob/master/boilerplate/ignite/templates/component/NAME.tsx.ejs)? 

Once you have the frontmatter you can modify it to generate the files at whatever path you'd like by adding `destinationDir: app/navigators` like [here](https://github.com/infinitered/ignite/blob/master/boilerplate/ignite/templates/navigator/NAMENavigator.tsx.ejs)

Hope this helps!

**Comment by xforcarlos** [comment]
@kateinkim  
thanks for help 
i use older version of ignite not maverick  
how can i use old version of cli to generate files with old structure

**Comment by xforcarlos** [comment]
@kateinkim 
thanks  i used the old version in g by 
``` npx ignite-cli@7.15.0 ```
