### ISSUE TITLE
Yarn unable to launch expo:web, missing package "webpack-dev-server"

### ISSUE THREAD

**Issue by frankcalise** [infinitered/ignite#2249]
### Describe the bug

1. `npx ignite-cli new IgniteExpoWebTest --bundle=com.igniteexpowebtest --git --install-deps --overwrite=false --packager=yarn --target-path=/Users/fcalise/code/IgniteExpoWebTest --remove-demo=false`
2. `cd IgniteExpoWebTest`
3. `yarn expo:web`

Observe the following in the terminal (can ignore the bit about the port in use):
```
yarn expo:web
yarn run v1.22.19
$ expo start --web
Starting project at /Users/fcalise/code/IgniteExpoWebTest
› Port 19000 is running chain-react-app-2023 in another window
  /Users/fcalise/code/ChainReactApp2023 (pid 21462)
✔ Use port 19001 instead? … yes
Some dependencies are incompatible with the installed expo version:
  react-native@0.69.5 - expected version: 0.69.6
  react-native-safe-area-context@4.3.4 - expected version: 4.3.1
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install react-native@0.69.6 react-native-safe-area-context@4.3.1
Starting Metro Bundler
CommandError: Missing package "webpack-dev-server" in the project. Try running the command again. (cwd: /Users/fcalise/code/IgniteExpoWebTest)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If you use the `npm` package manager, the project is able to start up via `npm run expo:web`

### Ignite version

8.0.1

### Additional info

```
System
  platform           darwin
  arch               arm64
  cpu                10 cores            Apple M1 Pro
  directory          IgniteExpoWebTest   /Users/fcalise/code/IgniteExpoWebTest

JavaScript (and globally-installed packages)
  node                16.14.2      /Users/fcalise/.nvm/versions/node/v16.14.2/bin/node
  npm                 8.5.0        /Users/fcalise/.nvm/versions/node/v16.14.2/bin/npm
    corepack          0.10.0
    eas-cli           2.1.0
    expo-cli          6.0.2
    gatsby-cli        4.21.0
    ignite-cli        8.0.1
    npm               8.5.0
    yarn              1.22.19
  yarn                1.22.19      /Users/fcalise/.nvm/versions/node/v16.14.2/bin/yarn
    create-expo-app   1.1.2
  pnpm                -            not installed
  expo                46.0.14      managed

Ignite
  ignite-cli         8.0.1        /Users/fcalise/.nvm/versions/node/v16.14.2/bin/ignite
  ignite src         src          /Users/fcalise/code/ignite/src

Android
  java               11.0.14.1    /Users/fcalise/.asdf/shims/java
  android home       -            /Users/fcalise/Library/Android/sdk

iOS
  xcode              14.0
  cocoapods          1.11.3       /opt/homebrew/bin/pod

Tools
  git                git version 2.37.0 (Apple Git-136)   /usr/bin/git
```

**Comment by sergioisidoro** [comment]
+1

**Comment by carlosa54** [comment]
Doing `yarn add webpack-dev-server@^3 -D` and adding it to the repo fixed it for me. It looks like expo webpack-config uses the webpack-dev-server version 3 configuration [here](https://github.com/expo/expo-cli/blob/main/packages/webpack-config/package.json#L70) in the expo cli [webpack.config](https://github.com/expo/expo-cli/blob/208354c051037a92c9d837bde425396244ca77c9/packages/webpack-config/src/webpack.config.ts)

**Comment by sergioisidoro** [comment]
For me `webpack-dev-server@^3` does launch, but on a clean project it still does not load with multiple console errors. Pinning it to the exact `3.11.0` also doesn't help.

**Comment by frankcalise** [comment]
@sergioisidoro yeah sorry that asset thing was what commenced the looking into Expo web, which then lead to finding out about the issue with yarn!

How are you doing now after `yarn add -D webpack-dev-server@^3` ?

Console isn't completely clean yet (we'll get there) but seems to be building and running now for me.

**Comment by sergioisidoro** [comment]
> How are you doing now after yarn add -D webpack-dev-server@^3 ?

After running the generator with `:latest` instead of `:edge` which fixed the asset issue, everything now works 👌

But the coincidence of a resource missing and a webpack issue made me immediately point fingers to webpack 😅 
Thanks for the help :)

**Comment by frankcalise** [comment]
Thank you for the help also @sergioisidoro !
