### ISSUE TITLE
Ignite generators don't work on Windows

### ISSUE THREAD

**Issue by frankcalise** [infinitered/ignite#2253]
### Describe the bug

When generating a screen with a command such as `npx ignite-cli generate screen TestScreen`, the frontmatter gets left in if executing from a Windows machine. For example:

```
---
patch:
  path: "app/screens/index.ts"
  append: "export * from \"./TestScreen\"\n"
  skip: 
---
import React, { FC } from "react"
import { observer } from "mobx-react-lite"
import { ViewStyle } from "react-native"
import { StackScreenProps } from "@react-navigation/stack"
import { AppStackScreenProps, AppStackParamList } from "../navigators"
import { Screen, Text } from "../components"
// import { useNavigation } from "@react-navigation/native"
// import { useStores } from "../models"

// STOP! READ ME FIRST!
// To fix the TS error below, you'll need to add the following things in your navigation config:
// - Add `Test: undefined` to AppStackParamList
// - Import your screen, and add it to the stack:
//     `<Stack.Screen name="Test" component={TestScreen} />`
// Hint: Look for the 🔥!

// REMOVE ME! ⬇️ This TS ignore will not be necessary after you've added the correct navigator param type
// @ts-ignore
export const TestScreen: FC<StackScreenProps<AppStackScreenProps, "Test">> = observer(function TestScreen() {
  // Pull in one of our MST stores
  // const { someStore, anotherStore } = useStores()

  // Pull in navigation via hook
  // const navigation = useNavigation()
  return (
    <Screen style={$root} preset="scroll">
      <Text text="test" />
    </Screen>
  )
})

const $root: ViewStyle = {
  flex: 1,
}
```

Fix the new line parsing based on the platform we're executing on to allow generators to be cross-platform

### Ignite version

8.2.0

### Additional info

```
System
  platform           win32
  arch               x64
  cpu                16 cores        Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
  directory          GeneratorTest   C:\temp\GeneratorTest

JavaScript (and globally-installed packages)
  node                16.14.2      C:\Program Files\nodejs\node.EXE
  npm                 8.6.0        C:\Program Files\nodejs\npm.CMD
    corepack          0.10.0
    eas-cli           0.60.0
    expo-cli          6.0.1
    ignite-cli        8.2.
    npm               8.6.0
    yarn              1.22.19
  yarn                1.22.19      C:\Program Files\nodejs\yarn.CMD
    create-expo-app   1.1.1
  pnpm                -            not installed
  expo                46.0.14      managed

Ignite
  ignite-cli         8.2.         C:\Program Files\nodejs\ignite.CMD
  ignite src         src          C:\Users\Frank\Documents\GitHub\ignite-cli\src

Android
  java               -            null
  android home       -            undefined
```

**Comment by ldm314** [comment]
@frankcalise @joshuayoes I still see this issue in my system using npx ignite-cli. The version I have:

- windows 10
- node --version: 18.12.1
- npx ignite-cli --version: 8.4.2
- npx --version: 8.19.2

**Comment by frankcalise** [comment]
> @frankcalise @joshuayoes I still see this issue in my system using npx ignite-cli. The version I have:
> 
> - windows 10
> - node --version: 18.12.1
> - npx ignite-cli --version: 8.4.2
> - npx --version: 8.19.2

Hey thanks for the update - we have a PR in the works here: https://github.com/infinitered/ignite/pull/2328

I just have to get pair with @joshuayoes at se point to clean up the unit tests, but I think the cli works.

Hope to fix it for you soon!

**Comment by ldm314** [comment]
Thanks! It's not a blocker for me, I can update the index and generated files. I did a quick search here and found this issue on it. I'll give it another try after its merged in.

**Comment by olnsbr** [comment]
Not fixed for me. 
Same problem of the original issue.

Steps to reproduce:

`npx ignite-cli@latest new PizzaApp`

`cd PizzaApp`

`npx ignite-cli generate model Sauce`

Model result:

```
---
patches:
  - path: "app/models/RootStore.ts"
    after: "from \"mobx-state-tree\"\n"
    insert: "import { SauceModel } from \"./Sauce\"\n"
    skip: true
  - path: "app/models/RootStore.ts"
    after: "types.model(\"RootStore\").props({\n"
    insert: "  sauce: types.optional(SauceModel, {} as any),\n"
    skip: true
  - path: "app/models/index.ts"
    append: "export * from \"./Sauce\"\n" 
    skip: 
---
import { Instance, SnapshotIn, SnapshotOut, types } from "mobx-state-tree"
import { withSetPropAction } from "./helpers/withSetPropAction"

/**
 * Model description here for TypeScript hints.
 */
export const SauceModel = types
  .model("Sauce")
  .props({})
  .actions(withSetPropAction)
  .views((self) => ({})) // eslint-disable-line @typescript-eslint/no-unused-vars
  .actions((self) => ({})) // eslint-disable-line @typescript-eslint/no-unused-vars

export interface Sauce extends Instance<typeof SauceModel> {}
export interface SauceSnapshotOut extends SnapshotOut<typeof SauceModel> {}
export interface SauceSnapshotIn extends SnapshotIn<typeof SauceModel> {}
export const createSauceDefaultModel = () => types.optional(SauceModel, {})
```

### Ignite Version

8.8.1

### Additional info

```
System
  platform           win32
  arch               x64
  cpu                16 cores     11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  directory          PizzaApp     C:\git\PizzaApp

JavaScript (and globally-installed packages)
  node               16.14.2                                   C:\Program Files\nodejs\node.EXE
  npm                8.5.0                                     C:\Program Files\nodejs\npm.CMD
    @angular/cli     14.1.2
    eas-cli          3.8.1
    fieldshare-web   -
    grunt-cli        1.4.3
    react-devtools   4.26.1
    sass             1.50.0
  yarn               1.22.15                                   C:\Program Files\nodejs\yarn.CMD
  pnpm               6.11.0                                    C:\Program Files\nodejs\pnpm.CMD
                     <no pnpm global package info available>
  expo               48.0.17                                   managed

Ignite
  ignite-cli         8.8.1        C:\Users\ovidi\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\ovidi\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               11.0.18      C:\Program Files\Microsoft\jdk-11.0.18.10-hotspot\bin\java.EXE
  android home       -            undefined

Tools
  git                git version 2.39.1.windows.1   C:\Program Files\Git\cmd\git.EXE
```

**Comment by joshuayoes** [comment]
Enough people are reporting this as an issue that I'll re-open this for now

**Comment by Badtor** [comment]
Same here on **ignite-cli 8.8.2**

Steps to reproduce:

`npx ignite-cli@latest new TestIgnite`

`cd TestIgnite`

`npx ignite-cli generate screen Dashboard`

After the command the prompt result is:

```
Generated new files:
C:\Users\MyUserName\Desktop\Projects\React-Native\testignite\app\screens\DashboardScreen.tsx
```

The result of DashboardScreen generated as follow:

```
---
patches:
- path: "app/screens/index.ts"
  append: "export * from \"./DashboardScreen\"\n"
  skip: 
- path: "app/navigators/AppNavigator.tsx"
  replace: "// IGNITE_GENERATOR_ANCHOR_APP_STACK_PARAM_LIST"
  insert: "Dashboard: undefined\n\t// IGNITE_GENERATOR_ANCHOR_APP_STACK_PARAM_LIST"
- path: "app/navigators/AppNavigator.tsx"
  replace: "{/* IGNITE_GENERATOR_ANCHOR_APP_STACK_SCREENS */}"
  insert: "<Stack.Screen name=\"Dashboard\" component={Screens.DashboardScreen} />\n\t\t\t{/* IGNITE_GENERATOR_ANCHOR_APP_STACK_SCREENS */}"
  skip: 
---
import React, { FC } from "react"
import { observer } from "mobx-react-lite"
import { ViewStyle } from "react-native"
import { NativeStackScreenProps } from "@react-navigation/native-stack"
import { AppStackScreenProps } from "app/navigators"
import { Screen, Text } from "app/components"
// import { useNavigation } from "@react-navigation/native"
// import { useStores } from "app/models"

interface DashboardScreenProps extends NativeStackScreenProps<AppStackScreenProps<"Dashboard">> {}

export const DashboardScreen: FC<DashboardScreenProps> = observer(function DashboardScreen() {
  // Pull in one of our MST stores
  // const { someStore, anotherStore } = useStores()

  // Pull in navigation via hook
  // const navigation = useNavigation()
  return (
    <Screen style={$root} preset="scroll">
      <Text text="dashboard" />
    </Screen>
  )
})

const $root: ViewStyle = {
  flex: 1,
}
```

### Ignite version (as fresh intallation)
8.8.2

### ignite-cli doctor
```
System
  platform           win32
  arch               x64
  cpu                8 cores      Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  directory          testignite   C:\Users\Salvatore\Desktop\Projects\React-Native\testignite 

JavaScript (and globally-installed packages)
  node               16.13.2      C:\Program Files\nodejs\node.EXE
  npm                9.6.7        C:\Program Files\nodejs\npm.CMD
    npm              9.6.7
  yarn               -            not installed
  pnpm               -            not installed
  expo               48.0.17      managed

Ignite
  ignite-cli         8.8.2        C:\Users\Salvatore\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\Salvatore\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               -            null
  android home       -            C:\Users\Salvatore\AppData\Local\Android\Sdk

Tools
  git                -            not installed
```

**Comment by frankcalise** [comment]
@olnsbr @Badtor question for you both if you don't mind trying something:

1. Since on Windows, can you open up one of the generator templates, ie: `PizzaApp\ignite\templates\screen\NAMEScreen.tsx.ejs`

2. Then, in VS Code (or however else you want to) change the line endings from LF to CRLF (which Windows expects, but it's checked into git with regular LF). Safe that file.

3. Re-run the generator and see that it generates all the proper files and the front matter is removed.

This worked for me, hope it reproduces correctly.

**Comment by olnsbr** [comment]
Thanks a lot @frankcalise, that was so easy. 
I used the Notepad++ EOL conversion tool and it fixed the problem.

1. Opened the file, ie: `PizzaApp\ignite\templates\screen\NAMEScreen.tsx.ejs`
2. View -> Show Symbol -> Show End of Line
3. Edit -> EOL Conversion -> Windows
4. Save the file.

Re-run the generator and worked fine.

Thanks again!

**Comment by frankcalise** [comment]
@olnsbr glad it worked for you! Thanks for confirming that fix, will figure out a solution to provide it in the cli so the end user doesn't have to think about this.

**Comment by Badtor** [comment]
> @olnsbr @Badtor question for you both if you don't mind trying something:
> 
> 1. Since on Windows, can you open up one of the generator templates, ie: `PizzaApp\ignite\templates\screen\NAMEScreen.tsx.ejs`
> 2. Then, in VS Code (or however else you want to) change the line endings from LF to CRLF (which Windows expects, but it's checked into git with regular LF). Safe that file.
> 3. Re-run the generator and see that it generates all the proper files and the front matter is removed.
> 
> This worked for me, hope it reproduces correctly.

I'm sorry for the late.

Thanks @frankcalise and @olnsbr, in definitely I have adopted the method of @olnsbr cause in VS Code I wasn't able to see the EOF Symbols correctly. So as @olnsbr mention, these are my steps:

1. Opened the file, ie: `PizzaApp\ignite\templates\screen\NAMEScreen.tsx.ejs`
2. View -> Show Symbol -> Show End of Line
3. Edit -> EOL Conversion -> Windows
4. Save the file.
5. In prompt I've lounched: `npx ignite-cli generate screen Dashboard`

It works. <g-emoji alias="tada" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f389.png" class="social-button-emoji">🎉</g-emoji><g-emoji alias="tada" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f389.png" class="social-button-emoji">🎉</g-emoji><g-emoji alias="tada" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f389.png" class="social-button-emoji">🎉</g-emoji>

Thank you so much! <g-emoji alias="tada" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f499.png?v8" class="social-button-emoji">💙</g-emoji>

**Comment by priyanshusaini105** [comment]
> **Thanks Every one;**


### For those who are still struggling in VS CODE
1. In **VS code** you can find the LF in bottom Tabbar **right side**
2. Opened the file, ie: `PizzaApp\ignite\templates\screen\NAMEScreen.tsx.ejs`
3. Change LF to CRLF
![image](https://github.com/infinitered/ignite/assets/76811245/d765bd2a-03d8-47f7-b7ce-885e15a7f85b)

4. In prompt I've lounched: `npx ignite-cli generate screen Dashboard`
5. Boom I worked

**Comment by frankcalise** [comment]
@joshuayoes maybe we can have prettier format these after copying via `--end-of-line crlf` for just those template files?

**Comment by joshuayoes** [comment]
I didn't know about that setting, that's a great idea

**Comment by Microhive** [comment]
The proposed solution works. But is there any particular reason why we have to change the line endings for Windows? If this is the expected behaviour then I would expect it to be mentioned in the Generators guide: https://github.com/infinitered/ignite/blob/master/docs/Generators.md

**Comment by frankcalise** [comment]
@Microhive are you having issues? What is your experience like?

I cannot reproduce this on my Windows 10 machine, using PowerShell and Ignite 8.9.4. Every generator works properly.

![image](https://github.com/infinitered/ignite/assets/374022/326c95ef-911b-4fd2-9cba-09c7a86069c6)

**Comment by frankcalise** [comment]
I have an idea for a fix here, will give it a try tomorrow.

**Comment by Microhive** [comment]
@frankcalise I have the following setup:
- Windows 11 64x 10.0.22621 Build 22621
- Yarn 1.22.19
- NPM 10.1.0
- Node 20.5.1

**Comment by frankcalise** [comment]
@Microhive should be automatic now in 8.10.1

Also made a documentation update in the event someone does need additional manual help with it, so thanks for that suggestion as well
