### ISSUE TITLE
Expo iOS App gets stuck on SplashScreen

### ISSUE THREAD

**Issue by engineerStuardo** [infinitered/ignite#2259]
### Describe the bug

I created a new repo with ignite boilerplate, then right away I just did expo publish and everything went fine. Then I scanned the QR on iOS devices and it got stuck in the SplashScreen and It's running fine on Android.

Here is the published app for you to test it: https://expo.dev/@stuardocortez/NewPizzaApp

### Ignite version

latest

### Additional info

.

**Comment by frankcalise** [comment]
Hi @engineerStuardo - expo publish using the classic Expo CLI? If you don't mind, could you please run `npx ignite-cli doctor` from the project directory and paste the output here?

Also please include your publish commands as well.

Thank you!

**Comment by engineerStuardo** [comment]
@frankcalise thanks for your answered. Here are the steps I'm following:

https://user-images.githubusercontent.com/72483443/194842009-005c8887-4e9e-4e48-809a-c0e20a53051a.mp4

and here it's the output of `npx ignite-cli doctor`:
```
System
  platform           darwin
  arch               arm64
  cpu                10 cores      Apple M1 Pro
  directory          NewPizzaApp   /Users/Stuardo/workspace/ReactNative/NewPizzaApp

JavaScript (and globally-installed packages)
  node               16.17.1      /opt/homebrew/bin/node
  npm                8.15.0       /opt/homebrew/bin/npm
    corepack         0.12.1
    eas-cli          2.2.1
    expo-cli         6.0.6
    npm              8.15.0
    yarn             1.22.19
  yarn               1.22.19      /opt/homebrew/bin/yarn
  pnpm               -            not installed
  expo               46.0.15      managed

Ignite
  ignite-cli         8.2.5        /Users/Stuardo/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/Stuardo/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               11.0.16.1    /usr/bin/java
  android home       -            /Users/Stuardo/Library/Android/sdk

iOS
  xcode              14.0.1
  cocoapods          1.11.3       /usr/local/bin/pod

Tools
  git                git version 2.37.0 (Apple Git-136)   /usr/bin/git
```

**Comment by frankcalise** [comment]
@engineerStuardo Hey thanks for the extra info! Are you meaning to use a bare workflow or an Expo managed work flow? The boilerplate allows for quick development/debugging of either, but I'm thinking you probably have to decide when going through with publish. 

From the terminal output it looks like Expo is picking up a bare workflow due to the native ios/android directories. However, if you don't want to work with the native code, try removing these directories and `index.js` and `react-native-bootsplash` package.

I have returned from traveling today, I will try to come up with some reproducible steps for you.

Please let me know if you intend to use the bare workflow, however. Thank you!

**Comment by engineerStuardo** [comment]
@frankcalise The idea is to have a Managed expo app. In this case I deleted `ios / android` folder and `index.js` and `react-native-bootsplash`. Then I published the app with `expo publish` and also `eas update`. And both of them gets stuck on SplashScreen, works on iOS and Android on simulators but the published version doesn't work on iOS just working on Android.

URL: https://expo.dev/@stuardocortez/testExpoPublish?serviceType=classic&distribution=expo-go

**Comment by frankcalise** [comment]
@engineerStuardo Sorry you're having trouble, but thanks for the info! Will take a look and get back to you

**Comment by engineerStuardo** [comment]
It should be like in the screenshot below, right?

![Screen Shot 2022-10-10 at 10 58 00](https://user-images.githubusercontent.com/72483443/194917698-4c9753c2-1a56-47af-867b-d35d2fdc2eb4.png)

**Comment by frankcalise** [comment]
Viewer should be fine

**Comment by engineerStuardo** [comment]
I just sent you the invite, thanks a lot @frankcalise

**Comment by frankcalise** [comment]
Thanks I'm able to see the issue in action now

**Comment by frankcalise** [comment]
It's interesting because even running `yarn expo:start --no-dev --minify` still works in the simulator (which would put the app in production mode like a publish). I was hoping to gain some information locally by running in release mode.

https://docs.expo.dev/workflow/development-mode/#production-mode

**Comment by engineerStuardo** [comment]
I know, right?... Do you think there's something else we can do to make it works?

**Comment by frankcalise** [comment]
@engineerStuardo Hey! I think it's hermes related. For now head over to your `app.json` and switch the `jsEngine` property to `jsc`. Publish again and see if that works for you.

**Comment by engineerStuardo** [comment]
@frankcalise OMG... awesome, it worked. I just tested with `expo publish` and `eas update` and it worked without any issue. I really appreciate all your help.

**Comment by frankcalise** [comment]
@engineerStuardo Thanks, glad it worked for you!

**Comment by engineerStuardo** [comment]
hey sorry to bother you @frankcalise :( , in this case the SplashScreen and Icon it's no showing in the publish version but it's working locally: 

https://expo.dev/accounts/stuardocortez/projects/testExpoPublish/updates/d8595363-dcf4-4b08-862a-046c08fcef50

**Comment by frankcalise** [comment]
@engineerStuardo if you wouldn't mind, could you please open another issue with steps to reproduce as it is different from this one.

Thanks
