### ISSUE TITLE
Detect npm permission issues and display friendly error message when installing globally

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#226]
- [x] Issue does not already exist
- [x] about ignite the cli

Per issue #219, npm will fail with a `EACCES` error when installing globally sometimes. It has to do with [this video](https://docs.npmjs.com/getting-started/fixing-npm-permissions) where the solutions are:
1. Change the permission to npm's default directory.
2. Change npm's default directory to another directory.
3. Install node with a package manager that takes care of this for you.

Perhaps there's a way to detect this situation and display a friendly error message. Also, I wonder if other npm modules have done just this. Might do some searching to see.

**Comment by dangrsmind** [comment]
Posted here: https://github.com/infinitered/ignite/issues/219#issuecomment-231069508

**Comment by skellock** [comment]
Many of these permission issues are now resolved.  In Ignite 2 we are not attempting to write into a protected directory.
