### ISSUE TITLE
Showcase component does not scroll on the web

### ISSUE THREAD

**Issue by Dolabok** [infinitered/ignite#2261]
### Describe the bug

Hello 
I noticed that the list of components on the demo page does not scroll on the web. I think this is related to the presence of the drawer menu on the page, the scrolling works correctly on other pages where it is not present.
You can open the drawer by holding the click and dragging the mouse to the right as you might do with the thumb on mobile, I think this behavior cancels the vertical scrolling.

Step to reproduce, just create and lunch a new application with the last version (and add webpack) :

npx ignite-cli@latest new myApp
yarn add -D webpack-dev-server@^3

I open the bug for now, I'll see about fixing it in the next few days if nobody does it by then

### Ignite version

8.2.5

### Additional info

System
  platform           linux                                                      
  arch               x64                                                        
  cpu                8 cores      Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz     
  directory          myApp   /home/dolabok/Documents/projects/myApp 

JavaScript (and globally-installed packages)
  node                 16.15.1      /usr/bin/node 
  npm                  8.19.2       /usr/bin/npm  
    corepack           0.10.0                     
    expo-cli           6.0.6                      
    npm-check          5.9.2                      
    npm                8.19.2                     
    serve              13.0.2                     
    sharp-cli          2.1.1                      
  yarn                 1.22.19      /usr/bin/yarn 
    create-react-app   5.0.1                      
  pnpm                 -            not installed 
  expo                 46.0.15      managed       

Ignite
  ignite-cli         7.14.1       /home/dolabok/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /home/dolabok/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               17.0.1       /usr/bin/java 
  android home       -            undefined

**Comment by frankcalise** [comment]
Hey @Dolabok thanks for reporting the issue! We have noticed this and are trying to streamline the web experience as best we can.

Can you see if this change alleviates your problem in the `DemoShowroomScreen.tsx`?

Change from `<Screen` wrapper around the `<SectionList` to `<SafeAreaView style={$screenContainer}>` and add the style, here is the git diff as an example:

```
--- a/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
+++ b/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
@@ -119,7 +119,7 @@ export function DemoShowroomScreen(_props: DemoTabScreenProps<"DemoShowroom">) {
         </SafeAreaView>
       )}
     >
-      <Screen preset="fixed" safeAreaEdges={["top", "bottom"]}>
+      <SafeAreaView style={$screenContainer}>
         <DrawerIconButton onPress={toggleDrawer} {...{ open, progress }} />

         <SectionList
@@ -146,11 +146,17 @@ export function DemoShowroomScreen(_props: DemoTabScreenProps<"DemoShowroom">) {
             )
           }}
         />
-      </Screen>
+      </SafeAreaView>
     </DrawerLayout>
   )
 }

+const $screenContainer = {
+  flex: 1,
+  backgroundColor: colors.background,
+}
+
 const $drawer: ViewStyle = {
   flex: 1,
 }
```

**Comment by Dolabok** [comment]
wonderful, the scrolling is back 
thank you

**Comment by frankcalise** [comment]
@Dolabok you're welcome! thanks for the feedback, we'll look to fold this change in upstream

**Comment by Dolabok** [comment]
Is there a list of planed tasks for web compatibility? I could possibly make pull requests

**Comment by frankcalise** [comment]
@Dolabok nothing at the moment, just started doing more testing with the web side and noting things. Feel free to create issues and work on some PRs though!

**Comment by Dolabok** [comment]
noted, thank you!

**Comment by notAunty** [comment]
Hi, curious to know why wouldn't this works?
```
-        <Screen preset="fixed" safeAreaEdges={["top", "bottom"]}>
+        <Screen preset="auto" safeAreaEdges={["top", "bottom"]}>
```

**Comment by frankcalise** [comment]
@notAunty Yeah that won't allow mobile to work.

However another solution leaving the Screen component in there is to add the following style
`<Screen preset="fixed" safeAreaEdges={["top", "bottom"]} contentContainerStyle={{ flex: 1 }}>`

That should enable scrolling on web and mobile properly as well.

We'll fix this in main when we decide which solution we want, but either of those should get you both going. 

Thanks for the feedback
