### ISSUE TITLE
Splash Screen and Icon not showing on Expo Go (Published app with EAS, working fine with expo publish)

### ISSUE THREAD

**Issue by engineerStuardo** [infinitered/ignite#2263]
### Describe the bug

When you configure an ignite Managed Expo App (I deleted `ios`, `android` folders and `index.js`. Also removed `react-native-bootsplash`). And configured app.json from `hermes` to `jsc` in `jsEngine` property. Then the app is running fine local and publish but in the published version is not showing SplashScreen and Icon Image (Just showing the background color). This scenario is when you publish the app with `eas update` because when you do `expo publish` works fine.

### Project with eas update:
Link to run it on Expo Go:
exp://u.expo.dev/update/2b324d2b-dcf4-4fd1-98d0-51004b7447c9

https://expo.dev/accounts/stuardocortez/projects/testExpoPublish/updates/54c4dc14-277a-49ea-a580-5d1011d9ecd4

### Project with expo publish:
https://expo.dev/@stuardocortez/expoPublisTest?serviceType=classic&distribution=expo-go

### Ignite version

latest

### Additional info

```
System
  platform           darwin
  arch               arm64
  cpu                10 cores          Apple M1 Pro
  directory          testExpoPublish   /Users/Stuardo/workspace/ReactNative/testExpoPublish

JavaScript (and globally-installed packages)
  node               16.17.1      /opt/homebrew/bin/node
  npm                8.15.0       /opt/homebrew/bin/npm
    corepack         0.12.1
    eas-cli          2.3.0
    expo-cli         6.0.6
    npm              8.15.0
    yarn             1.22.19
  yarn               1.22.19      /opt/homebrew/bin/yarn
  pnpm               -            not installed
  expo               46.0.15      managed

Ignite
  ignite-cli         8.2.5        /Users/Stuardo/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/Stuardo/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               11.0.16.1    /usr/bin/java
  android home       -            /Users/Stuardo/Library/Android/sdk

iOS
  xcode              14.0.1
  cocoapods          1.11.3       /usr/local/bin/pod

Tools
  git                git version 2.37.0 (Apple Git-136)   /usr/bin/git
```

**Comment by frankcalise** [comment]
@engineerStuardo Can you list your EAS build/submit/update commands here so I can properly reproduce? Thanks!

**Comment by engineerStuardo** [comment]
I just did the following:
```
eas init
eas update:configure
eas update
```

and I don't have a `eas.json`, should I have one? and if so, which structure should it have?

EAS build:
![Screen Shot 2022-10-11 at 07 01 40](https://user-images.githubusercontent.com/72483443/195097995-256b9fbe-0408-4c11-8482-c38900691c07.png)


EAS update: 
![Screen Shot 2022-10-11 at 07 00 50](https://user-images.githubusercontent.com/72483443/195097759-a29c8233-172a-4634-8f3a-73102a64bef7.png)

**Comment by frankcalise** [comment]
I'd first follow the [Creating your first build](https://docs.expo.dev/build/setup/) Expo documentation. If you don't want to wait for the EAS queue time you can add the `--local` flag to [build an `APK` or `.app` locally](https://docs.expo.dev/build-reference/local-builds/) and try it on your Android device or iOS simulator.

From these steps the splash screen and app icon appear fine. Your experience is running in Expo Go still which is a preview and not a standalone app that would reflect a final product.

I can't say what the reasoning is for the splash being different at this time but I don't believe it would look this way when actually creating store builds - so I'd test that part first and see the results.

**Comment by frankcalise** [comment]
This could also be related https://github.com/expo/expo/issues/18691
