### ISSUE TITLE
Detox Testing Link Is Broken In Docs

### ISSUE THREAD

**Issue by NoMoreTickets** [infinitered/ignite#2267]
### Describe the bug

Steps to repeat:

1. Navigate to https://github.com/infinitered/ignite in browser.
2. Go to "docs" folder
3. Click on "Testing.md" link
4. Find the heading on the page titled "Detox Testing"
5. On the line "We provide a [README.md](https://github.com/infinitered/ignite/blob/master/docs/%5B../boilerplate/detox/README.md%5D) inside of Ignite for how to get started with and run Detox tests once you have Ignited your app.", if you click on the README.md link you are redirected to a "404 Not Found" page

### Ignite version

8360c310fa0554bc6c663ec511bf8b86751d1e01

### Additional info

[asdf](https://github.com/infinitered/ignite/blob/master/docs/%5B../boilerplate/detox/README.md%5D)

**Comment by frankcalise** [comment]
Thanks, good find!
