### ISSUE TITLE
DrawerIconButton progress can get stuck in interpolation

### ISSUE THREAD

**Issue by DeMuu** [infinitered/ignite#2274]
### Describe the bug

Hi,

I'm new to the project, first of all, thanks for the great boilerplate!  ❤️ 

While testing the demo project I noticed that the DrawerIconButton progress interpolation gets stuck when you pull it and then let it snap back. This happens when opening or closing.

Steps to reproduce:

1. Navigate to components screen
2. Pull from the left to open the drawer to a point where it would snap back (probably less than 50%?)
3. Release the drawer

You can see the result in this screenshot
![IMG_699381D8EFE3-1 2](https://user-images.githubusercontent.com/19406963/197565355-99f602e5-2e6c-40ce-ac88-5feaebb6ca96.jpeg)

### Ignite version

8.2.5

### Additional info

System
  platform           darwin
  arch               x64
  cpu                12 cores     Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz

**Comment by jamonholmgren** [comment]
@DeMuu Thanks for reporting! I've confirmed this is indeed happening.

![CleanShot 2022-11-14 at 11 02 50@2x](https://user-images.githubusercontent.com/1479215/201743996-d61d709d-9c18-49d2-8da8-a30ead84209f.png)

**Comment by frankcalise** [comment]
@jamonholmgren PR is up!
