### ISSUE TITLE
Storyboard Required for iOS Submission

### ISSUE THREAD

**Issue by objectiveSee** [infinitered/ignite#2292]
### Describe the bug

I just created a new app using ignite however I got an error when submitting to Apple. They are requiring a storyboard file. I am wondering if this is something that ignite handles which I may have configured incorrectly. I actually was able to submit my app once without an issue, but my second build for some reason triggered this error from Apple.

I am also using Expo fully. One fix is to open Xcode and make the app "require full screen" but this feels like the wrong solution given I am building within Expo.

_[logs] ERROR: Asset validation failed (90476) Invalid bundle. Because your app supports Multitasking on iPad, you need to include the SplashScreen launch storyboard file in your **app-name** bundle. Use UILaunchScreen instead if the app’s MinimumOSVersion is 14 or higher and you prefer to configure the launch screen without storyboards. For details, see: https://developer.apple.com/documentation/bundleresources/information_property_list/uilaunchstoryboardname (ID: f2bc540e-6148-4983-9691-a9a3997a0ea6)_

### Ignite version

8.2.10

### Additional info

System
  platform           darwin                                       
  arch               arm64                                        
  cpu                8 cores      Apple M1                        
  directory          myAppName     /Users/username/workspace/myAppName 

JavaScript (and globally-installed packages)
  node                    17.5.0       /Users/username/.nvm/versions/node/v17.5.0/bin/node 
  npm                     8.19.2       /opt/homebrew/bin/npm                            
    @tmcw/togeojson-cli   2.0.1                                                         
    eas-cli               2.6.0                                                         
    expo-cli              6.0.6                                                         
    firebase-tools        11.14.1                                                       
    nodemon               2.0.20                                                        
    npm                   8.19.2                                                        
    nvm                   0.0.4                                                         
    serve                 14.0.1                                                        
    sharp                 0.31.1                                                        
    yarn                  1.22.19                                                       
  yarn                    1.22.19      /opt/homebrew/bin/yarn                           
    patch-package         6.4.7                                                         
    pod-install           0.1.32                                                        
  pnpm                    -            not installed                                    
  expo                    -            not installed                                    

Ignite
  ignite-cli         8.2.10       /Users/username/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/username/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               -            not installed 
  android home       -            undefined     

iOS
  xcode              13.2.1     
  cocoapods          1.11.3       /opt/homebrew/bin/pod 

Tools
  git                git version 2.32.0 (Apple Git-132)   /usr/bin/git

**Comment by frankcalise** [comment]
@objectiveSee have you removed the native android/ios directories?

**Comment by objectiveSee** [comment]
@frankcalise no, they are still there. Should I remove them?

**Comment by objectiveSee** [comment]
@frankcalise thanks for the quick reply! I tried the steps listed in that link, but now I get a warning when running `eas build --platform ios`. 

First, I made a fresh RN ignite app and ran `eas build --platform ios` successfully. Then I made the changes per the "pristine" method. Does anything jump out to you as incorrect here?

The actions I took were:
1. Start with a fresh RN Ignite project
2. `eas build --platform ios` works fine! ✅ 
3. `rm -rf ios/`
4. `rm -rf android/`
5. `rm index.js`
6. `yarn remove react-native-bootsplash`
7. finally, I ran `eas build --platform ios`

Warning: 
```
It looks like that you are using a custom metro.config.js that does not extend @expo/metro-config.
This can result in unexpected and hard to debug issues, like missing assets in the production bundle.
We recommend you to abort, fix the metro.config.js, and try again.
Learn more on customizing Metro
```

**Comment by frankcalise** [comment]
@objectiveSee mind pasting me the contents of your metro config?

**Comment by objectiveSee** [comment]
Here is `metro.config.js`. I haven't touch it since initializing the project:

```
const { getDefaultConfig } = require("metro-config")
const { getDefaultConfig: getDefaultExpoConfig } = require("@expo/metro-config")

let metroConfig
let isExpo = false
try {
  const Constants = require("expo-constants")
  // True if the app is running in an `expo build` app or if it's running in Expo Go.
  isExpo =
    Constants.executionEnvironment === "standalone" ||
    Constants.executionEnvironment === "storeClient"
} catch {}

if (isExpo) {
  /**
   *  Expo metro config
   * Learn more https://docs.expo.io/guides/customizing-metro

   * For one idea on how to support symlinks in Expo, see:
   * https://github.com/infinitered/ignite/issues/1904#issuecomment-1054535068
   */
  metroConfig = getDefaultExpoConfig(__dirname)
} else {
  /**
   * Vanilla metro config - we're using a custom metro config because we want to support symlinks
   * out of the box. This allows you to use pnpm and/or play better in a monorepo.
   *
   * You can safely delete this file and remove @rnx-kit/metro-* if you're not
   * using PNPM or monorepo or symlinks at all.
   *
   * However, it doesn't hurt to have it either.
   */
  const { makeMetroConfig } = require("@rnx-kit/metro-config")
  const MetroSymlinksResolver = require("@rnx-kit/metro-resolver-symlinks")

  metroConfig = (async () => {
    const defaultConfig = await getDefaultConfig()
    return makeMetroConfig({
      projectRoot: __dirname,
      // watchFolders: [`${__dirname}/../..`], // for monorepos
      resolver: {
        /**
         * This custom resolver is for if you're using symlinks.
         *
         * You can disable it if you're not using pnpm or a monorepo or symlinks.
         */
        resolveRequest: MetroSymlinksResolver(),
        assetExts: [...defaultConfig.resolver.assetExts, "bin"],
      },
    })
  })()
}

module.exports = metroConfig

```

**Comment by frankcalise** [comment]
@objectiveSee understood, can you try something like the following, I'm curious if the expo / vanilla config switching isn't happening properly

```
const { getDefaultConfig: getDefaultExpoConfig } = require("@expo/metro-config")

let metroConfig = getDefaultExpoConfig(__dirname)

module.exports = metroConfig
```

**Comment by objectiveSee** [comment]
@frankcalise I was able to get everything working by doing another fresh app using Ignite and removing the ios and android directories. I am not 100% sure why the metro stuff was not working, but now that is also working fine. Perhaps I ran some incorrect command along the way. I can close this one for now but will re-open if I experience the same issue again.

Appreciate the help!
