### ISSUE TITLE
can't ignite new app on windows11

### ISSUE THREAD

**Issue by MirGhojam** [infinitered/ignite#2293]
### Describe the bug

I ran the create new app command as suggested on my terminal, but after the installation of the cli, there are no follow up prompt. The whole procedure is suddenly stopped with no extra warnings or anything.

### Ignite version

8.3.0

### Additional info

somthing wrong with my network, can't upload the image. It goes like this:

```
C:\Users\Raytine>npx ignite-cli@latest new PizzaApp
Need to install the following packages:
  ignite-cli@8.3.0
Ok to proceed? (y) y

C:\Users\Raytine>
```

**Comment by frankcalise** [comment]
@MirGhojam Hey! Sorry you're having trouble. A couple of questions:

0. Add the `--debug` flag for verbose logging, maybe at least something will show up in the terminal
1. Does `npx` normally work for you on this machine or is this a new machine? If unsure, could you try `npx` with another package?
2. Maybe it's a privileges issue? Try running the shell (VSCode or PowerShell) as admin?
3. Check Windows EventViewer for any logs that might show up near the timestamp you are running the commands if things are failing silently.

**Comment by frankcalise** [comment]
@MirGhojam Hey, just following up - are you still having issues?

**Comment by frankcalise** [comment]
@MirGhojam so adding `--debug` to the install command displays no output?

You searched EventViewer and there are no errors?
