### ISSUE TITLE
In spacing should be same naming as in fonts

### ISSUE THREAD

**Issue by ryskin** [infinitered/ignite#2308]
That's really confusing in one place use **extraLarge** in another place it's just **xl**. I think naming is much more intuitive in fonts.

<img width="210" alt="image" src="https://user-images.githubusercontent.com/3756722/202340341-81d87238-d1ef-42b4-9450-20a794d3f557.png">

<img width="449" alt="image" src="https://user-images.githubusercontent.com/3756722/202340414-3e4f035d-2db7-48c6-be29-1f5b7ae32a73.png">

I propose adding more x ) like **xxxs** and **xxxl**, for extra small and extra big sizes.

The current demo really is the best of all time.

**Comment by yulolimum** [comment]
I like this proposal. I get confused between micro/tiny and huge/massive all the time. @robinheinze what do you think?

**Comment by jamonholmgren** [comment]
I don't have an opinion on which one is better, but I agree they should be consistent.

BTW, the `as TextStyle` doesn't do actual type-checking, just coerces/casts it as that.

<img width="894" alt="CleanShot 2022-11-16 at 19 22 39@2x" src="https://user-images.githubusercontent.com/1479215/202347032-75a7bb03-43ee-49ed-ac4d-8d5dd1c72f28.png">

I seem to remember some way to make a generic that would actually type-check when used `as Only<Thing>` or something, though?

**Comment by yulolimum** [comment]
@jamonholmgren 

It doesn't do typechecking but it does typeahead:
![yulolimum-capture-2022-11-16--19-34-39](https://user-images.githubusercontent.com/1775841/202348882-5164a239-177f-4413-a540-db42c7a00fad.jpg)

You can do `Record` generic...
![yulolimum-capture-2022-11-16--19-35-36](https://user-images.githubusercontent.com/1775841/202348896-f635ae08-798f-4bc3-a1f4-e2aca490cb15.jpg)

...but you lose the key union type that we have higher up in the component:
![yulolimum-capture-2022-11-16--19-37-23](https://user-images.githubusercontent.com/1775841/202349020-3d1ff91d-caea-465c-b451-af375c40bdb9.jpg)

If you have a way to do both - would be great!

**Comment by jamonholmgren** [comment]
Opened #2309 for that.

**Comment by robinheinze** [comment]
I'm totally fine if we want to change spacing scale to match the text size scale.
