### ISSUE TITLE
Better types for $sizeStyles

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#2309]
Per #2308, specifically [this comment](https://github.com/infinitered/ignite/issues/2308#issuecomment-1318011470), it would be good to get type-checking on the $sizeStyles object.

Currently, we're using `as TextStyle`, which just coerces but doesn't typecheck the object.

![as TextStyle](https://user-images.githubusercontent.com/1479215/202347032-75a7bb03-43ee-49ed-ac4d-8d5dd1c72f28.png)

@yulolimum had some ideas in [this comment](https://github.com/infinitered/ignite/issues/2308#issuecomment-1318017830) as well.

I remember seeing some sort of solution that involved an identity function that took a generic type, but I'm having trouble tracking it down. I'll post it here if I find it.

**Comment by jamonholmgren** [comment]
This is one approach that works, but I don't like it.

<img width="1218" alt="CleanShot 2022-11-16 at 20 18 23@2x" src="https://user-images.githubusercontent.com/1479215/202354563-7fd9470f-da08-48bd-a75d-d0ea927d2535.png">

**Comment by jamonholmgren** [comment]
Okay, so this seems to be the way to go -- use `satisfies`, which exists in TypeScript 4.9.x.

<img width="1149" alt="CleanShot 2022-11-16 at 20 29 59@2x" src="https://user-images.githubusercontent.com/1479215/202355647-a7fd9dd3-11f5-478e-8672-bcccc2bc7986.png">

Note that one must use the workspace TypeScript version rather than VS Code's built-in TS version.

<img width="514" alt="CleanShot 2022-11-16 at 20 29 06@2x" src="https://user-images.githubusercontent.com/1479215/202355705-5d24ff2e-0f93-40dd-81eb-8a9d13f3e7d7.png">

To me, this probably means we should wait for VS Code to be updated to TypeScript 4.9, and then deploy this change. We don't want to have to tell everyone to adjust their VS Code settings so it works.

**Comment by kateinkim** [comment]
@jamonholmgren VScode updated its type version: https://code.visualstudio.com/updates/v1_74#_typescript-49 thus `satisfies` will work for everyone. 😃

**Comment by frankcalise** [comment]
Fixed by #2437

**Comment by frankcalise** [comment]
Need to fix the linter
