### ISSUE TITLE
Naming in screen generators is different from demo screens, also casing issue

### ISSUE THREAD

**Issue by ryskin** [infinitered/ignite#2310]
`npx ignite-cli generate screen Calendar`

create **app/screens/calendar/calendarScreen.tsx**

1) Name of the file in a different casing, should be CalendarScreen.tsx
2) I think should be used the same pattern as in the Demo project.
- app/screens/CalendarScreen/CalendarScreen.tsx
- app/screens/CalendarScreen/index.tsx

**Comment by ryskin** [comment]
also noticed that import paths are wrong in the generated file, anyway it's useful and easy to adapt but anyway it's working not as expected.

**Comment by frankcalise** [comment]
@ryskin are you sure you aren't point at an old Ignite version, could you please post which you are using?

`npx ignite-cli generate screen Calendar`

results in this for me:

```
   Generated new files:
   C:\temp\PizzaApp\app\screens\CalendarScreen.tsx
```

**Comment by ryskin** [comment]
hmm Ignite ignite-cli         7.15.0

**Comment by ryskin** [comment]
yes, my bad, latest is 8.3.4
case is closed )
