### ISSUE TITLE
[Android] Heavy size apk when build release

### ISSUE THREAD

**Issue by vantuan88291** [infinitered/ignite#2312]
A long time ago, when i used ignite version that include react native 0.62.x, the apk size just around 19-20mb, and when i released on playstore, its just 8-10mb. And now i cannot believe that the apk file over 50mb(on my project 66mb) for react native version 0.69. Do you guys have any ideals for reduce the apk file?
This is what i did for reduce it:
- enable proguard
- enable r8(by default)
- enable engine hermes
- remove file not use(like image...)

And i think the reason come from expo core, should we remove expo module for react native CLI?

**Comment by jamonholmgren** [comment]
We'll definitely look into this, @vantuan88291! I don't want to remove the `expo` core library from Ignite, as Expo libraries are super important to our workflow, but I'm sure there are opportunities to reduce the apk file size quite a bit.

**Comment by frankcalise** [comment]
@vantuan88291 Thanks for your concern! Can you let us know how you are bundling your app? Also is there a reason for not choosing AAB or are you just producing dev APKs for now?

**Comment by vantuan88291** [comment]
> @vantuan88291 Thanks for your concern! Can you let us know how you are bundling your app? Also is there a reason for not choosing AAB or are you just producing dev APKs for now?

i just want to build apk file in release mode, of course AAB file to upload to playstore will be lighter, but the point is apk file in release mode. So heavy

**Comment by maqeelqureshi** [comment]
For testing purpose i have created a new app to check APK and AAB file sizes.

**APK : 64 mb
AAB : 29 mb**

I uploaded AAB 29 mb to microsoft app center, but when i was installing, it actually downloaded and installed **64 mb APK** file. So there is no difference if i generate apk or aab files on app center (not sure about store).

Appcenter link : 
install.appcenter.ms/users/ejadh-raqeb/apps/ignite/distribution_groups/everyone

**Comment by maqeelqureshi** [comment]
> @vantuan88291 Thanks for your concern! Can you let us know how you are bundling your app? Also is there a reason for not choosing AAB or are you just producing dev APKs for now?



> We'll definitely look into this, @vantuan88291! I don't want to remove the `expo` core library from Ignite, as Expo libraries are super important to our workflow, but I'm sure there are opportunities to reduce the apk file size quite a bit.

Is there any package that can be removed if one doesn't want to support expo and web platforms?

**Comment by maqeelqureshi** [comment]
> We'll definitely look into this, @vantuan88291! I don't want to remove the `expo` core library from Ignite, as Expo libraries are super important to our workflow, but I'm sure there are opportunities to reduce the apk file size quite a bit.

Is there any package that can be removed if one doesn't want to support expo and web platforms?

**Comment by omarabualhija** [comment]
I found it may be help u :
https://github.com/infinitered/ignite/discussions/2352

**Comment by omarabualhija** [comment]
I found this, it may help if you don't use expo lib. :
https://github.com/infinitered/ignite/discussions/2352

**Comment by frankcalise** [comment]
In the latest version of Ignite to be released in the near future, the demo app in release APK mode is roughly 29mb without any extra work proguard etc.

**Comment by frankcalise** [comment]
In Ignite v9, the Android APK is 29.6MB and 26.7MB (using Proguard). And that's without any dependency removal (which there are quite a few and depending on your use case you won't need all of them).

Going to close this out, as that is half / third of the size of the original issue.
