### ISSUE TITLE
Text props improvement

### ISSUE THREAD

**Issue by ryskin** [infinitered/ignite#2316]
I think need to make additional props (to avoid using styles) for underline, strike, and italic (textDecorationLine), that's basic for text like bold.

**Comment by yulolimum** [comment]
@ryskin 

Thanks for the suggestion!

What we're trying to achieve with the components is provide the developers with a good "starting point" for customization. Most components have just enough props (external customization) that it would be enough for most use-cases. What we **_don't_** want to do is provide "too much"  that components become hard to maintain. So, in other words, we have the basics and we have a way that you can extend that for your needs.

So, the difference between having a "size" prop and a "decoration" prop is that "size" is used on _most_ apps, but something like a strike-through is rarely used.

You can use the `presets` [block](https://github.com/infinitered/ignite/blob/master/boilerplate/app/components/Text.tsx#L95-L107) to add more predefined style groups to your style. You can define a `lineThrough` preset and add the necessary styles. You can do the same for `italic`, but note that the default fonts [don't include italic glyphs](https://github.com/infinitered/ignite/blob/master/boilerplate/app/theme/typography.ts#L13-L19) (so you'll need to add that).

**Comment by ryskin** [comment]
I'm agree with you but this small thing will make this component complete, underline and italic for example is often using by designers and in any design tool it will be visible.

This will not overload component, even in editor I write this message I always see icon **bold** and _italic _

**Comment by jamonholmgren** [comment]
@ryskin We've been noticing your activity internally here at Infinite Red and rest assured it's very appreciated! You've had some great ideas and contributions.

**Comment by ryskin** [comment]
@ryskin I always take ideas from Ignite and always wanted much more examples in demos and the latest release I think is the most significant. Also, I would like later to try to contribute with a code. I have some ideas, I remember what was hard for me some time ago, especially with MST, because the community is not big as I wish.
