### ISSUE TITLE
Add const assertion to colour palette.

### ISSUE THREAD

**Issue by RhyG** [infinitered/ignite#2327]
G'day, asked [a question](https://github.com/infinitered/ignite/discussions/2326) where Robin suggested raising an issue with the change.

This fairly minor suggestion is to add a const assertion to the [colour palette object](https://github.com/infinitered/ignite/blob/master/boilerplate/app/theme/colors.ts#L3):
```typescript
const palette = {
  neutral100: '#FFFFFF',
  neutral200: '#F4F2F1',
 ...
} as const;
```

This has the benefit of stricter types:
![strict](https://user-images.githubusercontent.com/47733004/205520129-f7c0c325-9220-4f27-99f0-21f5e63152f0.png)
instead of
![loose](https://user-images.githubusercontent.com/47733004/205520145-90f5d536-00d9-484d-9b00-b17713cd5afe.png)

After using/ripping off Ignite in different ways I have found it also gives better autocomplete in some cases, particularly when combined with more complicated theming.

Keen on your thoughts, love the repo and podcast. :)

**Comment by jamonholmgren** [comment]
Do it! ❤️ Thanks for using Ignite!
