### ISSUE TITLE
Android build fails after upgrading to Gradle 7.3.1

### ISSUE THREAD

**Issue by BitWizJason** [infinitered/ignite#2329]
### Describe the bug

I created a clean new Ignite project using the CLI. Everything built and ran fine. After opening it up in Android Studio, Android Studio recommend updating the project to the latest Gradle version. I preceded to allow it to update Gradel. The following files and lines in the project where changed:

```
andoird/build.gradle

-       classpath("com.android.tools.build:gradle:7.1.1")
+       classpath('com.android.tools.build:gradle:7.3.1')
```

```
android/gradle/wrapper/gradle-wrapper.properties

-distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
```

This then led to the following build errors:

```
> Task :expo-modules-core:configureCMakeDebug[arm64-v8a] FAILED
C/C++: C:\[ommitted]\node_modules\expo-modules-core\android\CMakeLists.txt debug|arm64-v8a : com.google.prefab.api.NoMatchin
gLibraryException: No compatible library found for //fbjni/fbjni. Rejected the following libraries:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
```
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-modules-core:configureCMakeDebug[arm64-v8a]'.
> [CXX1212] C:\[ommitted]\node_modules\expo-modules-core\android\CMakeLists.txt debug|arm64-v8a : User is using a static STL
 but library requires a shared STL [//fbjni/fbjni]
```

### Ignite version

8.4.2

### Additional info

System
  platform           win32                                                                 
  arch               x64           
  cpu                12 cores       AMD Ryzen 5 1600 Six-Core Processor            
  directory          [ommitted]

JavaScript
  node               18.12.1      C:\Program Files\nodejs\node.EXE
  npm                8.19.2       C:\Program Files\nodejs\npm.CMD
  yarn               -            not installed
  pnpm               -            not installed
  expo               46.0.17      managed

Ignite
  ignite-cli         8.4.2          C:\[ommitted]\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build          C:\[ommitted]\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               11.0.17      C:\Program Files\Eclipse Adoptium\jdk-11.0.17.8-hotspot\bin\java.EXE
  android home       -            C:\[ommitted]\AppData\Local\Android\Sdk

Tools
  git                git version 2.27.0.windows.1   C:\Program Files\Git\cmd\git.EXE

**Comment by frankcalise** [comment]
@BitWizJason thanks for the report, but this issue is likely more upstream. Please see this issue over at the react-native repo, it's likely we stick to AGP 7.3.1 for a bit longer.

https://github.com/facebook/react-native/issues/35592
