### ISSUE TITLE
Support Version Locking for React Native

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#233]
Turns out we can pass a command line option into `react-native init --version 0.27.0`

https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L53

We should consider this for our generator, so we don't get bit like we did today with upstream bugs on React Native 0.29.

**Comment by GantMan** [comment]
we should lock to 0.28 today, this is a great find.

**Comment by GantMan** [comment]
completed via #236
