### ISSUE TITLE
ReferenceError: __DEV__ is not defined (when trying to run new ignite app on iOS)

### ISSUE THREAD

**Issue by finnigantime** [infinitered/ignite#234]
See repro image here:
<img width="1306" alt="screen shot 2016-07-06 at 1 33 09 pm" src="https://cloud.githubusercontent.com/assets/1305608/16633506/8b408280-437e-11e6-87b6-024105246942.png">

### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

**Comment by GantMan** [comment]
What version of node are you running?  That looks like an "older version of node" error.

Also, we have a small bug we're fixing right now, because 0.29 just came out and broke some things.  So we're fixing away!

**Comment by finnigantime** [comment]
Thanks for the quick response! I was on Node v2.x, and upgrading to v4.x got past that issue for me (I'm now on v4.4.5). You may want to consider adding a node version validate that requirement.

I now can launch my app in the simulator but get this error:
<img width="518" alt="screen shot 2016-07-06 at 1 48 24 pm" src="https://cloud.githubusercontent.com/assets/1305608/16633941/7b85c42a-4380-11e6-85f6-71f6d1aec11b.png">
![screen shot 2016-07-06 at 1 48 28 pm](https://cloud.githubusercontent.com/assets/1305608/16633943/7ef34a10-4380-11e6-937d-6a15e5d4daf5.png)

I tried upgrading to the newest Node (v6.3.0) but still got this error.

**Comment by GantMan** [comment]
We'll definitely make a note on the node requirement.  I plan on adding something like that this week.

As for that new error, can you please try removing your app and starting over?  If this persists, I will check into it deeper.

**Comment by finnigantime** [comment]
Thanks @GantMan. I still hit this error when creating an app from scratch (now on Node 6). Note that I installed ignite via `npm install -g react-native-ignite` and not from sources. I tried reinstalling `react-native-cli` and `react-native-ignite` after upgrading to Node v6 but I'm still getting this error: 
![screen shot 2016-07-06 at 2 49 30 pm](https://cloud.githubusercontent.com/assets/1305608/16635802/e5b04c1e-4388-11e6-95ac-54ad9715460d.png)

Let me know if there is something else I should try from my side.

**Comment by GantMan** [comment]
@finnigantime - can you try with the latest version?

**Comment by josja** [comment]
Might have the same or related issue, I started with Ignite v1.3.0 yesterday on my default machine for building RN apps, when I run 'react-native run-ios' the build succeeds, shows the title loading screen in simulator but then:

![screen shot 2016-07-09 at 11 19 08](https://cloud.githubusercontent.com/assets/5016263/16707242/a770acdc-45c7-11e6-92d2-28076a8e278a.png)

When I run the packager it dies:
```
$ npm start

> SnoozeDeluxe@0.0.1 start /Users/josja/Projects/ignite/SnoozeDeluxe
> node node_modules/react-native/local-cli/cli.js start

 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/josja/.nvm/versions/node/v6.2.0/bin/node" "/Users/josja/.nvm/versions/node/v6.2.0/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! SnoozeDeluxe@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
```

Let me know how I can help.

**Comment by GantMan** [comment]
@finnigantime  - Please re-open if your problem persists passed version 1.3.x

**Comment by finnigantime** [comment]
Confirmed fixed - thanks! Sorry it took my so long to reply.
