### ISSUE TITLE
Add ignite version used to ignite project in initial git commit

### ISSUE THREAD

**Issue by joshuayoes** [infinitered/ignite#2345]
# Issue
It can be useful to know with what version of `ignite-cli` a project was started with. However, it is tricky to leave this information because Ignite does not currently leave a footprint in the project to store config values.

# Solution
Most projects are started opt into initializing a git repository. We can change the current `Initial commit` message on first commit to `Initial commit using Ignite <major>.<minor>.<patch>`. This preserves the value for historical purposes, but doesn't leave a footprint or risk getting tampered with later.

**Comment by frankcalise** [comment]
I like this compromise as a starting point, nice idea!

**Comment by LinFeiLong** [comment]
<img width="235" alt="Screenshot 2022-12-27 at 11 12 50" src="https://user-images.githubusercontent.com/6100043/209651146-95aed521-a01c-4d0b-9bd1-2b089f864505.png">

@joshuayoes are you talking about that ?

**Comment by frankcalise** [comment]
Hah, we already have this set up :)

**Comment by joshuayoes** [comment]
Great minds think alike 😆
