### ISSUE TITLE
Ignite splash screen logo persist on iOS.

### ISSUE THREAD

**Issue by abumubarak-dev** [infinitered/ignite#2347]
### Describe the bug

After generating the splash screen logo via the ignite cli. I can still see the ignite icon a few seconds before the new splash screen logo appears.

### Ignite version

latest

### Additional info

System
  platform           darwin
  arch               x64
  cpu                8 cores      Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  directory          Abode        /Users/abu_mubarak/dev/Abode

JavaScript (and globally-installed packages)
  node               19.3.0       /usr/local/bin/node
  npm                9.2.0        /usr/local/bin/npm
    eas-cli          3.1.0
    expo-cli         6.0.8
    ignite-cli       8.4.4
    npm              9.2.0
  yarn               -            not installed
  pnpm               -            not installed
  expo               46.0.17      managed

Ignite
  ignite-cli         8.4.4        /usr/local/bin/ignite
  ignite src         build        /usr/local/lib/node_modules/ignite-cli/build

Android
  java               11.0.17      /usr/bin/java
  android home       -            /Users/abu_mubarak/Library/Android/sdk

iOS
  xcode              14.0.1
  cocoapods          1.11.3       /usr/local/bin/pod

Tools
  git                git version 2.37.0 (Apple Git-136)   /usr/bin/git

**Comment by NikSmith** [comment]
same problem +1

**Comment by abumubarak-dev** [comment]
restart phone.

> same problem +1
> 
> UPD: I solved it
> 
> Just clear cache, rebuild project and restart phone.

Restarting the simulator works

**Comment by maqeelqureshi** [comment]
Splash screen updated after clean and restarting emulator but app icon is not updated.

**Comment by abumubarak-dev** [comment]
Try to Erase all content on the simulator/emulator and run the app again.
<img width="311" alt="Screenshot 2023-02-07 at 10 55 37" src="https://user-images.githubusercontent.com/47022889/217211969-1afaa794-7b00-4de1-8517-5eab6da8ae0f.png">

**Comment by mparodi** [comment]
after generating the splash screen, if I rebuild the project with `npx expo run:ios` the splash screen of ignite persists even after erasing all content of the simulator, reinstalling the app. Running `yarn run expo:ios` (that executes `expo start --ios` works but its just temporally).
