### ISSUE TITLE
What"s the puropose of index.ts inside icons folder?

### ISSUE THREAD

**Issue by MenaiAla** [infinitered/ignite#2349]
### Describe the bug

I just started checking out the content of each folder to get an overview of the role of each one. However, I got confused when I found [index.ts](https://github.com/infinitered/ignite/blob/master/boilerplate/assets/icons/index.ts) with 0 lines.

Would you explain the purpose of this file?

Thank you

### Ignite version

@latest

**Comment by frankcalise** [comment]
No reason, it's pending removal in a future fix.
