### ISSUE TITLE
What"s the purpose of index.ts inside icons folder?

### ISSUE THREAD

**Issue by MenaiAla** [infinitered/ignite#2350]
### Describe the bug

I just started checking out the content of each folder to get an overview of the role of each one. However, I got confused when I found [index.ts](https://github.com/infinitered/ignite/blob/master/boilerplate/assets/icons/index.ts) with 0 lines.

Would you explain the purpose of this file?

Thank you

### Ignite version

@latest

### Additional info

System
  platform           linux                                                     
  arch               x64                                                       
  cpu                8 cores          Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz 
  directory          ReactNativeApp   /home/alaeddine/Apps/ReactNativeApp

**Comment by frankcalise** [comment]
Closing due to duplicate #2349
