### ISSUE TITLE
[CXX1405] error when building with cmake using .../node_modules/expo-modules-core/android/CMakeLists.txt: Build command failed.

### ISSUE THREAD

**Issue by SahandMahdavi** [infinitered/ignite#2355]
### Describe the bug

I have the issue 
[CXX1405] error when building with cmake using .../node_modules/expo-modules-core/android/CMakeLists.txt: Build command failed.

On running android and can't do anything
The os is OSX M2

### Ignite version
```
8.4.6

### Additional info

System
  platform           darwin                               
  arch               arm64                                
  cpu                8 cores         Apple M2             
  directory          sahandmahdavi   /Users/sahandmahdavi 

JavaScript (and globally-installed packages)
  node               19.4.0       /opt/homebrew/bin/node 
  npm                9.2.0        /opt/homebrew/bin/npm  
    detox-cli        20.0.0                              
    npm              9.2.0                               
    yarn             1.22.19                             
  yarn               1.22.19      /opt/homebrew/bin/yarn 
    orval            6.11.0                              
  pnpm               -            not installed          
  expo               -            not installed          

Ignite
  ignite-cli         8.4.5        /Users/sahandmahdavi/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/sahandmahdavi/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               1.8.0_351    /usr/bin/java                            
  android home       -            /Users/sahandmahdavi/Library/Android/sdk 

iOS
  xcode              14.2       
  cocoapods          1.11.3       /Users/sahandmahdavi/.gem/bin/pod 

Tools
  git                git version 2.39.0   /opt/homebrew/bin/git 
```

**Comment by frankcalise** [comment]
Hi @SahandMahdavi - can you give a little more background on your problem? You're running Android, is this through Expo or not?

Also does iOS work ok for you?

What version of react-native and Expo are you targeting?

There are several threads related to Android set up and this error, perhaps some of these could point you in the right direction:
- https://github.com/expo/expo/issues/18412
- https://github.com/facebook/react-native/issues/35210

**Comment by SahandMahdavi** [comment]
@frankcalise 
No, I'm not building Android with the expo.
Yes for iOS it works perfectly fine.
**RN version: 0.69.7**
**Expo version: ~46.0.17**

**Comment by SahandMahdavi** [comment]
@frankcalise 

The above problem is fixed 
Now I'm facing an issue that I can't fix:

> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     Your current JDK is located in  /opt/hostedtoolcache/jdk/8.0.3[62](https://github.com/letsact/letsact-app/actions/runs/4019522035/jobs/6906467579#step:8:63)/x64/jre
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.



and



A problem occurred configuring project ':app'.
> 'kotlin-android' plugin requires one of the Android Gradle plugins.
  Please apply one of the following plugins to ':app' project:
  - com.android.application
  	- com.android.library
  	- com.android.dynamic-feature
  	- com.android.test
  	- com.android.instantapp
  	- com.android.feature

**Comment by frankcalise** [comment]
@SahandMahdavi is your machine set up for Android development? Follow the React Native CLI directions for Android here: https://reactnative.dev/docs/environment-setup

**Comment by SahandMahdavi** [comment]
@frankcalise Yes, it is set up 
I followed the steps in **reactnative.dev**

**Comment by frankcalise** [comment]
Yes but the Java installation you have is incorrect as the error you posted mentioned.

```
Failed to apply plugin 'com.android.internal.application'.
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
Your current JDK is located in /opt/hostedtoolcache/jdk/8.0.3[62](https://github.com/letsact/letsact-app/actions/runs/4019522035/jobs/6906467579#step:8:63)/x64/jre
You can try some of the following options:
- changing the IDE settings.
- changing the JAVA_HOME environment variable.
- changing org.gradle.java.home in gradle.properties.
```

From your `npx ignite-cli doctor`:
```
Android
  java               1.8.0_351    /usr/bin/java                            <--------------------- this is incorrect
  android home       -            /Users/sahandmahdavi/Library/Android/sdk 
```

Please revisit the setup documentation and look for the `Java Development Kit` section

**Comment by SahandMahdavi** [comment]
@frankcalise 
Fixed, thanks

**Comment by frankcalise** [comment]
You're welcome!
