### ISSUE TITLE
Certificate for <jfrog-prod-usw2-shared-oregon-main.s3.amazonaws.com> doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]

### ISSUE THREAD

**Issue by SahandMahdavi** [infinitered/ignite#2358]
### Describe the bug

Super strange error on android runtime 

Certificate for <jfrog-prod-usw2-shared-oregon-main.s3.amazonaws.com> doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]

### Ignite version

8.4.6

### Additional info

System
  platform           darwin                               
  arch               arm64                                
  cpu                8 cores         Apple M2             
  directory          sahandmahdavi   /Users/sahandmahdavi 

JavaScript (and globally-installed packages)
  node               19.4.0       /opt/homebrew/bin/node 
  npm                9.2.0        /opt/homebrew/bin/npm  
    detox-cli        20.0.0                              
    npm              9.2.0                               
    yarn             1.22.19                             
  yarn               1.22.19      /opt/homebrew/bin/yarn 
    ios-deploy       1.12.1                              
    orval            6.11.0                              
  pnpm               -            not installed          
  expo               -            not installed          

Ignite
  ignite-cli         8.4.5        /Users/sahandmahdavi/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/sahandmahdavi/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               1.8.0_351    /usr/bin/java                            
  android home       -            /Users/sahandmahdavi/Library/Android/sdk 

iOS
  xcode              14.2       
  cocoapods          1.11.3       /Users/sahandmahdavi/.gem/bin/pod 

Tools
  git                git version 2.39.0   /opt/homebrew/bin/git

**Comment by frankcalise** [comment]
@SahandMahdavi this is probably particular to your machine set up - Ignite doesn't do anything with AWS or S3

**Comment by frankcalise** [comment]
Is this in any way related to your other Java issue @SahandMahdavi ?

**Comment by frankcalise** [comment]
I'm going to close this due to stale activity and it probably not being related to Ignite (and it seems like you got your build working in another thread, #2355. Should there still be an issue, please feel free to reopen

**Comment by muhammadshaheer-er** [comment]
@SahandMahdavi know this is closed but how did you manage to fix this issue? where its moaning about s3.amazon?

**Comment by SahandMahdavi** [comment]
@muhammadshaheer-er 

It's a pity that setting up the AWS but can help you
[Jfrog](https://jfrog.com/knowledge-base/artifactory-aws-s3-connectivity-and-troubleshooting-steps/)
Also, there are a lot of articles written and published regarding setting up the AWS

**Comment by SahandMahdavi** [comment]
@muhammadshaheer-er 

It's a pity that setting up the AWS can help you
[Jfrog](https://jfrog.com/knowledge-base/artifactory-aws-s3-connectivity-and-troubleshooting-steps/)
Also, there are a lot of articles written and published regarding setting up the AWS

**Comment by SahandMahdavi** [comment]
@muhammadshaheer-er 

It's a pity that setting up the AWS can help you
[Jfrog](https://jfrog.com/knowledge-base/artifactory-aws-s3-connectivity-and-troubleshooting-steps/)
Also, there are a lot of articles written and published regarding setting up the AWS

**Comment by SahandMahdavi** [comment]
@LiJoeAllen Yes

**Comment by bradherman** [comment]
> @LiJoeAllen Yes

Any information on how you fixed it?

**Comment by SahandMahdavi** [comment]
I didn't use this AWS thing in the project,
I just deleted the dependencies, but if you need them there are some articles mentioned in the first comments please take a look at them.
You need a provisioning profile and cert for this.
@LiJoeAllen @bradherman
