### ISSUE TITLE
7 critical vulnerability when running yarn audit

### ISSUE THREAD

**Issue by aymane-missouri-nw** [infinitered/ignite#2371]
when i run a `yarn audit` command to a new ignite generated project , I found 7 critical vulnerabilites, i think removing them it's a good enhancement for the boilerplate.

![image](https://user-images.githubusercontent.com/104450977/217232729-aaf20d3d-829f-4186-a170-5abb771c3535.png)

**Comment by aymane-missouri-nw** [comment]
I will create a PR for this issue

**Comment by flexbox** [comment]
with 8.8.0 we bumped to 
> Expo SDK 48, react-native 0.71.7 

So I believe some errors were fixed. Feel free to re open if it's not the case 😅 

more informations on https://github.com/infinitered/ignite/releases
