### ISSUE TITLE
Getting Started with Ruby 3.2.0 & Yarn 3.4.1

### ISSUE THREAD

**Issue by morganick** [infinitered/ignite#2374]
### Describe the bug

I have the latest Ruby 3.2.0 installed via brew and Yarn 3.4.1. I have `corepack` enabled.

I started with your README.md and ran the following:
```
npx ignite-cli@latest new SampleApp
```
I accepted all of the defaults including installing dependencies. The first issue you'll run across is not having Cocoapods installed. This is a prerequisite even though the lines above state:

> For [Expo-powered React Native apps](https://expo.io/), no prerequisites are necessary ([why choose Expo?](https://medium.com/@adhithiravi/building-react-native-apps-expo-or-not-d49770d1f5b8))

Simply running `brew install cocoapods` is enough to get you past this part.

Now, we'll try to install the packages again with `yarn` only to make it into the `postInstall` script for running `pod-install`. This will error out because there is not a `node_modules` directory when using Yarn 3.4.1. The `node_modules` directory is used for pathing to install additional cocoapods from the `ios/Podfile`:

```ruby
require File.join(File.dirname(`cd #{pod_folder} && node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`cd #{pod_folder} && node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`cd #{pod_folder} && node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
```

 If you add the following to the `.yarnrc.yml` file you'll be able to move forward once again:

```
nodeLinker: node-modules
```

Now that you have cocoapods installed and can properly resolve the additional pods, you'll once again be greeted with an error because Ruby 3.2.0 removed `File.exists?`.

There are two packages that need to be updated in order to finally finish the pod installation `react-native-gesture-handler` to ~2.9.0 (https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.9.0) and `react-native-animated` to ~2.14.0 series (https://github.com/software-mansion/react-native-reanimated/releases/tag/2.14.0).

After manually updating these packages, the app will build and compile via `expo:start`. Then it will present you with an error that Expo and the packages above are now out of sync.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/151139/217654670-005aa32b-9ab3-44f3-b3d2-b7c570cdaa22.png">

You can track the issue with Expo here: https://github.com/expo/expo/issues/20707

### Ignite version

8.5.1

### Additional info

This command appears to not support Yarn 2.x and above.

```
System
  platform           darwin
  arch               arm64
  cpu                10 cores     Apple M1 Max
  directory          SampleApp    /Users/morganick/dev/playground/SampleApp

/Users/morganick/.npm/_npx/e31027f3785124a8/node_modules/gluegun/build/index.js:15
    throw up;
    ^
Usage Error: The 'yarn global' commands have been removed in 2.x - consider using 'yarn dlx' or a third-party plugin instead

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...

(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.14.0
```

**Comment by frankcalise** [comment]
@morganick hey! I'm trying to find the related issue on the main react-native repo for you, however from meetings with the RN core team I can say that they mentioned there are specific problems with ruby 3.2.0. I'd downgrade to a more compatible version for now.

I'll try and find out where this was mentioned.

**Comment by morganick** [comment]
@frankcalise this works on `npx ignite-cli@latest new PizzaApp`
