### ISSUE TITLE
Why remove child folder in screens folder?

### ISSUE THREAD

**Issue by vantuan88291** [infinitered/ignite#2375]
I think the folder that contain a screen file is importance, when i want to add new component that just related to this screen, i have to put it in the same folder. So please put it back when generate new screen

**Comment by pqv2210** [comment]
@vantuan88291 I mentioned this in my QnA section. plz check it :))
https://github.com/infinitered/ignite/discussions/2319

**Comment by frankcalise** [comment]
Closing this, see discussion mentioned by @pqv2210 above.
