### ISSUE TITLE
[Gen | CLI] - Consider simplifying publishing with `xyz`

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#239]
XYZ seems nice, and would help with the long release process we currently have.
Current process: https://github.com/infinitered/ignite/releases/tag/1.3.0
XYZ: https://github.com/davidchambers/xyz

**Comment by skellock** [comment]
We're going with lerna now that this is a monorepo.

I still use xyz for my small projects.  I like it.  It's no frills.  :)
