### ISSUE TITLE
Upgrade HttpClient to a module

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#24]
HttpClient is an opinionated wrapper around `fetch`.  

I'm going to move this to its own repo/npm module.   There's more I'd like to do with and lots more tests.

Because it has usefulness outside this repo, we're going to set it free.

**Comment by markrickert** [comment]
![if-you-love-something](https://cloud.githubusercontent.com/assets/139261/14114578/746301f4-f5a5-11e5-830a-897303f9582a.jpg)

**Comment by jamonholmgren** [comment]
Oh noes, not another npm module dependency, the world will end

**Comment by skellock** [comment]
Came up with this:   https://github.com/skellock/apisauce

Next step:  bring in a PR to show how it works.  See if y'all like it enough to include.

**Comment by skellock** [comment]
Status update.

There's an incoming patch for React Native which will bestow `XMLHttpRequest` the power to user `ontimeout` and `onerror`.  I'm hoping for 0.24.  They're just doing the rebase dance right now.

Once that's in master.  I'd be comfortable declaring `apisauce` ready for ignite-worthy.  

Tracking here:  https://github.com/skellock/apisauce/issues/7

**Comment by skellock** [comment]
Ok, that PR just landed in master.  I'll get to work on this integration.

**Comment by skellock** [comment]
https://github.com/infinitered/ignite/pull/62

The PR for the `ontimeout` and `onerror` will be arriving in 0.25.  I'll circle back when 0.25 lands and make sure everything is working as you'd expect.

**Comment by GantMan** [comment]
YES!  Looking great!
