### ISSUE TITLE
[GEN | CLI] - Detect version updates

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#240]
It just hit me that people on old versions of ignite will be like "WHAAAAAAAT?"

We should build it in now that if your'e running X and Y comes out, it should give a friendly message.  ASCII art is a must!

**Comment by GantMan** [comment]
@fvonhoven  -  @siakaramalegos 

Good low hanging fruit.

**Comment by pradel** [comment]
@GantMan What do you think about [update-notifier](https://github.com/yeoman/update-notifier) for that, yeoman and ava are using it.

**Comment by GantMan** [comment]
That looks ideal.  Good find.
