### ISSUE TITLE
Request upgrade to RN 0.71.6 due to XCode 14.3 iOS versioning error 

### ISSUE THREAD

**Issue by fzhang13** [infinitered/ignite#2418]
### Describe the bug

Currently in XCode Version 14.3 (14E222b). When running `npm run ios `or `npx react-native run ios` the build fails due to this error which has been patched in [RN 0.71.6](https://github.com/facebook/react-native/issues/36635)

### Ignite version

v8.6.1

### Additional info

System
  platform           darwin                                                             
  arch               x64                                                                
  cpu                12 cores     Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz              

JavaScript (and globally-installed packages)
  node               14.19.0      
  npm                6.14.16      
    corepack         0.10.0                                                              
    npm              6.14.16                                                             
    serverless       2.72.3                                                              
  yarn               1.22.19      /usr/local/bin/yarn                                    
  pnpm               -            not installed                                          
  expo               -            not installed                                          

Ignite
  ignite-cli         8.6.1                  
  ignite src         build       

Android
  java               1.8.0_361    /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              14.3       
  cocoapods          1.12.0       /usr/local/bin/pod 

Tools
  git                git version 2.40.0   /usr/local/bin/git

**Comment by frankcalise** [comment]
Hi @fzhang13 you can try either of these two branches, but these fixes should be coming when these get merged!

https://github.com/infinitered/ignite/pull/2377 
or
https://github.com/infinitered/ignite/pull/2423
