### ISSUE TITLE
Initial app fails after generation

### ISSUE THREAD

**Issue by josja** [infinitered/ignite#242]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

I started with Ignite v1.3.0 yesterday on my default machine for building RN apps, when I run 'react-native run-ios' the build succeeds, shows the title loading screen in simulator but then:

![screen shot 2016-07-09 at 11 19 08](https://cloud.githubusercontent.com/assets/5016263/16707242/a770acdc-45c7-11e6-92d2-28076a8e278a.png)

When I run the packager it dies:
```
$ npm start

> SnoozeDeluxe@0.0.1 start /Users/josja/Projects/ignite/SnoozeDeluxe
> node node_modules/react-native/local-cli/cli.js start

 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/josja/.nvm/versions/node/v6.2.0/bin/node" "/Users/josja/.nvm/versions/node/v6.2.0/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! SnoozeDeluxe@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
```

Npm list looks clean & healthy.
react@15.2.1
react-native@0.28.0

Let me know how I can help.

**Comment by josja** [comment]
OMG, one of my packagers was running in the background (locking port 8081)

**Comment by GantMan** [comment]
Hahaha, that sneaky port grab!    I wish they had given you a better error message.

Enjoy Ignite!
