### ISSUE TITLE
Unable to run project with ignite new MyProject

### ISSUE THREAD

**Issue by dili91** [infinitered/ignite#244]
Hi, when running a test project I get this error: 

/Users/andreadilisio/Documents/personal/projects/IgniteTest/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/Users/andreadilisio/Documents/personal/projects/IgniteTest/node_modules/graceful-fs/polyfills.js:18:9)
    at _runIOS (/Users/andreadilisio/Documents/personal/projects/IgniteTest/node_modules/react-native/local-cli/runIOS/runIOS.js:51:9)
    at /Users/andreadilisio/Documents/personal/projects/IgniteTest/node_modules/react-native/local-cli/runIOS/runIOS.js:24:1
    at tryCallTwo (/Users/andreadilisio/Documents/personal/projects/IgniteTest/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/andreadilisio/Documents/personal/projects/IgniteTest/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/andreadilisio/Documents/personal/projects/IgniteTest/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/andreadilisio/Documents/personal/projects/IgniteTest/node_modules/react-native/local-cli/runIOS/runIOS.js:23:8)
    at Object.run (/Users/andreadilisio/Documents/personal/projects/IgniteTest/node_modules/react-native/local-cli/cliEntry.js:91:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:73:7)

node : 6.2.2
react native cli: 0.1.7

Any suggestion ?

**Comment by GantMan** [comment]
please update your CLI, `npm i -g react-native-cli`

Sorry, our next version will check this for you.

**Comment by dili91** [comment]
thank you! @GantMan

**Comment by folivi** [comment]
Does it work for you?
Cause it doesn't for me

**Comment by GantMan** [comment]
@folivi - screen shots and errors please.

**Comment by ermaliii** [comment]
This is the error I get...
![error](https://cloud.githubusercontent.com/assets/2120975/16938724/e303ade8-4d48-11e6-9066-d53c6f5f02d4.png)

**Comment by GantMan** [comment]
@ermaliii  - I'd say your version of yeoman is out of date.   Please update yeoman and verify this is fixed.

**Comment by folivi** [comment]
Hi all,
this is the issue I used to see.
But now that I moved to node 6.0 everything is running smooth
cheers

**Comment by GantMan** [comment]
Thanks!  we might have to build in warnings for people running older versions of node, just to cover these cases.  I'll mark this as an easy task, and see if someone picks that up.

**Comment by kamikaz1k** [comment]
Hello, I am also getting the error @dili91 got.
node: v6.3.1 
react-native-cli: 1.0.0
yo: 1.8.4

Trace:
```
kamikaz1_k@MacBook-Air ~/w/E/testApp> react-native run-ios
/Users/kamikaz1_k/workspace/Experiments/testApp/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/Users/kamikaz1_k/workspace/Experiments/testApp/node_modules/graceful-fs/polyfills.js:18:9)
    at _runIOS (runIOS.js:50:11)
    at runIOS.js:24:5
    at tryCallTwo (/Users/kamikaz1_k/workspace/Experiments/testApp/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/kamikaz1_k/workspace/Experiments/testApp/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/kamikaz1_k/workspace/Experiments/testApp/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (cliEntry.js:95:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
```

**Comment by ermaliii** [comment]
@GantMan I did update yeoman and things are working fine now. Thanks for your help!

**Comment by GantMan** [comment]
Do you know what version of yeoman you had?   The issue here is that they moved to a promised based system for UI interaction, and we used that.  Expecting that yeoman would be backwards compatable, but they obviously are not.

I'd like to build in a check, but I need version numbers

**Comment by Alex4S** [comment]
@kamikaz1k +1

**Comment by GantMan** [comment]
@Alex4S - That's odd.  Version of npm and ignite?   Run `ignite doctor`

**Comment by trestrantham** [comment]
Having the same issue. Here's `ignite doctor`:

```
Computer
  Platform: darwin

Ignite
  Version: 1.4.1

Node
  Version: v6.3.1

NPM
  Version: 3.10.3

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.30.0
```

**Comment by GantMan** [comment]
@trestrantham - I'm at a loss on what could be different between our machines.  I just cleared off everything and did a fresh grab of all to get the same state:
```
Computer
  Platform: darwin

Ignite
  Version: 1.4.1
  Path: /Users/gantman/.nvm/versions/node/v6.3.1/bin/ignite

Node
  Version: v6.3.1
  Path: /Users/gantman/.nvm/versions/node/v6.3.1/bin/node

NPM
  Version: 3.10.3
  Path: /Users/gantman/.nvm/versions/node/v6.3.1/bin/npm

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.30.0
```

Everything worked fine for me.  If you'd like to do a screen share, please hit us up in the gitter channel:  https://gitter.im/infinitered/ignite
From there we can pair in real-time.

**Comment by trestrantham** [comment]
Weird. For additional context, I'm on macOS Sierra and using [`asdf`](https://github.com/asdf-vm/asdf-nodejs) version manager. I probably won't be able to screen share as I'm moving this week, but I'll report back with anything else I can find.

**Comment by GantMan** [comment]
I'm on nvm, as you can see from above.  I'd be eager to hear if you can figure out why your machine is not responding.

**Comment by trestrantham** [comment]
I was able to get this to run by switching from Xcode 8.0 beta 3 to Xcode 7.3.1. I'm downloading 8.0 beta 4 now to see if it's an issue there as well. (I'm working with SiriKit hence the beta builds.)

**Comment by GantMan** [comment]
ahhhhh.   Gotcha.  There might be a ticket on RN that describes this.

**Comment by sumangurung** [comment]
I just installed ignite and got the error while trying to run `react-native run-ios`:
```
react-native run-ios

ENOENT: no such file or directory, uv_chdir
```

Here is the output from `ignite doctor`:
```
Computer
  Platform: darwin

Ignite
  Version: 1.8.0
  Path: /usr/local/bin/ignite

Node
  Version: v6.3.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.3
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.33.1
```
