### ISSUE TITLE
getRootStore() results in recursive error

### ISSUE THREAD

**Issue by samstorino** [infinitered/ignite#2440]
### Describe the bug

Hello,

When I access a store from another store through `getRootStore()`, and the other store's properties are used in anything that ultimately returns from the function I receive the following error on `RootStore` and all typing is lost:

```
Type 'RootStore' recursively references itself as a base type.ts(2310)
```

According to [this issue](https://github.com/infinitered/ignite/issues/1974) the above error was observed when using `withRootStore` and migrating to `getRootStore()` was intended to address it. The comment in the linked issue (which has a great example) is the exact behavior I'm observing. As a contrived example, I was able to replicate this behavior in the demo app generated via `ignitecli` by modifying the `EpisodeStore`'s `fetchEpisodes` function from:

```
async fetchEpisodes() {
  const response = await api.getEpisodes()
  if (response.kind === "ok") {
    store.setProp("episodes", response.episodes)
  } else {
    console.tron.error(`Error fetching episodes: ${JSON.stringify(response)}`, [])
  }
},
```

to

```
async fetchEpisodes() {
  const response = await api.getEpisodes()
  if (response.kind === "ok") {
    store.setProp("episodes", response.episodes)
  } else {
    console.tron.error(`Error fetching episodes: ${JSON.stringify(response)}`, [])
  }

  // HERE: this line causes error in `RootStore` and all typing is lost.
  return getRootStore(store).authenticationStore.authEmail
},
```

The act of simply returning something from the other store breaks the `RootStore`. Interestingly if I cast the store as follows or explicitly define the return type the error goes away:

```
const authStore = getRootStore(store).authenticationStore as Instance<AuthenticationStore>
return authStore.authEmail
```

A more specific example in my app: I have a `NoteStore` that fetches and stores an array of "notes", and a `UiStateStore` that has a property `selectedNoteId` which represents the note being edited. I'm attempting to use `selectedNoteId` from a view in the `NoteStore` to find the note currently being edited as follows:

```
.views((store) => ({
  get selectedNote() {
    return store.notes.find(n => n.id === getRootStore(store).uiStateStore.selectedNoteId)
  }
}))
```

The above getter breaks saying `uiStateStoreo` doesn't exist. However, if I explicitly set the return type the error goes away:

```
.views((store) => ({
  get selectedNote(): Note {
    return store.notes.find(n => n.id === getRootStore(store).uiStateStore.selectedNoteId)
  }
}))
```

I apologize ahead of time if this isn't directly related to `ignite`/`getRootStore()`'s implementation, I'm new to all of this. Is this behavior expected? Any insight would be very helpful!

### Ignite version

8.5.1

### Additional info

```
stor@Sams-MacBook-Air ThinkBack % npx ignite-cli doctor
System
  platform           darwin
  arch               arm64
  cpu                8 cores      Apple M1
  directory          ThinkBack    /Users/stor/Documents/workspace/Applications/ThinkBack

JavaScript (and globally-installed packages)
  node               19.8.1       /opt/homebrew/bin/node
  npm                9.5.1        /opt/homebrew/bin/npm
    eas-cli          3.8.1
    expo-cli         5.0.3
    npm              9.5.1
  yarn               1.22.19      /opt/homebrew/bin/yarn
    expo-cli         6.3.1
    react-devtools   4.22.1
  pnpm               -            not installed
  expo               48.0.9       managed

Ignite
  ignite-cli         8.5.1        /Users/stor/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/stor/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               -            not installed
  android home       -            undefined

iOS
  xcode              14.2
  cocoapods          1.11.3       /usr/local/bin/pod

Tools
  git                git version 2.40.0   /opt/homebrew/bin/git
npm notice
npm notice New minor version of npm available! 9.5.1 -> 9.6.6
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.6
npm notice Run npm install -g npm@9.6.6 to update!
npm notice
```

**Comment by frankcalise** [comment]
Thanks for the insight @coolsoftwaretyler
