### ISSUE TITLE
Add support for EAS build and Expo Dev client. 

### ISSUE THREAD

**Issue by i-mighty** [infinitered/ignite#2444]
The current expo setup fails on android for EAS builds. 
It is because @expo/metro-config is not used and support for eas build is not available. 
It will be a nice to have changes to the metro.config.js to support this. 
Happy to help with this.

**Comment by flexbox** [comment]
@i-mighty 
If your problem is solved, can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by i-mighty** [comment]
Sure, I thought I did. 
If extra hands are needed to work on that, I would be happy to help.
