### ISSUE TITLE
Ignite base app, View not scrollable in ios simulator

### ISSUE THREAD

**Issue by pratyushsharma** [infinitered/ignite#245]
Running on iphone 6 ios9.3 and iphone 4s ios9.3
Nothing below the screen is visible.
![image](https://cloud.githubusercontent.com/assets/4585580/16762334/b3a39600-4841-11e6-93cf-c2e01502b7ed.png)
node 6.30
npm 3.10.3
react-native-cli: 1.0.0
react-native: 0.28.0
ignite: 1.3.0

- Identify exactly what aspect your issue is about
  - [ x ] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

**Comment by skellock** [comment]
Hi @pratyushsharma .  Is this still a problem on our end?
