### ISSUE TITLE
[docs] Add documentation for the `assets` directory

### ISSUE THREAD

**Issue by frankcalise** [infinitered/ignite#2451]
The readme does not mention or explain the assets directory like it does with all the other root directories.

We should update this to be documented and explain how to properly use and organize assets.

**Comment by jvm-cognition** [comment]
Hi @frankcalise, first and foremost enjoying the React Native Radio 📻, Could I pick this issue up and have away?

**Comment by frankcalise** [comment]
@jvm-cognition Glad you liked the podcast!

Yes of course, we would certainly appreciate the contribution.
