### ISSUE TITLE
How to allows (optional) Expo modules when init project

### ISSUE THREAD

**Issue by tunm1228** [infinitered/ignite#2462]

**Comment by flexbox** [comment]
Hey @tunm1228 thanks for your contribution 🙌 

Can you elaborate more on
> How to allows (optional) Expo modules

From my perspective you can write

```
expo install wahtever
```

and it will works out of the box

**Comment by tunm1228** [comment]
> Hey @tunm1228 thanks for your contribution 🙌
> 
> Can you elaborate more on
> 
> > How to allows (optional) Expo modules
> 
> From my perspective you can write
> 
> ```
> expo install whatever
> ```
> 
> and it will works out of the box

I want to remove expo from project

**Comment by tunm1228** [comment]
I can't find the option to remove expo to the project!

**Comment by flexbox** [comment]
You can read this discussion! 😉 
https://github.com/infinitered/ignite/discussions/2352

**Comment by tunm1228** [comment]
> You can read this discussion! 😉 #2352

Thank you so much!
