### ISSUE TITLE
123 vulnerabilities (115 moderate, 5 high, 3 critical) found with fresh install

### ISSUE THREAD

**Issue by robfuncken** [infinitered/ignite#2472]
### Describe the bug

When I install a fresh project with the cli on node 18 I get 123 vulnerabilities.. 

Is this something to be addressed? 

### Ignite version

8.8.3

### Additional info

System
  platform           win32
  arch               x64
  cpu                12 cores            Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  directory          directory C:\Users\Rob\Documents\development\directory

**Comment by joshuayoes** [comment]
This isn't an issue 99% of the time. 

`npm` is extremely eager to report any possible vector of vulnerability in packages, even if there is no possibility that it will face your app.

I'd recommend reading this blog article by Dan Abramov to learn more about this: https://overreacted.io/npm-audit-broken-by-design/

If you want to go about resolving these in your applications, I'd recommend these articles:
- https://www.voitanos.io/blog/don-t-be-alarmed-by-vulnerabilities-after-running-npm-install/
- https://blog.ifs.com/2022/10/how-to-fix-security-vulnerabilities-with-npm/
