### ISSUE TITLE
add react-native-maps as a component

### ISSUE THREAD

**Issue by omarabualhija** [infinitered/ignite#2478]
Hey guys, I just want to request a feature that you may add to your boilerplate which we all know and love.  would kindly request a react-native-maps component that allows me to customize markers and other location helpers such as tracking a location and calculating distance to destination. As well as many other helper functions that can be used in different applications.

Thank you!

**Comment by frankcalise** [comment]
Hi @omarabualhija, thanks for your interest in Ignite! We only add dependencies that we consistently use in our client projects, unfortunately `react-native-maps` is not one of them for us. However, we'd be happy to get to an Ignite Cookbook Recipe and create a walkthrough on how to achieve this in an Ignite project.

If you haven't been to the Cookbook yet, [check it out here](https://ignitecookbook.com/)! Feel free to drop in a request over on that repo: https://github.com/infinitered/ignite-cookbook/issues
