### ISSUE TITLE
[Feature Request] Use react-native-extended-stylesheet for styling

### ISSUE THREAD

**Issue by justingosan** [infinitered/ignite#248]
https://github.com/vitalets/react-native-extended-stylesheet
From its docs: `Extend React Native stylesheets with media-queries, variables, themes, relative units, percents, math operations, scaling and other styling stuff.`

I think this library would be a great addition to an already awesome project generator :)

Thoughts?

**Comment by skellock** [comment]
Thanks for the link.  I'd never seen this before.

**Comment by sinewave440hz** [comment]
We are using Extended Style Sheets in our Ignited project right now. I just generated a couple of containers, all that was necessary was a couple of changed lines in style and container files. Wasn't hard at all, but this would enhance an already very handy generator!

**Comment by skellock** [comment]
In Ignite 2.0, plugins are a thing. They allow you to plugin to Ignite as if you were writing into core!
