### ISSUE TITLE
Storage related

### ISSUE THREAD

**Issue by 2Senn** [infinitered/ignite#2481]
Hey guys, any reason why you are using AsyncStorage as the standard instead of MMKV? I noticed that you mention in your cookbook that MMKV is the fastest so I was curious as to why you keep AsyncStorage in the starter boilerplate instead.

Thanks ^^

**Comment by frankcalise** [comment]
@2Senn All package decisions for our boilerplate really just come down to how comfortable we've felt with it on client projects before changing up Ignite. So sometimes it's preference and other times it just we don't have enough feedback from our team members to "make the switch" just yet.

In the case of MMKV it's the latter - but feel free to try it and report back your experience!
