### ISSUE TITLE
I am facing similar issue as reported earlier (#182) but on Android app

### ISSUE THREAD

**Issue by bhushanjawle** [infinitered/ignite#249]
Here are the setup details 
![ignite rni18n error](https://cloud.githubusercontent.com/assets/1283725/16832677/f58143c8-49c8-11e6-83a5-0f8acf45def7.png)

- `node -v`: v5.12.0
- `npm -v`: npm -v
- `react-native -v` (cli): 0.1.10
- `react-native -v`: 0.28.0
- `ignite --version`: 1.3.0
Please advise.

**Comment by bhushanjawle** [comment]
Looks like some issue with installation of package(no errors were reported)
Explicitly executing the following solved it
_npm install react-native-i18n --save
rnpm link react-native-i18n_
After this I got similar message for RNDeviceInfo
![ignite deviceinfo](https://cloud.githubusercontent.com/assets/1283725/16833138/89e12734-49cb-11e6-8da2-0c2fbdaf6c90.png)
I should mention that running _react-native run-android_ after _ignite init AppName_ had not worked for me but gave me message that this is not an Android project. 
It asked me to run a command to which created the android directory.
Post it I started getting the above messages. 
I am probably missing some step as I don't see anyone else has faced this issue.
Please advise.

**Comment by bhushanjawle** [comment]
Ok. Seems like I am definitely missing some step as I was able to resolve above following similar process i.e.
_npm i -g react-native-device-info --save
rnpm link react-native-device-info_

**Comment by ahmed1490** [comment]
I was facing the same.. sometime and then i ignited a new project and it worked for me

**Comment by bhushanjawle** [comment]
Created another new project with ignite and it worked fine. So closing this issue.
