### ISSUE TITLE
Jest failed on models file with shortcut import from other files

### ISSUE THREAD

**Issue by gwijaya94** [infinitered/ignite#2490]
### Describe the bug

Create a fresh project using `npx ignite-cli@8.8.2 new PizzaApp`
Have some functions on `app/utils/function.ts`. Let's say this:
<img width="379" alt="Screenshot 2023-08-10 at 01 18 28" src="https://github.com/infinitered/ignite/assets/65438712/2d3c9161-a992-4ef5-a464-9f457108ca94">

When implemented it on new generated model (named "TestStore"),  import with shortcut config which is `app/utils/function`:
<img width="375" alt="Screenshot 2023-08-10 at 01 18 19" src="https://github.com/infinitered/ignite/assets/65438712/0c6fa613-c70b-483c-9780-acdd33fa989e">

And run `yarn test`, it show this problem:
![Screenshot 2023-08-10 at 01 17 53](https://github.com/infinitered/ignite/assets/65438712/f7dab49c-f804-41a7-926e-013b7a90e878)

And I tried import `function.ts` and running it on `services/api/api.ts`, got the same problem too.
Is there any workaround to pass this ?

### Ignite version

8.8.2 - 8.8.7

### Additional info

```
System
  platform           darwin                                                        
  arch               x64                                                           
  cpu                4 cores      Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz         
  directory          PizzaApp     /Users/oktora/Documents/untitled_folder/PizzaApp 

JavaScript (and globally-installed packages)
  node               18.4.0       /Users/oktora/.nvm/versions/node/v18.4.0/bin/node 
  npm                8.12.1       /Users/oktora/.nvm/versions/node/v18.4.0/bin/npm  
    corepack         0.11.2                                                         
    npm              8.12.1                                                         
  yarn               1.22.17      /usr/local/bin/yarn                               
    appcenter-cli    2.11.0                                                         
  pnpm               -            not installed                                     
  expo               48.0.20      managed                                           

Ignite
  ignite-cli         8.8.2        /Users/oktora/.npm/_npx/1d450c3dec5f91f5/node_modules/.bin/ignite      
  ignite src         build        /Users/oktora/.npm/_npx/1d450c3dec5f91f5/node_modules/ignite-cli/build 

Android
  java               11.0.16      /usr/bin/java                     
  android home       -            /Users/oktora/Library/Android/sdk 

iOS
  xcode              14.0.1     
  cocoapods          1.11.3       /usr/local/bin/pod 

Tools
  git                git version 2.37.0 (Apple Git-136)   /usr/bin/git 
```

**Comment by frankcalise** [comment]
Hi @gwijaya94 - does it work if you switch it to a relative path instead of using the TS alias?

**Comment by frankcalise** [comment]
@gwijaya94 hello sorry for the delay, can you add the following line to your `jest.config.js` file and tell me if it helps solve the issue please?

```
module.exports = {
  // .. other default stuff here
  moduleNameMapper: { "^app/(.*)$": "<rootDir>/app/$1", "^assets/(.*)$": "<rootDir>/assets/$1" },
}
```

**Comment by gwijaya94** [comment]
<img width="373" alt="Screenshot 2023-10-18 at 13 41 59" src="https://github.com/infinitered/ignite/assets/65438712/d48381a4-5468-4e87-a031-54bb0c779e66">

Confirmed it works on the new init app. 
And just tried it on some of my projects. Need to change `"^app/(.*)$"` to `"^~/(.*)$"`, because the projects use `~` as the root path.

Thank you for the solution! @frankcalise
