### ISSUE TITLE
Rename Project failed on Android Ignite 8.8.2 to latest (8.8.7)

### ISSUE THREAD

**Issue by gwijaya94** [infinitered/ignite#2491]
### Describe the bug

running `yarn ignite-cli rename` and trow error below:
![Screenshot 2023-08-11 at 15 29 30](https://github.com/infinitered/ignite/assets/65438712/8625e03d-305c-49ad-9264-6633db05bf74)
Checked on case 1, rename.js:
<img width="538" alt="Screenshot 2023-08-11 at 15 31 52" src="https://github.com/infinitered/ignite/assets/65438712/70437209-88ec-4fb1-88d8-1e3bfbe25f8b">
Result:
![Screenshot 2023-08-11 at 15 33 09](https://github.com/infinitered/ignite/assets/65438712/01be02f2-0fa3-410e-8efc-969742957c8b)

Impact from AndroidManifest.xml discards package attribute from manifest tag since Ignite 8.8.2.
Maybe discard package checking on AndroidManifest.xml later ?

<b>Solved with adding package attribute back.</b>

### Ignite version

8.8.2 - 8.8.7

### Additional info

```
System
  platform           darwin                                                        
  arch               x64                                                           
  cpu                4 cores      Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz         
  directory          PizzaApp     /Users/oktora/Documents/untitled_folder/PizzaApp 

JavaScript (and globally-installed packages)
  node               18.4.0       /Users/oktora/.nvm/versions/node/v18.4.0/bin/node 
  npm                8.12.1       /Users/oktora/.nvm/versions/node/v18.4.0/bin/npm  
    corepack         0.11.2                                                         
    npm              8.12.1                                                         
  yarn               1.22.17      /usr/local/bin/yarn                               
    appcenter-cli    2.11.0                                                         
  pnpm               -            not installed                                     
  expo               48.0.20      managed                                           

Ignite
  ignite-cli         8.8.2        /Users/oktora/.npm/_npx/1d450c3dec5f91f5/node_modules/.bin/ignite      
  ignite src         build        /Users/oktora/.npm/_npx/1d450c3dec5f91f5/node_modules/ignite-cli/build 

Android
  java               11.0.16      /usr/bin/java                     
  android home       -            /Users/oktora/Library/Android/sdk 

iOS
  xcode              14.0.1     
  cocoapods          1.11.3       /usr/local/bin/pod 

Tools
  git                git version 2.37.0 (Apple Git-136)   /usr/bin/git 
```

**Comment by jamonholmgren** [comment]
Good catch!

Want to submit a PR for this @gwijaya94 ?

**Comment by gwijaya94** [comment]
Sure, will update you soon! @jamonholmgren

**Comment by gwijaya94** [comment]
Hi @jamonholmgren, just submit the PR on https://github.com/infinitered/ignite/pull/2492. 
Mind to check it out? Thanks.
