### ISSUE TITLE
[!] Invalid `Podfile` file: cannot load such file -- ./scripts/autolinking.

### ISSUE THREAD

**Issue by zinou-11y** [infinitered/ignite#2493]
### Describe the bug

can't install pod ! 

get this error : [!] Invalid `Podfile` file: cannot load such file -- ./scripts/autolinking.

### Ignite version

8.8.7

### Additional info

System
  platform           darwin                                                          
  arch               x64                                                             
  cpu                10 cores     Apple M1 Pro                                       
  directory          ios          /Users/user/Desktop/untitled folder/mushaf-app/ios 

JavaScript (and globally-installed packages)
  node               20.2.0       /Users/user/.nvm/versions/node/v20.2.0/bin/node 
  npm                9.6.6        /Users/user/.nvm/versions/node/v20.2.0/bin/npm  
    corepack         0.17.2                                                       
    npm              9.6.6                                                        
  yarn               1.22.19      /usr/local/bin/yarn                             
    create-gatsby    3.11.0                                                       
    create-vite      4.4.1                                                        
  pnpm               -            not installed                                   
  expo               48.0.20      managed                                         

Ignite
  ignite-cli         8.8.7        /Users/user/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/user/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               20.0.2       /usr/bin/java                   
  android home       -            /Users/user/Library/Android/sdk 

iOS
  xcode              14.3.1     
  cocoapods          1.12.1       /opt/homebrew/bin/pod 

Tools
  git                git version 2.39.2 (Apple Git-143)   /usr/bin/git

**Comment by tunv8zzz** [comment]
change 
`require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")`

**Comment by frankcalise** [comment]
@zinou-11y Are you still having issues? can you try the next version of ignite?

`npx ignite-cli@next new PizzaApp`

**Comment by WayneKim92** [comment]
@frankcalise, Thank you. but this problem did not go away completely.

**Comment by GeoffreyOlivier** [comment]
Same problem, when I clone my reposotory, the project is age from 5 month.

**Comment by frankcalise** [comment]
Can anyone post a link to a repo that reproduces this error?

**Comment by dvanblokland** [comment]
I had the same issues as listed here. Working both on a mac and on a windows pc. After re-cloning my repository to a new folder on my mac it suddenly stopped working...

After some investigation I found out it has something to do with the folder name. Don't use SPACES in your path. After removing the space in the folder name it was fixed.

**Comment by frankcalise** [comment]
As @dvanblokland mentioned, spaces in the path are an issue when running an iOS project, however this is the same experience upstream in both Expo/RN. Will contact the folks over there and see if we can find a fix.

Until then, I have a PR open to add a warning if anyone is trying to create a project on macOS with spaces in their chosen path.
