### ISSUE TITLE
Release apk not works

### ISSUE THREAD

**Issue by FahimMontasir** [infinitered/ignite#2494]
### Describe the bug

I tried multiple times to build release apk using provided release:android command. But the app crashes after a few second in my phone.

### Ignite version

8.***

### Additional info

.

**Comment by frankcalise** [comment]
Hi can you check through this issue: https://github.com/infinitered/ignite/issues/2431

**Comment by FahimMontasir** [comment]
removing  "main": "node_modules/expo/AppEntry.js" from package.json works for me

**Comment by FahimMontasir** [comment]
removing "main": "node_modules/expo/AppEntry.js" from package.json works for me
