### ISSUE TITLE
unable to launch default generated android app - ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by tgaff** [infinitered/ignite#250]
I'm using a default, generated app with no changes but I can't get it to launch in the emulator.  Instead I get the error `ReferenceError: __DEV__ is not defined` when I run `react-native run-android`.

### sequence of events

```bash
○ → ignite new DemoApp
```

☕  ☕  ☕ 

```bash
○ → react-native run-android
/Users/tgaff/devel/reactNative/DemoApp/node_modules/react-native/Libraries/react-native/react-native.js:15
if (__DEV__) {
    ^

ReferenceError: __DEV__ is not defined
    at Object.<anonymous> (/Users/tgaff/devel/reactNative/DemoApp/node_modules/react-native/Libraries/react-native/react-native.js:15:5)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tgaff/devel/reactNative/DemoApp/node_modules/react-native/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/tgaff/devel/reactNative/DemoApp/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:391:22
    at Array.map (native)

```

### react-native functional in general

React-native otherwise is working fine.  
I can generate apps with `react-native init Bananas` and then run them with `react-native run-android`.  

* Note I do have to add a local.properties file and set the `sdk.dir` first.  But as far as I can tell that's par for the course.  
  * I did try adding a local.properties to the _ignite_ app but that did not resolve the issue. 

> thanks for any help

### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please include the following version information.

- `node -v`: v4.2.1
- `npm -v`: 2.14.7
- `react-native -v` (cli): 1.0.0
- `react-native -v`: 0.28.0  (but globally installed is 0.29.1)
- `ignite --version`: 1.3.0

**Comment by skellock** [comment]
Can you try heading up to node 6.x?

**Comment by tgaff** [comment]
That seems to have worked.  I also had to generate a new app from scratch and kill the previous one's node processes.

Thanks.  Is there anything we should do to help the next user with this?

**Comment by GantMan** [comment]
We can put a check in for the node version, during install.
