### ISSUE TITLE
URGENT : application cruch with apk release in real device and emulators 

### ISSUE THREAD

**Issue by HAFDIAHMED** [infinitered/ignite#2507]
### Describe the bug

> Task :react-native-gradle-plugin:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gradle-plugin:compileKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 59s
1 actionable task: 1 executed

### Ignite version

latest

### Additional info

![image](https://github.com/infinitered/ignite/assets/58536023/b6274445-b484-488d-94e4-df71c34eb323)

**Comment by HAFDIAHMED** [comment]
up up up please it is very important for us

**Comment by HAFDIAHMED** [comment]
up

**Comment by HAFDIAHMED** [comment]
up

**Comment by HAFDIAHMED** [comment]
up

**Comment by frankcalise** [comment]
Please read this issue https://github.com/infinitered/ignite/issues/2431
