### ISSUE TITLE
Add doctor check if `new` command does not succeed 

### ISSUE THREAD

**Issue by frankcalise** [infinitered/ignite#2509]
## Summary

Unfortunately, there are times where igniting a new app does not succeed. It would be great if the CLI `new` command could detect when an exception is thrown and run `doctor` to output more information about the developer's environment.

**Comment by jvm-cognition** [comment]
@frankcalise can I pick this one up?

**Comment by frankcalise** [comment]
@jvm-cognition absolutely, thanks!

**Comment by frankcalise** [comment]
@jvm-cognition it looks as if bun 1.0.6 throws up during install, so if you needed a good reproducer for this try:

`npx ignite-cli@next --packager=bun --yes`

Should see something like

```
    ⠧ Installing bun dependencies (wow these are heavy)
/Users/fcalise/.npm/_npx/2351a7c35afcf833/node_modules/gluegun/build/index.js:15
    throw up;
    ^
bun install v1.0.6 (969da088)
 Resolving dependencies
 Resolved, downloaded and extracted [1253]
 Saved lockfile
/bin/bash: ypes/react-do: No such file or directory

(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.11.0
```

**Comment by jvm-cognition** [comment]
@frankcalise thanks this would definitely help.

**Comment by jvm-cognition** [comment]
@frankcalise I think I might need to tweak the way my environment is set up currently when I run` npx ignite-cli@next` I would want it to point to the local package (if this is not the case correct me if I am wrong) for any changes I made to apply, Currently when I run this it wants me to download the alpha version of the cli.

`Need to install the following packages:
ignite-cli@9.0.0-alpha.7
Ok to proceed? (y)`

Any tips or advice on this would be appreciated.

**Comment by frankcalise** [comment]
@jvm-cognition yes you can do the following from the top level project directory:

```
yarn
yarn build
```

Then go up a directory or to some temp dir where you want the project to be created (or you can just make sure you point to the proper directory when generating a project via the cli) and utilize the local build, for example:

```
cd ~/temp/projects
/path/to/ignite/bin/ignite new PizzaApp2509
```

That'll run your local changes instead of reaching out to npm.
