### ISSUE TITLE
v9: Changing slug in `app.json` causes app to white screen with no error because fonts don't load

### ISSUE THREAD

**Issue by pkreipke** [infinitered/ignite#2514]
### Describe the bug

For anyone who runs into this bug while testing v9 (and possibly v8)....

MacOS is **case sensitive** so if you decide to use MixedCase for your app's `slug` value without knowing better (doh) or you change it for any other reason, then Ignite's use of the `useFont` hook doesn't create a new folder with the new name and yet it can't find the earlier folder.

Test was done in a new app from Ignite Expresso (v9).
- answer the init questions for new app `LowerCase` and choose for the slug also `LowerCase`
- complete the questions
- start the app in Expo Go (`yarn start`), all should be fine
- open app.json
- realize your mistake on the `slug` value and change it to `lowercase` ("slug": "lowercase")
- restart the app
- the app will white-screen with no information

<img width="365" alt="image" src="https://github.com/infinitered/ignite/assets/12683108/8bd11d77-9550-4423-8e41-48f91040f3db">

### Ignite version

9 (expresso)

### Additional info

A helpful thing to do is to modify the call to `useFonts(...)` to grab the resulting error and throw causing the app to display a message and the fault, including the parent of the problematic child folder.

- open `app.tsx`
- find the call to `useFonts()` hook
- modify the line to capture the error as well as `areFontsLoaded`
`const [areFontsLoaded, fontError] = useFonts(customFontsToLoad)`
- throw an error so that Expo Go quickly shows you the problem:
```
  if (fontError) {
    const { name, cause, message } = fontError
    throw new Error(`Could not load fonts. Did you rename your app or slug perhaps?\n${name}: ${cause}\n${message}`)
  }
```

- copy paste the parent directory from the error message and paste into Finder > Go > Go to Folder...
- fix the child folder name/case-ing.
- reload app
- error should gone

**Comment by frankcalise** [comment]
You should use the `rename` command from ignite-cli to do this. Could you try that and see if it fixes this issue?

**Comment by frankcalise** [comment]
Spoke via Slack, was not aware of the cli command. Closing but leaving for discoverability.
