### ISSUE TITLE
Xcode 15 / Sonoma OS Support (RN ^0.72.5) 

### ISSUE THREAD

**Issue by ahinkle** [infinitered/ignite#2521]
### Describe the bug

Hey there! Thanks for putting this amazing boilerplate package together.

I'm running MacOS Sonoma, which runs Xcode 15. On a fresh installation of Ignite, I get the following:

```
CompileC 

/Users/{redacted}/Library/Developer/Xcode/DerivedData/{redacted}/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/json.o

/Users/{redacted}/GitHub/{redacted}/{redacted}/ios/Pods/RCT-Folly/folly/json.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target ‘RCT-Folly’ from project ‘Pods’) 

```

React Native v0.72.5 released a patch with a handful of XCode 15 C++ compilation fixes. Would there be any capacity to upgrade the Ignite boilerplate to RN 0.72.5?

Much appreciated!

### Ignite version

8.9.1

### Additional info

```
System
  platform           darwin                                                           
  arch               x64                                                              
  cpu                16 cores          Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz       

iOS
  xcode              15.0       
  cocoapods          1.11.3       /usr/local/bin/pod 
```

**Comment by frankcalise** [comment]
@ahinkle `npx ignite-cli@next new PizzaApp` should get you to the latest, should be 9.0.0-alpha.7

**Comment by frankcalise** [comment]
@ahinkle did you get a chance to try this out?

**Comment by ahinkle** [comment]
Hey @frankcalise,

Yes! It's working on v9.0. Excited for the release. Thank you!
