### ISSUE TITLE
May I ask what the problem is? The template cannot run after installation

### ISSUE THREAD

**Issue by bihongbin3027** [infinitered/ignite#2525]
### Describe the bug

$ npm run android

> spider-sms@0.0.1 android
> react-native run-android --active-arch-only

info Starting JS server...
info Detected architectures x86
info Installing the app...

FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\sxyǰ����Ŀ\SpiderSMS\android\settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'SpiderSMS'.
> Could not read script 'D:\sxy前端项目\SpiderSMS\node_modules\expo\scripts\autolinking.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 795ms

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 -PreactNativeDebugArchitectures=x86 -PreactNativeArchitectures=x86

FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\sxyǰ����Ŀ\SpiderSMS\android\settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'SpiderSMS'.
> Could not read script 'D:\sxy前端项目\SpiderSMS\node_modules\expo\scripts\autolinking.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 795ms

    at makeError (D:\sxy前端项目\SpiderSMS\node_modules\execa\index.js:174:9)
    at D:\sxy前端项目\SpiderSMS\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\sxy前端项目\SpiderSMS\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (D:\sxy前端项目\SpiderSMS\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.

### Ignite version

7.15.0

### Additional info

System
  platform           win32
  arch               x64
  cpu                12 cores     Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
  directory          SpiderSMS    D:\sxy前端项目\SpiderSMS

JavaScript (and globally-installed packages)
  node               18.17.0                                   C:\Program Files\nodejs\node.EXE
  npm                10.1.0                                    C:\Program Files\nodejs\npm.CMD
    corepack         0.18.0                                                     
    npm              10.1.0                                                     
    pnpm             8.7.5                                                      
    yarn             1.22.19                                                    
  yarn               1.22.19                                   C:\Program Files\nodejs\yarn.CMD
  pnpm               8.7.5                                     C:\Program Files\nodejs\pnpm.CMD
                     <no pnpm global package info available>                    
  expo               49.0.13                                   managed          

Ignite
  ignite-cli         8.9.2        C:\Users\sxy\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\sxy\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               1.8.0_281    C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\sxy\AppData\Local\Android\Sdk        

Tools
  git                git version 2.40.0.windows.1   C:\Program Files\Git\mingw64\bin\git.EXE

**Comment by frankcalise** [comment]
@bihongbin3027 Hello!

Can you please supply the `npx ignite-cli new MyApp --debug` output you are trying to work with?

Also, please follow the [Environment Setup](https://reactnative.dev/docs/environment-setup?os=windows&platform=android) docs for React Native on Windows. It appears your Java version could be misconfigured.

If you'd like, try `npx ignite-cli@next new MyApp` and you might have an easier time getting up and running with the Expo Go configuration

**Comment by bihongbin3027** [comment]
@frankcalise Hello!  The following is created using npx ignite cli new MyApp -- debug.
------------------------------------------------------------------------------------------------------
$ yarn android
yarn run v1.22.19
$ react-native run-android --active-arch-only
info JS server already running.
info Detected architectures x86
info Installing the app...
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\sxyǰ����Ŀ\SpiderSMS\android\settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'SpiderSMS'.
> Could not read script 'D:\sxy前端项目\SpiderSMS\node_modules\expo\scripts\autolinking.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 -PreactNativeDebugArchitectures=x86 -PreactNativeArchitectures=x86

FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\sxyǰ����Ŀ\SpiderSMS\android\settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'SpiderSMS'.
> Could not read script 'D:\sxy前端项目\SpiderSMS\node_modules\expo\scripts\autolinking.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at makeError (D:\sxy前端项目\SpiderSMS\node_modules\execa\index.js:174:9)
    at D:\sxy前端项目\SpiderSMS\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\sxy前端项目\SpiderSMS\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (D:\sxy前端项目\SpiderSMS\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by bihongbin3027** [comment]
$ npx ignite-cli doctor
System
  platform           win32
  arch               x64
  cpu                12 cores     Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
  directory          SpiderSMS    D:\sxy前端项目\SpiderSMS

JavaScript (and globally-installed packages)
  node               18.17.0                                   C:\Program Files\nodejs\node.EXE
  npm                10.1.0                                    C:\Program Files\nodejs\npm.CMD
    corepack         0.18.0                                                     
    npm              10.1.0                                                     
    pnpm             8.7.5                                                      
    yarn             1.22.19                                                    
  yarn               1.22.19                                   C:\Program Files\nodejs\yarn.CMD
  pnpm               8.7.5                                     C:\Program Files\nodejs\pnpm.CMD
                     <no pnpm global package info available>                    
  expo               49.0.13                                   managed          

Ignite
  ignite-cli         8.9.2        C:\Users\sxy\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\sxy\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               11.0.20      C:\Program Files\Java\jdk-11\bin\java.EXE
  android home       -            C:\Users\sxy\AppData\Local\Android\Sdk

Tools
  git                git version 2.40.0.windows.1   C:\Program Files\Git\mingw64\bin\git.EXE
