### ISSUE TITLE
How do we pass a value to another screen?

### ISSUE THREAD

**Issue by sudharsan1988** [infinitered/ignite#253]
I was trying to pass a value to another screen. Do we have any specific methods to pass values through routes like we change the title on the screen itself?

Thank you

### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please include the following version information.

- `node -v`: 
- `npm -v`: 
- `react-native -v` (cli): 
- `react-native -v`: 
- `ignite --version`:

**Comment by GantMan** [comment]
as of version 1.3.1 this can be handled via RNRF, documentation here:  https://github.com/aksonov/react-native-router-flux/blob/master/docs/MINI_TUTORIAL.md#passing-information

If it's more that just a little info, we suggest using redux and saga.
