### ISSUE TITLE
[cli] --remove-demo should clean up unused deps

### ISSUE THREAD

**Issue by frankcalise** [infinitered/ignite#2544]
## Problem

The `--remove-demo` cli switch successfully removes demo mark up, files and assets (in v9). It would be nice if it also removed dependencies that are no longer used so the dev doesn't have to figure this out.

## Packages to Remove

- `react-native-drawer-layout`
- `expo-application`
- `@react-navigation/bottom-tabs`

**Comment by jvm-cognition** [comment]
@frankcalise can I pick this one up?

**Comment by frankcalise** [comment]
@jvm-cognition Go for it
