### ISSUE TITLE
 which unix2dos 'which' is not recognized error

### ISSUE THREAD

**Issue by onurusluca** [infinitered/ignite#2551]
### Describe the bug

From console:

npx ignite-cli@latest new YoldaClient

✅ What bundle identifier? · com.yolda_client
✅ Where do you want to start your project? · C:\CODING\LEARNING\MOBILE APPS\yolda-client
✅ Do you want to initialize a git repository? (Y/n) · Yes
✅ Remove demo code? We recommend leaving it in if it's your first time using Ignite (y/N) · No
✅ Which package manager do you want to use? · pnpm
✅ Do you want to install dependencies? (Y/n) · Yes

    █ Creating YoldaClient using Ignite 8.11.1
    █ Powered by  ∞ Infinite Red  (https://infinite.red)
    █ Package Manager: pnpm
    █ Bundle identifier: com.yolda_client
    █ Path: C:\CODING\LEARNING\MOBILE APPS\yolda-client
    ────────────────────────────────────────────────────

    🖨  3D-printing a new React Native app
    🎨 Getting those last few details perfect
    🧶 Installing pnpm dependencies (wow these are heavy)

The following error occurred:

    Error: Command failed with exit code 1: which unix2dos
'which' is not recognized as an internal or external command,
operable program or batch file.

### Ignite version

8.11.1

### Additional info

```
System
  platform           win32
  arch               x64
  cpu                12 cores       AMD Ryzen 5 5600X 6-Core Processor
  directory          yolda-client   C:\CODING\LEARNING\MOBILE APPS\yolda-client

JavaScript (and globally-installed packages)
  node               19.0.0                                                                              C:\Program Files\nodejs\node.EXE
  npm                9.6.2                                                                               C:\Program Files\nodejs\npm.CMD
    eas-cli          5.6.0

    nodemon          2.0.22

    npm              9.6.2

    pnpm             8.9.2

    tile-extruder    2.1.0

    typescript       5.1.3

  yarn               -                                                                                   not installed

  pnpm               8.9.2                                                                               C:\Users\dur2d\AppData\Local\pnpm\pnpm.EXE
                     <no pnpm global package info available>

  expo               48.0.21 -> .\node_modules\.pnpm\expo@48.0.21_@babel+core@7.23.3\node_modules\expo   managed


Ignite
  ignite-cli         8.11.1       C:\Users\dur2d\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\dur2d\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               21.0.1       C:\Program Files\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            C:\Users\dur2d\AppData\Local\Android\Sdk

Tools
  git                git version 2.42.0.windows.2   C:\Program Files\Git\cmd\git.EXE
```

### Comment
Also happens with: `npx ignite-cli@latest new PizzaApp --yes`:

    █ Creating PizzaApp using Ignite 8.11.1
    █ Powered by  ∞ Infinite Red  (https://infinite.red)
    █ Package Manager: npm
    █ Bundle identifier: com.pizzaapp
    █ Path: C:\CODING\LEARNING\MOBILE APPS\PizzaApp
    ────────────────────────────────────────────────────

    🖨  3D-printing a new React Native app
    🎨 Getting those last few details perfect
    🧶 Installing npm dependencies (wow these are heavy)

The following error occurred:

    Error: Command failed with exit code 1: which unix2dos
'which' is not recognized as an internal or external command,
operable program or batch file.

**Comment by onurusluca** [comment]
I have found this: https://github.com/infinitered/ignite/issues/2545
Did `npx ignite-cli@next`
Got this:

>  Welcome to Ignite 9.0.0-alpha.9!
>    Ignite is a CLI that helps you spin up a new React Native app using a
>    battle-tested tech stack.
> 
>    Commands
> 
>    new               Creates a new React Native app
>                      ignite new MyApp
>                      ignite new MyApp --bundle com.mycompany.myapp
> 
>    generate (g)      Generates components and other app features
>                      ignite generate --hello
>                      ignite generate component Hello
>                      ignite generate model User
>                      ignite generate screen Login
> 
>    doctor            Checks your environment & displays versions of installed dependencies
>                      ignite doctor
> 
>    rename            Renames your React Native project (experimental)
>                      ignite rename NewName com.mycompany.newname
> 
>    remove-demo (rd)  Removes demo code from the project (add --dry-run to list changes but not execute)
>                      ignite remove-demo
>                      ignite remove-demo --dry-run
> 
>    remove-demo-markup (rdm)  Removes @demo markup from the project (add --dry-run to list changes but not execute)
>                              ignite remove-demo-markup
>                              ignite remove-demo-markup --dry-run
> 
>    snackify          Creates a new branch which can be imported as an Expo snack
>                      ignite snackify
> 
>    See the documentation: https://github.com/infinitered/ignite/tree/master/docs
> 
>    If you need additional help, join our Slack at http://community.infinite.red

Where do I go from this? Do I do ` ignite new MyApp` ? I get this:
```
ignite: The term 'ignite' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
So do I need to add this to environment variables?

Why is this error happening?
Default way to use Ignite isn't through the `npx ignite-cli@next` so others will have this error too until this is addressed.

**Comment by frankcalise** [comment]
Hi @onurusluca  - sorry for the troubles. Since you're on Windows the cli is trying to fix the EOL in the generators.

It seems you are missing a utility in your shell, can you tell me more about if you're running in powershell or something else?

For now, you can certainly just continue by finishing the install from the project directory and then if you intend to use the generators you'll need to fix the EOL characters.

**Comment by onurusluca** [comment]
@frankcalise Thanks for the quick reply!

I am using PowerShell on Windows Terminal

I couldn't understand what to do from the explanation after doing `npx ignite-cli@next`. I just tried doing `npx ignite-cli@next new PizzaApp` and it works but really need to change the wording there. Also if the `ignite-cli@next` won't be ready soon, it'd be best to add this solution in Readme.

**Comment by onurusluca** [comment]
@frankcalise I am sorry for being too much but after doing the installation(without changing anything at all), I got this error after I do `pnpm run android`:

```
Logs for your project will appear below. Press Ctrl+C to exit.
Error: Unable to resolve module ./node_modules\expo\AppEntry from C:\CODING\LEARNING\MOBILE APPS\PizzaApp/.:

None of these files exist:
  * node_modules\expo\AppEntry(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)
  * node_modules\expo\AppEntry\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)
    at ModuleResolver.resolveDependency (C:\CODING\LEARNING\MOBILE APPS\PizzaApp\node_modules\.pnpm\metro@0.76.8\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\CODING\LEARNING\MOBILE APPS\PizzaApp\node_modules\.pnpm\metro@0.76.8\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at C:\CODING\LEARNING\MOBILE APPS\PizzaApp\node_modules\.pnpm\metro@0.76.8\node_modules\metro\src\lib\transformHelpers.js:169:21
    at Server._resolveRelativePath (C:\CODING\LEARNING\MOBILE APPS\PizzaApp\node_modules\.pnpm\metro@0.76.8\node_modules\metro\src\Server.js:1045:12)
    at async Server.requestProcessor [as _processBundleRequest] (C:\CODING\LEARNING\MOBILE APPS\PizzaApp\node_modules\.pnpm\metro@0.76.8\node_modules\metro\src\Server.js:449:37)
    at async Server._processRequest (C:\CODING\LEARNING\MOBILE APPS\PizzaApp\node_modules\.pnpm\metro@0.76.8\node_modules\metro\src\Server.js:383:7)
```

**Comment by onurusluca** [comment]
@frankcalise Regarding the above problem. I delete `node_modules` and `package-lock.json`, did `pnpm i` and it is working fine now. I don't know why this happened so I am just sharing my experience, maybe you can figure it out.

Although on the first page when scrolling, I got:
`WARN  estimatedItemSize FlashList prop is not defined - based on current configuration you can set it to 59 to optimize list performance. Refer to FlashList documentation for more details.`

**Comment by frankcalise** [comment]
Can you please provide the output of `Get-Command unix2dos`, do you have this utility installed from Git?

**Comment by onurusluca** [comment]
@frankcalise 
> Can you please provide the output of `Get-Command unix2dos`, do you have this utility installed from Git?

I am getting:


```
Get-Command: The term 'unix2dos' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by jamonholmgren** [comment]
We're looking into this internally, thanks for your patience!

**Comment by frankcalise** [comment]
@onurusluca @Markos21 when the CI finishes you can try the new version and see if the issue is fixed! Feel free to reopen the issue with more details if still having a problem.

Note, I've found sometimes Windows doesn't pull the latest via npx command, so make sure it's version `8.11.3` you are running.
