### ISSUE TITLE
[boilerplate] fix web layout tab bar alignment

### ISSUE THREAD

**Issue by frankcalise** [infinitered/ignite#2552]
## Overview

Currently, the tabs on the web layout are a little misaligned, it would be nice if they were aligned properly. The components icon is cut off (see screenshot)

If anyone wants to spruce up the web experience in general, that would certainly be welcome. 

## Screenshots

![image](https://github.com/infinitered/ignite/assets/374022/064802b3-f387-4948-973a-cc33e5f48941)

**Comment by Amarpsp10** [comment]
hi @frankcalise,

Tabar label style has property `flex: 1` which was making cause

**Comment by Amarpsp10** [comment]
@frankcalise thanks, PR created!
