### ISSUE TITLE
Generating app icon only generates for expo

### ISSUE THREAD

**Issue by shingso** [infinitered/ignite#2566]
### Describe the bug

When using` npx ignite-cli generate app-icon` to generate app icons it will only generate app icons for expo. I've tried reinstalling the application, but the icon never changes. It looks like the 'expo' constant was set for the generateAppIcons function (https://github.com/infinitered/ignite/blob/master/src/commands/generate/app-icon.ts). Is there a way to make the app icons generate for android? 

```
async function generate(toolbox: GluegunToolbox) {
  const { parameters } = toolbox

  const { isValid, messages } = await validateAppIconGenerator("expo", parameters.options)

  if (!isValid) {
    messages.forEach((message) => warning(message))
    return
  }

  const isSuccessful = await generateAppIcons("expo")

  if (isSuccessful) {
    heading(`App icons generated!`)
    p(
      "Uninstall the application from your simulator/emulator and re-build your app to see the changes!",
    )
  }
}
```

### Ignite version

9.0.1

### Additional info

System
  platform           darwin                                 
  arch               arm64                                  
  cpu                12 cores     Apple M2 Pro              
  directory          StripeTest   /Users/shingso/StripeTest 

JavaScript (and globally-installed packages)
  node               21.1.0       /opt/homebrew/bin/node 
  npm                10.2.0       /opt/homebrew/bin/npm  
    @angular/cli     15.1.4                              
    ios-deploy       1.12.2                              
    npm              10.2.0                              
  yarn               -            not installed          
  pnpm               -            not installed          
  bun                -            not installed          
  expo               48.0.20      managed                

Ignite
  ignite-cli         9.0.1        /Users/shingso/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/shingso/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               17.0.7       /usr/bin/java                      
  android home       -            /Users/shingso/Library/Android/sdk

**Comment by shingso** [comment]
Solved by downgrading the version, but leaving issue up incase is issue

**Comment by frankcalise** [comment]
@shingso yeah you can use the old version of Ignite if you need to target vanilla icon generation. The new one just needs Expo version as prebuild will take care of the the test.

Thanks for the info.
