### ISSUE TITLE
node_modules/expo/AppEntry.js 

### ISSUE THREAD

**Issue by tanzeel152** [infinitered/ignite#2571]
Cannot run the app on Android getting this error 
node_modules/expo/AppEntry.js 
Error: Unable to resolve module app/utils/storage from /Users/app/Desktop/PizzaApp/app/devtools/ReactotronConfig.ts: app/utils/storage could not be found within the project or in these directories:
  node_modules
  ../../node_modules 
 12 | import { clear } from "app/utils/storage"

### Ignite version

9.0.2

### Additional info

System
  platform           darwin                                                  
  arch               x64                                                     
  cpu                8 cores      Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz 
  directory          PizzaApp     /Users/app/Desktop/PizzaApp                

JavaScript (and globally-installed packages)
  node               21.1.0       /usr/local/bin/node 
  npm                10.2.0       /usr/local/bin/npm  
    eas-cli          5.7.0                            
    npm              10.2.0                           
    yarn             1.22.19                          
  yarn               1.22.19      /usr/local/bin/yarn 
    node-gyp         10.0.1                           
  pnpm               -            not installed       
  bun                -            not installed       
  expo               49.0.21      managed             

Ignite
  ignite-cli         9.0.2        /Users/app/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/app/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               11.0.21      /usr/bin/java                  
  android home       -            /Users/app/Library/Android/sdk 

iOS
  xcode              15.0.1     
  cocoapods          1.14.2       /Users/app/.rvm/gems/ruby-3.2.1/bin/pod 

Tools
  git                git version 2.39.3 (Apple Git-145)   /usr/bin/git

**Comment by tanzeel152** [comment]
> Can you post your `app.json` and `tsconfig.json`?

tsconfig 
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "jsx": "react-native",
    "module": "es2015",
    "moduleResolution": "node",
    "strict": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "sourceMap": true,
    "target": "esnext",
    "lib": ["esnext", "dom"],
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "baseUrl": ".",
    "paths": {
      "app/*": ["./app/*"],
      "assets/*": ["./assets/*"]
    }
  },
  "extends": "expo/tsconfig.base",
  "ts-node": {
    "compilerOptions": {
      // compilerOptions specified here will override those declared above,
      // but *only* in ts-node.  Useful if you want ts-node and tsc to use
      // different options with a single tsconfig.json.
      "module": "commonjs"
    }
  },
  "include": ["index.js", "App.tsx", "app", "types", "plugins", "app.config.ts"],
  "exclude": ["node_modules", "test/**/*"]
}

app.json 
{
  "name": "PizzaApp",
  "displayName": "PizzaApp",
  "expo": {
    "name": "PizzaApp",
    "slug": "PizzaApp",
    "scheme": "pizzaapp",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/app-icon-all.png",
    "splash": {
      "image": "./assets/images/splash-logo-all.png",
      "resizeMode": "contain",
      "backgroundColor": "#191015"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "jsEngine": "hermes",
    "assetBundlePatterns": [
      "**/*"
    ],
    "android": {
      "icon": "./assets/images/app-icon-android-legacy.png",
      "package": "com.pizzaapp",
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/app-icon-android-adaptive-foreground.png",
        "backgroundImage": "./assets/images/app-icon-android-adaptive-background.png"
      },
      "splash": {
        "image": "./assets/images/splash-logo-android-universal.png",
        "resizeMode": "contain",
        "backgroundColor": "#191015"
      }
    },
    "ios": {
      "icon": "./assets/images/app-icon-ios.png",
      "supportsTablet": true,
      "bundleIdentifier": "com.pizzaapp",
      "splash": {
        "image": "./assets/images/splash-logo-ios-mobile.png",
        "tabletImage": "./assets/images/splash-logo-ios-tablet.png",
        "resizeMode": "contain",
        "backgroundColor": "#191015"
      }
    },
    "web": {
      "favicon": "./assets/images/app-icon-web-favicon.png",
      "splash": {
        "image": "./assets/images/splash-logo-web.png",
        "resizeMode": "contain",
        "backgroundColor": "#191015"
      },
      "bundler": "metro"
    },
    "plugins": [
      "expo-localization",
      [
        "expo-build-properties",
        {
          "ios": {
            "newArchEnabled": false
          },
          "android": {
            "newArchEnabled": false
          }
        }
      ]
    ],
    "experiments": {
      "tsconfigPaths": true
    }
  },
  "ignite": {
    "version": "9.0.2"
  }
}

**Comment by frankcalise** [comment]
Can you provide me some more information to help you please? 

1. Include the command you are running to generate the project
2. Which OS, iPhone or Android are you running
3. Have you tried both? If not, please do
4. Can you run react-native or Expo generated apps without Ignite usually?

**Comment by tanzeel152** [comment]
thanks yarn android solved the issue
