### ISSUE TITLE
Changing app icon

### ISSUE THREAD

**Issue by savasgok** [infinitered/ignite#2579]
### Describe the bug

I followed the procedure written in Generators about changing icon. After running the generator, I got "App icons generated!   Uninstall the application from your simulator/emulator and re-build your app to see the changes!". I first uninstalled the app in the emulator and rebuild the app.Unfortunately, no changes in the app icons. 

I did this twice to ensure icon is not changing. Could you please help me?

### Ignite version

latest

### Additional info

npx ignite-cli generate app-icon android
   
   Generating Expo app icons...
   ✅ app-icon-ios.png
   ✅ app-icon-android-legacy.png
   ✅ app-icon-android-adaptive-background.png
   ✅ app-icon-android-adaptive-foreground.png
   ✅ app-icon-all.png
   ✅ app-icon-web-favicon.png
   ✅ app.json
   App icons generated!
   Uninstall the application from your simulator/emulator and re-build your app to see the changes!

**Comment by abtonc** [comment]
Execute `yarn run prebuild:clean` command, it fixed the similar issue that I had with splash screen for me.

If that does not work, try deleting `ios` and `android` folders.

**Comment by savasgok** [comment]
Thank you for your help. `yarn run prebuild:clean` worked for me

**Comment by mazenchami** [comment]
@savasgok Thank you for opening this issue. It looks like @abtonc solution worked for you.

I'll be closing out this issue as it looks like its resolved. Feel free to re-open if the issue still persists.
