### ISSUE TITLE
Where is the best palace to dispatch action and  fetch data from server?

### ISSUE THREAD

**Issue by xiongjiabin** [infinitered/ignite#258]
If the network is not good, we found has some "stops"  when do navigations, So my question, where is the best palace to dispatch action to saag and do the fetch job. 
 
tapNewTask (){
      const { dispatch, navigator } = this.props
      **dispatch(Actions.requestTaskStart())**
      const route = Routes.TaskScreen
      navigator.push(route)
  }

or

tapNewTask (){
      const { dispatch, navigator } = this.props
      const route = Routes.TaskScreen
      navigator.push(route)
      **dispatch(Actions.requestTaskStart())**
  }

or in component's componentDidMount?

**Comment by skellock** [comment]
When you say stops, you be janky animation?  That's really an issue with React Native.

Generic solutions I can think of:

1.  `InteractionManager` allows you to defer your work until the animation ends.  Have a look at https://facebook.github.io/react-native/docs/interactionmanager.html .
2.  `Animation.start()` can now opt-in into `useNativeDriver: true` to pump the events from the native side of the bridge.  Less JS competing for execution.
3.  `componentDidMount ()` can work great. It depends on your app.  Do you have all the info you need to kick off your action?  In your example, you do.

Also, it might not be the network access that's causing the jank.  It could be the fact you're transitioning to a screen that has a lot of controls it needs to instantiate.  Images are really bad for this.  They lock while decoding.  It's hardly noticeable until you have a lot.  Then it hurts. 

For this, you might be able to defer rendering of the controls on the destination screen by using a simple state flag that's driven by a setTimeout in componentDidMount.  I've had success with this before, but really didn't like having to do it.

Their new IncrementalRenderer (currently experimental) is supposed to address this issue.

Another thing that can slow down your app is using `seamless-immutable` in your reducers when your data is LARGE (e.g. a JSON dataset).

It boils down to... there's lots of ways to improve performance.  You have to play around to see what's right for your app.
