### ISSUE TITLE
Expo Go should not install expo-dev-client

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#2600]
### Describe the bug

When @morganick created a new Ignite app, choosing Expo Go, it installed expo-dev-client, which caused issues.

Expo Go should not install that.

### Ignite version

latest

### Additional info

no

EDIT: thanks @ElonVolo -- this is the error message:

```
CommandError: No development build (com.myorg.myapp) for this project is installed. Please make and install a development build on the device first.
```

**Comment by ElonVolo** [comment]
Could there be any connection between this bug me, just now, creating a fresh ignite project, running "yarn ios" and getting back the error

```CommandError: No development build (com.myorg.myapp) for this project is installed. Please make and install a development build on the device first.```
