### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by LThemes** [infinitered/ignite#2613]
### Describe the bug

With latest version when you build a brand new app via cli you get [missing "en.LoginScreen.SignIn" translation] for example
This happens with all translations.

![Simulator Screenshot - iPhone 11 Pro - 2024-01-24 at 22 03 26](https://github.com/infinitered/ignite/assets/6774298/cb825df7-c720-4ec6-be6f-80d81eb2e9af)

### Ignite version

9.4.1

### Additional info

System
  platform           darwin                                                                               
  arch               x64                                                                                  
  cpu                12 cores        Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz         

`Creating testeposcache using Ignite 9.4.1
    █ Powered by  ∞ Infinite Red  (https://infinite.red)
    █ Package Manager: npm
    █ Bundle identifier: com.testeposcache
    █ Path: /Users/********/dev/react_native/********/********/testeposcache
    ────────────────────────────────────────────────────

    🖨  3D-printing a new React Native app
    🎨 Getting those last few details perfect
    🧶 Installing npm dependencies (wow these are heavy)
       Configuring app.json
    🛠️  Removing fancy demo markup

    ────────────────────────────────────────────────────

    Ignited testeposcache in 92.2s  🚀

    For next time: here are the Ignite options you picked!
      npx ignite-cli new testeposcache \
        --bundle=com.testeposcache \
        --git=false \
        --install-deps \
        --packager=npm \
        --target-path=/Users/********/dev/react_native/********/********/testeposcache \
        --remove-demo=false \
        --workflow=expo \
        --no-timeout=false`

**Comment by baontsparkminds** [comment]
temporary solution:
`const fallbackLocale = "en"`
=> `const fallbackLocale = "en-US"`

**Comment by boilad** [comment]
For non-US folks, you'll have to add an entry for `en-XX` here: https://github.com/infinitered/ignite/blob/75cc7515cd371a44962b9e379d9e121c801cc4ae/boilerplate/app/i18n/i18n.ts#L14

Ex: As a Canadian, I had to add an entry for `en-CA`

**Comment by LThemes** [comment]
Thanks both that worked :)
