### ISSUE TITLE
Error when running `pod install` in the `ios` directory.

### ISSUE THREAD

**Issue by 2lach** [infinitered/ignite#2620]
## Error when running pod install -> Error installing hermes-engine

Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed -> Cause: Error installing hermes-engine

## Description:
first i ran:
`npx ignite-cli@latest new zlazhpush `

choosen options:
```whatever
✅ What bundle identifier? · com.stefanpush
✅ Where do you want to start your project? ·/my/paths/to/projects/testproject/zlazhpush
✅ Do you want to use Expo? · Expo
✅ Which Expo workflow? (You can switch between them later with a little work -- here's how: https://ignitecookbook.com/docs/recipes/SwitchBetweenExpoGoCNG) · Expo CNG

✅ Do you want to initialize a git repository? (Y/n) · Yes
✅ Remove demo code? We recommend leaving it in if it's your first time using Ignite (y/N) · Yes
✅ Which package manager do you want to use? · npm
✅ Do you want to install dependencies? (Y/n) · No
✅ ❗EXPERIMENTAL❗Would you like to enable the New Architecture? (y/N) · No
```
then 
`npm install` (succesfully)
`npm run ios`

at this point i received a build error

Expected Behavior:
I expected my IPhone (virtual from XCode) to render the start application

Actual Behavior:
Error 
```bash
✔ Config synced
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Error installing hermes-engine

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/my/path/.gem/ruby/3.2.2/bin/pod install --repo-update --ansi
```


Environment:





### Ignite version

9.4.2

### Additional info

```bash
System
  platform           darwin
  arch               arm64
  cpu                8 cores      Apple M3
  directory          zlazhpush   /my/paths/to/projects/testproject/zlazhpush

JavaScript (and globally-installed packages)
  node               18.16.1      /my/paths/to/Library/Caches/fnm_multishells/54304_1706729940241/bin/node
  npm                9.5.1        /my/paths/to/Library/Caches/fnm_multishells/54304_1706729940241/bin/npm
    npm              9.5.1
  yarn               1.22.21      /opt/homebrew/bin/yarn
    ios-deploy       1.12.2
  pnpm               -            not installed
  bun                -            not installed
  expo               49.0.22      managed

Ignite
  ignite-cli         9.4.2        /my/paths/to/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /my/paths/to/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               1.8.0_391    /usr/bin/java
  android home       -            undefined

iOS
  xcode              15.2
  cocoapods          1.15.0       /my/paths/to/.gem/ruby/3.2.2/bin/pod

Tools
  git                git version 2.43.0   /opt/homebrew/bin/git
  ```

**Comment by 2lach** [comment]
Enviroment:

![neofetch](https://github.com/infinitered/ignite/assets/11457600/5d72992d-1bd8-427a-ab75-149c70727a69)


Log:
[xcodebuild.log](https://github.com/infinitered/ignite/files/14116827/xcodebuild.log)

**Comment by 2lach** [comment]
**This was not an Ignite issue it is a  Cocoapods issue when using a mac with a M1,2,3 chip**

here is how i resolved it:

1. Open terminal
2. Type: gem list
3. In my case, the list that resulted had all this:
```
cocoapods (1.10.2)
cocoapods-core (1.10.2)
cocoapods-deintegrate (1.0.5)
cocoapods-downloader (1.6.3)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.1)
cocoapods-trunk (1.6.0)
cocoapods-try (1.2.0)
```
4. From that list, uninstall everything that references 'cocoapods'. Do this by typing the following for each 'cocoapods' reference you see: sudo gem uninstall cocoapods-core
5. Install homebrew.
6. Update homebrew: `brew upgrade`
7. Using homebrew, install Ruby `brew install rbenv ruby-build`
8. Update ruby: `rbenv install 3.2.0`
9. Set the new ruby version to global: rbenv global 3.2.0
10.  add `eval "$(rbenv init - zsh)"`to your .zshrc 
11. Restart your computer.
12. `sudo gem uninstall cocoapods`
13. `sudo arch -arm64 gem install -n /usr/local/bin cocoapods -v 1.14.3`


links:
https://forum.unity.com/threads/cocoapods-installation-failure-when-building-for-ios.1167700/#post-8793733
https://github.com/CocoaPods/CocoaPods/issues/12226

**Comment by markrickert** [comment]
Thanks for posting the solution here!
