### ISSUE TITLE
new install in Win10 - not finding react-native-cli

### ISSUE THREAD

**Issue by xims** [infinitered/ignite#263]
Hello,

I've just made a fresh install of everything on Win 10.

When I run command 'ignite new testApp'
I get error:
Igniting testApp
� Must have at least version 1.x - 'npm install -g react-native-cli'

I did ran that command and it finished with a message '`-- react-native-cli@1.0.0'

node v6.3.0
npm v3.8.3

**Comment by akhenda** [comment]
I'm also getting the same error. I also have react-native-cli@1.0.0 installed.

**Comment by mengyou658** [comment]
me too

**Comment by GantMan** [comment]
Install grep please, we think this might be the issue.

This code will fail without grep:
https://github.com/infinitered/ignite/blob/6f2c628440fc20f622aa1420b7cc11456c458729/ignite-generator/src/app/index.es#L140-L142

We'll update the check to alarm windows users

**Comment by GantMan** [comment]
please upgrade to 1.4.0 and try again.

**Comment by kevinvangelder** [comment]
Everything is working for me with the following versions:
```
Computer
  Platform: win32

Ignite
  Version: 1.4.0
  Path: C:\USERS\KEVIN\APPDATA\ROAMING\NPM\IGNITE.CMD

Node
  Version: v6.3.1
  Path: C:\PROGRAM FILES\NODEJS\NODE.EXE

NPM
  Version: 3.10.6
  Path: C:\PROGRAM FILES\NODEJS\NPM.CMD

Yeoman
  Version: 1.8.3

React Native CLI
  Version: 1.0.0

App
  React Native Version: ¯\_(ツ)_/¯
```

**Comment by GantMan** [comment]
did you have to install grunt-cli globally?

**Comment by kevinvangelder** [comment]
I already had it. Keep in mind that I'm on Microsoft's Windows Insider builds, so I have early access to things like Bash in CMD.

**Comment by xims** [comment]
I can confirm, it's working now
Thanks a lot!

**Comment by GantMan** [comment]
excellent!  Closing now
