### ISSUE TITLE
Toggle "switch" variant does not slide on web

### ISSUE THREAD

**Issue by Warr1611** [infinitered/ignite#2637]
### Describe the bug

Steps to reproduce:
1. Initialize a new project: `npx ignite-cli new ignite-test`
2. `cd .\ignite-test\`
3. `yarn start`
4. Press `w` to open web version
5. Navigate to http://localhost:8081/showroom/toggle/variants
6. Click one of the "switch" variant Toggles

![image](https://github.com/infinitered/ignite/assets/7979407/d66047ed-d0ce-4bfa-a314-7ae2e5edc053)
Before clicking either
![image](https://github.com/infinitered/ignite/assets/7979407/90016171-66f6-4835-b184-e434614d5a01)
After clicking both

The colors change, but the inner indicator does not slide to reflect the new state.

### Ignite version

9.5.0

### Additional info

System
  platform           win32
  arch               x64
  cpu                16 cores      11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz
  directory          ignite-test   C:\Users\warr7\repos\habit-tracker\ignite-test\ignite-test

JavaScript (and globally-installed packages)
  node               20.11.0                                   C:\Program Files\nodejs\node.EXE
  npm                10.2.4                                    C:\Program Files\nodejs\npm.CMD
    expo-cli         6.3.10
  yarn               1.22.21                                   C:\Program Files\nodejs\yarn.CMD
  pnpm               8.15.2                                    C:\Program Files\nodejs\pnpm.CMD
                     <no pnpm global package info available>
  bun                -                                         not installed
  expo               50.0.6                                    managed

Ignite
  ignite-cli         9.5.0        C:\Users\warr7\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\warr7\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               1.8.0_291    C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.EXE
  android home       -            undefined

Tools
  git                git version 2.31.1.windows.1   C:\Program Files\Git\cmd\git.EXE

**Comment by frankcalise** [comment]
Thanks for the report, will look into it!

**Comment by frankcalise** [comment]
@Warr1611 I opened a PR with a fix for it, try it out in your project and LMK if it's good for you

**Comment by Warr1611** [comment]
@frankcalise I dropped your changes into my project and they work perfectly! Thanks!
