### ISSUE TITLE
[Enhancement] v10 - Replace async storage with mmkv

### ISSUE THREAD

**Issue by frankcalise** [infinitered/ignite#2639]
## Overview
- Remove @react-native-async-storage/async-storage
- Install react-native-mmkv
- Make adjustments utils/storage.ts
- Add Cookbook recipe to revert to async storage

## Prerequisites
- Depends on #2638 
- Target branch `v10`

**Comment by SlideeScherz** [comment]
not compatible with Expo

**Comment by frankcalise** [comment]
@SlideeScherz not compatible with Expo Go is correct, we're aware but we have plans :)

**Comment by frankcalise** [comment]
Closed by #2660
