### ISSUE TITLE
[Enhancement] v10 - Refactor Toggle

### ISSUE THREAD

**Issue by frankcalise** [infinitered/ignite#2644]
## Overview
- `Toggle.tsx` component is large, houses 3 components and is hard to read
- Refactor into Checkbox/Switch/Radio components
- Possibly refactor reanimated code related to RTL Switch
- Target branch `v10`

**Comment by markrickert** [comment]
Awesome! This definitely should be done. I think removing reanimated as a direct dependency of any of our components is a good idea. We can keep it in the package json because it's required for other things, but I don't think we should be using reanimated in our default components.

**Comment by frankcalise** [comment]
@markrickert so you're saying the components dir to only rely on `Animated` from core RN?

**Comment by markrickert** [comment]
Yeah, i think our boilerplate components should be as simple as possible. I don't think ignite should be in the business of advanced animation examples unless we're actually using that animation and component in a real project. My opinion is the simpler the better. Take with a grain of 🧂 😄

**Comment by frankcalise** [comment]
Closed by #2667 in v10
