### ISSUE TITLE
Unable to access Store A values/actions in Store B firectly using useStores hook 

### ISSUE THREAD

**Issue by Zilleabbas10** [infinitered/ignite#2652]
### Describe the bug

I am working on a boilerplate of react-native-ignite and trying to access Store A actions directly in Store B using useStores() hook but I am unable to do it and can't find any way to do it.

If I use .create() It creates a new instance of the store.

Is there any way to do it so, or am I missing anything? Thanks

### Ignite version

7.15.0

### Additional info

N/A

**Comment by frankcalise** [comment]
Ignite 7.15 is quite old, is this a new project or one that's been around for some time?

If the latter, if you could provide a snippet of what you have that would be helpful.

If it's a new project and you're just starting out, I'd try using the latest version and see if you run into the same issue.

**Comment by Zilleabbas10** [comment]
@frankcalise  It's a new project and Sorry ignite version is 9.2.0

So Let me add some details. 
Let's suppose I am using the same code of boilerplate

This is my AuthenticationStore file

```
import { Instance, SnapshotOut, types } from "mobx-state-tree"

export const AuthenticationStoreModel = types
  .model("AuthenticationStore")
  .props({
    authToken: types.maybe(types.string),
    authEmail: "",
  })
  .views((store) => ({
    get isAuthenticated() {
      return !!store.authToken
    },
  }))
  .actions((store) => ({
    setAuthToken(value?: string) {
      store.authToken = value
    }
  }))

export interface AuthenticationStore extends Instance<typeof AuthenticationStoreModel> {}
export interface AuthenticationStoreSnapshot extends SnapshotOut<typeof AuthenticationStoreModel> {}
```

And This is my EpisodeStore file
```
import { Instance, SnapshotOut, types } from "mobx-state-tree"
import { api } from "../services/api"
import { Episode, EpisodeModel } from "./Episode"
import { withSetPropAction } from "./helpers/withSetPropAction"

export const EpisodeStoreModel = types
  .model("EpisodeStore")
  .props({
    episodes: types.array(EpisodeModel),
    favorites: types.array(types.reference(EpisodeModel)),
    favoritesOnly: false,
  })
  .actions(withSetPropAction)
  .actions((store) => ({
    async fetchEpisodes() {


// here I want to use action function `setAuthToken` from AuthenticationStore, How can I use here??


      const response = await api.getEpisodes()
      if (response.kind === "ok") {
        store.setProp("episodes", response.episodes)
      } else {
        console.error(`Error fetching episodes: ${JSON.stringify(response)}`)
      }
    },
  }))

export interface EpisodeStore extends Instance<typeof EpisodeStoreModel> {}
export interface EpisodeStoreSnapshot extends SnapshotOut<typeof EpisodeStoreModel> {}
```

In EpisodeStore file, I put a comment in action `fetchEpisodes`, Here I want to use `setAuthToken` from AuthenticationStore, How can I access this method??

Do I make my point clear??

**Comment by frankcalise** [comment]
@Zilleabbas10 hey, I think this Ignite Cookbook Recipe can help you out: https://ignitecookbook.com/docs/recipes/DistributingAuthTokenToAPI

**Comment by Zilleabbas10** [comment]
@frankcalise In this example we are calling `distributeAuthToken` function from `AuthenticationStore` in a component. But in my case I need to call this `distributeAuthToken` function in my another store directly.

**Comment by frankcalise** [comment]
@Zilleabbas10 So what that recipe does is, upon setting the API token, your api requests made in other stores will already have that info filled in for you. So you don't need to obtain it and pass it in every call in other stores

**Comment by Zilleabbas10** [comment]
@Zilleabbas10 Let suppose I have a `LoadingStore` file like the following

```
import { Instance, SnapshotOut, types } from "mobx-state-tree"

export const LoadingStoreModel = types
  .model("LoadingStore")
  .props({
    isLoading: types.maybe(types.boolean),
  })
  .views((store) => ({
  }))
  .actions((store) => ({
    setLoading(value?: boolean) {
      store.isLoading = value
    }
  }))

export interface LoadingStore extends Instance<typeof LoadingStoreModel> {}
export interface LoadingStoreSnapshot extends SnapshotOut<typeof LoadingStoreModel> {}
```

I need to call the action of this loadingStore.setLoading(true) before I call any API in someother store. How can I do this??

I think I am pretty more clear now??

**Comment by frankcalise** [comment]
You can get to other stores by first getting the root store using the included helper:

https://github.com/infinitered/ignite/discussions/2503#discussioncomment-7069292

**Comment by Zilleabbas10** [comment]
@frankcalise thanks man. This is what I was looking for. Really appreciated your help 👍
