### ISSUE TITLE
Generic function load in storage [boilerplate]

### ISSUE THREAD

**Issue by tuantvk** [infinitered/ignite#2657]
Hi guys, thank you for this boilerplate.

I have suggest use generic function for this case like more helpful:

https://github.com/infinitered/ignite/blob/69ab34be11e9cb718f0c4acc97d6fd05ada4ac1a/boilerplate/app/utils/storage/storage.ts#L37

Replace with:
```ts
export async function load<T>(key: string): Promise<T | null> {
  try {
    const almostThere = await AsyncStorage.getItem(key)
    return JSON.parse(almostThere ?? "")
  } catch {
    return null
  }
}
```

**Comment by frankcalise** [comment]
Nice idea, thank you! Implemented for the next version in #2660
