### ISSUE TITLE
Typescript broken with mobx state tree

### ISSUE THREAD

**Issue by vantuan88291** [infinitered/ignite#2668]
### Describe the bug

I dont know why ts always got error like this:
<img width="634" alt="Screenshot 2024-04-18 at 20 10 20" src="https://github.com/infinitered/ignite/assets/9206731/f4ce8954-3045-45a1-9822-660432ce5971">
Still work as normal but ts broken, please help

### Ignite version

9.6.3

### Additional info

System
  platform           darwin
  arch               arm64
  cpu                8 cores      Apple M1 Pro
  directory          paradise     /Users/vantuan88291/code/reactnative/paradise

JavaScript (and globally-installed packages)
  node               18.17.1      /opt/homebrew/opt/node@18/bin/node
  npm                9.6.7        /opt/homebrew/opt/node@18/bin/npm
    appcenter-cli    2.14.0
    code-push-cli    3.0.0
    corepack         0.18.0
    eas-cli          0.59.0
    expo-cli         6.0.1
    npm              9.6.7
    yarn             1.22.18
  yarn               1.22.22      /Users/vantuan88291/code/reactnative/paradise/node_modules/.bin/yarn
    ignite-cli       8.8.7
  pnpm               -            not installed
  bun                -            not installed
  expo               50.0.15      managed
  expo global cli    6.0.1        Deprecated: Found 'expo-cli' installed. Please remove it.

Ignite
  ignite-cli         9.6.3        /Users/vantuan88291/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite
  ignite src         build        /Users/vantuan88291/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build

Android
  java               17.0.9       /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
  android home       -            /Users/vantuan88291/Library/Android/sdk

iOS
  xcode              15.1
  cocoapods          1.13.0       /Users/vantuan88291/.rvm/gems/ruby-3.0.0/bin/pod

Tools
  git                git version 2.39.1   /opt/homebrew/bin/git

**Comment by frankcalise** [comment]
Hi @vantuan88291 can  you provide your TypeScript version installed and share what the error is?

**Comment by frankcalise** [comment]
@coolsoftwaretyler does this ring any bells? I know it isn't much to go off of, but figured I'd ask

**Comment by coolsoftwaretyler** [comment]
Nothing really jumps out to me. I don't often use the separate `props` builder call, but I don't see an issue there. Here's a (non-reproducing) reproduction: https://codesandbox.io/p/sandbox/ignite-2668-mg594q?file=%2Fsrc%2Findex.ts%3A16%2C1

I'm using the `withSetPropAction` from [the recipe article](https://mobx-state-tree.js.org/recipes/auto-generated-property-setter-actions), in which I changed some of the TypeScript. But I also do not see an issue [when I switch over to Ignite's version](https://github.com/infinitered/ignite/blob/master/boilerplate/app/models/helpers/withSetPropAction.ts)

**Comment by frankcalise** [comment]
@vantuan88291 have you resolved this issue? Or could you provide some more information
