### ISSUE TITLE
Docs: Add screenshots of each component in docs

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#2671]
It would be really nice to have screenshots of each component, maybe right below the code snippet. Should be relatively simple to add. I recommend hosting the images in [here](https://github.com/infinitered/ir-docs/tree/main/static/img) OR just uploading them to this issue and capturing the URL.

![CleanShot 2024-04-22 at 12 33 46@2x](https://github.com/infinitered/ignite/assets/1479215/b05c4e73-58d3-4f9c-8187-c9579912fbc9)

https://github.com/infinitered/ignite/issues/2667#issuecomment-2070773338_

**Comment by frankcalise** [comment]
@jamonholmgren / @yulolimum  Do you have any suggestions on good screenshot taking for such a thing? I'd normally just ctrl+cmd+shift+4 but they won't be framed nice or even sized I guess.

Or we could just screenshot the showroom screen part of each one I guess

**Comment by jmejiamu** [comment]
Hello @frankcalise  , @jamonholmgren 
I wonder if someone is already working on this issue?
I would like to contribute to it , this would be my idea to share the screenshot for the different components. 
I was thinking to get them from the app template and share  them in a simulator. what do you think or what are your ideas ? 
![simulator_screenshot_90427CE0-ACA5-44E7-BBCB-9B84699BE308-portrait](https://github.com/infinitered/ignite/assets/27458911/512bd778-0f15-4c03-8c2a-80a4afd3e67b)

**Comment by frankcalise** [comment]
@jmejiamu hey thanks for your interest! you are free to take a go at this one.

How they appear in the simulator is fine. I'm thinking maybe in isolation perhaps so other components on the screen don't confuse users.

Other than that, just keep them consistent throughout the documentation so it has a nice feel to it and users know where to look/what to expect.

You will have to also clone down https://github.com/infinitered/ir-docs if you want to see them work locally as they were hosted at https://docs.infinite.red - let us know if you have any issues.

**Comment by frankcalise** [comment]
@jmejiamu are you working on this?

**Comment by frankcalise** [comment]
Ah ok, the docs that should be modified belong in this tepo, not ir-docs.

Sorry for the confusion, you just needed to clone that repo and link these docs so you could see your changes as you would view the doc site

**Comment by jmejiamu** [comment]
@frankcalise I see, sorry I got confused. I will modify work on that again.
