### ISSUE TITLE
[request]: Support RN v0.74

### ISSUE THREAD

**Issue by turker0** [infinitered/ignite#2673]
Would be good to use bridgeless mode by default.
see https://reactnative.dev/blog/2024/04/22/release-0.74

**Comment by jamonholmgren** [comment]
@turker0 We generally follow Expo's adoption cycle for new React Native apps, so keep an eye out, shoudln't be long.

**Comment by frankcalise** [comment]
You can use bridgeless when opting into the new architecture.

0.74 will be available in Ignite when Expo SDK 51 is released, in the mean time you can utilize the beta

You can get started with this command today:

`npx ignite-cli@latest new MyBridgelessApp --experimental=new-arch,expo-next --workflow=cng --yes`
