### ISSUE TITLE
A Better type for styles

### ISSUE THREAD

**Issue by vanenshi** [infinitered/ignite#2680]
what about we use this type instead of exclusively defining the type of style?

```tsx
import { ViewStyle, TextStyle, ImageStyle } from 'react-native';

// Define a custom type to allow only one of the specified types
type ExclusiveStyle<T, U, V> =
  | (T extends U ? never : T extends V ? never : T)
  | (U extends V ? never : U);

// Define NamedStyle as a union of ViewStyle, TextStyle, and ImageStyle
export type NamedStyle = ExclusiveStyle<ViewStyle, TextStyle, ImageStyle>;
```

Here is the result

```tsx
const $text: NamedStyle = {
  borderWidth: 1,
  color: 'red',
  resizeMode: 'center', // Error: Object literal may only specify known properties, and 'resizeMode' does not exist in type 'TextStyle'.
};
```

**Comment by frankcalise** [comment]
Hey could you provide some more context around this?

I couldn't get this to work properly, for example, in the `WelcomeScreen.tsx`.

Changing `$welcomeLogo` over to NamedStyle, it thinks it is a `TextStyle`

Adding `fontFamily` to `$bottomContainer`, it is not underlining it as an error, which is assigned to a View.

**Comment by vanenshi** [comment]
> Hey could you provide some more context around this?
> 
> I couldn't get this to work properly, for example, in the `WelcomeScreen.tsx`.
> 
> Changing `$welcomeLogo` over to NamedStyle, it thinks it is a `TextStyle`
> 
> Adding `fontFamily` to `$bottomContainer`, it is not underlining it as an error, which is assigned to a View.

Hi @frankcalise Yep, I tried to fix the style but had no luck, as you mentioned, it's not detecting the `$welcomeLogo` as `ImageStyle`.  

it's possible to use a simpler style like 
```tsx
export type NamedStyle = ViewStyle | TextStyle | ImageStyle;
```
but I wanted to make sure they stayed separated

**Comment by frankcalise** [comment]
Thanks for the suggestion though, let us know if you ever get that clever attempt from the first try working! It definitely looks interesting if it could work out
