### ISSUE TITLE
Getting Started - the app lands on a blank page

### ISSUE THREAD

**Issue by sanjeevkumarraob** [infinitered/ignite#2694]
### Describe the bug

I am new to react native app development. I followed the ignite getting started and provided all default values in the app setup  questions. When i ran `yarn ios` , it is giving me a blank page application. The documentation shows with component, icons and assets screen shots. But I am not able to see any of them in the demo application.

Am i missing something here? Any help/pointers will be much appreciated.
![Screenshot 2024-06-08 at 8 11 32 PM](https://github.com/infinitered/ignite/assets/2202215/a2214e0c-a9c0-4209-99b8-7927b05e1f1c)
![Screenshot 2024-06-08 at 8 11 26 PM](https://github.com/infinitered/ignite/assets/2202215/4f48d6c9-6f30-40a4-be61-5b4401ebb29e)

### Ignite version

9.7.0

### Additional info

```
sanjeevkumar@MacBook-Pro PizzaApp % npx ignite-cli doctor
System
  platform           darwin                                                                    
  arch               x64                                                                       
  cpu                8 cores      Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz                   
  directory          PizzaApp     /Users/sanjeevkumar/apps/react_native/PizzaApp 

JavaScript (and globally-installed packages)
  node               21.6.2       /usr/local/bin/node 
  npm                10.8.1       /usr/local/bin/npm  
    @angular/cli     10.0.0                           
    @ionic/cli       7.2.0                            
    @xata.io/cli     0.15.8                           
    cordova-res      0.15.1                           
    cordova          10.0.0                           
    corepack         0.24.0                           
    firebase-tools   8.16.2                           
    gatsby-cli       5.10.0                           
    ios-deploy       1.10.0                           
    n                9.1.0                            
    native-run       1.2.2                            
    npm              10.8.1                           
    react-devtools   5.0.0                            
    yarn             1.22.19                          
  yarn               1.22.19      /usr/local/bin/yarn 
  pnpm               -            not installed       
  bun                -            not installed       
  expo               51.0.11      managed             

Ignite
  ignite-cli         9.7.0        /Users/sanjeevkumar/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/sanjeevkumar/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               15.0.1       /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              15.4       
  cocoapods          1.15.2       /usr/local/bin/pod 

Tools
  git                git version 2.39.3 (Apple Git-146)   /usr/bin/git 
```

**Comment by sanjeevkumarraob** [comment]
I think the issue is missing watchman. As a newbie to app development, this one was a complete miss and there is no mention of this anywhere in the document. 

for any noob out there in the universe, facing the same issue, please run this command 

```
brew install watchman

```
and then run `yarn ios`

**Comment by frankcalise** [comment]
Thanks for the report @sanjeevkumarraob - you have it working now?

I can't see why watchman would matter here in the case of Expo Go, but I could be wrong as it is recommended in the [Get Started for Expo](https://docs.expo.dev/get-started/set-up-your-environment/?platform=ios&device=simulated).

Historically Ignite hasn't been for a super beginner, so thanks for pointing out where the docs fall short. We'll update the guide to make sure you've done the recommended Environment Setup by Meta and Expo

**Comment by frankcalise** [comment]
I actually think this is a font loading issue, try to apply these changes and see if it clears up for you - #2695

**Comment by louielyl** [comment]
> I actually think this is a font loading issue, try to apply these changes and see if it clears up for you - #2695

The fix works, thank you @frankcalise !

FYI my build worked once if I used the Expo Go, but it never worked with the following config:

      npx ignite-cli new PizzaApp \
        --bundle=com.recallable \
        --git \
        --install-deps \
        --packager=yarn \
        --target-path=MYPATH \
        --remove-demo=false \
        --workflow=cng \
        --no-timeout=false

Hope it helps!

**Comment by sanjeevkumarraob** [comment]
@frankcalise This fix worked fine! I uninstalled watchman and recreated the app and it worked perfectly fine on the first run along with these changes.

**Comment by frankcalise** [comment]
Thanks @louielyl and @sanjeevkumarraob I will get it merged soon. Appreciate the help and feedback
