### ISSUE TITLE
expo 51 EAS build failing on iOS

### ISSUE THREAD

**Issue by Janendran** [infinitered/ignite#2706]
### Describe the bug

[RUN_FASTLANE] ▸ ** ARCHIVE FAILED **
[RUN_FASTLANE] ▸ The following build commands failed:
[RUN_FASTLANE] ▸ SwiftCompile normal arm64 Compiling\ noop-file.swift /var/folders/xr/37snnd7d1275sdjnphp8p28c0000gn/T/eas-build-local-nodejs/9729f3db-6d12-46d4-aa00-c1cfd59002fd/build/iOS/xxx/noop-file.swift (in target 'xxx' from project 'xxx')
[RUN_FASTLANE] ▸ SwiftCompile normal arm64 /var/folders/xr/37snnd7d1275sdjnphp8p28c0000gn/T/eas-build-local-nodejs/9729f3db-6d12-46d4-aa00-c1cfd59002fd/build/iOS/xxx/noop-file.swift (in target 'xxx' from project 'xxx')
[RUN_FASTLANE] ▸ SwiftCompile normal arm64 /Users/xxx/Library/Developer/Xcode/DerivedData/xxx-fynpvwcehmfobngujoedeivujnxz/Build/Intermediates.noindex/ArchiveIntermediates/xxx/IntermediateBuildFilesPath/xxx.build/Release-iphoneos/xxx.build/DerivedSources/GeneratedAssetSymbols.swift (in target 'xxx' from project 'xxx')
[RUN_FASTLANE] ▸ SwiftCompile normal arm64 /var/folders/xr/37snnd7d1275sdjnphp8p28c0000gn/T/eas-build-local-nodejs/9729f3db-6d12-46d4-aa00-c1cfd59002fd/build/ios/Pods/Target\ Support\ Files/Pods-xxx/ExpoModulesProvider.swift (in target 'xxx' from project 'xxx')
[RUN_FASTLANE] ▸ (4 failures)
[RUN_FASTLANE] ** ARCHIVE FAILED **

### Ignite version

9.7.1 

### Additional info

System
  platform           darwin                                                          
  arch               arm64                                                           
  cpu                8 cores          Apple M1 Pro                                   
  directory          ObservationApp   /Users/xxx/ObservationApp 

JavaScript (and globally-installed packages)
  node                22.4.1       /opt/homebrew/bin/node 
  npm                 10.8.1       /opt/homebrew/bin/npm  
    @expo/ngrok       4.1.0                               
    create-expo-app   2.1.1                               
    eas-cli           10.1.1                              
    lodash            4.17.21                             
    n                 9.2.0                               
    npm               10.8.1                              
    react-devtools    4.28.0                              
  yarn                1.22.19      /opt/homebrew/bin/yarn 
  pnpm                -            not installed          
  bun                 -            not installed          
  expo                51.0.20      managed                

Ignite
  ignite-cli         9.7.1        /Users/xx/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/xxx/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               17.0.11      /usr/bin/java 
  android home       -            undefined     

iOS
  xcode              15.4       
  cocoapods          1.15.2       /opt/homebrew/bin/pod 

Tools
  git                git version 2.39.3 (Apple Git-146)   /usr/bin/git

**Comment by frankcalise** [comment]
Hi @Janendran sorry you're having troubles.

Can you provide some more information? What ignite options did you start the project with and what command are you using to make your build that is failing?

I can't reproduce this issue

**Comment by Janendran** [comment]
✅ Do you want to use Expo? · Expo
✅ Which Expo workflow? (You can switch between them later with a little work -- here's how: https://ignitecookbook.com/docs/recipes/SwitchBetweenExpoGoCNG) · Expo Go

✅ Do you want to initialize a git repository? (Y/n) · Yes
✅ Remove demo code? We recommend leaving it in if it's your first time using Ignite (y/N) · Yes
✅ Which package manager do you want to use? · npm
✅ Do you want to install dependencies? (Y/n) · Yes


failing on eas build --profile production --platform ios

**Comment by frankcalise** [comment]
@Janendran can you paste a snippet with the failure from EAS?

**Comment by Janendran** [comment]
@frankcalise 
[RUN_FASTLANE] ** ARCHIVE FAILED **
[RUN_FASTLANE] 
[RUN_FASTLANE] 
[RUN_FASTLANE] The following build commands failed:
[RUN_FASTLANE] 	SwiftEmitModule normal arm64 Emitting\ module\ for\ Observation (in target 'Observation' from project 'Observation')
[RUN_FASTLANE] 	SwiftCompile normal arm64 /Users/username/Library/Developer/Xcode/DerivedData/Observation-efmwtjejxaecyegcnlwxmnvapxpi/Build/Intermediates.noindex/ArchiveIntermediates/Observation/IntermediateBuildFilesPath/Observation.build/Release-iphoneos/Observation.build/DerivedSources/GeneratedAssetSymbols.swift (in target 'Observation' from project 'Observation')
[RUN_FASTLANE] 	SwiftCompile normal arm64 Compiling\ ExpoModulesProvider.swift /var/folders/xr/37snnd7d1275sdjnphp8p28c0000gn/T/eas-build-local-nodejs/ce2f2db6-8bf1-4f36-9b7b-11d010152eae/build/ios/Pods/Target\ Support\ Files/Pods-Observation/ExpoModulesProvider.swift (in target 'Observation' from project 'Observation')
[RUN_FASTLANE] 	SwiftCompile normal arm64 /var/folders/xr/37snnd7d1275sdjnphp8p28c0000gn/T/eas-build-local-nodejs/ce2f2db6-8bf1-4f36-9b7b-11d010152eae/build/ios/Pods/Target\ Support\ Files/Pods-Observation/ExpoModulesProvider.swift (in target 'Observation' from project 'Observation')
[RUN_FASTLANE] (4 failures)
[RUN_FASTLANE] Exit status: 65

**Comment by frankcalise** [comment]
@Janendran is this a standard new ignite project or have you added dependencies?

Can you paste your `package.json` contents?

This doesn't seem like an Ignite issue at first glance, if it's specific to Expo you can post [there](https://github.com/expo/expo) or find help in their [discord](https://discord.com/invite/expo)

**Comment by Janendran** [comment]
@frankcalise thanks, this is a standard new ignite

{
  "name": "observation",
  "version": "0.0.1",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "compile": "tsc --noEmit -p . --pretty",
    "format": "prettier --write \"app/**/*.{js,jsx,json,md,ts,tsx}\"",
    "lint": "eslint App.tsx app test --fix --ext .js,.ts,.tsx && npm run format",
    "patch": "patch-package",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:maestro": "maestro test .maestro/FavoritePodcast.yaml",
    "adb": "adb reverse tcp:9090 tcp:9090 && adb reverse tcp:3000 tcp:3000 && adb reverse tcp:9001 tcp:9001 && adb reverse tcp:8081 tcp:8081",
    "postinstall": "patch-package",
    "bundle:visualize": "npx react-native-bundle-visualizer",
    "bundle:visualize:dev": "npx react-native-bundle-visualizer --dev",
    "build:ios:sim": "eas build --profile development --platform ios --local",
    "build:ios:dev": "eas build --profile development:device --platform ios --local",
    "build:ios:prod": "eas build --profile production --platform ios --local",
    "build:android:sim": "eas build --profile development --platform android --local",
    "build:android:dev": "eas build --profile development:device --platform android --local",
    "build:android:prod": "eas build --profile production --platform android --local",
    "start": "npx expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "npx expo start --web",
    "bundle:web": "npx expo export --platform web",
    "serve:web": "npx server dist",
    "prebuild:clean": "npx expo prebuild --clean"
  },
  "dependencies": {
    "@expo-google-fonts/space-grotesk": "^0.2.2",
    "@expo/metro-runtime": "~3.2.1",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.0.2",
    "@shopify/flash-list": "1.6.4",
    "apisauce": "3.0.1",
    "date-fns": "^2.30.0",
    "expo": "~51.0.8",
    "expo-build-properties": "~0.12.1",
    "expo-font": "~12.0.5",
    "expo-linking": "~6.3.1",
    "expo-localization": "~15.0.3",
    "expo-splash-screen": "~0.27.4",
    "expo-status-bar": "~1.12.1",
    "i18n-js": "3.9.2",
    "mobx": "6.10.2",
    "mobx-react-lite": "4.0.5",
    "mobx-state-tree": "5.3.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.3",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0",
    "@babel/plugin-transform-arrow-functions": "^7.0.0",
    "@babel/plugin-transform-shorthand-properties": "^7.0.0",
    "@babel/plugin-transform-template-literals": "^7.0.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@types/i18n-js": "3.8.2",
    "@types/jest": "^29.2.1",
    "@types/react": "~18.2.14",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.59.0",
    "@typescript-eslint/parser": "^5.59.0",
    "babel-jest": "^29.2.1",
    "eslint": "8.17.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-config-standard": "17.0.0",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-n": "^15.0.0",
    "eslint-plugin-promise": "6.0.0",
    "eslint-plugin-react": "7.30.0",
    "eslint-plugin-react-native": "4.0.0",
    "eslint-plugin-reactotron": "^0.1.2",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.2",
    "patch-package": "6.4.7",
    "postinstall-prepare": "1.0.1",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "reactotron-core-client": "^2.8.13",
    "reactotron-mst": "^3.1.7",
    "reactotron-react-js": "^3.3.11",
    "reactotron-react-native": "^5.0.5",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.2",
    "typescript": "~5.3.3"
  },
  "engines": {
    "node": ">=18"
  },
  "prettier": {
    "printWidth": 100,
    "semi": false,
    "singleQuote": false,
    "trailingComma": "all"
  },
  "eslintConfig": {
    "root": true,
    "parser": "@typescript-eslint/parser",
    "extends": [
      "plugin:@typescript-eslint/recommended",
      "plugin:react/recommended",
      "plugin:react-native/all",
      "standard",
      "prettier"
    ],
    "plugins": [
      "@typescript-eslint",
      "react",
      "react-native",
      "reactotron"
    ],
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "settings": {
      "react": {
        "pragma": "React",
        "version": "detect"
      }
    },
    "globals": {
      "__DEV__": false,
      "jasmine": false,
      "beforeAll": false,
      "afterAll": false,
      "beforeEach": false,
      "afterEach": false,
      "test": false,
      "expect": false,
      "describe": false,
      "jest": false,
      "it": false
    },
    "rules": {
      "@typescript-eslint/ban-ts-ignore": 0,
      "@typescript-eslint/ban-ts-comment": 0,
      "@typescript-eslint/explicit-function-return-type": 0,
      "@typescript-eslint/explicit-member-accessibility": 0,
      "@typescript-eslint/explicit-module-boundary-types": 0,
      "@typescript-eslint/indent": 0,
      "@typescript-eslint/member-delimiter-style": 0,
      "@typescript-eslint/no-empty-interface": 0,
      "@typescript-eslint/no-explicit-any": 0,
      "@typescript-eslint/no-object-literal-type-assertion": 0,
      "@typescript-eslint/no-var-requires": 0,
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          "argsIgnorePattern": "^_",
          "varsIgnorePattern": "^_"
        }
      ],
      "comma-dangle": 0,
      "multiline-ternary": 0,
      "no-undef": 0,
      "no-unused-vars": 0,
      "no-use-before-define": 0,
      "no-global-assign": 0,
      "quotes": 0,
      "react-native/no-raw-text": 0,
      "react/no-unescaped-entities": 0,
      "react/prop-types": 0,
      "space-before-function-paren": 0,
      "reactotron/no-tron-in-production": "error"
    }
  }
}

**Comment by frankcalise** [comment]
@Janendran curious have you tried to build it on EAS cloud?

Some other local things to think about:
- did you rename your project or is there some mismatch in your app.json? the build log says `Observation` but your package json says `testApp` so if `app.json` has a mismatch somewhere that could be an issue

- open Xcode and log into your developer account? building prod will do code signing and might be getting hung up there
