### ISSUE TITLE
patch-package version is too old 

### ISSUE THREAD

**Issue by keponk** [infinitered/ignite#2712]
Current version in the boilerplate is :
`"patch-package": "6.4.7"`

Current upstream version is `8.0.0`

The issue is that the `6.x` version is not compatible with the latest npm lockfile version (version 3) and running `npm run patch` on any package that has nested packages (i.e. `@expo/cli` ) will fail.

**Comment by frankcalise** [comment]
@keponk thanks for the find! mind opening a PR?

**Comment by keponk** [comment]
@frankcalise  PR ready

**Comment by frankcalise** [comment]
Completed by #2713
