### ISSUE TITLE
Can't new a ignite project on windows 7

### ISSUE THREAD

**Issue by LucasZheng** [infinitered/ignite#273]
When I new a project on windows, I encounter issues as below:

>  Igniting zq
        Found react-native
        Missing git

then it quit the install process, the folder is empty. I had installed `Git-2.9.2-32-bit` in my computer, I don't know why it always get this error.

**Comment by GantMan** [comment]
if you type `git` in the command line, does it work?

**Comment by LucasZheng** [comment]
@GantMan , yes, it works. It will print some git information.

**Comment by skellock** [comment]
If I remember, a standard windows install of git doesn't put it on the path.

Instead, it embeds a Bash shell that you're asked to click on.

@LucasZheng :  If you type Win+R and `cmd.exe`  and then type `git`, do you see it there?  That's essential what Ignite is doing.

**Comment by LucasZheng** [comment]
@GantMan @skellock , I successfully created a ignite project after I restarted my computer. But when I run `react-native run-android` in my new project folder, I got an error: `Android project not found. Maybe run react-native android first?`. I had installed react native and android studio follow the guide of official site.

**Comment by skellock** [comment]
Sounds like perhaps you didn't actually get all the steps done completed?  Or maybe you're in the wrong directory?

You should be in the directory that was created.  It should have a `package.json` file, `node_modules` sub directory, and you should also see a `android` sub directory.

Is that what you see?

**Comment by GantMan** [comment]
@LucasZheng - I'm glad your git situation is fixed.   Perhaps you could share some documentation to help windows 10 users in the future :)

As for "Android project not found", look for an android folder as @skellock mentioned.  This will tell us where you're at.

**Comment by LucasZheng** [comment]
@skellock , unfortunately, there is no `android` sub directory. I don't know why? I waited for a long long time to `new` a project, and there is no error after all the process done.

**Comment by skellock** [comment]
Are you able to run `ignite doctor` and paste what you see for us please?

**Comment by GantMan** [comment]
you may need to run `ignite doctor` from a different folder.   Due to a current bug.

**Comment by LucasZheng** [comment]
@skellock @GantMan 

```
Computer
  Platform: win32

Ignite
  Version: 1.4.0
  Path: C:\USERS\LUCAS\APPDATA\ROAMING\NPM\IGNITE.CMD

Node
  Version: v6.3.1
  Path: C:\PROGRAM FILES\NODEJS\NODE.EXE

NPM
  Version: 3.10.3
  Path: C:\PROGRAM FILES\NODEJS\NPM.CMD

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: ¯\_(ツ)_/¯
```

**Comment by skellock** [comment]
Looks great.  Let's see if we can rule out `ignite`.  Can you run `react-native init WithoutIgnite`?  Will take a few moments to run, but at the end, you should be able to:

```
cd WithoutIgnite
react-native run-android
```

**Comment by LucasZheng** [comment]
@skellock  still installing. But I only see `package.json` file and `node_modules` sub directory in the `WithoutIgnite ` folder. I will tell you the result after I run `react-native run-android` when init process done.

**Comment by LucasZheng** [comment]
@skellock , all the functionalities work now, thanks for your help.
