### ISSUE TITLE
renderRightButton doesn't work - Want to have Hamburger icon on all screens

### ISSUE THREAD

**Issue by sudharsan1988** [infinitered/ignite#275]
Thanks to @GantMan for making the navigation bar easy to modify. However, I ran into some issues.

I tried to move the Hamburger icon to Right side on all screens with "renderRightButton={NavItems.hamburgerButton}" but it didn't show up on the right side but it was hidden or something. And the default Hamburger icon from react-native-router-flux was shown on left side of initial scene. I also try to hide the default icon but couldn't figure out how to do it even after I went through react-native-router-flux. Not sure, this issue is in Ignite 1.4.1 or react-native-router-flux

Any help would be much appreciated.
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

**Comment by sudharsan1988** [comment]
I would like to include one more point to this issue here,

Whenever we use "renderRightButton" on any scenes, it renders the button on left side instead of right side. So, in this case, we have two buttons on the left side.

**Comment by GantMan** [comment]
Most of this is RNRF, but definitely should be solved in Ignite, as a set of best practices.   We'll have a look at it soon!

**Comment by juancabraal** [comment]
I had the same issue this week,

the best approach is to add this on your scene
`renderBackButton={() => false}`

The full example: 
`<Scene key='presentationScreen' component={PresentationScreen} title='iDermato' initial renderBackButton={() => false} />`

**Comment by sudharsan1988** [comment]
@juancabraal , thanks for your help. It worked for me. I used renderLeftButton={() => false} to hide the default hamburger icon from RNRF and added the below style to 'TouchableOpacity' from https://github.com/aksonov/react-native-router-flux/issues/994

<TouchableOpacity onPress={toggleDrawer} style={{ width: 40, height: 40, right: 5, top: 5, position: 'absolute'}}>
        <Icon name='bars'
          size={Metrics.icons.medium}
          color={Colors.snow}
          style={styles.navButtonLeft}
        />
      </TouchableOpacity>

Now I can use renderRightButton={NavItems.hamburgerButton} in any scenes so that I can keep the hamburger on rightside of the navbar throughout the app.

**Comment by GantMan** [comment]
Another good option is a custom nav bar.   I'll be working with @fvonhoven  and @ryanlntn  today to see about making some decent examples in Ignite.
