### ISSUE TITLE
[CLI] Check for react-native install globally and warn

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#276]
The `react-native` package shouldn't be installed globally.  But... well, sometimes it happens.

The `react-native-cli` even checks for this condition & bombs.

Problem is... that's like step 40 of 800 for Ignite.  

It'd be a nice touch to detect this condition and fail early & loudly when we run the ignite cli.

Here's some untested code that may or may not do that:

```js
const cmd = 'npm -s -g ls --depth=0' // lists top level global installed packages
const ohCrap = Shell.exec(cmd, { silent: true }).stdout.indexOf('react-native@') >= 0
```

Perhaps place it early in the startup cycle inside https://github.com/infinitered/ignite/blob/master/ignite-cli/src/index.es

A little bit of background info #138 .

**Comment by ryanlntn** [comment]
Resolved by #314
