### ISSUE TITLE
Dependency Conflict: Unable to Resolve React Version with React-Test-Renderer During Installation

### ISSUE THREAD

**Issue by yashdesai87** [infinitered/ignite#2769]
### Describe the bug

Merely running `npx ignite-cli@latest new guardian-mobile` with all the default options selected causes this issue.

### Ignite version

9.9.1

### Additional info

System
  platform           darwin                               
  arch               arm64                                
  cpu                8 cores      Apple M2                
  directory          htdocs       /Users/user/htdocs 

JavaScript (and globally-installed packages)
  node               21.7.1       /Users/user/Library/Application Support/Herd/config/nvm/versions/node/v21.7.1/bin/node 
  npm                10.5.0       /Users/user/Library/Application Support/Herd/config/nvm/versions/node/v21.7.1/bin/npm  
    corepack         0.25.2                                                                                                   
    npm              10.5.0                                                                                                   
  yarn               -            not installed                                                                               
  pnpm               -            not installed                                                                               
  bun                -            not installed                                                                               
  expo               -            not installed                                                                               

Ignite
  ignite-cli         9.9.1        /Users/user/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /Users/user/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               -            not installed 
  android home       -            undefined     

iOS
  xcode              15.4       
  cocoapods          Not installed    

Tools
  git                git version 2.39.3 (Apple Git-146)   /usr/bin/git

**Comment by frankcalise** [comment]
Duplicate of https://github.com/infinitered/ignite/issues/2747

Please use yarn for now or install with the legacy peer deps flag as the above issue mentions

**Comment by yashdesai87** [comment]
Thank you. Using yarn worked.
