### ISSUE TITLE
Route Definition not added in NavigationRouter upon new Screen generation

### ISSUE THREAD

**Issue by waqas19921** [infinitered/ignite#277]
Route Definition not added in `NavigationRouter` upon new Screen generation
using command `ignite generate screen`

**Comment by GantMan** [comment]
yes, you are correct.   When we switched router we wanted to wait a bit before we determined what the behavior should be.   This seems like a good place to open for that discussion.

So when someone does `ignite generate screen` what would be the IDEAL experience?   What questions would the best for the generator to ask you?   What file output would be best?   Probably even stubbing a test, right!?

Let's identify this task now that RNRF is in place.

CC: @ryanlntn @skellock @leonskim @kevinvangelder @fvonhoven

**Comment by DavidBates** [comment]
Although it was a bit daunting to add my first screen to the nav it made me explore the codebase more and I had a better understanding of the framework. Also, there are times where I would want to generate a screen but not have it added to the nav (an inner page like the listview or listviewgrid in the example app.) It would be nice to have the option to add to nav but I believe adding a screen to navigation is better addressed by a tutorial.

**Comment by DanielMSchmidt** [comment]
I agree with @DavidBates. On a related note, may we add a short note about this part currently not working? I just wondered for some time why there is no route set up.

**Comment by skellock** [comment]
This will be address once we commit to a router.  We've started this journey now with Ignite and `react-navigation`.  Once they're production ready, we'll be looking to hook this up.

**Comment by DanielMSchmidt** [comment]
@skellock Sounds nice 👍
