### ISSUE TITLE
Update contribution/docs template to require testing new/changed app features

### ISSUE THREAD

**Issue by fpena** [infinitered/ignite#2786]
This can be: 
* Another checklist item in the PR template
* Add screenshots if the feature is visible

**Comment by lindboe** [comment]
idea: one way to encourage contributors to test is to add a section to the PR template to request screenshots if the changes are visible in the app

**Comment by frankcalise** [comment]
I would clarify screenshots to be screenshots or video of both "before" and "after" so it's easy for the reviewer to see the difference

**Comment by frankcalise** [comment]
Closed by #2794
