### ISSUE TITLE
Can not connect desktop app reactotron v9.10.1, dev Android, OS Window

### ISSUE THREAD

**Issue by jameheller98** [infinitered/ignite#2787]
### Describe the bug

I can not connect desktop app reactotron v9.10.1 on my Window

### Ignite version

9.10.1

### Additional info

```
System
  platform           win32
  arch               x64
  cpu                20 cores     13th Gen Intel(R) Core(TM) i9-13900H
  directory          Domoco       C:\Users\ASUS\Domoco

JavaScript (and globally-installed packages)
  node                                   20.11.0      C:\Users\ASUS\scoop\apps\nodejs-lts\current\node.EXE
  npm                                    10.2.4       C:\Users\ASUS\scoop\apps\nodejs-lts\current\npm.CMD
    appcenter-cli                        3.0.0
    appcenter                            5.0.1
    react-native-tab-view-reanimated-3   0.3.45
    zmp-cli                              3.15.7
  yarn                                   1.22.19      C:\Users\ASUS\scoop\apps\yarn\current\bin\yarn.CMD
    create-expo-app                      2.1.1
  pnpm                                   -            not installed
  bun                                    -            not installed
  expo                                   51.0.34      managed

Ignite
  ignite-cli         9.10.1       C:\Users\ASUS\scoop\persist\nodejs-lts\cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\ASUS\scoop\persist\nodejs-lts\cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               17.0.9       C:\Users\ASUS\scoop\apps\microsoft17-jdk\current\bin\java.EXE
  android home       -            C:\Users\ASUS\AppData\Local\Android\Sdk

Tools
  git                git version 2.43.0.windows.1   C:\Users\ASUS\scoop\shims\git.EXE
```

**Comment by frankcalise** [comment]
@jameheller98 did you run `yarn adb`? 

https://docs.infinite.red/reactotron/quick-start/react-native/#troubleshooting

**Comment by jameheller98** [comment]
@frankcalise Yes, I'm sure I have run command "yarn adb reverse tcp:9090 tcp:9090", but its not display on desktop app after refresh app from expo

**Comment by frankcalise** [comment]
@jameheller98 I don't have any issues connecting with Ignite 9, Expo 51 and Reactotron 3.7.0 on Windows.

Could you provide a repository to check out with the problem reproduced?

**Comment by jameheller98** [comment]
Okay I using another version reactotron-react-native here dependencies:
```
"devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-transform-arrow-functions": "^7.0.0",
    "@babel/plugin-transform-shorthand-properties": "^7.0.0",
    "@babel/plugin-transform-template-literals": "^7.0.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@testing-library/react-native": "^12.5.2",
    "@types/i18n-js": "3.8.2",
    "@types/jest": "^29.2.1",
    "@types/react": "~18.2.14",
    "@typescript-eslint/eslint-plugin": "^5.59.0",
    "@typescript-eslint/parser": "^5.59.0",
    "babel-jest": "^29.2.1",
    "eslint": "8.17.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-config-standard": "17.0.0",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-n": "^15.0.0",
    "eslint-plugin-promise": "6.0.0",
    "eslint-plugin-react": "7.30.0",
    "eslint-plugin-react-native": "4.0.0",
    "eslint-plugin-reactotron": "^0.1.2",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.2",
    "patch-package": "^8.0.0",
    "postinstall-prepare": "1.0.1",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "reactotron-core-client": "^2.8.13",
    "reactotron-mst": "^3.1.7",
    "reactotron-react-js": "^3.3.11",
    "reactotron-react-native": "^5.0.5",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.2",
    "typescript": "~5.3.3"
  }
  ```
Can you check new version dependencies of new version ignite @frankcalise ?

**Comment by jameheller98** [comment]
https://github.com/user-attachments/assets/6bcd0e7c-0c94-46db-9ba3-4ba127de0ac1

Here video I implement the app with "yarn adb" and "yarn start --reset-cache" and reset app. Althought the desktop app react otron realize real device but connection not linked, so sad :((

**Comment by frankcalise** [comment]
@jameheller98 that Reactotron version is for the desktop app, not the plugins under dependencies.

From your video, it looks like your device is connected to your computer via USB (or emulator) as it shows up in the adb list in Reactotron from what I can tell.

That error you're seeing in the video is not a Reactotron connection issue, it must be related to your app. 

I would ignite a new app via `npx ignite-cli@latest new Example app --yes` and run it on the same device or emulator and see check if that connects.

**Comment by jameheller98** [comment]
@frankcalise okay get me message after the new app connected to react otron and already working. I will wait response of you ⭐

**Comment by frankcalise** [comment]
@jameheller98 if that is working than it is specific to your application. check the Reactotron set up in your app compared to the example.

Without a link to a repository or source code around the set up I can't help much further.

**Comment by jameheller98** [comment]
@frankcalise Okay I will create new project and run example api, after I will response you. Thank a lots of support for me ❤️

**Comment by jameheller98** [comment]
This is repository example I created: https://github.com/jameheller98/example-ignite
And problem is existed, the bottom bar in desktop app react otron still not display connection more.
@frankcalise

**Comment by frankcalise** [comment]
@jameheller98 Sorry for the confusion, but I didn't mean to just post a brand new app created from the Ignite CLI. I have already verified that works.

Some things to try:
1. If you are testing against different application code than posted above, please create a repo with that code. (I'm guessing this based on the video you posted with the mqtt error, which does not look familiar to Ignite's template, but am unsure)
2. If you have started your application with metro before starting Reactotron, make sure you reload the app and then it should connect
3. Maybe you have some specific network settings (firewall, etc) that are preventing the connection

**Comment by jameheller98** [comment]
Okay I think that last things you can help me, so thank you very much support me, I will check suggests of you ⭐

**Comment by frankcalise** [comment]
I think you got this working? Please open an issue on the [Reactotron](https://github.com/infinitered/reactotron/) repository if not
