### ISSUE TITLE
How to remote debug ignite application through Chrome devTools

### ISSUE THREAD

**Issue by LucasZheng** [infinitered/ignite#279]
Hey guys,  
I want to know how to remote dubug `ignite` application on my physical mobile device through Chrome devTools.   
According to this guide: https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/webviews, I might need to add some code as below in a specific java file.  
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
    WebView.setWebContentsDebuggingEnabled(true);
}`  
Could you give me some advice? Thanks.

**Comment by GantMan** [comment]
You should just be able to press Command + D on iOS or Command + M on Android to show the remote debugging console.   Once you do, you'll have a chrome debugging session available.

**Comment by LucasZheng** [comment]
@GantMan , ok, please close this meaningless issue.

**Comment by GantMan** [comment]
Sorry Lucas, you meant on device.  Did you shake the device?   Should be able to debug that way.
