### ISSUE TITLE
Ignite-cli generate app-icon is not generating icons android

### ISSUE THREAD

**Issue by KartikDevarde2601** [infinitered/ignite#2792]
### Describe the bug

 i update the file according to the doc [https://github.com/infinitered/ignite/blob/master/docs/concept/Generators.md](url) but it not generate the or replace the native res folder icons in android it just update  the  app/asset/* only .
![Screenshot from 2024-09-28 19-21-01](https://github.com/user-attachments/assets/67a3e0e5-7acf-4f62-bd03-573de7b9190a)

### Ignite version

9.10.1

### Additional info

kartik@kartik-the-coder:~/Documents/GitHub/LodoChamps$ npx ignite-cli doctor
System
  platform           linux                                                  
  arch               x64                                                    
  cpu                4 cores      Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz 
  directory          LodoChamps   /home/kartik/Documents/GitHub/LodoChamps  

JavaScript (and globally-installed packages)
  node                 22.6.0       /home/kartik/.nvm/versions/node/v22.6.0/bin/node 
  npm                  10.8.2       /home/kartik/.nvm/versions/node/v22.6.0/bin/npm  
    corepack           0.29.3                                                        
    npm                10.8.2                                                        
    yarn               1.22.22                                                       
  yarn                 1.22.22      /home/kartik/.nvm/versions/node/v22.6.0/bin/yarn 
    icon-set-creator   1.2.6                                                         
  pnpm                 -            not installed                                    
  bun                  -            not installed                                    
  expo                 51.0.34      managed                                          

Ignite
  ignite-cli         9.10.1       /home/kartik/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /home/kartik/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

Android
  java               17.0.11      /home/kartik/.sdkman/candidates/java/current/bin/java 
  android home       -            /home/kartik/Android/Sdk                              

Tools
  git                git version 2.34.1   /usr/bin/git

**Comment by KartikDevarde2601** [comment]
the issue is raise previous but it close #2367

**Comment by frankcalise** [comment]
hi @KartikDevarde2601 - there is no need with Ignite 9+ to generate any other icons than the ones that you see there. Upon generating your build, all of the assets optimized for each device type will be generated.

You can read more about it here: https://docs.expo.dev/tutorial/configuration/#app-icon

If you are using your own bare RN project or an older version of Ignite, you'll want to `npx ignite-cli@8.11.3` or something in the version 8 range to be able to generate android/ios assets specifically.

**Comment by KartikDevarde2601** [comment]
thank you @frankcalise for help.
