### ISSUE TITLE
init project run ios

### ISSUE THREAD

**Issue by hoangcuong22** [infinitered/ignite#2797]
### Describe the bug

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'DevMenu' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","Timing","AppState","SourceCode","BlobModule","WebSocketModule","SettingsManager","DevSettings","RedBox","Networking","Appearance","DevLoadingView","UIManager","DeviceInfo","ImageLoader","LinkingManager","RNGestureHandlerModule","I18nManager","AsyncLocalStorage"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","BugReporting","HeadlessJsTaskSupport","SoundManager","IntentAndroid","PlatformLocalStorage","RNC_AsyncSQLiteDBStorage","RNCAsyncStorage","AsyncSQLiteDBStorage","DevMenu"]}, js engine: hermes

### Ignite version

"9.10.1"

### Additional info

![{B8F04DE9-A3AB-4264-9BAF-C77B51354A6D}](https://github.com/user-attachments/assets/0f0cc0b0-093b-46d5-aa70-61cdecca65fb)

**Comment by hoangcuong22** [comment]
help me

**Comment by theBulmad** [comment]
This DevMenu issue is becoming quite common now, I'm experiencing the same when attempting to use expo go.

**Comment by hoangcuong22** [comment]
I had this problem when running the app on iOS but Android worked fine

**Comment by hoangcuong22** [comment]
Do you have any way to solve it?

**Comment by theBulmad** [comment]
@hoangcuong22 try this:
`yarn expo prebuild -p ios`
`cd ios && pod install`
`yarn ios`

Found it in the ignite slack channel

**Comment by TokenAce** [comment]
Same issue here with new project - Expo Go is a no Go

**Comment by hoangcuong22** [comment]
> @hoangcuong22 try this: `yarn expo prebuild -p ios` `cd ios && pod install` `yarn ios`
> 
> Found it in the ignite slack channel

It's great that it works for my project

**Comment by frankcalise** [comment]
@hoangcuong22 are you running the new architecture?

**Comment by frankcalise** [comment]
Previous discussion around the same issue in https://github.com/infinitered/ignite/issues/2678

Couple of things you can do here:
1. Remove the offending Reactotron custom command [here](https://github.com/infinitered/ignite/blob/master/boilerplate/app/devtools/ReactotronConfig.ts#L50-L58)
2. Utilize Expo CNG
3. Go with `npx ignite-cli@next` (which will use CNG) which should be released this week

But this will not be fixed here as it's related to Expo Go
