### ISSUE TITLE
Lightbox

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#28]
### Make sure verify the following before submitting an issue.
- [x] Issue does not already exist

Add common module https://github.com/oblador/react-native-lightbox

**Comment by GantMan** [comment]
doesn't seem to work with latest React Native?

https://github.com/oblador/react-native-lightbox/issues/31

**Comment by GantMan** [comment]
Looks like there's a fix https://github.com/oblador/react-native-lightbox/issues/31#issuecomment-207234149

My concern is, will this fix be implemented, and the repo maintained?

Might not be a good fit for ignite if the component is staying out of date for so long.

**Comment by GantMan** [comment]
Looks like lightbox is back to working.   We'll consider this when the generator stuff gets involved.

**Comment by skellock** [comment]
I recently worked with a client and they had this component in their app.  It was a constant source of grief unfortunately.
