### ISSUE TITLE
Unable to run development build in iOS 17 

### ISSUE THREAD

**Issue by andresteves** [infinitered/ignite#2813]
### Describe the bug

Tried to create a project using `npx ignite-cli@latest new Testing` and then run `yarn expo run:ios --device` and running on physical device running ios 17 and keeping `Could not load the app: The network connection was lost`.
Node v20.2.0

### Ignite version

v10.0.1

### Additional info

System
  platform           darwin                                                         
  arch               arm64                                                          
  cpu                8 cores      Apple M1

**Comment by morganick** [comment]
@andresteves if you open up Xcode and go to Window -> Devices and Simulators, does your physical device show up there as connected? When you select that device, is "Show run destination" set to "Automatic" or "Always"? Is the device on the same network as the computer?

**Comment by andresteves** [comment]
Yes it shows and also they are on the same wifi network. Run destination is set to `Automatic`.

**Comment by andresteves** [comment]
Also tried to run a quick start using just expo and it works fine with development build.

**Comment by andresteves** [comment]
```
andreesteves@Andres-iMac PetPaly % npx ignite-cli@latest doctor
System
  platform           darwin                                                         
  arch               arm64                                                          
  cpu                8 cores      Apple M1                                          
  directory          PetPaly      /Users/andreesteves/Documents/workspaceRN/PetPaly 

/Users/andreesteves/.npm/_npx/bec2839915ba8fc3/node_modules/gluegun/build/index.js:15
    throw up;
    ^
Usage Error: The 'yarn global' commands have been removed in 2.x - consider using 'yarn dlx' or a third-party plugin instead

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...

(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.2.0
andreesteves@Andres-iMac PetPaly %

**Comment by andresteves** [comment]
Fixed by removing `expo-dev-client` dependency.
