### ISSUE TITLE
Unable to resolve "../../App" from "../../node_modules/expo/AppEntry.js

### ISSUE THREAD

**Issue by KartikDevarde2601** [infinitered/ignite#2815]
### Describe the bug

 **installation**
✅ What bundle identifier? · com.claimeasy
✅ Where do you want to start your project? · /home/kartik/Documents/GitHub/claimEsay/apps/native

✅ How do you want to manage Native code? · CNG
✅ Do you want to initialize a git repository? (Y/n) · No
✅ Remove demo code? We recommend leaving it in if it's your first time using Ignite (y/N) · Yes

✅ Include MobX-State-Tree code? (recommended) (Y/n) · Yes
✅ Which package manager do you want to use? · yarn
✅ Do you want to install dependencies? (Y/n) · Yes
✅ [Experimental] Expo Router for navigation? (y/N) · No
✅ [Experimental] the New Architecture? (y/N) · No
   
![Screenshot_20241019_032959_claimeasy](https://github.com/user-attachments/assets/219b1007-5035-4bc5-9f99-bbee6d87501b)

**Package.Json**

  "name": "claimeasy",
  "version": "0.0.1",
  "private": true,
  "main": "expo/AppEntry.js",
  "scripts": {
    "compile": "tsc --noEmit -p . --pretty",
    "format": "eslint . --fix",
    "lint": "eslint . --fix",
    "lint:check": "eslint .",
    "patch": "patch-package",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:maestro": "maestro test .maestro/FavoritePodcast.yaml",
    "adb": "adb reverse tcp:9090 tcp:9090 && adb reverse tcp:3000 tcp:3000 && adb reverse tcp:9001 tcp:9001 && adb reverse tcp:8081 tcp:8081",
    "postinstall": "patch-package",
    "bundle:visualize": "npx react-native-bundle-visualizer",
    "bundle:visualize:dev": "npx react-native-bundle-visualizer --dev",
    "build:ios:sim": "eas build --profile development --platform ios --local",
    "build:ios:dev": "eas build --profile development:device --platform ios --local",
    "build:ios:prod": "eas build --profile production --platform ios --local",
    "build:android:sim": "eas build --profile development --platform android --local",
    "build:android:dev": "eas build --profile development:device --platform android --local",
    "build:android:prod": "eas build --profile production --platform android --local",
    "start": "npx expo start",
    "android": "npx expo run:android",
    "ios": "npx expo run:ios",
    "web": "npx expo start --web",
    "bundle:web": "npx expo export --platform web",
    "serve:web": "npx server dist",
    "prebuild:clean": "npx expo prebuild --clean"
  },
  "dependencies": {
    "@expo-google-fonts/space-grotesk": "^0.2.2",
    "@expo/metro-runtime": "~3.2.1",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.0.2",
    "@shopify/flash-list": "1.6.4",
    "apisauce": "3.0.1",
    "babel-plugin-module-resolver": "^5.0.2",
    "date-fns": "^4.1.0",
    "expo": "~51.0.8",
    "expo-build-properties": "~0.12.1",
    "expo-dev-client": "~4.0.14",
    "expo-font": "~12.0.5",
    "expo-linking": "~6.3.1",
    "expo-localization": "~15.0.3",
    "expo-splash-screen": "~0.27.4",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "i18next": "^23.14.0",
    "intl-pluralrules": "^2.0.1",
    "mobx": "6.10.2",
    "mobx-react-lite": "4.0.5",
    "mobx-state-tree": "5.3.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^15.0.1",
    "react-native": "0.74.5",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-keyboard-controller": "^1.12.7",
    "react-native-mmkv": "^2.12.2",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@testing-library/react-native": "^12.5.2",
    "@types/jest": "^29.2.1",
    "@types/react": "~18.2.14",
    "babel-jest": "^29.2.1",
    "eslint": "^8.57.0",
    "eslint-config-expo": "^7.1.2",
    "eslint-config-prettier": "^9.1.0",
    "eslint-config-standard": "^17.1.0",
    "eslint-plugin-n": "^17.10.2",
    "eslint-plugin-prettier": "^5.2.1",
    "eslint-plugin-promise": "^7.1.0",
    "eslint-plugin-react-native": "^4.1.0",
    "eslint-plugin-reactotron": "^0.1.2",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.2",
    "patch-package": "^8.0.0",
    "postinstall-prepare": "1.0.1",
    "prettier": "^3.3.3",
    "react-test-renderer": "18.2.0",
    "reactotron-core-client": "^2.8.13",
    "reactotron-mst": "^3.1.7",
    "reactotron-react-js": "^3.3.11",
    "reactotron-react-native": "^5.0.5",
    "reactotron-react-native-mmkv": "^0.2.6",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.2",
    "typescript": "~5.3.3"
  },
  "engines": {
    "node": "^18.18.0 || >=20.0.0"
  }
}

**tsconfig.json**
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "jsx": "react-native",
    "module": "es2015",
    "moduleResolution": "node",
    "strict": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "sourceMap": true,
    "target": "esnext",
    "lib": [
      "esnext",
      "dom"
    ],
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./app/*"],
      "assets/*": ["./assets/*"]
    },
    "typeRoots": [
      "./node_modules/@types",
      "./types"
    ]
  },
  "extends": "expo/tsconfig.base",
  "ts-node": {
    "compilerOptions": {
      "module": "commonjs"
    }
  },
  "include": [
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules",
    "test/**/*"
  ]
}

### Ignite version

10.0.1

### Additional info

**System**
  platform           linux                                                            
  arch               x64                                                              
  cpu                4 cores      Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz           
  directory          native       /home/kartik/Documents/GitHub/claimEsay/apps/native 

**JavaScript (and globally-installed packages)**
  node                 22.6.0                                    /home/kartik/.nvm/versions/node/v22.6.0/bin/node 
  npm                  10.8.2                                    /home/kartik/.nvm/versions/node/v22.6.0/bin/npm  
    corepack           0.29.3                                                                                     
    nodemon            3.1.7                                                                                      
    npm                10.8.2                                                                                     
    turbo              2.1.3                                                                                      
    yarn               1.22.22                                                                                    
  yarn                 1.22.22                                   /home/kartik/.nvm/versions/node/v22.6.0/bin/yarn 
    icon-set-creator   1.2.6                                                                                      
  pnpm                 9.11.0                                    /home/kartik/.local/share/pnpm/pnpm              
                       <no pnpm global package info available>                                                    
  bun                  -                                         not installed                                    
  expo                 51.0.38                                   managed                                          

**Ignite**
  ignite-cli         10.0.1       /home/kartik/.npm/_npx/e31027f3785124a8/node_modules/.bin/ignite      
  ignite src         build        /home/kartik/.npm/_npx/e31027f3785124a8/node_modules/ignite-cli/build 

**Android**
  java               17.0.11      /home/kartik/.sdkman/candidates/java/current/bin/java 
  android home       -            /home/kartik/Android/Sdk                              

**Tools**
  git                git version 2.34.1   /usr/bin/git

**Comment by KartikDevarde2601** [comment]
#2571

**Comment by frankcalise** [comment]
hi @KartikDevarde2601 what command are you using to run the application?

**Comment by KartikDevarde2601** [comment]
hii @frankcalise sorry for late replay  
 i am using **Expo development build**  
yarn run android

**Comment by frankcalise** [comment]
@KartikDevarde2601 so you are running in a turbo monorepo?

**Comment by KartikDevarde2601** [comment]
yes . Is there an example repository available to help set up the Ignite Turbo monorepo? nite Turbo monorepo?

**Comment by frankcalise** [comment]
@KartikDevarde2601 https://github.com/infinitered/react-native-mlkit is a turbo monorepo with an Ignite app inside the `apps/` directory if that is helpful

**Comment by KartikDevarde2601** [comment]
@frankcalise thank you for helping 🙂
