### ISSUE TITLE
Unable to create a project using the cli command "https://github.com/infinitered/ignite/issues/new?template=bug_report.yml&labels=bug"

### ISSUE THREAD

**Issue by ogunwolejo** [infinitered/ignite#2824]
### Describe the bug

3D-printing a new React Native app
    🎨 Getting those last few details perfect
    ❌ Installing yarn dependencies (wow these are heavy)
 -  Gathering system and project details   Unable to gather system and project details.

### Ignite version

npx ignite-cli@latest new PizzaApp

### Additional info

System
  platform           win32
  arch               x64
  cpu                4 cores       Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  directory          play_ground   C:\Users\USER\Documents\Personal\play_ground
C:\Users\USER\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\gluegun\build\index.js:15
    throw up;
    ^

Error: Command failed: pnpm --version
C:\Program Files\nodejs\node_modules\corepack\dist\lib\corepack.cjs:22373
              throw new UsageError(`This project is configured to use ${result.spec.name} because ${result.target} has a "packageManager" field`);
                    ^

UsageError: This project is configured to use yarn because C:\Users\USER\package.json has a "packageManager" field
    at Engine.findProjectSpec (C:\Program Files\nodejs\node_modules\corepack\dist\lib\corepack.cjs:22373:21)
    at async Engine.executePackageManagerRequest (C:\Program Files\nodejs\node_modules\corepack\dist\lib\corepack.cjs:22404:24)
    at async Object.runMain (C:\Program Files\nodejs\node_modules\corepack\dist\lib\corepack.cjs:23096:5) {
  clipanion: { type: 'usage' }
}

Node.js v20.18.0

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'pnpm --version',
  stdout: '',
  stderr: 'C:\\Program Files\\nodejs\\node_modules\\corepack\\dist\\lib\\corepack.cjs:22373\r\n' +
    '              throw new UsageError(`This project is configured to use ${result.spec.name} because ${result.target} has a "packageManager" field`);\r\n' +
    '                    ^\r\n' +
    '\r\n' +
    'UsageError: This project is configured to use yarn because C:\\Users\\USER\\package.json has a "packageManager" field\r\n' +
    '    at Engine.findProjectSpec (C:\\Program Files\\nodejs\\node_modules\\corepack\\dist\\lib\\corepack.cjs:22373:21)\r\n' +
    '    at async Engine.executePackageManagerRequest (C:\\Program Files\\nodejs\\node_modules\\corepack\\dist\\lib\\corepack.cjs:22404:24)\r\n' +
    '    at async Object.runMain (C:\\Program Files\\nodejs\\node_modules\\corepack\\dist\\lib\\corepack.cjs:23096:5) {\r\n' +
    "  clipanion: { type: 'usage' }\r\n" +
    '}\r\n' +
    '\r\n' +
    'Node.js v20.18.0\r\n'
}

Node.js v20.18.0

**Comment by frankcalise** [comment]
@ogunwolejo can you give us some more details about your options you've selected so we can try to reproduce it on Windows? Specifically the packager manager you are trying to utilize as it looks like something is the issue there

**Comment by frankcalise** [comment]
There was a fix published for Windows users via  #2817 in 10.0.2, you can try with that version. `npx ignite-cli@latest`
