### ISSUE TITLE
Sdk 52

### ISSUE THREAD

**Issue by Jacob-CZ** [infinitered/ignite#2847]
Hello I am on the verge of starting a new large app, and would like sdk 52 and primarily the new rn architecture could you bump it please.

**Comment by Hao-yiwen** [comment]
+1

**Comment by frankcalise** [comment]
Hi @Jacob-CZ, there is a PR in progress #2843.

However, you don't need to wait on us to upgrade this boilerplate to start your project, you can easily do it yourself via:

```bash
npx ignite-cli@latest new MyApp
yarn add expo@^52.0.0
npx expo install --fix
```

Enable new arch and run prebuild
