### ISSUE TITLE
Generators do not work with expo navigation

### ISSUE THREAD

**Issue by Jacob-CZ** [infinitered/ignite#2853]
### Describe the bug

The generators, for screens do not work at all but thats understandable, but the components and stores are very inconvenient.

### Ignite version

10.0.0

### Additional info

non relevant

**Comment by frankcalise** [comment]
Hi @Jacob-CZ, thanks for the report. I have a couple of follow up questions to better understand your issue:

1. By expo navigation do you mean expo-router?
2. What was your Ignite new command that you used to generate your project?
3. What was the generator command you used to generate a new component?
4. Can you provide more detail around "do no work" - for example, does it error out? does it not generate what you expect?

Thank you

**Comment by Jacob-CZ** [comment]
Oh yeah im so sorry i forgot to explain, do not work means it puts it in the wrong folder. And i thing the stores are not added to the index export. The commant is the one from the docs using the @latest. Because the new expo router stuff is in src/app and not just app
