### ISSUE TITLE
ignite-cli missing from npm registry

### ISSUE THREAD

**Issue by yimba-ltd** [infinitered/ignite#2863]
### Describe the bug

The ignite-cli seems to have completely vanished from the npm registry
<img width="1501" alt="Screenshot 2024-12-08 at 18 56 10" src="https://github.com/user-attachments/assets/a7009119-a4ba-491f-8c90-fccd83033a6f">

### Ignite version

10.0.5

**Comment by frankcalise** [comment]
Maybe npmjs.com was down for a bit? It's working again - https://www.npmjs.com/package/ignite-cli

![image](https://github.com/user-attachments/assets/514c44af-cbcd-469e-b25b-8542ff699f83)
