### ISSUE TITLE
Add React-Native for windows

### ISSUE THREAD

**Issue by thonymg** [infinitered/ignite#287]
hello, 

This repository adds support for the Windows 10 SDK. Any plan to add this ?

https://github.com/ReactWindows/react-native-windows

**Comment by GantMan** [comment]
Yes!   We're first making our support for Windows developers smooth, then when UWP is mature enough to handle our existing code base, we plan on supporting it 👍

**Comment by thonymg** [comment]
+1

**Comment by nsivraj** [comment]
+1

**Comment by GantMan** [comment]
We'll be looking into this in the next 2 weeks :)

**Comment by semiautomatix** [comment]
Please please please! I'm eager to port my Android app to a Windows 10 IOT running on a PI and would be infinitely grateful if you could add support to what is already a sterling project.

Thanking you in advance :-)

**Comment by leesolway** [comment]
Really looking forward to this feature being implemented.

**Comment by GantMan** [comment]
For those of you looking to do development on Windows for Android, that should be possible right now, btw.

**Comment by semiautomatix** [comment]
I've tried to add Windows support but there are issues especially regarding experimental navigation, any recommendations? I'll try again and provide feedback.

**Comment by skellock** [comment]
@GantMan, @kevinvangelder and @leonskim have been knee deep in Windows + React Native.  It's very possible.  We're going to be shipping 2.0 with Windows support as a target as well.

**Comment by semiautomatix** [comment]
@skellock do with have a 2.0 date yet? Very excited!

**Comment by skellock** [comment]
Hopefully before March 1st.  We're going beta this week.  🎉
