### ISSUE TITLE
Create new project

### ISSUE THREAD

**Issue by duonghungit24** [infinitered/ignite#2873]
how to create a new project that i do not use expo with react native bare

**Comment by frankcalise** [comment]
hey @duonghungit24 you can not do this, we believe Expo gives us the best experience for building apps. You have a couple of options:

1. Copy most of Ignite's file structure, components, etc into your own bare react-native project and remove any dependency related to Expo
2. You can clone this repo which has no Expo dependencies and contains a _similar_ structure to Ignite - https://github.com/frankcalise/ignite-vanilla-template

**Comment by duonghungit24** [comment]
> hey @duonghungit24 you can not do this, we believe Expo gives us the best experience for building apps. You have a couple of options:
> 
> 1. Copy most of Ignite's file structure, components, etc into your own bare react-native project and remove any dependency related to Expo
> 2. You can clone this repo which has no Expo dependencies and contains a _similar_ structure to Ignite - https://github.com/frankcalise/ignite-vanilla-template

I can still use the Ignite CLI to create components and screens, right?

**Comment by frankcalise** [comment]
> 
> 
> 
> 
> > hey @duonghungit24 you can not do this, we believe Expo gives us the best experience for building apps. You have a couple of options:
> > 
> > 1. Copy most of Ignite's file structure, components, etc into your own bare react-native project and remove any dependency related to Expo
> > 2. You can clone this repo which has no Expo dependencies and contains a _similar_ structure to Ignite - https://github.com/frankcalise/ignite-vanilla-template
> 
> I can still use the Ignite CLI to create components and screens, right?

Absolutely yes, you can use the generators. Just add the `ignite/templates` directory to your project and customize your templates

**Comment by duonghungit24** [comment]
> > > hey @duonghungit24 you can not do this, we believe Expo gives us the best experience for building apps. You have a couple of options:
> > > 
> > > 1. Copy most of Ignite's file structure, components, etc into your own bare react-native project and remove any dependency related to Expo
> > > 2. You can clone this repo which has no Expo dependencies and contains a _similar_ structure to Ignite - https://github.com/frankcalise/ignite-vanilla-template
> > 
> > 
> > I can still use the Ignite CLI to create components and screens, right?
> 
> Absolutely yes, you can use the generators. Just add the `ignite/templates` directory to your project and customize your templates

oh thank you, Can you regularly update it to the latest version?

**Comment by frankcalise** [comment]
@duonghungit24 you can always grab the ignite/templates directory for the latest templates or utilize the update command: https://docs.infinite.red/ignite-cli/cli/Ignite-CLI/#update

But often times once you have customized these to your project - you won't want to do this

**Comment by duonghungit24** [comment]
> Refer

yebbb, I will refer to the documentation above.
OTHER:  Unfortunately, I just encountered a freeze on the splash screen on the actual Android device; it still works fine on the virtual device. (I am using the ignite-cli@latest)
