### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by smshuja** [infinitered/ignite#288]
Are you planning on adding Deep Linking? It would be really helpful as most apps these days have this requirement?

References:
https://facebook.github.io/react-native/docs/linking.html
https://www.lullabot.com/articles/navigation-and-deep-linking-with-react-native

**Comment by GantMan** [comment]
Good call!  We'll make this a TODO item.

**Comment by smshuja** [comment]
Any ideas how to do this with the current structure?

**Comment by skellock** [comment]
https://github.com/aksonov/react-native-router-flux/issues/704 looks promising.

**Comment by skellock** [comment]
Ignite 2.0 is looking to ship with `react-navigation` which uses this feature out-of-the-box.

**Comment by samtoya** [comment]
Any update on this please... I need to get this working in my app, it's holding me back for production launch. Any help on this would be greatly appreciated. Thanks.

**Comment by jamonholmgren** [comment]
@samtoya Can you post the results of `ignite doctor` please? If you're still having trouble with it, that is.

**Comment by samtoya** [comment]
I'm unable to run `ignite doctor` successful, I have the ignite video plugin installed.

I'm using ignite-cli@3.1.6 .

Here's my output;

`
Error: Error: Couldn't load command video -- needs a "run" property with a function.

  - command-loader.js:53 Object.loadCommandFromFile
    [lib]/[ignite-cli]/[gluegun]/build/loaders/command-loader.js:53:15

  - plugin-loader.js:40
    [lib]/[ignite-cli]/[gluegun]/build/loaders/plugin-loader.js:40:105

  - Array.map

  - plugin-loader.js:40 Object.loadPluginFromDirectory
    [lib]/[ignite-cli]/[gluegun]/build/loaders/plugin-loader.js:40:59

  - runtime.js:175 Runtime.addPlugin
    [lib]/[ignite-cli]/[gluegun]/build/runtime/runtime.js:175:38

  - runtime.js:204
    [lib]/[ignite-cli]/[gluegun]/build/runtime/runtime.js:204:58

  - Array.map

  - runtime.js:204 Runtime.addPlugins
    [lib]/[ignite-cli]/[gluegun]/build/runtime/runtime.js:204:24

  - builder.js:150
    [lib]/[ignite-cli]/[gluegun]/build/domain/builder.js:150:61

  - Array.forEach


/Users/samtoya/.nvm/versions/node/v10.16.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Error: Couldn't load command video -- needs a "run" property with a function.
    at Object.loadCommandFromFile (/Users/samtoya/.nvm/versions/node/v10.16.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/loaders/command-loader.js:53:15)
    at /Users/samtoya/.nvm/versions/node/v10.16.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/loaders/plugin-loader.js:40:105
    at Array.map (<anonymous>)
    at Object.loadPluginFromDirectory (/Users/samtoya/.nvm/versions/node/v10.16.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/loaders/plugin-loader.js:40:59)
    at Runtime.addPlugin (/Users/samtoya/.nvm/versions/node/v10.16.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/runtime/runtime.js:175:38)
    at /Users/samtoya/.nvm/versions/node/v10.16.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/runtime/runtime.js:204:58
    at Array.map (<anonymous>)
    at Runtime.addPlugins (/Users/samtoya/.nvm/versions/node/v10.16.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/runtime/runtime.js:204:24)
    at /Users/samtoya/.nvm/versions/node/v10.16.0/lib/node_modules/ignite-cli/node_modules/gluegun/build/domain/builder.js:150:61
    at Array.forEach (<anonymous>)
`

**Comment by samtoya** [comment]
@jamonholmgren Here....:


System
  platform           darwin

  arch               x64
  cpu                4 cores                                         Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  directory          /Users/samtoya/Code/TechNation/RN/aftownmusic

JavaScript
  node               10.16.0      /Users/samtoya/.nvm/versions/node/v10.16.0/bin/node
  npm                6.11.3       /Users/samtoya/.nvm/versions/node/v10.16.0/bin/npm
  yarn               1.17.3       /Users/samtoya/.nvm/versions/node/v10.16.0/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.59.9

Ignite
  ignite-cli           3.1.6                                                                                                                                                                                        /Users/samtoya/.nvm/versions/node/v10.16.0/bin/ignite
  createdWith          3.1.5
  boilerplate          ignite-andross
  examples             classic
  navigation           react-navigation
  askToOverwrite       true
  generators           {"component":"ignite-andross","container":"ignite-andross","listview":"ignite-andross","list":"ignite-andross","redux":"ignite-andross","saga":"ignite-andross","screen":"ignite-andross"}
  boilerplateVersion   4.1.0

Android
  java               1.8.0_222    /usr/bin/java
  android home       -            /Users/samtoya/Library/Android/sdk

iOS
  xcode              11.0

**Comment by jamonholmgren** [comment]
Hey @samtoya , please file a new issue on [Ignite Andross](https://github.com/infinitered/ignite-andross). Thanks!

**Comment by samtoya** [comment]
Okay.. @jamonholmgren 

Thanks.
