### ISSUE TITLE
NavigatorExperimental Away Mission

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#29]
`<Navigator>` is sun-setting.

`<NavigatorExperimental>` is transitioning in (the name will change).

I'm hearing nothing but great things about it.  Redux like apparently.

Anyone up for spiking it through before its officially released?   This is my only hesitation in picking a 3rd party library @ryanlntn for Navigation routing & presentation.  

It's all about to change.

**Comment by jamonholmgren** [comment]
The notification email was funny, because it removed the code tags:

<img width="426" alt="screen shot 2016-03-31 at 1 37 03 pm" src="https://cloud.githubusercontent.com/assets/1479215/14190071/ae4c4938-f745-11e5-935d-5a73111512fc.png">

**Comment by skellock** [comment]
is sorry.

is fixed.

:smiley_cat:

**Comment by skellock** [comment]
@GantMan is on this.

**Comment by mmazzarolo** [comment]
Hey @GantMan, are you still working on the Navigation Experimental?  
I've been working on an app that uses almost the same structure of ignite but I always used `react-native-router-flux`... which is a mess since it's last update.  
I was looking for a substitute for the navigation and I'm still undecided between the standard navigation and the experimental one, any hint? :)  
Thank you!

**Comment by GantMan** [comment]
Hey @mmazzarolo :)

I spent a whole 2 days fighting the new Navigation Experimental, and it just wasn't ready.  It hurt so bad!  LOL.   I saw he was updating it every day, so I decided to give it a bit of time and back off.   Now it might be time to come back.  I'll start carving some time to venture off again.   If anyone else wants to take a look, I'm happy to download what I've learned to them.

**Comment by mmazzarolo** [comment]
@GantMan i toyed a bit with it this morning, it *seems* to be working fine in my project (still need to add a drawer and some more tricky routes).  
If you're interested I created [this Gist](https://gist.github.com/mmazzarolo/5a4f235b6b07fa14247c0fb081b1f13f) with my current setup... I'm following most of your coding standard but you should style it a bit (especially `NavigationHeader.js`).  
To navigate between scenes I'm calling `navigatePush('routeName')`, but adding a specific action for each route might be cleaner.

**Disclaimer:** I've stolen and then tweaked all that boilerplate from [here](https://github.com/jlyman/RN-NavigationExperimental-Redux-Example) 🐼

**Comment by GantMan** [comment]
This is awesome, I'll check into this immediately.  Also, this seems like a good opportunity if you want to get your name on the list of contributors to ignite ;)

**Comment by mmazzarolo** [comment]
Yup, I've been a bit hesitant on contributing because I never tried the Ignite app itself, i only used the boilerplate.  
Give me a day of two and I'll probably take a look at it and try to implement the new experimental navigation (I'm still playing with it).

**Comment by mmazzarolo** [comment]
@GantMan, don't know if you're interested but I updated the Gist adding a native toolbar for both iOS and Android and the drawer.  
This navigator seems to be super flexible and I organized all the navigation stuff like in my first file in the Gist, but I'm continuously refactoring it.  

HOWEVER
I'm having some problem resetting the navigation stack (when switching routes from the drawer) and it seems to be a [known issue](https://github.com/ericvicenti/navigation-rfc/issues/50).  
When I'll reach a stable working navigator I'll also dive into the ignite one, if still needed.  

👘

**Comment by GantMan** [comment]
Man, you're my hero.  I was just lining up this weekend to dive deep into re-writing the nav stack.  I think if anything, I'll either hold off, or set the ground for you.

I would love an ignite navigation best practices PR.

**Comment by GantMan** [comment]
@mmazzarolo - Any luck?  I was thinking of taking a swing at this task this week.

**Comment by mmazzarolo** [comment]
@GantMan, nope, I stopped working on it because [currently replacing the stack is buggy, but we should have a fix soon](https://github.com/facebook/react-native/issues/7422).  
If you don't need to reset the screen stack I would still wait a little.

**Comment by GantMan** [comment]
awesome, will wait for a bit :) as per your recommendation.

**Comment by mmazzarolo** [comment]
Just a small update: still no updates.  
Navigation Experimental development seems to be really slow 🎌

**Comment by markrickert** [comment]
> Update: no updates.

:trollface:

**Comment by steve21124** [comment]
The current initial ignite base generator has empty drawer menu. from above discussion
https://gist.github.com/mmazzarolo/5a4f235b6b07fa14247c0fb081b1f13f
https://github.com/caroaguilar/NavigationDrawerExample
http://caroaguilar.com/post/react-native-navigation-tutorial/

did any one has idea which way is a good way to create drawer menu?

**Comment by GantMan** [comment]
We've got drawers working with our current nav, but not with NavigatorExperimental, which is what this ticket is geared towards.

Are you looking fora  good example drawer in the initial ignite base?

**Comment by steve21124** [comment]
yes, I am looking for a good example of drawer menu in ignite base. there are several drawer menu react native. but I just wandering. which one is a good one to use so it integrate nicely to ignite base

**Comment by mmazzarolo** [comment]
@steve21224 I'd go with `react-native-drawer`, it is the most flexible one in my opinion.  
The only issue I've had so far with it is regarding a11y but it might be a corner case.  
It also integrates nicely with the current navigator of Ignite.

**Comment by steve21124** [comment]
good thanks. then I will reuse the react native drawer from http://caroaguilar.com/post/react-native-navigation-tutorial/ then.....

**Comment by steve21124** [comment]
Finally, I got it. my left drawer menu be able to replace the main container page. 
Here what I did. 
1.
<pre>
  _navigate(route) {
      this.navigator.resetTo(route);
      this.navigator.drawer.close();
  }  

  renderDrawerContent () {
    return (
      <View style={{marginTop: 30, padding: 10}}>
        <RoundedButton onPress={() => this._navigate(Routes.PresentationScreen)}>
          Theme Screen
        </RoundedButton>
        <RoundedButton onPress={() => this._navigate(Routes.PresentationScreenB)}>
          Theme Screen
        </RoundedButton>
        <RoundedButton onPress={() => this._navigate(Routes.PresentationScreenC)}>
          Theme Screen
        </RoundedButton>
      </View>
    )
  }
</pre>
and each presentation screen will have it own page. this will integrate nicely with ignite.  
thanks for the help

**Comment by GantMan** [comment]
Awesome @steve21124 

If you'd like to do an example in a PR we'd be happy to accept it.

**Comment by steve21124** [comment]
Thank you. Yes, if I can put some time in writing the tutorial for it. it will let you know. 
This generator so awesome. I just look it yesterday. Now, I feel so productive in creating react native application.

From the ignite readme, I did not see there is generator for menu items. It might be cool. given a list of string array, using command "ignite generate menu 'Screen1,Screen2,Screen3,Screen4'". it will automatically create left drawer menu with the associate screen page from (ignite generate screen ...)

**Comment by GantMan** [comment]
I like that!   Thoughts, @kevinvangelder and @skellock ?

**Comment by GantMan** [comment]
We will need to get ignite on the new navigator ASAP

![image](https://cloud.githubusercontent.com/assets/997157/15476486/dfab9656-20d4-11e6-9095-37a4f2fbe5fa.png)

**Comment by mmazzarolo** [comment]
@gantman, I'll try to submit a basic pr in two data if you're still interested

**Comment by steve21124** [comment]
i think. any pr that help. it will be great

**Comment by mmazzarolo** [comment]
days*, not data  
...and unfortunately I'm too busy with other stuff, hope to take a look at it soon.  
In the meantime if anyone else want to start [this might help](https://gist.github.com/mmazzarolo/5a4f235b6b07fa14247c0fb081b1f13f).  
P.S.: they still haven't fixed the reset issue  (on 0.26.1)

**Comment by GantMan** [comment]
I believe @skellock is slated to attack this this week.

**Comment by sudharsan1988** [comment]
@steve21124 Just followed your instruction to add drawer menu content and that worked nicely but it makes the backbutton not working on the screen when we visit from the drawer menu item.

Is the backbutton working fine for you?

**Comment by sudharsan1988** [comment]
@steve21124 I replaced the below line on the _navigate() function,

this.navigator.resetTo(route); 
to
this.navigator.push(route);  

After made this change, back button works but the transition to the new screen isn't natural when we press the menu item from drawer. I guess, we need to change the transition method for drawer menu items. What do you suggest?

**Comment by ahmed1490** [comment]
useful: http://www.reactnativediary.com/2016/06/23/navigation-examples-1.html

**Comment by GantMan** [comment]
#235 - solves how we're going to handle this.  Going to close this ticket.
