### ISSUE TITLE
How to update react to react@^15.3.0

### ISSUE THREAD

**Issue by juancabraal** [infinitered/ignite#293]
Good morning, every new plugin that I try to install on ignite gives me this messenger

npm WARN react-addons-test-utils@15.3.0 requires a peer of react@^15.3.0 but none was installed.
npm WARN react-dom@15.3.0 requires a peer of react@^15.3.0 but none was installed.

How can I update this dependency?

**Comment by skellock** [comment]
Here's the problem.  `react-native` has a peer-dependency on `react@15.2.1`.   So, if we upgrade our `react` then `react-native` will start triggering that warning.  Hehe.

So, we wait until the next release of `react-native`.  :)

Sorry, that bugs me too.

🍻
