### ISSUE TITLE
Google Maps Workaround?

### ISSUE THREAD

**Issue by CharlieIGG** [infinitered/ignite#294]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [?] ignite base application
  - [ ] ignite the cli
  - [?] ignite generated code

So I realize Google Maps View generator was removed about a month ago because issues, however I really really need to get maps working with this here. I'm trying to use [react-native-maps library](https://github.com/lelandrichardson/react-native-maps)... Somebody mentioned a way they got it working here([#237](https://github.com/infinitered/ignite/pull/237)), but it doesn't work for me. I have started a clean _ignite-less_ react app, followed the install instructions for manual installation of native dependencies, and got it working. However when I try to bring that code to my Ignite-based app and follow the same steps, I get "Unfortunately MyApp has stopped" whenever I try to start the app (app is successfully built tho). **I would seriously appreciate any help.** Thanks!

Also, here's the output from _ignite doctor_:
```
Computer
  Platform: darwin

Ignite
  Version: 1.5.0
  Path: /Users/Charlieigg/.nvm/versions/node/v6.3.0/bin/ignite

Node
  Version: v6.3.0
  Path: /Users/Charlieigg/.nvm/versions/node/v6.3.0/bin/node

NPM
  Version: 3.10.6
  Path: /Users/Charlieigg/.nvm/versions/node/v6.3.0/bin/npm

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.31.0
```

**Comment by skellock** [comment]
Sounds like you have multiple versions of Google's app compat library.

Try this:
```
rm -rf android/build
rm -rf android/app/build
grep appcompat-v **/*.gradle
```

If you run this from your project directory (where your packages.json lives), it should descend into your node_modules and pick up anywhere where 3rd party libs want to use app compat.


![image](https://cloud.githubusercontent.com/assets/68273/17673466/367c3a24-62ef-11e6-9152-ab3bccd2d5f5.png)

**Comment by CharlieIGG** [comment]
TYVM for your answer @skellock. I tried exactly those lines in the root of my project but only get the following output without the mention of appcompat as it show in your screenshot:

```
android/build.gradle:// Top-level build file where you can add configuration options common to all sub-projects/modules.
android/build.gradle:
android/build.gradle:buildscript {
android/build.gradle:    repositories {
android/build.gradle:        jcenter()
android/build.gradle:    }
android/build.gradle:    dependencies {
android/build.gradle:        classpath 'com.android.tools.build:gradle:1.3.1'
android/build.gradle:
android/build.gradle:        // NOTE: Do not place your application dependencies here; they belong
android/build.gradle:        // in the individual module build.gradle files
android/build.gradle:    }
android/build.gradle:}
android/build.gradle:
android/build.gradle:allprojects {
android/build.gradle:    repositories {
android/build.gradle:        mavenLocal()
android/build.gradle:        jcenter()
android/build.gradle:        maven {
android/build.gradle:            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
android/build.gradle:            url "$rootDir/../node_modules/react-native/android"
android/build.gradle:        }
android/build.gradle:    }
android/build.gradle:}
android/settings.gradle:rootProject.name = 'RNTaxi'
android/settings.gradle:
android/settings.gradle:include ':app'
android/settings.gradle:include ':react-native-vector-icons'
android/settings.gradle:project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
android/settings.gradle:include ':react-native-i18n'
android/settings.gradle:project(':react-native-i18n').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-i18n/android')
android/settings.gradle:include ':react-native-device-info'
android/settings.gradle:project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
``` 
Note: I had to type in `grep appcompat -v **/*.gradle` instead of `grep appcompat-v **/*.gradle` to get any output at all. Your help and ideas are appreciated.

**Comment by GantMan** [comment]
Just got 0.31 working with latest maps.  Here's some info, not sure if it's help :)  Always hard to debug without the code on my machine.  I can tell you I had the exact same issue, and I got passed it, but might not remember the exact steps on how.

**From what I'm reading, you're going after Android yes?**

Firstly, make sure you're pointing at master in `package.json` with this:
`"react-native-maps": "git@github.com:lelandrichardson/react-native-maps.git",`
I don't believe they've released since @skellock 's additions.

Next,  be sure to `adb logcat` when you run your project (`react-native log-ios` if you're doing iOS).  This will give you the info you're missing when your app crashes. 

Lastly, close packager, any IDE's and stop debugging and close simulators, then run these commands in this order to destroy any cache.   https://raw.githubusercontent.com/GantMan/mobile-commander/master/bin/newclear.sh
Hopefully, that will clear any ghosts in the machine, if that's the issue.

The above steps will give you some info either fix the issue, or give us some info to chew on.  We'll get this puppy working 👍

**Comment by CharlieIGG** [comment]
Thank you @GantMan, after following your steps it didn't work, but I had no idea `add logcat` existed. After taking a look at the logs, Googling around and testing several different things adding these three lines to the gradle got it working:
   ```
 compile "com.google.android.gms:play-services-base:8.4.0" 
    compile 'com.google.android.gms:play-services-maps:8.4.0'
    compile 'com.google.android.gms:play-services-gam:8.4.0'
```
