### ISSUE TITLE
Ignite base application does not build: could not find play-services-gcm

### ISSUE THREAD

**Issue by nicosaki** [infinitered/ignite#298]
Steps 1 and 2 of running generated app completed (with messages about npmconf and cross-spawn-asynch deprecation).
Step 3: Ran a Genymotion API 23, attempted to build with react-native run-android and received:

>A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-device-info'.
   > Could not resolve all dependencies for configuration ':react-native-device-info:_debugCompile'.
      > Could not find com.google.android.gms:play-services-gcm:8.3.0.

I tried a second time after remembering to change my build.gradle targetSdkVersion to 23 and received the same output. I'm guessing I need to update the play services version to the newest one, but I can't find where I need to do that.

ignite doctor
```
Computer
  Platform: darwin

Ignite
  Version: 1.5.0
  Path: /Users/nicosaki/.npm-packages/bin/ignite

Node
  Version: v6.2.1
  Path: /usr/local/bin/node

NPM
  Version: 3.10.5
  Path: /Users/nicosaki/.npm-packages/bin/npm

Yeoman
  Version: 1.8.4

React Native CLI
  Version: undefined

App
  React Native Version: 0.31.0
```

**Comment by GantMan** [comment]
are you sure you have google play services downloaded with the `android` SDK manager?

Can you screenshot your SDK manager packages for us?

**Comment by nicosaki** [comment]
![image](https://cloud.githubusercontent.com/assets/10930700/17746396/b97e4748-6464-11e6-9848-a16b2d83ba52.png)
![image](https://cloud.githubusercontent.com/assets/10930700/17746414/cc048bac-6464-11e6-9ae9-894601a5f95f.png)

I updated everything on the sdk manger and tried a fresh base build from a new init, to the same result but much faster: Does it cache settings outside of the project folder? 
Maybe my update fixed it but a cache is in the way?
(Apologies for my ignorance, I'm only a few days into learning React Native for my capstone.)

**Comment by nicosaki** [comment]
I fixed it and managed to build it.
However, the moment it's built on my emulator (react-native run-android) it crashes with a simple 'application has stopped' alert on the emulator. No error messages or anything.

**Comment by skellock** [comment]
Can you paste what happens from logcat when you experience this crash?

`adb logcat`

Fire that up.. start your app... and when it crashes, grab a bunch of lines from it.   That'll help narrow down the runtime problem.

**Comment by nicosaki** [comment]
Thank you for the help!
Below is the log from the moment I initiated with react-native run-android
I bolded the first line that looks problematic to my untrained eyes, and the problem seems to have occurred sometime after that point:

08-17 20:32:48.463   696  1583 D NetlinkSocketObserver: NeighborEvent{elapsedMs=132960, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_STALE}
08-17 20:32:53.778  1634  1634 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
08-17 20:32:53.780  1634  1634 D AndroidRuntime: CheckJNI is OFF
08-17 20:32:53.802  1634  1634 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
08-17 20:32:53.819  1634  1634 E memtrack: Couldn't load memtrack module (No such file or directory)
08-17 20:32:53.820  1634  1634 E android.os.Debug: failed to load memtrack module: -2
08-17 20:32:53.821  1634  1634 I Radio-JNI: register_android_hardware_Radio DONE
08-17 20:32:53.836  1634  1634 D AndroidRuntime: Calling main entry com.android.commands.am.Am
08-17 20:32:53.877   696  1123 I UsageStatsService: User[0] Flushing usage stats to disk
08-17 20:32:53.918   696  1123 I UsageStatsDatabase: Time changed by +2s503ms. files deleted: 0 files moved: 6
08-17 20:32:53.931   696  1123 I UsageStatsService: User[0] Rollover scheduled @ 2016-08-18 20:00:00(1471564800000)
08-17 20:32:53.933  1634  1634 D AndroidRuntime: Shutting down VM
08-17 20:32:54.366  1643  1643 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
08-17 20:32:54.367  1643  1643 D AndroidRuntime: CheckJNI is OFF
08-17 20:32:54.378  1643  1643 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
08-17 20:32:54.391  1643  1643 E memtrack: Couldn't load memtrack module (No such file or directory)
08-17 20:32:54.391  1643  1643 E android.os.Debug: failed to load memtrack module: -2
08-17 20:32:54.391  1643  1643 I Radio-JNI: register_android_hardware_Radio DONE
08-17 20:32:54.400  1643  1643 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
08-17 20:32:54.406  1643  1643 I art     : System.exit called, status: 0
08-17 20:32:54.406  1643  1643 I AndroidRuntime: VM exiting with result code 0.
08-17 20:32:54.674  1653  1653 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
08-17 20:32:54.676  1653  1653 D AndroidRuntime: CheckJNI is OFF
08-17 20:32:54.690  1653  1653 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
08-17 20:32:54.706  1653  1653 E memtrack: Couldn't load memtrack module (No such file or directory)
08-17 20:32:54.706  1653  1653 E android.os.Debug: failed to load memtrack module: -2
08-17 20:32:54.707  1653  1653 I Radio-JNI: register_android_hardware_Radio DONE
08-17 20:32:54.719  1653  1653 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
08-17 20:32:54.727   106   106 I installd: free_cache(8888489) avail 13191524352
08-17 20:32:55.301  1653  1653 I art     : System.exit called, status: 0
08-17 20:32:55.301  1653  1653 I AndroidRuntime: VM exiting with result code 0.
08-17 20:32:55.562  1664  1664 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
08-17 20:32:55.564  1664  1664 D AndroidRuntime: CheckJNI is OFF
08-17 20:32:55.584  1664  1664 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
08-17 20:32:55.604  1664  1664 E memtrack: Couldn't load memtrack module (No such file or directory)
08-17 20:32:55.604  1664  1664 E android.os.Debug: failed to load memtrack module: -2
08-17 20:32:55.605  1664  1664 I Radio-JNI: register_android_hardware_Radio DONE
08-17 20:32:55.619  1664  1664 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
08-17 20:32:56.082   696   752 I ActivityManager: Start proc 1673:com.android.defcontainer/u0a4 for service com.android.defcontainer/.DefaultContainerService
08-17 20:32:56.501   696   752 I PackageManager.DexOptimizer: Running dexopt (dex2oat) on: /data/app/vmdl551776877.tmp/base.apk pkg=com.ingredientinspector isa=x86 vmSafeMode=false debuggable=true oatDir = /data/app/vmdl551776877.tmp/oat
**08-17 20:32:56.539  1687  1687 W dex2oat : Unexpected CPU variant for X86 using defaults: x86**
08-17 20:32:56.541  1687  1687 I dex2oat : /system/bin/dex2oat --debuggable
08-17 20:32:56.828  1687  1689 W dex2oat : Before Android 4.1, method int android.support.v7.internal.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
08-17 20:32:59.664  1687  1687 I dex2oat : dex2oat took 3.125s (threads: 4) arena alloc=2MB java alloc=5MB native alloc=28MB free=2MB
08-17 20:32:59.778   696   710 I ActivityManager: Force stopping com.ingredientinspector appid=10060 user=-1: uninstall pkg
08-17 20:32:59.803   696   752 I PackageManager: Package com.ingredientinspector codePath changed from /data/app/com.ingredientinspector-2 to /data/app/com.ingredientinspector-1; Retaining data and using new
08-17 20:32:59.804   696   710 I ActivityManager: Force stopping com.ingredientinspector appid=10060 user=-1: replace pkg
08-17 20:32:59.804   696   752 W PackageManager: Code path for com.ingredientinspector changing from /data/app/com.ingredientinspector-2 to /data/app/com.ingredientinspector-1
08-17 20:32:59.804   696   752 W PackageManager: Resource path for com.ingredientinspector changing from /data/app/com.ingredientinspector-2 to /data/app/com.ingredientinspector-1
08-17 20:32:59.819   696   752 W PackageManager: Unknown permission com.google.android.c2dm.permission.RECEIVE in package com.ingredientinspector
08-17 20:32:59.835   696   752 W Settings: Setting install_non_market_apps has moved from android.provider.Settings.Global to android.provider.Settings.Secure, returning read-only value.
08-17 20:32:59.835   696   752 I art     : Starting a blocking GC Explicit
08-17 20:32:59.849   696   752 I art     : Explicit concurrent mark sweep GC freed 26452(1577KB) AllocSpace objects, 9(252KB) LOS objects, 33% free, 5MB/8MB, paused 327us total 13.209ms
08-17 20:32:59.852   696   752 W PackageManager: Couldn't remove dex file for package:  at location /data/app/com.ingredientinspector-2/base.apk, retcode=-1
08-17 20:32:59.852   106   106 E installd: Couldn't opendir /data/app/vmdl551776877.tmp: No such file or directory
08-17 20:32:59.855  1664  1664 I art     : System.exit called, status: 0
08-17 20:32:59.855  1664  1664 I AndroidRuntime: VM exiting with result code 0.
08-17 20:32:59.855   696   752 I ActivityManager: Force stopping com.ingredientinspector appid=10060 user=0: pkg removed
08-17 20:32:59.860   696   696 D JobSchedulerService: Receieved: android.intent.action.PACKAGE_REMOVED
08-17 20:32:59.873   696   773 I InputReader: Reconfiguring input devices.  changes=0x00000010
08-17 20:32:59.875   696   773 I InputReader: Reconfiguring input devices.  changes=0x00000010
08-17 20:32:59.876   696   773 I InputReader: Reconfiguring input devices.  changes=0x00000010
08-17 20:32:59.886   696   696 V WebViewFactory: webViewPackageName: com.android.webview
08-17 20:32:59.902   696  1097 I ActivityManager: Start proc 1696:com.android.gallery3d/u0a37 for broadcast com.android.gallery3d/.app.PackagesMonitor
08-17 20:32:59.937   696   709 W VoiceInteractionManagerService: no available voice recognition services found for user 0
08-17 20:32:59.961  1070  1070 D CarrierServiceBindHelper: Receive action: android.intent.action.PACKAGE_REMOVED
08-17 20:33:00.042  1070  1070 D CarrierServiceBindHelper: Receive action: android.intent.action.PACKAGE_ADDED
08-17 20:33:00.043  1070  1070 D CarrierServiceBindHelper: Receive action: android.intent.action.PACKAGE_REPLACED
08-17 20:33:00.044  1070  1070 D CarrierServiceBindHelper: mHandler: 3
08-17 20:33:00.044  1070  1070 D CarrierServiceBindHelper: mHandler: 3
08-17 20:33:00.044  1070  1070 D CarrierServiceBindHelper: mHandler: 3
08-17 20:33:00.044  1070  1070 D CarrierConfigLoader: mHandler: 9 phoneId: 0
08-17 20:33:00.099  1392  1392 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1221 android.content.ContextWrapper.startService:581 android.content.ContextWrapper.startService:581 com.android.keychain.KeyChainBroadcastReceiver.onReceive:12 android.app.ActivityThread.handleReceiver:2725 
08-17 20:33:00.141   696   707 I ActivityManager: Start proc 1714:com.svox.pico/u0a50 for broadcast com.svox.pico/.VoiceDataInstallerReceiver
08-17 20:33:00.152   696  1097 I ActivityManager: Killing 1262:com.android.quicksearchbox/u0a53 (adj 15): empty #17
08-17 20:33:00.207   696  1123 I ActivityManager: Start proc 1728:com.android.quicksearchbox/u0a53 for broadcast com.android.quicksearchbox/.SearchWidgetProvider
08-17 20:33:00.209   696  1105 I ActivityManager: Killing 1405:com.android.dialer/u0a5 (adj 15): empty #17
08-17 20:33:00.236  1728  1728 W System  : ClassLoader referenced unknown path: /system/app/QuickSearchBox/lib/x86
08-17 20:33:00.243   696  1123 I ActivityManager: Killing 1448:com.android.managedprovisioning/u0a9 (adj 15): empty #17
08-17 20:33:00.608  1742  1742 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
08-17 20:33:00.609  1742  1742 D AndroidRuntime: CheckJNI is OFF
08-17 20:33:00.633  1742  1742 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
08-17 20:33:00.651  1742  1742 E memtrack: Couldn't load memtrack module (No such file or directory)
08-17 20:33:00.651  1742  1742 E android.os.Debug: failed to load memtrack module: -2
08-17 20:33:00.652  1742  1742 I Radio-JNI: register_android_hardware_Radio DONE
08-17 20:33:00.665  1742  1742 D AndroidRuntime: Calling main entry com.android.commands.am.Am
08-17 20:33:00.670   696   707 I ActivityManager: START u0 {flg=0x10000000 cmp=com.ingredientinspector/.MainActivity} from uid 0 on display 0
08-17 20:33:00.727  1742  1742 D AndroidRuntime: Shutting down VM
08-17 20:33:00.834  1752  1752 I art     : Late-enabling -Xcheck:jni
08-17 20:33:00.839   696   844 I ActivityManager: Start proc 1752:com.ingredientinspector/u0a60 for activity com.ingredientinspector/.MainActivity
08-17 20:33:00.885  1752  1766 I GMPM    : App measurement is starting up
08-17 20:33:00.890  1752  1766 E GMPM    : getGoogleAppId failed with status: 10
08-17 20:33:00.891  1752  1766 E GMPM    : Uploading is not possible. App measurement disabled
08-17 20:33:00.894   696  1085 I ActivityManager: START u0 {act=android.settings.action.MANAGE_OVERLAY_PERMISSION cmp=com.android.settings/.Settings$OverlaySettingsActivity} from uid 10060 on display 0
08-17 20:33:00.902  1752  1752 W unknown:React: Overlay permissions needs to be granted in order for react native apps to run in dev mode
08-17 20:33:00.917  1752  1752 V fb-UnpackingSoSource: locked dso store /data/user/0/com.ingredientinspector/lib-main
08-17 20:33:00.919  1752  1752 V fb-UnpackingSoSource: deps mismatch on deps store: regenerating
08-17 20:33:00.919  1752  1752 V fb-UnpackingSoSource: so store dirty: regenerating
08-17 20:33:00.939  1752  1752 D ApkSoSource: not allowing consideration of lib/x86/libfb.so: deferring to libdir
08-17 20:33:00.940  1752  1752 D ApkSoSource: not allowing consideration of lib/x86/libfolly_json.so: deferring to libdir
08-17 20:33:00.940  1752  1752 D ApkSoSource: not allowing consideration of lib/x86/libglog.so: deferring to libdir
08-17 20:33:00.940  1752  1752 D ApkSoSource: not allowing consideration of lib/x86/libglog_init.so: deferring to libdir
08-17 20:33:00.940  1752  1752 D ApkSoSource: not allowing consideration of lib/x86/libgnustl_shared.so: deferring to libdir
08-17 20:33:00.940  1752  1752 D ApkSoSource: not allowing consideration of lib/x86/libicu_common.so: deferring to libdir
08-17 20:33:00.940  1752  1752 D ApkSoSource: not allowing consideration of lib/x86/libimagepipeline.so: deferring to libdir
08-17 20:33:00.940  1752  1752 D ApkSoSource: not allowing consideration of lib/x86/libjsc.so: deferring to libdir
08-17 20:33:00.940  1752  1752 D ApkSoSource: not allowing consideration of lib/x86/libreactnativejni.so: deferring to libdir
08-17 20:33:00.940  1752  1752 D ApkSoSource: not allowing consideration of lib/x86/libreactnativejnifb.so: deferring to libdir
08-17 20:33:00.940  1752  1752 V fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
08-17 20:33:00.941  1752  1752 V fb-UnpackingSoSource: starting syncer worker
08-17 20:33:00.947  1752  1752 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.ingredientinspector/lib-main (from syncer thread)
08-17 20:33:00.947  1752  1752 V fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.ingredientinspector/lib-main (syncer thread started)
08-17 20:33:01.050  1752  1774 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-17 20:33:01.054  1752  1752 D         : HostConnection::get() New Host Connection established 0xe99f3890, tid 1752
08-17 20:33:01.157  1752  1752 D AndroidRuntime: Shutting down VM
08-17 20:33:01.158  1752  1752 E AndroidRuntime: FATAL EXCEPTION: main
08-17 20:33:01.158  1752  1752 E AndroidRuntime: Process: com.ingredientinspector, PID: 1752
08-17 20:33:01.158  1752  1752 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@9c361db -- permission denied for this window type
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:319)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:587)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl$3$1.run(XReactInstanceManagerImpl.java:397)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-17 20:33:01.158  1752  1752 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-17 20:33:01.168  1090  1280 E Surface : getSlotFromBufferLocked: unknown buffer: 0xe1242f50
08-17 20:33:01.188   696  1777 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-17 20:33:01.291   696  1777 I OpenGLRenderer: Initialized EGL, version 1.4
08-17 20:33:01.291   696  1777 D         : HostConnection::get() New Host Connection established 0xdd57c2a0, tid 1777
08-17 20:33:01.355  1292  1779 W AppStateAppOpsBridge: AppOp permission exists for package android of user 0 but package doesn't exist or did not request [Ljava.lang.String;@19ee9bb access
08-17 20:33:01.488  1292  1781 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-17 20:33:01.493  1292  1292 D         : HostConnection::get() New Host Connection established 0xe8bfb890, tid 1292
08-17 20:33:01.573   696  1777 W EGL_emulation: eglSurfaceAttrib not implemented
08-17 20:33:01.573   696  1777 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdb853be0, error=EGL_SUCCESS
08-17 20:33:01.743  1292  1779 W AppStateAppOpsBridge: AppOp permission exists for package android of user 0 but package doesn't exist or did not request [Ljava.lang.String;@19ee9bb access
08-17 20:33:01.760   106   106 W installd: Failed to open /data/data/android: No such file or directory
08-17 20:33:01.871   696   708 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=0 for 116ms
08-17 20:33:02.033  1292  1781 D libEGL  : loaded /system/lib/egl/libEGL_emulation.so
08-17 20:33:02.035  1292  1781 D libEGL  : loaded /system/lib/egl/libGLESv1_CM_emulation.so
08-17 20:33:02.042  1292  1781 D libEGL  : loaded /system/lib/egl/libGLESv2_emulation.so
08-17 20:33:02.048  1292  1781 D         : HostConnection::get() New Host Connection established 0xeec12510, tid 1781
08-17 20:33:02.321  1292  1781 I OpenGLRenderer: Initialized EGL, version 1.4
08-17 20:33:02.374   696   711 I Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
08-17 20:33:02.477  1292  1781 W EGL_emulation: eglSurfaceAttrib not implemented
08-17 20:33:02.477  1292  1781 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xeec135a0, error=EGL_SUCCESS
08-17 20:33:02.589  1292  1292 I Choreographer: Skipped 50 frames!  The application may be doing too much work on its main thread.
08-17 20:33:02.977   696   715 I ActivityManager: Displayed com.android.settings/.Settings$OverlaySettingsActivity: +1s836ms (total +2s152ms)
08-17 20:33:05.983   696  1583 D NetlinkSocketObserver: NeighborEvent{elapsedMs=150480, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_REACHABLE}
08-17 20:33:13.725   696   710 W ActivityManager: Activity stop timeout for ActivityRecord{a09965b u0 com.ingredientinspector/.MainActivity t8}

**Comment by skellock** [comment]
Window permission error?  Strange.   

* What are you using for a VM?  
* What version of Android (api level)?  
* Does this problem exist with just a fresh `react-native init AndroidApp` or just ignite?
* Are you using any other 3rd party libraries in your app? like ones that have to do with lock screen stuff?

**Comment by nicosaki** [comment]
Genymotion is the emulator I'm using, running API 23 (I've tried two versions of 23 on Geny, same outcome).
Problem exists for fresh react-native init and fresh ignite new.
The app I'm trying to build is a fresh ignite app, whose only change was to the android/app/build.settings targetSdkVersion changed to 23.

**Comment by skellock** [comment]
Can you try creating a new Genymotion app with api 22?  In 23 the permissions system changed drastically, and some googling seems to reveal Android 6 + React Native + Redbox as a potential issue.

We've already ruled out Ignite, so let's see if we can rule out some more.

**Comment by nicosaki** [comment]
It built! Yay!
Thank you for your guidance, I've been struggling with this for far too long.
You are appreciated!
