### ISSUE TITLE
Error: Requiring module "54"

### ISSUE THREAD

**Issue by iztokf** [infinitered/ignite#299]
After successfully deployed base app on android (react-native run-android), i get this error:
![image](https://cloud.githubusercontent.com/assets/4134426/17741306/02654a92-649c-11e6-8109-341219cf83bb.png)

All suggestions how to fix the issue are irrelevant - i can normaly launch and debug my other react native apps. Here's my ignite doctor output:
```
Computer
  Platform: linux

Ignite
  Version: 1.5.0
  Path: /usr/local/bin/ignite

Node
  Version: v6.4.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.3
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.31.0
```

Please help :)

**Comment by GantMan** [comment]
HI @iztokf 

What a wild error!

Are you sure your packager is not out of date, or running a different app?

It looks like your app and your packager are speaking different languages to one another.

**Comment by iztokf** [comment]
you were right. packager was running a different app :S thanks!
