### ISSUE TITLE
How do I put image in Title of the page

### ISSUE THREAD

**Issue by Talkwondo** [infinitered/ignite#300]
Hi,
So I am using your template very useful.
I want to put an image instead of a text. 

How can I do that?

Thanks,

**Comment by jhabdas** [comment]
@Talkwondo You may be in a little over your head and should consider starting from scratch so you can fully grasp the technologies at play here and get the basics down:

https://facebook.github.io/react-native/docs/getting-started.html
https://facebook.github.io/react-native/docs/images.html

Here's an example of adding an image to a new app created using `react-native init`:
https://github.com/jhabdas/lumpen-radio/commit/a9d84f97006fc526c0b0d388a48bc1228d0b703e

**Comment by ryanlntn** [comment]
@Talkwondo You'll need to create a custom nav bar component and assign it in your scenes:
```
<Scene key='myScreen' component={MyScreen} navBar={MyCustomNavBar} />
```
You can find more info here: https://github.com/aksonov/react-native-router-flux

We're planning on adding an example or two to Ignite in the near future.

**Comment by GantMan** [comment]
Done in examples:  https://github.com/infinitered/ignite/blob/36082b0b957b92d2051f1daa9e7b72ed79e84fb5/ignite-base/App/Components/CustomNavBar.js
