### ISSUE TITLE
Clean boilerplate

### ISSUE THREAD

**Issue by nicolasdelfino** [infinitered/ignite#301]
Hi! Awesome work guys!
A nice option would be being able to generate a stripped down bare minimum project like ignite new "name" --min (or something), without all the bells and whistles. Maybe with two generated routes, a start screen and a second screen.

**Comment by skellock** [comment]
Heyo!  This is pretty high on the priority list.  Not just a `--min`, but the ability to answer a few prompts to pick & choose whatcha want.

Ignite 2.0 is going to be this.  :)

**Comment by kevinvangelder** [comment]
@nicolasdelfino This is already outlined in our roadmap: https://github.com/infinitered/ignite/wiki/Roadmap

Thanks!
