### ISSUE TITLE
Drawer - invalid prop type on initial open

### ISSUE THREAD

**Issue by nicolasdelfino** [infinitered/ignite#306]
[x] ignite base application

```
Computer
  Platform: darwin

Ignite
  Version: 1.5.0
  Path: /usr/local/bin/ignite

Node
  Version: v6.2.2
  Path: /usr/local/bin/node

NPM
  Version: 3.9.5
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.31.0
```

Hi, looks like there´s a problem with open={state.open} of Drawer. 

First time you open open the drawer you´ll get this error: 
_**Warning: Failed prop type: Invalid prop `open` of type `function` supplied to `Drawer`, expected `boolean**_

Log of state.open returns undefined first time, then true/false etc...

**Comment by GantMan** [comment]
this should be fixed as of https://github.com/infinitered/ignite/pull/289

See that PR for the fix.
