### ISSUE TITLE
Add example app of what the ignite-cli produces

### ISSUE THREAD

**Issue by rdsteg** [infinitered/ignite#309]
Hey, love the direction you're taking with ignite!  I also love to reference the app's structure and 'best practices'.  I think it would be great if you guys could add a folder/repo that has the base configuration of an ignite app!  I would open a PR, but I'm not sure if you guys want to take that route - do you think this would be viable?

**Comment by rdsteg** [comment]
Ugh, I'm dumb.  It's what ignite-base is, isnt it?  Well, maybe the point is, and I'm the only one, to rename the directory to something like ignite-app?

**Comment by GantMan** [comment]
Add a PR to the readme making this clear and we'll take it 👍 
All feedback is awesome!
