### ISSUE TITLE
make a button on the right navbar

### ISSUE THREAD

**Issue by Talkwondo** [infinitered/ignite#310]
Hey,
Well I tried to make the hamburger icon on the right navbar but when i add:
renderLeftButton={NavItems.hamburgerButton} renderRightButton={NavItems.hamburgerButton}

I get the hamburger below it and not on the right side.
<img width="53" alt="screen shot 2016-08-22 at 8 57 17 pm" src="https://cloud.githubusercontent.com/assets/20122139/17865395/135b590a-68ab-11e6-9a67-02892aa9d465.png">

**Comment by sayedatif** [comment]
hey @Talkwondo if you want to add icon on the right hand side of navbar you have to edit App/Navigation/NavButton.js and add this code in my case i am adding search icon

```
searchButton (onPressFunction) {
    return (
        <TouchableOpacity onPress={onPressFunction}>
          <Icon name='md-search'
            size={Metrics.icons.medium}
            color={Colors.snow}
            style={styles.navButtonRight}
            />
        </TouchableOpacity>
    )
  },
```

and edit NavigationBarRouteMapper.js 

```
CreateButton (buttonId, navigator) {
    switch (buttonId) {
      .......
      case 'SEARCH':
        return NavButtons.searchButton(navigator.state.tapSearch)
      case 'CLOSE':
        return NavButtons.crossButton(this.crossButton.bind(this, navigator))
      default:
        return (<Text>Needs Button</Text>)
    }
  },
```
add some styles in App/Navigation/Styles/NavigationStyles.js so that it gets aligned on right side

```
navButtonRight: {
    margin: Metrics.baseMargin,
    alignSelf: 'flex-end'
  },
```

hope i answered your question any doubts are welcome.

**Comment by Talkwondo** [comment]
Hello,
Thank you very much for your help.
I don't have you file names as you have..  also if you can help me with another issue. I want the action of opening the camera for a QR code identifier. can you help me with that?

Thanks,

**Comment by degroote22** [comment]
Check this out: https://github.com/moaazsidat/react-native-qrcode-scanner
You can look for other plugins here https://js.coach/all/react-native-qrcode-scanner?search=qr%20code
