### ISSUE TITLE
Add generator option to create Reducer, Saga and api

### ISSUE THREAD

**Issue by waqas19921** [infinitered/ignite#315]
Please provide an option in CLI to generate reducer, saga and api files for any object to add in state. Plus it will also add default request, success and failure Type strings in `Types.js` and methods in `Creators.js`

**Comment by GantMan** [comment]
We're doing one last refactor to the way we make Types/Creators and reducers.   Once we are happy with the change, we will be making a generator :)

**Comment by skellock** [comment]
Sorry, I'll make time for it this week.

**Comment by GantMan** [comment]
@skellock - you've been coding like a beast lately, no rush.

**Comment by waqas19921** [comment]
Should you can make generator now. Refactoring is completed or not?

**Comment by GantMan** [comment]
Should definitely make a generator.

@waqas19921 - if you'd like to take first stab at it, I can answer any questions you may have.

**Comment by juddey** [comment]
@waqas19921 are you going to have a go at this? I might, if you're not.

**Comment by GantMan** [comment]
I say go for it @juddey

**Comment by juddey** [comment]
@GantMan lol you would :shipit:

**Comment by juddey** [comment]
hey, just wondering how this might be affected by #447...? I know that its a long way out but still thought I'd ask.

**Comment by GantMan** [comment]
You don't need to worry about that yet.  447 needs to worry about this.

**Comment by juddey** [comment]
![screen shot 2016-10-29 at 3 37 24 pm](https://cloud.githubusercontent.com/assets/7445602/19826766/490dc266-9df0-11e6-8675-46fe9f47298b.png)

![image](https://cloud.githubusercontent.com/assets/7445602/19826764/3de5e8aa-9df0-11e6-9b0d-7ade11c1d251.png)

cc @GantMan

**Comment by GantMan** [comment]
![image](https://cloud.githubusercontent.com/assets/997157/19826804/7fb5784a-9d5a-11e6-8e3c-3e606ed84814.png)
