### ISSUE TITLE
Drawer warning on freshly generated app

### ISSUE THREAD

**Issue by tmaziere** [infinitered/ignite#317]
Hi,

This issue is about a freshly generated code with Ignite 1.5.0 (OSX). The hamburger icon is not well displayed and this is the warning i get when the drawer is activated : 
`Warning: Failed prop type: Invalid prop ’open‘ of type ‘function‘ supplied to ‘Drawer‘, expected ‘boolean‘.`

I got it with both iOS and Android simulators.

And this is the _doctor_ response :
```
Computer
  Platform: darwin

Ignite
  Version: 1.5.0
  Path: /Users/*/.nvm/versions/node/v6.2.1/bin/ignite

Node
  Version: v6.2.1
  Path: /Users/*/.nvm/versions/node/v6.2.1/bin/node

NPM
  Version: 3.9.3
  Path: /Users/*/.nvm/versions/node/v6.2.1/bin/npm

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.31.0
```

Could it be caused by a recent version of the drawer component ?

**Comment by GantMan** [comment]
This will be fixed in next release.  I'll leave this ticket until them.  Should be releasing next week.

**Comment by GantMan** [comment]
https://github.com/infinitered/ignite/releases/tag/1.6.0
