### ISSUE TITLE
Hamburger is sitting below the title bar

### ISSUE THREAD

**Issue by leesolway** [infinitered/ignite#318]
When starting a new ignite project, the Hamburger icon is sitting below the main Nav Bar.

Welllllll, it just might be.  Do me a favor and check the following.

- [ ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x ] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

**Comment by GantMan** [comment]
@leesolway  - please take a look at this commit and let us know if this fixes it.  Staged for release:
https://github.com/infinitered/ignite/pull/311/commits/2aca1834f234a082c1fe75ab7b4fac5671753590

**Comment by vodnok** [comment]
Had the same issue here and indeed the solution was to do what GantMan suggest by deleting marginTop: Metrics.doubleBaseMargin on navButtonLeft

**Comment by leesolway** [comment]
@GantMan This is exactly how i had resolved the issue.

**Comment by GantMan** [comment]
We'll be shipping a release tomorrow to support 0.32.0 and fix this problem.

**Comment by GantMan** [comment]
https://github.com/infinitered/ignite/releases/tag/1.6.0
