### ISSUE TITLE
Application ... has not been registered

### ISSUE THREAD

**Issue by MatthewHartz** [infinitered/ignite#320]
Hi I followed the install steps of 

```npm install -g react-native-ignite```

```ignite new MyApplication```

```cd MyApplication```

```react-native run-android```

I'm using my Samsung s6 as a debugger, and I received the error message "Application MyApplication has not been registered.  This is either due to a require() error during initialization or failure to call AppRegistery.registerComponent.

I took a look at the index.android.js file, and all looks well, any ideas?

**Comment by GantMan** [comment]
do you have a packager running that is for a previous app?

Can you push this up to a repo for us to pull?

**Comment by MatthewHartz** [comment]
I didn't have it running, but maybe there was still a process running.  I restarted my PC and that fixed it.

Thanks! I'll close.
