### ISSUE TITLE
Freshly Generated App Crashes

### ISSUE THREAD

**Issue by darrindickey** [infinitered/ignite#322]
Freshly generated app. As soon as it's generated, I cd into the app directory and run react-native run-ios. The app successfully builds, but will not run. It starts and crashes. If I build in xCode, I get the error Thread 1: SIGABRT:
libc++abi.dylib: terminating with uncaught exception of type NSException

I've deleted and regenerated the app 4 times and still end up with this same problem.

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

```
Computer
  Platform: darwin

Ignite
  Version: 1.5.0
  Path: /Users/<username>/.nvm/versions/node/v4.3.1/bin/ignite

Node
  Version: v4.3.1
  Path: /Users/<username>/.nvm/versions/node/v4.3.1/bin/node

NPM
  Version: 3.10.6
  Path: /Users/<username>/.nvm/versions/node/v4.3.1/bin/npm

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.31.0
```

**Comment by darrindickey** [comment]
Upon further review, this may be related to react-native. A fresh install of RN yields the same problem.

**Comment by skellock** [comment]
Did you grab the beta Xcode by any chance?  Do you see anything in the stack trace related to WebSockets?

**Comment by darrindickey** [comment]
No to both. I finally got it working. I had to go into Edit Scheme and change Build Configuration from Debug to Release.
