### ISSUE TITLE
Can't build `ignite-base` without creating a `.env` file - Confusing to devs

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#323]
## Currently `ignite-base` will not run without a `.env` file

One way around this, is we create a `.gitignore` and a `.gitignore.template` and we enforce them to be the same in `firedrill.sh` except the `.gitignore.template` has the `.env` exception.  Currently we just copy our `.gitignore` as is.   This would allow us to check a `.env` file in our repo but not in any resulting repo that is ignited.

.we should probably fix this soon.

One other solution is to adjust the npm module to fail gracefully with a warning when there is no .env file.  No guarantee such a change would be merged.

**Comment by GantMan** [comment]
This was originally introduced by `react-native-config` in PR #304

**Comment by skellock** [comment]
Temp fix:  https://github.com/infinitered/ignite/pull/330
Perm fix: https://github.com/luggit/react-native-config/pull/31

I'll keep this assigned to me & update if `react-native-config` accepts.

**Comment by GantMan** [comment]
config got merged!  We can update on their next release and close :)

**Comment by skellock** [comment]
... and released.  Ready to swap out in:

https://github.com/infinitered/ignite/blob/master/ignite-base/package.json#L31

and

https://github.com/infinitered/ignite/blob/master/ignite-base/package.json.template#L31

if someone beats me to this task.

**Comment by GantMan** [comment]
🔥  FireDrill 🚒  appreciates that you listed 2 files.

**Comment by skellock** [comment]
FireDrill has my back.  And I have it's.

**Comment by GantMan** [comment]
version 0.1.0 was released.  Package.json can be updated now.
