### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by TheGuy68** [infinitered/ignite#327]
I've tried to get Igniter installed but it just gives me this error.

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "react-native-ignite"
npm ERR! node v0.10.25
npm ERR! npm  v3.10.6
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED
npm ERR!     at errnoException (net.js:901:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:892:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect' }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /projects/RN/npm-debug.log

**Comment by gediminaspetrikas** [comment]
Might be a network issue. Do you have a stable internet connection?

**Comment by GantMan** [comment]
Looks to me like npm permissions.   Please go through this:   https://docs.npmjs.com/getting-started/fixing-npm-permissions

Going to close, but let me know if it doesn't end up being NPM we can open it again.
