### ISSUE TITLE
TypeScript support as an option?

### ISSUE THREAD

**Issue by jamespacileo** [infinitered/ignite#337]
Opening this issue so a discussion can be started.

TypeScript 2 is bound to be released, so I believe any discussion should be targeted to version 2 or 2.1.

[These are the features on roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap)

Most or all the 2.0 features are implemented in the beta release `npm install typescript@beta`

Part of the 2.1 features are implemented in the next release `npm install typescript@next`

**Comment by skellock** [comment]
I'm open to both TypeScript & Flow.  Haven't had the bandwidth to process either just yet.

**Comment by jamespacileo** [comment]
Ok I'll share any progress I make on integrating Typescript in the future :)

**Comment by GantMan** [comment]
After much discussion, we're going forward with Flow.  #387 - Working with Facebook's code, it makes sense to keep familiar with their methodology.   We'd be interested in chatting more, but for now we're closing this ticket.   I'll reopen if you want to chat.

**Comment by fbartho** [comment]
Is there any hope of supporting both these days? -- Our app is itself written in TypeScript, and it would be great if our ignite plugins were TypeScript as well!
