### ISSUE TITLE
UI sluggish (~2 fps) on Android (Nexus 5X)

### ISSUE THREAD

**Issue by jamespacileo** [infinitered/ignite#338]
Freshly initialised app, Ignite version 1.6.1.

```
ignite new testApp
cd testApp
react-native run-android
```

Phone used is a clean non-rooted Nexus 5X, Android v 6.0.1.

Navigation very sluggish.

perf stats at end of navigation animation:
```
UI: 2.1 fps
199 dropped so far
8 stutters (4+) so far
JS: 2.1 fps
```

Hope this helps.

**Comment by skellock** [comment]
Was this in production mode?

**Comment by GantMan** [comment]
Was this test done with a production build on a device?  Or were you in developer mode?

**Comment by jamespacileo** [comment]
Thanks for the replies! It was run with commands listed, so definitely not
production.

I've read some other issues and it looks like 2 fps may be normal for
development.

If that's the case, are there steps that can be taken to have close to 60
fps during development too?

I'm willing to switch any debug tools off that are slowing the base app
down.

I'm developing android first, so that if it runs fluid in dev on Android I
know there will be virtually no performance issues on both ios and Android
in production.

Thanks! :)

**Comment by skellock** [comment]
You'd be surprised actually.  I've seen things (scrolling lists) perform better on Android devices (nexus 7) than iPhone (6) devices.

Best to test on both.

The big offenders for dev debug speed is:  `console.log` and `debug JS remotely`.  Ensure those are off.

But you're not going to get 60fps.  The emulators use software OpenGL drivers, which means you're running off CPU to do things.

Where this is really noticeable on Android is WebViews.  Put a webview on your screen and watch that sucker tank.  Fire it up on the device and there's not problems at all.

**Comment by jamespacileo** [comment]
Thanks for taking the time to write the reply!

@skellock I'm using a physical test device
So if I disable `console.log` and `remote debugging` I'll have the same butter-smooth performance as vanilla React Native development?

Also forgive me for not knowing, but are you referring to tooling which isn't in vanilla React Native? Or are you talking about disabling the vanilla tooling itself?

Thanks for your time.

**Comment by skellock** [comment]
It'll be better, but not butter.  There are big optimizations that happen when you switch into production mode. 

The `debug JS remotely` is on the device.  it's the menu when you shake.  just ensure that's off.  

Also `console.log` statements cause slowdowns too, so try removing those if you've got 'em in your codebase.

Take your app, and run `cd android && ./gradlew installRelease` to run in production mode.  That's when you'll see what your users sees.

**Comment by jamespacileo** [comment]
Thanks again!

Ok sounds like you're referring to the vanilla tooling, the vanilla remote debugger was off, so that leaves the `console.log` statements.

Gut feeling would be multiple `console.log` statements called with big chunks of data in them, but running a search in the project doesn't reveal any statements apart from:

```
if (__DEV__) console.log('TOKEN:', token)
...
if (__DEV__) console.log('NOTIFICATION:', notification)
```

Feels like a bit of a mystery. Any recommendations on finding the bottleneck?

**Comment by skellock** [comment]
Not quite sure.  You could try turning on systrace and going crazy with that, but in my experience, dev mode is always laggy.

**Comment by jamespacileo** [comment]
Hi @skellock I've found the culprit.

It's not the `console.log` or the `remote JS debugger`

Removing the `ProgressiveImage` Component returns the app to 60fps with all debugging tools enabled, lag completely vanishes. 

So I've done some digging...

The image used for the component is 4288 × 2844 and 1.5Mb, replacing this with an optimised HD 1920x1080 image removes the lag as well as returning the app to 60fps.

So it seems that most issues raised on sluggishness are potentially related to the usage of this image, my gut feeling is that the component scales the image repeatedly each frame and doesn't cache the result. 

This is probably due to the nature of the `Animated.Image` component, we should probably add a proxy image and feed the scaled image as source to the `Animated.Image` component, that hopefully should permanently fix the problem.

Any chance we could kindly re-open the issue to continue discussion?

Hope this helps everyone.

**Comment by skellock** [comment]
I had read somewhere that image decoding can affect this.

That image is massive.  Likes like 48 Meg of RAM alone.

I've never used Progressive Image before (coincidently I was about to integrate it in today to a client app).  I'll take a look this morning and see whats up.

You're awesome dude!

**Comment by GantMan** [comment]
Progressive image needs to come out.  We thought of some cool components to place in Ignite, and progressive image was one of them, but to be honest it really should be an external component.

I say we switch it for a simple component called "Rounded image" or something like that.  Thoughts?

**Comment by skellock** [comment]
Sure.  If we're just displaying an image, I'm not sure we need a component.

Interesting side note.  Not sure when this was added, but on Android, that fade-in after load effect is now built in!

**Comment by GantMan** [comment]
Then I say we remove the component.  Looks like we have some other components without examples that could be added.   I'll knock this out AM

**Comment by skellock** [comment]
Actually before I close this, @jamespacileo are you cool with how things went here?  Does it make sense to you that we killed the Progressive Image component with the animation?

**Comment by jamespacileo** [comment]
Hi @skellock that sounds reasonable. Thanks for the consideration! 👍
