### ISSUE TITLE
Missing generator react-native-ignite:listView

### ISSUE THREAD

**Issue by besingamkb** [infinitered/ignite#344]
Hi,

I am trying to generate a new listView base on the documentation. and I got this error. 

```bash
C:\Users\Mark Kevin Besinga\SnapIgnite>ignite generate listView Videos
Generate a new listView named Videos
Error react-native-ignite:listView Videos

You don't seem to have a generator with the name react-native-ignite:listView installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 7 registered generators run yo with the `--help` option.

C:\Users\Mark Kevin Besinga\SnapIgnite>
```

### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [ ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [x] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

```
Computer
  Platform: win32

Ignite
  Version: 1.5.0
  Path: C:\USERS\MARK KEVIN BESINGA\APPDATA\ROAMING\NPM\IGNITE.CMD

Node
  Version: v6.4.0
  Path: C:\PROGRAM FILES\NODEJS\NODE.EXE

NPM
  Version: 3.10.3
  Path: C:\PROGRAM FILES\NODEJS\NPM.CMD

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.31.0
```

**Comment by GantMan** [comment]
can you try with `listview` all lowercase?

**Comment by besingamkb** [comment]
my apology. i miss look on it. it works on `listview` all lowercase

**Comment by GantMan** [comment]
@besingamkb  -   Sounds like a good PR!   I agree it should be case-insensitive.

Would you please open a ticket requesting that generators are case-insensitive, and I'll mark it as an easy future task?
