### ISSUE TITLE
I18n. Fallback doesn't work when using translations outside of Components

### ISSUE THREAD

**Issue by ruskid** [infinitered/ignite#346]
Helloo,

I have a config like this for image picker:
```javascript
import I18n from 'react-native-i18n'

const PICKER_OPTIONS = {
    title: I18n.t('avatar_title'),
    cancelButtonTitle: I18n.t('avatar_cancel'),
    takePhotoButtonTitle: I18n.t('avatar_takePicture'),
    chooseFromLibraryButtonTitle: I18n.t('avatar_takeFromLibrary'),
}
export default PICKER_OPTIONS
```

and I receive **missing en-US translation** with fallback activated. When I use the same I18n.t('avatar_title') in React Components it gets translated.

**Comment by GantMan** [comment]
Wow, that's odd.  I wouldn't have expected that.  Can you check through the NPM repo and see if anyone has any info on this?   https://github.com/AlexanderZaytsev/react-native-i18n

My gut says this might be a race-condition.   A top-level const might be assigned before the lifecycle of React Native.  That's just a guess.   

Does the const work if you move it to the same file, but not the same class?

**Comment by ruskid** [comment]
Agree, very weird. 
It worked before the I18n update.

I already tested it outside the class, doesn't work.

**Comment by ruskid** [comment]
Ok. so, finally had time to see this issue. And I fixed this by changing order of imports in App.js

```javascript
import React, { Component } from 'react'
import { Provider } from 'react-redux'
import '../I18n/I18n' //declare this before RootContainer
import RootContainer from './RootContainer'
import createStore from '../Redux'
import DebugSettings from '../Config/DebugSettings'
```

**Comment by ruskid** [comment]
Try to reproduce this, to confirm if this is a bug

**Comment by GantMan** [comment]
wow...   will do

**Comment by GantMan** [comment]
@ruskid - I didn't have time to really create an example of the issue, so I just moved the order of imports like you suggested.  That way if what you said works, then we're good.

Please reopen if the issue persists.
