### ISSUE TITLE
`npm run android`?

### ISSUE THREAD

**Issue by jgkim** [infinitered/ignite#347]
Basically, we can launch the Android emulator with `react-native run-android`. However, [to use `reactotron` on Android](https://github.com/reactotron/reactotron/issues/174), we also need to tunnel `tcp:9090` with `adb reverse tcp:9090 tcp:9090`. The thing is sometimes I forget to do it and it's tedious to type the command.

What about having `npm run android`, which run those two commands in sequence?

**Comment by skellock** [comment]
I'm going to find some time this weekend to apply https://github.com/reactotron/reactotron/issues/192 to Reactotron.

Essentially, it bypasses the need to run adb with your emulator at all.  You just keep your default config.  :)  

If that weren't possible, I'd totally go with your suggestion!  Thx for filing an issue!

**Comment by skellock** [comment]
Btw, i feel your pain, i'm a contributor to both repos and I still trip up on that adb step!  haha.
