### ISSUE TITLE
Early exit if folder already exists

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#349]
When someone does `ignite new TacoTruck` but the tacotruck folder exists, we should fail.

See this issue comment:   https://github.com/infinitered/ignite/issues/241#issuecomment-244415741

**Comment by juddey** [comment]
Made a start on this today, should have something soon. ⌛

**Comment by GantMan** [comment]
Let me know if you have any questions.  We don't have much documentation on our structure.
