### ISSUE TITLE
ignite new testApp misses react-native-cli despite it being installed

### ISSUE THREAD

**Issue by wdiechmann** [infinitered/ignite#354]
I installed the react-native-cli and did a `react-native init testApp` followed by `react-native run-ios` and all the world was good :)

Then I `cd ~ && npm install react-native-ignite -g` followed by `ignite new testApp` which had me left with this:

```
$ ignite new testApp
This command requires yo to be installed.
Installing yo...
(node:55281) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/Users/walther/.node/bin/yo-complete -> /Users/walther/.node/lib/node_modules/yo/lib/completion/index.js
/Users/walther/.node/bin/yo -> /Users/walther/.node/lib/node_modules/yo/lib/cli.js

> yo@1.8.5 postinstall /Users/walther/.node/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✔ NODE_PATH matches the npm root

Everything looks all right!
/Users/walther/.node/lib
└── yo@1.8.5 

🔥 Setting testApp on FIRE! 🔥
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------
Igniting testApp

𝗫 Missing react-native - 'npm install -g react-native-cli'
$ npm list react-native-cli
/Users/walther
└── react-native-cli@1.0.0 

$ 

```

Finally I tried to verify that the react-native-cli was actually there - which `npm list react-native-cli ` seems to support ? So now I'am at a loss as to what next, debugging-wise?

Oh - and `ignite doctor` tells me this: 

```
$ ignite doctor
/Users/walther/.node/lib/node_modules/react-native-ignite/node_modules/ramda/dist/ramda.js:4307
                return str.trim();
                          ^

TypeError: Cannot read property 'trim' of null
    at Object.trim (/Users/walther/.node/lib/node_modules/react-native-ignite/node_modules/ramda/dist/ramda.js:4307:27)
    at Object.f1 [as trim] (/Users/walther/.node/lib/node_modules/react-native-ignite/node_modules/ramda/dist/ramda.js:446:27)
    at Command.<anonymous> (/Users/walther/.node/lib/node_modules/react-native-ignite/index.js:116:36)
    at Command.listener (/Users/walther/.node/lib/node_modules/react-native-ignite/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/walther/.node/lib/node_modules/react-native-ignite/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/walther/.node/lib/node_modules/react-native-ignite/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/walther/.node/lib/node_modules/react-native-ignite/index.js:133:21)
    at Module._compile (module.js:541:32)
$ 

```

**Comment by GantMan** [comment]
Wow, that seems like a lot going on.  Obviously something isn't right.

OK, so since you typed `npm install react-native-ignite -g` I can assume you have the latest/greatest ignite, even though we can't see it in doctor.

The code that is failing for you seems to be right here:  https://github.com/infinitered/ignite/blob/master/ignite-generator/src/app/index.es#L131-L147

What that code does, is run `which` to see if there's a result.   So when you run `which react-native` do you get a result on your machine?

**Comment by wdiechmann** [comment]
hmmm - strange!

when I do `which react-native` it returns nil (well it doesn't but that would be the effect if done programmatically, I guess)

but when I do `$react-native` - it returns 

```
$ react-native
You did not pass any commands, did you mean to run `react-native init`?
$ 
```

**Comment by wdiechmann** [comment]
well - the plot thickens!

```
$ npm list react-native
/Users/walther
└── (empty)

npm ERR! code 1
$
```

**Comment by wdiechmann** [comment]
then I did

```
$ sudo npm install -g react-native-cli
Password:
(node:59956) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/Users/walther/.node/bin/react-native -> /Users/walther/.node/lib/node_modules/react-native-cli/index.js
react-native-cli@1.0.0 /Users/walther/.node/lib/node_modules/react-native-cli
├── semver@5.3.0
├── minimist@1.2.0
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
└── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.4.0, read@1.0.7, winston@0.8.3, utile@0.2.1)
$ 

```

**Comment by GantMan** [comment]
there seems to be something wrong with your setup :/

**Comment by wdiechmann** [comment]
well - indeed

so I better remove npm, node et al?

**Comment by GantMan** [comment]
Sorry to say I don't know what the fix will be, but yes, a blown away node and fresh proper install would be my next steps.  You never know when this will bite you again, so it's key to fix it.

We could add something to ignite doctor that when it sees this, it would warn the user their setup is borked.  Not sure how many of these we'll see.   Perhaps it would be a good contribution, if you're not winded from a complete reconstruction of your local setup.

**Comment by wdiechmann** [comment]
I reckon a fresh install would never hurt anyway - but then I guess Electron and a few other libs will send me on a few other detours. Come what may, I'm of to install-land :)

cheers,
(and thx for prompt replies)

**Comment by skellock** [comment]
This reminds me of npm 2 issues.  When you have a dependency that can't find another dependency: thats npm 2.  I recently had this issue on Reactotron.  :(

But ya, I'm eith @GantMan on this one.  Nuke and install latest node (6.5) from brew. :)

Good luck @wdiechmann ! See ya on the other side.

**Comment by wdiechmann** [comment]
sorry to bother you (again) but this is not going away :(

[did a gist to aid my comment](https://gist.github.com/wdiechmann/a030590a99aa1e300104c7c1bceaf66d)

**Comment by GantMan** [comment]
what's the output of `which react-native` now?

**Comment by wdiechmann** [comment]
(last line in the gist)

empty

**Comment by wdiechmann** [comment]
and if it is any help at all

```
$ pwd
/Users/walther
$ cat .npmrc
prefix=/Users/walther/.node
$ ls .node/bin
ignite		react-native	yo		yo-complete
$ .node/lib/node_modules/react-native-cli/index.js
You did not pass any commands, did you mean to run `react-native init`?
$ 

```

**Comment by skellock** [comment]
Are you able to create a React Native app without ignite?

I noticed you installed with `sudo`. I wouldn't recommend that.  Half the issues we see are permission related.  Ha!

**Comment by wdiechmann** [comment]
I am - that was the first thing I did - line 78 in the gist :$

**Comment by wdiechmann** [comment]
and I believe you're referring to my initial shot at it, @skellock ? In the gist all sudo-ing done by me is removing all my initially hard-earned node/modules these last 2-3 years :)

**Comment by skellock** [comment]
haha.

Strange.  So from a shell, no path issues.  From a script, problems.  Hmm.  

Where do you set your path for node?  Do you have that in a bashrc or profile?  Or are you running zsh?  using something like dotenv?

**Comment by wdiechmann** [comment]
well steve - that gist really is a wealth of information ;)

line 71-74 says:
```
$ echo $NODE_PATH
:/Users/walther/.node/lib/node_modules:/usr/local/lib/node_modules
$ cat .npmrc
prefix=/Users/walther/.node
```

\- and the NODE_PATH gets set in ~/.bashrc on the last line like this 

```
export NODE_PATH=:/Users/walther/.node/lib/node_modules:/usr/local/lib/node_modules
```

**Comment by wdiechmann** [comment]
running a regular bash

**Comment by wdiechmann** [comment]
as the react-native is something of a new (sidekick) to me - after killing all my node stuff, I hurried back to the "nuclear facility" and did a quick 

```
$ git clone https://github.com/electron/electron-quick-start
$ npm install && npm start
```

Happy to report that all is well in 'Manhattan' :D 

(so even if I'd really like to take a stab or two at this ignite thing - my electrons are safe and that's what will allow me to sleep well in a little while)

**Comment by skellock** [comment]
Guilty as charged.  I didnt read the 1400 line Gist end to end.

Your PATH includes npm's global location.  I'm at a loss as to why it wouldn't for scripts.

**Comment by GantMan** [comment]
haha, good that the electron is stable.   Now if we can figure out why `which react-native` is failing!

If you want to bypass this problem locally, you can go to your node modules and and comment that line out.  That will allow you to move forward without the which command working.

**Comment by wdiechmann** [comment]
@skellock - please allow me to apologise! I'd be quite a piece, using for free and adding insults on top! That was in no way my intentions! Weak command of a non-mother-tongue and eager to prove having covered my bases prior to crying 'wolf' - and on top of that I have this terrible habit of (mis)using irony and sarcasm -

@GantMan - I will add a // and be gone ;)

**Comment by wdiechmann** [comment]
Actually - I woun't :)

What I did was ponder - and then I added **$HOME/.node/bin** to my PATH!

That helped ignite along - and everybody may now return to their stations and have a biscuit and a cup'o'tea :D

Sorry for all the commotion

**Comment by GantMan** [comment]
I'm happy it's solved!  I wasn't sure how our checks were failing.

Such an interesting dilemma!   I wonder if we should add a check to the PATH variable if something comes back blank, or at least document this case?  Glad all is well!

**Comment by skellock** [comment]
Indeed.  For closure, I'd love to know how the shell knows, but a script doesn't.  I wonder if perhaps the PATH was inside `.bash_profile` instead of `.bashrc` originally?  

That *might* explain it.

**Comment by wdiechmann** [comment]
well - i would have been helped quite a bit if the ignite doctor had pointed out that my PATH was missing a ‘node’ element

- or even better perhaps

if your commandExec(‘which’-something used the NODE_PATH to call react-native - of sorts 

anyways - I didn’t quite see it coming - and am still puzzled by it - 

cheers,
Walther

**Comment by wdiechmann** [comment]
well - Steve

it’s as if you’re psychic :)

did a quick 

$ more ~/.bash_profile
#!/usr/bin/env bash

echo '.bash_profile start'
# PATH additions --------------------------
# mysql
PATH="/usr/local/mysql/bin:$PATH"

# npm
PATH="/usr/local/share/npm/bin:~/.node/bin:$PATH”
---snip---

and for good measure

$ more ~/.bashrc
# System-wide .bashrc file for interactive bash(1) shells.
export PS1='\$ '
# Make bash check its window size after a process completes
shopt -s checkwinsize

# export PATH=$HOME/local/bin:$PATH
PATH=$HOME/local/bin:$HOME/bin:$HOME/.node/bin:$PATH

I did the .bashrc ‘add-on’ - but the .bash_profile was sitting there all the time! This is an important lesson (even with 20 years of *nix under my belt - most of which were decent scripting, bashing, etc - but it never crossed my mind to distinguish between the two SOG’s) ;)


cheers,
Walther
