### ISSUE TITLE
android physical back button does not close slide out menu - closes entire app

### ISSUE THREAD

**Issue by tgaff** [infinitered/ignite#357]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- ✅  Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x]  ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

## description

If a slide-out / pull-out menu is currently displayed on android devices, hitting the physical back-button slides-closed that menu.  You can demonstrate this yourself on an android device with Google Keep or Google Maps.  In ignite, if you slide out the menu and then hit physical-back the entire app closes.  That's unexpected to users (and I've gotten at least one comment in feedback on this).

### steps to reproduce

1. ignite new testapp
2. cd testapp && react-native run-android
3. in the opened app slide out the menu by clicking the hamburger
4. hit the emulator or phone physical back button
5. observe app close

### expected behavior

The app remains open, but the menu slides closed.

### doctor

```
Computer
  Platform: darwin

Ignite
  Version: 1.6.2
  Path: /Users/tgaff/.nvm/versions/node/v6.2.2/bin/ignite

Node
  Version: v6.2.2
  Path: /Users/tgaff/.nvm/versions/node/v6.2.2/bin/node

NPM
  Version: 3.9.5
  Path: /Users/tgaff/.nvm/versions/node/v6.2.2/bin/npm

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.32.0
```

**Comment by GantMan** [comment]
special thanks to @lukabers for this one.  Will be in next release.
