### ISSUE TITLE
Remove Fastlane

### ISSUE THREAD

**Issue by jhabdas** [infinitered/ignite#358]
Thoughts on removing Fastlane from the generated code? IMO it's too opinionated. There are plenty of other services one may wish to choose from, including [Buddybuild](https://habd.as/beta-testing-react-native-buddybuild/), Bitrise, etc. and I feel it should be up to the implementation to make the CI decision without leading them. I hope you agree.

**Comment by GantMan** [comment]
I do.  We'll need to move fastlane to a generator, and then we can remove.  So it could be `ignite generate fastlane` which would be useful, and even friendly to other possibilities.

I'll mark this as a TODO/EASY and hope someone picks up the PR soon.  If not, I will def get it eventually.

**Comment by jhabdas** [comment]
Solid. Thanks 👌🏼

**Comment by skellock** [comment]
This is now gone.  But could rise from the ashes as a plugin!

**Comment by RWOverdijk** [comment]
Ahw! I personally disagree with @jhabdas his statement _"IMO it's too opinionated"_. That would mean everything should go, as it's all opinionated. I mean, redux? The navigation library? Apisauce?

Not that long ago, ignite included react-native-router-flux, which got replaced with react-navigation. I don't understand why, but I trust that this decision was made by people that know the react-native playing ground better than I do.

The reason I started using ignite was _because_ it was opinionated. It's an excellent starting ground from a to z. I just realized fastlane was missing and it's a little disappointing imo.

Anyway, just my thoughts on the matter :)

**Comment by jhabdas** [comment]
> I personally disagree with @jhabdas his statement "IMO it's too opinionated"

The wonderful thing about opinion and feelings is they cannot be disagreed with. Nevertheless, leading implementations on CI approach or authentication, can styme innovation and lead to potential risks down the line.

That said, my understanding is CI is a deployment concern, and not something an asset pipeline should necessarily be implementing. But that's just my opinion.

**Comment by RWOverdijk** [comment]
> The wonderful thing about opinion and feelings is they cannot be disagreed with.

What I meant, was that I don't share your opinion. Which.. Is disagreeing? So, I _can_ disagree with your opinion. Which I do. And I think providing an opinionated and complete bundle, is useful. Even CI. It being moved to a generator, but at least pointed out would have made more sense. Now it's just removed, with no generator.

**Comment by jhabdas** [comment]
I believe what you're trying to say is that you disagree with the outcome of this issue and would prefer to see a more opinionated solution for building your apps. Perhaps Pepperoni has the kind of opinion you desire. Otherwise the plug-in system is the way to go. Extensible and enables BYOO, Bring Your Own Opinion.

**Comment by jhabdas** [comment]
Also, just for fun, if I told you "It's my opinion that I can levitate," would you disagree with me? Or would you thank me for sharing and choose to go your own way?

**Comment by RWOverdijk** [comment]
Yes, I would. Because I would have a different opinion. Which is [what a disagreement is](https://www.merriam-webster.com/thesaurus/disagree). English isn't my first language, but I know it well enough to know that you're wrong. :p 

Semantics aside, we agree that a plugin system is the way to go. But the "full-blown" option the cli offers now doesn't include fastlane anymore, there's no plugin, it's just gone. It's (as far as I could see) not document anywhere besides this issue. I think that's a shame for newcomers.

Thanks for mentioning Buddybuild by the way, I just checked it out and it looks pretty cool! :)

**Comment by jhabdas** [comment]
Haha. Fair enough. Buddybuild was the reason I opened this issue. My argument Fastlane was too complex had more to do with it's <del>crappy</del> <ins>subpar</ins> CX (Customer Experience) than anything.

It's possible to use Buddy together with Fastlane (some are), but for getting, ahem, _Ignited_, BB is the way to go for CI in RN apps at the moment.

Here is a quick post I wrote on my experience with it:
https://habd.as/beta-testing-react-native-buddybuild/

Here's an example integration:
https://github.com/jhabdas/lumpen-radio

And here's how to hide all your secrets:
http://stackoverflow.com/questions/33117227/setting-environment-variable-in-react-native/39645159#39645159

Have fun out there!

**Comment by GantMan** [comment]
I'm looking forward to plugins for both these options.   If either of you are interested in learning how to write em, let me know!   I'd love to help, and it's super easy.

@ryanlntn - We'll need to explore do one of these when we release the Chain React conference app in a bit.

**Comment by RWOverdijk** [comment]
@GantMan I'm curious. Perhaps @jhabdas can help out since he already has experience with it (and an example integration). I'd like to learn more about it.

**Comment by jhabdas** [comment]
@GantMan I'll do it next RN app I make. 👍
