### ISSUE TITLE
Get "Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2" when building Ignite app 

### ISSUE THREAD

**Issue by make2514** [infinitered/ignite#362]
Hi guys,

I am very new to Ignite. I have followed the instruction in README.md file to initialize ignite app.
After executing this command: "react-native run-android", I got this failure notification from react-native:

Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2

I have searched for a solution on stackoverflow and edit build.gradle as answered in this thread:
http://stackoverflow.com/questions/29460443/execution-failed-for-task-appdexdebug-com-android-ide-common-process-proces

The above failure went away, but there is this new failure notification:

Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: org/webkit/android_jsc/R.class

Any insight would be appreciated! Thank you very much!

**Comment by GantMan** [comment]
please `cd android` and run `./gradlew clean`  Please let me know if that fixes it.  I'm interested in this issue, as this sometimes happens to me.

**Comment by make2514** [comment]
Thank you very much for your help, GantMan! The command `./gradlew clean ` indeed fixed the issue for me.
I have initialized a new Ignite app instance, follow your instruction and it worked.
Have a nice weekend!

**Comment by GantMan** [comment]
@make2514  and @tnikolay - In version 1.7.1 which I will release soon, this will have been run for you.   Ensuring no one has to worry to do it themselves :)

**Comment by TimFletcher** [comment]
I used 1.7.1 (having never installed Ignite before) and bumped into the #371 issue. I needed to run `./gradlew clean` manually to get `react-native run-android` to work.

**Comment by GantMan** [comment]
that's so odd, since as of 1.7.1 it runs `./gradlew clean` for you after everything is installed

I'm gonna try to recreate this problem locally.

**Comment by GantMan** [comment]
just did a fresh install of 1.7.1 and it didn't have this problem :(  Anyone got ideas?

**Comment by xcsrz** [comment]
(bump)  With a fresh install of Android Studio, SDK packages and Ignite I ignited a new project and ran into this same issue right out of the box.

**Comment by GantMan** [comment]
I'm frustrated by the need for `./gradlew clean`, I'll continue trying to track this down.

**Comment by illing2005** [comment]
Same here.
Needed to run `./gradlaw clean`.
Would be great if this was mentioned in the readme.

**Comment by GantMan** [comment]
@illing2005 - please send a PR!  I'll merge it.

Also, happy to merge if anyone figures out how to avoid this!   It drives me crazy that we have to do that now :(   I'll figure it out eventually.

**Comment by illing2005** [comment]
Done

**Comment by code-by** [comment]
./gradlaw clean don't help for me

**Comment by kogden** [comment]
me neither :(

**Comment by kevinvangelder** [comment]
@kogden Can you open a new issue?
