### ISSUE TITLE
I can set a custom package name?

### ISSUE THREAD

**Issue by WilliamPeralta** [infinitered/ignite#365]
Now package name is calculate from project name, but i need in this format "it.domain.appname"

**Comment by GantMan** [comment]
In iOS?  Just open up Xcode and change it 👍

**Comment by lukabers** [comment]
Android?

**Comment by GantMan** [comment]
I think that might be in the build.gradle.   I would just do a find-all and replace 👍

**Comment by WilliamPeralta** [comment]
but i need do refactoring of  my project every times that i make changes it? in Android the project name is same of folders tree
would be nice to build a project using a command, more or less like this:
ignite new MyApplication --package-name=it.myproject.app

**Comment by GantMan** [comment]
I like that idea.    I'll make this a task.

**Comment by WilliamPeralta** [comment]
good :) thank you

**Comment by MatthiasDebaere** [comment]
I would also like to see this feature!

**Comment by skellock** [comment]
This is a great suggestion.

**Comment by cluny85** [comment]
Hello! are any update of this thread?

**Comment by GantMan** [comment]
I added the Hacktoberfest tag to this.  I've got a few higher priority issues right now, but if someone completes it it will count towards their Hacktoberfest shirt now.

https://hacktoberfest.digitalocean.com/

**Comment by robinheinze** [comment]
@GantMan I can give this a shot

**Comment by robinheinze** [comment]
I haven't been able to get to this one yet, so if anyone else wants to grab it for Hacktoberfest, go for it!

**Comment by KamranKhankhail** [comment]
anyone did it?. can we provide package name now?

**Comment by KPS250** [comment]
Any update on this?

**Comment by jamonholmgren** [comment]
What we need is the ability to pass through the `--package` CLI command to `react-native init`.

```
ignite new MyApp --package "com.infinitered.jamonapp"
```

This would run:

```
react-native init MyApp --package "com.infinitered.jamonapp"
```

I would hold off until we have PR #1379 merged in, or work off of that branch, though.

**Comment by jamonholmgren** [comment]
We actually have an issue for this, so I'll track over there at #1044.
