### ISSUE TITLE
Generated screens look for actions wrong

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#366]
As of Ignite 1.7.0 refactor, we need to update our screen generators.

This line will error
https://github.com/infinitered/ignite/blob/master/ignite-generator/container/templates/container.js.template#L4-Lundefined

**Comment by skellock** [comment]
I'm sorry, this is my fault.  I looked through the generators and everything.  I'll make time today to fix if nobody else beats me to it first.

**Comment by GantMan** [comment]
super easy to overlook, not sure if there could have even been a test.

**Comment by juddey** [comment]
hey, hey, its Open-Source-Monday!

Will put together a PR for this one, just wondering if I should:
a) remove the line and leave it out, or
b) replace it with something like, 
`import SomeActions from  ../Redux/SomeRedux`
or c) Something else I haven't thought of yet...

**Comment by GantMan** [comment]
I'm thinking a commented out line, like b.  So it's there for when we need it, but it won't throw an error out the box :)

**Comment by GantMan** [comment]
happy open source monday to you!  I did an open source Saturday, don't have any idea why.   That and video games :D
