### ISSUE TITLE
Does react-native-config works for you on ignite?

### ISSUE THREAD

**Issue by ruskid** [infinitered/ignite#368]
Just wondering, Ignite already released the version with react-native-config, but I couldn't make it work.
I created the ticket https://github.com/luggit/react-native-config/issues/32 with no success, **does it work for you guys?**

Also Ignite released 1.7.0 with React Native updated to 0.33 did you experience this issue?
https://github.com/facebook/react-native/issues/9841

I needed to rollback back to 0.32, so my Ignite update is not full. Those are just questions, as you keep releasing new versions of Ignite, i am just wondering if I am the only one who has problems.

**Comment by GantMan** [comment]
Hi @ruskid - Excellent work and tickets!  I love issues that are organized like this.

Let's see:
I do NOT currently have the problem with react-native-config, but we are using a branch of RNConfig that was released by @skellock - which might be a different version?
Are you igniting a brand new project, or upgrading?  If upgrading, can I talk you into running a `newclear`

As for the facebook ticket 9841, I did not experience this issue.  But that's regarding a fresh build of Ignite.

**Comment by GantMan** [comment]
Be extra sure to `newclear`  https://github.com/GantMan/mobile-commander/blob/master/bin/newclear.sh

That might be residual mess.  I find upgrades sometimes require baptism by fire :)

**Comment by ruskid** [comment]
Tried to use `newclear`, still no result, config is undefined(((

**Comment by ruskid** [comment]
@skellock  I don't know where to reply now xd you broke the system.
Yes, this is still an issue, I tested your version and 0.1.0.

I shared my app with @pedro and waiting for his reply on this. I guess you can close this ticket here, as it doesn't relate to ignite, it's just a question.

**Comment by skellock** [comment]
Roger.  I'm sorry.  Haha.
