### ISSUE TITLE
TemperatureSaga is lonely without its Test

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite#373]
- [X] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [X] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

---
The Temperature Saga interacts with an external api, which is a common requirement. It'd be super cool to have an accompanying test that goes along with the TemperatureSaga for reference purposes.

**Comment by GantMan** [comment]
We will take a look at this soon
![soon](http://i.imgur.com/lYXDVgW.gif)

**Comment by skellock** [comment]
Weirdly enough, I put this in StartupSagaTest.js `¯\_(ツ)_/¯`.  I'll fix this next time I get a chance.  :)

**Comment by GantMan** [comment]
Ah yes, there it is.   https://github.com/infinitered/ignite/blob/a055be56e84d85d5603c62d2c0e4de71af2b8e07/ignite-base/Tests/Sagas/StartupSagaTest.js

I also want to add some other API calls.  I feel it would be helpful to have more than 2 hitting the same endpoint, now that we can get more info from our API.

**Comment by juddey** [comment]
Sorry for the false positive(?), I will have a look at the startup saga test. 😊 

I'll leave you guys to close/do whatever with this ticket depending on what you discuss above.

**Comment by juddey** [comment]
and fwiw, the more example code (particularly tests) that are around to look at, the better ignite becomes. 🔥
