### ISSUE TITLE
Just trying this out but doesn't work following readme.

### ISSUE THREAD

**Issue by tapickell** [infinitered/ignite#382]
Excited to try out
Following Steps...
```
Step 1: Install

npm install -g react-native-ignite
.
.
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!

> react-native-ignite@1.8.0 postinstall /Users/toddpickell/.nvm/versions/node/v6.6.0/lib/node_modules/react-native-ignite
> npm i -g generator-react-native-ignite

> spawn-sync@1.0.15 postinstall /Users/toddpickell/.nvm/versions/node/v6.6.0/lib/node_modules/generator-react-native-ignite/node_modules/spawn-sync
> node postinstall
```
Looks good lets see the magic....
```
Step 2: Use

~/code ᐅ ignite new IgniteTestApp
🔥 Setting IgniteTestApp on FIRE! 🔥
? ==========================================================================
We're constantly looking for ways to make yo better!
May we anonymously report usage statistics to improve the tool over time?
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== No
Error react-native-ignite IgniteTestApp

You don't seem to have a generator with the name react-native-ignite installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 1 registered generators run yo with the `--help` option.
```

Not sure what happened there.
I have never used Yo before so I am not familiar but it looks like it installed
the generator in the initial install part.
Am I missing some assumed knowledge here or is the readme out of date?

### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [X] Issue does not already exist
* searched didn't find an open issue for this.
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [X] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).
```
Computer
  Platform: darwin

Ignite
  Version: 1.8.0
  Path: /Users/toddpickell/.nvm/versions/node/v6.6.0/bin/ignite

Node
  Version: v6.6.0
  Path: /Users/toddpickell/.nvm/versions/node/v6.6.0/bin/node

NPM
  Version: 3.10.3
  Path: /Users/toddpickell/.nvm/versions/node/v6.6.0/bin/npm

Yeoman
  Version: 1.5.0

React Native CLI
  Version: 1.0.0

App
  React Native Version: ¯\_(ツ)_/¯
```

**Comment by designorant** [comment]
Looks like you might have a system-wide installed Yeoman that somewhat conflicts with the one installed via NVM.

Here are a few hints that should get you going:
1. `which yo`
2. https://github.com/infinitered/ignite/issues/217#issuecomment-229865986

**Comment by tapickell** [comment]
```
~/code ᐅ which yo
/usr/local/bin/yo
```

**Comment by tapickell** [comment]
```
~/code ᐅ rm -rf /usr/local/bin/yo
~/code ᐅ which yo
yo not found
~/code ᐅ ignite new IgniteTestApp
This command requires yo to be installed.
Installing yo...
...
🔥 Setting IgniteTestApp on FIRE! 🔥
...
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
   > Failed to notify project evaluation listener.
      > failed to find Build Tools revision 23.0.3
      > failed to find Build Tools revision 23.0.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 34.167 secs
✔︎ Cleaning up after messy guests

Time to get cooking! 🍽
```

**Comment by tapickell** [comment]
well thats a lot further than before, lol.

**Comment by designorant** [comment]
You're likely not fully set up for Android development, see [Android Setup](http://facebook.github.io/react-native/releases/0.23/docs/android-setup.html).

**Comment by GantMan** [comment]
@tapickell - did you end in success!?

**Comment by tapickell** [comment]
Nope. Not using this anymore.

**Comment by GantMan** [comment]
@tapickell - I'd love to follow up with you to see what the problem ended up being.   

Our goal is to make ignite work out the box, which it does for almost everyone.  Please let me know if you'd be willing to dig further into this particular issue.

**Comment by eikebartels** [comment]
Im having the same issue.

**Comment by GantMan** [comment]
hi @eikebartels - so your build is failing?  For Android?

**Comment by eikebartels** [comment]
Yes. On init project 

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> > A problem occurred configuring project ':react-native-maps'.
>    > Failed to notify project evaluation listener.
>       > failed to find Build Tools revision 23.0.3
>       > failed to find Build Tools revision 23.0.3

**Comment by GantMan** [comment]
looks like you don't have android properly installed.  Can you type `android` and install the build tools for 23?

**Comment by eikebartels** [comment]
Actually I have installed 23

<img width="563" alt="screen shot 2016-11-23 at 9 33 04 pm" src="https://cloud.githubusercontent.com/assets/767979/20577839/7839462c-b1c4-11e6-992f-978f99107a0c.png">

**Comment by eikebartels** [comment]
Ok got the issue.... I didn't install version 3.0.2 -_- 🤓


But then I getting another issue. 

On android 

> Application bpppppp has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
> runApplication
>     AppRegistry.js:99
> __callFunction
>     MessageQueue.js:236
> <unknown>
>     MessageQueue.js:108
> guard
>     MessageQueue.js:46
> callFunctionReturnFlushedQueue
>     MessageQueue.js:107
> 

and iOS is crashing straight away

**Comment by eikebartels** [comment]
Ok Android is running now 

```
$ killall node
$ react-native run-android
```

**Comment by skellock** [comment]
FWIW.  I always install the build tools 23.0.1, 23.0.2, and 23.0.3.

React Native released a few versions where the moved to 23.0.3.  3rd party folk then moved up too.  Then RN moved back to 23.0.2.  But didn't go back.   Meanwhile some 3rd party folk never moved from 23.0.1.

And hilarity ensued.

**Comment by GantMan** [comment]
Sorry for the difficult setup @eikebartels - we will continue to try to add checks in place to help users, but sometimes the issue is so elusive, we can't even conceive what a friendly warning would check for.

Fortunately it appears you're up and running for now.  Please ping us if you have any issue.

**Comment by molerat619** [comment]
I also have that problem with the generator. I am afraid of removing the current `yo` because I use it for other web projects at work. Will that break if I follow the described methodology?

**Comment by jamonholmgren** [comment]
@molerat619 You might want to wait for Ignite 2, which does not use Yeoman.

**Comment by molerat619** [comment]
Ok, thanks for the info. Is there a release date yet?

**Comment by skellock** [comment]
We're hoping for the end of February*.

<sub>(* This year February has 40 days though.)</sub>
