### ISSUE TITLE
Generated folder is incomplete

### ISSUE THREAD

**Issue by osiloke** [infinitered/ignite#384]
### Hiya! 

I've been trying to create a new project with the new version but it does not include Android and IOS folder etc Basically it does not complete. The new command ends with the output below
```
✔︎ Linking external libs
⠋ Linking external libs./PickUp/ios/PickUp/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo=0x7f9df14152a0 {NSFilePath=./PickUp/ios/PickUp/Info.plist, NSUnderlyingError=0x7f9df1413f80 "The operation couldn’t be completed. No such file or directory"})
✔︎ Updating PList file
⠋ Cleaning up after messy guestscd: no such file or directory: PickUp/android
/bin/sh: ./gradlew: No such file or directory
✔︎ Cleaning up after messy guests
```

So **I** think it's broken

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

Also, for the quickest assistance **i** run `ignite doctor` and the everything is below (including the lines with 3 backticks).

```
Computer
  Platform: darwin

Ignite
  Version: 1.8.0
  Path: /Users/osi/.nvm/versions/node/v4.2.1/bin/ignite

Node
  Version: v4.2.1
  Path: /Users/osi/.nvm/versions/node/v4.2.1/bin/node

NPM
  Version: 3.8.6
  Path: /Users/osi/.nvm/versions/node/v4.2.1/bin/npm

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: ¯\_(ツ)_/¯
```

**Comment by GantMan** [comment]
Hey!  What happens when you create a react native project without Ignite?  Does it make those 2 folders?

**Comment by osiloke** [comment]
I think i traced the problem. An npm package in my local cache had a corrupted package.json file, so that kept breaking the install process. It would be nice if there was a nice error stating that npm could not install dependencies or something

**Comment by GantMan** [comment]
that's wild!  If you give us a good way to detect that, we can add that to our CLI

**Comment by osiloke** [comment]
This issue is related to npm/npm#6084. I'll look into it
