### ISSUE TITLE
A word of caution on Licensing

### ISSUE THREAD

**Issue by jhabdas** [infinitered/ignite#385]
Ignite uses `react-native-router-flux`, which is under a [BSD-2-Clause](https://opensource.org/licenses/BSD-2-Clause) open source license. I [reached out](https://github.com/aksonov/react-native-router-flux/issues/1199) to the maintainer of the project and ~~they~~ someone suggested credits ~~must~~ be given for distributed binaries. 😿

**Comment by jhabdas** [comment]
Edit, the maintainer hasn't gotten back to me yet.

**Comment by skellock** [comment]
woah.  thx for the heads up!

**Comment by jhabdas** [comment]
Approval has been given by the RNRF owner to switch the RNRF license to MIT from its current BSD license. The intention of such indicates more freedom of use. Closing.

**Comment by skellock** [comment]
Thank you!

**Comment by GantMan** [comment]
Great follow through @jhabdas !

**Comment by jhabdas** [comment]
With pleasure. Thanks for the helping hand, @GantMan
