### ISSUE TITLE
Adding Flow checking to Ignite

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#387]
With all the options for static type checking, it looks like we're leaning towards using Flow since it comes with React Native, and will work well.

As of #386 - We can see we are 116 errors away from being a flow compatible. app. 

We should go implement flow throughout, and then add flow to our CI - `fireDrill.sh`, to stay compliant.

https://flowtype.org/docs/getting-started.html#_

**Comment by GantMan** [comment]
We will need to move from `standard` to `standard-flow` ->  https://github.com/Gozala/standard-flow

I think we can still keep our standard badge, since we'll still be Standard, just + Flow

**Comment by amilajack** [comment]
Or we could use ESLint? I'm working on a plugin for eslint integration:

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by GantMan** [comment]
standard is a set of ESLint rules under the covers.  We just don't want to worry about micromanaging ESLint rules, so we just subscribe to standard :)

**Comment by GantMan** [comment]
closed via 461
