### ISSUE TITLE
Getting unhandled JS exception

### ISSUE THREAD

**Issue by svkangal** [infinitered/ignite#390]
Getting the following error. Trying this out for the first time and not sure whats going on.

<img width="373" alt="screen shot 2016-09-25 at 7 30 48 pm" src="https://cloud.githubusercontent.com/assets/2807160/18821137/5075cb8c-8358-11e6-9dc7-e87a09827e50.png">

Ignite Doctor
```
Computer
  Platform: darwin

Ignite
  Version: 1.8.0
  Path: /usr/local/bin/ignite

Node
  Version: v4.4.3
  Path: /usr/local/bin/node

NPM
  Version: 2.15.1
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.33.0
```

**Comment by GantMan** [comment]
Wow. that's odd.  Umm can you `npm i` and try again?  I'm kinda not sure what would cause that?

Have you ever built a non-ignite react native project?

**Comment by svkangal** [comment]
Yes I tried the non-ignite react native project before and it worked fine. Will try npm i.

**Comment by GantMan** [comment]
Unfortunately that error does not tell us much.  Also be sure to stop and reset packager.

**Comment by svkangal** [comment]
Now seeing this error. Looks like entire dev env is messed up with something..
<img width="372" alt="screen shot 2016-09-25 at 9 47 42 pm" src="https://cloud.githubusercontent.com/assets/2807160/18822949/bb7abbde-8369-11e6-9dec-2e54e32caa0f.png">

**Comment by svkangal** [comment]
Not sure but when I do ignite new, the build always fails for andriod project saying missing local.properties with ANDRIOD_HOME. Could that be a reason for incomplete setup?

**Comment by svkangal** [comment]
never mind got it to work now :)
