### ISSUE TITLE
Hot Reload Saga Support

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#391]
As mentioned in the hot-reloading ticket, we should have support at the Provider level, so sagas and redux can be hot-reloaded.  To be done by whomever gets there first!

Visual part was done at #155 

References:
https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/create.js#L28-L32

http://stackoverflow.com/questions/34243684/make-redux-reducers-and-other-non-components-hot-loadable

**Comment by GantMan** [comment]
I took a quick stab at this and it failed.  Here's my code that I was playing with:

```javascript
  console.log('HOT', module.hot)
  // hot-reload Redux store
  if (__DEV__ && module.hot) {
    module.hot.accept(['./', './TemperatureRedux', './LoginRedux'], () => {
      const nextRootReducer = combineReducers({
        temperature: require('./TemperatureRedux').reducer,
        login: require('./LoginRedux').reducer
      })
      store.replaceReducer(nextRootReducer)
    })
  }
```

Noticed hot module replacement always works after the first error message is displayed.

Bonus docs:  https://webpack.github.io/docs/hot-module-replacement.html

**Comment by GantMan** [comment]
now that I know editing a saga file twice makes hot-reloading work... I'm less inclined to figure this out, lol.   No clue on how that works.

**Comment by juddey** [comment]
Just been reading up on this.

Imo, I'm infinitely ( 👈  see what I did there :) better off with hot reloading, so I think its worth doing something about.  Looks like there are a lot of [issues](https://github.com/yelouafi/redux-saga/issues/22) to consider, and we're probably tied to applying whatever `redux-saga`   does in the long term. 

I've been running a similar-to-your-fix-version of ignite for a while now and it seems to be behaving quite acceptably (as you describe above anyway).

--- 

![image](https://cloud.githubusercontent.com/assets/7445602/19255556/b03272e0-8fbb-11e6-9aeb-080bf4e3e7d8.png)

**Comment by wafisher** [comment]
Are there any updates on this? I just want to confirm that with the current version, there's no way to Hot Reload any saga code, correct? Unfortunately, that saving-it-twice trick doesn't seem to work for me.

**Comment by skellock** [comment]
Hot reloading sagas is app-dependant.   Sagas maintain their state and interrupting them may or may not make sense for all apps.  Have a look at task cancellation in sagas for more details.

Reducers on the other hand can be reloaded!
