### ISSUE TITLE
Material Kit Radio button not working

### ISSUE THREAD

**Issue by Lokesh235** [infinitered/ignite#394]
Hi,

I was trying to implement radio button group using MKRadioButton in one of my Views but the radio button is not toggling.

Thanks

**Comment by GantMan** [comment]
Any update on what happened?

**Comment by Lokesh235** [comment]
I re-installed and reconfigured according to instruction in https://github.com/xinthink/react-native-material-kit/blob/master/README.md. It worked. 
P.S. I removed the default configuration of material kit in my ignite app.
