### ISSUE TITLE
MapView don't work ?

### ISSUE THREAD

**Issue by augisticz** [infinitered/ignite#396]
![untitled](https://cloud.githubusercontent.com/assets/11173295/19011493/1f8ca5a0-87c1-11e6-8eaa-f2521a693be5.png)

**Comment by GantMan** [comment]
what language is that?  Can anyone translate!

**Comment by augisticz** [comment]
react native android

**Comment by augisticz** [comment]
It error : Unfortunately, testIgnite has stopped

**Comment by VinZenTz1989** [comment]
I have the same problem when running app on Android but IOS is fine

**Comment by JoshM1994** [comment]
I would imagine this is an issue that often comes up with the react-native-maps plugin (https://github.com/airbnb/react-native-maps) - I had real trouble getting it to work as a standalone plugin but got there eventually after reading through lots of the [issues](https://github.com/airbnb/react-native-maps/issues) and the Android setup instructions on the main repo page.

Disclaimer: I'm not using Ignite at the moment, but have a lot of experience with RN maps

**Comment by augisticz** [comment]
I try to follow (https://github.com/airbnb/react-native-maps) ,It's same

**Comment by skellock** [comment]
I'm having troubles in the app we're building too on Android.  I haven't looked at it just yet, it's high on my priority list.

One thing recent they've done was bump the Google maps dependency from 8.4 to 9.4 in their build.gradle.  So I'll take a closer look at this too.

**Comment by augisticz** [comment]
Thank you @skellock,I Change the Google maps dependency from 9.4 to 9.6.1 is work!

**Comment by matthiasprieth** [comment]
https://github.com/infinitered/ignite-maps/issues/13
