### ISSUE TITLE
Base application not running

### ISSUE THREAD

**Issue by bentrengrove** [infinitered/ignite#397]
Hello, 

I followed the getting started guide but I can't get the base application to run, both iOS and Android show syntax errors for trailing commas. What did I do wrong?

I tried upgrading the react native version but that didn't help.

Thanks for any help, Ben

<img width="487" alt="screen shot 2016-10-02 at 08 29 34" src="https://cloud.githubusercontent.com/assets/19445/19017099/63b84cd4-887a-11e6-8833-876ee9a20204.png">

Ignite Doctor

```
Computer
  Platform: darwin

Ignite
  Version: 1.9.0
  Path: /usr/local/bin/ignite

Node
  Version: v5.1.0
  Path: /usr/local/bin/node

NPM
  Version: 3.3.12
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.34.1
```

**Comment by bentrengrove** [comment]
I have updated Node to the latest version but the issue persists.

```
Computer
  Platform: darwin

Ignite
  Version: 1.9.0
  Path: /usr/local/bin/ignite

Node
  Version: v6.7.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.7
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.34.1
```

**Comment by GantMan** [comment]
Hi @bentrengrove - that's quite an odd error.  It's complaining about code INSIDE react native.  I also, can't seem to find that error anywhere on google.  Do you have a second environment you can give this a run on?  I don't get this error locally, and I'm quite confused on how I could reproduce it :/

**Comment by bentrengrove** [comment]
Thanks for the reply.

I do not have another environment unfortunately but I have been playing around some more.
I believe something is going wrong with Babel as it never finishes transforming.

<img width="682" alt="screen shot 2016-10-02 at 09 26 47" src="https://cloud.githubusercontent.com/assets/19445/19017362/6a5fdf22-8882-11e6-97b9-3b5eeb298419.png">

Something else that is interesting is I can run base react native projects no problem. I am only seeing these errors when trying to use ignite.

**Comment by GantMan** [comment]
I have a process (wrapped in a simple command called `newclear` that I'd like to see if it clears things up.   Can you please run these commands?

https://github.com/GantMan/mobile-commander/blob/master/bin/newclear.sh

Let me know if that unclogs the transfer

**Comment by bentrengrove** [comment]
Thanks! Newclear seems to have done it. Sorry for the bother

**Comment by GantMan** [comment]
all good!  Glad it worked out.

**Comment by GantMan** [comment]
feel free to add the newclear command `npm i -g mobile-commander` and other commands.
