### ISSUE TITLE
Search in navbar

### ISSUE THREAD

**Issue by valinaga** [infinitered/ignite#398]
How can a search bar (react-native-material-design-search-bar) can be added to navbar? An example will be wonderful.

**Comment by bielcapanema** [comment]
Hi, you can do a custom navbar to a specific screen just adding the prop hideNavBar in your Scene:
`<Scene key='title' component={Screen} title='Title' hideNavBar />`

and in your screen you can do:
`<Container>
  <Header >
    <Search />
  </Header>
</Container>`

or just style one view around of `<Search />` to look like a navbar

**Comment by GantMan** [comment]
This is in master right now as a screen with search in examples.

Let us know if you have any further questions.
