### ISSUE TITLE
[CLI] Ignite can be sped up with a quick performance tweak

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#401]
currently, Ignite CLI will pull down a git version of itself on running, and use the branches/tags/files etc.  

As Ignite grows the `git clone` will grow, and the time associated.   We can narrow this process with prime precision by pulling only a `head` and `branch` of the desired version.  Thus ensuring Ignite CLI runs will only await the files they are required to use.

Example of pulling a specific branch with no history:  https://strk.kbt.io/blog/2011/06/07/getting-just-the-tip-of-a-remote-git-branch/comment-page-1/

**Comment by siakaramalegos** [comment]
I may have a solution (see slack @GantMan 😄)
