### ISSUE TITLE
ProgressiveImage component has been removed, but style file persists

### ISSUE THREAD

**Issue by christianbach** [infinitered/ignite#402]
### Hi, and thanks for a super great react native generator!

I noticed that the ProgressiveImage component has been removed. But in my generated project the style file still exists. `App/Components/Styles/ProgressiveImageStyle.js`

I think it could be removed to?

**Comment by GantMan** [comment]
Get some hacktoberfest credit :)  PRs welcome

**Comment by guidiego** [comment]
Done! ;)
