### ISSUE TITLE
ReduxPersist config should not include empty whitelist

### ISSUE THREAD

**Issue by panzer-planet** [infinitered/ignite#409]
As several people on gitter mentioned, an empty whitelist seems to blacklist all reducers.
Specifying an empty whitelist effectively blacklists everything. This is something redux-persist should sort out, but maybe ignite should consider having only the whitelist or blacklist defined in ReduxPersist.js, since once you have a whitelist, adding to the blacklist is analogous to removing from the whitelist and vice versa. i.e it's redundant.

**Comment by kevinvangelder** [comment]
When I added the whitelist option I attempted to manually test all the different use cases and didn't see any problems, but maybe I forgot to test when both options are blank...
