### ISSUE TITLE
ignite generate screen adds broken import

### ISSUE THREAD

**Issue by panzer-planet** [infinitered/ignite#410]
**ignite generate screen** adds `import Actions from '../Actions/Creators'` to the generated file. The Actions folder does not exist, this line simply needs to be removed from the generator.

**Comment by skellock** [comment]
Thank you.  This was my fault.  I had missed this during the redux overhaul.

**Comment by seejay55** [comment]
Is this issue still open? If so I'd love to help out, I'm looking for something simple for my first contribution.

**Comment by juddey** [comment]
Hi @panzer-planet, which version of ignite did you use? I thought I did a PR to fix this one a few weeks back...?
https://github.com/infinitered/ignite/pull/380/commits/912b6b1c12fb7461219ffb6d24b2ac6c1131f394

I've just pulled back 1.9.0 and it seems like its there.
/cc @seejay55

**Comment by GantMan** [comment]
verified, this has been fixed.
