### ISSUE TITLE
Warning / Bug on "Component Examples Screen"

### ISSUE THREAD

**Issue by NoviceGopher** [infinitered/ignite#411]
![igniteerror1](https://cloud.githubusercontent.com/assets/7389244/19163358/44cf36dc-8c19-11e6-9a39-03c729536407.png)
![igniteerror2](https://cloud.githubusercontent.com/assets/7389244/19163367/501dff32-8c19-11e6-874d-48f7cf6a90bb.png)

I deployed signed apk to my device to test and this screen does not come up in its entirety, probably because of the above warning. Meaning the `drawer button`, `Real  Button with Curve`, `Alert Message..`  etc do not show up.

Thanks

**Comment by 6congyao** [comment]
I suggest to fix this issue with changing the key from "Full Button" to "Map Callout" in /App/Components/MapCallout.js
I also commit a PR for that:)

**Comment by GantMan** [comment]
@6congyao - looking forward to your PR!

**Comment by msalokangas** [comment]
@GantMan @6congyao - noticed the same and made a PR https://github.com/infinitered/ignite/pull/430
