### ISSUE TITLE
.testRelease always seems to use Facebook latest switch

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite#414]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [X] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [X] ignite base application

Started off with #66... but in the process, I found that when the testRelease script runs, it's always running in the `latest` mode (despite what the documentation says.

PR coming!
👕

**Comment by GantMan** [comment]
o nice!  good catch

**Comment by juddey** [comment]
Resolved in #419
