### ISSUE TITLE
Wait AsyncStorage to load navigation

### ISSUE THREAD

**Issue by bielcapanema** [infinitered/ignite#416]
How can I wait to my store sync to AsyncStorage to mount my navigation?
the problem is: when I'm logged my first screen is home and when I'm not is login screen.

I will appreciate any help.
thanks!

**Comment by GantMan** [comment]
My favorite way of solving this is to have a screen that shows before both, that will redirect to the correct one.

If you make this screen look like your splash image, then no one will notice.  ALSO, it gives you a chance to fade-out your splash image or do anything fancy, you might want to do visually.

A little animation on this screen is pretty good for a primary loading screen.

**Comment by bielcapanema** [comment]
Good tip man! but how you get the state synchronously?
I mean, the app startup in splash the first time and how you know if the AsyncStorage already return to show the correct screen?

**Comment by GantMan** [comment]
make sure your initial reduce shape is always different from what could be stored.

For instance.  Have `userLoggedIn` INITIAL_STATE be `null`.   Now when it flips to `true/false` you know you're dealing with useful data.

**Comment by bielcapanema** [comment]
I see, but if is the first time that I open the App and the userLoggedIn is really null? 
You have some example or open source app that you can share with me?
Big thanks!

**Comment by GantMan** [comment]
I'll make this a task, and see if I can get an IR dev to add it to Ignite.

**Comment by jsheets** [comment]
I've tried to set up my app exactly like this, but am having trouble trapping the final STARTUP action. In my landing screen (whose only purpose is to check if the user is logged in, then route to the login or app screens), I am logging componentWillReceiveProps(). The app hits it before STARTUP fires, but the persisted state isn't loaded yet. Then I'm seeing the STARTUP action, but componentWillReceiveProps() is not called again to trigger my decision logic with the rehydrated data.

The strange thing is, the render() method sees the rehydrated data. But componentWillReceiveProps() is not called with those changes.

Does this make any sense? Am I missing some React lifecycle quirk in props loading? Isn't it enough to inject that state via mapStateToProps, e.g. `login: state.login`? 

Ironically I had this working in an older version of the ignite templates by throwing my custom Action from persistStore() in RehydrationServices.js, but that function has been refactored in recent template versions to do pretty much the same thing. It looks like it should work. I'm at a loss!

**Comment by skellock** [comment]
There's a couple issues around ReduxPersist timing.  We're going to have a closer look at this when it comes time to fix it up for Ignite 2.0.  Thank you.
