### ISSUE TITLE
Roadmap is out of date

### ISSUE THREAD

**Issue by Airblader** [infinitered/ignite#418]
The [Roadmap](https://github.com/infinitered/ignite/wiki/Roadmap) seems to be quite a bit out of date. It should be updated, removed or at least marked as out of date.

**Comment by GantMan** [comment]
Updated!  Thanks for the call out on that, we've been so busy we missed it.

Please let me know what you think of the updated version, and if we're missing anything that looks key: 
https://github.com/infinitered/ignite/wiki/Roadmap

**Comment by Airblader** [comment]
Great, thanks. As a newcomer looking at the roadmap was something I did, so having up to date information there can be vital for somebody to get an overview of the current status. :-)

I'll close this ticket now that it's been updated. I'm not really deep enough in Ignite to judge the correctness myself.
