### ISSUE TITLE
Yarn

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#425]
Test yarn, and make sure it works.

THEN:  Update docs to have yarn examples.
THEN: Open discussion ticket on moving internal `npm` commands to `yarn`

https://code.facebook.com/posts/1840075619545360
https://yarnpkg.com/en/compare

**Comment by GantMan** [comment]
@juddey - you and several others suggested this :)

**Comment by juddey** [comment]
Well, it was more that it might be worth taking a look at and evaluating, but hey, if it works, lets jump in with both 🐾 .

**Comment by GantMan** [comment]
looks like we're awaiting an update for yarn before we go forward any further.  Yarn latest is kinda broken.

**Comment by zberkom** [comment]
Yeah, currently the yarn `run` command is borked, but that should be fixed in the next version.

**Comment by GantMan** [comment]
Version 16.1 is out for yarn
