### ISSUE TITLE
Does not work with Youtube Player

### ISSUE THREAD

**Issue by PraveenVignesh** [infinitered/ignite#426]
Hi, 

I have been trying to integrate `react-native-youtube` to play youtube video.

But the video paused with error "UNAUTHORIZED_OVERLAY". 

When I debug further, There is conflict between react-native-drawer and react-native-youtube.

My `ignite doctor` output,

```
Computer
  Platform: darwin

Ignite
  Version: 1.5.0
  Path: /usr/local/bin/ignite

Node
  Version: v6.2.1
  Path: /Users/praveen-3001/.nvm/versions/node/v6.2.1/bin/node

NPM
  Version: 3.9.3
  Path: /Users/praveen-3001/.nvm/versions/node/v6.2.1/bin/npm

Yeoman
  Version: 1.5.1

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.33.1
```

**Comment by prabakarviji** [comment]
@revaret is this the same issue we faced?

**Comment by JeevPRobinson** [comment]
Seems like the same one @prabakarviji. Any progress on this?

**Comment by GantMan** [comment]
do you have an example project I can pull down?

**Comment by skellock** [comment]
Someone in #170 had mentioned that they had to remove the drawer for this to work.
