### ISSUE TITLE
~/App/Sounds - Implemented?

### ISSUE THREAD

**Issue by dovy** [infinitered/ignite#428]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.
- [ ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [X] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

```
Computer
  Platform: darwin

Ignite
  Version: 1.9.1
  Path: /usr/local/bin/ignite

Node
  Version: v6.1.0
  Path: /usr/local/bin/node

NPM
  Version: 3.8.6
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.4

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.34.1
```

I notice you have a Sounds folder within ~/App/Sounds. I was curious if there's any intention to add support for like https://github.com/zmxv/react-native-sound or anything of the likes? Need to play some audio bites here.  ;)

**Comment by GantMan** [comment]
currently no sounds folder yet, but a sounds example should be easy.

**Comment by dovy** [comment]
This project was the only one I could get working easily, though it's iOS only.

https://github.com/mikehedman/react-native-simple-sound

I think it would be great to bake this in. If you have an example with sound, I'd love to see it.

**Comment by skellock** [comment]
I think would make a great plugin for Ignite 2.
