### ISSUE TITLE
FR: Add support for React Native Web?

### ISSUE THREAD

**Issue by tomsdev** [infinitered/ignite#429]
Hi, have you considered adding support for the Web as an additional platform? What work needs to be done to add an additional platform to ignite?

The most popular library that provide Web support for React Native code is:
https://github.com/necolas/react-native-web

Here is an example application that targets both Web, iOS and Android with the same code:
https://github.com/grigio/HAgnostic-News

**Comment by GantMan** [comment]
Would love to explore with this.  Please report any findings if you research before me.

**Comment by skellock** [comment]
I'd love to see something like this come through.  It's probably a better fit as a plugin or generators.

It blows my mind how compatible `react-native` and `react-native-web` are.

**Comment by zzz945** [comment]
https://github.com/zzz945/react-native-web-boilerplate
I added web support to Ignite app, sharing redux saga and other logic code.

**Comment by jamonholmgren** [comment]
@zzz945 That looks sweet!
