### ISSUE TITLE
Swiping to the edge shows the previous screen

### ISSUE THREAD

**Issue by mykelaballe** [infinitered/ignite#433]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [ ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ x ] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

![swipe left](https://cloud.githubusercontent.com/assets/22584900/19448627/3cd8d590-94d5-11e6-9e38-96e025110837.jpeg)

Is this a feature in Ignite? Coz its a bit annoying for users especially those phones that are very sensitive, event swiping close to the edge displays the previous screen. Also my app shows the login screen when swiping from the index screen which has 4 tabs. Basically whichever tab i swipe to the edge, it shows the login screen behind it, it looks like your peeling something

**Comment by mykelaballe** [comment]
oh so its really a bug and still a todo. is there any temporary workaround for this?

**Comment by kevinvangelder** [comment]
React-Native-Router-Flux, which currently powers the Ignite Navigation, has a [`panHandlers` property](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#gestures) you can set to `null` on each `scene` you wish to disable swipe-back behavior for **or** (my preference) you can set your Home Scene and your Login Scene to [`type="replace"`](https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#scene) which will automatically prevent the user from going backwards on the navigation stack.

**Comment by GantMan** [comment]
:+1:

**Comment by mykelaballe** [comment]
can give a sample code? not sure where to put those codes.

Below is my some snippet from my NavigationRouter.js file

![image](https://cloud.githubusercontent.com/assets/22584900/19463759/4abad416-9529-11e6-808c-906f11118faa.png)

**Comment by mykelaballe** [comment]
doesnt work

**Comment by kevinvangelder** [comment]
@mykelaballe You should be able to put `type="replace"` on both your `login` scene and your `Home` scene.
