### ISSUE TITLE
How to programmatically go to home screen?

### ISSUE THREAD

**Issue by mykelaballe** [infinitered/ignite#434]
Actually this is more of a question rather than an issue. Not so sure also if this is the right repo to post this question. But anyway, i was just wondering how can i programmatically go to the device's home screen, like pressing the physical home button? tnx and more power

**Comment by kevinvangelder** [comment]
http://stackoverflow.com/questions/34801664/how-do-i-exit-shut-down-a-react-native-app

**Comment by GantMan** [comment]
Yup @mykelaballe - iOS doesn't really allow this much at all.   But you can do it in Android! :)
