### ISSUE TITLE
Authentication Example

### ISSUE THREAD

**Issue by leesolway** [infinitered/ignite#435]
Ignite has some awesome examples but one thing missing for me is how to manage login (auth) flow. It would be great to see examples built using this project template.

Some of the common problems i have faced in most apps include:
- Auth token is stored but how is it used for API requests
- How to route when a user is not logged in
- How to manage the refresh token e.g. when to fire it, how to buffer the request etc.

This request may be out of scope, i just feel these are very common tasks that could be shown and very helpful.

**Comment by skellock** [comment]
![image](https://cloud.githubusercontent.com/assets/68273/23340200/3955154a-fc00-11e6-9410-0fd3b904cd6b.png)

@derekgreenberg will be putting together a post/guide for us!

**Comment by vincejah** [comment]
Hi @skellock @derekgreenberg,

When do you expect to have this post/guide ready?

**Comment by skellock** [comment]
I'm not sure.  It's certainly a popular question.

**Comment by GantMan** [comment]
@derekgreenberg ping

**Comment by WorldWideWebb** [comment]
bump

**Comment by skellock** [comment]
kapow

**Comment by vesper8** [comment]
want this too! would be especially nice if there was an example using jwt.. something like this
https://github.com/joshgeller/react-native-jwt

**Comment by tmaly1980** [comment]
@skellock , does the "kapow" mean someone came up with some documentation? Where would that be?

Assuming it's not ready yet, I'm looking through the following articles to try and make something work as seamlessly as possible with the ignite boilerplate:

http://blog.slatepeak.com/build-a-react-redux-app-with-json-web-token-jwt-authentication/
https://www.theodo.fr/blog/2017/03/how-to-create-an-authentication-system-and-a-persistent-user-session-with-react-native/
https://medium.com/@alexmngn/the-essential-boilerplate-to-authenticate-users-on-your-react-native-app-f7a8e0e04a42

The first one has a higher order component that allows for "protected" screens and "public" screens so the user is prompted for a login if they are trying to access protected content (and not signed in), and if not wrapped, then don't try to authenticate. I'm not 100% sure how this would integrate yet with react-native-navigation.

The third one specifically goes over a neat idea on how to deal with keeping the tokens refreshed. In the past I would have a complex fetch() wrapper that would try to refresh the token if the server said it was expired, then try the request again. This other way does the refreshing in the background and pays attention to the expiration date to make it automagic.

**Comment by tmaly1980** [comment]
@skellock , @derekgreenberg  is this example done? I've looked through ignite-example-login and that doesn't seem to have anything that handles JWT tokens (storing, adding to headers, refreshing), for example.

**Comment by tmaly1980** [comment]
One thing that also needs to be considered is if the server end returns a JWT-related auth error (ie invalid token), there should be something globally at the api error to handle this, rather than have code in each/every saga action.

**Comment by trda** [comment]
I dare say 2.0 release doesn't include it, too ?

**Comment by ruddell** [comment]
@trda In my [Ignite JHipster](https://github.com/ruddell/ignite-jhipster) boilerplate, I have a JWT authentication option.  It usually expects a [JHipster](http://www.jhipster.tech/) server backend, but the logic should still apply.  Just a quick summary of how it works:

Link to sample app repo: https://github.com/ruddell/IgniteJhipsterSampleApp

- [StartupSagas](https://github.com/ruddell/IgniteJhipsterSampleApp/blob/811c59f471c6d22e80992e5f445594f83c414e96/App/Sagas/StartupSagas.js#L31-L32) loads the token if present
  - If token is present, gets account information and sets API auth header
- [DrawerContent](https://github.com/ruddell/IgniteJhipsterSampleApp/blob/811c59f471c6d22e80992e5f445594f83c414e96/App/Containers/DrawerContent.js#L52-L59) shows different options based on authentication
  - If not authenticated, show links to Login, Register, Forgot PW 
  - If authenticated, show links to Settings, Logout
- [LoginScreen](https://github.com/ruddell/IgniteJhipsterSampleApp/blob/811c59f471c6d22e80992e5f445594f83c414e96/App/Containers/LoginScreen.js) contains the login form (from Ignite v1)
- [Sagas/index.js](https://github.com/ruddell/IgniteJhipsterSampleApp/blob/811c59f471c6d22e80992e5f445594f83c414e96/App/Sagas/index.js#L38-L40) links LoginRedux actions to LoginSagas
- [LoginSagas.login](https://github.com/ruddell/IgniteJhipsterSampleApp/blob/811c59f471c6d22e80992e5f445594f83c414e96/App/Sagas/LoginSagas.js#L7-L25) calls the API endpoint which returns a JWT token if credentials are valid
This token is added as a header in [Api.js](https://github.com/ruddell/IgniteJhipsterSampleApp/blob/811c59f471c6d22e80992e5f445594f83c414e96/App/Services/Api.js#L38-L39)
- Any sagas calling APIs that require authentication are wrapped in the [CallApi saga](https://github.com/ruddell/IgniteJhipsterSampleApp/blob/811c59f471c6d22e80992e5f445594f83c414e96/App/Sagas/CallApiSaga.js) that will show the login screen if a 401 error happens (token expired)
  - If not re-authenticated, cancel the request
  - If re-authenticated, retry the request with the new JWT Token
  - I got this concept from [this apisauce issue](https://github.com/infinitered/apisauce/issues/116#issuecomment-316318339).

**Comment by vzpintor** [comment]
Somebody has an example from authentication flow with ignite bowser, I'm try to use this flow https://reactnavigation.org/docs/en/auth-flow.html but, not working it.

I'm relative new using ignite and I don't have much idea that how can I it

Please somebody that help me

**Comment by scinfu** [comment]
+1

**Comment by rohitnishad613** [comment]
+1 JWT auth

**Comment by abikali** [comment]
+1

**Comment by malistedifito** [comment]
Hi,
I found some login example, hope it helps: https://pietrzakadrian.com/blog/react-native-authentication-flow-with-mobx-state-tree
