### ISSUE TITLE
Warning flattenChildren: Encountered two children with the same key

### ISSUE THREAD

**Issue by TimMeade** [infinitered/ignite#438]
Just installed yesterday:  everything else seems to work fine.

Android build to Genymotion emulator.

I found two references to this in other issues, but do not see a fix.  

Warning: flattenChildren(...): Encountered two children with the same key, `1$Full button`. Child keys must be unique:

```
Computer
  Platform: darwin

Ignite
  Version: 1.9.1
  Path: /usr/local/bin/ignite

Node
  Version: v6.9.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.8
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.34.1
```

**Comment by GantMan** [comment]
this is fixed in 1.9.2  which will be released this week 👍
