### ISSUE TITLE
Yarn the install

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#440]
As of right now, when you ignite a new project we're installing with `npm`.

As you might guess, this is sloowwwwwww.

We'd love to detect if you have yarn installed.  If you do, we use it, if not we use npm.

The detection should be shared for other generators, but the ultimate place it should be used for now, is our app generator.

**Comment by iraquitan** [comment]
Hi, I'd like to try this out. Can you give me a quick start on where should I work on (ignite/ignite-generator/src/app/index.es)?

**Comment by GantMan** [comment]
Sure!   First read this:  https://github.com/infinitered/ignite/wiki/Intro-to-Contributing-to-Ignite
Then, let me know your questions.  I'll answer them by updating the doc so that future contributors will know!

**Comment by skellock** [comment]
In ignite 2, we detect yarn and install using it (where we can -- sometimes it's just broken!)
