### ISSUE TITLE
1.10.0 Broken

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#445]
Even though testRelease passed, 1.10.0 broke somehow with Maps.

This needs to be fixed ASAP

**Comment by VinSpee** [comment]
hehe I was just wondering about this… Glad I'm not crazy :-)

**Comment by GantMan** [comment]
https://github.com/airbnb/react-native-maps/issues/371

Looks like maps broke it.

**Comment by GantMan** [comment]
I think I'm going to disable maps and release soon.

**Comment by GantMan** [comment]
Released 1.10.1 with no maps.
