### ISSUE TITLE
android-23 missing

### ISSUE THREAD

**Issue by FezVrasta** [infinitered/ignite#448]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code
  - [x] not sure

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

I just installed ignite and started the app with `react-native run-android` but I get the below error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> failed to find target with hash string 'android-23' in: /usr/local/opt/android-sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I installed the `android-sdk` with `brew` but I can't find a way to install the version 23, I have only the 24.

```
Computer
  Platform: darwin

Ignite
  Version: 1.10.1
  Path: /Users/<user>/.nvm/versions/node/v6.9.1/bin/ignite

Node
  Version: v6.9.1
  Path: /Users/<user>/.nvm/versions/node/v6.9.1/bin/node

NPM
  Version: 3.10.8
  Path: /Users/<user>/.nvm/versions/node/v6.9.1/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.35.0
```

**Comment by FezVrasta** [comment]
So, seems like the `android` command didn't install the correct packages, I'm installing them manually 1 by 1...

**Comment by GantMan** [comment]
Yup!  Looks like you're missing android version 23.

You might have 2 versions of android on your system.  Always check for that.

Please update us if everything works once you have android 23!

**Comment by FezVrasta** [comment]
Yes now it works, it's just weird because the installer said that it would have installed everything needed...

**Comment by GantMan** [comment]
Gonna make this a task then.

When you ignite a project, it should check for `which android` and `android list | grep "android-23"`
If either of those two are missing, a warning will be displayed to the user that they must install them.

**Comment by GantMan** [comment]
Side note:  grep will fail on windows, so detect via JavaScript and not grep

**Comment by rahmanadianto** [comment]
I got this error when run "ignite new <App>". I am sure I have installed android sdk 23, is it because Android have removed command line tool? 

I got this when try "android list"
The android command is no longer available.
For manual SDK and AVD management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
