### ISSUE TITLE
How to enable hot-reload?

### ISSUE THREAD

**Issue by FezVrasta** [infinitered/ignite#449]
### Hiya! So you think it's broken or missing a feature eh?

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [x] ignite the cli
  - [ ] ignite generated code

How to enable hot-reload or at least auto reload?

**Comment by GantMan** [comment]
Press command + D on iOS or command + M on Android, then select hot-reload or automatic reload.

On device you can shake device to get the developer menu as well.

**Comment by jackywhlee** [comment]
@GantMan Hey, where in the documentations does it tell you about the "command + M" on Android? I'm surprised I had to go into Github issues to find the solution, when this answer ought to be in the documentations, or maybe it is but I failed to find it.

**Comment by GantMan** [comment]
Good question.  I'm sure everyone would take a readme update pull-request if you can identify where that _should_ be stated.

It's one of those things people learn and then take for granted ☹️

**Comment by jackywhlee** [comment]
I'm actually in the process of selecting a react-native boilerplate to migrate our reactboilerplate app into, so I know just about as much as the next person who stumbled upon this repo. 

Finding youtube tutorial videos was challenging too, as it seems there are two marketing names? Infinite Red? It's a bit overwhelming to a new user, with a lot of searching around to do.

Would highly suggest to update the README.md with updated documentations and perhaps youtube videos too, i.e. https://www.youtube.com/watch?v=lv00UOXxy0g ought to include the name Ignite in its title, and the video itself doesn't show how hot-reload is enabled, it sort of enabled itself through a pre-script in fast-forward.

Sorry for the rant. Just hoping to provide some helpful feedback.

**Comment by kevinvangelder** [comment]
[Hot reloading is a react native feature](http://facebook.github.io/react-native/releases/0.43/docs/debugging.html#accessing-the-in-app-developer-menu) and the keyboard shortcuts don't change in Ignite. That said, we should probably link to the React Native documentation somewhere in the readme so new users can learn the React Native basics directly from the source.

**Comment by Moji0098** [comment]
how to enlble hot-reload on real device not virtual device .. thank you

**Comment by fabriziobertoglio1987** [comment]
@Moji0098  on android `adb shell input keyevent 82`
