### ISSUE TITLE
[RFC] An easy way/script to include fonts

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#45]
rnpm can include fonts if they are in an imported package... I'm interested in a way to use that, or other means to include fonts in Android/iOS from an command in the current project.

**Comment by skellock** [comment]
That's a great idea.

`ignite font add ~/Downloads/comicsans.ttf`

**Comment by kevinvangelder** [comment]
For reference, here are how-to articles.
Android: https://medium.com/@gattermeier/custom-fonts-in-react-native-for-android-b8a331a7d2a7#.ii4ol2yee
iOS: https://medium.com/@gattermeier/custom-fonts-in-react-native-for-android-b8a331a7d2a7#.ii4ol2yee

**Comment by jan-happy** [comment]
+1

**Comment by RWOverdijk** [comment]
👍

**Comment by skellock** [comment]
Ya, this would be awesome.  I could have used this on every project.  Anyone want to tackle this as an Ignite 2 plugin?

**Comment by rcalabro** [comment]
+1

**Comment by marionety** [comment]
+1

**Comment by jkao1** [comment]
+1

**Comment by emech-en** [comment]
Any workaround for this?

**Comment by jamonholmgren** [comment]
I'd love to have help with this.

```
ignite font add ~/Downloads/comicsans.ttf
ignite font remove comicsans
```

That would be a great addition to Ignite.

You'd need to add a command, in the `src/commands` folder:

```
src
  |- commands
      |- font
          |- font.ts
          |- add.ts
          |- remove.ts
          |- list.ts
```

Something like that.

**Comment by kevinvangelder** [comment]
Hey everyone, I believe this is no longer something Ignite should be concerned about as `react-native link` will handle any fonts/assets added to the `package.json`.
```json
  "rnpm": {
    "assets": [
      "./src/theme/fonts/"
    ]
  }
```
