### ISSUE TITLE
Running React Native setup version 0.35.0 fails during ignite

### ISSUE THREAD

**Issue by faisalkanji** [infinitered/ignite#453]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [ x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [x ] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

Hello 
I am trying to ignite a new app, but when I "ignite new testapp" there is an x next to the "Running React Native setup version 0.35.0" line and the appropriate folders are not generated in the test app folder. There is also an x next to the "linking external libs" line

The output for my ignite doctor is: 
```
Computer
  Platform: linux

Ignite
  Version: 1.10.1
  Path: /home/kanjif/.nvm/versions/node/v6.8.1/bin/ignite

Node
  Version: v6.8.1
  Path: /home/kanjif/.nvm/versions/node/v6.8.1/bin/node

NPM
  Version: 3.10.8
  Path: /home/kanjif/.nvm/versions/node/v6.8.1/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.35.0
```

Thank You

**Comment by GantMan** [comment]
can you copy and paste what fails and what the error is?

**Comment by faisalkanji** [comment]
✔︎ Finding react-native
✔︎ Finding git
✔︎ Getting ready for guests
𝗫 Running React Native setup version 0.35.0 (~ 2 minutes-ish)
✔︎ Downloading latest Ignite files from https://github.com/infinitered/ignite.git
✔︎ Using ignite release 1.10.1
⠋ Using ignite release 1.10.1rm: could not remove file (code EACCES): node_modules//.bin/bin-version-check
rm: could not remove file (code EACCES): node_modules//.bin/dateformat
rm: could not remove file (code EACCES): node_modules//.bin/detect-newline
rm: could not remove file (code EACCES): node_modules//.bin/escodegen
rm: could not remove file (code EACCES): node_modules//.bin/esgenerate
rm: could not remove file (code EACCES): node_modules//.bin/esparse
rm: could not remove file (code EACCES): node_modules//.bin/esvalidate
rm: could not remove file (code EACCES): node_modules//.bin/find-versions
rm: could not remove file (code EACCES): node_modules//.bin/github-username
rm: could not remove file (code EACCES): node_modules//.bin/har-validator
rm: could not remove file (code EACCES): node_modules//.bin/ignite
rm: could not remove file (code EACCES): node_modules//.bin/mkdirp
rm: could not remove file (code EACCES): node_modules//.bin/nopt
rm: could not remove file (code EACCES): node_modules//.bin/os-name
rm: could not remove file (code EACCES): node_modules//.bin/osx-release
rm: could not remove file (code EACCES): node_modules//.bin/pretty-bytes
rm: could not remove file (code EACCES): node_modules//.bin/rc
rm: could not remove file (code EACCES): node_modules//.bin/rimraf
rm: could not remove file (code EACCES): node_modules//.bin/seek-bunzip
rm: could not remove file (code EACCES): node_modules//.bin/seek-table
rm: could not remove file (code EACCES): node_modules//.bin/semver
rm: could not remove file (code EACCES): node_modules//.bin/shjs
rm: could not remove file (code EACCES): node_modules//.bin/sshpk-conv
rm: could not remove file (code EACCES): node_modules//.bin/sshpk-sign
rm: could not remove file (code EACCES): node_modules//.bin/sshpk-verify
rm: could not remove file (code EACCES): node_modules//.bin/strip-dirs
rm: could not remove file (code EACCES): node_modules//.bin/strip-indent
rm: could not remove file (code EACCES): node_modules//.bin/strip-json-comments
rm: could not remove file (code EACCES): node_modules//.bin/tabtab
rm: could not remove file (code EACCES): node_modules//.bin/twigjs
rm: could not remove file (code EACCES): node_modules//.bin/uuid
rm: could not remove file (code EACCES): node_modules//.bin/which
rm: could not remove file (code EACCES): node_modules//.bin/yeoman-character
rm: could not remove file (code EACCES): node_modules//.bin/yo
rm: could not remove file (code EACCES): node_modules//.bin/yo-complete
rm: could not remove file (code EACCES): node_modules//.bin/yodoctor
rm: could not remove file (code EACCES): node_modules//.bin/yosay
rm: could not remove directory (code EACCES): node_modules//.bin
rm: could not remove directory (code ENOTEMPTY): node_modules/
✔︎ Pre-rinse
✔︎ Copying Ignite goodies
   create app/README.md
    force app/package.json
   create app/.babelrc
   create app/.env
   create app/.ignite
   create app/index.ios.js
   create app/index.android.js
   create app/.editorconfig
   create app/Tests/Components/AlertMessageTest.js
   create app/Tests/Components/DrawerButtonTest.js
   create app/Tests/Components/FullButtonTest.js
   create app/Tests/Components/RoundedButtonTest.js
   create app/Tests/Reducers/LoginReducerTest.js
   create app/Tests/Reducers/TemperatureReducerTest.js
   create app/Tests/Sagas/LoginSagaTest.js
   create app/Tests/Sagas/StartupSagaTest.js
   create app/Tests/Sagas/TemperatureSagaTest.js
   create app/Tests/Services/FixtureAPITest.js
   create app/Tests/Setup.js
   create app/App/Components/AlertMessage.js
   create app/App/Components/DrawerButton.js
   create app/App/Components/FullButton.js
   create app/App/Components/MapCallout.js
   create app/App/Components/README.md
   create app/App/Components/RoundedButton.js
   create app/App/Components/Styles/AlertMessageStyle.js
   create app/App/Components/Styles/DrawerButtonStyles.js
   create app/App/Components/Styles/FullButtonStyle.js
   create app/App/Components/Styles/MapCalloutStyle.js
   create app/App/Components/Styles/README.md
   create app/App/Components/Styles/RoundedButtonStyle.js
   create app/App/Config/AppConfig.js
   create app/App/Config/DebugSettings.js
   create app/App/Config/index.js
   create app/App/Config/PushConfig.js
   create app/App/Config/ReactotronConfig.js
   create app/App/Config/README.md
   create app/App/Config/ReduxPersist.js
   create app/App/Containers/AllComponentsScreen.js
   create app/App/Containers/APITestingScreen.js
   create app/App/Containers/App.js
   create app/App/Containers/DeviceInfoScreen.js
   create app/App/Containers/DrawerContent.js
   create app/App/Containers/ListviewExample.js
   create app/App/Containers/ListviewGridExample.js
   create app/App/Containers/ListviewSectionsExample.js
   create app/App/Containers/LoginScreen.js
   create app/App/Containers/MapviewExample.js
   create app/App/Containers/PresentationScreen.js
   create app/App/Containers/README.md
   create app/App/Containers/RootContainer.js
   create app/App/Containers/Styles/AllComponentsScreenStyle.js
   create app/App/Containers/Styles/APITestingScreenStyle.js
   create app/App/Containers/Styles/DeviceInfoScreenStyle.js
   create app/App/Containers/Styles/DrawerContentStyle.js
   create app/App/Containers/Styles/ListviewExampleStyle.js
   create app/App/Containers/Styles/ListviewGridExampleStyle.js
   create app/App/Containers/Styles/LoginScreenStyle.js
   create app/App/Containers/Styles/MapviewExampleStyle.js
   create app/App/Containers/Styles/PresentationScreenStyle.js
   create app/App/Containers/Styles/README.md
   create app/App/Containers/Styles/RootContainerStyle.js
   create app/App/Containers/Styles/ThemeScreenStyle.js
   create app/App/Containers/Styles/UsageExamplesScreenStyle.js
   create app/App/Containers/ThemeScreen.js
   create app/App/Containers/UsageExamplesScreen.js
   create app/App/Fixtures/boise.json
   create app/App/Fixtures/README.md
   create app/App/Fixtures/toronto.json
   create app/App/I18n/af.json
   create app/App/I18n/am.json
   create app/App/I18n/ar.json
   create app/App/I18n/bg.json
   create app/App/I18n/ca.json
   create app/App/I18n/cs.json
   create app/App/I18n/da.json
   create app/App/I18n/de.json
   create app/App/I18n/el.json
   create app/App/I18n/english.json
   create app/App/I18n/es.json
   create app/App/I18n/et.json
   create app/App/I18n/fi.json
   create app/App/I18n/fil.json
   create app/App/I18n/fr.json
   create app/App/I18n/he.json
   create app/App/I18n/hi.json
   create app/App/I18n/hr.json
   create app/App/I18n/hu.json
   create app/App/I18n/I18n.js
   create app/App/I18n/id.json
   create app/App/I18n/it.json
   create app/App/I18n/ja.json
   create app/App/I18n/ko.json
   create app/App/I18n/lt.json
   create app/App/I18n/lv.json
   create app/App/I18n/ms.json
   create app/App/I18n/nb.json
   create app/App/I18n/nl.json
   create app/App/I18n/no.json
   create app/App/I18n/pl.json
   create app/App/I18n/platform_languages.txt
   create app/App/I18n/pt.json
   create app/App/I18n/README.md
   create app/App/I18n/ro.json
   create app/App/I18n/ru.json
   create app/App/I18n/sk.json
   create app/App/I18n/sl.json
   create app/App/I18n/sr.json
   create app/App/I18n/sv.json
   create app/App/I18n/sw.json
   create app/App/I18n/th.json
   create app/App/I18n/tr.json
   create app/App/I18n/uk.json
   create app/App/I18n/vi.json
   create app/App/I18n/zh.json
   create app/App/I18n/zu.json
   create app/App/Images/BG.png
   create app/App/Images/ignite_logo.png
   create app/App/Images/ir.png
   create app/App/Images/tile_bg.png
   create app/App/Images/top_logo.png
   create app/App/Images/top_logo@2x.png
   create app/App/Images/top_logo@3x.png
   create app/App/Lib/MapHelpers.js
   create app/App/Lib/README.md
   create app/App/Lib/Utilities.js
   create app/App/Navigation/NavigationDrawer.js
   create app/App/Navigation/NavigationRouter.js
   create app/App/Navigation/NavItems.js
   create app/App/Navigation/Styles/NavigationContainerStyle.js
   create app/App/Navigation/Styles/NavigationDrawerStyle.js
   create app/App/Navigation/Styles/NavItemsStyle.js
   create app/App/Redux/CreateStore.js
   create app/App/Redux/index.js
   create app/App/Redux/LoginRedux.js
   create app/App/Redux/StartupRedux.js
   create app/App/Redux/TemperatureRedux.js
   create app/App/Sagas/index.js
   create app/App/Sagas/LoginSagas.js
   create app/App/Sagas/StartupSagas.js
   create app/App/Sagas/TemperatureSagas.js
   create app/App/Services/Api.js
   create app/App/Services/ExamplesRegistry.js
   create app/App/Services/FixtureApi.js
   create app/App/Services/ImmutablePersistenceTransform.js
   create app/App/Services/RehydrationServices.js
   create app/App/Themes/ApplicationStyles.js
   create app/App/Themes/Colors.js
   create app/App/Themes/Fonts.js
   create app/App/Themes/Images.js
   create app/App/Themes/index.js
   create app/App/Themes/Metrics.js
   create app/App/Themes/README.md
   create app/App/Transforms/ConvertFromKelvin.js
   create app/App/Transforms/README.md
   create app/fastlane/Appfile
   create app/fastlane/Fastfile
   create app/fastlane/Matchfile
✔︎ Installing Ignite dependencies (~ 1 minute-ish)
𝗫 Linking external libs
⠋ Linking external libs/bin/sh: 1: plutil: not found
✔︎ Updating PList file
⠋ Updating PList filecd: no such file or directory: app/android
/bin/sh: 1: ./gradlew: not found
✔︎ Cleaning up after messy guests

**Comment by faisalkanji** [comment]
Yes running a test project in React Native works perfectly

**Comment by faisalkanji** [comment]
Got it to work by uninstalling React Native and Ignite and then reinstalling them both

**Comment by GantMan** [comment]
wow, hah
