### ISSUE TITLE
Base application fails to build when paths are too long for drawings

### ISSUE THREAD

**Issue by MatthiasDebaere** [infinitered/ignite#455]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

So this is actually already fixed as I already found a solution to the issue, but, just for anyone having trouble in the future:

When I ingited a new project, react-native run-android on the generated base application. The error was too long to make any sense, but, after trying different things (updated yo, node, ..) I found out it was because of the long path/file names. So I ignited an other project, with a shorter path (c:/myIgniteProject) and things worked just fine from the start.

(More info: more specifically, it had to do with drawings that, I believe, react-native-device-info adds)

Greetings and thanks for Ignite!

**Comment by skellock** [comment]
Thanks for the heads up!
