### ISSUE TITLE
Make `import imagesfile` work with subdirectories of /Images 

### ISSUE THREAD

**Issue by amedeedaboville** [infinitered/ignite#456]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite generated code

Hi,
I would like to add a feature to the imagesfile generator to be able to work with subdirectories within the images directory.

This would basically be changing https://github.com/infinitered/ignite/blob/master/ignite-generator/src/imagesfile/index.es to recursively traverse directories.

It could prepend the directory name to the object key with a separator (ideally '/')
The current behavior is that the generator lists all files in a directory, and adds a require() call for each, even if the file is a directory.

Additionally: why not make the import work like this:
- Don't change any filenames (no camelcasing, replacing spaces etc)
- Recursively go through every directory in Images
- Make a Map out of filename: image

For example an image in `App/Images/loading-icons/BigLoadingIcon@2x.png` would be put in the images Map as 

```
{'loading-icons/BigLoadingIcon@2x.png': require('../Images/loading-icons/BigLoadingIcon@2x.png')}
```

Then, as developers we could use `<Image source=images[image_filename] />` and get around the very irritating lack of dynamic image imports in RN.

**Comment by GantMan** [comment]
awesome!  this is great feedback!

**Comment by fvonhoven** [comment]
I'm going to tackle this soon, but just for brainstorming purposes and feedback:
 - How about the option to maintain folder structure on import?

**Comment by jamonholmgren** [comment]
@fvonhoven Still planning to knock this out?

**Comment by fvonhoven** [comment]
@jamonholmgren I've got a full workload atm...feel free to tackle this one! 👍

**Comment by jamonholmgren** [comment]
This issue no longer applies to Ignite; closing.
