### ISSUE TITLE
Delete Actions for Weather and Login at startup

### ISSUE THREAD

**Issue by Talkwondo** [infinitered/ignite#457]
Hi,
I have another Login method and everytime i run the App I see the this code in the debugger.
I tried to delete the actions but then an error occurred.
<img width="539" alt="screen shot 2016-10-27 at 17 12 42" src="https://cloud.githubusercontent.com/assets/20122139/19771308/2d8b42c4-9c6b-11e6-9b88-781a8d9f461e.png">

Please help.

Thanks,

**Comment by skellock** [comment]
I'm not entirely use what you're saying here.  If you're stuck, please don't hesitate to reopen.

I think there are some issues with our code connecting to the temperature service (tokens).  We're going to be changing the example to use github or something a little less hostile.
