### ISSUE TITLE
Ignite crashes on iOS versions less than 9.2 due to react-native-config

### ISSUE THREAD

**Issue by ipavl** [infinitered/ignite#459]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

I'm encountering an issue after exporting Ignite-based apps to .ipa files for ad-hoc distribution on iOS devices in which the "Powered by React Native" screen is displayed for a second and then the app closes. The closest thing I have been able to find is [this StackOverflow thread](https://stackoverflow.com/questions/35785747/react-native-ios-app-crashes-without-report). Extracting the .ipa file shows that there is a minified JS bundle in it, but I haven't yet figured out how to build an .ipa with a non-minified bundle to compare.

I followed the "Building your app for production" section on the [Running on Device](https://facebook.github.io/react-native/docs/running-on-device-ios.html) page of the React Native docs (except for the section on ATS as I could not find that key in the project using grep) and then exported the app through Xcode's `Product > Archive` menu and selected Ad-hoc distribution to generate the .ipa.

This affects the base project generated by `ignite new project`. I tried using just `react-native init project` and that works fine as an .ipa.

`ignite doctor` output:

```
Computer
  Platform: darwin

Ignite
  Version: 1.10.1
  Path: /usr/local/bin/ignite

Node
  Version: v6.7.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.7
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: 0.35.0
```

**Comment by GantMan** [comment]
Hiya @ipavl - Let's figure out this issue right?

Firstly, have you tried running on device but not as an IPA?  I ask because, that's usually how I debug device failures.  It's helpful to stay connected to device and see those logs and debug!

Secondly, I've seen this issue 2 times.  Once it was my rehydration of redux that was stopping crashes, so when I went to a device with no redux, I saw the issue.  You can mimic this locally by resetting your simulator as if it were a new device.

The other time this happened, it was a component I was using, and someone had filed a ticket on the component repo saying so.  Which saved me hours of narrowing down what component was misbehaving.  I forgot which one it was, now, but worth looking into.

I hope those help, please report back with findings.

**Comment by GantMan** [comment]
@ipavl - any update?

**Comment by ipavl** [comment]
Hi @GantMan, thank you for your response. I haven't had a chance to try on a device directly yet, but I had no issues running the Ignite base application on a fresh simulator.

**Comment by GantMan** [comment]
gotcha.  Please run on device while tethered and let me know if you find anything.

**Comment by ipavl** [comment]
There were no issues running it on a device from Xcode as Debug or Release directly.

**Comment by GantMan** [comment]
that really doesn't make sense.   I'm not sure how you can debug the IPA.  Maybe add crashlytics or some other crash reporting 3rd party?

**Comment by ipavl** [comment]
**Short version**

react-native-config's deployment target is 9.2 and the device I originally tested on was on a lower iOS version than I thought (<9.2). Changing its deployment target makes the app run.

I'm currently trying to see if there's a way to lower react-native-config's deployment target for my project in a way that could be checked into Git, otherwise I might just end up removing it.

**Longer version**

I was able to reproduce this by running the Ignite base application on a simulator running iOS 8, which matches the device it was failing on (I thought it was on 10). iOS 10 works fine.

This is what Xcode displays when the app crashes/stops loading:

```
dyld: Symbol not found: ___NSDictionary0__

Referenced from: /Users/.../Library/Developer/CoreSimulator/Devices/.../data/Containers/Bundle/Application/.../test.app/test

Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation

in /Users/.../Library/Developer/CoreSimulator/Devices/.../data/Containers/Bundle/Application/.../test.app/test

(lldb)
```

Adding CoreFoundation.framework and making it optional as suggested in [this thread](https://stackoverflow.com/questions/6344560/dyld-symbol-not-found-error-how-to-resolve-this-issue) then results in a crash at `return DOT_ENV` of ReactNativeConfig.m:

```
- (NSDictionary *)constantsToExport {
    return DOT_ENV
}
```

From here I was able to find that the minimum iOS deployment target for react-native-config was 9.2. Changing it to 8 makes the app run, and removing CoreFoundation again still seems to work fine.

**Comment by GantMan** [comment]
Hopefully react-native-config will be fixed up soon. We plan on testing this with our plugin system.

**Comment by hchoong** [comment]
This is still an open issue on react-native-config https://github.com/luggit/react-native-config/issues/65

**Comment by skellock** [comment]
@hchoong has the work around for now.  Also `react-native-device-info` and `react-native-maps` does this too.  We'll look at overriding this in the plugins we create for these.
