### ISSUE TITLE
generator-react-native-ignite

### ISSUE THREAD

**Issue by shapik2004** [infinitered/ignite#467]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.
- [ ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [+ ] ignite base application
  - [ ] ignite the cli
  - [+ ] ignite generated code

ignite --version
1.10.1

> ignite new App
> 🔥 Setting App on FIRE! 🔥
> /usr/local/lib/node_modules/generator-react-native-ignite/node_modules/is-relative/index.js:1
> (function (exports, require, module, __filename, __dirname) { 

SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-react-native-ignite/node_modules/is-absolute/index.js:10:18)
    at Module._compile (module.js:573:32)

---

react-native init her
This will walk you through creating a new React Native project in /Users/check/her
Installing react-native package from npm...
Setting up new React Native app in /Users/check/her
her@0.0.1 /Users/check/her
└── react@15.3.2

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g
her@0.0.1 /Users/check/her
├─┬ babel-jest@16.0.0 
│ ├─┬ babel-plugin-istanbul@2.0.3 
│ │ ├── istanbul-lib-instrument@1.2.0 
│ │ └─┬ test-exclude@2.1.3 
│ │ └── require-main-filename@1.0.1 
│ └─┬ babel-preset-jest@16.0.0 
│ └── babel-plugin-jest-hoist@16.0.0 
├── babel-preset-react-native@1.9.0 
├─┬ jest@16.0.2 
│ └─┬ jest-cli@16.0.2 
│ ├── callsites@2.0.0 
│ ├─┬ is-ci@1.0.10 
│ │ └── ci-info@1.0.0 
│ ├─┬ istanbul-api@1.0.0-aplha.10 
│ │ ├── async@1.5.2 
│ │ ├─┬ fileset@0.2.1 
│ │ │ └── minimatch@2.0.10 
│ │ ├─┬ istanbul-lib-hook@1.0.0-alpha.4 
│ │ │ └── append-transform@0.3.0 
│ │ ├─┬ istanbul-lib-report@1.0.0-alpha.3 
│ │ │ ├── async@1.5.2 
│ │ │ ├── path-parse@1.0.5 
│ │ │ └─┬ supports-color@3.1.2 
│ │ │ └── has-flag@1.0.0 
│ │ ├── istanbul-lib-source-maps@1.0.2 
│ │ ├─┬ istanbul-reports@1.0.0 
│ │ │ └─┬ handlebars@4.0.5 
│ │ │ ├── async@1.5.2 
│ │ │ └── source-map@0.4.4 
│ │ └─┬ js-yaml@3.6.1 
│ │ ├── argparse@1.0.9 
│ │ └── esprima@2.7.3 
│ ├── istanbul-lib-coverage@1.0.0 
│ ├── jest-changed-files@16.0.0 
│ ├─┬ jest-config@16.0.2 
│ │ ├─┬ istanbul@0.4.5 
│ │ │ ├── async@1.5.2 
│ │ │ ├── esprima@2.7.3 
│ │ │ └── supports-color@3.1.2 
│ │ └── jest-environment-node@16.0.2 
│ ├─┬ jest-environment-jsdom@16.0.2 
│ │ └─┬ jsdom@9.8.3 
│ │ ├── abab@1.0.3 
│ │ ├── acorn@2.7.0 
│ │ ├─┬ acorn-globals@1.0.9 
│ │ │ └── acorn@2.7.0 
│ │ ├── array-equal@1.0.0 
│ │ ├── content-type-parser@1.0.1 
│ │ ├── cssom@0.3.1 
│ │ ├── cssstyle@0.2.37 
│ │ ├── html-encoding-sniffer@1.0.1 
│ │ ├── iconv-lite@0.4.13 
│ │ ├── nwmatcher@1.3.9 
│ │ ├── parse5@1.5.1 
│ │ ├─┬ request@2.76.0 
│ │ │ ├── aws-sign2@0.6.0 
│ │ │ ├── aws4@1.5.0 
│ │ │ ├── caseless@0.11.0 
│ │ │ ├─┬ combined-stream@1.0.5 
│ │ │ │ └── delayed-stream@1.0.0 
│ │ │ ├── forever-agent@0.6.1 
│ │ │ ├─┬ form-data@2.1.1 
│ │ │ │ ├── asynckit@0.4.0 
│ │ │ │ └─┬ mime-types@2.1.12 
│ │ │ │ └── mime-db@1.24.0 
│ │ │ ├─┬ har-validator@2.0.6 
│ │ │ │ └─┬ is-my-json-valid@2.15.0 
│ │ │ │ ├── generate-function@2.0.0 
│ │ │ │ ├─┬ generate-object-property@1.2.0 
│ │ │ │ │ └── is-property@1.0.2 
│ │ │ │ └── jsonpointer@4.0.0 
│ │ │ ├─┬ hawk@3.1.3 
│ │ │ │ ├── boom@2.10.1 
│ │ │ │ ├── cryptiles@2.0.5 
│ │ │ │ └── sntp@1.0.9 
│ │ │ ├─┬ http-signature@1.1.1 
│ │ │ │ ├── assert-plus@0.2.0 
│ │ │ │ ├─┬ jsprim@1.3.1 
│ │ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ │ └── verror@1.3.6 
│ │ │ │ └─┬ sshpk@1.10.1 
│ │ │ │ ├── asn1@0.2.3 
│ │ │ │ ├── assert-plus@1.0.0 
│ │ │ │ ├── bcrypt-pbkdf@1.0.0 
│ │ │ │ ├─┬ dashdash@1.14.0 
│ │ │ │ │ └── assert-plus@1.0.0 
│ │ │ │ ├── ecc-jsbn@0.1.1 
│ │ │ │ ├─┬ getpass@0.1.6 
│ │ │ │ │ └── assert-plus@1.0.0 
│ │ │ │ ├── jodid25519@1.0.2 
│ │ │ │ ├── jsbn@0.1.0 
│ │ │ │ └── tweetnacl@0.14.3 
│ │ │ ├── is-typedarray@1.0.0 
│ │ │ ├── isstream@0.1.2 
│ │ │ ├── json-stringify-safe@5.0.1 
│ │ │ ├── oauth-sign@0.8.2 
│ │ │ ├── qs@6.3.0 
│ │ │ └── stringstream@0.0.5 
│ │ ├── symbol-tree@3.1.4 
│ │ ├─┬ tough-cookie@2.3.2 
│ │ │ └── punycode@1.4.1 
│ │ ├── webidl-conversions@3.0.1 
│ │ ├─┬ whatwg-encoding@1.0.1 
│ │ │ └── iconv-lite@0.4.13 
│ │ ├─┬ whatwg-url@3.0.0 
│ │ │ └── tr46@0.0.3 
│ │ └── xml-name-validator@2.0.1 
│ ├── jest-file-exists@15.0.0 
│ ├── jest-haste-map@16.0.2 
│ ├─┬ jest-jasmine2@16.0.2 
│ │ ├─┬ jasmine-check@0.1.5 
│ │ │ └── testcheck@0.1.4 
│ │ └── jest-matchers@16.0.2 
│ ├── jest-mock@16.0.2 
│ ├─┬ jest-resolve@16.0.2 
│ │ └── jest-haste-map@16.0.2 
│ ├── jest-resolve-dependencies@16.0.2 
│ ├─┬ jest-runtime@16.0.2 
│ │ ├── jest-haste-map@16.0.2 
│ │ └─┬ yargs@5.0.0 
│ │ ├── cliui@3.2.0 
│ │ └── window-size@0.2.0 
│ ├─┬ jest-snapshot@16.0.2 
│ │ ├─┬ jest-diff@16.0.0 
│ │ │ └── diff@3.0.1 
│ │ ├── jest-matcher-utils@16.0.0 
│ │ ├── natural-compare@1.4.0 
│ │ └── pretty-format@4.2.1 
│ ├─┬ jest-util@16.0.2 
│ │ └── diff@3.0.1 
│ ├─┬ node-notifier@4.6.1 
│ │ ├─┬ cli-usage@0.1.4 
│ │ │ ├── marked@0.3.6 
│ │ │ └─┬ marked-terminal@1.7.0 
│ │ │ ├─┬ cardinal@1.0.0 
│ │ │ │ ├── ansicolors@0.2.1 
│ │ │ │ └─┬ redeyed@1.0.1 
│ │ │ │ └── esprima@3.0.0 
│ │ │ └─┬ node-emoji@1.4.1 
│ │ │ └── string.prototype.codepointat@0.2.0 
│ │ ├── growly@1.3.0 
│ │ ├─┬ lodash.clonedeep@3.0.2 
│ │ │ ├─┬ lodash._baseclone@3.3.0 
│ │ │ │ ├── lodash._arraycopy@3.0.0 
│ │ │ │ ├── lodash._arrayeach@3.0.0 
│ │ │ │ ├── lodash._baseassign@3.2.0 
│ │ │ │ └── lodash._basefor@3.0.3 
│ │ │ └── lodash._bindcallback@3.0.1 
│ │ └── shellwords@0.1.0 
│ ├── throat@3.0.0 
│ └─┬ yargs@5.0.0 
│ ├── cliui@3.2.0 
│ ├── get-caller-file@1.0.2 
│ ├── lodash.assign@4.2.0 
│ ├── require-directory@2.1.1 
│ ├── set-blocking@2.0.0 
│ ├── which-module@1.0.0 
│ ├── window-size@0.2.0 
│ └─┬ yargs-parser@3.2.0 
│ └── camelcase@3.0.0 
├── jest-react-native@16.0.0 
└── react-test-renderer@15.3.2

To run your app on iOS:
cd /Users/check/her
react-native run-ios

or - Open /Users/check/her/ios/her.xcodeproj in Xcode Hit the Run button To run your app on Android: Have an Android emulator running (quickest way to get started), or a device connected cd /Users/check/her react-native run-android
ignite doctor

Computer
  Platform: darwin

Ignite
  Version: 1.10.1
  Path: /usr/local/bin/ignite

Node
  Version: v6.9.1
  Path: /usr/local/bin/node

NPM
  Version: 3.10.8
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: ¯_(ツ)_/¯

**Comment by GantMan** [comment]
wow, that's odd.

2 things:  
1, send us the output of `ignite doctor`

2, what happens when you type `react-native init her`, does it complete wit no errors?  Can you run the result?

**Comment by shapik2004** [comment]
react-native init her
This will walk you through creating a new React Native project in /Users/check/her
Installing react-native package from npm...
Setting up new React Native app in /Users/check/her
her@0.0.1 /Users/check/her
└── react@15.3.2 

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g
her@0.0.1 /Users/check/her
├─┬ babel-jest@16.0.0 
│ ├─┬ babel-plugin-istanbul@2.0.3 
│ │ ├── istanbul-lib-instrument@1.2.0 
│ │ └─┬ test-exclude@2.1.3 
│ │   └── require-main-filename@1.0.1 
│ └─┬ babel-preset-jest@16.0.0 
│   └── babel-plugin-jest-hoist@16.0.0 
├── babel-preset-react-native@1.9.0 
├─┬ jest@16.0.2 
│ └─┬ jest-cli@16.0.2 
│   ├── callsites@2.0.0 
│   ├─┬ is-ci@1.0.10 
│   │ └── ci-info@1.0.0 
│   ├─┬ istanbul-api@1.0.0-aplha.10 
│   │ ├── async@1.5.2 
│   │ ├─┬ fileset@0.2.1 
│   │ │ └── minimatch@2.0.10 
│   │ ├─┬ istanbul-lib-hook@1.0.0-alpha.4 
│   │ │ └── append-transform@0.3.0 
│   │ ├─┬ istanbul-lib-report@1.0.0-alpha.3 
│   │ │ ├── async@1.5.2 
│   │ │ ├── path-parse@1.0.5 
│   │ │ └─┬ supports-color@3.1.2 
│   │ │   └── has-flag@1.0.0 
│   │ ├── istanbul-lib-source-maps@1.0.2 
│   │ ├─┬ istanbul-reports@1.0.0 
│   │ │ └─┬ handlebars@4.0.5 
│   │ │   ├── async@1.5.2 
│   │ │   └── source-map@0.4.4 
│   │ └─┬ js-yaml@3.6.1 
│   │   ├── argparse@1.0.9 
│   │   └── esprima@2.7.3 
│   ├── istanbul-lib-coverage@1.0.0 
│   ├── jest-changed-files@16.0.0 
│   ├─┬ jest-config@16.0.2 
│   │ ├─┬ istanbul@0.4.5 
│   │ │ ├── async@1.5.2 
│   │ │ ├── esprima@2.7.3 
│   │ │ └── supports-color@3.1.2 
│   │ └── jest-environment-node@16.0.2 
│   ├─┬ jest-environment-jsdom@16.0.2 
│   │ └─┬ jsdom@9.8.3 
│   │   ├── abab@1.0.3 
│   │   ├── acorn@2.7.0 
│   │   ├─┬ acorn-globals@1.0.9 
│   │   │ └── acorn@2.7.0 
│   │   ├── array-equal@1.0.0 
│   │   ├── content-type-parser@1.0.1 
│   │   ├── cssom@0.3.1 
│   │   ├── cssstyle@0.2.37 
│   │   ├── html-encoding-sniffer@1.0.1 
│   │   ├── iconv-lite@0.4.13 
│   │   ├── nwmatcher@1.3.9 
│   │   ├── parse5@1.5.1 
│   │   ├─┬ request@2.76.0 
│   │   │ ├── aws-sign2@0.6.0 
│   │   │ ├── aws4@1.5.0 
│   │   │ ├── caseless@0.11.0 
│   │   │ ├─┬ combined-stream@1.0.5 
│   │   │ │ └── delayed-stream@1.0.0 
│   │   │ ├── forever-agent@0.6.1 
│   │   │ ├─┬ form-data@2.1.1 
│   │   │ │ ├── asynckit@0.4.0 
│   │   │ │ └─┬ mime-types@2.1.12 
│   │   │ │   └── mime-db@1.24.0 
│   │   │ ├─┬ har-validator@2.0.6 
│   │   │ │ └─┬ is-my-json-valid@2.15.0 
│   │   │ │   ├── generate-function@2.0.0 
│   │   │ │   ├─┬ generate-object-property@1.2.0 
│   │   │ │   │ └── is-property@1.0.2 
│   │   │ │   └── jsonpointer@4.0.0 
│   │   │ ├─┬ hawk@3.1.3 
│   │   │ │ ├── boom@2.10.1 
│   │   │ │ ├── cryptiles@2.0.5 
│   │   │ │ └── sntp@1.0.9 
│   │   │ ├─┬ http-signature@1.1.1 
│   │   │ │ ├── assert-plus@0.2.0 
│   │   │ │ ├─┬ jsprim@1.3.1 
│   │   │ │ │ ├── extsprintf@1.0.2 
│   │   │ │ │ ├── json-schema@0.2.3 
│   │   │ │ │ └── verror@1.3.6 
│   │   │ │ └─┬ sshpk@1.10.1 
│   │   │ │   ├── asn1@0.2.3 
│   │   │ │   ├── assert-plus@1.0.0 
│   │   │ │   ├── bcrypt-pbkdf@1.0.0 
│   │   │ │   ├─┬ dashdash@1.14.0 
│   │   │ │   │ └── assert-plus@1.0.0 
│   │   │ │   ├── ecc-jsbn@0.1.1 
│   │   │ │   ├─┬ getpass@0.1.6 
│   │   │ │   │ └── assert-plus@1.0.0 
│   │   │ │   ├── jodid25519@1.0.2 
│   │   │ │   ├── jsbn@0.1.0 
│   │   │ │   └── tweetnacl@0.14.3 
│   │   │ ├── is-typedarray@1.0.0 
│   │   │ ├── isstream@0.1.2 
│   │   │ ├── json-stringify-safe@5.0.1 
│   │   │ ├── oauth-sign@0.8.2 
│   │   │ ├── qs@6.3.0 
│   │   │ └── stringstream@0.0.5 
│   │   ├── symbol-tree@3.1.4 
│   │   ├─┬ tough-cookie@2.3.2 
│   │   │ └── punycode@1.4.1 
│   │   ├── webidl-conversions@3.0.1 
│   │   ├─┬ whatwg-encoding@1.0.1 
│   │   │ └── iconv-lite@0.4.13 
│   │   ├─┬ whatwg-url@3.0.0 
│   │   │ └── tr46@0.0.3 
│   │   └── xml-name-validator@2.0.1 
│   ├── jest-file-exists@15.0.0 
│   ├── jest-haste-map@16.0.2 
│   ├─┬ jest-jasmine2@16.0.2 
│   │ ├─┬ jasmine-check@0.1.5 
│   │ │ └── testcheck@0.1.4 
│   │ └── jest-matchers@16.0.2 
│   ├── jest-mock@16.0.2 
│   ├─┬ jest-resolve@16.0.2 
│   │ └── jest-haste-map@16.0.2 
│   ├── jest-resolve-dependencies@16.0.2 
│   ├─┬ jest-runtime@16.0.2 
│   │ ├── jest-haste-map@16.0.2 
│   │ └─┬ yargs@5.0.0 
│   │   ├── cliui@3.2.0 
│   │   └── window-size@0.2.0 
│   ├─┬ jest-snapshot@16.0.2 
│   │ ├─┬ jest-diff@16.0.0 
│   │ │ └── diff@3.0.1 
│   │ ├── jest-matcher-utils@16.0.0 
│   │ ├── natural-compare@1.4.0 
│   │ └── pretty-format@4.2.1 
│   ├─┬ jest-util@16.0.2 
│   │ └── diff@3.0.1 
│   ├─┬ node-notifier@4.6.1 
│   │ ├─┬ cli-usage@0.1.4 
│   │ │ ├── marked@0.3.6 
│   │ │ └─┬ marked-terminal@1.7.0 
│   │ │   ├─┬ cardinal@1.0.0 
│   │ │   │ ├── ansicolors@0.2.1 
│   │ │   │ └─┬ redeyed@1.0.1 
│   │ │   │   └── esprima@3.0.0 
│   │ │   └─┬ node-emoji@1.4.1 
│   │ │     └── string.prototype.codepointat@0.2.0 
│   │ ├── growly@1.3.0 
│   │ ├─┬ lodash.clonedeep@3.0.2 
│   │ │ ├─┬ lodash._baseclone@3.3.0 
│   │ │ │ ├── lodash._arraycopy@3.0.0 
│   │ │ │ ├── lodash._arrayeach@3.0.0 
│   │ │ │ ├── lodash._baseassign@3.2.0 
│   │ │ │ └── lodash._basefor@3.0.3 
│   │ │ └── lodash._bindcallback@3.0.1 
│   │ └── shellwords@0.1.0 
│   ├── throat@3.0.0 
│   └─┬ yargs@5.0.0 
│     ├── cliui@3.2.0 
│     ├── get-caller-file@1.0.2 
│     ├── lodash.assign@4.2.0 
│     ├── require-directory@2.1.1 
│     ├── set-blocking@2.0.0 
│     ├── which-module@1.0.0 
│     ├── window-size@0.2.0 
│     └─┬ yargs-parser@3.2.0 
│       └── camelcase@3.0.0 
├── jest-react-native@16.0.0 
└── react-test-renderer@15.3.2 

To run your app on iOS:
   cd /Users/check/her
   react-native run-ios
   - or -
   Open /Users/check/her/ios/her.xcodeproj in Xcode
   Hit the Run button
To run your app on Android:
   Have an Android emulator running (quickest way to get started), or a device connected
   cd /Users/check/her
   react-native run-android





ignite doctor

```
Computer
  Platform: darwin

Ignite
  Version: 1.10.1
  Path: /usr/local/bin/ignite

Node
  Version: v6.9.1
  Path: /usr/local/bin/node

NPM
  Version: 3.10.8
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.0.0

App
  React Native Version: ¯\_(ツ)_/¯
```

**Comment by shapik2004** [comment]
react-native init her
This will walk you through creating a new React Native project in /Users/check/her
Installing react-native package from npm...
Setting up new React Native app in /Users/check/her
her@0.0.1 /Users/check/her
└── react@15.3.2

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g
her@0.0.1 /Users/check/her
├─┬ babel-jest@16.0.0 
│ ├─┬ babel-plugin-istanbul@2.0.3 
│ │ ├── istanbul-lib-instrument@1.2.0 
│ │ └─┬ test-exclude@2.1.3 
│ │ └── require-main-filename@1.0.1 
│ └─┬ babel-preset-jest@16.0.0 
│ └── babel-plugin-jest-hoist@16.0.0 
├── babel-preset-react-native@1.9.0 
├─┬ jest@16.0.2 
│ └─┬ jest-cli@16.0.2 
│ ├── callsites@2.0.0 
│ ├─┬ is-ci@1.0.10 
│ │ └── ci-info@1.0.0 
│ ├─┬ istanbul-api@1.0.0-aplha.10 
│ │ ├── async@1.5.2 
│ │ ├─┬ fileset@0.2.1 
│ │ │ └── minimatch@2.0.10 
│ │ ├─┬ istanbul-lib-hook@1.0.0-alpha.4 
│ │ │ └── append-transform@0.3.0 
│ │ ├─┬ istanbul-lib-report@1.0.0-alpha.3 
│ │ │ ├── async@1.5.2 
│ │ │ ├── path-parse@1.0.5 
│ │ │ └─┬ supports-color@3.1.2 
│ │ │ └── has-flag@1.0.0 
│ │ ├── istanbul-lib-source-maps@1.0.2 
│ │ ├─┬ istanbul-reports@1.0.0 
│ │ │ └─┬ handlebars@4.0.5 
│ │ │ ├── async@1.5.2 
│ │ │ └── source-map@0.4.4 
│ │ └─┬ js-yaml@3.6.1 
│ │ ├── argparse@1.0.9 
│ │ └── esprima@2.7.3 
│ ├── istanbul-lib-coverage@1.0.0 
│ ├── jest-changed-files@16.0.0 
│ ├─┬ jest-config@16.0.2 
│ │ ├─┬ istanbul@0.4.5 
│ │ │ ├── async@1.5.2 
│ │ │ ├── esprima@2.7.3 
│ │ │ └── supports-color@3.1.2 
│ │ └── jest-environment-node@16.0.2 
│ ├─┬ jest-environment-jsdom@16.0.2 
│ │ └─┬ jsdom@9.8.3 
│ │ ├── abab@1.0.3 
│ │ ├── acorn@2.7.0 
│ │ ├─┬ acorn-globals@1.0.9 
│ │ │ └── acorn@2.7.0 
│ │ ├── array-equal@1.0.0 
│ │ ├── content-type-parser@1.0.1 
│ │ ├── cssom@0.3.1 
│ │ ├── cssstyle@0.2.37 
│ │ ├── html-encoding-sniffer@1.0.1 
│ │ ├── iconv-lite@0.4.13 
│ │ ├── nwmatcher@1.3.9 
│ │ ├── parse5@1.5.1 
│ │ ├─┬ request@2.76.0 
│ │ │ ├── aws-sign2@0.6.0 
│ │ │ ├── aws4@1.5.0 
│ │ │ ├── caseless@0.11.0 
│ │ │ ├─┬ combined-stream@1.0.5 
│ │ │ │ └── delayed-stream@1.0.0 
│ │ │ ├── forever-agent@0.6.1 
│ │ │ ├─┬ form-data@2.1.1 
│ │ │ │ ├── asynckit@0.4.0 
│ │ │ │ └─┬ mime-types@2.1.12 
│ │ │ │ └── mime-db@1.24.0 
│ │ │ ├─┬ har-validator@2.0.6 
│ │ │ │ └─┬ is-my-json-valid@2.15.0 
│ │ │ │ ├── generate-function@2.0.0 
│ │ │ │ ├─┬ generate-object-property@1.2.0 
│ │ │ │ │ └── is-property@1.0.2 
│ │ │ │ └── jsonpointer@4.0.0 
│ │ │ ├─┬ hawk@3.1.3 
│ │ │ │ ├── boom@2.10.1 
│ │ │ │ ├── cryptiles@2.0.5 
│ │ │ │ └── sntp@1.0.9 
│ │ │ ├─┬ http-signature@1.1.1 
│ │ │ │ ├── assert-plus@0.2.0 
│ │ │ │ ├─┬ jsprim@1.3.1 
│ │ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ │ └── verror@1.3.6 
│ │ │ │ └─┬ sshpk@1.10.1 
│ │ │ │ ├── asn1@0.2.3 
│ │ │ │ ├── assert-plus@1.0.0 
│ │ │ │ ├── bcrypt-pbkdf@1.0.0 
│ │ │ │ ├─┬ dashdash@1.14.0 
│ │ │ │ │ └── assert-plus@1.0.0 
│ │ │ │ ├── ecc-jsbn@0.1.1 
│ │ │ │ ├─┬ getpass@0.1.6 
│ │ │ │ │ └── assert-plus@1.0.0 
│ │ │ │ ├── jodid25519@1.0.2 
│ │ │ │ ├── jsbn@0.1.0 
│ │ │ │ └── tweetnacl@0.14.3 
│ │ │ ├── is-typedarray@1.0.0 
│ │ │ ├── isstream@0.1.2 
│ │ │ ├── json-stringify-safe@5.0.1 
│ │ │ ├── oauth-sign@0.8.2 
│ │ │ ├── qs@6.3.0 
│ │ │ └── stringstream@0.0.5 
│ │ ├── symbol-tree@3.1.4 
│ │ ├─┬ tough-cookie@2.3.2 
│ │ │ └── punycode@1.4.1 
│ │ ├── webidl-conversions@3.0.1 
│ │ ├─┬ whatwg-encoding@1.0.1 
│ │ │ └── iconv-lite@0.4.13 
│ │ ├─┬ whatwg-url@3.0.0 
│ │ │ └── tr46@0.0.3 
│ │ └── xml-name-validator@2.0.1 
│ ├── jest-file-exists@15.0.0 
│ ├── jest-haste-map@16.0.2 
│ ├─┬ jest-jasmine2@16.0.2 
│ │ ├─┬ jasmine-check@0.1.5 
│ │ │ └── testcheck@0.1.4 
│ │ └── jest-matchers@16.0.2 
│ ├── jest-mock@16.0.2 
│ ├─┬ jest-resolve@16.0.2 
│ │ └── jest-haste-map@16.0.2 
│ ├── jest-resolve-dependencies@16.0.2 
│ ├─┬ jest-runtime@16.0.2 
│ │ ├── jest-haste-map@16.0.2 
│ │ └─┬ yargs@5.0.0 
│ │ ├── cliui@3.2.0 
│ │ └── window-size@0.2.0 
│ ├─┬ jest-snapshot@16.0.2 
│ │ ├─┬ jest-diff@16.0.0 
│ │ │ └── diff@3.0.1 
│ │ ├── jest-matcher-utils@16.0.0 
│ │ ├── natural-compare@1.4.0 
│ │ └── pretty-format@4.2.1 
│ ├─┬ jest-util@16.0.2 
│ │ └── diff@3.0.1 
│ ├─┬ node-notifier@4.6.1 
│ │ ├─┬ cli-usage@0.1.4 
│ │ │ ├── marked@0.3.6 
│ │ │ └─┬ marked-terminal@1.7.0 
│ │ │ ├─┬ cardinal@1.0.0 
│ │ │ │ ├── ansicolors@0.2.1 
│ │ │ │ └─┬ redeyed@1.0.1 
│ │ │ │ └── esprima@3.0.0 
│ │ │ └─┬ node-emoji@1.4.1 
│ │ │ └── string.prototype.codepointat@0.2.0 
│ │ ├── growly@1.3.0 
│ │ ├─┬ lodash.clonedeep@3.0.2 
│ │ │ ├─┬ lodash._baseclone@3.3.0 
│ │ │ │ ├── lodash._arraycopy@3.0.0 
│ │ │ │ ├── lodash._arrayeach@3.0.0 
│ │ │ │ ├── lodash._baseassign@3.2.0 
│ │ │ │ └── lodash._basefor@3.0.3 
│ │ │ └── lodash._bindcallback@3.0.1 
│ │ └── shellwords@0.1.0 
│ ├── throat@3.0.0 
│ └─┬ yargs@5.0.0 
│ ├── cliui@3.2.0 
│ ├── get-caller-file@1.0.2 
│ ├── lodash.assign@4.2.0 
│ ├── require-directory@2.1.1 
│ ├── set-blocking@2.0.0 
│ ├── which-module@1.0.0 
│ ├── window-size@0.2.0 
│ └─┬ yargs-parser@3.2.0 
│ └── camelcase@3.0.0 
├── jest-react-native@16.0.0 
└── react-test-renderer@15.3.2

To run your app on iOS:
cd /Users/check/her
react-native run-ios

or - Open /Users/check/her/ios/her.xcodeproj in Xcode Hit the Run button To run your app on Android: Have an Android emulator running (quickest way to get started), or a device connected cd /Users/check/her react-native run-android
ignite doctor

Computer
Platform: darwin

Ignite
Version: 1.10.1
Path: /usr/local/bin/ignite

Node
Version: v6.9.1
Path: /usr/local/bin/node

NPM
Version: 3.10.8
Path: /usr/local/bin/npm

Yeoman
Version: 1.8.5

React Native CLI
Version: 1.0.0

App
React Native Version: ¯(ツ)/¯

**Comment by skellock** [comment]
Haven't heard back.  Please reopen if you're still having probs.

**Comment by akhil-geekyants** [comment]
@skellock  I am testing locally based on this https://shift.infinite.red/make-your-own-react-native-boilerplate-with-ignite-cli-c45bfa564684. Ran command to generate screen and got this. Any advice on what might have gone wrong

![screen shot 2018-03-16 at 5 45 30 pm](https://user-images.githubusercontent.com/27768184/37520297-794e223e-2942-11e8-8270-ccbc09a1fc1d.png)

**Comment by skellock** [comment]
Can you open a new issue please?
