### ISSUE TITLE
Re-enable maps

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#468]
The `mapReturn` branch is to get maps working again.

As of right now, bringing in maps 11, you get it working on iOS
![image](https://cloud.githubusercontent.com/assets/997157/19840950/d3128606-9ecf-11e6-9d13-84aea8639fb3.png)

And on Android, it compiles, but as soon as you click the mapview example you get this:
![image](https://cloud.githubusercontent.com/assets/997157/19840967/20d22162-9ed0-11e6-8005-9e9b17310da8.png)
With nothing logged to `react-native android-log`

At a loss on how to track down further.  @skellock, @fvonhoven or anyone... ideas?

**Comment by GantMan** [comment]
modifying `react-native-maps/android/build.gradle` to + stops the crash:
![image](https://cloud.githubusercontent.com/assets/997157/19841381/dd64a8ce-9ed8-11e6-8c40-3e6015b21f5e.png)

but makes the screen look like this on android:
![image](https://cloud.githubusercontent.com/assets/997157/19841389/05a91e1e-9ed9-11e6-9262-ea4a3de70322.png)

Playing with styles I see this:  
![image](https://cloud.githubusercontent.com/assets/997157/19841411/79db8fb0-9ed9-11e6-955e-9237ca15c295.png)

**Comment by GantMan** [comment]
![image](https://cloud.githubusercontent.com/assets/997157/19843977/b5f2bc64-9ef5-11e6-99c6-47392cad5197.png)

Need to figure out the best plan for moving to + over 9.4

**Comment by huangkaiw3n** [comment]
I'm not sure if you've seen this yet, but I was having a runtime error as well on Android only some time ago. The reason is because there are conflicting google play services versions among the node_modules.

https://github.com/airbnb/react-native-maps/issues/647#issuecomment-252088828

**Comment by GantMan** [comment]
@huangkaiw3n - is there another package in Ignite that specifies an android version?  Maybe we can get that version changed.   Or is it conflicting with something in core?

**Comment by huangkaiw3n** [comment]
@GantMan Yep. For me, the issue was, that react-native-device-info was specified to use the latest play-services version whereas react-native-maps used specifically version 9.4.0 causing the crash.

I discovered them by loading the project in Android Studio which points out the possible conflicts. So if this doesn't solve it still, try loading it in Android Studio.
