### ISSUE TITLE
ProgressiveImage component requires hardcoded width/height

### ISSUE THREAD

**Issue by markrickert** [infinitered/ignite#47]
When using `<ProgressiveImage />` without an explicit width/height, the component throws an error:

```javascript
ExceptionsManager.js:76 Unhandled JS Exception: Cannot read property 'width' of undefined
```

Code in question is:

https://github.com/infinitered/ignite/blob/master/ignite-base/App/Components/ProgressiveImage.js#L66-L70

```javascript
  render () {
    return (
      <View
        width={this.props.style.width}
        height={this.props.style.height}
        backgroundColor={'#CCC'}
      >
      {this.handleImage()}
      </View>
    )
  }
```

### Make sure verify the following before submitting an issue.

- [x] Issue does not already exist
- [x] You have example code or some other reproduce experiment that we can verify

**Comment by skellock** [comment]
You're probably calling it like this:

 `<ProgressiveImage style=[goodies] />`

Where `goodies` is a bunch of styles in an array.  

The `ProgressiveImage` component reaches directly into the `style` object for a prop named `width` and `height`.  So `.style` should be a `{}` according to that code.

Perhaps we should standardize our components to say:   Whenever you make `style` as a property, it must be a React Native compatible style.

Also, does `View` even have a property called `width` and `height`?

**Comment by GantMan** [comment]
do we close this one?

**Comment by skellock** [comment]
Ya.  I think components like this should live in a different library to be honest.

**Comment by GantMan** [comment]
agreed.   We need some components to be examples, but nothing this complicated.   Closing this ticket in favor of a ticket to removed progressive image component.
