### ISSUE TITLE
Documentation.  It's time.

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#470]
Many skilled folks are landing in this repo and looking for documentation.  We have parts scattered, but it' be nice to have a gitbook or something that brings it all together.

I've always felt that `redux-saga` does a brilliant job of this.  

http://yelouafi.github.io/redux-saga/

**Comment by GantMan** [comment]
@skellock - how do we gitbook?  Let's begin.

**Comment by skellock** [comment]
I summon @codeithuman for wisdom and guidance!

**Comment by skellock** [comment]
Ignite 2 is in much better shape thanks to @codeithuman, @mlaco, and @robinheinze.
