### ISSUE TITLE
command line with ignite closes cmd window after entering

### ISSUE THREAD

**Issue by ilyashusterman** [infinitered/ignite#474]
after ignite install, i enter "ignite new MyApp" or anything else that starts with the word ignite and the cmd windows closes right off.. help please

**Comment by GantMan** [comment]
That's a wild issue!  Your command window is actually closing itself?

That seems pretty deeply rooted as a problem.  Not really affiliated with ignite, I believe.  Do you have this issue with any other commands at all?

**Comment by luissardon** [comment]
seems like ignite calls exit $ when something fails

**Comment by GantMan** [comment]
would the exit be causing the command window to close?

**Comment by skellock** [comment]
Haven't heard anything back here.  Please feel free to re-open if this is still happening.
