### ISSUE TITLE
Add a generator for react-native-elements

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite#475]
The [react-native-elements](https://github.com/react-native-community/react-native-elements) project has some ui awesomeness that we should grace `ignite` with.

**Comment by shroukkhan** [comment]
+1 . it looks awesome!

**Comment by juddey** [comment]
So the install of this module is a sinch: 
`npm install react-native-elements`
its pure js.

I'm thinking an `--element` option or similar passed to component/screen/container would be how it might work in practice. eg:

`ignite g container AwesomeContainer --element button list tabs`

Would scaffold a container, with button, list and tab elements in the render method.

We should also check if the module is in `package.json` first, and if not, then install it. 

How does that sound for a way forward?

**Comment by GantMan** [comment]
Eh, maybe not as much of a sinch as it sounds.   Or maybe it is, let's see.

So if someone says they want react native elements, the command should be :

`ignite add react-native-elements`
this would:
* check the `.ignite` file if RNE has been added already under plugins.  If it's already been added it would show a friendly message telling you so.
* Adding RNE would consist of the following:
  * add to plugins section of `.ignite`
  * automatically npm/yarn install node module (as you stated)
  * copy examples:
    * check if usage example screens exists
    * If UsageExample screen then copy in the examples
    * if user did `ignite add react-native-elements --no-examples` then skip
    * **Here's the tricky part** - once rne has been added, we modify screen generator.  It can ask what RNE elements to include in the wizard.  OR you can pass them in.  Having NPM modules affect generators is key to the growth.  We can do this with blueprints, or each ignite add-in can come with a subgenerator.

**Comment by GantMan** [comment]
if you agree to the experience above, I can then rope in other devs to start describing how this would work.   Including the author of RNE.

btw, thanks for keeping me from being lazy 🏃 I've been thinking and not acting on this!

**Comment by GantMan** [comment]
ALSO: It might be easier to move an in-house generator over first, like Maps.  Especially since this would add a command rather then modify one.  But then again, if they are based on sub-generators, it might be simple.

**Comment by juddey** [comment]
I was more meaning that the install of RNE was a sinch, not necessarily implementing it! 😅

> check the .ignite file if RNE has been added already under plugins. If it's already been added it would show a friendly message telling you so.
add to plugins section of .ignite
automatically npm/yarn install node module (as you stated)

This is all good. You've just articulated what I thought it would do here. :mind_read:

For the **tricky part**, I think its worth doing a quick mockup of how the code _might_ look at the end of the process, and how we might get there in terms of prompts etc.  (this might be short, or long, but then at least we're all understanding each other on the end result.) Mocking only needs to be done for the tricky part, the rest has enough explanation.

I'd hardly call it lazy. We all need a life outside our online one 🎈

**Comment by GantMan** [comment]
good call on the mock!  I'll think on it, but if you beat me to it, I won't complain :)  I'm packing for a trip to SanFran right now.

This IRL thing is over-rated.  Did you know people still wear pants out in the world?  Perhaps digital is the right way to go  

🚫  👖  💯

**Comment by juddey** [comment]
just shuddering at thought of @GantMan ➖ 👖

**Comment by GantMan** [comment]
![image](https://cloud.githubusercontent.com/assets/997157/20042554/b61a1ace-a441-11e6-9dac-50b20abaa587.png)

**Comment by jamonholmgren** [comment]
FYI: https://github.com/dabit3/ignite-elements

Close?

**Comment by juddey** [comment]
Done.
