### ISSUE TITLE
Install documenation issue with Yarn: ignite command not found

### ISSUE THREAD

**Issue by dhilton** [infinitered/ignite#477]
## Describe the issue

When attempting an install using yarn, on mac osX (El Captain) using latest Yarn (0.16.1) the binary doesn't then become available at the commandline (in zsh). 

The reason is related to https://github.com/yarnpkg/yarn/issues/648 - the binary is in a different place.

This may cause potential users to fail in their attempts to use ignite. 

## FIx

Update the documentation in the Yarn variant to include a brief note to that issue to help with troubleshooting.

**Comment by GantMan** [comment]
thanks!  Would you like to author that PR on the readme?

**Comment by dhilton** [comment]
Done! Please review and comment.
