### ISSUE TITLE
generate components in sub folder

### ISSUE THREAD

**Issue by ducduong** [infinitered/ignite#479]
Hello, is there any way for us to generate a component in subfolder of /Components instead? For bigger projects, putting everything in /Components can be a bit messy.

Thanks.

**Comment by GantMan** [comment]
I agree this should be possible.  Currently no, but should be easy enough to add.  Will mark this as a task and see if someone grabs it.  Every now and then people with open source time come through and add these things.

**Comment by jamonholmgren** [comment]
I'm working on the ability to specify where things get generated in your `ignite/ignite.json` config. Also related to #819.

**Comment by jamonholmgren** [comment]
This is taking longer than expected due to a large amount of yak shaving in progress.

**Comment by GantMan** [comment]
Should be an easy PR, @ducduong - would you be interested in help on how to do this?  That would get this feature released the fastest.

**Comment by jamonholmgren** [comment]
Tracking on #996, closing this one.
