### ISSUE TITLE
Suggest troubleshooting tips when missing environment prerequisites

### ISSUE THREAD

**Issue by dabbott** [infinitered/ignite#483]
The first time I tried `ignite new Project`, my Android prerequisite was not found, which led to the Android build failing.

![screen shot 2016-11-06 at 1 03 32 pm](https://cloud.githubusercontent.com/assets/1198882/20041650/7549087c-a421-11e6-9a07-89b06d631e73.png)

In my case, it came down to missing `android` in my `PATH` (when I installed RN ages ago, I don't think this wasn't needed), but I only figured that out by searching for similar git issues on this repo.

It would be super helpful to display suggestions to the user in the case of a missing prerequisite. For example, if Android is missing, some combination of these suggestions would be helpful:
- `Unable to find 'android' in your PATH.`
- `Unable to find 'ANDROID_HOME' environment variable.`
- `Make sure you've followed the latest react-native setup instructions at https://facebook.github.io/react-native/docs/getting-started.html before using ignite.`
- `If you're only targeting iOS, you may continue now and set up Android another time. The Android files will all be generated, but the build will fail.`

**Comment by GantMan** [comment]
`/gif IT SHALL BE DONE!`

**Comment by Danm72** [comment]
Bump, just installed it with $ANDROID_HOME in my path and still got the Missing android error.
