### ISSUE TITLE
Linting crapping out right away

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#484]
latest react native throws in jest tests that fail linting:

![image](https://cloud.githubusercontent.com/assets/997157/20088853/c3767860-a537-11e6-8d56-861f267f0b7c.png)

As for now, we can just delete this folder and enforce AVA.  Eventually this will get cleaned up if the user selects Jest over AVA

**Comment by GantMan** [comment]
Also, add `standard` to package.json.

**Comment by baskan** [comment]
+ also add "seamless-immutable" to package.json
