### ISSUE TITLE
Pre-Commit hook breaks committing on Windows

### ISSUE THREAD

**Issue by zolrath** [infinitered/ignite#487]
By default `package.json` contains a git hook on pre-commit:
```
"ghooks": {
    "pre-commit": "if [ -d 'ignite-base' ]; then cd ignite-base; fi; npm run lint"
}
```
When attempting to make a commit on Windows this causes an error of `-d was unexpected at this time.`, stopping the commit from being made.

**Comment by GantMan** [comment]
true.  That's a bash command.  We should try to find a more elegant way to do that, or kill it.

**Comment by budda** [comment]
Cordova hooks are implemented as NodeJS to be flexible cross platform but still access the file system and run system commands.

Examples: http://devgirl.org/2013/11/12/three-hooks-your-cordovaphonegap-project-needs/

**Comment by GantMan** [comment]
nice!  We'll be changing this soon, we're doing some fundamental changes.

**Comment by skellock** [comment]
ghooks is now gone.
