### ISSUE TITLE
Can I generate a mapView with google maps?

### ISSUE THREAD

**Issue by therealgilles** [infinitered/ignite#492]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

Trying to figure out if I can generate a map view with Google Maps instead of Apple Maps on ios? Is it feasible? If so, some directions would be most welcomed. Thank you

**Comment by GantMan** [comment]
I haven't really looked into this:
A cursory search found this:
http://stackoverflow.com/questions/34950794/google-maps-in-react-native-ios

I'm really not sure about Maps being google maps in, but I'd ask on https://github.com/airbnb/react-native-maps

**Comment by therealgilles** [comment]
Thank you for your answer.

The stackoverflow article is not helpful. I've asked a question on react-native-maps, but I haven't received any answer yet. Their examples are CocoaPods based unfortunately (and I'm super new to XCode).

I see AirMaps is included under Libraries with an AirMaps.xcodeproj file (see screenshot below). I think I need to include AirGoogleMaps the same way, but I do not know how to do it.

![screen shot 2016-11-11 at 2 33 27 pm](https://cloud.githubusercontent.com/assets/18076992/20233795/704ff3a2-a828-11e6-8c26-edc3b71492fe.png)

**Comment by therealgilles** [comment]
I have figured this out, see https://github.com/airbnb/react-native-maps/issues/789.

**Comment by GantMan** [comment]
excellent!  I might updated our maps generator to include this.

**Comment by skellock** [comment]
When the `ignite-maps` plugin is created for Ignite 2, that should most definitely have this an option if it's supported out of the box with `react-native-maps`.
