### ISSUE TITLE
EACCES on generator-react-native-ignite block and i'm using sudo.

### ISSUE THREAD

**Issue by maotora** [infinitered/ignite#493]
Hi, thank you for this project.

I'm facing issues when installing `react-native-ignite` with `sudo npm install -g react-native-ignite`

It seems the first part of `react-native-ignite` runs fine but when it starts to run the **post install script** `npm i -g generator-react-native-ignite` something goes terribly wrong and i get this stack trace.

```
> npm i -g generator-react-native-ignite

npm ERR! Linux 4.8.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "generator-react-native-ignite"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! path /home/username/.npm/generator-react-native-ignite/1.11.0/package
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/home/username/.npm/generator-react-native-ignite/1.11.0/package'
npm ERR!  { Error: EACCES: permission denied, mkdir '/home/username/.npm/generator-react-native-ignite/1.11.0/package'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/username/.npm/generator-react-native-ignite/1.11.0/package' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/react-native-ignite/npm-debug.log
npm ERR! Linux 4.8.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "react-native-ignite"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

```

I tried to install `sudo npm i -g generator-react-native-ignite` alone, installing it worked but running `$ ignite` I still get `command not found` and installing still brings errors. 

I also tried to create the folder it's failing to create, made it then installed `react-native-ignite` again but same error.

I'm running Archlinux OS and the stacktrace goes on by saying i need to update my node but i'm using `nodejs: 7.1.0, npm: 3.10.9` and my system is updated.

I tried installing it with `sudo yarn global add react-native-ignite` it installed successfully but when i tried running `ignite` nothing ran, checking where it installs with `yarn global bin` it showed `/usr/bin` and i saw the `ignite` file in there.
Ran `file /usr/bin/ignite` found out it's a broken link to `/usr/lib/node_modules/react-native-ignite/index.js` which isn't there. :(

I also found this solution [here](https://github.com/infinitered/ignite/issues/169) didn't work, should i panic now?

**Comment by GantMan** [comment]
Have you gone through these steps?
https://docs.npmjs.com/getting-started/fixing-npm-permissions

If so, maybe we can screen share when I return from vacation

**Comment by maotora** [comment]
@GantMan Thank you for your suggestions.

The prefix solution worked magic!
