### ISSUE TITLE
Generating a screen

### ISSUE THREAD

**Issue by joshg111** [infinitered/ignite#494]
What is the expected behavior of generate screen? The doc says:

> A generated screen is an opinionated container with a generated route. Keyboard avoiding and other base code is placed in this connected smart component.

I'm wondering what a "generated route" means. Will this connect the container to NavigationRouter.js?

**Comment by juddey** [comment]
@joshg111 Yes, it should. But at this time, no, it doesn't 😞 .
We should remove that documentation or fix the functionality.

**Comment by joshg111** [comment]
Thx for the reply! So is there any difference between generating a component and generating a screen?

**Comment by joshg111** [comment]
Actually I meant to say: "between generating a container and generating a screen?"

**Comment by juddey** [comment]
They're very similar codewise. The screen adds a bit more code on top of the container  (keyboardavoidingview and a couple of other bits which escape me right now).

**Comment by skellock** [comment]
This will be a thing once the navigation landscape is in a better place.  Right now we're halfway between rnrf and react-navigation.  Once `react-navigation` is ready for primetime, we'll be using that.  Then we can build this on top.
