### ISSUE TITLE
Non pure functions in LoginRedux.js

### ISSUE THREAD

**Issue by joshg111** [infinitered/ignite#500]
I'm curious why the reducers in LoginRedux.js are not pure. It seems they use state.merge(..) which I think will change the original state object. Redux implementations seem to always stress having reducers be pure functions, even in the redux sauce use cases they use pure functions. I'm not sure the side effects of not using pure functions though so maybe it's not such a big deal. Example of what I'm referencing below. 

```javascript
// @flow

import { createReducer, createActions } from 'reduxsauce'
import Immutable from 'seamless-immutable'

/* ------------- Types and Action Creators ------------- */

const { Types, Creators } = createActions({
  loginRequest: ['username', 'password'],
  loginSuccess: ['username'],
  loginFailure: ['error'],
  logout: null
})

export const LoginTypes = Types
export default Creators

/* ------------- Initial State ------------- */

export const INITIAL_STATE = Immutable({
  username: null,
  error: null,
  fetching: false
})

/* ------------- Reducers ------------- */
// I'm talking about the following functions which use state.merge(..). 
// My understanding is that merge will change the original state object.

// we're attempting to login
export const request = (state: Object) => state.merge({ fetching: true })

// we've successfully logged in
export const success = (state: Object, { username }: Object) =>
  state.merge({ fetching: false, error: null, username })

// we've had a problem logging in
export const failure = (state: Object, { error }: Object) =>
  state.merge({ fetching: false, error })

// we've logged out
export const logout = (state: Object) => INITIAL_STATE

/* ------------- Hookup Reducers To Types ------------- */

export const reducer = createReducer(INITIAL_STATE, {
  [Types.LOGIN_REQUEST]: request,
  [Types.LOGIN_SUCCESS]: success,
  [Types.LOGIN_FAILURE]: failure,
  [Types.LOGOUT]: logout
})

/* ------------- Selectors ------------- */

// Is the current user logged in?
export const isLoggedIn = (loginState: Object) => loginState.username !== null

```

**Comment by GantMan** [comment]
Hi @joshg111 

I've got good news.  Fortunately `.merge` is creating a new immutable object.   👍   

So we're safe, but I still agree you have a valid point in the readability sector.

It reads like it's not pure, and that bothers the hell out of me.  It's the `seamless-immutable` library that is the culprit.  As a former ruby developer, I feel code should say what it does!  And `.merge` sounds to be impure.

Benefit of `seamless-immutable` is you can't accidentally mutate.  Which trust me is hell to find when someone does that!

Downside, it says "merge" when it means "createMerged"

I hope this helps!

**Comment by jorgutdev** [comment]
@GantMan wow thanks so much! I didn't know that .merge was creating a new object ...
