### ISSUE TITLE
Running npm install a second time fails

### ISSUE THREAD

**Issue by budda** [infinitered/ignite#502]
Trying to install any new packages added to package.json fails.
```
$ npm install
npm WARN react-dom@15.4.1 requires a peer of react@^15.4.1 but none was installed.
```
I have to rm -rf the node_modules directory and clean up before executing an install.

ignite doctor output:
```
Computer
  Platform: darwin

Ignite
  Version: 1.11.0
  Path: /usr/local/bin/ignite

Node
  Version: v5.8.0
  Path: /usr/local/bin/node

NPM
  Version: 3.8.1
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.2.0

App
  React Native Version: 0.36.1
```

**Comment by GantMan** [comment]
That's not a fail, that's just a warn.  Sometimes dependencies split across react versions. You can install multiple copies of react to remove this warning, but most of the time it's just innocuous.
