### ISSUE TITLE
__tests__ fail on base app when trying to commit my changes

### ISSUE THREAD

**Issue by budda** [infinitered/ignite#503]
The two ios and android files in __tests__ cause the javascript standard syntax pre commit check to fail.

1. semi colons used on the import lines
2. unused 'tree' variable

Should the boilerplate two tests start out as commented code ?

**Comment by GantMan** [comment]
hiya budda.  Are you using latest ignite?  `ignite doctor` to find out.

I believe this should be removed in recent projects.

**Comment by budda** [comment]
I got promoted to update the Ignite CLI a few minutes after I posted this ticket.
I'm currently running v1.12.0

However, I would have created the base app earlier in the week. So if the latest update fixes this i assume this ticket can be closed then ?

**Comment by GantMan** [comment]
yup!  We had no idea they were sneaking in those test folders :)  But we've got them now!
