### ISSUE TITLE
Command-R doesn't work in iOS simulator

### ISSUE THREAD

**Issue by budda** [infinitered/ignite#504]
I'm unable to trigger a reload in the iOS simulator using command-R

**Comment by skellock** [comment]
Try double-tapping r.

**Comment by budda** [comment]
@skellock no joy.

Also using option-command triggers the Simulators multi tap simulation mode too -- so not sure how that will work with Copy mode that's mentioned in the footer of the red screens.

**Comment by budda** [comment]
I'm currently re-running ```$ react-native run-ios``` to update the simulator view.

**Comment by skellock** [comment]
Sometimes your keyboard gets messed up.  Check under the hardware menu in the simulator.  Is there a keyboard toggle for `command + k` or `command + shift + k`?

**Comment by Mitishah247** [comment]
You might have disabled(unchecked) "Connect hardware keyboard" option which is in the hardware/keyboard menu. Make sure its checked.

**Comment by liamse** [comment]
as @skellock said, if your `Cmd+r` does not work, double tap to `r` and if `Cmd+d` does not work as well, you can double tap on `d`.

**Comment by MilosJo** [comment]
> Try double-tapping r.
That is actually related to Android Simulator.

As @skellock stated. Toggling `cmd+k `and/or `cmd+shift+k` fixed issue for me.
Thanks
