### ISSUE TITLE
react-native-config not using .env by default

### ISSUE THREAD

**Issue by kriskate** [infinitered/ignite#505]
For some reason, running `ignite new MyProject`, this line:
`apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"`
from `android/app/build.gradle`, has to be entered manually, although it can be seen ignite-base, on the repo.

It deems .env unusable by default.
Ignite version: 1.11.0/1.12.0

**Comment by GantMan** [comment]
Thanks!  Will check into this.  I think there's a ticket filed on the .env project.

**Comment by kriskate** [comment]
You're right! I found it there. https://github.com/luggit/react-native-config/issues/34
I guess this issue can be marked as duplicate 👍

**Comment by GantMan** [comment]
When we move this to an ignite module, this step will be automated.
