### ISSUE TITLE
Generate an empty base application

### ISSUE THREAD

**Issue by Knudian** [infinitered/ignite#506]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [x] ignite the cli
  - [ ] ignite generated code

--------
Hello there,

First 👍 
Second, I would like _**not**_ to delete a lot of files when generating an app, or to be able to generate an app with only some basic views : 
- homepage,
- login,
- sidebar,
- settings page.

And just that.
(Afterwards, the other generators are enough ;))

Are some generators on the way to be released, allowing this possibility?

Warm regards !

**Comment by skellock** [comment]
Yes.  We are actively working on this for Ignite 2.0.   

We hear you loud & clear.  We agree!
