### ISSUE TITLE
NativeBase Support

### ISSUE THREAD

**Issue by Knudian** [infinitered/ignite#507]
Hello,

I am usually using [NativeBase](https://github.com/GeekyAnts/NativeBase) for my RN projects, but it's not included/supported actually into Ignite.

Will this nice library be included in future releases?
Or just "no" ?

**Comment by skellock** [comment]
Just "yes" actually.  It'll be a plugin and not a core.

In fact in Ignite 2.0, everything will be a plugin.

**Comment by GantMan** [comment]
I've spoken with the author of NativeBase, we have plans to add this in Ignite 2.0

See ya soon!
