### ISSUE TITLE
Old rnpm = Issues Installing

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#51]
When through the fresh install process tonight.

Looks like we'll need make sure `rnpm` is installed properly and is up-to-date.

The I18N library wasn't able to be linked properly.   

![image](https://cloud.githubusercontent.com/assets/68273/14481024/d1c07b58-00fc-11e6-8310-7b24d2cc6680.png)

After upgrading and re-linking, the I18N library was found.

**Comment by GantMan** [comment]
Doesn't it notice and fix that? 
https://github.com/infinitered/ignite/blob/master/ignite-generator/src/shared/shared.js#L26-L31

**Comment by GantMan** [comment]
I'm an idiot.  It passes rnpm check, just wrong version.  Gotcha.   What do you think we should do?  prompt user to upgrade?

**Comment by GantMan** [comment]
it does warn, though:  https://github.com/infinitered/ignite/blob/master/ignite-generator/src/shared/shared.js#L34

**Comment by skellock** [comment]
Well, if we don't upgrade, this project doesn't work.   I think we upgrade that warning to a prompt.  If they say no, they we should bail.

The warning may show, but i missed it.  It took nearly 10 minutes to install and create the first app.  I had long since tabbed away from the shell.

Maybe we could move the `rnpm` check earlier?  Maybe surround it with emoji?

Something to soothe the wandering minds of absentee shell script runners like me.

**Comment by GantMan** [comment]
You're write, we should prompt the user.  Do you know what version we need to enforce?  Or do you think any npm outdated is worth the bail?

**Comment by skellock** [comment]
Comes down to whatever minimum version is required to install any of our deps that need it.

The i18n lib needed either 1.5 or 1.6 to work.

Bail if we can't fulfill the minimum. Stern finger wagging if you're out of date but still good enough to run us.
