### ISSUE TITLE
Updating existing project with the newer Ingnite-generated scaffolding 

### ISSUE THREAD

**Issue by alexissmirnov** [infinitered/ignite#514]
A question/discussion/feature request

I've stated a project a few weeks ago, got tons of value from the generated code - thanks! Now there's a new release of Ignite. Other than reading the change log, cherrypicking changes, is there anything that could be done to benefit from a new release?

A lot of files in my project didn't change since they were generated. There could maybe be a way to update those somehow?

A general question - is there an intent to support people who have created the project, or the focus is really on first-time project generation?

**Comment by GantMan** [comment]
It is our ambition to create an update system in version 3.0.   As for now, we are focussed on our 2.0 release, so the upgrade job falls solely on your shoulders 😞    We are open to any feedback on how we could make this simpler before 3.0.

As for your general question.  Our generators will be upgraded in 2.0, and will be updatable!  But the code they generate will not be our concern until 3.0

**Comment by GantMan** [comment]
Gonna close this issue, re-open if this fails to explain something, or comment if you have suggestions on how we could best help.
