### ISSUE TITLE
cannot install with yarn (no npm)

### ISSUE THREAD

**Issue by pvinis** [infinitered/ignite#515]
i tried installing with yarn. i dont have npm on my system. the installation failed because npm is hard-coded in the cli package.json to install the generator.

**Comment by GantMan** [comment]
we have yarn half-enforced.  Would you like the do the PR to fix this?
If not, we can fix it up for you.  Just let us know.

**Comment by pvinis** [comment]
im not super confident with yarn/npm/node stuff, so i dont know how to fix it exactly. i saw that you check if yarn is available, but i dont know how to do that in the package.json

**Comment by GantMan** [comment]
no worries!  We'll knock this out.

**Comment by skellock** [comment]
In Ignite 2, yarn is supported.
