### ISSUE TITLE
Add generator help to ignite-cli

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite#519]
Gitter question from @budda:

Is there a way to get a list of all the available generators from the 'ignite' command.. without finding the documentation url? 
Was hoping maybe `ignite generate --help` would do it.

Just a hassle to open a browser each time to remind my poor memory 😄

**Comment by GantMan** [comment]
To be honest this will soon be staring you clear in the face with the new ignite config file in 2.0, BUT! a command to make it clean is definitely first class!

RE: #488

**Comment by skellock** [comment]
There is now in Ignite 2.0.  `ignite g`.
