### ISSUE TITLE
Is it possible to change the indetation size of the generated files?

### ISSUE THREAD

**Issue by raymondctc** [infinitered/ignite#520]
I have tried updating the .editorconfig file in project folder but it seems not working

**Comment by GantMan** [comment]
this will be easy to change in ignite 2.0 - We're working diligently on this and more to be released hopefully soon!

**Comment by GantMan** [comment]
I'm leaving this ticket open until then.

**Comment by jamonholmgren** [comment]
We won't be building this into Ignite 2.0, but you can make your own generators that have the desired indentation and it'll work how you want it to. :)
