### ISSUE TITLE
how quickly ignite got updated to catch up with react-native version?

### ISSUE THREAD

**Issue by goodwill** [infinitered/ignite#524]
As title, I just installed react-native and its 0.39, but then I realise ignite binds to 0.37, as everyone kinda notice react-native is quite common to have fast deprecation and breaking changes, I want to know generally how quickly the team will catchup with react-native version?

**Comment by GantMan** [comment]
We normally are right on top of it.  Usually within days :)

Unfortunately we're strongly focussed on Ignite 2.0 updates and our bandwidth for updates has been somewhat suffering this past month.   We should move to (I believe it's 0.39.1 soon).  The update is actually quite trivial most of the time, but every so often it's big, so we try to put aside a few hours to get it right.

0.38 looks trivial, but 0.39 will be slightly more delicate.  We'll update this ticket with progress.

**Comment by GantMan** [comment]
Key info:  http://facebook.github.io/react-native/blog/2016/12/05/easier-upgrades.html

**Comment by ivankennethwang** [comment]
Is there any plans of moving to 0.40?

**Comment by skellock** [comment]
Yes.  In fact, we should go straight to 41 shortly.  Tracking on #638.
