### ISSUE TITLE
Installation fails with npm, run fails with yarn

### ISSUE THREAD

**Issue by Blackclaws** [infinitered/ignite#526]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [x ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [x ] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

```
Computer
  Platform: linux

Ignite
  Version: 1.12.0
  Path: /usr/bin/ignite

Node
  Version: v7.2.0
  Path: /usr/bin/node

NPM
  Version: 4.0.3
  Path: /usr/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.3.0

App
  React Native Version: ¯\_(ツ)_/¯
```

-----------------
So I wanted to check out ignite to see whether it could save me the hassle of wiring everything up myself. Trying to install it with npm -g results in the following:

npm ERR! Error: EACCES: permission denied, mkdir '/root/.npm/generator-react-native-ignite/1.12.0/package'
npm ERR!  { Error: EACCES: permission denied, mkdir '/root/.npm/generator-react-native-ignite/1.12.0/package'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/root/.npm/generator-react-native-ignite/1.12.0/package' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/react-native-ignite/npm-debug.log
npm ERR! Linux 4.8.11-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "react-native-ignite"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE

while running npm -g as ROOT. 

Installation with yarn using yarn global add react-native-ignite works as intended. However the result is not pretty:

/usr/lib/node_modules/yo/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Configstore.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:34:26)
    at Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:172:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

when running as ROOT again. When running as normal user:

🔥 Setting app on FIRE! 🔥
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------
Igniting app

✔︎ Finding react-native
✔︎ Finding android
✔︎ Finding git
⠋ Finding gitshell.js: internal error
Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/generator-react-native-ignite/app/templates'
    at Object.fs.mkdirSync (fs.js:854:18)
    at /usr/lib/node_modules/generator-react-native-ignite/node_modules/shelljs/src/mkdir.js:65:10
    at Array.forEach (native)
    at Object._mkdir (/usr/lib/node_modules/generator-react-native-ignite/node_modules/shelljs/src/mkdir.js:48:8)
    at Object.mkdir (/usr/lib/node_modules/generator-react-native-ignite/node_modules/shelljs/src/common.js:240:23)
    at emptyFolder (/usr/lib/node_modules/generator-react-native-ignite/app/index.js:62:21)
    at AppGenerator.cleanBeforeRunning (/usr/lib/node_modules/generator-react-native-ignite/app/index.js:287:7)
    at Object.<anonymous> (/usr/lib/node_modules/generator-react-native-ignite/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/lib/node_modules/generator-react-native-ignite/node_modules/run-async/index.js:25:25
    at /usr/lib/node_modules/generator-react-native-ignite/node_modules/run-async/index.js:24:19
ignite new app  7.35s user 0.46s system 127% cpu 6.135 total

It looks similar to https://github.com/infinitered/ignite/issues/493 however the permission fix on node modules does not work.

**Comment by Blackclaws** [comment]
Manually running the install for generator-react-native-ignite i.e. npm install -g generator-react-native-ignite works. 
Does the npm install drop privileges?

**Comment by Blackclaws** [comment]
The second problem that I get when installing with yarn appears also after manually installing generator-react-native-ignite. 

Apparently ignite tries to mkdir on the global node packages. This should not happen. I don't think ignite should require a change in owner of the node_modules directory to a user. Especially on shared installations this is not practical.

**Comment by GantMan** [comment]
looks like your npm permissions are borked.  Can you give this a go?  https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by Blackclaws** [comment]
Thats what I thought aswell. However the folders are already owned by root and permissions are all read + execute and only root write (as they should be). These fixes would propose changing the directory owner to a local user (which can work) but thats not desired for multi-user systems. It does work fine if I set the prefix to my home directory and create a "global" repository there as they propose in option 2. However this means that the packages will not be shared between users. 

As far as I see it a global installed package should be usable by all users without requiring ownership of te package directory. If this is not the case "global" install is a sort of misnomer isn't it?

**Comment by GantMan** [comment]
agreed.   Yeah, I'm not very well adept at fixing Node packages.  Always one of those things you have to be "at computer" to really understand.

Ignite will pull down a new templates directory on every init, which is why it tries to remove and reinstall that directory.

Is your goal to just try Ignite?  or to generate a fresh project?

If it is to just try, just pull down the repo, and run ignite-base.   You can build a project from there if you like.

**Comment by Blackclaws** [comment]
I originally just wanted to try it but ran into this problem then. This is starting to look more and more like a design flaw in the generator though (among other things) so this might be classified as a bug. The way I see it if ignite pulls down a new templates directory to the global installation everytime on init then of course it will fail if that directory is not owned  by the user. However normal npm global installs do go into a root owned /usr/lib/node_modules directory. The templates should then not be pulled there but into a temporary directory after a check whether the global directory is writable maybe.

**Comment by GantMan** [comment]
We're currently re-doing some aspects of Ignite for 2.0, and I'll make a note of this so we hopefully don't have this problem in the next version.

1.0 is always "Wow it actually works!" so, 2.0 is optimized and cleaner :)

**Comment by Blackclaws** [comment]
Well true. I guess if you know the workaround is to install the generator into a local global repository it works. But this is something that should at least fail more gracefully. Great tool nevertheless.

**Comment by skellock** [comment]
Ignite 2 supports yarn.  Shipping soon to an Internet near you.
