### ISSUE TITLE
Redux-Thunk instead of Redux-Saga in Ignite generated code

### ISSUE THREAD

**Issue by zarmeen92** [infinitered/ignite#528]
Can we use redux-thunk instead of redux-saga in Ignite generated application?

**Comment by GantMan** [comment]
This will be available as a feature in Ignite 2.0 - I'll leave this ticket open and help you get started when we release 2.0 for beta testing.

**Comment by zarmeen92** [comment]
@GantMan expected date of release of ignite 2.0?

**Comment by GantMan** [comment]
I'm hoping for early January

**Comment by leesolway** [comment]
Does this mean removing Saga's?

**Comment by GantMan** [comment]
sagas will not be removed.  We'll simply make it easy for people to customize (and if they go with Thunk, they will probably remove sagas) but we won't be managing the Thunk plugin.

**Comment by franzejr** [comment]
This is good, @GantMan. I think it might be very good have options: Sagas, Thunk, Loop, others. Cool!

**Comment by skellock** [comment]
The `--empty` or `--min` app templates both support DIY state management.  Creating your own generators in Ignite 2.0 is really straight forward.  We have some docs now in place for this, but I think a few videos would go a long way!

Thanks all!

**Comment by ajonno** [comment]
How can we opt out of redux-saga and instead just use redux-thunk when creating a new (Ignite CLI 2) app ?

**Comment by GantMan** [comment]
We haven't started it yet, but we plan to move Saga to a plugin, I believe.

Have you looked into or considered making a thunk plugin?  Then you'd just have to remove Saga by hand, and then install your thunk plugin.

**Comment by ajonno** [comment]
I'd love to create a thunk plugin, how can I get started / example etc ?

**Comment by skellock** [comment]
https://github.com/infinitered/ignite/blob/master/docs/advanced-guides/creating-plugins.md

Come join us on community.infinite.red if you need some realtime help.
