### ISSUE TITLE
UsageExampleScreen.js doesn't bind the button press handlers

### ISSUE THREAD

**Issue by budda** [infinitered/ignite#532]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

The rocket, send, star, trophy etc buttons don't do anything when pressed. This is due to the ```handlePressSend``` etc. methods not being bound with a ```onPress={this.handlePressRocket.bind(this)}``` in the JSX.

```
Computer
  Platform: darwin

Ignite
  Version: 1.12.0
  Path: /usr/local/bin/ignite

Node
  Version: v7.2.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.9
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.2.0

App
  React Native Version: 0.37.0
```

**Comment by GantMan** [comment]
heh, I missed an event

**Comment by kevinvangelder** [comment]
While the rockets method of binding is a convenient shorthand it's probably less than ideal for example purposes as it's much too easy for a new developer to overlook.
