### ISSUE TITLE
Improve Redux generator template

### ISSUE THREAD

**Issue by budda** [infinitered/ignite#534]
When generating a new Redux type add some more boilerplate to demonstrate basic get/set of some generic variables.

This would help new starters hopefully.

**Comment by budda** [comment]
Also include an example reset() Action for every generated Redux file.

```export const xyzReset = (state: Object) => INITIAL_STATE```

**Comment by skellock** [comment]
It's up to your app to decide if it makes sense to reset parts of the tree.

It's also possible to do this by installing a reducer at the top level which looks for an action  type of "CTRL_ALT_DELETE" to reset all state under it.  I've used this technique on Reactotron to both reset & inject new state externally.  =)
