### ISSUE TITLE
Add documentation links in generated template files

### ISSUE THREAD

**Issue by budda** [infinitered/ignite#535]
Add a comment to the top of generated template files which points the author to some recommended documentation regarding what they have just generated.

Spitting out a documentation hint / link from the CLI tool isn't suitable as that will get lost the day after.

**Comment by GantMan** [comment]
very nice.  Will do in our current generator refactor branch.

**Comment by skellock** [comment]
We now have docs in place.  I'm not sure putting that in the CLI is the best course of action though.  Links move & change.  

The new docs are shaping up nice.  I think they answer some more questions.  Certainly better than the "no docs" we had before!
