### ISSUE TITLE
Flow fails on fresh initialized ignite projekt

### ISSUE THREAD

**Issue by Blackclaws** [infinitered/ignite#536]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

```
Computer
  Platform: linux

Ignite
  Version: 1.12.0
  Path: /home/felix/.node_packages/bin/ignite

Node
  Version: v7.2.1
  Path: /usr/bin/node

NPM
  Version: 4.0.3
  Path: /usr/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.3.0

App
  React Native Version: 0.37.0
```
Initialized new project with:

  ignite new FlowTest

Run flow in project folder.
  yarn flow

Flow reports 109 errors mostly from within react-native. 

Expected behaviour would be that flow reports a clean folder.

**Comment by skellock** [comment]
We're up to 252 errors.  And we're not keeping the `.flowconfig` in sync either.  I recommend we not ship a .flowconfig override with our boilerplate.

**Comment by jamonholmgren** [comment]
@skellock This appears to be an Ignite 1 issue. What are you looking for in Ignite 2 with this?

**Comment by skellock** [comment]
I ran:

```sh
ignite new NewApp --max
cd NewApp
# then patch up flow to the latest version and run...
flow
```

We should be error free and happy out of the box.

**Comment by jamonholmgren** [comment]
Got it. When do you think it would be best to take that dive? I have this feeling that our app template is still in major flux. But maybe it's okay to jump into it? I'm happy to tackle this if so.

**Comment by skellock** [comment]
Our template is about to go through some changes ya.  But not tomorrow.

We don't need to go full crazy flow, but we should at least not have any errors.  Or perhaps we remove it because we're not ready?

I'll defer to @GantMan on this.  I'll agree with whatever he says.

**Comment by jamonholmgren** [comment]
I'll agree with whatever @GantMan says too.

**Comment by jamonholmgren** [comment]
I'm going to remove Flow.

**Comment by skellock** [comment]
Ya I agree. Just for now while we're renovating.
