### ISSUE TITLE
null response on sagas, but the API gets called

### ISSUE THREAD

**Issue by jjbernal** [infinitered/ignite#543]
Hello.

I call an API in the saga like this:
```
const response = yield call(api.postLogin, username, password)
```
and the value of _response_ is null, eventhough I can see via Reactotron that the call to the API is done correctly and an API response is returned.

In fact, if I don't check for a null response  afterwards, the app crashes.

Here's the output for `ignite doctor` 
```
Computer
  Platform: darwin

Ignite
  Version: 1.12.0
  Path: /usr/local/bin/ignite

Node
  Version: v7.2.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.9
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.3.0

App
  React Native Version: 0.37.0
```

Thank you.

**Comment by skellock** [comment]
What does your `postLogin` function look like?

I agree with you, it should *never* be null.

**Comment by jjbernal** [comment]
Here it is:

```
const postLogin = (username, password) => {
    api.post('user/login', {id: username, password: password})
}
```

**Comment by skellock** [comment]
Try removing those braces after the fat arrow or add a `return` to the front of your `api.post` line.

**Comment by jjbernal** [comment]
Ok, that did the trick.
Thank you!
