### ISSUE TITLE
[2.0] destructuring error

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#546]
Probably node failing to do a node check.
![image](https://cloud.githubusercontent.com/assets/997157/21287276/4d6724a2-c42d-11e6-8eb3-8c9e7759cf8a.png)

known that node < 6 would be problems, but this doesn't really tell the user shiiiiiiiii
```
 $ node -v                                                                                                                                            
v5.1.0
```

**Comment by GantMan** [comment]
upgrading to node 7 fixed this, but the issue is we need to check ES6 things before using them, the irony is the check fails.  I would even assume pushing this to gluegun for real fixing.

**Comment by skellock** [comment]
I agree 100%.

Gluegun has it's own check.  I'll make sure it's not happening there as well, but this `cli.js` is located within ignite and we should be as safe as possible.

This totally didn't cross my mind at all.  We can prevent this error for sure.

Thanks.

**Comment by skellock** [comment]
Ignite 2 requires Node 7.6 now.
