### ISSUE TITLE
[RFC | Base] Maps

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#55]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base applicattion
  - [ ] ignite the cli
  - [ ] ignite generated code

Should we put a map screen inside base?   Basic maps are easy, but cross platform maps with callouts and a sort of agreed upon best interaction UX, would be nice. 

For those of you who've done RN maps, I would like opinions.

For those of you who have not, I'd like your gut reaction.

**Comment by skellock** [comment]
Yes.  Let's dump everything useful in.  Kitchen sink style.   

`v2.0` on the roadmap is to be selective at ignition time.

**Comment by jamonholmgren** [comment]
> ignition time

I like that @skellock

**Comment by jamonholmgren** [comment]
@GantMan I think having kitchen-sink is useful for sure.

**Comment by steve21124** [comment]
this react native maps has 954 stars. 
https://github.com/lelandrichardson/react-native-maps

**Comment by ahmed1490** [comment]
is this closed?

**Comment by GantMan** [comment]
I want to keep it open until we're no longer dependent on Steve's branch.   I feel we can't forget it in this odd state.   Even though it works, it shouldn't sit like this long.

**Comment by skellock** [comment]
Agreed.  I don't want my branch to exist.

More info:

https://github.com/lelandrichardson/react-native-maps/issues/331

**Comment by ahmed1490** [comment]
looks like already works with 0.29 
https://github.com/lelandrichardson/react-native-maps/pull/370

**Comment by GantMan** [comment]
We need to bring maps back in now, it should be good.
