### ISSUE TITLE
Simplify mapStateToProps with Ramda?

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#552]
Consider: 
![image](https://cloud.githubusercontent.com/assets/997157/21316420/3b49f55c-c5c6-11e6-8413-35a168e34ffa.png)
And ultimately a very clean version:
![image](https://cloud.githubusercontent.com/assets/997157/21316458/7a47394a-c5c6-11e6-9a0d-f0120436799e.png)
from
http://randycoulman.com/blog/2016/02/16/using-ramda-with-redux/

#### Possible complaints?
* How can I change the name of one item?
* I'd like to pick `state.board.teacher` not the entire board.  How can I do that?

**Comment by jamonholmgren** [comment]
I'd say this is lower priority, although the curried version is very nice!

**Comment by skellock** [comment]
Pick can't change the name, but evolve can.  Really it depends on what you're trying to do.  It really depends on the app.  

I'd say in our boilerplate, we need a little less clever things though.  I even think we've gone too far with reduxsauce.  I keep hearing this complaint over & over again.

I'm going to close this up, but you should use this technique in your app if it makes sense for you.  I know I'm going to now.
