### ISSUE TITLE
API help

### ISSUE THREAD

**Issue by mtwallet** [infinitered/ignite#553]
Hi there.

First of all thank you for an excellent starter kit, great work. I am in the middle of my first RN project and have decided to move it over to Ignite, I feel it will help me to improve my project and code.

That said some of the concepts are different than the way I have learned to do things and I would appreciate a little help; firstly with how to structure the API file.

My project has a number of methods each with different configurations, for example my current Axios configs (currently inside Sagas) look like:

Authenticate

```JS
  const config = {
    url: 'http://xyz.com/token',
    method: 'post',
    data: {
      client_id: 2,
      grant_type: 'password',
      username: action.username,
      password: action.password
    },
    transformRequest: [function (data) {
      const credentials = qs.stringify(data);

      return credentials;
    }],
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    }
  };
``` 

Fetch orders

```JS
  const config = {
    method: 'get',
    url: 'http://xyz.com/get-orders',
    headers: {
      Authorization: `Bearer ${state.auth.token}`
    }
  };
``` 

Create order

```JS
  const config = {
    method: 'post',
    url: 'http://xyz.com/create-order',
    params: {
      orderId: state.currentOrder.currentOrderId,
      trolleyNumber: 'trolleyNumber'
    },
    headers: {
      Authorization: `Bearer ${state.auth.token}`
    }
  };
```

I maybe over thinking this but would I structure this the same in Ignite with 3 separate API files given the configs are slightly different? or is there a preferred method of combining them into a single file. Apologies if this is a ridiculously simple question! but I'm quite new to this and I want to make sure I'm not working against Ignite best practises.

**Comment by GantMan** [comment]
Hi!  And welcome to Ignite :)

That's very interesting that your API requires 3 different configuration states in order to handle 3 different calls.

But does it?   From what I see above, you're doing `.post`, `.get` and simply passing params to those functions.   Couldn't you create an API with all the state you would need, and simply post/get with that API?

Take a look at the API testing screen, and perhaps make some test API calls there.

Yes you can create 3 different API objects with 3 different states, but that might be overkill for your situation.   Let us know if this advice helps, or if you need more details.

**Comment by mtwallet** [comment]
@GantMan thanks for the reply, I appreciate the help. I'll take a look and report back.

**Comment by mtwallet** [comment]
@GantMan Thanks for the warm welcome! I have managed to get my authentication working in the api test screen. I have no clue whether I am doing this correctly but it works using:

```JS
    import qs from 'querystringify'

    const create = (baseURL = 'http://XYZ.com/') => {

      const api = apisauce.create({
        baseURL,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        timeout: 10000
      })

      const signInUser = (username, password) => api.post('/token', qs.stringify({
        client_id: 2,
        grant_type: 'password',
        username,
        password
      }))

      return {
        signInUser
      }
    }

    export default {
      create
    }
```

and in the test screen

```JS
    const endpoints = [
      { label: 'Sign in user', endpoint: 'signInUser', args: ['username', 'password'] }
    ]
```

I've got that working with the `LoginSaga` and it populates my store with the token on success, happy days! (I think) :)

I've setup my next api endpoint for fetching orders which looks like this:

```JS
    const getAllOrders = (token) => api.get('api/sales/get-picking-orders', {
      headers: {
        Authorization: `Bearer ${token}`
      }
    })
```

but because in the test screen:

```JS
    const endpoints = [
        { label: 'Sign in user', endpoint: 'signInUser', args: ['username', 'password'] },
        { label: 'Get all orders', endpoint: 'getAllOrders', args: [token] }
    ]
```

the token falls outside of the `APITestingScreen` class I cannot get access to the token. Is there way to access to the token easily so I can test my endpoint?

**Comment by kevinvangelder** [comment]
@mtwallet If your token is in the store, you'll want to use `this.state.token` and in your `mapStateToProps` set `token: state.login.token` (replace `login.token` with the correct path to where you've stored the token).

If you post a gist with the two or three files you're working on we'll be better able to help you. Also, for more interactive assistance, check out our [Gitter room](https://gitter.im/infinitered/ignite).

**Comment by skellock** [comment]
Come find us in http://community.infinite.red to chat more about this.
