### ISSUE TITLE
You don't seem to have a generator ... installed

### ISSUE THREAD

**Issue by nonameolsson** [infinitered/ignite#563]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [X] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [x] ignite the cli
  - [ ] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).
-------

So, I can't start a new project. I have followed the instructions to install Ignite with `npm install -g react-native-ignite`. But when I run `ignite new Secretary` it tells med `You don't seem to have a generator with the name react-native-ignite installed.`.
```
~/Development/ReactNative
▶ npm install react-native-ignite -g
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/Users/nonameolsson/.nvm/versions/node/v6.6.0/bin/ignite -> /Users/nonameolsson/.nvm/versions/node/v6.6.0/lib/node_modules/react-native-ignite/index.js

> react-native-ignite@1.12.0 postinstall /Users/nonameolsson/.nvm/versions/node/v6.6.0/lib/node_modules/react-native-ignite
> npm i -g generator-react-native-ignite

/Users/nonameolsson/.nvm/versions/node/v6.6.0/lib
└── generator-react-native-ignite@1.12.0

/Users/nonameolsson/.nvm/versions/node/v6.6.0/lib
└── react-native-ignite@1.12.0


~/Development/ReactNative
▶ ignite new Secretary
🔥 Setting Secretary on FIRE! 🔥
Error react-native-ignite Secretary

You don't seem to have a generator with the name react-native-ignite installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 4 registered generators run yo with the `--help` option.

~/Development/ReactNative
▶ ignite doctor

Computer
  Platform: darwin

Ignite
  Version: 1.12.0
  Path: /Users/nonameolsson/.nvm/versions/node/v6.6.0/bin/ignite

Node
  Version: v6.6.0
  Path: /Users/nonameolsson/.nvm/versions/node/v6.6.0/bin/node

NPM
  Version: 4.0.5
  Path: /Users/nonameolsson/.nvm/versions/node/v6.6.0/bin/npm

Yeoman
  Version: 1.7.0

React Native CLI
  Version: 2.0.1

App
  React Native Version: ¯\_(ツ)_/¯

~/Development/ReactNative
▶
```

**Comment by nonameolsson** [comment]
Any comments? I still have this issue, and can't manage to get started with ignite. I have also installed:
`npm install -g generator-react-native-ignite`.

What am I missing here? I really want to get started with Ignite :)

**Comment by derekgreenberg** [comment]
@nonameolsson Looks like this might be an issue with npm installs on your system. Take a look at https://github.com/yeoman/yo/issues/403 for actions you can take to fix the problem.

**Comment by nonameolsson** [comment]
Thank you @derekgreenberg! That worked.
