### ISSUE TITLE
[2.0] Ignite - basic - structure

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#568]
`ignite add basic-structure`

Creates basic ignite folders and approved structure.   As of right now, this will include the following opinions:

* Redux
* Sagas
* Navigator - RNRF

This is the only plugin for `ignite new something --min`

This plugin does the following:
* Copies over your index.ios.js to look at App folder
* Copies over your index.android.js to look at App folder
* Creates a README if none is exists
* Creates an ignite.toml file if none exists (should there be an ignite directory?)
* Creates an App folder in root
* Creates App/Components
  * README.md
  * App/Components/Styles
* Creates App/Config
  * README.md
  * App.Config.js
  * DebugConfig.js
  * index.js
* Creates App/Containers
  * README.md
  * App/Containers/Styles
  * App.js
  * RootContainer.js
* Creates App/Fixtures
  * README.md
* Creates App/Images
  * README.md
  * all Ignite images
* Creates App/Lib
  * README.md
* Creates App/Navigation
  * Create App/Navigation/Styles
  * README.md
  * NavItems.js
  * NavigationRouter.js
* Redux
  * CreateStore
  * index
  * StartupRedux.js
* Creates App/Themes
  * README.md
  * ApplicationStyles.js
  * Colors.js
  * Fonts.js
  * Images.js
  * index.js
  * Metrics.js
* Creates App/Transforms
  * README.md

**Comment by GantMan** [comment]
the goal is to have ignite basic structure break up into pieces and get smaller as more parts are modularized.

**Comment by skellock** [comment]
I vote to remove redux, sagas, and RNRF from `--min`.  It should be just the *core* stuff.  Some apps might not need sagas or even redux.

**Comment by skellock** [comment]
Done.  `--min` is in place for 2.0.   And to 1-up ourselves, `--empty` is now a thing.
