### ISSUE TITLE
npm package.json goodies

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#57]
@skellock deserves the credit for adding these two beautiful Android scripts
```
    "android:logcat": "$ANDROID_HOME/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V",
    "android:shake": "$ANDROID_HOME/platform-tools/adb shell input keyevent 82"
```

Rather than stealing his thunder ⚡  I made this ticket so he can do it.

**Comment by skellock** [comment]
hahaha... ok.   incoming!

**Comment by skellock** [comment]
https://github.com/infinitered/ignite/pull/58
