### ISSUE TITLE
Mapview broken in Android base application

### ISSUE THREAD

**Issue by perqa** [infinitered/ignite#570]
<img width="289" alt="screen shot 2016-12-27 at 18 07 14" src="https://cloud.githubusercontent.com/assets/960796/21504495/c08a8d36-cc5f-11e6-94ad-7aba523ded90.png">

Application created by 

``ignite new TestApplication``

Everything seems to work, except Mapview on Android.

**Comment by GantMan** [comment]
You can use our key for now:  
https://github.com/infinitered/ignite/blob/master/ignite-base/android/app/src/main/AndroidManifest.xml#L51-L54

I'll make sure this works in what I'm working on for Ignite 2.0

**Comment by jamonholmgren** [comment]
This will be part of the `ignite-mapview` plugin, which I don't think has been started yet.

**Comment by jamonholmgren** [comment]
Fixed in #741 I think?

**Comment by jamonholmgren** [comment]
Okay, never mind -- this is maps, that was weather service.

**Comment by jamonholmgren** [comment]
Moving to `ignite-maps`.
