### ISSUE TITLE
Question: What styling controls the presentation page shrinking effect in the default app?

### ISSUE THREAD

**Issue by stubblychin** [infinitered/ignite#581]
Hi,

A small question to help a noob understand things a bit better.

On the default app, in android, when I move back to the PresentationScreen, from one of the sub pages, (not the the menu drawer), the contents of the presentation screen seem to do a grow/shrink effect.  It also has a white padding/border around it as it shrinks/grows.

I suspect there is a style somewhere controlling this, but I can't find it, or it isn't where I think it is.

**Comment by GantMan** [comment]
can you make a small video showing this effect, it doesn't come to mind.

**Comment by stubblychin** [comment]
Here's a quick demo I made via my Nexus phone (which is a higher version than marshmallow) 

https://youtu.be/6x1PPlQ19FQ

**Comment by GantMan** [comment]
Ah yes!  I'm familiar with that.  I think that's either part of the transitions in React Native, OR that comes from RNRF.   I'm pretty sure it's configurable.

@skellock - do you know?

**Comment by skellock** [comment]
Oh ya... that's the default transition in Navigation Experimental (inside RNRF).  They do a 95% scaling which will cause that silly white background.

I'm not entirely sure where to go to change it, but I know that Navigation Experimental is customizable.

Hope that helps.

**Comment by stubblychin** [comment]
You are indeed correct.  There is a fadeInScene function in node_modules/react-native-router-flux/src/DefaultRenderer.js which has a 0.95 scaling.

That function gets called by the direction interpolator.  How I override this I've no clue.

**Comment by GantMan** [comment]
You can pass your own animation style with your own interpolation function:

https://github.com/aksonov/react-native-router-flux/blob/38260d7812431dfc39195391c11ff14924b989d7/docs/API_CONFIGURATION.md
