### ISSUE TITLE
[2.0] Proposed Navigation Construct

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#593]
When a plugin wants to add a screen as an example screen, there needs to be a construct for not only copying the screen, but also adding that screen to the routes, opening it etc.  This means we need to wrap an abstract layer around our Navigation, should we (likely we will) deviate from RNRF in the future.

I'm suggesting we have a command that is exposed to the user and the other functions via CLI.

```sh
# Example CLI for asking for a screen to be added
ignite router add Path/to/SomeScreen.js
# Adds reference to SomeScreen to routes list, so other screens can now open it.

# Example CLI for asking for a screen to be removed
ignite router remove SomeScreen.js
# Removes reference to SomeScreen from routes (Full path not needed).  
# Removed file remains on disk, just removed from routes.
```

**Registering new screens 👍 , Opening 👎** 
Now a screen _can_ be opened, but screen opening is different for every router  :rage2:  We abstract this away behind an Ignite file so plugin authors can open screens without knowing what navigation has been selected.
```js
// If using RNRF this contains NavigationActions
import IgniteNav from '../Navigation/IgniteNav.js'
...
// If using RNRF this is like NavigationActions.someScreen({someValue: true})
IgniteNav.open('SomeScreen', {someValue: true})
```
Keeping IgniteNav as an API shim, we can then hot-swap navigation later if needed.

### The Ignite Plugin Author Experience
They use `ignite.addScreenExample('path/of/file/to/add')`, and they are good.  

_thats it!_

Under the hood, this does the following:
* copies the file to Examples/Containers 
* runs `ignite router add path/of/file/to/add`
* adds a button to `PluginExamplesScreen` which uses `IgniteNav` to open the new screen.  

Plugin authors can use any of these steps manually should they need a more complicated example setup.

**Comment by skellock** [comment]
Seems reasonable to me.

For `addScreenExample`, that makes sense to me.  What about if there's extra files needed to accompany that screen?  Like images and stuff?  I guess it'd be just up to the plugin author to put them in the right place too.

I wouldn't mind seeing what happens with `react-navigation`'s api before we commit to something.  Especially since we're all hoping that it'll be the thing we use.

What do you think about calling it `ignite screen add` instead of `ignite router add`?

**Comment by GantMan** [comment]
> For addScreenExample, that makes sense to me. What about if there's extra files needed to accompany that screen? Like images and stuff? I guess it'd be just up to the plugin author to put them in the right place too.

Yup, authors will need to move files if they get fancy.  My hope is that as the need grows, we can be in touch with the authors to add features.

> I wouldn't mind seeing what happens with react-navigation's api before we commit to something. Especially since we're all hoping that it'll be the thing we use.

That's what I'm saying though.  We don't want to commit.  If later we change the navigation, we just make it fit our API.  Am I missing what you're saying?  We're not actually committing, that's the benefit.

> What do you think about calling it ignite screen add instead of ignite router add?

I'm fine with that!  Let the noodley goodness flow!

![image](https://cloud.githubusercontent.com/assets/997157/21965593/c8f5a924-db28-11e6-98d2-342802975ed8.png)

**Comment by skellock** [comment]
Question:  Is this just for adding ignite sample screens?  Or are you thinking for how we'll be navigating within our app?

If it's just ignite sample screens, then we can do whatever you want.  We're creating the dev screen experience.

If you're talking for how all navigation works in our app, I do have some questions about what I'm seeing.

1.  The concept of `open` as a verb might not be enough.  push, pop, replace, popTo.  These are all verbs that need to be considered.

2.  Figuring out just how much goes in a router vs go into a command.  When I say `open('MyScreen')` and it's on a different tab... how will that work?  I know it'll be up to the underlying navigator's implementation, but I'm concerned about defining a language for that without seeing `react-navigation` in action.

3.  IgniteNav as a singleton.  On iPad portrait, you can have two distinct navigators.   Globals might preclude that unless we can pass a "window" (or whatever it is called) to it.

**Comment by GantMan** [comment]
> If it's just ignite sample screens, then we can do whatever you want. We're creating the dev screen experience.

Devscreens with a unknown navigation is the driving force of this need. 

> If you're talking for how all navigation works in our app, I do have some questions about what I'm seeing. 

Anyone who uses `IgniteNav`, and the features built into it, will be protected from future swaps/changes in navigation.  If the power of `IgniteNav` is found wanting, people can use the underlying architecture, but they will not be protected should they later swap out.  Which, let's be honest, you should know that.

so the short answer is this:  Since IgniteNav is node-module proof, it makes sense that eventually we can grow it, especially when we need to swap.  But for now it serves the needs with only the open/close.

**Comment by skellock** [comment]
So this proposal is "how to use navigation" in an ignite app... of which devscreens will use?

**Comment by GantMan** [comment]
yes.  But a better way to say it is this.   How dev screens will use navigation, and perhaps one day all Ignite apps (version 2.5?  Just an idea that never happens?  Who will know!?)

**Comment by skellock** [comment]
So I don't mind us coming up with our own navigation for dev screens, but tying that in with how the navigation for the app works is biting off too much, in my opinion.

Wanna chat in person tomorrow?

**Comment by GantMan** [comment]
sounds good!

**Comment by skellock** [comment]
I think `react-navigation` should be our exit path here.  If others want to use different navigation libs, we allow them by them making their own app templates.

Supporting 1 router is hard enough.  Supporting them all is impossible.

Please feel free to re-open this if you think I'm drinking too much crunk juice.
