### ISSUE TITLE
Drawer switches sides on right-to-left locale, but it's mask doesn't

### ISSUE THREAD

**Issue by projoneftw** [infinitered/ignite#596]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

`ignite doctor`:

```
Computer
  Platform: darwin

Ignite
  Version: 1.13.0
  Path: /Users/alexandermargulis/.nvm/versions/node/v7.4.0/bin/ignite

Node
  Version: v7.4.0
  Path: /Users/alexandermargulis/.nvm/versions/node/v7.4.0/bin/node

NPM
  Version: 4.0.5
  Path: /Users/alexandermargulis/.nvm/versions/node/v7.4.0/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 2.0.1

App
  React Native Version: 0.38.0
```

awesome project you got here! 👍 
I found that the side menu becomes un-closable when switching to right-to-left language. But then I saw that the mask is still sitting on the right side, so it's closable, but weird :)
I'm very new to react native and mobile dev, so not sure where to fix that... my guess is the drawer mask has absolute position, so when when drawer sticks to right, the mask stays at right instead of going left.
Steps to reproduce: switch to hebrew lang (on Android it looks like this: "עברית").

**Comment by kevinvangelder** [comment]
@projoneftw Thanks for finding and reporting this issue. Turns out that this is a problem with the react-native-drawer library. https://github.com/root-two/react-native-drawer/issues/225
