### ISSUE TITLE
New syntax for `patching.insertInFile`

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#598]
Currently, `insertInFile` does this:

```javascript
    if (!patching.isInFile(launchScreen, 'import DevscreensButton')) {
      patching.insertInFile(launchScreen, 'import styles', 'import DevscreensButton from \'./Components/DevscreensButton.js\'\n', false)
    }
```

I'd like to propose named parameters:

```javascript
    patching.insertInFile(launchScreen, {
      after: 'import styles', // or before:
      insert: 'import DevscreensButton from \'./Components/DevscreensButton.js\'\n'
    })
```

Additionally, if the `insert` already exists, it doesn't error -- it simply ignores it. This will let this function be idempotent.

I can implement this if it's good to go.

**Comment by kevinvangelder** [comment]
Since contributors will likely be using this tool on a semi-regular basis it seems like improving the interface in this way would be worthwhile.

**Comment by jamonholmgren** [comment]
BTW I already have a version of this implemented, see the ignite-i18n package index.js.

**Comment by skellock** [comment]
Great, i hadn't realized it's already in production.
