### ISSUE TITLE
Add option to pass a react native version.

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#602]
In Ignite 2 for the `new` command.  It'd be nice to support multiple versions of React Native.

```sh
ignite new SpecialVersion --react-native 0.41.0-rc.0
```

[From a discussion](https://github.com/infinitered/ignite/pull/601#discussion_r97225821) we had recently.

The default will be whatever we're expecting it to be for Ignite.  And we'll be updating this frequently.  This would be great though, to test out release candidates, or whatever.  We do run the risk of not being compatible with our `ignite-basic-structure`, however, if you're setting this flag, you already know what you're doing and how to fix it.

**Comment by skellock** [comment]
Now in place.

**Comment by naza13** [comment]
after the ''new'' command I wrote down  ''--react-native 0.45.1-rc.0'' but it still doesn't work
