### ISSUE TITLE
ignite add should protect against packages without package.json

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#605]
Currently, trying to add a package without a `package.json` results in a nasty error. Check and display an error if there is no package.json.

Likely around `src/plugins/default/commands/add.js` line 74.

@GantMan @skellock

**Comment by jamonholmgren** [comment]
Additionally, we should do the following:

* [ ] If no `index.js` in the plugin, then don't require an add / remove function
* [ ] If there is an `index.js` in the plugin, then detect if it's missing `add` and give a friendly error. Don't require `remove`.

**Comment by kevinvangelder** [comment]
Closed by #617
