### ISSUE TITLE
Error when I run android

### ISSUE THREAD

**Issue by thiagoterleski** [infinitered/ignite#607]
Has anyone had the same problem?

![captura de tela 2017-01-24 as 11 44 46](https://cloud.githubusercontent.com/assets/2950918/22249678/12dd28ba-e22b-11e6-9734-dea77c7d0a94.png)

### ignite doctor
```
Computer
  Platform: darwin

Ignite
  Version: 1.13.0
  Path: /usr/local/bin/ignite

Node
  Version: v7.2.0
  Path: /usr/local/bin/node

NPM
  Version: 4.1.1
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 2.0.1

App
  React Native Version: 0.38.0
```

**Comment by ruddell** [comment]
"React native uses 23.0.2. maps uses 23.0.3. and some other 3rd party libs use 23.0.1." - skellock
![android](https://cloud.githubusercontent.com/assets/4294623/22255000/e610b98e-e20a-11e6-82b0-318e3942a6b8.png)

**Comment by thiagoterleski** [comment]
Thanks!
