### ISSUE TITLE
Move Android Release Task to Command

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#61]
- [x] Issue does not already exist
- Identify exactly what aspect you're issue is about
  - [ ] ignite base applicattion
  - [x] ignite the cli
  - [ ] ignite generated code

As of right now, when you want to get your app ready to release on android, you have to do a lot of manual work.  This and things like this seem to lend themselves to ignite command.

https://facebook.github.io/react-native/docs/signed-apk-android.html

**Comment by jamonholmgren** [comment]
The "you're" vs "your" thing in the issue template bugs me ... :)
