### ISSUE TITLE
Add a way to make an ignite plugin generator.

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#614]
Let's make it easy for people create ignite plugins, by providing them with boilerplate.

```sh
ignite plugin new i18n
ignite plugin new MyPlugin
```

@jamonholmgren wanted this which gives purpose to the new plugin namespace.

```sh
ignite plugin list
```

**Comment by jamonholmgren** [comment]
#665 adds the generator and #728 adds `list`, `search`, and `info`.
