### ISSUE TITLE
Ignite TOML should require an '[ignite]' node

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#615]
We shouldn't assume that the `ignite.toml` has a `[ignite]` entry.  Some plugins don't have anything in there.

Let's fix this up:

https://github.com/infinitered/ignite/blob/next/packages/ignite/src/plugins/default/commands/add.js#L98

**Comment by kevinvangelder** [comment]
Related to #616

**Comment by skellock** [comment]
Fixed by #655 .  `ignite/ignite.json` is now completely optional.
