### ISSUE TITLE
Testing For Ignite 2

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#621]
Lulz.  Let's start.  It's too fragile.

**Comment by Blackclaws** [comment]
Is there an official guide how to build and install ignite 2.0? Or are you going to publish @next npm packages?
Should we start using 2.0 for production for easier migration?

**Comment by skellock** [comment]
Not quite ready for human consumption just yet.  

We will tag with a pre-release once we're ready to go though.  So much has been fluctuating, it'd be demoralizing for someone to start documentation just yet.  :)

**Comment by jamonholmgren** [comment]
Ref #675

**Comment by skellock** [comment]
Closing, we have tests.
