### ISSUE TITLE
Can't do a basic install

### ISSUE THREAD

**Issue by veebuv** [infinitered/ignite#628]
The error i'm getting, sorry if this has already been issued, but I just can't fin a work around

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/generator-react-native-ignite/app/templates'
Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

**Comment by Blackclaws** [comment]
See this:

https://github.com/infinitered/ignite/issues/526

**Comment by skellock** [comment]
Many of the permissions issues have been resolved in Ignite 2 because the only directory we write to is the one you're making for your React Native app.
