### ISSUE TITLE
Weird "NETWORK_ERROR" while connect to my serve

### ISSUE THREAD

**Issue by yayolius** [infinitered/ignite#629]
Hello, i am having the same issue than this buddy: https://github.com/skellock/apisauce/issues/22,
I am developing in Android, but everytime that i try to access my development server in localhost in http://localhost:3000, it get an NETWORK_ERROR response, but the app is connected, and the network is working.
But when i try to access external domains like http://api.github.com IN THE SAME file, it works without any issue.

``
import apisauce from 'apisauce'

const create = (baseURL = 'http://0.0.0.0:3000/api/') => {

  const api = apisauce.create({
    // base URL is read from the "constructor"
    baseURL,
    // here are some default headers
    headers: {
      'Accept': 'application/json',
      'Cache-Control': 'no-cache'
    },
    // 10 second timeout...
    timeout: 10000
  })

  if (__DEV__ && console.tron) {
    api.addMonitor(console.tron.apisauce)
  }

  const getEvents = () => api.get('Events')
  const getEvent = (id) => api.get('Events/'+id+'/')

  return {
    getEvents,
    getEvent
  }
}

// let's return back our create method as the default.
export default {
  create
}
``

As a server i am using an standard loopback app, i have beign debugging this for 2 days and i don't see any other issue.

Best Regards.
Claudio

**Comment by skellock** [comment]
Did you port forward?  Your server is probably running on your computer and not your android device.

`adb reverse tcp:3000 tcp:3000` to open up a reverse tunnel.
