### ISSUE TITLE
Need new API Key for Examples

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#633]
Someone went crazy on our API key
![image](https://cloud.githubusercontent.com/assets/997157/22406164/5ae98f68-e613-11e6-85cf-10e39a810102.png)

Looks like we're not going to be able to use this one.  Need to either open a new account, OR switch API for examples.

**Comment by skellock** [comment]
LOL.  Someone really needed to check the weather.

We shouldn't have an API key in our examples, though.  

I've used Github's API in Reactotron.  You can do 60/hr without a key per-ip.  

Here's more options https://github.com/toddmotto/public-apis

**Comment by GantMan** [comment]
I think moving to github is best.   You can't trust the weather :D :umbrella:

**Comment by jamonholmgren** [comment]
Great idea @skellock

**Comment by skellock** [comment]
Tracking on #740.
