### ISSUE TITLE
Upgrade to React Native 0.41.0

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#638]
Welcome to February!  

Ignite 1 is still at 0.39.2.  0.40.0 was a bit of "destroyer of worlds" upgrade, but 0.41.0 looks to be a little easier (minus that breaking Java change that may affect 3rd parties).

Let's get us up on 0.41.0.

**Comment by waqas19921** [comment]
When will ignite version that supports 0.41 being launched?

**Comment by GantMan** [comment]
I think we have it in 2.0, if you'd like to use that.

Otherwise we'll be getting it into 1.x this weekend.

**Comment by valinaga** [comment]
Hi,

Any updates on RN 0.41? Can't wait to get into it. Thanks.

**Comment by GantMan** [comment]
@valinaga - would you like to try 2.0?  I'll screen share with you and you'll be on RN 0.41

**Comment by valinaga** [comment]
This will be great!
Thanks,

Vali Nagacevschi
CEO

Tel:+ 40 788 10 10 11

**Comment by waqas19921** [comment]
I have tested RN 0.41 with ignite 1.13 there is no breaking thing everything is fine. Please update to RN 0.41.

**Comment by valinaga** [comment]
RN 0.41 goes with which version of react?
Thanks

Vali Nagacevschi

**Comment by valinaga** [comment]
It didn't work with actual version. I'm getting errors about headers all over the places.
Please let me know when the 2.0 version will be ready. 
Thanks

**Comment by skellock** [comment]
Ya, Ignite 1 is staying at 0.39.2 because of breaking changes to iOS components introduced by React Native 0.40.0.

In Ignite 2.0 we're on the latest.

More details when it ships!

**Comment by waqas19921** [comment]
@valinaga update following npm packages and then run everything will be alright.
    ```
"apisauce": "^0.7.0",
    "react-native-device-info": "0.9.9",
    "react-native-drawer": "^2.3.0",
    "react-native-i18n": "1.0.0",
    "react-native-maps": "^0.13.0",
    "react-native-vector-icons": "4.0.0"
```

**Comment by valinaga** [comment]
@waqas19921 I started a new ignite project. The I edited the package.json as above.
I also changed "react-native": "0.41.0".
I deleted node_modules and run npm install
Then I run react-native run-ios and got lot of errors about headers not found.
Is it something I'm missing?
Thanks!

**Comment by skellock** [comment]
You need to update your headers to the new <React/RCTView.h> (etc.) import method. Also update your scheme to remove parallelization and add the React library first in the build order.

Then you need to make sure your third party libs are up to date ( or using non public releases in the case of react-native-maps 0.13.0).

This was a frustrating upgrade.

**Comment by valinaga** [comment]
@skellock is there anywhere a step by step instruction on how exactly to do it? Upgrading headers and the rest? Thanks.

**Comment by skellock** [comment]
Not really a guide, but here's some more info:  https://twitter.com/skellock/status/818813810781908992/photo/1

**Comment by valinaga** [comment]
Well, it finally worked! Such an pain, though. Hope the upgrade from 1 to 2 not to be so bad. Thanks @skellock and @waqas19921 !

**Comment by skellock** [comment]
We use React Native, so unfortunately it will be complicated for some people because we have to do these steps. 💩🙈
