### ISSUE TITLE
Generation of a map view breaks

### ISSUE THREAD

**Issue by rameez-dynamo** [infinitered/ignite#640]
So I have been trying to generate a map-view using the ```ignite generator``` feature for last few hours and it breaks. The following were my theories:

1. Something to do with the setup of the ```AndroidManifest.xml``` file. So I added the location permissions and also a Google Maps API key. Then I reran the ```ignite generate mapview```. No fruits borne. 

2. Something to do with the structure of my existing Ignite project, which is causing this to break. So I generated a new project and tried the same command. Nothing.

This is the error I get. 

<img width="1413" alt="screen shot 2017-02-02 at 7 01 48 pm" src="https://cloud.githubusercontent.com/assets/24460705/22562051/3b2cfad2-e97b-11e6-8bed-08de98f3fd2a.png">

Anyone else experiencing this?

`ignite doctor` output:

```
Computer
  Platform: darwin

Ignite
  Version: 1.13.0
  Path: /usr/local/bin/ignite

Node
  Version: v7.1.0
  Path: /usr/local/bin/node

NPM
  Version: 3.10.9
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.2.0

App
  React Native Version: 0.38.0
```

**Comment by kevinvangelder** [comment]
Can you confirm you have the SDKs for 23.0.1, 23.0.2, 23.0.3, and Google Play Services in your Android SDK manager?

**Comment by rameez-dynamo** [comment]
I do have those installed.

**Comment by skellock** [comment]
Please feel free to re-open if you're still stuck.   React Native Maps is tricksy.
