### ISSUE TITLE
Unknown named module: reduxsauce

### ISSUE THREAD

**Issue by nikkollaz** [infinitered/ignite#642]
Hi, i am trying to run and test Ignite by first time, i can't find how to fix errors.

**I do this steps:**
sudo ignite new MyIgnite9
cd MyIgnite9
react-native run-android

Compiles everything ok but on runtime on emulator shows me this error...
Unknown named module: 'reduxsauce'

**I tried to do this actions:**
sudo yarn install
react-native link

**but do not build anymore shows me this error:**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-config:compileLint'.
> Unable to create lint output directory.

Some idea how to fix it?

**Comment by kevinvangelder** [comment]
You shouldn't need to run `sudo` for any of those commands, and in fact it is strongly discouraged to use `sudo` for anything related to `npm`, and probably by extension `yarn`. If you can't run these commands without `sudo` then you probably have a problem with your npm/yarn installation. I know it sucks, but I would try uninstalling npm/yarn and installing it without `sudo`.

**Comment by paulsumit1993** [comment]
I ran into the same issue on windows

**Comment by skellock** [comment]
@paulsumit1993 are you getting a permission issue too?

**Comment by paulsumit1993** [comment]
Its fixed now, just run `yarn` or `npm install` in your react native project root directory to install missing dependencies.

**Comment by skellock** [comment]
Yep.  The dependencies need to be installed for society to function.  Glad you're hooked up!

**Comment by nikkollaz** [comment]
it's working now, i make my script to install new apps using Ignite because when i tried always crash when it is installing dependencies, but with this i fix it.

sudo ignite new <project name>
cd <project name>
npm install reduxsauce --save
npm install
react-native link react-native -device-info
react-native run-ios

**Comment by kevinvangelder** [comment]
I'm glad you were able to get it working, but I would still strongly advise you fix your NPM environment so that you are no longer running commands via sudo. There are many unintended consequences this cause so it's likely that as long as you are using sudo you'll have issues using Ignite.

**Comment by nikkollaz** [comment]
yeah i think is the best kevin, i will fix my npm environment, one day i could repent not having listened you ;)
