### ISSUE TITLE
Prevent some commands from running unless in ignited app

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#643]
- [x] Issue does not already exist
- [x] ignite the cli

## Replication Steps

_Note this is with the current `next` branch installed and linked._

1. `ignite new Foo` and complete the generation of the project
2. `ignite new Foo` again
3. Note that it does not error

It should refuse to continue if the folder exists.

**Comment by skellock** [comment]
We had this, but wasnt working.  I took it out so we can continue. Will address tomorrow.

**Comment by jamonholmgren** [comment]
@skellock Low priority

**Comment by skellock** [comment]
So, let's bring it back like this:

#### Are we in an ignited project? 

Criteria:
* presence of a `./ignite/ignite.json` file
* presence of a `./node_modules/react-native/package.json` file.

(We expect people to be in their root project directory. Maybe in the future we can support running commands from a sub directory)


Triggered By Running:
* `generate`, `add`, `remove`, or `spork`

Action:
* prints an error and exits

Where to put this?
* The logic: `packages/ignite/src/lib/detectIgnite.js`
* For the check, my preferences is in each of the 4 command files as opposed to plugin registration.

Perhaps we need some sort of event lifecycle system in gluegun?  `onBeforeRun`, `onAfterRun`?  Etc... thoughts?  Overkill for this one task, but I can see us needing this for other things like logging.

**Comment by skellock** [comment]
One part of this is done.  You cannot run `new` with the target directory already existing.
