### ISSUE TITLE
`ignite new` fails with TypeError: system.spawn is not a function

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#644]
```
TypeError: system.spawn is not a function
    at Command.module.exports [as run] (/Users/jh/Code/ReactNative/ignite/packages/ignite/src/plugins/default/commands/new.js:79:16)
```

However, while filing this issue I was able to resolve my own issue.

1. Go into your `ignite/packages/ignite` folder
2. Run `npm install`

It'll bring in the latest `gluegun` and everything works.

Filing this anyway in case someone else runs into this.

**Comment by skellock** [comment]
This note was in my PR.  I think we might need to track these notes in a release.  Even if its just for us right now.  Sucks that you lost time to this.
