### ISSUE TITLE
Ignite generated redux files don't work (Wrong reducer name)

### ISSUE THREAD

**Issue by Blackclaws** [infinitered/ignite#647]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [x ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

Also, for the quickest assistance please run `ignite doctor` and paste in
everything (including the lines with 3 backticks).

```
Computer
  Platform: linux

Ignite
  Version: 1.13.0
  Path: /home/felix/.npglobal/bin/ignite

Node
  Version: v7.4.0
  Path: /usr/bin/node

NPM
  Version: 4.0.5
  Path: /usr/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 2.0.1

App
  React Native Version: 0.38.0
```

Right so this is a weird one. 

Using 
    ignite generate redux test

will generate the redux file named testRedux. However what it will not do in that file is capitalize the name of the types when mapping to reducers.

Example:

export const reducer = createReducer(INITIAL_STATE, {
  [Types.test_REQUEST]: request,
  [Types.test_SUCCESS]: success,
  [Types.test_FAILURE]: failure
})

should be

export const reducer = createReducer(INITIAL_STATE, {
  [Types.TEST_REQUEST]: request,
  [Types.TEST_SUCCESS]: success,
  [Types.TEST_FAILURE]: failure
})

this is especially weird as the template explicitly states to cap it all.

export const reducer = createReducer(INITIAL_STATE, {
  [Types.<%= name.split(/(?=[A-Z])/).join('_').toUpperCase() %>_REQUEST]: request,
  [Types.<%= name.split(/(?=[A-Z])/).join('_').toUpperCase() %>_SUCCESS]: success,
  [Types.<%= name.split(/(?=[A-Z])/).join('_').toUpperCase() %>_FAILURE]: failure
})

very weird bug.

However after checking the template delivered with generator-react-native-ignite does not seem to contain the toUpperCase statement.

Is that package not up to date?

**Comment by ruddell** [comment]
I think it's fixed but not released https://github.com/infinitered/ignite/issues/578

**Comment by GantMan** [comment]
so sorry, we need to release this.  I'll try to make time today.

**Comment by Blackclaws** [comment]
Ah  I see. Any update on the timeline for 2.0? Is there going to be a February release?

**Comment by GantMan** [comment]
we're working towards it!   :crossed_fingers:

**Comment by skellock** [comment]
My answer is HELL YES.

**Comment by GantMan** [comment]
this is why I love you Steve.  <3

LET'S MAKE THIS HAPPEN!

**Comment by skellock** [comment]
This is fixed and pending a release.

**Comment by skellock** [comment]
We missed this goal by 4 days.  Pretty close! 

The bug is now corrected in Ignite 2.
