### ISSUE TITLE
I'm being run in an Ignite directory.

### ISSUE THREAD

**Issue by akusany2** [infinitered/ignite#648]
### Sorry, I couldn't create a new app here, I'm being run in an Ignite directory.

- [x] ignite the cli

```
Computer
  Platform: darwin

Ignite
  Version: 1.13.0
  Path: /Users/ankitkr/.nvm/versions/node/v6.9.2/bin/ignite

Node
  Version: v6.9.2
  Path: /Users/ankitkr/.nvm/versions/node/v6.9.2/bin/node

NPM
  Version: 3.10.9
  Path: /Users/ankitkr/.nvm/versions/node/v6.9.2/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 2.0.1

App
  React Native Version: ¯\_(ツ)_/¯
```

Just installed ignite with guidelines but facing this error when init a new app.
`ignite new test`

test folder does not exists in the directory.

Am I missing something? 

[#349](https://github.com/infinitered/ignite/issues/349)

```
// https://github.com/infinitered/ignite/blob/master/ignite-cli/src/index.es

// Early exit if the project name already exists (#349)
const checkDir = (project) => {
  if (fs.existsSync(process.cwd() + '/' + project.toString())) {
    console.log(`Sorry, I couldn't create the directory for "${project}" - it already exists. :(`)
    Shell.exit(1)
  };

  if (fs.existsSync(process.cwd() + '/App')) {
    console.log('Sorry, I couldn\'t create a new app here, I\'m being run in an Ignite directory.')
    Shell.exit(1)
  }
}
```

Everything appears to be good - checking on the current directory where I've init'ed ignite with CLI.

**Comment by kevinvangelder** [comment]
Is there an `App` directory in that folder? That check is a little over-simplified.

**Comment by akusany2** [comment]
Damn! I missed it, there is an App directory in my folder, sorry about this 💯

**Comment by kevinvangelder** [comment]
No problem, in the future we'll have a more specific check that won't fail when a generic folder is present.
