### ISSUE TITLE
Ignite stuck at step Installing Ignite dependencies (~ 1 minute-ish)

### ISSUE THREAD

**Issue by kyawmoehaynes** [infinitered/ignite#656]
When I Ignite new App, the installation stuck at step "Installing Ignite dependencies (~ 1 minute-ish)"

<img width="643" alt="screen shot 2017-02-07 at 11 17 49 pm" src="https://cloud.githubusercontent.com/assets/7079899/22697521/9e8b9c4a-ed8c-11e6-8eb9-5a7994d07a23.png">

<img width="362" alt="screen shot 2017-02-07 at 11 17 40 pm" src="https://cloud.githubusercontent.com/assets/7079899/22697520/9e850fba-ed8c-11e6-9d2d-09bfc0890f30.png">

Ignite doctor 

<img width="343" alt="screen shot 2017-02-07 at 11 20 13 pm" src="https://cloud.githubusercontent.com/assets/7079899/22697519/9e85b604-ed8c-11e6-9a7e-4e80fefe490d.png">

**Comment by jamonholmgren** [comment]
@kyawmoehaynes You self-closed this, is it something you still need help with?

**Comment by anant-singh** [comment]
I need help with this
