### ISSUE TITLE
When Ignite will support React Native 0.41?

### ISSUE THREAD

**Issue by iamrutvik** [infinitered/ignite#658]
Is there any road map?

**Comment by GantMan** [comment]
We've got it in ignite 2.0, and we plan on having 2.0 released this month.  So we'll handle it that way.  

That sound right @jamonholmgren and @skellock ?

**Comment by skellock** [comment]
That would be my preference.

**Comment by jamonholmgren** [comment]
Correct. Thanks for the question @iamrutvik
