### ISSUE TITLE
Ignite Documentation/Tutorials

### ISSUE THREAD

**Issue by ali-hellani** [infinitered/ignite#659]
I have just started using ignite and have figured out some of it, but is there any documentation or tutorials on how to use the features it provides and to get more familiar with the structures ?!

**Comment by jamonholmgren** [comment]
@ali-hellani Welcome, friend!

First, start with the intro video: https://www.youtube.com/watch?v=5SVLs_NN_uY

Then join our Slack: http://infiniteredcommunity.herokuapp.com/

Ask questions in the #ignite channel in there and we're happy to help!
