### ISSUE TITLE
[CLI | Generator] - Test usage of CLI functionality

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#66]
- [x] Issue does not already exist
- Identify exactly what aspect you're issue is about
  - [ ] ignite base applicattion
  - [x] ignite the cli
  - [x] ignite generated code

As of right now we have some pretty decent functionality tests.  But we're not testing the commands to make sure they behave as we're hoping.  It would be nice to actually have `fireDrill` run some long-standing checks on a fresh machine to make sure we're not breaking anything as we evolve.  

Developer time is too precious to re-build an entire project + apply all generators upon each verification.

**Comment by GantMan** [comment]
Application generator is now tested by https://github.com/infinitered/ignite/blob/cf2b3cdbf23ee798c1987c79cd0fdf2f5bb8ba0c/testRelease.sh

We need to just build in tests for the other generators there.

**Comment by juddey** [comment]
Hello, made a start on this one, and have a couple of questions.
1. How do you suggest we deal with the listview selection (Where you get asked what type of listview would you like...)
2. The mapview generator wants to install react-native-maps and clobber  ` App/Components/MapCallout.js` => is this normal, and if so, how to deal with it?

Thanks :)

**Comment by GantMan** [comment]
I haven't started the generator testing just yet.  Some good resources would be the yeoman docs.
http://yeoman.io/authoring/testing.html

**Comment by juddey** [comment]
Oh - I've misread this ticket! I've substituted `testRelease` for `fireDrill` and busily been writing my function into `testRelease.sh` without a thought of yeoman.... 

Its nearly done, so I'll PR what I have done and if its useful then keep, otherwise just bin it.

**Comment by GantMan** [comment]
I like the idea of testrelease being more robust, anyhow.  I'm always up for fixes/better tests.  I'll happily take those updates!  I feel yeoman tests will be faster/better in the long run, but NOTHING is as good as the real thing.  So testrelease updates is awesome!

Would definitely help.

**Comment by juddey** [comment]
Picking this up again today in light of the changes discussed in #475 (and others). Be 😢  if we started shipping broken generators!

Summary:
- Made a start by  adding `ava` to the ignite generator dev dependencies, as well as the yeoman libs, and getting tests running with `npm test`.
- Created a component test => [gist](https://gist.github.com/juddey/8df2afb8db5a0c64a1b4d8fdf291ce80#file-component-test-js).

I really don't like the idea of all the repeated 'thenables' in the code so spent a bit of time fiddling around trying to get rid of them - but not much luck => Bright ideas appreciated!

Let me know if this is on the right track - Feedback welcome!

**Comment by juddey** [comment]
@GantMan Let me now your views on this in light of #447 and #488 :)

**Comment by GantMan** [comment]
ah, yes, sorry about #488 throwing a wrench in the gears.

I promise to make the process feel/look clean.  Just need to really do it all the way through.  You can hop in with me on #488 if you like.

**Comment by skellock** [comment]
We have integration tests now in v2.  They were working.  Then not working.  And dammit I will make them work again.  Having issues with npm.
