### ISSUE TITLE
Unknown error, "ava"

### ISSUE THREAD

**Issue by nonameolsson** [infinitered/ignite#666]
### Hiya! So you think it's broken or missing a feature eh?

Welllllll, it just might be.  Do me a favor and check the following.

- [X] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [X] ignite generated code

```
Computer
  Platform: win32

Ignite
  Version: 1.12.0
  Path: C:\USERS\ANDREAS\APPDATA\ROAMING\NPM\IGNITE.CMD

Node
  Version: v7.2.1
  Path: C:\PROGRAM FILES\NODEJS\NODE.EXE

NPM
  Version: 3.10.10
  Path: C:\PROGRAM FILES\NODEJS\NPM.CMD

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 2.0.1

App
  React Native Version: 0.38.0
```

Hi!
I'm having trouble to start my Ignite generated app.

This is the error message which I get.

![screenshot_1](https://cloud.githubusercontent.com/assets/1493018/22828919/1ecffb2a-efa0-11e6-9206-fedbfade0fdc.png)

**Comment by skellock** [comment]
Does windows have a `node_modules/.bin` folder?  Or do they call it something else?

**Comment by nonameolsson** [comment]
Yes it has. Here's a screenshot of it and its content.
![screenshot_2](https://cloud.githubusercontent.com/assets/1493018/22829364/86627a72-efa2-11e6-9e36-8f1808d850c9.png)

**Comment by nonameolsson** [comment]
I just installed Ignite on my Mac, and tried to start a new project
```
Computer
  Platform: darwin

Ignite
  Version: 1.13.0
  Path: /Users/nonameolsson/.nvm/versions/node/v6.6.0/bin/ignite

Node
  Version: v6.6.0
  Path: /Users/nonameolsson/.nvm/versions/node/v6.6.0/bin/node

NPM
  Version: 4.0.5
  Path: /Users/nonameolsson/.nvm/versions/node/v6.6.0/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 2.0.1

App
  React Native Version: 0.38.0
```

This was the result.
<img width="1433" alt="screen shot 2017-02-10 at 15 41 03" src="https://cloud.githubusercontent.com/assets/1493018/22830592/5e3e221c-efa7-11e6-967f-5c24f541d7c4.png">

**Comment by skellock** [comment]
Thats strange.  Was this after running `ignite new Thing`?

Can you try `cd android && ./gradlew clean && cd .. && react-native run-android` again.  Just make sure it's clean.

**Comment by skellock** [comment]
For the Windows issue can you turn of hot reloading and try again?  Does that work?

**Comment by skellock** [comment]
Feel free to re-open if you're still stuck.  Our windows support is still less than perfect.
