### ISSUE TITLE
Add activity indicator to `newclear`

### ISSUE THREAD

**Issue by kevinvangelder** [infinitered/ignite#67]
In a large project, the `newclear` command can appear to hang while it removes all your node modules. It would be great if we could show a spinner or some other activity indicator while that portion of the command is running (`npm i` has it's own, so we don't need to worry about that portion) so that users don't think the command has failed.

**Comment by GantMan** [comment]
https://github.com/helloIAmPau/node-spinner

**Comment by kevinvangelder** [comment]
If possible, it would be great to replicate the functionality in #121 here.

**Comment by GantMan** [comment]
What's the best way to indicate to people that we have `mobile-commander` for this, and shouldn't use the newclear script inside?   I'm wondering  for migration.

**Comment by kevinvangelder** [comment]
@GantMan The best way is to replace the newclear script with a message that says, "Deprecated in favor of mobile-commander, install it thusly: ..."

**Comment by skellock** [comment]
Is there anyway to depend on mobile commander without installing it as a global dependency?

**Comment by GantMan** [comment]
doing a local install, does it give you the CLI?   I don't think it does.

**Comment by skellock** [comment]
I don't mind having `mobile_commander` as a dev dependency if we're chasing the functionality, but I'm not a fan of installing individual commands globally.

I like `npm run newclear`.  Or even `npm run` to see the list.  

Some folks will already have shell aliases setup for some of these things.

My opinion of course.

**Comment by GantMan** [comment]
I'm more than happy to make it local, if that's doable.   Maybe we merge these into ignite commands?

`ignite newclear`?

**Comment by skellock** [comment]
oh hell yes

**Comment by skellock** [comment]
yarn significantly speeds up the re-install time.

**Comment by skellock** [comment]
Also tracking in #652.
