### ISSUE TITLE
Clean out Devscreens 

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#672]
As of right now, dev screens depend on app styles.  The schism needs to happen! ➗ 

1. Move styles over to dev screens
2. Make dev screens point to new styles
3. Delete unused styles from copied files
4. Delete unused styles from original themes folder

**Comment by kevinvangelder** [comment]
Technically we've only done 1 & 2.

**Comment by skellock** [comment]
Oops.  I did it again.

**Comment by skellock** [comment]
Are we ok to close this issue now?  I feel like we are.
