### ISSUE TITLE
Node 7 Requirement?

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#676]
### Problem

Will Node 7 be too much of a barrier?  I want to say no, but I'm not sure.  It's trivial to install `npm i -g n && n 7.5`.

Will people be wanting all the babel-provided JS features they're used to in RN?

### Ignite vs Gluegun

In gluegun, we don't necessarily run in a babel environment.  Use node 7 --harmony.  The end.  Bye!

However,

An `ignite-*` plugin lives in the `node_modules` of a *React Native app*.  

Which means it has a `.babelrc` (historically it didn't, but they changed their minds and now ship with one).

The default preset `babel-preset-react-native` comes with everything we need & more to run `ignite`.  We get `async/await`, we get rests, import/export, decorators, you name it.

We still are executing in a node environment, but with `babel-core` we can run in a "better" environment.

### Pros

* RN devs will feel more at home with the normal babel-enhanced syntax.
* We still don't have to add any new dependencies to plugins.
* We won't have to require Node 7 with `--harmony`.  I mean it's the current version, and soon it'll be core in Node 8 (2 months away?).
* We could split `ignite` into 2 parts.  A Node 6 CLI (launcher) and the `ignite-lib` which would be installed into a RN App.  This is exactly how `react-native-cli` works.  Ignite updates stay with the project which is a more stable experience.

### Cons

* Will significantly slow down startup time.
* Will add a lot more overhead to `ignite`'s dependencies (basically babel).
* It'll be a lot more work to build.
* This wouldn't be ready for our 2.0 launch.  I'm just spitballing here. (2.1 or 3.0).

### Summary

Node 7 is the easy way. 

I went that route because `babel` environments are hard to get right.  Especially when plugins are in different locations.  I'm just realizing now, for *react native only* apps, different locations isn't a constraint.  I think I could make this work.

But I'd hate to build it if people are totally fine with installing Node 7.

**Comment by GantMan** [comment]
my thought on this, let's do node 7 and see what happens

**Comment by RWOverdijk** [comment]
Is this related to the error I'm getting?

> Error: Cannot find module 'internal/fs'

**Comment by skellock** [comment]
Are you on the `next` branch?

**Comment by RWOverdijk** [comment]
@skellock I am not, no. I just installed globally so the latest release. Should I use next for node 7?

**Comment by skellock** [comment]
We are using Node 7 for Ignite 2. It isn't ready yet, so I'd say hang tight on Ignite 1 for now.

**Comment by jamonholmgren** [comment]
Since 7.6 now doesn't require the `--harmony` flag, we're good, right?

**Comment by skellock** [comment]
Yup!
