### ISSUE TITLE
Add more fields to generated plugins

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#680]
Generated plugins should also include `description`, `license`, `devDependencies` in their generated `package.json`.

**Comment by skellock** [comment]
Heads up; `devDependencies` are optional. I could be convinced of peer dependencies, but we decided not to for now.

**Comment by jamonholmgren** [comment]
We should also add `author`, `url`, and also add a sample README.md file.

**Comment by GantMan** [comment]
also the generated file has blah.js instead of blah.js.ejs for examples

**Comment by jamonholmgren** [comment]
@robinheinze Could you fix these things in Ignite?

**Comment by robinheinze** [comment]
Working on this now.
