### ISSUE TITLE
Generate appears to do nothing

### ISSUE THREAD

**Issue by codeithuman** [infinitered/ignite#685]
When using Ignite 2 Alpha, I can run `ignite generate MyIgniteProject`. When running this command, the Ignite "header" displays in the terminal, but no new project is created or error displayed. 

![screen shot 2017-02-15 at 11 30 59 am](https://cloud.githubusercontent.com/assets/3494509/22991935/e41859b0-f372-11e6-93f6-c21d7a648e07.png)

I would recommend displaying a message asking if the developer meant to type `ignite new {ProjectName}`.

**Comment by kevinvangelder** [comment]
Generate is a namespace, so it will actually probably list the available sub-commands.

**Comment by skellock** [comment]
Let's put a message in that says, "No generators installed.  Check out https://github.... for more info"?  Or something?

**Comment by codeithuman** [comment]
Oh I see. Maybe `ignite generate` can detect if there is an ignite project is the current directory and display something similar to git? 

```
Not a git repository (or any of the parent directories)
```

Or something like Steve mentioned about not having generators installed.

**Comment by kevinvangelder** [comment]
Yeah, those are good suggestions. We had an "is an ignite project" check built-in, but it got disabled.

**Comment by skellock** [comment]
Ya it was broken, I couldn't run anything so i had to turn it off.

So let's detect if there's no generators and display an error message.  

We could put it [just before this line](https://github.com/infinitered/ignite/blob/next/packages/ignite/src/commands/generate.js#L107) by checking `length(userRegistry) === 0` where `import { length } from 'ramda'`... or however you want to do it.

**Comment by skellock** [comment]
Thanks for having these discussions guys.  This stuff matters.

Sorry that I clobbered your code @kevinvangelder.  Added more details to #643 about checking if we're in an ignite project if you wanna bring 'er back?
