### ISSUE TITLE
Setup lerna for publish

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#686]
We'll be publishing with lerna, so let's make sure that's firing on all cylinders.

* Switch to independent version numbers (which means we may not be able to use github releases).
* Tag `react-native-ignite` on npm as @alpha so we can practice a bit.  The other repos are new, so they don't need a tag just yet.

**Comment by skellock** [comment]
Deploy from Travis.  I want this to be a thing.  But I don't know if it's a thing.  Can someone tell me if it's a thing?

**Comment by jamonholmgren** [comment]
@skellock It's a thing: https://docs.travis-ci.com/user/deployment/script/

**Comment by skellock** [comment]
We need to have a discussion about the version numbers.

I'd like to switch to shared version numbers.  I originally thought I wanted independent mode, but that will screw up github releases.  Github only allows us to have 1 name.  So if we bump 3 components in 1 release, and they have 3 different version numbers, we're cooked.

So let's say we start all components in here at `2.0.0`.

When we bump a few components, we would release `2.0.1`.  But only the ones that changed.  The remainder stay at `2.0.0`.

This is the shared version number approach that lerna gives us.  Think of it as a high-water mark.

But here's the wrinkle:  semver.

Semver wants us to bump the major on breaking changes.  That means, the moment even one of our smaller components introduces a breaking change, we bump to `3.0.0`.  It might be weird to call `Ignite 2` `3.0.0`, but I'm cool with it I guess.

The other way around this is to *not* use semver.  And this is the approach I'm voting for.

Instead of semver `major.minor.patch`...

We do:  `marketing.breaking.nonbreaking`.

This isn't as horrible as you might think.  We switch from carrots to tildes when including anything ignite.

Since we control the call to `npm install` via our `ignite add`, we could easily swap it out.

Let's chat about this.

We can make them both work, we just need to decide before launching.

/cc: @jamonholmgren @GantMan @kevinvangelder

**Comment by jamonholmgren** [comment]
@skellock I'm on board with `marketing.breaking.nonbreaking`. Question, though: since Ignite 2+ is a CLI with no runtime, what is considered a "breaking" change? API/behavior changes when you run `ignite x` and `ignite x` now means something different? Perhaps machine-gun incrementing the major version isn't a big deal since there's no runtime API.

**Comment by skellock** [comment]
The advantage of going hard on the major version is, we don't have to explain anything to anyone.  It's semver.  The end.  If you're ok with 2.x.x turning into 3.x.x and then 4.x.x, let's just do it like that.

The breaking change I'm worried about is the interface between a plugin and the cli.  Let's say we introduce a new feature inside an extension. And some plugins start using it.  How do we make sure end users don't have a stale cli that doesn't support it?

Usually these types of things are solved by npm dependencies.

The way `react-native-cli` and `create-react-app` solve this problem is by doing something like #739. (we'd still have ignite devDeps -- still no runtime deps).

**Comment by jamonholmgren** [comment]
That makes sense, the plugin interface is critical for sure. Another idea is to enforce a version within a plugin with something like:

```
context.ignite.checkVersion("^ 2.0.0")
```

However, I agree that splitting the CLI and core apart makes more sense, and rely on NPM to keep things in sync.

**Comment by skellock** [comment]
Just an update.  We're switching back to shared-version mode.

So we've kicked out the plugins from this repo.

I'd like to kick out the app templates next.  They're plugins as well.  I can see us wanting to bump majors on `ignite-infinite-red-app-template` very soon (next few months).

/cc @jamonholmgren and @GantMan

**Comment by jamonholmgren** [comment]
This is on the docket to discuss tomorrow morning.

**Comment by skellock** [comment]
Fixed by #798 .  Lerna will work out of the box now.
