### ISSUE TITLE
Prevent addComponentExample from magically appending .ejs

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#690]
This is the wrong level of magic:

~https://github.com/infinitered/ignite/blob/next/packages/ignite/src/extensions/ignite.js#L201~
https://github.com/infinitered/ignite/blob/master/packages/ignite-cli/src/extensions/ignite/addPluginComponentExample.js#L23

Not all component examples are templates, and there's no harm in running all files through the generator, but let's not have the user type `addComponentExample('foo.js')` when it's `foo.js.ejs` on the file system.

Let's change our current usage to pass in `foo.js.ejs`.  Let's also print a `warning` that the template was not found, but not bomb the install of the plugin.

Found by @robinheinze

**Comment by GantMan** [comment]
agreed
