### ISSUE TITLE
[2.0] Just `cd` into the damn folder

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#696]
![image](https://cloud.githubusercontent.com/assets/997157/23105300/ccad7ed0-f6a2-11e6-87e8-49ac3bec5cff.png)
3 commands spit out, all 3 have the same first step.   Let's just cd into the folder when we're done.

**Comment by skellock** [comment]
Problem with this is, you have to wrap our cli in a shell script.  This will make it have issues with windows out of the box.

I can't think of good way to do this.  Would love to hear some ideas.

**Comment by GantMan** [comment]
o yeah... we can't `cd` because we're a separate process from shell.

No way to cat/pipe a cd in there eh?

**Comment by skellock** [comment]
Nope.  Not without sorcery™.

**Comment by designorant** [comment]
I think this is perfectly fine. `react-native init` requires `cd` afterwards too.

 I wouldn't like to see anything jump folders for me anyway.
