### ISSUE TITLE
ignite add windows

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#697]
There are 3 or so steps to add windows to a project.  Wrap them up into `ignite add windows` plugin.

**Comment by skellock** [comment]
Should this be a plugin?  Or do we want this to be an app template?  or a command line switch we send to unholy?  

I ask because I really don't know what's involved.

**Comment by GantMan** [comment]
It's like "add this platform" which I would like as a command.  That's kinda how it is now.  You get iOS and Android for free, and then you say "gimme X too!"

**Comment by jamonholmgren** [comment]
So there will be an `ignite-windows` plugin, officially supported?

**Comment by skellock** [comment]
Can you have a codebase with both mobile and windows?

**Comment by GantMan** [comment]
yes.   Just like iOS/Android it will only break on native usage.

**Comment by kevinvangelder** [comment]
@GantMan speaking of this, we should probably finalize the upstream RNW CLI for picking UWP or WPF.

**Comment by jamonholmgren** [comment]
Where are you at on this @kevinvangelder ?

**Comment by jamonholmgren** [comment]
We haven't had much demand for this, so I'm going to close it, because we don't intend to build it.
