### ISSUE TITLE
Plugin Generator Example

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#699]
2 small nits for you @jamonholmgren 

First off, I'd like to change the question to:
"Will your plugin have an example component?"

Because "Would you like to generate an example component" sounds like I might have a generator that makes components, which is not clear.

Second, I said "NO"
![image](https://cloud.githubusercontent.com/assets/997157/23108596/4627c9fa-f6d5-11e6-8134-e1da52fdeb43.png)

But I still had an example `EXAMPLE_FILE` reference in my resulting plugin `index.js`.

**Comment by jamonholmgren** [comment]
👍 ty @GantMan , will look next week.
