### ISSUE TITLE
Any recommend about library for redux reusable complex components.

### ISSUE THREAD

**Issue by giangqaz** [infinitered/ignite#700]
Now, I face with some complex listview component that reusable. 
does any recommend for that?

**Comment by skellock** [comment]
ListView's data is given to it externally via a datasource.  Which makes it very reusable.

Here's some details on that:  https://facebook.github.io/react-native/docs/listview.html

For the data part, it sound like you might be interested in a few tutorials to get started:

https://github.com/markerikson/react-redux-links/blob/master/basic-concepts.md
