### ISSUE TITLE
[2.0] - Incorrect error message

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#701]
When you run add and you'r plugin is valid, but the current project you're in is not, the error message is wrong.
![image](https://cloud.githubusercontent.com/assets/997157/23130208/301d45e2-f74b-11e6-89dd-dc997fe04216.png)

Developing a 3rd party plugin I had 3 terminals open.  I ran this in the wrong one and for 5 minutes I was absolutely confused due to the error message.

**Comment by skellock** [comment]
https://github.com/infinitered/ignite/pull/681 makes this optional.

**Comment by skellock** [comment]
Drop an `ignite.toml` with my apologies for a short-term fix.

**Comment by GantMan** [comment]
Nope, the error itself is misleading.  So much so, it confused you too :)

**Comment by GantMan** [comment]
The plugin from add was valid.   The current directory I was in was not.

**Comment by skellock** [comment]
HAHA!  Owned.  

Ugh.  Ugly.  Thx dude.

**Comment by skellock** [comment]
Tracking in #643.
