### ISSUE TITLE
Remove doesn't work like add can with paths

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#702]
It should check if it's a path before just checking package.json for the name.

![image](https://cloud.githubusercontent.com/assets/997157/23131561/13b3a40a-f750-11e6-90b2-3bc31d42cbee.png)

**Comment by skellock** [comment]
When you remove a plugin, you should type `ignite remove redux-logger`.  You shouldn't have to type the full path from where it came from.

**Comment by jamonholmgren** [comment]
I'd recommend showing an error:

```
$ ignite remove /path/to/ignite-redux-logger
Verifying Plugin
💩 When removing a package, you shouldn't use a path. Try `ignite remove ignite-redux-logger` instead.
FAIL
```
