### ISSUE TITLE
ignite cli does not seems to work

### ISSUE THREAD

**Issue by phaneendra** [infinitered/ignite#71]
ignite cli does not seems to work

Get the below error on 
$ node -v
v4.2.2
$ npm -v
3.5.3
$npm -g list --depth=0
├── babel-eslint@4.1.6
├── bower@1.7.7
├── generator-react-native-ignite@0.0.4
├── generator-webapp@2.0.0
├── gulp@3.9.0
├── gulp-cli@1.2.1
├── npm@3.5.3
├── react-native-cli@0.2.0
├── react-native-ignite@0.1.10
└── yo@1.7.0

$ ignite new react-native-aics
🔥 Setting react-native-aics on FIRE! 🔥
generate app -> react-native-aics ☕️  This will take a while ☕️
events.js:141
      throw er; // Unhandled 'error' event
      ^

ReferenceError: colors is not defined

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base applicattion
  - [x] ignite the cli
  - [ ] ignite generated code

**Comment by GantMan** [comment]
ah. Thanks so much!  Our tests are in-project, so when mistakes like this happen they are hard to catch.

We're working on tests that will catch these issues in the future.

please update:
`npm install -g generator-react-native-ignite`
and 
`npm install -g react-native-ignite`

**Comment by GantMan** [comment]
I just tested this, so I'm closing this issue.  Let me know if it still doesn't work for you and we can revisit this ticket.

**Comment by phaneendra** [comment]
yes the reference error color issue is gone - but it seems there is another error now when we run 
`ignite new app` 
`Error: Cannot find module '../validation' `
Guess this is already raised as an issue
#75

**Comment by GantMan** [comment]
@phaneendra 
Update to latest generator-react-native-ignite version 0.1.1 for the fix.

Sorry about that, npm can be sneaky.  I wasn't exposing that file correctly.
