### ISSUE TITLE
Add current directory ignite doctor.

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#710]
When folks run `ignite doctor` let's display the current directory too.  It'll help with the conversations for debugging.

[Right around here](https://github.com/infinitered/ignite/blob/master/packages/ignite-cli/src/commands/doctor.js#L34) should do the trick.

**Comment by jamonholmgren** [comment]
@robinheinze Can you take this on?

**Comment by robinheinze** [comment]
Yup, will do
