### ISSUE TITLE
SYSTEM_ALERT_WINDOW permission on Marshmallow and above

### ISSUE THREAD

**Issue by iamrutvik** [infinitered/ignite#729]
App is getting crashed before showing splash screen in Marshmallow and above throwing an exception that permission is denied for this window type.

The reason is, due to the change in Android permission model, user have to allow this permission explicitly. 

I found this [solution on stackoverflow](http://stackoverflow.com/questions/32061934/permission-from-manifest-doesnt-work-in-android-6/32065680#32065680) but dont know how to implement it.

Here is my MainActivity.java

package com.nytevibe;
import com.facebook.react.ReactActivity;
import com.cboy.rn.splashscreen.SplashScreen;
import com.burnweb.rnpermissions.RNPermissionsPackage;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;

public class MainActivity extends ReactActivity {

    public static int OVERLAY_PERMISSION_REQ_CODE = 1234;
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {

        SplashScreen.show(this);  // here

        return "NyteVibe";
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (!Settings.canDrawOverlays(this)) {
            Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,
                    Uri.parse("package:" + getPackageName()));
            startActivityForResult(intent, OVERLAY_PERMISSION_REQ_CODE);
        }
    }

    @Override
      public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
          RNPermissionsPackage.onRequestPermissionsResult(requestCode, permissions, grantResults); // very important event callback
          super.onRequestPermissionsResult(requestCode, permissions, grantResults);
      }
}

You guys have any solutions in Ignite? It's seems it's using that permission before launching the app.

**Comment by skellock** [comment]
Ya, that's the new permission system in Android 6 (api 23). React Native's red/yellow box uses an overlay.

You can add that code above which will do the trick.

Or you can fallback your build target to 22 like Facebook does now.

In `android/app/build.gradle` change the section `android -> defaultConfig -> targetSdkVersion` from 23 to 22.
