### ISSUE TITLE
This morning on my laptop - Bug

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#736]
![image](https://cloud.githubusercontent.com/assets/997157/23332172/f70486a0-fb3a-11e6-96cb-71ec99a2075f.png)

I have a fresh bootstrap

**Comment by GantMan** [comment]
I guess I'm missing something.  Shouldn't bootstrap register these components locally?   It has in the past, right?

**Comment by GantMan** [comment]
bonus, I just did an npm link manually and it didn't work.  Guess something is super wonky on my laptop?

**Comment by skellock** [comment]
>  It has in the past, right?

`npm run bootstrap` runs `lerna bootstrap`, which ensures each `package/*` packages has their modules installed.  The packages that depend on each other (in our repo, that's a grand total of 0) will then be symlinked.

How ignite finds its plugins though is by "directory".

Check out [this line here](https://github.com/infinitered/ignite/blob/master/packages/ignite-cli/src/commands/new.js#L82).   

What we're doing during our "pre-alpha" stage is looking for *all* our ignite plugins in the `ignite` repo on your hard drive.  We're not going to do this much longer though.  Soon, these will be hosted on NPM.

> bonus, I just did an npm link manually and it didn't work. Guess something is super wonky on my laptop?

Can you share an error so I can help?

My guess is that you already have/had `ignite` linked.  First remove with `npm -g rm ignite-cli` or `npm -g rm ignite` (depending on what you've already installed on your laptop)

**Comment by GantMan** [comment]
So my only error I get is the one you see above.  Where it can't find `ignite-unholy-app-template`

When I npm link it is successful :(  So no errors.  Just no way to ignite a new project right now bc the above error.

If this is cache I can't bust it.

**Comment by GantMan** [comment]
Any other reason I might be hitting this line?   
https://github.com/infinitered/ignite/blob/c304fe21aeadcb5a7ad2d6d3efc066b7a5da3612/packages/ignite-cli/src/commands/add.js#L125

**Comment by skellock** [comment]
Ya that comes from running [this function](https://github.com/infinitered/ignite/blob/c304fe21aeadcb5a7ad2d6d3efc066b7a5da3612/packages/ignite-cli/src/commands/add.js#L36) and something goes wrong.

We don't emit the exception (we should in --debug mode), but could log you it and see what's up?

If you ran `npm link` and it didn't give you an error, that means it worked.

I wonder if what you're experiencing here is an older `yarn` or something?  The answer is in that exception.

**Comment by GantMan** [comment]
![image](https://cloud.githubusercontent.com/assets/997157/23335278/af51c5b0-fb77-11e6-8d45-672426f8acea.png)

```
 $ ignite n TestTaco3 --debug                                                               [13:42:56]
22:29:13 [ignite] making directory TestTaco3
22:29:13 [ignite] switched directory to /Users/gantman/Documents/Projects/playground/TestTaco3
🔥 igniting app TestTaco3
22:29:13 [ignite] running app template: ignite add /Users/gantman/Documents/Projects/rn/ignite/packages/ignite-unholy-app-template TestTaco3 --is-app-template --ignite-dev-package-prefix /Users/gantman/Documents/Projects/rn/ignite/packages/ignite- --debug
22:29:13 [ignite] running add command
22:29:13 [ignite] installing /Users/gantman/Documents/Projects/playground/TestTaco3/node_modules/ignite-unholy-app-template from source directory
22:29:13 [ignite] checking for yarn cache
✖ ignite-unholy-app-template does not appear to be an NPM module. Does it exist and have a valid package.json?
22:29:14 [ignite] error running app template
22:29:14 [ignite] undefined
22:29:14 [ignite] cleaning temporary files
22:29:14 [ignite] finished running new
```

looks like whatever version of ignite that this computer remembers does not have the correct submodules being copied in?

**Comment by skellock** [comment]
Maybe it's dying on the [yarn cache dir](https://github.com/infinitered/ignite/blob/master/packages/ignite-cli/src/commands/add.js#L47)?

What happens when you type `yarn cache dir` on your command line?  What version of yarn are you running?

**Comment by GantMan** [comment]
```
 $ yarn cache dir                                                                                                         [16:29:56]
yarn cache v0.18.1
/Users/gantman/Library/Caches/Yarn
✨  Done in 0.03s.
```

**Comment by skellock** [comment]
```sh
❯ yarn cache dir
/Users/steve/Library/Caches/Yarn
```

I wonder if it's dying on the fact yours is displaying a header?

Can you upgrade to the latest version of yarn?  `npm i -g yarn`

**Comment by GantMan** [comment]
@skellock - you were right.   It was the version of yarn.  We'll have to make sure we're using 20+
