### ISSUE TITLE
Debugging won't work

### ISSUE THREAD

**Issue by Xurma2** [infinitered/ignite#738]
> [intellij] [Warning] Couldn't import script at <http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false>. Debugging won't work: Try reloading the JS from inside the app, or Reconnect the debugger: 
Cannot GET /json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9Vc2Vycy9WaWN0b3IvaWduaXRlL015QXBwbGljYXRpb24vbm9kZV9tb2R1bGVzL3JlYWN0LW5hdGl2ZS9wYWNrYWdlci9yZWFjdC1wYWNrYWdlci9zcmMvUmVzb2x2ZXIvcG9seWZpbGxzL3ByZWx1ZGVfZGV2LmpzIl0sIm5hbWVzIjpbImdsb2JhbCIsIl9fREVWX18iLCJfX0JVTkRMRV9TVEFSVF9USU1FX18iLCJEYXRlIiwibm93Il0sIm1hcHBpbmdzIjoiO0FBQ0FBLE9BQU9DLE9BQVAsQ0FBaUIsSUFBakI7O0FBRUFELE9BQU9FLHFCQUFQLENBQStCQyxLQUFLQyxHQUFMLEVBQS9CIiwiZmlsZSI6InByZWx1ZGVfZGV2LmpzIiwic291cmNlc0NvbnRlbnQiOlsiLyogZXNsaW50IHN0cmljdDowICovXG5nbG9iYWwuX19ERVZfXyA9IHRydWU7XG5cbmdsb2JhbC5fX0JVTkRMRV9TVEFSVF9USU1FX18gPSBEYXRlLm5vdygpO1xuIl19

- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
 I dont know about this

```
Computer
  Platform: darwin

Ignite
  Version: 1.13.0
  Path: /Users/Victor/.nvm/versions/node/v6.9.1/bin/ignite

Node
  Version: v6.9.1
  Path: /Users/Victor/.nvm/versions/node/v6.9.1/bin/node

NPM
  Version: 3.10.8
  Path: /Users/Victor/.nvm/versions/node/v6.9.1/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 2.0.1

App
  React Native Version: 0.38.0
```

**Comment by skellock** [comment]
I've never used intellij before. I'm afraid I won't be of any help.

**Comment by Xurma2** [comment]
@skellock 
As far as I find an error occurred in other IDE
The most common cause is a bug in the code in the assembly
Perhaps there are some logs?

**Comment by Xurma2** [comment]
http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false
Realy I can not see this bundle

**Comment by skellock** [comment]
Best bet would be to run it from the command line.  Does anything come up there?

**Comment by Xurma2** [comment]
Project start and work. But it is not working in debugging mode.
How can I start debugging from the command line?

**Comment by skellock** [comment]
If you're talking about chrome debugging, that's something you turn on when the app is running.  As far as intellij debugging, i really don't know.

So the app builds and runs fine?  You can see your app and it has the latest changes?

**Comment by skellock** [comment]
Here's how to debug. From the react native docs.  https://facebook.github.io/react-native/docs/debugging.html

**Comment by jamonholmgren** [comment]
@Xurma2 The IR Community Slack is probably a better place to get help on this. 

http://community.infinite.red

Jump in the #ignite channel there and someone might be able to help you. :)
