### ISSUE TITLE
Make ignite-core a dev dependency of the project.

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#739]
We should really consider sooner rather than later to split the CLI and core functionality apart.

Currently all ignite plugins are a dependency of the end-user's project, but ignite isn't.  Delivering updates in plugins might be incompatible with core.

This is solved by using npm dependencies.  (Specifically devDependencies in our case).

We'd have to bust apart the cli into two parts and make the sure the core gets placed inside the user's project.

This would make upgrades much easier.  =)

**Comment by jamonholmgren** [comment]
I agree, this makes a lot of sense. I'm not sure I'd be the best one to tackle this Steve but I'm happy to help.
