### ISSUE TITLE
Rename "Unholy" template to "Infinite Red"

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#745]
Up until now, the "Unholy" template has been sort of a kitchen sink approach, where we put sample code of the decisions we've made so far.

In reality, "Unholy" is the stack that Infinite Red currently thinks is the best way to build React Native projects. Given that we have a lot of experience spinning up greenfield apps, our decisions are pretty informed, but they are of course opinions.

I'd like to rename "Unholy" to "Infinite Red" to make it more clear what this set of opinions represents. We build apps a certain way at Infinite Red and are proud of the work we've done, but there are a lot of very viable alternatives out there. If you want to sort of go down the "Blessed" IR route, then that's why the "Infinite Red" template will exist. Ignite 2 lets you use that or any other custom or preconfigured set of decisions.

cc @GantMan @skellock @robinheinze @derekgreenberg

**Comment by skellock** [comment]
Yep.  

I'd like `ignite-basic-generators` to be named `ignite-infinite-red-generators` (or whatever we end up calling `ignite-infinite-red-app`).

**Comment by GantMan** [comment]
agreed

**Comment by jamonholmgren** [comment]
I'd like to point out the irony of me wanting to call the "unholy" template the "IR blessed" template now.
