### ISSUE TITLE
Beyond Ignite 2.0

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#754]
Now that we're into the final week for Ignite 2.0 (beta), I'd like to turn a little of the focus on Ignite 2.1. The most important thing in my opinion has to be getting the app templates fully integrated with React Native's templating system _and_ discussing and refining the new `infinite-red-app-template` (formerly known as "Unholy"). Emphasis on the latter.

The decisions made in `infinite-red-app-template`, or the IR-AT for short [I'll just go ahead and coin that now], are probably 6-9 months old at least. We've made a few new discoveries along the way and there are some new things that have come out, including the new react-navigation. Time to align our visions for IR-AT.

In this issue, I'd like to discuss priorities for 2.1 and beyond. @GantMan, @skellock, @kevinvangelder,  @robinheinze and I will be having a short meeting tomorrow AM and will put some notes in here, and we can discuss async going forward from there.

**Comment by GantMan** [comment]
review @jamonholmgren  and @skellock and @kevinvangelder 

### Proposed Roadmap of 2.0

**Ignite 2.0:** 
* React Native Maps (generator/plugin)
* `ignite.addAndroidPermission` function (needed for maps)
* significant testing end to end
* some framework of permutation testing
* Video
* Testing
* Blog post (I have this half written)
* website copy

**Ignite 2.1:**
* Early detection testing against FB master (Travis daily CI)
* Promo video
* Reactotron plugin
* Redux Persist plugin
* Choose AVA or JEST plugins
* apisauce plugin
* update listview generator to have experimental option

**Ignite 2.2:**
* play nicely with RN templates
* Themes OR Component Styles options
* Enforce standard JS with githooks plugin
* RNRF or React Navigation plugins
* Drawer or No generator?

**Ignite 2.3:**
* Choose Sagas or Epics plugins

**Ignite 2.4**
* Redux or MobX

If these are agreed upon.  They should become tickets with proper tags and set to a milestone.  That way we use Github to manage release items.

**Comment by skellock** [comment]
Thanks for the giant list!

I think we should only plan for 2 steps ahead.

We all are pretty clear about what the next goal is.  And usually that means we can put things off to the goal after that.... but more than 2 out gets a bit fuzzy.

I think the tests are in a good spot.  @jamonholmgren and @robinheinze are running a bit more with that angle.

Marketing stuff is all you @GantMan.  I spun up a few tasks, but you're already on top of that.

Navigation, I feel is a discussion first.  We all want `react-navigation`, but I don't think anyone is going to stamp it with "fit for client consumption" today.  That team is firing correct though.  Maybe next week it'll be good enough?  Hell, I haven't used it in a 2 weeks.  Maybe it is good now?

Feel free to add more tasks:

* Mark 'em as `type: discussion` & `without` a milestone if you want to get the ball rolling.  
* Mark 'em with the `Future` milestone if you feel like we need this.
* Mark 'em with `2.1` if you feel like need this now.

Thanks @jamonholmgren for rallying us.
