### ISSUE TITLE
how do you install ignite 2?

### ISSUE THREAD

**Issue by rheilgm** [infinitered/ignite#755]
i uninstalled the old ignite and run `npm install ignite-cli -g` but ignite is not recognized now

**Comment by dinghua** [comment]
+1

**Comment by tk1cntt** [comment]
+1

**Comment by skellock** [comment]
I'd say hang tight till this week.  Beta 1 incoming.

**Comment by GantMan** [comment]
We're finishing up the docs and what needs to be in 2.0 - so soon!!!
