### ISSUE TITLE
Getting ":CFBundleIdentifier", Does Not Exist error while trying to run in iOS.

### ISSUE THREAD

**Issue by hrishikeshsoman** [infinitered/ignite#756]
Hi, 

 I have successfully created a new project using the ignite CLI. But when I am trying to run the project using the command `react-native run-ios` I am getting the following error even if my build returns a success message.

> ** BUILD SUCCEEDED **

> 
> Installing build/Build/Products/Debug-iphonesimulator/PictureBookIgnite.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/PictureBookIgnite.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist

Please find the version details  here: 

```
Computer
  Platform: darwin

Ignite
  Version: 1.13.0
  Path: /usr/local/bin/ignite

Node
  Version: v6.9.1
  Path: /usr/local/bin/node

NPM
  Version: 3.10.8
  Path: /usr/local/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 2.0.1

App
  React Native Version: 0.38.0
```

Any suggestions will be appreciated.

**Comment by junbinku** [comment]
have your try re-running the stimulator?

**Comment by jamonholmgren** [comment]
Also, feel free to join us in our community Slack [community.infinite.red](http://community.infinite.red) to chat with other friendly React Native engineers!

**Comment by nelsieborja** [comment]
Hi,

Also getting same error, below is the detail. Android works fine except for iOS

`An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

**Comment by nelsieborja** [comment]
Hi, came across with the same issue a while ago and after digging some solutions, upgrading Xcode with the latest version did the trick for me. Bec after finding out there's an incompatibility in the code so I thought Xcode might need to be upgraded for it to support the new code - a change which made by react developers recently. Sharing it and hope it helps.

**Comment by EmmanuelGuther** [comment]
I have answered a solution, that in my case fix this problem.

https://stackoverflow.com/a/44131754/3224192

**Comment by sw-yx** [comment]
Hi guys, running into this same issue too. Xcode 9, macos 10.12.6, node 9.4, npm 5.3, react-native-cli 2.0.1. these are the things i have tried:

- `react-native upgrade` (using the new `react-native-git-upgrade`)
- killing whatever is using port 8081 with `lsof -n -i4TCP:8081`
- manually running `npm start` and then `react-native run-ios`

CFBundleIdentifier is in `ios/PizzaApp/info.plist`

what else could be the cause of this?

**Comment by jamonholmgren** [comment]
Hey @sw-yx , did you try @EmmanuelGuther 's suggestions too?

**Comment by sw-yx** [comment]
hey @jamonholmgren thanks for the reply. i looked at it but im not using cocoapods (i think) so i couldnt use his suggestion at all.

after doing some research it seems that CFBundleIdentifier errors are very generic, so all of us reporting issues here could have all sorts of different causes and it will be very hard to tie it down. Ultimately this makes me just abandon using ignite and just going to CRNA for now until the developer experience is more stable..

**Comment by jamonholmgren** [comment]
@sw-yx Yeah, I understand the frustration! Sometimes what I do in these situations is comment out a bunch of code, get the app compiling again, and then slowly re-enable sections until I find the culprit.

CRNA is pretty good so you'll be in good hands there too (we're researching building Ignite on top of it, in fact). And you always have Ignite source to refer to if you need ideas on how to do things. :)
