### ISSUE TITLE
Yarn version check (0.20+?)

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#758]
![image](https://cloud.githubusercontent.com/assets/997157/23368428/6f825352-fcd3-11e6-9829-f3aa7c667d60.png)

### Upgrade
![image](https://cloud.githubusercontent.com/assets/997157/23368466/8e5cd66c-fcd3-11e6-999a-8b8fa3cc9b59.png)

**Comment by skellock** [comment]
i think i saw somewhere (create-react-app source code?) where they redirect stderr to /dev/null.. i wonder if thats where the `npm cache dir` version number line comes from?  I dunno... the easier way is to just say `yarn@>=0.20` or whatever.
