### ISSUE TITLE
Plugin Author Testing Overview

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#774]
It'll be a good idea to provide some techniques (possibly some tools????) to help plugin authors test their plugins.

It'd be super cool if we could expose our testing tools via a package they could use.

Having a good solid document would also be A+.

**Comment by jamonholmgren** [comment]
I'm game to help with this.

**Comment by skellock** [comment]
I think we're in a really good spot with this now @jamonholmgren ?  Feel like clicking the close button? ---------------------------------------
                                                                              | 
                                                                              V

**Comment by skellock** [comment]
fail.

**Comment by jamonholmgren** [comment]
I tend to go through all my Github notifications like once a week. heh

**Comment by jamonholmgren** [comment]
Example of how to test boilerplates here: https://github.com/infinitered/ignite-ir-boilerplate-bowser/blob/master/test/generators-integration.test.js
