### ISSUE TITLE
Website Copy Wanted

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#776]
We need some material to help round out the new web site.

@mlaco - Let us know what we can do to help.  

If you want to post some screenshots with big angry arrows pointing at blocks say, "INSERT 3 NEW FEATURES HERE", that would really help.

**Comment by mlaco** [comment]
Currently adding some copy on staging

**Comment by mlaco** [comment]
Here's that screenshot with big angry arrows. I can pick out some features to promote here, but I would also appreciate input!
<img width="1130" alt="ignite_2_0_has_landed__and_timesheet_ _infinite_red__inc__ _harvest" src="https://cloud.githubusercontent.com/assets/4466642/23563649/8b363e16-0015-11e7-8380-a047690f97a4.png">

**Comment by skellock** [comment]
oh man... that IS angry!

**Comment by skellock** [comment]
One feature I like is:  It's a boilerplate maker.  There's like 30 React Native boilerplates out there, and we're all blending together.  Ignite allows you to make your own boilerplate and still pick the best plugins that work for you.

Another feature is: spork!  With it, no generators are locked in.  At a project level, you can use a 3rd party generator, and then change small things you didn't like about it... for example if you're on "team semi-colon" but the generator isn't.

Jamon likes No Runtime Dependencies.  We only have dev dependencies.  Like a linter, nothing ignite ships with your app if you don't want it.

I'll add more when I think of it...  sorry they're not in marketing format.

**Comment by mlaco** [comment]
Your descriptions are great, I'm using them.

**Comment by mlaco** [comment]
I've made a pass at copy on https://infinite-red-staging.herokuapp.com/ignite. Feedback very welcome!

**Comment by jamonholmgren** [comment]
Really good @mlaco , I'll revise a bit soon.

**Comment by GantMan** [comment]
![image](https://cloud.githubusercontent.com/assets/997157/23805389/47a270ca-0583-11e7-8dd9-5af8a9dfd896.png)
**^ should be launch screen graphic**

![image](https://cloud.githubusercontent.com/assets/997157/23805293/ecef522e-0582-11e7-86ca-3e54c1c8de59.png)
suggested:
**Ignite 2 is a CLI and generator for React Native with boilerplates, plugins, and more. Choose from many boilerplates, or start your own! Support standalone plugins as you need them. Ignite adapts to your project -- not the other way around.**

![image](https://cloud.githubusercontent.com/assets/997157/23805358/283dc57c-0583-11e7-828f-2a21893b12fc.png)
**^ talk to @cindy-nguyen about getting the right graphic here.**

![image](https://cloud.githubusercontent.com/assets/997157/23805425/732735f0-0583-11e7-9507-19e0495d2b20.png)
**Our github readme provides a step by step guide on how to start using Ignite.  If you're interested in writing your own plugin, or even starting your own boilerplate that can use your own plugins, then check our docs folder for the correct quickstart.  You can always join us on http://community.infinite.red to ask your questions in person.**

![image](https://cloud.githubusercontent.com/assets/997157/23805626/4b15a58c-0584-11e7-8329-a281d3720da1.png)
Our goal is to make things work right away!  The modular plugin system gives you a friendly experience to add application features, or write your own.  Our goal is to be the co-pilot for your application build.  The smoother we make the experience, the better.  We're always open to feedback!

**Comment by robinheinze** [comment]
Added Gant's copy (tweaked a couple of words) and got the images put in.
