### ISSUE TITLE
React Native Prelease Builds and CI

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#777]
React Native often has breaking changes.  It'd be cool to stay on top of this by trying out their preleases (or even nightly builds).

We have the ability now to say `ignite new OmgYisss --react-native-version 0.42.0-rc.3 --max`.

It'd be great to hook this + our integration tests up to a robot to run these for us.

@GantMan has more info on Travis if we go with that.

**Comment by jamonholmgren** [comment]
And, in my humble opinion, the React Native core team could keep an eye on our CI to see what they're breaking. ¯\_(ツ)_/¯

**Comment by skellock** [comment]
Mr Shruggy!  Your arm!!?

React Native is amazingly tested. The breaks are more by design. They're doing the right thing.

**Comment by jamonholmgren** [comment]
Not intending to implement this; closing.
