### ISSUE TITLE
Styled Components Plugin

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#783]
I've [seen just enough](https://github.com/styled-components/styled-components) of this plugin to know it's pretty hot 💩 .  I'd love to use this.

I'm using it on a web-based side project, and it feels great.  The support React Native and the concept is pretty solid.

It addresses the top problem I have with how we do our styles.  Portability.

**Comment by jamonholmgren** [comment]
We don't intend to build this plugin, so I'm going to close this issue.
