### ISSUE TITLE
Statement Management Pluggability in infinite-red-app-template

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#784]
We're team Redux.  Nothing wrong with that.

Mobx, rxjs, cycle, redux-loop.  I can't keep em all straight.

Question I have here is... do we want to support pluggability into `ignite-infinite-red-app-template`?  or do we encourage people to make their own boilerplates?

I vote the latter.  But what does everyone think?

**Comment by GantMan** [comment]
So your idea is keep that problem at the boilerplate level?   I kinda like this solution.  It slides the scale in the other direction for simplicity.

Let's discuss and put our resulting convo here on github.

**Comment by skellock** [comment]
The current landscape of react-native boilerplates is zero-sum.  Everyone has their strong opinions and they start their own starter kit and we fragment more & more.

Ignite is now offering an end to that churn.  And it's not our opinions.  It'll be our plugins.

See, I think its sound advice to "create your own boilerplate".  You pick the right state management for you.  You pick the right styling components.  You pick the navigator you like.

But we all need maps.  Push notifications.  Vector Icons.  CodePush.

We have a way we build stuff at Infinite Red.  I think a lot of people will like that.  3,895 people if I were a betting man. But there's probably 10x that who don't.  Or outgrow it.  Or are curious to try another style.  Or want tweaks.

Now they don't have to go away because they use Ducks or whatever.  They can make their own boilerplate chock full of opinions.  Just like we did under [153 lines of code](https://github.com/infinitered/ignite/blob/master/packages/ignite-infinite-red-app-template/index.js) + a bunch o templates.  

If we say, `ignite-infinite-red-app-template` is a redux stack, we can invest our time in other places: plugins.

With a custom `ignite-*-app-template`, people can get to work right now.  With `ignite-infinite-red-app-template` we have to move our code out of the way, negotiate a common ground with neighbours, maintain a dropdown list for their option, hope they don't go stale, hope we don't go stale....  boilerplates just seem more nimble.

^ The opinion of a man who just drank a lot of [NeoCitran](http://www.neocitran.ca/).

**Comment by jamonholmgren** [comment]
I'm fully on board with this. Let's make `infinite-red-app-template` the gold shining star of Redux React Native boilerplates, and encourage team MobX to make their own gold shining star Ignite boilerplate. (Almost certainly someone watching this thread is on that team -- we want you to make a boilerplate, so please [join us](http://community.infinite.red) and let's make this happen.)
