### ISSUE TITLE
Generators show no useful output

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#785]
When running any generator, I just get the Ignite header:

![screen shot 2017-02-27 at 9 42 52 pm](https://cloud.githubusercontent.com/assets/1479215/23393183/f4e1c4c6-fd35-11e6-85f9-31e5fc406b2b.png)

I should see a progress bar and completion like `ignite add`.

Question: is this the plugin's responsibility? I'd think this would be provided by ignite-cli's generator.js.

**Comment by jamonholmgren** [comment]
Note that the generator in question worked fine. I ran it twice though because I didn't think it worked.

**Comment by skellock** [comment]
#805 fixes this.  CopyBatch wasn't printing anything.  It will now.
