### ISSUE TITLE
--verbose should be a thing

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#786]
we have `--debug`; let's make an alias called `--verbose` for those of us who accidentally forget what to type here.

**Comment by jamonholmgren** [comment]
Also `-v`.

**Comment by skellock** [comment]
And lets remove --debug.  I agree with you guys.

**Comment by GantMan** [comment]
-v is for version though :(

**Comment by GantMan** [comment]
@skellock - not so sure I agree on removing `--debug`.  but only advertising that one exists.  You can keep `--debug` as functional should someone try it instead of verbose.

**Comment by skellock** [comment]
I forgot about `-v`, good point.  Shouldn't remove that.

I'm ok with keeping the crouching verbose hidden debug.

**Comment by jamonholmgren** [comment]
you guys are getting really verbose on this tiny issue

I won't try to debug you though

**Comment by skellock** [comment]
Daaaadddd.... you're embarrassing me in front of my friends.

**Comment by jamonholmgren** [comment]
@skellock I'm not actually seeing a way to do this in Ignite. Is this a gluegun thing?

**Comment by skellock** [comment]
https://github.com/infinitered/ignite/blob/master/packages/ignite-cli/src/extensions/ignite/log.js#L12
