### ISSUE TITLE
Rename a few projects

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#798]
Since these generators rely on `ignite-infinite-red-app-template`, anyone object to me renaming this to `ignite-infinite-red-generators`?

/cc @GantMan + @jamonholmgren

**Comment by jamonholmgren** [comment]
I thought this over this morning. I think I'd rather keep the current name in this case. While the IR-AT is definitely all Infinite Red opinions, these generated components and whatnot are less opinionated. And Ignite needs some basic generators as something to default to. I'd vote to keep as-is.

**Comment by skellock** [comment]
`ListView` and `Component` are almost opinion free.  The other are full-on Infinite Red.

Split 'em up?

I like the idea of creating `ignite-infinite-red-generators` because people who create their own boilerplates will be doing the same.  It'd be nice to show folks an example of where and why.

If we have some core generators, we'll get people contributing more.  That way we can build up a library of things everyone needs.  Just like we're doing with plugins.

**Comment by skellock** [comment]
That last message was very cryptic.  I was typing it mid-meeting.

Here's what we decided:

* `ignite-minimal-app-template` will disappear.  i've just rolled that into `ignite-infinite-red-app-template`.
* `ignite-infinite-red-app-template` is now called `ignite-ir-app`.
* we're recommending people call these things `ignite-{boilerplate-name}-app`.
* `ignite-empty-app-template` is going to be dismantled and run entirely from inside `new.js`.
* `ignite-basic-generators` is going to be rolled into `ignite-ir-app`.
* `ignite-dev-screens` will remain here, but will be stripped of all `ir` opinions and hooks.

**Comment by jamonholmgren** [comment]
Update: `ignite-ir-app` will be renamed to `ignite-ir-boilerplate` and we will have a slightly different model for boilerplate plugins.

**Comment by jamonholmgren** [comment]
I re-opened #819 to track the final thing that remains here. Closing this.
