### ISSUE TITLE
MyApplication doesn't run 

### ISSUE THREAD

**Issue by junbinku** [infinitered/ignite#809]
Hi there, 
I ran the react-native run-ios and the stimulator shows up of an iphone screen.
I tried opening the MyApplication icon then it appears to open and just closed in just a few seconds.
I did every step of the instructions but this happens, not sure why is this happening.
This error appears.

ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1028:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1361:11)

**Comment by skellock** [comment]
Sounds like it might be a watchman issue.  Do you have watchman installed?  `brew install watchman`.

**Comment by jamonholmgren** [comment]
@junbinku Feel free to continue this conversation over in [our community slack](http://community.infinite.red) ... thanks!
