### ISSUE TITLE
Remove navbar bottom border

### ISSUE THREAD

**Issue by Cmdv** [infinitered/ignite#810]
### Hello I've been searching for some time to adjust the border line that sits bellow the top navigational bar 😟 

Could you let me know where this can be adjusted? ideally I'm looking at removing it 😄 

- [ ] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [ ] ignite base application
  - [ ] ignite the cli
  - [x] ignite generated code

**Comment by skellock** [comment]
Open up `App/Navigation/Styles/NavigationContainerStyle.js` and in the `navBar` object, add `borderBottomWidth: 0`.

Nice to see some PureScript people around these parts.

**Comment by Cmdv** [comment]
@skellock thanks a lot, was having a nightmare just couldn't find it 😂 

Us PS people still have to hold a day job hehe
