### ISSUE TITLE
Print better errors when dying

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#814]
Currently all unhandled exceptions just cause a promise failure and a useless error:

```js
(node:12915) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: extension.setup is not a function
(node:12915) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Let's capture and display the stack trace.

Sorry @robinheinze

**Comment by jamonholmgren** [comment]
Is this only a glue gun thing or do we need fixes in `ignite` too?

**Comment by skellock** [comment]
We should catch this up in Ignite, but ya, gluegun should not be letting this slip through.

For here,

It'd be nice to catch wrap this for setup errors:

https://github.com/infinitered/ignite/blob/master/packages/ignite-cli/src/cli/cli.js#L24

And this for runtime errors.

https://github.com/infinitered/ignite/blob/master/packages/ignite-cli/src/cli/cli.js#L44

Even if we just trap the exception, log the stack trace, and rethrow.  It's better than a swallowed promise and generic error.  We can certain improve this later.

**Comment by skellock** [comment]
@jamonholmgren bonus points for using this:  https://github.com/AriaMinaei/pretty-error or something like it if we're printing stack traces.
