### ISSUE TITLE
Remove Infinite Red opinions from ignite-dev-screens

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#819]
We should have no expectations that the `App/` folder exists.  This should be "standalone" plugin.

Now, we do have to hook into the user's app, but maybe we can detect that we've got `ignite-ir-app` install and do what we do now.  If it's not installed, we can print out instructions on what they can do to integrate?

**Comment by jamonholmgren** [comment]
Not _entirely_ fixed in #830 as requested @skellock so feel free to re-open if you'd like to do more on this.

**Comment by jamonholmgren** [comment]
Tracking this here until we're [fully satisfied](https://www.youtube.com/watch?v=nrIPxlFzDi0).

**Comment by jamonholmgren** [comment]
`ignite-dev-screens` is now [in its own repo](https://github.com/infinitered/ignite-dev-screens) and so we can track there if we want to. I'm not sure we need to pull the opinions out any more than we have already.
