### ISSUE TITLE
IGNITE_PLUGINS_PATH shouldn't be required

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#820]
#772 introduced IGNITE_PLUGIN_PATH and required it. However, I don't really think this should be required -- we should infer the path if not found. This results in a bad DX (IMO) when first spinning up an Ignite app.

<img width="618" alt="screen shot 2017-03-02 at 3 28 51 pm" src="https://cloud.githubusercontent.com/assets/1479215/23531808/2a8ef192-ff5d-11e6-92b4-0cb77b8b62fa.png">

**Comment by skellock** [comment]
It was only in place so we can make everything work while in dev mode.  The packages will all live on npm.

**Comment by skellock** [comment]
Just a heads up, this message only appears when the package isn't found on `npm`.

The resolution order for `ignite add something` goes like this:

* look for a directory called `something` (can be relative or absolute)
* look for a directory called `something` in any path found on `IGNITE_PLUGIN_PATH`
* look on npm

If all these fail you see that message.

Once we publish `ignite-ir-app`, we won't see this error anymore.

**Comment by jamonholmgren** [comment]
I knew that.

![headdesk](https://media.giphy.com/media/E2USislQIlsfm/giphy.gif)
