### ISSUE TITLE
Problem with Node 7.7.1 and fs-mock

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#823]
Currently tracking an issue with `fs-mock` and 7.7.1 not working.

Work around is to install node 7.6 for now.

More details here:  

https://github.com/tschaub/mock-fs/pull/198

**Comment by jamonholmgren** [comment]
We're on their timetable. Bumping to 2.0.

**Comment by skellock** [comment]
#838 changes this to a temp git dependency.
