### ISSUE TITLE
Screen generator has some issues

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#826]
When I generate a screen using `ignite g screen HomeScreen`, a few issues:

1. It makes `HomeScreenScreen` -- it should detect there's already *Screen and don't duplicate
2. It's using the wrong template interpolation `{{ props.name }}` instead of `<%= props.name %>`
3. It has an I18n line even though my app doesn't have I18n

**Comment by nonotest** [comment]
Just tried this generator and ended up with :
```
/* ***********************************************************
* A short word on how to use this automagically generated file.
* We're often asked in the ignite gitter channel how to connect
* to a to a third party api, so we thought we'd demonstrate - but
* you should know you can use sagas for other flow control too.
*
* Other points:
*  - You'll need to add this saga to sagas/index.js
*  - This template uses the api declared in sagas/index.js, so
*    you'll need to define a constant in that file.
*************************************************************/

import { call, put } from 'redux-saga/effects'
import ScanProductActions from '../Redux/ScanProductRedux'

export function * getScanProduct (api, action) {
  const { data } = action
  // make the call to the api
  const response = yield call(api.getscanProduct, data)

  // success?
  if (response.ok) {
    // You might need to change the response here - do this with a 'transform',
    // located in ../Transforms/. Otherwise, just pass the data back from the api.
    yield put(ScanProductActions.scanProductSuccess(response.data))
  } else {
    yield put(ScanProductActions.scanProductFailure())
  }
}
```
in my `ScreenStyle` , not sure if I should make a separate issue or if it's linked to the interpolation problem,

thanks guys,

**Comment by nonotest** [comment]
Just noticed that it added `Animatable` as well when I didn't add it to the project.
Looks like it's not taking into account any of the initial settings.

**Comment by Un3qual** [comment]
Is anyone working on this? It seems like a pretty high priority issue.

**Comment by skellock** [comment]
We track boilerplate issues [over here](https://github.com/infinitered/ignite-ir-boilerplate-2016).

And yes, I'm working on this.

**Comment by jeveloper** [comment]
Thanks Skellock , was about to fix it :)
