### ISSUE TITLE
Update CI to run new tests

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#828]
Update our CI to run Ignite 2 tests.

* [ ] ~Remove Travis~ Actually, we'll keep Travis I think -- if it works
* [ ] Add `./bin/testRelease` that runs all tests and checks generated output
* [ ] Update Semaphore to run `./bin/testRelease`

**Comment by skellock** [comment]
Snagging this from ya @jamonholmgren

**Comment by skellock** [comment]
We don't need any custom scripts or global installs for this repo.

![image](https://cloud.githubusercontent.com/assets/68273/23580037/e2541d3c-00c7-11e7-8a5b-2d82b015d84e.png)

We may want to consider something like this for `ignite-ir-boilerplate-2016` once we promote that package to a repo.
