### ISSUE TITLE
Early failing `ignite new` should have rollback

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#846]
There's nothing useful in an early failing `ignite new`
![image](https://cloud.githubusercontent.com/assets/997157/23583226/4d55769a-0103-11e7-8c99-ce6591251257.png)

The TestProj folder has an `npm-debug.log` which is useless.  We should have just cleaned up after ourselves.

**Comment by skellock** [comment]
This won't fail anymore because we've published `ignite-ir-boilerplate-2016` on npm.
