### ISSUE TITLE
Nothing is generated on Windows 10

### ISSUE THREAD

**Issue by johntom** [infinitered/ignite#862]
Hi
Installed version 2 on win10 pro and checked all dependecies. With exception of maps I had ignite 1 sample running using genymotion. When I run ignite new PizzaApp nothing is generated in folder. Note: I also posted on slack,
Thanks
John

**Comment by skellock** [comment]
Thanks for the report John.  We'll take a look at running from Windows.  Probably something small I overlooked.

**Comment by johntom** [comment]
I'm looking to move and app from Native Starter Pro(4.0) and already find the support community (slack and github) a notch above. Also I just found out about the following  and tracking now.

C:\React\ignite2>ignite doctor
System
  platform           win32
  arch               x64
  cpu                4 cores            Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  directory          C:\React\ignite2

JavaScript
  node               7.7.1        C:\PROGRAM FILES\NODEJS\NODE.EXE
  npm                4.1.2        C:\PROGRAM FILES\NODEJS\NPM.CMD
  yarn               0.21.3       C:\USERS\JOHN\APPDATA\ROAMING\NPM\YARN.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0-beta.1   C:\USERS\JOHN\APPDATA\ROAMING\NPM\IGNITE.CMD
vvv -----[ DEBUG ]----- vvv
{ Error: Command failed: java -version
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

    at ChildProcess.exithandler (child_process.js:210:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'java -version',
  stderr: 'Error: Registry key \'Software\\JavaSoft\\Java Runtime Environment\'\\CurrentVersion\'\r\nhas value \'1.8\', but \'1.7\' is required.\r\nError: could not find java.dll\r\nError: Could not find Java SE Runtime Environment.\r\n' }
^^^ -----[ DEBUG ]----- ^^^

**Comment by skellock** [comment]
Oh that's interesting.  That error looks like it's triggered by running `ignite doctor`.  Do you get the same error if you just type `java` from the command line?

What do you see if you run `ignite new HelloJohn --debug`?

**Comment by johntom** [comment]
C:\React\ignite2>ignite new PizzaApp --debug
-----------------------------------------------

-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

:fire:  igniting app PizzaApp
16:09:24 [ignite] making directory PizzaApp
16:09:24 [ignite] switched directory to C:\React\ignite2\PizzaApp
16:09:24 [ignite] running boilerplate: ignite boilerplate-install ir-boilerplate-2016 PizzaApp --debug
16:09:24 [ignite] error running boilerplate
16:09:24 [ignite] undefined
16:09:24 [ignite] cleaning temporary files
16:09:24 [ignite] finished running new

C:\React\ignite2> (edited)

C:\React\ignite2>java
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

C:\React\ignite2>

**Comment by johntom** [comment]
Odd thing is that 1.7 is no longer available. ReInstalling with jdk-8u121-windows-x64.exe

**Comment by skellock** [comment]
Looks like there's 2 issues here.  

Issue 1 is the boilerplate isn't getting run properly.  I was able to reproduce that here.  We'll patch that up.

Issue 2 looks like java isn't setup properly to run from the command line.  Maybe consider re-installing Java?  Are you able to run `react-native android` ok from normal apps?

**Comment by skellock** [comment]
Oops.. haha.  I posted at the same time as you.  Ok.  Sounds good.

**Comment by johntom** [comment]
yes I've had no major problems with react-native android

**Comment by johntom** [comment]
I finally followed this https://www3.ntu.edu.sg/home/ehchua/programming/howto/JDK_Howto.html
Seems like java is fixed

C:\React\ignite2>ignite doctor
System
  platform           win32
  arch               x64
  cpu                4 cores            Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  directory          C:\React\ignite2

JavaScript
  node               7.7.1        C:\PROGRAM FILES\NODEJS\NODE.EXE
  npm                4.1.2        C:\PROGRAM FILES\NODEJS\NPM.CMD
  yarn               0.21.3       C:\USERS\JOHN\APPDATA\ROAMING\NPM\YARN.CMD

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0-beta.1   C:\USERS\JOHN\APPDATA\ROAMING\NPM\IGNITE.CMD

Android
  java               -            C:\PROGRAMDATA\ORACLE\JAVA\JAVAPATH\JAVA.EXE
  android home       -            C:\Users\john\AppData\Local\Android\sdk

C:\React\ignite2>

**Comment by skellock** [comment]
Sweet! 

Still working on the other issue.  It's happening when shelling out to run `react-native link` on Windows.  Not quite sure why some react-native commands work and some don't.

**Comment by mwarger** [comment]
I'm getting this issue as well.  Thanks for looking into it!

**Comment by skellock** [comment]
No, unfortunately that log files doesn't exist.  We're tracking that issue here #623.  Logging is something I believe should be added to gluegun as well.

[This line](https://github.com/infinitered/ignite-ir-boilerplate-2016/blob/master/boilerplate.js#L185) is causing the grief.  Seems to not want to execute in a grandchild process.  Been trying a bunch of things, but no luck so far.

**Comment by giangqaz** [comment]
running ignite 2.0 on windows, and I got same error.

**Comment by alopezinkt** [comment]
Same issue here and now when I run "ignite generate component Mycomponent" on a folder with an app generated with v1.9..6 it says that the command has to be run on a ignite-compatible directory.

I tryed to downgrade to version 1.9.6, but I get the same error about non ignite-compatible directory.

**Comment by skellock** [comment]
I'm working on a fix for Windows for beta 2.

**Comment by skellock** [comment]
Alrighty crew.  Please grab the latest version.  Beta 3.  `npm i -g ignite-cli`.  This fixes a few issues outstanding on Windows.

Please let me know if you have any issues with it.

**Comment by giangqaz** [comment]
thanks, it worked
