### ISSUE TITLE
Newly generated screen does not have EJS pass through

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#869]
![image](https://cloud.githubusercontent.com/assets/997157/23591580/f9a12066-01b7-11e7-8c33-c916a69376fb.png)

### Steps to recreate:
Generate a screen, see it fail to properly handle EJS injection.
`ignite g screen Taco`

---
### Suggested Strategy for Testing:  
This will also fail linting.  A decent test should be to generate a screen and lint it.  This would protect against failed EJS as well as templates that do not adhere to our linting standards.

**Comment by GantMan** [comment]
fyi, I'm writing this test.

**Comment by kevinvangelder** [comment]
@GantMan Is this complete?

**Comment by GantMan** [comment]
it is now.
