### ISSUE TITLE
What to do with dirty files after running ignite remove plugin 

### ISSUE THREAD

**Issue by juddey** [infinitered/ignite#870]
I'm writing `ignite-keychain`, to add `react-native-keychain` to ignite. I run `ignite add /home/justin/projects/react-native/ignite-keychain`, then `ignite remove ignite-keychain`

I get this status:
![image](https://cloud.githubusercontent.com/assets/7445602/23594811/d38c0542-0281-11e7-9f8d-afbec05057c7.png)

All seems to be added and removed as expected but I am wondering what to do with these couple of files that are marked as modified. This is what has changed: 

#### yarn.lock
```
"ignite-keychain@file:/home/justin/projects/react-native/ignite-keychain":
  version "0.0.1"
```
#### project.pbxproj
```
LIBRARY_SEARCH_PATHS = (
		"$(inherited)",
<<< there were some deletes in here >>>
				);
```
I'm wondering if yarn.lock might disappear on its own once the package is installed to npm, and whether I should even worry about the iOS project file...

But I thought I would ask.

**Comment by skellock** [comment]
Casualty of war unfortunately.  😆

**Comment by juddey** [comment]
:boom:
