### ISSUE TITLE
Add sanity checks before running new

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#874]
We have `ignite doctor` yay!

But...

We need to run environmental checks before allowing people to run `new`.

So far I've seen people have issues with `react-native-cli`, `yarn` and `xcode 7`.

Let's check these things silently before allowing them to spit out an app.

* [ ] Check presence of react-native & error if it's installed
* [ ] Check presence of npm 2, upgrade to npm 4 after installing ignite (see [below comment](https://github.com/infinitered/ignite/issues/874#issuecomment-285345838))

**Comment by skellock** [comment]
Another thing to add to the list.  The presence of `react-native` installed globally will trip up some steps but not others.  :(

**Comment by skellock** [comment]
Also, people who have npm 2 installed, then upgrade to npm 4 after installing ignite will have issues.  We can detect this by looking for the `gluegun` dependency underneath the `node_modules` in the `ignite-cli` directory.

**Comment by skellock** [comment]
Come to think of it, that's exactly what [should be happening](https://github.com/infinitered/ignite/blob/master/packages/ignite-cli/package.json#L52).  Investigate why this isn't working?

**Comment by skellock** [comment]
Might want to consider #883 detection as well if it turns out to be an issue.

**Comment by skellock** [comment]
Bumping up to higher priority as this is devouring lots of hours.

**Comment by jamonholmgren** [comment]
PR on the way for checking presence of `react-native`.

**Comment by skellock** [comment]
I did a check for `react-native` already.  We still need a few others still.

**Comment by jamonholmgren** [comment]
Should be good to go on this one.
