### ISSUE TITLE
[Base] - Add API Test Screen

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#88]
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

Need for the API test screen has been stubbed.  Please add it.

**Comment by kevinvangelder** [comment]
@GantMan Can you document what this features this screen should have?

**Comment by GantMan** [comment]
this screen is in use on several projects, it's basically a place for adding API for immediate testing.
