### ISSUE TITLE
`ignite init` fails for dashed-project-names

### ISSUE THREAD

**Issue by chapati23** [infinitered/ignite#882]
**What's going on?**
The failure itself happens during `react-native init`, i suppose. When you try `react-native init demo-app` you'll get an error message telling you that project names can only have alphanumeric characters.

---
**Steps to reproduce**
* Try running `ignite new demo-app`
* Watch it fail with no idea what's wrong

---
**Proposed solution**
* Forward the error message from `react-native init` so people don't have to walk through the source code to find out what's wrong :)

**Comment by skellock** [comment]
Agreed!  Thanks for opening this.

**Comment by skellock** [comment]
Related to #874
