### ISSUE TITLE
Windows Powershell issues

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#883]
I just dealt with someone who had some problems running under Windows Powershell.

It was worked around by running ignite through good ol' `cmd.exe`.

The error they were experiencing was:

![image](https://cloud.githubusercontent.com/assets/68273/23752552/c991221a-04a3-11e7-8aad-42c62580507b.png)

Could have been a rogue globally installed package, Windows Powershell, or perhaps the Illuminati.

**Comment by guarilha** [comment]
I had the same problem with Powershell 

```
user@machine MINGW64 ~/
$ ignite new NewApp
-----------------------------------------------
  (                  )   (
  )\ )   (        ( /(   )\ )    *   )
 (()/(   )\ )     )\()) (()/(  ` )  /(   (
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\
 (_))    /(_))_   _((_) (_))   (_(_())  ((_)
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _|
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app NewApp
√ using the Infinite Red boilerplate
√ added React Native 0.42.0
an error occured while installing ignite-ir-boilerplate-2016 boilerplate.
Error: ENOENT: no such file or directory, open 'C:\dev\tty'
``` 

Using `cmd.exe` solved for me as well.

**Comment by Slapbox** [comment]
Fails in babun, works in cmd.exe for me as well.

**Comment by pra85** [comment]
I faced a similar issue when using Git Bash. Works when using in `cmd.exe`

**Comment by skellock** [comment]
Anyone have insights into why this is happening?  Some light googling turn up no answers for me.

**Comment by Slapbox** [comment]
No idea why it doesn't work, but is there a reason you can't use `cmd.exe`?

**Comment by skellock** [comment]
Me personally?  Ya, I can use `cmd.exe`.  But it should run on powershell & git bash too.  Because people use that as well.

**Comment by friek108** [comment]
I think this could be related to https://github.com/yarnpkg/yarn/issues/859 and https://github.com/yarnpkg/yarn/issues/2224. I can't get this to run in windows no matter what I try, even in command prompt or otherwise. Turns out setting up react-native takes days of work and still... ahhh :(

**Comment by weakish** [comment]
yarn v0.27.5 `global add` works with both cmd.exe and PowerShell.

**Comment by jamonholmgren** [comment]
I don't intend to support Windows Powershell, but if someone wants to tackle this, feel free!

**Comment by frankcalise** [comment]
PowerShell is now working in the latest version of Ignite, v8!
