### ISSUE TITLE
Not able  to create new plugin

### ISSUE THREAD

**Issue by anantha322** [infinitered/ignite#885]
local:Sample xyz$ ignite plugin new radio-buttons
? Is this an app boilerplate plugin? Yes
? Will your plugin have an example component? No
? Will your plugin have a generator command? (e.g. ignite generate <mygenerator>
 <name>) Yes
Creating new plugin: ignite-radio-buttons
vvv -----[ DEBUG ]----- vvv
Error: template not found /usr/local/lib/node_modules/ignite-cli/src/cli/../templates/plugin/.gitignore
    at Object.generate (/usr/local/lib/node_modules/ignite-cli/node_modules/gluegun/src/core-extensions/template-extension.js:51:13)
    at Object.copyBatch (/usr/local/lib/node_modules/ignite-cli/src/extensions/ignite/copyBatch.js:41:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)
^^^ -----[ DEBUG ]----- ^^^

**Comment by marionorato77** [comment]
I am getting exactly the same error when I try to create a new plugin. Does anyone else have the same problem?

**Comment by skellock** [comment]
Yes.  This is an issue.  I've just encountered this today.  The work around until we get the fix in place is to 

```sh
touch /usr/local/lib/node_modules/ignite-cli/src/cli/../templates/plugin/.gitignore
```
(or whever the first line of the error message is tell you to point.

We seem to be missing that file from the plugin generator.

**Comment by skellock** [comment]
Turns out... `.gitignore` is ignored by `npm`!   https://github.com/npm/npm/issues/7252

I'll do a work around to get this in place.

Sheesh.
