### ISSUE TITLE
Add Ctrl+C to Cancel

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#888]
There are some edge cases where when we spawn subcommands, control+c doesn't work anymore.

Let's look into something like https://github.com/jprichardson/node-death for trapping and exiting.

We should never lock up the user's shell.

First step would be to reproduce.  I think I remember experiencing this myself when a subcommand tried to prompt for input, but we weren't showing it.

**Comment by fvonhoven** [comment]
@skellock Additionally, you cannot ctrl+c out once Ignite is cooking...
![screen shot 2017-03-15 at 2 51 59 pm](https://cloud.githubusercontent.com/assets/10098988/23967983/090b0c9a-098f-11e7-883c-def34bb81fa0.png)

**Comment by jamonholmgren** [comment]
I can't seem to reproduce this. It works fine when I ctrl+C at the point @fvonhoven was at.

![image](https://cloud.githubusercontent.com/assets/1479215/26186392/5dc54136-3b46-11e7-9d2c-6f28289d71a8.png)

**Comment by aledalgrande** [comment]
This would be very useful. On my Mac (Sierra + zsh), it doesn't halt execution.

**Comment by jamonholmgren** [comment]
I believe this is no longer an issue with the latest versions of Ignite. If it is, please open a new issue (and tag this issue, #888).
