### ISSUE TITLE
Doesn't support node 6.x

### ISSUE THREAD

**Issue by pospi** [infinitered/ignite#889]
Given that `react-native-cli` doesn't support node >= `7.0` at the moment, this is somewhat painful. I dislike having to switch node versions constantly!

**Comment by GantMan** [comment]
are you sure about that?  I think we're using it just fine. hrmmm

**Comment by skellock** [comment]
The `react-native-cli` works great on node 7.6+.  Make sure you're running the latest version of that cli.

**Comment by pospi** [comment]
My bad- I had some interoperability issues between Yarn and NVM.. complicated to explain and not relevant to this project!

**Comment by skellock** [comment]
No problem. Yarn has been awesome and frustrating at the same time.

**Comment by pospi** [comment]
Yeah. So the more detailed version is basically that Yarn installs global
modules to its own folder, and you end up with conflicting modules when you
run multiple nodes with NVM. In addition it uses a `package.json` to manage
that folder, so if you switch node versions and attempt another global
module install you might find some of your previously installed globals
complaining about unsupported node versions. The error turned out to be
from a module not related to `react-native-cli` at all, but the error
output made it look like a dependency to me.
