### ISSUE TITLE
Super Verbose Install Mode

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#89]
I feel like that giant wall of text is a bit too much when running `ignite n MyApp`.   Would you be open to using a spinner instead?

**Comment by GantMan** [comment]
very much so!   The wall of text is better than eerie silence (the default behavior), but farrrrr from ideal.   

Implementing a spinner with some kind of "here's what we're working on" feedback is very friendly in comparison.

**Comment by GantMan** [comment]
documenting: 
Suggested spinner -> https://github.com/helloIAmPau/node-spinner

**Comment by kevinvangelder** [comment]
Resolved by #121
