### ISSUE TITLE
Ignite 2 "New Command" doesn't work

### ISSUE THREAD

**Issue by lacmax** [infinitered/ignite#894]
Ignite 2 "New Command" doesn't work, 
When I run the ignite new command only the initial folder is created without any content
---
What's going on?
Ignite 2 "New Command" doesn't work
---
Steps to reproduce
ignite new PizzaApp
---
`ignite doctor` results:
System
  platform           darwin                                                                                             
  arch               x64                                                                                                
  cpu                8 cores                                       Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz  
  directory          /Users/lucascarvalho/Desktop/ProjetosIgnite                                                        

JavaScript
  node               7.6.0        /usr/local/bin/node  
  npm                4.1.2        /usr/local/bin/npm   
  yarn               -            null                 

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.0.0-beta.4   /usr/local/bin/ignite  

Android
  java               1.8.0-ea     /usr/bin/java  
  android home       -            undefined      

iOS
  xcode              8.0

**Comment by skellock** [comment]
do you accidently have `react-native` installed globally?  it should only be `react-native-cli`.  I've seen this environment cause this error.

Try `npm rm -g react-native` and try again.

**Comment by lacmax** [comment]
Same problem :( , Last week it was working, I do not know if it was after the last beta version.

**Comment by lacmax** [comment]
<img width="646" alt="captura de tela 2017-03-13 as 16 20 34" src="https://cloud.githubusercontent.com/assets/18317823/23871563/b8303a88-0809-11e7-9860-2cd341f3ed15.png">

**Comment by nonotest** [comment]
yep same here, worked with beta2.

```
$ ignite doctor
System
  platform           darwin
  arch               x64
  cpu                8 cores                                          Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
  directory         ..

JavaScript
  node               7.7.1        /usr/local/bin/node
  npm                4.3.0        /usr/local/bin/npm
  yarn               0.21.3       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0-beta.4   /usr/local/bin/ignite

Android
  java               1.8.0_77     /usr/bin/java
  android home       -            /Users/arnaudmoret/Library/Android/sdk

iOS
  xcode              8.2.1
```

**Comment by nonotest** [comment]
@lacmax  this was related to the project name for me. make sure your project name would be valid if you were using `react-native init` instead

**Comment by fvonhoven** [comment]
@lacmax Did you get it working?
@skellock seems to be related to #882 ? Perhaps we can close this if lacmax is 👍

**Comment by skellock** [comment]
another thing to try is with `--npm`.  this forces yarn to turn off.  I've seen a few cases now of conflicts between nvm vs yarn as well as yarn vs yarn.  It's hard to keep this straight haha.

**Comment by jamonholmgren** [comment]
@skellock This is labeled "bug" and "help wanted" but I'm not seeing anything actionable here. Good to close?

**Comment by skellock** [comment]
@lacmax @nonotest can you try this again with the latest? `npm i -g ignite-cli`.

**Comment by nonotest** [comment]
It worked the first time after updating ignite-cli.. but then it started not working again.
Looks like it reverted back to the old behaviour although I still have
```
$ ignite -v
2.0.0-beta.8
```

Will try to re-install ignite later and see what happens.
Cheers,
