### ISSUE TITLE
Remove es6-ism from check.js

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#895]
Let's go straight up vanilla es3 in our check.js script.

People still installing with Node 4 will experience this, instead of the nice error message hiding this gate.

```sh
[dominic:/personal-workspace]$ ignite new pizza
/home/dominic/.nvm/versions/node/v4.2.3/lib/node_modules/ignite-cli/src/cli/check.js:2
const { nodeVersion, isNewEnough, hasAsyncAwait } = require('gluegun/sniff')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
```

**Comment by choisel** [comment]
Hello, I ran into this issue while trying to test your tool.
Do you have any workaround until it's fixed?

Thanks.
Choisel.
