### ISSUE TITLE
Warnings on init

### ISSUE THREAD

**Issue by johntom** [infinitered/ignite#897]
`ignite doctor` results:

```
  platform           win32
  arch               x64
  cpu                4 cores                     Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  directory          C:\React\ignite2\PizzaApp

JavaScript
  node               7.7.1        C:\PROGRAM FILES\NODEJS\NODE.EXE
  npm                4.1.2        C:\PROGRAM FILES\NODEJS\NPM.CMD
  yarn               0.21.3       C:\USERS\JOHN\APPDATA\ROAMING\NPM\YARN.CMD

React Native
  react-native-cli   2.0.1
  app rn version     0.42.0

Ignite
  ignite             2.0.0-beta.4   C:\USERS\JOHN\APPDATA\ROAMING\NPM\IGNITE.CMD

Android
  java               -            C:\PROGRAMDATA\ORACLE\JAVA\JAVAPATH\JAVA.EXE
  android home       -            C:\Users\john\AppData\Local\Android\sdk

C:\React\ignite2\PizzaApp>
```
![screenshot-2017-03-14_12 05 17 181](https://cloud.githubusercontent.com/assets/1877376/23910953/aa74422e-08b1-11e7-9cdd-cc19c9609657.png)
![screenshot-2017-03-14_12 05 49 898](https://cloud.githubusercontent.com/assets/1877376/23910955/aa792550-08b1-11e7-9247-62ccf872b76b.png)
![screenshot-2017-03-14_12 06 30 146](https://cloud.githubusercontent.com/assets/1877376/23910954/aa74e7b0-08b1-11e7-98b0-cb870e2e6449.png)

**Comment by skellock** [comment]
The `onRequestClose` warning has [this PR](https://github.com/infinitered/ignite/pull/892) fixing it.  I haven't reviewed it.

The Navigation issue [was fixed] in `react-navigation`, but we haven't updated the dependencies in the dev screens yet.  You should be able to update the `react-navigation` library in your project it might go away if they've released the fix.

Thanks!
