### ISSUE TITLE
Fresh install doesn't pass linting

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#90]
Let's patch these two bad boys up.  A fresh ignite app doesn't pass our own linting.  :)

```
./App/Containers/AllComponentsScreen.js
  15:8  error  'I18n' is defined but never used  no-unused-vars

./App/Navigation/NavigationBar.js
  8:2  error  More than 1 blank line not allowed  no-multiple-empty-lines
```

**Comment by GantMan** [comment]
I wonder how this ever got in master like this.  O well, fixed now.  good catch!

**Comment by skellock** [comment]
Thanks!  I don't mind fixing these up too.  Just sort of recording as I go here.  👍

**Comment by GantMan** [comment]
yeah, you caught me exactly at the right time, I was just finished a task, so I grabbed it.

Normally not this kind of response time, lol
