### ISSUE TITLE
json-server plugin

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#900]
![image](https://cloud.githubusercontent.com/assets/68273/23918324/ea414b88-08c8-11e7-9a39-2a0a24240679.png)

**Comment by GantMan** [comment]
![mind blown](https://cloud.githubusercontent.com/assets/997157/23918407/0dc6a738-08b0-11e7-9d86-ee90b0bd9075.gif)

**Comment by skellock** [comment]
@derekgreenberg any interest in doing this? I know you had some great opinions about fixtures and mock objects from our channel yesterday.

**Comment by derekgreenberg** [comment]
@skellock This sounds like a good task for me. I could work on it this Saturday, but I will need your help to get started.

**Comment by skellock** [comment]
I'm doing a session with @carlinisaacson and @fvonhoven tomorrow at 2pm PST for 1 hour.  Covering the basics on how to get started with contributing & developing plugins.  Love to have you.

**Comment by derekgreenberg** [comment]
I'll attend today's training session at 2PM PST.

**Comment by carlinisaacson** [comment]
@skellock @derekgreenberg I believe that session is actually 11AM PDT and 2PM EDT.

**Comment by skellock** [comment]
lol!  thank you.. i'm sorry.  timezones are hard.

**Comment by jamonholmgren** [comment]
@derekgreenberg has this mostly done, so I'll close this issue and he can publish when he's ready.
