### ISSUE TITLE
ignite generate screen 

### ISSUE THREAD

**Issue by naaness** [infinitered/ignite#901]
When I generate a screen the component's name is {{ props.name }}, is normal?

![image](https://cloud.githubusercontent.com/assets/5529918/23924738/f1411254-08d9-11e7-9ecd-56b541d7afb5.png)

**Comment by skellock** [comment]
No, that's a bug.  We've got PR accepted and merged, just pushing out a build shortly.  Standby.

**Comment by naaness** [comment]
@skellock thanks man
