### ISSUE TITLE
Update react-native-ignite to helpfully point to ignite-cli

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#907]
If someone installs `react-native-ignite` by mistake, it would be good to give them a heads-up about Ignite 2 (`ignite-cli`). Maybe we could add an info log that tells them to uninstall this one and install `ignite-cli`.

Something like:

```
$ npm install -g react-native-ignite
$ ignite
Ignite 2 beta is out! To try it, run:

npm uninstall -g react-native-ignite
npm install -g ignite-cli

Go to https://infinite.red/ignite to learn more.

<normal stuff>
```

**Comment by skellock** [comment]
Great idea!
