### ISSUE TITLE
Screen generation is generating saga instead of style

### ISSUE THREAD

**Issue by elieteyssedou** [infinitered/ignite#908]
Hi,

I just began a project with Ignite, but when I came to generate a screen called 'Home', ignite created me a saga in the HomeScreenStyle instead of a style.

<img width="1052" alt="capture d ecran 2017-03-17 a 10 41 44" src="https://cloud.githubusercontent.com/assets/8143621/24037801/36093e30-0aff-11e7-96eb-da5db002e905.png">

By the way, in the screen generation I had some `{{ props.name }}` expressions instead of just `HomeScreen`. I couldn't launch my screen until I change all the `{{ props.name}}` for `HomeScreen`. (something related to the template engine I guess)

<img width="838" alt="capture d ecran 2017-03-17 a 10 48 29" src="https://cloud.githubusercontent.com/assets/8143621/24037904/afca0f56-0aff-11e7-9bae-e6fd4712085d.png">
 
Thank you,

Elie

**Comment by GantMan** [comment]
Hey Elie!  It looks like we fixed this a while ago, but there wasn't a new/released version of the boilerplate!   We're gonna circle up to make sure this doesn't happen again.  Thanks so much for bringing this to our attention!   Sorry for the silly issue.

**Comment by valinaga** [comment]
@GantMan when can we get the fix for above? Copy/pasting screens and styles is annoying. Thanks

**Comment by GantMan** [comment]
should be fixed in latest boilerplate.  Please test

`ignite add ir-boilerplate-2016`
let me know if that works.

**Comment by GantMan** [comment]
We try to fix issues ASAP, but weekends always slow us down.   🎉  🎈

**Comment by valinaga** [comment]
I got `'import RoundedButton' was not found in file.` while running `ignite add ir-boilerplate-2016`. Was it completed? What was it suppose to return on success?

**Comment by jamonholmgren** [comment]
Just tested generating a screen and it looks like this has been fixed.

![screen shot 2017-03-22 at 10 42 49 pm](https://cloud.githubusercontent.com/assets/1479215/24233666/f21f3df4-0f50-11e7-88b7-bdcf38694967.png)

@valinaga Could you file a new issue over at https://github.com/infinitered/ignite-ir-boilerplate-2016 if you're still having this issue?
