### ISSUE TITLE
Installation error when node_modules/react-native exists

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#913]
With @derekgreenberg's help, we were able to reproduce a strange error that some people may have been getting on their machines during the install process.

### Steps to reproduce

```sh
mkdir /tmp/foo
cd /tmp/foo
npm init -y
yarn add react-native
ignite new something --max
```

### How to prevent

We should detect if the user is in a directory with `node_modules` and has `react-native` in it.  We should prevent people from getting into this situation.

Sadly, I think it may be cause by `ignite` not being able to be run from a prior attempt (but cannot reproduce this just yet).

**Comment by moses5407** [comment]
I don't know if commenting reopens this.. HOpefully so.

I'm getting a different error and this has continued after trying the react-native cli update mentioned.

I get "an error occured while installing ignite-r-boilerplate-2016 boilerplate"
Error: Command failed git-commit-m "Initial commit"
Please tell me who you are"

It then sticks on configuring git
