### ISSUE TITLE
Allow installing into an existing directory

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#914]
@derekgreenberg pointed out a good use case where you would have a directory already created and would like to install ignite into it.

This will happen when people create the repo first on github.

`react-native init` will prompt you first and then install it.  We should do the same.

**Comment by kevinvangelder** [comment]
To be clear, you mean warn the user before overwriting the directory versus `ignite attach`?

**Comment by skellock** [comment]
Currently we don't let people create ignite into an existing directory.  It always creates it in a sub-directory.

To be honest, that's a limitation of `react-native init`, but we could move it back a directory once it's finished.

So he basically wanted `ignite new Derek .` =)

**Comment by jamonholmgren** [comment]
In my opinion, since `react-native init` doesn't support this, I don't think we should. I vote to `wontfix` this. :)

**Comment by skellock** [comment]
Sold.
