### ISSUE TITLE
Older react-native-cli causing ENOENT issues

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#919]
Older versions of `react-native-cli` are causing issues with `nvm`-based installs.

This seems to be resolved in the more recent versions of `react-native-cli`.  Let's make `react-native-cli>=2.0.0` a requirement.

### Steps to Reproduce

```sh
nvm use 7.6.0
npm i -g react-native-cli@1.10.0
npm i -g ignite-cli@2.0.0-beta.6
```

### Fixed By

```sh
npm i -g react-native-cli@2.0.1
```

**Comment by skellock** [comment]
Related:

* https://github.com/infinitered/ignite-ir-boilerplate-2016/issues/11
* #905 
* #894 
* #874

**Comment by agahEbrahimi** [comment]
I've already done this but it continues giving the same error anyway.

**Comment by pavini** [comment]
Hi, I try uninstall react-native but I still getting the problem.

ignite doctor

System
  platform           darwin
  arch               x64
  cpu                4 cores                 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
  directory          /Users/pavini/Desktop

JavaScript
  node               9.5.0        /usr/local/bin/node
  npm                5.6.0        /usr/local/bin/npm
  yarn               1.3.2        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0        /usr/local/bin/ignite

Android
  java               1.8.0_151    /usr/bin/java
  android home       -            undefined

iOS
  xcode              9.2


The error:

<img width="601" alt="screen shot 2018-02-03 at 23 23 32" src="https://user-images.githubusercontent.com/202020/35773426-621995a4-0939-11e8-9793-01e09a98e36c.png">
