### ISSUE TITLE
[Generated Code][Android] Failing builds due to PushNotification package

### ISSUE THREAD

**Issue by peterlazar1993** [infinitered/ignite#92]
The PushNotification package requires the context and since the generated code does not provide it, the builds are failing.

So in ```MainActivity.java``` of the generated code, it should look like this ```new ReactNativePushNotificationPackage(this)```.

It looks like this is already fixed in the repo, maybe it's not pushed out?
https://github.com/infinitered/ignite/blob/master/ignite-base/android/app/src/main/java/com/rnbase/MainActivity.java#L42

**Comment by GantMan** [comment]
Hey @peterlazar1993 

So, the repo doesn't clone the base, but uses the files inside base to patch up a fresh RN install.   We utilize rnpm to do the patching for specific dependencies.

So if I understand what you're saying, when a brand new RN project comes down, and rnpm is run, it doesn't add the necessary code to MainActivity.java.

@markrickert - you helped us get this installed, can you weigh in?

Plans for moving forward:
option1 - Remove push notifications from ignite
option2 - Add an extra part of the script that copies in that line (and any other extraneous lines) that packages may miss.

Personally, we need option2, so we're going to need a "Find this line of code, and then insert here" function written.   I'm happy to add this should we go with option 2.   @fvonhoven - and @kevinvangelder  this is something we can pair on to get you guys dealing with the generator.

**Comment by nonotest** [comment]
Hello,

I encountered the same kind of issues about two weeks ago with android.
If it can help, this was the final MainActivity.java

````
package com.xxx;

import com.facebook.react.ReactActivity;
import com.oblador.vectoricons.VectorIconsPackage;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import com.i18n.reactnativei18n.ReactNativeI18n;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import android.content.Intent; // <--- Import Intent


import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {
     private ReactNativePushNotificationPackage mReactNativePushNotificationPackage; // <------ Add Package Variable

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "xxx";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
	mReactNativePushNotificationPackage = new ReactNativePushNotificationPackage(this); // <------ Initialize the Package

        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new VectorIconsPackage(),
            new ReactNativeI18n(),
	    mReactNativePushNotificationPackage
        );
    }

    @Override
    protected void onNewIntent (Intent intent) {
	super.onNewIntent(intent);
        mReactNativePushNotificationPackage.newIntent(intent);
    }

}
````

**Comment by GantMan** [comment]
I'm going to have a discussion with the good people who made `rnpm` tomorrow.   If I can fix the above, I will.   If not, we're going to remove push notifications from the default ignite project.

**Comment by GantMan** [comment]
https://github.com/rnpm/rnpm/blob/master/src/config/android/index.js#L107

https://github.com/zo0r/react-native-push-notification/pull/75

**Comment by GantMan** [comment]
Just pointed master at my branch, this works now.  Might take a moment to also add the permissions.

**Comment by GantMan** [comment]
https://github.com/infinitered/ignite/releases/tag/0.2.4
