### ISSUE TITLE
What's with Codacy?

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#924]
I noticed that our codacy badge dropped from an A to B.

I don't even know what codacy is... so i clicked it.

It proceeded to tell me a bunch of problems which:

* were in conflict with `standard` js
* couldn't understand the backtick strings in javascript
* and had issues with the es3 code we wrote for to be compatible with node 4
* compatibility warnings against browsers (we're a CLI)
* we scored a 100% on security but we allow people to `context.system.run('rm -rf')`

I see it as low value as-is. 

Maybe we can configure what rules we want?  

@GantMan & @jamonholmgren - thoughts?

**Comment by jamonholmgren** [comment]
@skellock I'd recommend we remove Codacy. We're in a pretty good spot with our linter already. I understand wanting to keep an eye on code complexity but we can do that as we review pull requests.

**Comment by jamonholmgren** [comment]
@skellock Actually, I'd like to keep Codacy, but adjust the rules to be more standard-compliant.

**Comment by jamonholmgren** [comment]
@GantMan If you can give me access to Codacy, I'll do this.

**Comment by skellock** [comment]
We already have a linter doing this job.

I believe it's just noise.  It takes a perfectly fine PR and subtracts confidence.

https://www.codacy.com/app/jamonholmgren/ignite/pullRequest?prid=636248

**Comment by jamonholmgren** [comment]
I removed the hook @skellock . Someone else can remove the README badge if they're feeling ambitious.
