### ISSUE TITLE
YellowBox

### ISSUE THREAD

**Issue by fvonhoven** [infinitered/ignite#93]
YellowBox is not tied to `DebugSettings`
- [x] Issue does not already exist
- Identify exactly what aspect your issue is about
  - [x] ignite base application
  - [ ] ignite the cli
  - [ ] ignite generated code

**Comment by GantMan** [comment]
https://github.com/infinitered/trackops-mobile/blob/master/App/Root.js#L106

**Comment by GantMan** [comment]
closed via #95
