### ISSUE TITLE
ignite doctor --bug should work

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#932]
In [the docs](https://github.com/infinitered/ignite/blob/1c677e1e53b6de27a4c9386e5aa2c6a980fe8071/docs/quick-start/ignite-commands.md#doctor), we mention `ignite doctor --bug` which ostensibly should open a browser with an Ignite issue ready to go and the results of `ignite doctor` pre-filled.

I'm not sure where this idea came from, but it's a good one. We should implement it.

**Comment by skellock** [comment]
I mentioned it in passing to @codeithuman and the bastard wrote it down!

**Comment by jamonholmgren** [comment]
Rethinking this, I think it would be a good idea to have this command be `ignite issue`. We should also ask if it's a problem with Bowser or the CLI and then file the issue with the appropriate repo.
