### ISSUE TITLE
How to properly access user access token from redux store and send it as a header?

### ISSUE THREAD

**Issue by aemdy** [infinitered/ignite#933]
I am using a boilerplate generated by Ignite to start my React Native app. Right now I'm facing the following situation and not sure how to properly solve it.

Flow:
1. user logins through facebook
2. gains access token
3. I'm sending it though API to backend to gain backend access token
4. token is saved to redux store.

From now on, that token needs to be sent with every subsequent user request. I feel that it needs to be added to default API created in `App/Sagas/index.js`, but at that point I don't have access to store.

**Comment by jamonholmgren** [comment]
Hey @aemdy, thanks for using Ignite! Join us in http://community.infinite.red in the #ignite channel and ask there, if you don't mind. If it makes sense to make a change to the boilerplate, file an issue over at https://github.com/infinitered/ignite-ir-boilerplate-2016, and we'll make it happen -- or better yet, push a PR over to us there!
