### ISSUE TITLE
Upgrading from beta.2 to beta.7 fails

### ISSUE THREAD

**Issue by orozcojair** [infinitered/ignite#935]
This afternoon I tried to upgrade from ignite beta.2 to beta.7 by running both methods

`npm i -g ignite-cli@2.0.0-beta.7` and `ignite add ignite-ir-2016` 

after processes were complete, running `ignite doctor` would fail and present me with this 

![2017-03-22_2227](https://cloud.githubusercontent.com/assets/983866/24236006/328095b2-0f5d-11e7-842e-30eb5bc55530.png)

just for reference I then installed beta.6 and it is working properly.

My machine is a windows 8 with node 7.7 and npm 4.3, processor intel i7 with 8 cores. 

Thank you

**Comment by skellock** [comment]
`yarn` should be optional.  we broke something.  as a work around for now, `npm i -g yarn`.

**Comment by orozcojair** [comment]
confirmed that installing yarn is a legitimate work-around

**Comment by aarjithn** [comment]
Tracking this in https://github.com/infinitered/ignite/issues/949
