### ISSUE TITLE
Using custom boilerplate fails depending on CWD

### ISSUE THREAD

**Issue by FruitieX** [infinitered/ignite#936]
Hi! Great job on Ignite 2. :)

I'm developing a custom boilerplate, and found some strange behavior when testing the boilerplate out:

```
$ cd ~/src/ignite-boilerplate
$ npm link

$ cd ~/src
$ export IGNITE_PLUGIN_PATH=~/.npm-packages/lib/node_modules
$ ignite new MyApp --boilerplate ignite-boilerplate
...
✖ ignite-boilerplate does not have a boilerplate.js
```

But this works:
```
# Change dir to home instead of ~/src
$ cd
$ export IGNITE_PLUGIN_PATH=~/.npm-packages/lib/node_modules
$ ignite new MyApp --boilerplate ignite-boilerplate
```

This also fails:
```
$ mkdir ~/tmp
$ cd ~/tmp
$ export IGNITE_PLUGIN_PATH=~/.npm-packages/lib/node_modules
$ ignite new MyApp --boilerplate ignite-boilerplate
...
✖ ignite-boilerplate does not have a boilerplate.js
```

Really mysterious how it doesn't work if I'm in a subdirectory under home. Any ideas and are you able to reproduce?

**Comment by skellock** [comment]
Woah.  That's weird.  It's like it's not picking up the right path.  But even that doesn't make sense with your 3rd scenario.

One thing you can do is type `--debug` and it'll spit out a bit more info.  

Let's say your making your new boilerplate in `~/src/ignite-fruitiex-boilerplate`.  You would `export IGNITE_PLUGIN_PATH=/Users/fruitiex/src`.  I'd wouldn't rely on the the `~` expansion (just to rule that out).

Then from `~/tmp`, i'd expect you could do `ignite new GoTime -b fruitiex-boilerplate`.

**Comment by FruitieX** [comment]
Using `export IGNITE_PLUGIN_PATH=/Users/fruitiex/src` works. Odd, I was sure I had tried that as well. Closing issue.

**Comment by skellock** [comment]
Yay!  If you ever experience that again, please lemme know.
