### ISSUE TITLE
where to find boilerplates?

### ISSUE THREAD

**Issue by tudinger** [infinitered/ignite#943]
Please just tell me where to find boilerplates list......

**Comment by GantMan** [comment]
Right now there are only 2.

The one for our tech stack from 2016, and the new one. 

We'll continue to modify `ignite-ir-next` and stamp "stable versions" of it in the readme.

https://github.com/infinitered/ignite-ir-next

We should probably add this to the the ignite readme.

**Comment by jamonholmgren** [comment]
There are some third party boilerplates in progress as well. We'll add them to our docs as they're ready to use (or close).

**Comment by kevinvangelder** [comment]
@tudinger In case you haven't heard (while we're working on an official list of boilerplates) NativeBase recently launched an Ignite boilerplate. https://blog.nativebase.io/nativebase-with-ignite-57cb72c63ff3

**Comment by robinheinze** [comment]
This can now be found at https://github.com/infinitered/ignite/blob/master/BOILERPLATES.md (it's also linked from the README).
