### ISSUE TITLE
The screen generator not work well

### ISSUE THREAD

**Issue by Den368** [infinitered/ignite#944]
**What's going on?**
`ignite generate screen something` create the files `somethingScreen` in Containers and `somethingScreenStyle`, however, the import of the style by default is:
`// Styles
import styles from './Styles/somethingStyle'` as you can see the file name is different.
I know it's not a big deal to rename the file or the import but this thing not happened to me in Ignite 1

---
**Steps to reproduce**
1. Install fresh installation of Ignite 2.
2. Run `ignite generate screen something`
3. Run `react-native run-android`
4. Import Error
---
`ignite doctor` results:

**Comment by GantMan** [comment]
hiya, your ignite doctor results aren't showing.  Please re-run and post those.

**Comment by GantMan** [comment]
Also, I think this might be fixed in `ir-next`, would you like to give that a try?

`igntie add ir-next` and then try that screen generator.

**Comment by Den368** [comment]
Thank you for the great advice, this fixed the problem.
However, this option should be by default as it is in Ignite 1.

**Comment by GantMan** [comment]
We will fix.   Just awaiting our next stable release.
