### ISSUE TITLE
Unrecognized 'run-android', can't install basic example

### ISSUE THREAD

**Issue by MyTotoro** [infinitered/ignite#945]
System
  platform           darwin
  arch               x64
  cpu                4 cores                                  Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
  directory          /Users/Kevin/Documents/MyIgniteProject

JavaScript
  node               7.7.4        /usr/local/bin/node
  npm                4.1.2        /usr/local/bin/npm
  yarn               0.21.3       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0-beta.8   /usr/local/bin/ignite

Android
  java               1.8.0_121    /usr/bin/java
  android home       -            /Users/MyTotoro/Library/Android/sdk

iOS
  xcode              8.2.1

---
I installed the example in the docs for Ignite 2:

`ignite new MyIgniteProject`
`cd MyIgniteProject`
`react-native run-android`

---

`Command `run-android` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.`

I can get the basic react-native working on my computer with 'init' and then run-android, I don't know why it doesn't work inside Ignite

**Comment by jamonholmgren** [comment]
@MyTotoro Did you get this figured out yet? Sorry about the slow response!

**Comment by MyTotoro** [comment]
No worries, I ended up doing a clean install of my mac OS and subsequently node/react etc, so it's working now

the template is great btw, I wish there was more documentation on everything that's used and how it's connected but it's still really nice to see good architecture
