### ISSUE TITLE
Ignite.removeDebugConfig leaves a blank space in DebugConfig.js

### ISSUE THREAD

**Issue by derekgreenberg** [infinitered/ignite#948]
## ignite.removeDebugConfig('useJsonServer') leaves a blank space in DebugConfig.js where it should have removed the key/value pair.

Reviewed this issue with @jamonholmgren. 

---
Steps to reproduce

Generate a new Ignite Plugin

In the const add = async function (context) function, invoke:

`ignite.setDebugConfig('useJsonServer', '__DEV__ && true', true)`

### Look at the modified DebugConfig.js file:

```
export default {
  useJsonServer: __DEV__ && true,
  showDevScreens: __DEV__,
  useFixtures: false,
  ezLogin: false,
  yellowBox: __DEV__,
  reduxLogging: __DEV__,
  includeExamples: __DEV__,
  useReactotron: __DEV__
}
```
In the const remove = async function (context) function, invoke:

`ignite.removeDebugConfig('useJsonServer')`

### Look at the DebugConfig.js file of the ignited project and observe that a blank line remains where the 'useJsonServer' key was removed.

```
export default {

  showDevScreens: __DEV__,
  useFixtures: false,
  ezLogin: false,
  yellowBox: __DEV__,
  reduxLogging: __DEV__,
  includeExamples: __DEV__,
  useReactotron: __DEV__
}
```
---
`ignite doctor` results:

```
System
  platform           darwin
  arch               x64
  cpu                8 cores                            Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  directory          /Users/derekgreenberg/git/ignite

JavaScript
  node               7.7.4        /usr/local/bin/node
  npm                4.1.2        /usr/local/bin/npm
  yarn               0.21.3       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1

Ignite
  ignite             2.0.0-beta.8   /Users/derekgreenberg/.node/bin/ignite

Android
  java               1.8.0_73     /usr/bin/java
  android home       -            /usr/local/opt/android-sdk

iOS
  xcode              8.3
```

**Comment by jamonholmgren** [comment]
When I build out https://github.com/infinitered/gluegun/issues/155 we can switch to the new patching extension and it should fix this.

**Comment by skellock** [comment]
New patching system is ready to go if you want to pick this back up.

**Comment by jamonholmgren** [comment]
`setDebugConfig` is not used in Bowser. Since we aren't officially supporting Andross anymore, this method should be deprecated, and thus I will close this issue.
