### ISSUE TITLE
Error: not found: yarn

### ISSUE THREAD

**Issue by GiacomoK** [infinitered/ignite#949]
Hello,
On Win7 I followed the guide to install ignite, and I did it, but when I try to create a new project I get this error:

Error: not found: yarn

and

(node:5520) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: not found: yarn

Should I install yarn? It does not say anywhere.

**Comment by lbaker2** [comment]
Yeah. Yarn dependency is missing from the documentation, but you can get it from [here](https://yarnpkg.com/lang/en/docs/install/#windows-tab). You may run into other problems after installing Yarn, but those can be filed in separate issues.

**Comment by lbaker2** [comment]
#951 was submitted in response to this issue.

**Comment by jamonholmgren** [comment]
Should we really be requiring `yarn`? Or just detecting it's not installed and instead use `npm`?

**Comment by aarjithn** [comment]
It would be great if yarn is not a dependency. yarn has a dependency on node v7, which ignite-cli is not compatible with as it requires v7.6+. So we end up installing both yarn and a node version to use ignite.

**Comment by skellock** [comment]
Yarn doesn't have a hard node 7 dependency, ignite does though.

This is a bug for sure. yarn was intended to be a nice-to-have. just need to track down where this is failing. Stack traces will help with this.  Is this just happening on windows?  Does it still happen if you ad `--npm` to your command?

**Comment by GiacomoK** [comment]
What command to you mean? To create project? Something like this:

ignite new PizzaApp --npm

**Comment by skellock** [comment]
Yes.  I put `--npm` because I was having some problems with `yarn` early on.  I wanted a way to test the `npm` path without uninstalling `yarn`.

**Comment by GiacomoK** [comment]
Tried with --npm option (without yarn installed) but I got the same error.

**Comment by skellock** [comment]
How about if you type: `ignite new Without --no-boilerplate --npm`?

**Comment by GiacomoK** [comment]
it worked, but it did not install other packages

**Comment by skellock** [comment]
Right.  `--no-boilerplate` skips adding the boilerplate.  Sounds like the problem might be in the `add` command.

**Comment by skellock** [comment]
I think what's happening here  is ... when we shell out, node is giving precendence to the `node_modules/.bin/react-native` executable instead of the global one on the path.

**Comment by JohnnyTwoShoes** [comment]
ignite is a very poor written piece of software. after a day wasting time installing it, still not working

**Comment by GantMan** [comment]
Hey @JohnnyTwoShoes 
I'm always sad to see someone lose time with anything we work with, rather than gain.   Lots of people are able to use Ignite with no problems.

If you'd like to [join our community slack](https://infiniteredcommunity.herokuapp.com/), and then DM me, I can do a screen share with you to get you up and running.
