### ISSUE TITLE
ignite generate component shouldn't override already created component

### ISSUE THREAD

**Issue by chlela** [infinitered/ignite#950]
What's going on?
Generating a component shouldn't override an already existing component with same name.  You can potentially warn the user or ask for confirmation
---
Steps to reproduce
* issue command: ignite generate component testComponent
* Make changes to testComponent
* re-issue command: ignite generate component testComponent

Changes are overwritten

**Comment by jamonholmgren** [comment]
I agree. Should be straightforward.

**Comment by robinheinze** [comment]
Addressing this with https://github.com/infinitered/ignite-ir-boilerplate-2016/pull/32
