### ISSUE TITLE
Project homepage problem

### ISSUE THREAD

**Issue by pravosud** [infinitered/ignite#954]
Hi there, something went wrong on your project homepage, check it out:

![0](https://cloud.githubusercontent.com/assets/5364762/24601365/0830438e-1872-11e7-97ab-3d7e8261d653.png)

**Comment by GantMan** [comment]
![logo](https://cloud.githubusercontent.com/assets/997157/24613409/d75b99c6-184d-11e7-9053-2334a76ac20b.gif)
Works for me in incognito mode.  What browser are you using?  Plz share your env.

**Comment by pravosud** [comment]
I tested it 5 days ago on two different laptops in Chrome browser.
Now all is fine :)
