### ISSUE TITLE
pure React.js plans?

### ISSUE THREAD

**Issue by MM-Psiiirus** [infinitered/ignite#955]
Hiya,
do you have any plans to bringt your boilerplating to normal react.js projects too?
I would love to e.g have a standard "boilerplating-way" to create reducers, actions and components inside react.js app. It's kind of handy if u work with several devs inside a big growing project.

**Comment by GantMan** [comment]
Though we currently do not have an ambition to build a React.js version, we are hoping to extend to as many platforms beyond React Native as possible.   This means 2 things.

We'd love for someone to use our templates/boilerplates to give their own go on web.   We'd support them as much as we can.

Whenever React Native and React.js do a bit of merging and eventually web is just a platform of React, we'll do our best to support it (though I'm sure that's deep in the future).
