### ISSUE TITLE
Support React Native 0.44.0

### ISSUE THREAD

**Issue by skellock** [infinitered/ignite#957]
React Native 0.43.0 is now available.

Also, let's [remove ignite depending](https://github.com/infinitered/ignite/blob/master/src/extensions/reactNative.js#L6) on a specific version and move that off to the boilerplates if they care.

**Comment by MyTotoro** [comment]
so I just ncu updated and it broke everything... does ignite generally break when updating react/react-native?

**Comment by skellock** [comment]
> so I just ncu updated and it broke everything

What is ncu? What errors are you seeing?

> does ignite generally break when updating react/react-native?

I'd say not often.  It depends on React Native's changes though.  RN is pretty good with letting us know what the breaking changes are.

**Comment by MyTotoro** [comment]
https://www.npmjs.com/package/npm-check-updates

I just did a fresh install of an ignite template and updated React and RN (it broke only when I updated RN, when I updated React to 15.5.2, it was fine)

![image](https://cloud.githubusercontent.com/assets/3621921/24825109/c04996c0-1be5-11e7-824d-d1a5ccf8a18a.png)

Ignore the change in RootContainer, this is the error I'm seeing

![screenshot_20170407-230103](https://cloud.githubusercontent.com/assets/3621921/24825146/b5e712e2-1be6-11e7-8c93-01baca9d56d3.png)

**Comment by skellock** [comment]
I googled and this came up: https://github.com/facebook/react-native/issues/13291 .  Related to your issue?

**Comment by MyTotoro** [comment]
no luck, I've tried playing with different permutations - I think I'll just stick with the original 15.4.1 and .42

**Comment by kevinvangelder** [comment]
React Native 0.43 is using React 16.0.0-alpha which isn't really ready for use in React Native.

**Comment by skellock** [comment]
It's ready. There's just warnings out the wazoo.  :(  Wasn't their best release.  I say we wait for 44 =) =)

**Comment by skellock** [comment]
44 is here.  It still uses 16.0.0-alpha.6.  Hilarity continues to ensue.  Recommend waiting for 0.45.0.

**Comment by jamonholmgren** [comment]
Okay, thanks @skellock. Opened a related issue in #1013.
