### ISSUE TITLE
Ignite checks are too rough on react-native-cli

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite#960]
When I add an ignite command to `yarn run` it fails on detecting `react-native-cli`

![image](https://cloud.githubusercontent.com/assets/997157/24632324/57f43cce-1889-11e7-89db-1a5f1a23f9ef.png)

Typing the command this runs will work.  It's just the script housing that makes a false positive.

**Comment by skellock** [comment]
This the same as #949.  Let's track it there.

**Comment by jamonholmgren** [comment]
Related to #940 too.
