### ISSUE TITLE
Cant install the generators plugin 

### ISSUE THREAD

**Issue by elidiazgt** [infinitered/ignite#961]
---
What's going on?
Cant install and use the generators plugin while attach ignite to a create react native app

---
Steps to reproduce
create-react-native-app test
cd test
ignite attach
ignite add basic-generators

result:
DEPRECATION WARNING: Heads up! `index.js` in plugins is deprecated. Please use `plugin.js` instead!
DEPRECATION_WARNING: Heads up! `ignite.addScreenExamples` is deprecated. Please use `ignite.addPluginScreenExamples` instead.

---
`ignite doctor` results:
System
  platform           darwin
  arch               x64
  cpu                4 cores                                                                                       Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  directory          /Users/test

JavaScript
  node               7.6.0        /usr/local/bin/node
  npm                4.1.2        /usr/local/bin/npm
  yarn               0.21.3       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.41.2

**Comment by skellock** [comment]
Basic generators are no longer standalone.  They are rolled into the boilerplate.  Did you find this in documentation somewhere?  We should remove it if that's the case. =)

**Comment by jhblacklock** [comment]
Same issue: located here.

https://www.npmjs.com/package/ignite-basic-generators

**Comment by skellock** [comment]
That package is now deprecated.  The contents live on inside the boilerplates called `ignite-ir-boilerplate-2016` and `ignite-ir-next`.
