### ISSUE TITLE
Wrong DevScreens/DevTheme relative path when adding listview/sectioned

### ISSUE THREAD

**Issue by cvicens** [infinitered/ignite#966]
---
What's going on?
After adding a listview component as suggested in the video [here](https://youtu.be/lv00UOXxy0g) and later modifying the navigation drawer to subtitute the launcher by the generated screen, I get the following error:

![screen shot 2017-04-10 at 10 37 45](https://cloud.githubusercontent.com/assets/1593244/24853007/d688f868-1dd9-11e7-8479-14d5fe1c3a4e.png)

---
Steps to reproduce

```
$ ignite generate listview TextableSectionedScreen

? What kind of ListView would you like to generate? With Sections
✔︎ App/Containers/TextableSectionedScreen.js
✔︎ App/Containers/Styles/TextableSectionedScreenStyle.js
```

Edit ./App/Navigation/NavigationRouter.js and import the new screen: 

```
import TextableSectionedScreen from '../Containers/TextableSectionedScreen'
```

Modify the line where the launcherScreen is injected to inject our new screen:

```
<Router>
        <Scene key='drawer' component={NavigationDrawer} open={false}>
          <Scene key='drawerChildrenWrapper' navigationBarStyle={Styles.navBar} titleStyle={Styles.title} leftButtonIconStyle={Styles.leftButton} rightButtonTextStyle={Styles.rightButton}>
            <Scene initial key='textableSectionedScreen' component={TextableSectionedScreen} title='TextableSectionedScreen' hideNavBar />
          </Scene>
        </Scene>
      </Router>
```

The error is as
../../../ignite/DevScreens/DevTheme/

../../../../../DevScreens/DevTheme/

---
Solution:
Go to ./App/Containers/Styles/TextableSectionedScreenStyle.js

Error is at line 2:
- It reads: 
``import { ApplicationStyles, Metrics, Colors } from '../../../../../DevScreens/DevTheme/'``
- When it should read:
``import { ApplicationStyles, Metrics, Colors } from '../../../ignite/DevScreens/DevTheme/'``

**Comment by GantMan** [comment]
how old is your app/ignite?   I think this was something that was fixed in the new boilerplate.

Did you use ignite-ir-next?

**Comment by skogman** [comment]
+1

**Comment by jamonholmgren** [comment]
@cvicens Would you mind providing a pull request to both boilerplates?

https://github.com/infinitered/ignite-ir-boilerplate-2016 (default, for now)
https://github.com/infinitered/ignite-ir-next (new boilerplate)

**Comment by Ancinek** [comment]
Having the same issue. Started using (installed) ignite yesterday.
