### ISSUE TITLE
Ignite not logging STATE anymore

### ISSUE THREAD

**Issue by justingosan** [infinitered/ignite#967]
Hi!

I just got back to using ignite once again. I remember in a previous version the BEFORE and AFTER state would be logged into the dev console whenever an action was triggered. Is there any way to turn this back on again?

Thanks!

**Comment by GantMan** [comment]
hey!   No worries, it's still available!  We're just making it an option.
We hope to keep an exhaustive list of options here as they grow:  https://github.com/infinitered/ignite/blob/master/PLUGINS.md

What' you're talking about was `redux-logger` and you should be able to add it back with a simple:
`ignite add redux-logger`

Let me know how it goes!

**Comment by justingosan** [comment]
Thanks for the tip! Got it working :)

Justin

On Mon, 10 Apr 2017 at 8:26 PM Gant Laborde

<
mailto:Gant Laborde <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

hey! No worries, it's still available! We're just making it an option.

We hope to keep an exhaustive list of options here as they grow:
https://github.com/infinitered/ignite/blob/master/PLUGINS.md

What' you're talking about was

redux-logger

and you should be able to add it back with a simple:

ignite add redux-logger

Let me know how it goes!

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/infinitered/ignite/issues/967#issuecomment-292934496
, or

**Comment by Sidhanthsur** [comment]
After doing this I get a R not defined error, since import R from 'ramda' is not included.

**Comment by jamonholmgren** [comment]
@Sidhanthsur You might submit an issue and PR to the `ignite-redux-logger` plugin. :)

**Comment by GantMan** [comment]
as author of that plugin I'd appreciate the PR.  I'm def busy!
