### ISSUE TITLE
can't start new project

### ISSUE THREAD

**Issue by moses5407** [infinitered/ignite#970]
I get "an error occured while installing ignite-r-boilerplate-2016 boilerplate"
Error: Command failed git-commit-m "Initial commit"
Please tell me who you are"

It then sticks on configuring git

On linux ... newest react-native cli

I'll run ignite doctor and post the results back here

**Comment by moses5407** [comment]
System
  platform           linux                                                       
  arch               x64                                                         
  cpu                2 cores      Intel(R) Celeron(R) 2955U @ 1.40GHz  
  directory          /home/nerf                                                  

JavaScript
  node               7.8.0        /usr/local/bin/node  
  npm                4.2.0        /usr/local/bin/npm   
  yarn               0.22.0       /usr/bin/yarn        

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.0.0-beta.8   /usr/local/bin/ignite  

Android
  java               1.8.0_121    /usr/bin/java  
  android home       -            undefined

**Comment by moses5407** [comment]
configuring gitan error occured while installing ignite-ir-boilerplate-2016 boilerplate.
Error: Command failed: git commit -m "Initial commit."

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

**Comment by skellock** [comment]
Sounds like your git isn't configured with your user name.  Can you try running the command again with `--skip-git`?

**Comment by kevinvangelder** [comment]
@moses5407 Looks like you may have made a typo in your command or while copying the error here. `ignite-r-boilerplate-2016` should be `ignite-ir-boilerplate-2016`.

**Comment by OkuraSt** [comment]
Hi, Im having the same error as described by @moses5407, if I follow @skellock suggestion the wizard finishes correctly but im not able to open the files in webstorm.

Git configuration is apparently correct, any ideas?

![image](https://cloud.githubusercontent.com/assets/9710146/25608685/97d6a606-2ee1-11e7-816b-67e6fca2b945.png)

![image](https://cloud.githubusercontent.com/assets/9710146/25608768/e7ee8c4e-2ee1-11e7-9a61-ef4675c162c2.png)

Thank you

**Comment by jamonholmgren** [comment]
@OkuraSt Sorry, just saw this. You mention this:

> im not able to open the files in webstorm

Can you explain?

**Comment by skellock** [comment]
Still an issue with the latest ignite-cli?

**Comment by gzzengwei** [comment]
Hi I have similar issue when creating new projects, I tried on two macbook, same issue. It just takes forever in the 'adding React Native' part

> 🔥 igniting app PizzaApp
> ✔ using the Infinite Red boilerplate v2 (code name 'Andross')
> ⠸ adding React Native 0.42.3 (30 seconds-ish) 

I try to switch from `nvm` to `n`, no luck ..

output of `ignite doctor` :
```
System
  platform           darwin
  arch               x64
  cpu                4 cores                               Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  directory          /Users/wei/projects/PizzaApp

JavaScript
  node               8.1.2        /usr/local/bin/node
  npm                5.0.3        /usr/local/bin/npm
  yarn               0.24.6       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.45.1

Ignite
  ignite             2.0.0-rc.2   /usr/local/bin/ignite

Android
  java               1.8.0_102    /usr/bin/java
  android home       -            undefined

iOS
  xcode              8.0
```

And I also wonder why in `ignite doctor` say my rn version is 0.45.1 and it says `adding React Native 0.42.3` when create new app with cli
