### ISSUE TITLE
Getting error from socket.js when debugging

### ISSUE THREAD

**Issue by genesy** [infinitered/ignite#974]
What's going on?
I initiated an app with the ignite cli, the initial app runs fine on ios simulator but when I debug remotely I get an error from socket.js

![error](http://i.imgur.com/IW1X2ly.png)

---
Steps to reproduce
Initiate app normally
run react-native run-ios
debug in chrome

---
`ignite doctor` results:

System
  platform           darwin
  arch               x64
  cpu                8 cores                         Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  directory          /Users/gene/test

JavaScript
  node               7.9.0        /usr/local/bin/node
  npm                4.5.0        /usr/local/bin/npm
  yarn               0.22.0       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.42.0

Ignite
  ignite             2.0.0-beta.8   /usr/local/bin/ignite

Android
  java               1.8.0_111    /usr/bin/java
  android home       -            undefined

iOS
  xcode              8.1

**Comment by jamonholmgren** [comment]
@genesy I missed this one...did you get it figured out yet?

**Comment by kyawmoehaynes** [comment]
+1. If I use Debug JS Using Chrome, ignite app would just freeze when I press Open Devscreens button.

**Comment by skellock** [comment]
Does turning off the connect statement in ReactotronConfig.js fix it?

**Comment by nonameolsson** [comment]
Yeah, I'm experiencing this also. @skellock Do you get this also, or do you need more info from us?
![screen shot 2017-08-07 at 11 24 53](https://user-images.githubusercontent.com/1493018/29035963-1c321976-7b63-11e7-9f7e-855f905fee8a.png)

**Comment by skellock** [comment]
Looks like something in depths of `socket.io` going bananas while in this mode.  Reactotron uses `socket.io`.  We're replacing that in 2.0.

Work around for now is to not turn on reactotron while chrome debugging.  Sorry for the troubles.

**Comment by kevinvangelder** [comment]
This should be resolved in our newer boilerplates due to Reactotron moving away from socket.io
