### ISSUE TITLE
`ignite new ignite` generates empty `ignite` folder

### ISSUE THREAD

**Issue by markmssd** [infinitered/ignite#975]
Not much of a big issue, but still should be known...

Wanted to give this library a try, and ran `ignite new ignite`... but it always ends up generating an empty `ignite` folder...

`ignite new IgniteApp` works like a charm though. Other than this, keep it rocking!

**Comment by piuccio** [comment]
just had the same problem

**Comment by jamonholmgren** [comment]
We need to add a check after this line of code:

https://github.com/infinitered/ignite/blob/master/src/commands/new.js#L28

```javascript
  // camelCase the project name for user example
  const projectNameCamel = upperFirst(camelCase(projectName))
```

Add a check that looks for `projectNameCamel === 'Ignite'` and then kill the process, warning the user that they can't use Ignite.

Maybe have something silly there for levity, like:

```
Hey...that's my name! Use something other than Ignite for your project name, you big dope.
```

but less dorky

**Comment by markmssd** [comment]
Good job guys! Keep up the good work 💯

**Comment by jamonholmgren** [comment]
@markmssd Thanks! We're making a concerted effort to blow through these smaller issues before Ignite 2.0.0 release.
