### ISSUE TITLE
When igniting a new project...missing screens

### ISSUE THREAD

**Issue by fvonhoven** [infinitered/ignite#978]
---
What's going on?

When igniting a new project, I said yes to dev screens. 
The ListviewExamplesScreens, LoginScreen, and LaunchScreen are there but there is no API testing screen. (See below) 

![image](https://cloud.githubusercontent.com/assets/10098988/25110063/ef937086-23a6-11e7-86cc-fdd1973db5ab.png)

---
Steps to reproduce
* ignite a new project - add everything but I18n
* See Video ⬇️ 
https://drive.google.com/open?id=0BzlXehZt36H0b2ZuNVJzYzhuMFE
---
`ignite doctor` results:
![image](https://cloud.githubusercontent.com/assets/10098988/25110122/3b40ea4a-23a7-11e7-9bd1-98f34066d3cf.png)

**Comment by GantMan** [comment]
API testing screen should be in `/ignite/DevScreens` folder

**Comment by GantMan** [comment]
![image](https://cloud.githubusercontent.com/assets/997157/25110436/9d08ae8c-23a9-11e7-8822-d39958a02939.png)
^ that was your problem.  We need to find out why your add permission failed.  You're on ignite beta 6, can you upgrade to ignite beta 8?
