### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Spacelapp** [infinitered/ignite#979]
When I try to change the name of a Saga/Redux (LoginSagas -> OAuthSagas & LoginRedux -> OAuthRedux) I always got the error:
`at takeLatestHelper 
 TypeError: Cannot read property 'name' of undefined`
Of course I renamed all necessary variables and files...

**Comment by GantMan** [comment]
Did you check the index.js in the folder as well?  Which has references?

Also, make sure you turn off rehydrate in the redux rehydrate config in Config folder.  It might be loading old state with no place to put it.

**Comment by jamonholmgren** [comment]
@Spacelapp Did you get this figured out?

**Comment by jamonholmgren** [comment]
Going to close as abandoned, but if you are still having trouble with this I'll reopen. Thanks!

**Comment by Un3qual** [comment]
@Spacelapp Did you ever figure this out?

**Comment by tmaly1980** [comment]
I had the SAME issue.... took me a few minutes but the undefined refers to the worker in takeLatest (ie the saga function itself). it's being passed undefined, which likely means a non-existent function is being imported from the saga. I double checked what was referenced in Sagas/index.js and what was exported in my saga file. In my case, it was a typo.

**Comment by samselfridge** [comment]
Just had this issue - my problem was that I wasn't importing my saga function properly (also typo), but the 'name undefined' was the only error it was throwing.
