### ISSUE TITLE
Could not get BatchedBridge, make sure your bundle is packaged correctly

### ISSUE THREAD

**Issue by chapeljuice** [infinitered/ignite#984]
I ran through the Getting Started instructions, and then after I ran react-native run-android I'm getting an error.

---
What's going on?
Getting error, can't see the app.
<img width="574" alt="screen shot 2017-04-20 at 3 39 30 pm" src="https://cloud.githubusercontent.com/assets/862642/25255534/0283bc4c-25e0-11e7-92b6-6e4d95a5f430.png">

---
Steps to reproduce 
Run through "Getting Started" instructions.

---
`ignite doctor` results:
chaps 👻  TestApp $ ignite doctor
System
  platform           darwin                                                                                       
  arch               x64                                                                                          
  cpu                8 cores                                 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz  
  directory          /Users/chapel/Documents/repos/TestApp                                                        

JavaScript
  node               7.9.0        /usr/local/bin/node  
  npm                4.2.0        /usr/local/bin/npm   
  yarn               0.23.2       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       
  app rn version     0.42.0      

Ignite
  ignite             2.0.0-beta.8   /usr/local/bin/ignite  

Android
  java               1.8.0_121    /usr/bin/java                      
  android home       -            /Users/chapel/Library/Android/sdk  

iOS
  xcode              8.3

**Comment by skellock** [comment]
Do you get the same issue if you run `ignite new MyDifferentApp -b ir-next` ?

**Comment by chapeljuice** [comment]
That totally worked ... why? Thanks!

**Comment by skellock** [comment]
Because the default boilerplate for ignite `ignite-ir-boilerplate-2016` uses `react-native-router-flux`.  And yesterday RNRF cut a build that blows things up.   We rolled back the version, so if you ran your old command again, it might work (hopefully it does!!!).

The `ir-next` boilerplate uses `react-navigation`, which is why that works.  And where we're heading.

Sorry for the hiccups!

**Comment by chapeljuice** [comment]
No worries, thanks for the help and the explanation! 😃
