### ISSUE TITLE
Relative path in boilerplate flag broken

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#985]
![image](https://cloud.githubusercontent.com/assets/1479215/25286426/8baa672c-2672-11e7-8de7-53050d9b50ed.png)

```
✖ ignite-../plugins/ignite-ir-next is not available on npm.
```

Should be a straightforward bugfix -- expand relative paths in the `-b` and `--boilerplate` flags.

**Comment by skellock** [comment]
We need to also pass along the path to the ignite command that adds the boilerplate to itself.

https://github.com/infinitered/ignite-ir-next/blob/master/boilerplate.js#L207

**Comment by jamonholmgren** [comment]
Path in the ignite command that adds the boilerplate to itself is done in https://github.com/infinitered/ignite-ir-next/issues/32. This should be an easy fix.
