### ISSUE TITLE
Generators should take a custom path

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite#996]
Ref #994, #479, and https://github.com/infinitered/ignite-ir-next/pull/27.

Pretty straightforward, we want to be able to do this:

```
$ ignite generate component MyComponent --path=App/Custom/Path
```

We'll need to pass through the option to the underlying generator and hopefully they respect the custom path.

**Comment by baldursson** [comment]
As I see it, the custom path argument may be a bit overkill. Like in Rails' generators, if you just put a slash in the name, it will be considered a subpath:

`ignite generate component Custom/Path/MyComponent`

That would put the `MyComponent` into `App/Custom/Path`

I you put a slash in the name now though, it's just ignored which would result in this:
`App/CustomPathMyComponent`

**Comment by jamonholmgren** [comment]
I like how you think @baldursson. Want to take a crack at it?

**Comment by baldursson** [comment]
Sure @jamonholmgren! I will try to make time for it

**Comment by jamonholmgren** [comment]
@baldursson Hey, it's been a while! Is this something you'd like to try sometime? I could see it being quite useful.

**Comment by jamonholmgren** [comment]
This is more of a Bowser thing, so closing now.

**Comment by scinfu** [comment]
has this feature been implemented?
