### ISSUE TITLE
ignite generated screen do not have the good StyleSheet path 

### ISSUE THREAD

**Issue by didierbrun** [infinitered/ignite#999]
Hello inifinite team !

It seems that when you create a screen via : 

ignite generate screen Profile 

The stylesheet file generated is _Styles/ProfileScreenStyle.js_, however, the "import" in the ProfileScreen.js is 
`import styles from './Styles/ProfileScreen'`

it should be : 
`import styles from './Styles/ProfileScreenStyle'`

That is, not very important but I preferred to report it :)

Ignite doctor 
```
System
  platform           darwin                                                                                                  
  arch               x64                                                                                                     
  cpu                12 cores                                           Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz  
  directory          /Projects/BigBoss/Internal/React/DiorDemo/server                                                        

JavaScript
  node               7.9.0        /usr/local/bin/node  
  npm                4.2.0        /usr/local/bin/npm   
  yarn               0.23.2       /usr/local/bin/yarn  

React Native
  react-native-cli   2.0.1       

Ignite
  ignite             2.0.0-beta.8   /usr/local/bin/ignite  

Android
  java               1.8.0_131    /usr/bin/java                 
  android home       -            /usr/local/share/android-sdk  

iOS
  xcode              8.2.1       
```

**Comment by GantMan** [comment]
I think we just had that fixed, but haven't released.  @fvonhoven -isnt' that what you fixed?

**Comment by fvonhoven** [comment]
@GantMan correct, but only in the 2016 boilerplate, I haven't checked in the `next` boilerplate

**Comment by jamonholmgren** [comment]
Thanks for reporting @didierbrun , we'll try to get that integrated into `ir-next` and released on both soon.

**Comment by fvonhoven** [comment]
Similar issue addressed in `next` with [this](https://github.com/infinitered/ignite-ir-next/pull/29)

**Comment by skellock** [comment]
Fixed with the latest boilerplates.
